rgw: Add External Authentication for S3
ceph/ceph pull request #34093
Opened 2020-03-20 18:16 UTC by clwluvw

Ceph external authenticators like Keystone, LDAP, STS, ... doesn't support all RGWUser features and force users to use Keystone, ... servers and can't use their own authentication servers. With this PR anyone can have their own authentication server (Organizations most have) and Ceph Object Storage (S3) can authenticate users with their own authentication server based on needed APIs. Now Remote Users can have SubUser, Permission, is_admin, ... when they come from the server.

Signed-off-by: Seena Fallah <seeenafallah@gmail.com>

2020-03-20 21:25 UTC, mattbenjamin commented
Well, currently remote authentication works fine, but creates a shadow user--not in keystone, but in the RGW database.  That can then be a system user, have caps, and so on.  I will read further.

2020-03-20 21:30 UTC, clwluvw commented
@mattbenjamin Really thanks for your attention. Yes in this scenario we have a shadow of external users in RGW database. The main point here is to support SubUser and Permissions and admin users that still are shadows and it acts like Keystone.

2020-03-21 14:47 UTC, clwluvw commented
jenkins render docs

2020-03-23 14:07 UTC, clwluvw commented
Hi @mattbenjamin, Do you have any idea why docs didn't render from 2 days ago?

2020-03-24 17:35 UTC, clwluvw commented
@mdw-at-linuxbox It's now ready for your review :)

2020-03-30 17:34 UTC, clwluvw commented
@mattbenjamin Hi Matt. Can someone else review this PR?

2020-03-30 18:02 UTC, cbodley commented
why is it necessary or useful to invent a new authentication protocol here?

2020-03-30 18:03 UTC, clwluvw commented
> why is it necessary or useful to invent a new authentication protocol here?

@cbodley To support subuser in Remote Authentications.

2020-03-30 20:02 UTC, cbodley commented
> @cbodley To support subuser and other RGWUser features in Remote Authentication.

these are radosgw internals - it's not clear why they should be involved in remote authentication

> And also anyone have it's own authentication server (Organizations most have) by implementing these APIs.

most organizations don't write a custom json endpoint to handle their authentication, they rely on integration with existing services though keystone, ldap, or sts

2020-03-30 20:05 UTC, clwluvw commented
> > @cbodley To support subuser and other RGWUser features in Remote Authentication.
> 
> these are radosgw internals - it's not clear why they should be involved in remote authentication

When a user authenticated with Remote authenticators as @mattbenjamin said there will be a shadow in RGW database of that user. So why these users can't have subuser?

2020-03-30 20:17 UTC, cbodley commented
these shadow users are created in `rgw::auth::RemoteApplier::create_account()` to map a remote account to a local RGWUserInfo. this is a 1-to-1 mapping, so there's no reason to use subusers

2020-03-30 20:24 UTC, clwluvw commented
> these shadow users are created in `rgw::auth::RemoteApplier::create_account()` to map a remote account to a local RGWUserInfo. this is a 1-to-1 mapping, so there's no reason to use subusers

@cbodley Sorry but I don't get why there is no way we can have subuser. You said there is 1-to-1 mapping with a remote account and local RGWUserInfo and RGWUserInfo keeps subusers too.
As I get from remote authentication process we will get the AuthInfo from remote authenticator and see if we have already that user in our database. If there wan't there we will create it with `rgw::auth::RemoteApplier::create_account()` in RGW database and RGW database support subuser. So why we can't have subuser there? Am I wrong?

2020-03-30 20:26 UTC, clwluvw commented
> most organizations don't write a custom json endpoint to handle their authentication, they rely on integration with existing services though keystone, ldap, or sts

@cbodley Some organizations have workspace and want a feature like AWS that make it possible to add users to your AWS account and get access to them like a subuser here. Keystone, ldap, sts, (RemoteApplier) doesn't support subuser so we can support this feature with this PR.

2020-03-30 20:50 UTC, clwluvw commented
>> most organizations don't write a custom json endpoint to handle their authentication, they rely on integration with existing services though keystone, ldap, or sts

> @cbodley Some organizations have workspaces and want a feature like AWS that make it possible to add users to your AWS account and get access to them like a subuser here. The usage can be calculate for workspace user and other management features. So if organization have multiple workspace (workspaces can have many users in them and each user in workspace has specific access to the workspaces buckets (READ, WRITE, FULL-CONTROL)) it can be done with this feature.
Keystone, ldap, sts, (RemoteApplier) doesn't support subuser so we can support this feature with this PR.

@cbodley And also if we wan't to give storage as a service with Ceph it will be a need of this type of workspaces like you see in digitalocean that use Ceph there is also a need for this feature https://ideas.digitalocean.com/ideas/DO-I-320

2020-04-02 17:38 UTC, clwluvw commented
@cbodley What's your idea about it?

2020-04-06 15:15 UTC, clwluvw commented
Ping @cbodley

2020-04-16 14:31 UTC, clwluvw commented
Ping @cbodley

2020-04-16 17:59 UTC, cbodley commented
we are interested in account-level features and have discussed some design ideas there. but the user/subuser relationship isn't the right fit for this. the subuser concept was added to support swift, and has never been well-defined for use with s3. features like bucket listing, quota enforcement, and acls are all done at the user-level, and have no interaction with subusers

2020-04-16 18:07 UTC, clwluvw commented
> we are interested in account-level features and have discussed some design ideas there. but the user/subuser relationship isn't the right fit for this. the subuser concept was added to support swift, and has never been well-defined for use with s3. features like bucket listing, quota enforcement, and acls are all done at the user-level, and have no interaction with subusers

Good and really waiting for the implementation of that design but if we use subuser feature temporary until that design why isn't it well in S3? I know these feature don't support subuser. for example we can't set user quota for subuser. But for temporary solution until that design came on can't we support subuser for this purpose? I have also implement bucket acl for subuser here https://github.com/ceph/ceph/pull/34486. I know for example user acl isn't implement again but now I think it would be good to have minimum support of this concept with subuser.

2020-04-16 18:32 UTC, clwluvw commented
> we are interested in account-level features and have discussed some design ideas there. but the user/subuser relationship isn't the right fit for this. the subuser concept was added to support swift, and has never been well-defined for use with s3. features like bucket listing, quota enforcement, and acls are all done at the user-level, and have no interaction with subusers

@cbodley Good and really waiting for the implementation of that design but what if we use subuser feature temporary until that design? I know these features doesn't support subuser. for example we can't set user quota for subuser. But for short term solution until that design came, can't we support subuser for this purpose? I have also implement bucket acl for subuser here #34486 and also we have support on subuser in bucket policy. I know for example user acl isn't implement again but now I think it would be good to have minimum support of this concept with subuser. Isn't that?

2020-04-17 14:10 UTC, cbodley commented
i don't think it's reasonable to add new subuser functionality that can only be used with some new custom authentication mechanism. i don't think it's reasonable to add a new authentication protocol in the first place

2020-04-17 14:14 UTC, clwluvw commented
> i don't think it's reasonable to add new subuser functionality that can only be used with some new custom authentication mechanism. i don't think it's reasonable to add a new authentication protocol in the first place

@cbodley I understand your concerns here with adding new protocol right now but are you okay with starting with these type or PRs like #34486 and #33762 or maybe #33210 so it would get some points and then we can check if it's still reasonable to have this protocol or not?

2020-04-17 14:29 UTC, cbodley commented
i would not be in favor of merging subuser changes that we have no way of exercising or testing, no

2020-04-17 14:31 UTC, clwluvw commented
> i would not be in favor of merging subuser changes that we have no way of exercising or testing, no

What about adding tests or qa?

2020-04-17 14:49 UTC, clwluvw commented
> i would not be in favor of merging subuser changes that we have no way of exercising or testing, no

@cbodley Can't we cover this by adding tests or qa?

2020-04-17 15:42 UTC, cbodley commented
but how do you test s3 subuser features when you can't issue s3 requests as a subuser?

2020-04-17 15:44 UTC, clwluvw commented
> but how do you test s3 subuser features when you can't issue s3 requests as a subuser?

@cbodley What do you mean about I can't issue S3 requests with subuser? As I test in nautilus subusers can have s3 keys and can also send S3 requests.

2020-04-20 15:50 UTC, cbodley commented
> As I test in nautilus subusers can have s3 keys

okay, thanks. i don't think our team has much experience with subusers, which explains the gaps in functionality and testing. if you're willing to work on test coverage, i'd love to see these gaps filled in

2020-07-03 14:10 UTC, clwluvw commented
I have added qa tests here #35661

2020-09-02 09:23 UTC, clwluvw commented
unstale please

2020-11-01 19:51 UTC, clwluvw commented
Unstale please

2020-12-31 21:16 UTC, clwluvw commented
unstale please

2021-06-21 10:41 UTC, frittentheke commented
@cbodley @mattbenjamin Is a more fine grained integration of OpenStack Keystone (or any other external authentication) still being considered or on the roadmap somewhere?

I am wondering how Ceph S3 with its feature-rich bucket policies can be "properly" used in an OpenStack environment if the only Principal that can be referenced is an OpenStack `Project` and potentially a role.

2022-01-10 10:29 UTC, frittentheke commented
@cbodley @mattbenjamin may I kindly bring this one up again and not let it go stale?

It's still a little unfortunate that RADOSGW does not handle users when integrated with OpenStack Keystone.
Maybe there are some pointers to the roadmap that I missed?

2022-01-12 17:10 UTC, frittentheke commented
> > @cbodley @mattbenjamin may I kindly bring this one up again and not let it go stale?
> > It's still a little unfortunate that RADOSGW does not handle users when integrated with OpenStack Keystone. Maybe there are > some pointers to the roadmap that I missed?
> 
> Hi @frittentheke, I'm confused; This discussion was about subusers, which is, in part, a mechanism used with Swift interop when the users are RGW local users. RGW (separately) has keystone integration, which permits authentication directly as OpenStack users. What am I missing?

Yeah sorry my statement was indeed confusing. 

I was referring to support for OpenStack Keystone "users" as subusers for buckets. Currently RGW only uses the the `project_id` from the keystone authentication:

 * https://github.com/ceph/ceph/blob/6ce6874bae8fbac8921f0bdfc3931371fc61d4ff/src/rgw/rgw_auth_keystone.cc#L127
 * https://github.com/ceph/ceph/blob/6ce6874bae8fbac8921f0bdfc3931371fc61d4ff/src/rgw/rgw_auth_keystone.cc#L515
 * (https://github.com/ceph/ceph/pull/34093#issuecomment-864930146)

This actually renders bucket policies with rules for different Keystone users non-functional as they are all reduced to their project.

I once asked on the ML about this as well https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/S2TV7GVFJTWPYA6NVRXDL2JXYUIQGMIN/ and I simply thought a generic implementation for external authentication could enable such a richer integration as it apparently also has support for subusers.

2022-02-14 11:03 UTC, frittentheke commented
@mattbenjamin would you kindly take another look at this PR or even my question on the ML (https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/S2TV7GVFJTWPYA6NVRXDL2JXYUIQGMIN/) about the keystone auth integration?


I am just so darn confused that currently only the project id is taken from Keystone which is then rendering all nice features such as Ceph subusers or any further access control useless.

2022-02-14 11:08 UTC, frittentheke commented
@mattbenjamin would you kindly take another look at this PR or even my question on the ML (https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/S2TV7GVFJTWPYA6NVRXDL2JXYUIQGMIN/) about the keystone auth integration?

I am just so darn confused that currently only the project id is taken from Keystone which is then rendering all nice features such as Ceph subusers or any further access control useless. Are you potentially working on extending the integration in https://github.com/ceph/ceph/pull/43898 ?

2022-07-10 07:13 UTC, anthonyeleven requested changes
Apologies for the delay, we're working to do better.
I've requested some documentation changes.  I must defer to the RGW code folks regarding the code and API bits.

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +
Suggest something like

It is possible to use an external authentication server for the Ceph Object Gateway (RGW), providing 
all user features including subuser, tenant, and permissions.  The external server must implement that API as below.

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +In your authentication server you should implement these APIs so we can get our needed data
s/In your/The/
s/you//
s/our//

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +``access_key_id``: This is a access key which is used in request.
Maybe something like

This is the access key used in requests
This is the request signature computed with the user secret / signing key.

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +
Optional, only needed if the user has tenants.

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +``user_name``: display name in RGW User
RGW user display name

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +``is_admin``: Optional. default is false. true if user is admin.
\`\`is_admin\`\`: Optional.  Default is \`\`false\`\` for typical users, but \`\`true\`\` for  the \`\`admin\`\` user.

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +``subuser``: Optional. If user is subuser of a user. ``id`` should be in a format of ``user_id:subuser``
in the format

2022-07-10 07:13 UTC, anthonyeleven commented on doc/radosgw/external-authentication.rst
> +``access_key_id``: This is a access key which needed a secret for it
We describe the access key id above, so I would just remove this line.

2022-07-10 07:13 UTC, anthonyeleven commented on src/common/options.cc
> +    .set_description("URL to external authentication server to get user info"),
"User info endpoint URL for an external authentication server"

2022-07-10 07:13 UTC, anthonyeleven commented on src/common/options.cc
> +    .set_description("URL to external authentication server to get user secret")
"User secret endpoint URL for an external authentication server"

2022-07-10 07:13 UTC, anthonyeleven commented on src/common/options.cc
> +    "To cache user access key and secret key we use to send GET request to this URL"
we send a GET

2022-07-10 07:13 UTC, anthonyeleven commented on src/common/options.cc
> +    "in pattern of URL/?access_key_id=ACCESS_KEY_ID and need response in format of"
In the pattern of
and need a response in the format

2022-07-10 07:13 UTC, anthonyeleven commented on src/common/options.cc
> +        "Max number of access keys that will be cached. Access Key that is not cached "
Access keys that are not cached require the

2022-07-10 07:13 UTC, anthonyeleven commented on src/common/options.cc
> +    .set_description("Should RGW verify the external authentication server SSL certificate."),
.set_description("Should RGW verify the external authentication server's SSL certificate?"),

2022-07-10 07:13 UTC, anthonyeleven commented on src/common/options.cc
> +    .set_description("Should external authentication be used to authenticate users."),
? instead of .

2022-07-10 12:53 UTC, mattbenjamin commented
I don't know if we should be doing what this PR intends, but it seems to be doing several things.  I'm most suspicious of "remote authentication for S3."  RGW already has Keystone authentication.  I think the oldest part of this change involves changing the Keystone integration, so we also need to fully understand that.  But what sort of remote authentication protocol standard does the "remote authentication for S3 " represent?  Why can't integration with established OpenID::connect- and Oauth2-enabled IDPs satisfy the requirement, esp. given their intrinsic support for dynamic authz of different kinds?

2022-07-11 11:49 UTC, mattbenjamin commented
> @mattbenjamin Well, the idea was to have a general rest API for external authentication. In this case, it won't be limited to any authentication systems (like keystone, ...) and on the server-side (authentication server) anyone can have its own implementation and prepare the APIs needed by RGW to sync and could use all the RGW User's feature! eg. in keystone there is no subuser support (#33210) - but with this idea, there is no need to have a Keystone for the authenticator and RGW can connect to any Authentication server implements the needed APIs.

It would be my contention that it's not consistent with RGW's role to define an a sui generis remote authentication protocol.  To repeat a question from above, why is it not possible to build on OpenID::connect() or Oauth2--these are established standards with a lot of flexibility and basically well-known security properties?

2022-07-11 13:23 UTC, frittentheke commented
> It would be my contention that it's not consistent with RGW's role to define a sui generis remote authentication protocol. To repeat a question from above, why is it not possible to build on OpenID::connect() or Oauth2--these are established standards with a lot of flexibility and basically well-known security properties?

I second your thinking here. While looking at OIDC or SAML to allow RGW to consume an existing authentication setup one cannot ignore that OpenStack Keystone is quite a common auth target for RGW, but it currently does not provide those kind of "standard" interfaces. The federation feature (https://docs.openstack.org/keystone/latest/admin/federation/introduction.html) works to integrate Keystone with existing authentication systems. And if those exists in the form of a versatile implementation like  Keycloak those could then also be used as auth source by RGW.

But, with only Keystone and it's built-in auth, which is natively supported by RGW the case looks different.
While OAuth 2.0 is being worked on (https://blueprints.launchpad.net/keystone/+spec/oauth2-client-credentials-ext, https://blueprints.launchpad.net/keystone/+spec/enhance-oauth2-interoperability) this is not yet available widespread.

Also the question is if the proper claims and metadata can be provided to a potential client RGW yet. So enabling features like subusers, groups and whatever RGW supports to use in its bucket policies. Also the mapping from and to the world of EC2 credentials to serve S3 adds some more complexity.

What I am saying is that just having a standard and very common auth protocol like OAuth 2.0, only helps if that's what your clients use. If you "only" want to integrate one established system like Keystone or the whole of OpenStack services with RGW, RGW might have to have a more plug and play integration into that ecosystem. And while that exists in the form of keystone_auth (which lacks in functionality, see https://github.com/ceph/ceph/pull/34093#issuecomment-1011268529), it's reasonable to think about having a more generic integration available which then allows for a simple far end to exist on the Keystone side.

If you allow for a comparison, look at what Kubernetes does with its webhook auth: https://kubernetes.io/docs/reference/access-authn-authz/webhook/. That also does allow of any arbitrary system to provide auth to Kubernetes, while they certainly also support OIDC ... if you already have that for your clients.

2022-09-27 14:29 UTC, frittentheke commented
I don't consider this stale.

2022-09-27 16:02 UTC, mmgaggle commented
@frittentheke It would seem that adding support for AssumeRoleWithSAML, and combining it with keystone-as-idp (SAML) would be a viable option, would it not?

2022-10-14 12:48 UTC, frittentheke commented
@mmgaggle Sorry about the late response.

> @frittentheke It would seem that adding support for AssumeRoleWithSAML, and combining it with keystone-as-idp (SAML) would be a viable option, would it not?

 This sounds like it's going in he right direction of reusing existing capabilities ....

 * https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html
 * https://docs.openstack.org/keystone/latest/admin/federation/configure_federation.html#keystone-as-an-identity-provider-idp
 
but is this really lightweight enough to have this as the standard auth integration of RGW to an OpenStack cloud?
SAML is not really common (anymore) and OIDC and OAuth 2.0 with all sort of additions and flows are taking over.

2022-12-13 19:59 UTC, frittentheke commented
@mmgaggle would you mind diving into your idea a little more?

2023-03-13 21:01 UTC, closed without merging