osd/ECBackend: optimize remaining read as readop contain multiple objects
ceph/ceph pull request #35821
Opened 2020-06-29 04:03 UTC by Aran85

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-06-29 06:04 UTC, Aran85 commented
jenkins retest this please

2020-06-29 06:20 UTC, Aran85 commented
@dzafman @jdurgin please help to review, thanks.

2020-07-08 01:44 UTC, Aran85 commented
can someone help review?

2020-07-14 01:08 UTC, Aran85 commented
jenkins retest this please

2020-08-17 03:29 UTC, tchaikov commented
@Aran85 hi Zengran, could you help create a tracker ticket?

2020-08-17 15:14 UTC, Aran85 commented
@tchaikov updated, thanks for the QA.

2020-08-20 02:15 UTC, jdurgin commented
looks good to go to me. since this is purely an optimization when an IO error occurs, I don't think it makes sense to backport.

2020-08-21 00:53 UTC, tchaikov requested changes
i suspect that this fails the thrash-erasure-code tests suites. see https://pulpito.ceph.com/kchai-2020-08-19_06:47:30-rados-wip-kefu-testing-2020-08-19-1141-distro-basic-smithi/

2020-08-21 01:41 UTC, Aran85 commented
> tests

/build/ceph-16.0.0-4528-g8d9001a/src/test/osd/RadosModel.h: 934: ceph_abort_msg("racing read got wrong version"

2020-08-21 02:11 UTC, Aran85 commented
more detail:

2020-08-19T18:23:41.538 INFO:tasks.rados.rados.0.smithi008.stdout:6:  writing smithi00819524-6 from 0 to 90112 tid 1
2020-08-19T18:23:41.553 INFO:tasks.rados.rados.0.smithi008.stdout:6:  finishing write tid 1 to smithi00819524-6
2020-08-19T18:23:41.558 INFO:tasks.rados.rados.0.smithi008.stdout:6:  finishing write tid 3 to smithi00819524-6
2020-08-19T18:23:41.562 INFO:tasks.rados.rados.0.smithi008.stdout:6:  finishing write tid 4 to smithi00819524-6
2020-08-19T18:23:41.562 INFO:tasks.rados.rados.0.smithi008.stdout:update_object_version oid 6 v 2 (ObjNum 5 snap 0 seq_num 5) dirty exists
2020-08-19T18:23:41.562 INFO:tasks.rados.rados.0.smithi008.stderr:Error: racing read on 6 returned version 0 rather than version 2
2020-08-19T18:23:41.562 INFO:tasks.rados.rados.0.smithi008.stderr:/build/ceph-16.0.0-4528-g8d9001a/src/test/osd/RadosModel.h: In function 'virtual void WriteOp::_finish(TestOp::CallbackInfo*)' thread 7feeb37fe700 time 2020-08-19T18:23:41.562448+0000
2020-08-19T18:23:41.562 INFO:tasks.rados.rados.0.smithi008.stderr:/build/ceph-16.0.0-4528-g8d9001a/src/test/osd/RadosModel.h: 934: ceph_abort_msg("racing read got wrong version")
2020-08-19T18:23:41.563 INFO:tasks.rados.rados.0.smithi008.stderr: ceph version 16.0.0-4528-g8d9001a (8d9001a8062a52bb640447b6a7e38abbff3580ee) pacific (dev)
2020-08-19T18:23:41.563 INFO:tasks.rados.rados.0.smithi008.stderr: 1: (ceph::__ceph_abort(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe1) [0x7feebecab1d7]
2020-08-19T18:23:41.563 INFO:tasks.rados.rados.0.smithi008.stderr: 2: (WriteOp::_finish(TestOp::CallbackInfo*)+0x6b0) [0x560cf78c2a60]
2020-08-19T18:23:41.563 INFO:tasks.rados.rados.0.smithi008.stderr: 3: (write_callback(void*, void*)+0x19) [0x560cf78df039]
2020-08-19T18:23:41.563 INFO:tasks.rados.rados.0.smithi008.stderr: 4: (()+0x98707) [0x7feec7985707]
2020-08-19T18:23:41.564 INFO:tasks.rados.rados.0.smithi008.stderr: 5: (()+0xb24c5) [0x7feec799f4c5]
2020-08-19T18:23:41.564 INFO:tasks.rados.rados.0.smithi008.stderr: 6: (()+0xb535f) [0x7feec79a235f]
2020-08-19T18:23:41.564 INFO:tasks.rados.rados.0.smithi008.stderr: 7: (()+0xb56a6) [0x7feec79a26a6]
2020-08-19T18:23:41.564 INFO:tasks.rados.rados.0.smithi008.stderr: 8: (()+0xbd6df) [0x7feebe55c6df]
2020-08-19T18:23:41.564 INFO:tasks.rados.rados.0.smithi008.stderr: 9: (()+0x76db) [0x7feebe82f6db]
2020-08-19T18:23:41.565 INFO:tasks.rados.rados.0.smithi008.stderr: 10: (clone()+0x3f) [0x7feebdfb7a3f]

2020-08-21 02:25 UTC, tchaikov commented
rerunning the failed tests without this changeset at https://pulpito.ceph.com/kchai-2020-08-21_02:24:23-rados-wip-kefu-testing-2020-08-19-1142-distro-basic-smithi/

2020-08-21 03:39 UTC, Aran85 commented
# the expected  WriteOp procedure:

write range with tid=1 
finish with user_version=1

write head with tid=3
finish with user_version=2

read op with tid=4
finish with user_version=3

# test result :
write head with tid=3 return with user_version=2 (it is correct)
**read op with tid=4 return with user_version=0 (wrong place)**

2020-08-21 03:45 UTC, Aran85 commented
@tchaikov  @jdurgin  Because the changes did not related with the user_version, and normally the reply.user_version is filled by oi.user_version in PrimaryLogPG::complete_read_ctx..  puzzling results..

2020-08-21 03:46 UTC, Aran85 commented
@tchaikov is there any other client logs with debug_objecter >=7,  or osd logs with debug_osd>= 10 ?

2020-08-21 04:29 UTC, tchaikov commented
> @tchaikov is there any other client logs with debug_objecter >=7, or osd logs with debug_osd>= 10 ?

https://pulpito.ceph.com/kchai-2020-08-19_06:47:30-rados-wip-kefu-testing-2020-08-19-1141-distro-basic-smithi/5359037/

where we had
```
debug ms: 20
bluestore fsck on mount: True
osd scrub max interval: 120
debug osd: 25
```

2020-08-21 06:01 UTC, Aran85 commented
@tchaikov  updated, would you help to rerun the suites? 

btw, the src/test/osd/RadosModel.h WriteOp::_begin did not add the last read to waiting list.. So the finish will not check the read op's return value.. that mislead some..
(see https://github.com/ceph/ceph/blob/ec73fea99e43ac2767d846d584940d4dd8ef354e/src/test/osd/RadosModel.h#L887)

2020-08-21 06:36 UTC, tchaikov commented
> @tchaikov updated, would you help to rerun the suites?
> 

could you note down what change you made in a comment? it'd help reviewer to understand your changeset better. especially those have reviewed your changes.

> btw, the src/test/osd/RadosModel.h WriteOp::_begin did not add the last read to waiting list.. So the finish will not check the read op's return value.. that mislead some..
> (see
> 
> https://github.com/ceph/ceph/blob/ec73fea99e43ac2767d846d584940d4dd8ef354e/src/test/osd/RadosModel.h#L887
> 
> )

could you please create a PR to address this ?

2020-08-24 12:18 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-08-21_13:05:18-rados-wip-kefu-testing-2020-08-21-1823-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-22_07:06:08-rados-wip-kefu-testing-2020-08-22-1251-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-22_07:06:08-rados-wip-kefu-testing-2020-08-22-1251-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-22_11:08:32-rados-wip-kefu-testing-2020-08-22-1252-distro-basic-smithi/

2020-08-24 12:33 UTC, tchaikov commented
@jdurgin @dzafman this change passed the rados suite. could you take another look?

2020-08-27 14:32 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-08-25_04:54:49-rados-wip-kefu-testing-2020-08-25-0950-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-26_16:53:29-rados-wip-kefu-testing-2020-08-26-1944-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-27_03:37:15-rados-wip-kefu-testing-2020-08-27-0139-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-27_08:22:12-rados-wip-kefu-testing-2020-08-27-1255-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-27_10:01:54-rados-wip-kefu-testing-2020-08-27-1255-distro-basic-smithi/

@jdurgin @dzafman ping?

2020-08-28 11:45 UTC, tchaikov requested changes
https://pulpito.ceph.com/kchai-2020-08-28_06:18:09-rados-wip-kefu-testing-2020-08-28-1247-distro-basic-smithi/

all thrash-erasure-code-* tests failed with

> "2020-08-28T07:02:13.843696+0000 osd.9 (osd.9) 38 : cluster [ERR] 3.cs0 shard 4(4) 3:3f45dd62:::smithi04717497-21:177 : missing" in cluster log

2020-08-29 03:55 UTC, Aran85 commented
[new scrub first chunk, the 3:6e0b9a9a:::smithi18817338-30:204 pass the scrub compare. (start at v 742'1398)]
2020-08-28T07:44:43.203+0000 7fe3cf48b700 10 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] starting a new chunky scrub
2020-08-28T07:44:43.203+0000 7fe3cf48b700 20 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] scrub state INACTIVE [MIN,MIN) max_end MIN
2020-08-28T07:44:43.215+0000 7fe3cf48b700 10 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] build_scrub_map_chunk [3:68000000::::0,3:6e0b9a9a:::smithi18817338-30:246)  pos (0/24 3:6c4824c0:::smithi18817338-34:1f5)
2020-08-28T07:44:43.215+0000 7fe3cf48b700 25 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_scan_list  3:6e0b9a9a:::smithi18817338-30:204
2020-08-28T07:44:43.243+0000 7fe3cf48b700 10 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_select_auth_object: selecting osd 1(2) for obj 3:6e0b9a9a:::smithi18817338-30:204 with oi 3:6e0b9a9a:::smithi18817338-30:204(667'1337 client.4450.0:6089 dirty|data_digest s 2064384 uv 1197 dd 274b0ba6 alloc_hint [0 0 0])
2020-08-28T07:44:43.243+0000 7fe3cf48b700 20 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_compare_scrubmaps authshards 3 digest_match
2020-08-28T07:44:43.243+0000 7fe3cf48b700 20 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_compare_scrubmaps shards 3 digest_match
2020-08-28T07:44:43.243+0000 7fe3cf48b700 20 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_compare_scrubmaps shards 3 digest_match

(NOTE: the 3:6e0b9a9a:::smithi18817338-30:204 pass the scrub compare)

[second chunk scrub: osd.1 w/o 3:6e0b9a9a:::smithi18817338-30:204 because we start with 3:6e0b9a9a:::smithi18817338-30:246, but osd.7 and osd.5 build chunk wthin 3:6e0b9a9a:::smithi18817338-30:204, so the 3:6e0b9a9a:::smithi18817338-30:204 be thinked as missing on osd.1]
2020-08-28T07:44:43.243+0000 7fe3cf48b700 20 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] scrub state NEW_CHUNK [3:6e0b9a9a:::smithi18817338-30:246,3:6e0b9a9a:::smithi18817338-30:246) max_end 3:6e0b9a9a:::smithi18817338-30:246

2020-08-28T07:44:43.255+0000 7fe3cf48b700  2 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] scrub_compare_maps replica 5(0) has 14 items
2020-08-28T07:44:43.255+0000 7fe3cf48b700  2 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] scrub_compare_maps replica 7(1) has 14 items
2020-08-28T07:44:43.255+0000 7fe3cf48b700 10 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_select_auth_object: selecting osd 5(0) for obj 3:6e0b9a9a:::smithi18817338-30:204 with oi 3:6e0b9a9a:::smithi18817338-30:204(667'1337 client.4450.0:6089 dirty|data_digest s 2064384 uv 1197 dd 274b0ba6 alloc_hint [0 0 0])
2020-08-28T07:44:43.255+0000 7fe3cf48b700 20 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_compare_scrubmaps authshards 3 digest_match
2020-08-28T07:44:43.255+0000 7fe3cf48b700 20 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] be_compare_scrubmaps shards 3 digest_match
2020-08-28T07:44:43.255+0000 7fe3cf48b700  2 osd.1 pg_epoch: 742 pg[3.16s2( v 742'1398 (0'0,742'1398] local-lis/les=736/737 n=37 ec=502/22 lis/c=736/736 les/c/f=737/737/0 sis=736) [5,7,1]p1(2) r=2 lpr=736 crt=742'1398 lcod 740'1396 mlcod 740'1396 active+clean+scrubbing+snaptrim_wait trimq=61 ps=34] 3.16s2 shard 1(2) 3:6e0b9a9a:::smithi18817338-30:204 : missing

2020-08-29 03:59 UTC, Aran85 commented
Its too lag to download the osd.5's log :(  
So it seems that the osd.5 wrongly list out the smithi18817338-30:204 on the chunk of [3:6e0b9a9a:::smithi18817338-30:246,3:6e0b9a9a:::smithi18817338-30:246)..

2020-08-29 04:14 UTC, tchaikov commented
@Aran85 no worries. i think it was a false alarm. i am going to rerun the test with your change.

2020-08-29 15:53 UTC, tchaikov commented
https://pulpito.ceph.com/kchai-2020-08-29_13:54:19-rados-wip-kefu-testing-2020-08-29-1945-distro-basic-smithi/

2020-08-31 05:09 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-08-29_04:43:21-rados-wip-kefu-testing-2020-08-29-1106-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-29_13:54:19-rados-wip-kefu-testing-2020-08-29-1945-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-31_03:26:38-rados-wip-kefu-testing-2020-08-31-0934-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/47179

2020-09-06 10:52 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-09-03_14:29:24-rados-wip-kefu-testing-2020-09-02-1016-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-04_15:27:05-rados-wip-kefu-testing-2020-09-04-1852-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-05_14:56:36-rados-wip-kefu-testing-2020-09-05-2016-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-06_09:34:33-rados-wip-kefu-testing-2020-09-06-1546-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/47180
- https://tracker.ceph.com/issues/47179

2020-09-07 06:52 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-09-06_13:32:55-rados-wip-kefu-testing-2020-09-06-2017-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-07_01:57:21-rados-wip-kefu-testing-2020-09-06-2017-distro-basic-smithi

failures tracked by 

- https://tracker.ceph.com/issues/47306
- https://tracker.ceph.com/issues/47179

and i tested locally using

```sh
../qa/run-standalone.sh osd-backfill-prio.sh
```

it passed.

2020-09-09 00:55 UTC, dzafman commented on src/osd/ECBackend.cc
> +	// avoid re-read for completed object as we may send remaining reads for uncopmpleted objects
@aran85 typo in comment "uncopmpleted"

2020-09-09 01:33 UTC, dzafman approved these changes
Looks good.  When I was making changes in handle_sub_read_reply() I couldn't consider multiple objects, it made my brain hurt.  Thanks for fixing this.

2020-12-05 14:54 UTC, merged