mds: inherit MMDSPing from MMDSOp
ceph/ceph pull request #36004
Opened 2020-07-10 07:43 UTC by joscollin

2020-07-10 23:48 UTC, batrick commented
Marking this DNM because the fix is incomplete.

2020-07-14 05:11 UTC, joscollin commented
http://pulpito.front.sepia.ceph.com/jcollin-2020-07-13_06:13:24-fs-wip-mmdsping-fix-distro-basic-smithi/

2020-07-16 14:08 UTC, batrick commented
jenkins retest this please

2020-07-16 22:47 UTC, batrick commented
jenkins test dashboard backend

2020-07-31 21:14 UTC, batrick commented
@joscollin status?

2020-08-01 03:22 UTC, joscollin commented
@batrick There are [no related failures](https://github.com/ceph/ceph/pull/36004#issuecomment-657970434). So please merge this.

Please note: This PR only prevents unnecessary test failures, so that the current tests could continue. The issue mentioned in the tracker (why the test continues after the assert) is yet to be investigated.

2020-08-03 16:54 UTC, batrick commented
> @batrick There are [no related failures](https://github.com/ceph/ceph/pull/36004#issuecomment-657970434). So please merge this.

The fix is still incomplete. As we discussed, you need to understand why the `MMDSPing` message was processed by `MDSRank::ms_dispatch` and not in earlier testing. Check the logs.

> Please note: This PR only prevents unnecessary test failures, so that the current tests could continue. The issue mentioned in the tracker (why the test continues after the assert) is yet to be investigated.

2020-08-04 03:09 UTC, joscollin commented
Closing this. Will send a new PR to fix the issue mentioned in the tracker.

2020-08-04 16:04 UTC, batrick commented
@joscollin I've been including this in my integration branch so I don't see the failure. So I'm reopening it.

2020-08-05 06:34 UTC, joscollin commented
Added one more inter-mds class from https://github.com/ceph/ceph/pull/26004.

2020-09-18 17:53 UTC, batrick commented
@joscollin here's an instance of the failure:

/ceph/teuthology-archive/pdonnell-2020-09-18_04:24:45-fs-wip-pdonnell-testing-20200918.022351-distro-basic-smithi/5445285/remote/smithi140/log/ceph-mds.a.log.gz

Please save the log and debug.

2020-09-21 09:47 UTC, joscollin commented
@batrick Thanks Patrick! I'm checking that now.

2020-10-19 19:20 UTC, batrick requested changes

2020-10-19 19:20 UTC, batrick commented on src/mds/MDSDaemon.cc
> +  dout(10) << sizeof(xlist<void*>::item) << "\t xlist<>::item * 2 = " << 2*sizeof(xlist<void*>::item) << dendl;
Please move this commit to another PR.

2020-10-21 10:16 UTC, joscollin commented
http://pulpito.front.sepia.ceph.com/jcollin-2020-10-20_06:44:34-fs-wip-mmdsping-fix-distro-basic-smithi/

`fs` suite ran with `--limit 100`

2020-10-21 16:03 UTC, batrick approved these changes

2020-10-21 16:07 UTC, batrick requested changes
Actually, there's one more change to make.

`MDSRank::is_valid_message` needs to recognize these `MMDSPing` and `MMDSMetrics` messages and not return true. We don't want the MDSRank dispatcher to ever process them.

2020-10-21 16:11 UTC, joscollin commented
> Actually, there's one more change to make.
> 
> `MDSRank::is_valid_message` needs to recognize these `MMDSPing` and `MMDSMetrics` messages and not return true. We don't want the MDSRank dispatcher to ever process them.

Right, I'll check that code path and make the change.

2020-10-22 04:36 UTC, joscollin commented
> Actually, there's one more change to make.
> 
> `MDSRank::is_valid_message` needs to recognize these `MMDSPing` and `MMDSMetrics` messages and not return true. We don't want the MDSRank dispatcher to ever process them.

I've checked the code once again today morning and I think this is unnecessary, because:

1. `MDSRank::is_valid_message` currently returns `false` for an incoming `MSG_MDS_PING` and `MSG_MDS_METRICS`  and thus `MDSRank::_dispatch` doesn't process the message.
2. In such cases, an incoming `MSG_MDS_PING` or an `MSG_MDS_METRICS` would assert [here](https://github.com/ceph/ceph/blob/master/src/mds/MDSRank.cc#L1016) at the first place as it is mds-mds message?

2020-10-22 04:45 UTC, joscollin commented
Sorry, I've edited my comment ^

2020-10-22 09:09 UTC, joscollin commented
jenkins test make check

2020-10-22 13:43 UTC, batrick commented
Right, my mistake. Okay PR looks good as-is.

2020-10-22 13:43 UTC, batrick approved these changes

2020-10-22 19:50 UTC, batrick commented
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20201021.232150

failures unrelated

2020-10-22 19:55 UTC, merged