mgr/cephadm: add autopep8 format changes
ceph/ceph pull request #36523
Opened 2020-08-07 22:15 UTC by mgfritch

introduced by: 7d8a3b60321

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-08-07 22:18 UTC, mgfritch commented
It's getting rather annoying working around these in a dev. environment ... can we get the additional changes committed that did not occur during #36348 ?

2020-08-08 15:36 UTC, mgfritch commented
jenkins make check

2020-08-08 15:37 UTC, mgfritch commented
jenkins test make check

2020-08-10 00:36 UTC, sebastian-philipp commented
Hm. My thought was: 

1. do we really want to stop running QA runs for a day, plus force everyone to rebase their PRs, just for some PEP-8 changes? 
2. I don't want to review this monster PR. Most of the changes look innocent, but some changes introduce bugs or break type annotations. 

That's why I asked @votdev to skip those changes in his pr and since then sneaked in PEP8 PRs once every few days.

2020-08-19 21:29 UTC, mgfritch commented
> Hm. My thought was:
> 
> 1. do we really want to stop running QA runs for a day, plus force everyone to rebase their PRs, just for some PEP-8 changes?
> 2. I don't want to review this monster PR. Most of the changes look innocent, but some changes introduce bugs or break type annotations.
> 
> That's why I asked @votdev to skip those changes in his pr and since then sneaked in PEP8 PRs once every few days.

but would it be better to get this done now?

I'm unsure how other devs are working around this, but my current workflow has been to commit locally, run tox, and then stash/drop the autopep8 changes ..

2020-08-25 13:27 UTC, sebastian-philipp requested changes

2020-08-25 13:27 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/inventory.py
> +        self.osdspec_previews_refresh_queue = []  # type: List[str]
this change brakes the alignment.

2020-08-25 13:27 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/tests/test_scheduling.py
> +                             "Cannot place <ServiceSpec for service_name=mon> on 3: Unknown hosts")),
the scheduler test is already **really** hard to read. breaking the table here makes it even harder to grasp. 

Can we leave this as it was?

2020-08-26 13:57 UTC, mgfritch commented
Duplicated by: #36793, #36794, #36792, #36817, #36818, #36816, #36815

2020-08-26 13:57 UTC, closed without merging