[RFC]kv/RocksDBStore: make recycle_log_file_num work.
ceph/ceph pull request #36579
Opened 2020-08-12 07:51 UTC by majianpeng

This PR(https://github.com/facebook/rocksdb/pull/6351) make
recycle_log_file_num can't work.
In fact, for ceph kTolerateCorruptedTailRecords mode is safe.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-08-12 07:52 UTC, majianpeng commented
@markhpc @aclamk . i'm not 100% sure. please review. Thanks!

2020-08-12 12:04 UTC, markhpc commented
@majianpeng yikes, Sage was the one that wrote the log recycling code in the first place.  They should have consulted him when they made that change: https://github.com/facebook/rocksdb/pull/746

I'm not sure what to think about this yet.  I'm rather wary of enabling kTolerateCorruptedTailRecords until I really understand the safety guarantees better.

2021-06-29 18:37 UTC, markhpc requested changes
Hi Majianpeng,

@aclamk and I reviewed the upstream rocksdb PRs here:

https://github.com/facebook/rocksdb/pull/7252

and here:

https://github.com/facebook/rocksdb/pull/7271

I don't think we can actually safely use kTolerateCorruptedTailRecords with log recycling as they are currently implemented given the evidence provided.  @liewegas recommended that it might be possible to create a new RecoveryMode that wouldn't suffer from the same problem documented in those PRs, though I'm not sure exactly what it would look like since we are still faced with the fundamental problem of not knowing if corruption is real.

2021-06-29 20:12 UTC, liewegas commented
tbh I think the best approach would be to create a new WAL file format that (1) is 4k block aligned and (2) has a header for each block that indicates the generation # for that log file (so we can see whether what we read is from a previous pass or corruption).  That would be a fair bit of effort, though.

2021-07-01 07:24 UTC, aclamk commented
@liewegas
I am considering making 4k aligned WAL you mentioned a BlueFS way of handling subsequent writes to RocksDB WALs.
On BlueFS start those files would be converted to plain, continuous files;
or maybe specialized reader will fixup offsets & data on read request.
In any case - I would like to make this a BlueFS implementation detail, hidden behind BlueRocksEnv interface.
Do we value separation from RocksDB enough to justify such approach?

2021-09-15 00:53 UTC, jdurgin commented
Closing since this isn't safe as implemented, and would require significant work to function correctly.

2021-09-15 00:53 UTC, closed without merging