DNM: doc fix wip
ceph/ceph pull request #36572
Opened 2020-08-12 01:32 UTC by dmick

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>
jenkins do not test
jenkins render docs

2020-08-12 01:33 UTC, dmick commented
jenkins do not test

2020-08-12 01:33 UTC, dmick commented
jenkins render docs

2020-08-13 00:31 UTC, dmick commented
jenkins do not test

2020-08-13 00:31 UTC, dmick commented
jenkins render docs

2020-08-13 23:23 UTC, dmick commented
jenkins render docs

2020-08-18 03:35 UTC, tchaikov commented
jenkins test make check

2020-08-18 08:43 UTC, varshar16 commented on doc/mgr/orchestrator.rst
> +    Also, the implementation of the commands may differ differ between modules.
```suggestion
    Also, the implementation of the commands may differ between modules.
```

2020-08-18 23:56 UTC, dmick commented on doc/mgr/orchestrator.rst
> +    Also, the implementation of the commands may differ differ between modules.
thanks!

2020-08-18 23:57 UTC, dmick commented on doc/mgr/orchestrator.rst
> +    Also, the implementation of the commands may differ differ between modules.
forcepushed the update

2020-08-26 08:19 UTC, varshar16 requested changes
@dmick please rebase the commit

2020-08-26 20:08 UTC, dmick commented
rebased, reworded conflicting change text to avoid awkward phrasing

2020-08-27 04:58 UTC, varshar16 approved these changes

2020-08-27 15:07 UTC, merged

2020-08-27 15:08 UTC, sebastian-philipp commented
Wasn't on my radar, due to missing github labels.