mds: make caps dump more readable
ceph/ceph pull request #36600
Opened 2020-08-13 07:48 UTC by gmayyyha

before 
```c
{
    "last_sent": 19014,
    "last_issue_stamp": 1597301031,
    "wanted": 0,
    "pending": 341,
    "revokes": []
},
```
after
```c
{
    "ino": "0x20000000000",
    "last_sent": 3,
    "last_issue_stamp": "2020-08-13T15:46:30.151082+0800",
    "wanted": "-",
    "pending": "pAsLsXsFscr",
    "revokes": []
}
```

2020-08-28 06:08 UTC, gmayyyha commented
jenkins test make check

2020-08-28 07:43 UTC, ukernel approved these changes

2020-08-31 23:54 UTC, gmayyyha commented
jenkins test make check

2020-09-01 23:01 UTC, batrick commented
jenkins test make check

2020-09-02 23:03 UTC, batrick commented
jenkins test make check

2020-09-02 23:33 UTC, batrick requested changes
This breaks `make check`:

````
104/204 Test #113: check-generated.sh ........................***Failed    4.96 sec
Enivronment Variables Already Set
stty: 'standard input': Inappropriate ioctl for device
checking ceph-dencoder generated test instances...
numgen type
3 ACLGrant
2 ACLGranteeType
2 ACLOwner
2 ACLPermission
3 AuthMonitor::Incremental
2 BitVector<2>
2 BloomHitSet
2 Capability
13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20558 Segmentation fault      "$@" > "$out"
13860: copy ctor not supported
13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20563 Segmentation fault      "$@" > "$out"
13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20553 Segmentation fault      "$@" > "$out"
13860: copy operator= not supported
13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20564 Segmentation fault      "$@" > "$out"
````

I think because the format changed but I'm not sure how that caused a segfault.

2020-09-04 06:05 UTC, gmayyyha commented
> This breaks `make check`:
> 
> ```
> 104/204 Test #113: check-generated.sh ........................***Failed    4.96 sec
> Enivronment Variables Already Set
> stty: 'standard input': Inappropriate ioctl for device
> checking ceph-dencoder generated test instances...
> numgen type
> 3 ACLGrant
> 2 ACLGranteeType
> 2 ACLOwner
> 2 ACLPermission
> 3 AuthMonitor::Incremental
> 2 BitVector<2>
> 2 BloomHitSet
> 2 Capability
> 13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20558 Segmentation fault      "$@" > "$out"
> 13860: copy ctor not supported
> 13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20563 Segmentation fault      "$@" > "$out"
> 13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20553 Segmentation fault      "$@" > "$out"
> 13860: copy operator= not supported
> 13860: /home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh: line 2005: 20564 Segmentation fault      "$@" > "$out"
> ```
> 
> I think because the format changed but I'm not sure how that caused a segfault.

@batrick  caused by `f->dump_stream("ino") << inode->ino()`, generate_test_instances does not initialize inode.
```c
void Capability::generate_test_instances(std::list<Capability*>& ls)
{
  ls.push_back(new Capability);
  ls.push_back(new Capability);
```

2020-09-04 17:02 UTC, batrick commented
jenkins test api

2020-09-04 17:03 UTC, batrick approved these changes

2020-09-04 22:09 UTC, batrick commented
jenkins test api

2020-09-06 15:57 UTC, merged