rgw: dump transitions in RGWLifecycleConfiguration::dump()
ceph/ceph pull request #36812
Opened 2020-08-26 08:50 UTC by Huber-ming

backport of 36092
parent tracker: https://tracker.ceph.com/issues/46647

Signed-off-by: Shengming Zhang <zhangsm01@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-08-27 19:40 UTC, smithfarm requested changes
please re-do the commit using `git cherry-pick -x`

see https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst

2020-09-10 18:24 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri4-testing-2020-09-10-1822-octopus](https://trello.com/c/JFI9lhmf/1006-wip-yuri4-testing-2020-09-10-1822-octopus)

2020-09-10 18:24 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri4-testing-2020-09-10-1822-octopus](https://trello.com/c/JFI9lhmf/1006-wip-yuri4-testing-2020-09-10-1822-octopus)

2020-09-11 16:09 UTC, cbodley approved these changes

2020-09-16 15:38 UTC, merged