nautilus: mgr/dashboard: redirect to original URL after successful login
ceph/ceph pull request #36834
Opened 2020-08-26 18:54 UTC by avanthakkar

backport tracker: https://tracker.ceph.com/issues/47156

---

backport of https://github.com/ceph/ceph/pull/36582
parent tracker: https://tracker.ceph.com/issues/45067

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-08-31 11:13 UTC, callithea approved these changes
lgtm, thank you!

2020-09-15 15:01 UTC, tspmelo requested changes
Please add a comment on the commit for why this was backported from octopus and not master.

2020-09-15 15:30 UTC, smithfarm commented
@avanthakkar For commits that have no conflicts, I don't see a compelling reason to cherry-pick from octopus. Having two "cherry-picked from" lines in the commit message is confusing, and - as @tspmelo - there is no explanation why you chose to do it this way?

2020-09-15 16:53 UTC, smithfarm approved these changes
Oh, I see now. The first "cherry picked from . . ." line is in the master commit (and presumably should have been removed since it points to an out-of-tree/downstream commit).

This is OK as-is.

2020-09-18 11:06 UTC, avanthakkar commented
> Please add a comment on the commit for why this was backported from octopus and not master.

Sorry, it's a mistake while backporting - didn't change branch back to master while backporting to nautilus, so got backported from the octopus branch

2020-09-23 09:23 UTC, smithfarm requested changes
This cherry-pick had conflicts, but there is no "Conflicts" section in the commit message. Please add one?

```
+ git cherry-pick -x 330c75cb511d61306a8841973f2b18e17893c555
Auto-merging src/pybind/mgr/dashboard/frontend/src/app/shared/services/auth-guard.service.spec.ts
CONFLICT (content): Merge conflict in src/pybind/mgr/dashboard/frontend/src/app/shared/services/auth-guard.service.spec.ts
Auto-merging src/pybind/mgr/dashboard/frontend/src/app/core/auth/login/login.component.ts
CONFLICT (content): Merge conflict in src/pybind/mgr/dashboard/frontend/src/app/core/auth/login/login.component.ts
Adding qa/suites/rados/singleton-bluestore/msgr-failures/many.yaml
Adding qa/suites/rados/singleton-bluestore/msgr-failures/few.yaml
Adding qa/suites/rados/perf/objectstore
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1845 and retry the command.
error: could not apply 330c75cb511... mgr/dashboard: redirect to original URL after successful login
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```

2020-09-23 09:24 UTC, smithfarm commented
> Sorry, it's a mistake while backporting - didn't change branch back to master while backporting to nautilus, so got backported from the octopus branch

This explanation is not correct. The first "(cherry picked from commit ...)" line is already there in the master commit. Look:

https://github.com/ceph/ceph/pull/36582/commits/330c75cb511d61306a8841973f2b18e17893c555

So, this basckpo

2020-09-28 09:20 UTC, smithfarm submitted a review, later dismissed
While adding the "Conflicts" section, you managed to remove one of the "(cherry picked from commit ...)" lines. There should be two:

```
(cherry picked from commit b5359a155c6ff7e92ab6c6ed16f7ff9fc76c76ea)
(cherry picked from commit 330c75cb511d61306a8841973f2b18e17893c555)
```

The first one is part of the master commit message, which should be preserved in its entirety. (But it probably should have been omitted since commits in master are supposed to original - that's a different question, though.)

The second one was added when you did `git cherry-pick -x`.

If you feel that you absolutely must remove one of them, then remove the first one ;-)

2020-09-28 13:53 UTC, avanthakkar commented
jenkins test api

2020-09-29 08:33 UTC, callithea commented
jenkins test api

2020-10-02 08:37 UTC, callithea commented
jenkins test api

2020-10-02 10:59 UTC, LenzGr commented
jenkins test api

2020-10-19 13:38 UTC, nizamial09 approved these changes

2020-11-02 11:13 UTC, avanthakkar commented
jenkins retest this please

2020-11-05 09:48 UTC, merged