nautilus: rgw: log resharding events at level 1 (formerly 20)
ceph/ceph pull request #36843
Opened 2020-08-27 03:44 UTC by Huber-ming

backport tracker: https://tracker.ceph.com/issues/47056
***
backport of #36719
parent tracker: https://tracker.ceph.com/issues/47040

log resharding events at level 1 (formerly 20)
Signed-off-by: Or Friedmann <ofriedma@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-08-27 12:23 UTC, Huber-ming commented
jenkins test make check

2020-08-27 19:34 UTC, smithfarm requested changes
Thanks for the backport! We don't accept cherry-picks unless they are done using git cherry-pick -x. Please re-do it using that command.

For details on how the Ceph project handles backports, please read https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst

(NOTE: since the master PR #36719 has only one commit, the backport PR should also have only one. This one has two...)

2020-08-27 19:36 UTC, smithfarm commented
simplest procedure for preparing backport branch, assuming upstream remote is called "ceph":

1. git fetch ceph
2. git reset --hard ceph/nautilus
3. git cherry-pick -x a5428c8a29414044a87b7dc009f27b336d4232e2
4. git push -f

Nothing else is needed.

2020-08-28 02:59 UTC, Huber-ming commented
jenkins test make check

2020-08-28 12:00 UTC, smithfarm commented
```
1 tests failed out of 172

Total Test time (real) = 992.83 sec

The following tests FAILED:
	  5 - run-tox-mgr-dashboard (Failed)

2020-08-28 12:00 UTC, smithfarm commented
jenkins test make check

2020-08-28 13:08 UTC, smithfarm commented
```
run-tox-mgr-dashboard (Failed)
```

for the second time in a row

2020-09-05 10:54 UTC, smithfarm commented
make check is failing in nautilus PRs due to https://tracker.ceph.com/issues/47269

2020-09-23 09:31 UTC, smithfarm commented
jenkins test make check

2020-09-23 19:06 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri2-testing-2020-09-23-1204-nautilus](https://trello.com/c/nXrOZ7iq/1018-wip-yuri2-testing-2020-09-23-1204-nautilus)

2020-09-24 14:27 UTC, cbodley approved these changes

2020-09-24 14:58 UTC, merged