mgr/dashboard: fix style being applied globally in modal footer
ceph/ceph pull request #36865
Opened 2020-08-28 06:57 UTC by ishanrai05

fixes: https://tracker.ceph.com/issues/45018

Signed-off-by: Ishan Rai <ishanrai05@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-08-28 06:58 UTC, ishanrai05 commented
@tspmelo

2020-08-28 07:01 UTC, ishanrai05 commented
before:
![after](https://user-images.githubusercontent.com/31144462/91531413-658f2680-e92a-11ea-8c2d-0e3a01cb4761.png)

now:
![before](https://user-images.githubusercontent.com/31144462/91531424-6922ad80-e92a-11ea-911a-f527c7416876.png)

2020-08-28 08:02 UTC, avanthakkar commented
jenkins test api

2020-08-28 08:03 UTC, avanthakkar approved these changes
lgtm!

2020-08-28 08:12 UTC, votdev approved these changes

2020-08-28 08:47 UTC, tspmelo commented
Could you also apply this to all other styles where this can happen?
The issue mentioned is not specific to modals.

2020-08-28 08:48 UTC, ishanrai05 commented
@tspmelo sure, I will update the PR

2020-08-28 08:49 UTC, tspmelo requested changes
This should also be applied to other components.

2020-08-31 14:52 UTC, tspmelo requested changes

2020-08-31 14:52 UTC, tspmelo commented on src/pybind/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.scss
> +::ng-deep cd-modal.modal-footer {
I would suggest having only 1 `::ng-deep` and move  `::ng-deep cd-modal.modal-body` inside
```suggestion
::ng-deep cd-modal {
  .modal-footer {
```

2020-08-31 14:52 UTC, tspmelo commented on src/pybind/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.scss
> +::ng-deep cd-modal.modal-body {
This should go inside the previous `::ng-deep`
```suggestion
.modal-body {
```

2020-08-31 14:52 UTC, tspmelo commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.scss
> +::ng-deep cd-info-card.pg-status-popover-wrapper {
Think its better to use the component selector:
```suggestion
::ng-deep cd-health .pg-status-popover-wrapper {
```

2020-08-31 14:54 UTC, tspmelo commented
I would suggest adding the component selector to all usages of `::ng-deep`.

2020-09-01 11:58 UTC, tspmelo requested changes

2020-09-01 11:58 UTC, tspmelo commented on src/pybind/mgr/dashboard/frontend/src/app/core/layouts/workbench-layout/workbench-layout.component.scss
> +::ng-deep cd-workbench-layout #toast-container {
This block of styles is exactly the same in `blank-layout.component.scss` and both don't work with this solution.
We should remove it from both files and put it in `src/styles/ceph-custom/_toast.scss`

2020-09-01 11:58 UTC, tspmelo commented on src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.scss
> +    }
`table-filters` can be removed since we no longer use this.
Please remove it from the scss and html.

2020-09-01 15:06 UTC, tspmelo requested changes

2020-09-01 15:06 UTC, tspmelo commented on src/pybind/mgr/dashboard/frontend/src/styles/ceph-custom/_toast.scss
> +::ng-deep #toast-container {
we can't use `::ng-deep` outside of components:
```suggestion
#toast-container {
```

2020-09-04 09:11 UTC, tspmelo approved these changes

2020-09-04 09:12 UTC, merged