octopus: mgr/dashboard: Datatable catches select events from other datatables
ceph/ceph pull request #36899
Opened 2020-08-31 08:43 UTC by callithea

backport tracker: https://tracker.ceph.com/issues/47199

---

backport of https://github.com/ceph/ceph/pull/36590
parent tracker: https://tracker.ceph.com/issues/46903

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-08-31 08:44 UTC, callithea commented
jenkins test dashboard

2020-08-31 09:58 UTC, tspmelo requested changes
Please cherry-pick https://github.com/ceph/ceph/pull/36859 into the PR to fix the e2e failure.

2020-08-31 14:44 UTC, tspmelo approved these changes

2020-09-17 12:13 UTC, votdev approved these changes

2020-09-23 08:49 UTC, merged