common/options: change the default value of option osd_async_recovery_min_cost from 100 to 10
ceph/ceph pull request #36914
Opened 2020-08-31 19:32 UTC by vumrao

common/options: change the default value of option osd_async_recovery_min_cost from 100 to 10
While testing different RGW workloads we do not see async recovery benefits
specifically in EC pools with the default async recovery cost 100.
We changed the value from 100 to 10 and we saw a good amount of async recovery
activity during pgs recovery.

Fixes: https://tracker.ceph.com/issues/47223
Signed-off-by: Vikhyat Umrao <vikhyat@redhat.com>

2020-09-01 00:26 UTC, xiexingguo approved these changes

2020-09-02 22:00 UTC, neha-ojha commented
@xiexingguo wondering if you have encountered any more experimentation with `osd_async_recovery_min_cost`

2020-09-03 00:35 UTC, xiexingguo commented
> wondering if you have encountered any more experimentation with `osd_async_recovery_min_cost`

we default it to 1 in our product, which means we enable it whenever we can:)

2020-09-03 00:47 UTC, xiexingguo commented
on second thought I think we should probably leave it as it is, e.g., during upgrade, OSDs may talk with each other using a different `osd_async_recovery_min_cost` value, which might lead to a choose_acting loop.

2020-09-03 00:50 UTC, xiexingguo commented
> @xiexingguo wondering if you have encountered any more experimentation with `osd_async_recovery_min_cost`

See comment above.

2020-09-03 05:53 UTC, vumrao commented
> on second thought I think we should probably leave it as it is, e.g., during upgrade, OSDs may talk with each other using a different `osd_async_recovery_min_cost` value, which might lead to a choose_acting loop.

Hmm, if this option is injectable then I think it may not be a problem we can inject and update the ceph.conf before running upgrade or any kind of maintence work?

2020-09-03 06:13 UTC, xiexingguo commented
> Hmm, if this option is injectable then I think it may not be a problem we can inject and update the ceph.conf before running upgrade or any kind of maintence work?

Yeah, in practice we could do that, but then we need to fix the upgrage test suites first. 
Besides, we'd better not change it silently without noting its nasty side-effect in the PendingReleaseNote..

Can't you simply override the rgw_whatever_conf.yaml instead if you only cares about the rgw related test suites?

2020-09-03 06:14 UTC, xiexingguo commented
> Hmm, if this option is injectable then I think it may not be a problem we can inject and update the ceph.conf before running upgrade or any kind of maintence work?

Yeah, in practice we could do that, but then we need to fix the upgrage test suites first.
Besides, we'd better not change it silently without noting its nasty side-effect in the PendingReleaseNote..

Can't you simply override the rgw_whatever_conf.yaml instead if you only care about the rgw related test suites?

2020-09-03 23:59 UTC, neha-ojha commented
> > on second thought I think we should probably leave it as it is, e.g., during upgrade, OSDs may talk with each other using a different `osd_async_recovery_min_cost` value, which might lead to a choose_acting loop.
> 
> Hmm, if this option is injectable then I think it may not be a problem we can inject and update the ceph.conf before running upgrade or any kind of maintence work?

As @xiexingguo indicated, the downside of having mixed versions with different cost is very huge, it can lead to `choose_acting` looping. We had fixed a similar issue in https://github.com/ceph/ceph/pull/27798. If we really want to change the default, we'd have to add a `SERVER_*` check to verify that all OSDs are running the same version, before using the new default. I also think it is not worth backporting for the same reason.

2020-09-05 09:49 UTC, tchaikov requested changes
i think this change is the reason of
```
2020-09-04T17:08:57.641 INFO:tasks.ceph.osd.2.smithi098.stderr:    -1> 2020-09-04T17:08:57.613+0000 7f961136b700 -1 /build/ceph-16.0.0-5175-gda394fa67e0/src/common/Throttle.cc: In f
unction 'virtual int64_t Throttle::put(int64_t)' thread 7f961136b700 time 2020-09-04T17:08:57.608602+0000
2020-09-04T17:08:57.641 INFO:tasks.ceph.osd.2.smithi098.stderr:/build/ceph-16.0.0-5175-gda394fa67e0/src/common/Throttle.cc: 230: FAILED ceph_assert(count >= c)
2020-09-04T17:08:57.641 INFO:tasks.ceph.osd.2.smithi098.stderr:
2020-09-04T17:08:57.642 INFO:tasks.ceph.osd.2.smithi098.stderr: ceph version 16.0.0-5175-gda394fa67e0 (da394fa67e09acd45ad77a597bd9a9191845381d) pacific (dev)
2020-09-04T17:08:57.642 INFO:tasks.ceph.osd.2.smithi098.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x14b) [0x563ab0a6e597]
2020-09-04T17:08:57.643 INFO:tasks.ceph.osd.2.smithi098.stderr: 2: (ceph::__ceph_assertf_fail(char const*, char const*, int, char const*, char const*, ...)+0) [0x563ab0a6e772]
2020-09-04T17:08:57.643 INFO:tasks.ceph.osd.2.smithi098.stderr: 3: (Throttle::put(long)+0x3e4) [0x563ab1152454]
2020-09-04T17:08:57.643 INFO:tasks.ceph.osd.2.smithi098.stderr: 4: (OpRequest::_unregistered()+0x31) [0x563ab1405a71]
2020-09-04T17:08:57.643 INFO:tasks.ceph.osd.2.smithi098.stderr: 5: (TrackedOp::put()+0x229) [0x563ab0b39bb9]
2020-09-04T17:08:57.643 INFO:tasks.ceph.osd.2.smithi098.stderr: 6: (ReplicatedBackend::InProgressOp::~InProgressOp()+0x20) [0x563ab0e61860]
2020-09-04T17:08:57.644 INFO:tasks.ceph.osd.2.smithi098.stderr: 7: (ceph::common::RefCountedObject::put() const+0x1b2) [0x563ab114ad42]
2020-09-04T17:08:57.644 INFO:tasks.ceph.osd.2.smithi098.stderr: 8: (ReplicatedBackend::do_repop_reply(boost::intrusive_ptr<OpRequest>)+0x175) [0x563ab0e4b265]
2020-09-04T17:08:57.644 INFO:tasks.ceph.osd.2.smithi098.stderr: 9: (ReplicatedBackend::_handle_message(boost::intrusive_ptr<OpRequest>)+0x87) [0x563ab0e5e637]
2020-09-04T17:08:57.644 INFO:tasks.ceph.osd.2.smithi098.stderr: 10: (PGBackend::handle_message(boost::intrusive_ptr<OpRequest>)+0x97) [0x563ab0cd8327]
2020-09-04T17:08:57.644 INFO:tasks.ceph.osd.2.smithi098.stderr: 11: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0x6fd) [0x563ab0c75a9d]
2020-09-04T17:08:57.644 INFO:tasks.ceph.osd.2.smithi098.stderr: 12: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x17b) [0x563a
b0af35bb]
2020-09-04T17:08:57.645 INFO:tasks.ceph.osd.2.smithi098.stderr: 13: (ceph::osd::scheduler::PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x67) [0x
563ab0d5d167]
2020-09-04T17:08:57.645 INFO:tasks.ceph.osd.2.smithi098.stderr: 14: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x90c) [0x563ab0b1117c]
2020-09-04T17:08:57.646 INFO:tasks.ceph.osd.2.smithi098.stderr: 15: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x4ac) [0x563ab115b2ac]
2020-09-04T17:08:57.646 INFO:tasks.ceph.osd.2.smithi098.stderr: 16: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x563ab115e560]
```

see https://pulpito.ceph.com/kchai-2020-09-04_15:27:05-rados-wip-kefu-testing-2020-09-04-1852-distro-basic-smithi/5406186/

2020-09-10 10:02 UTC, vumrao commented
Thanks, @tchaikov. @neha-ojha and I would be discussing about this change as she explained above in her comment. We will see how we want to take this PR forward. We have done some additional tests and these new results showing correct behavior so maybe this change will not be required. I will update the PR with more details.

2020-09-15 12:00 UTC, vumrao commented
- There was a mistake in the crush failure domain that was causing EC pool pgs to not go under recovey_wait and because of that the results were invalid with a default cost 100 and we needed to reduce the default cost to 10 or 5. 
- Fixing the failure domain gave the correct test results with the default cost 100. Hence closing this PR as the default cost is good.

2020-09-15 12:00 UTC, closed without merging