ceph-volume: util.device.Device should handle tmpfs gracefully
ceph/ceph pull request #36950
Opened 2020-09-02 15:13 UTC by andrewschoen

When `ceph-volume simple scan` is ran against a cluster with
ceph-volume created bluestore OSDs the device is returned
as 'tmpfs'. This patch allows the Device class to gracefully
handle that value and correctly report to `simple scan` that
the OSD was not created by ceph-disk.

Resolves: rhbz#1872983

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-02 15:14 UTC, andrewschoen commented
jenkins test ceph-volume tox

2020-09-03 07:30 UTC, jan--f commented
jenkins test ceph-volume all

2020-09-03 08:59 UTC, jan--f requested changes
I see several issues with this:

1. I can not reproduce the bug. I see from https://bugzilla.redhat.com/show_bug.cgi?id=1872983 that this is 14.2.8 plus something. I attempted to reproduce this with 14.2.10 and the simple scan command comes back with rc=0. The diff between v14.2.8 and v14.2.10 doesn't explain the difference.
2. This fix is imho in the wrong place. The scan code should resolve the osd directory to a block device for the data partition. The `Device()` class is neither meant to be called with a `/var/lib/ceph/osd` path nor with 'tmpfs'.

But given (1.) we should first figure out why ceph-volume is behaving differently in the bug report compared to upstream.

2020-09-03 13:31 UTC, dsavineau commented
> 1. I can not reproduce the bug. I see from https://bugzilla.redhat.com/show_bug.cgi?id=1872983 that this is 14.2.8 plus something. I attempted to reproduce this with 14.2.10 and the simple scan command comes back with rc=0. The diff between v14.2.8 and v14.2.10 doesn't explain the difference.

Because the issue can't be reproduced with stable upstream nautilus release. The commit introducing the regression is only present in the nautilus branch and not in any 14.2.x release.

Downstream the specific commit has been cherry picked with both 14.2.8 and 14.2.10.

If you test this against the nautilus branch then you will hit the issue.

2020-09-03 14:16 UTC, yorabl commented
Tested this change and it worked for me. Thanks!

2020-09-03 14:21 UTC, andrewschoen commented
> I see several issues with this:
> 
> 1. I can not reproduce the bug. I see from https://bugzilla.redhat.com/show_bug.cgi?id=1872983 that this is 14.2.8 plus something. I attempted to reproduce this with 14.2.10 and the simple scan command comes back with rc=0. The diff between v14.2.8 and v14.2.10 doesn't explain the difference.

Can you reproduce with the tip of the nautilus branch? The BZ suggests that the bug was introduced with https://github.com/ceph/ceph/pull/35878, but I was unable to see how. I'll keep looking.

I had thought this was an existing bug when scanning against a ceph-volume created OSD, I could be wrong though. Does scanning against a 14.2.x created ceph-volume osd return a block device?

2020-09-03 15:45 UTC, andrewschoen commented
I tested with 14.2.8 and the Device class is getting passed ``tmpfs`` when scanning a ceph-volume created OSD. This line https://github.com/ceph/ceph/commit/41b1cee2a1476e8585660f3a6eaf17f2df33a145#diff-6993397b6f0532424603186ca62822bcR138 causes the issue because it assumes ``tmps`` is a ``vg/lv``.

This PR fixes the issue while keeping the change from the backport intact. Another option would be to just filter by path, I'm not sure we're gaining anything by filter by path or vg_name/lv_name.

2020-09-03 17:56 UTC, andrewschoen commented
> This PR fixes the issue while keeping the change from the backport intact. Another option would be to just filter by path, I'm not sure we're gaining anything by filter by path or vg_name/lv_name.

Actually, we can't only filter by path. I could instead make a change in ``scan`` to not make the second call to ``Device`` if ``encryption.legacy_encrypted`` returns ``tmpfs``. Would you prefer that?

2020-09-04 11:55 UTC, jan--f commented
> Actually, we can't only filter by path. I could instead make a change in `scan` to not make the second call to `Device` if `encryption.legacy_encrypted` returns `tmpfs`. Would you prefer that?

I think that would be the better fix, yes.

2020-09-04 14:53 UTC, andrewschoen commented
jenkins test ceph-volume tox

2020-09-04 14:58 UTC, andrewschoen commented
jenkins test ceph-volume all

2020-09-04 14:59 UTC, andrewschoen commented
> > Actually, we can't only filter by path. I could instead make a change in `scan` to not make the second call to `Device` if `encryption.legacy_encrypted` returns `tmpfs`. Would you prefer that?
> 
> I think that would be the better fix, yes.

Sounds good, I've made the change.

2020-09-04 15:03 UTC, andrewschoen commented
jenkins test ceph-volume tox

2020-09-04 15:11 UTC, andrewschoen commented
@jan--f have you seen this tox failure before? It doesn't look like it's related to my work here.

```
==================================== ERRORS ====================================
_______________ ERROR collecting ceph_volume/tests/test_main.py ________________
.tox/py3/lib/python3.5/site-packages/_pytest/python.py:552: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
.tox/py3/lib/python3.5/site-packages/_pytest/pathlib.py:520: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.5/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:986: in _gcd_import
    ???
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:673: in _load_unlocked
    ???
.tox/py3/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
ceph_volume/tests/test_main.py:3: in <module>
    from ceph_volume import main
ceph_volume/main.py:9: in <module>
    from ceph_volume import log, devices, configuration, conf, exceptions, terminal, inventory, drive_group
ceph_volume/drive_group/__init__.py:1: in <module>
    from .main import Deploy # noqa
E     File "/home/jenkins-build/build/workspace/ceph-volume-pr/src/ceph-volume/ceph_volume/drive_group/main.py", line 32
E       logger.error(f'argv: {argv}')
E                                  ^
E   SyntaxError: invalid syntax
=========================== short test summary info ============================
ERROR ceph_volume/tests/test_main.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.52s ===============================
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-volume-pr/src/ceph-volume/.tox/py3/bin/py.test -v ceph_volume/tests --ignore=ceph_volume/tests/functional (exited with code 2)
```

2020-09-08 07:36 UTC, jan--f commented
@andrewschoen yes I've seen those. Some jenkins hosts are still on py 3.5 and format strings were only introduced in 3.6. Fixed in #37039

2020-09-08 07:36 UTC, jan--f approved these changes
lgtm

2020-09-08 07:37 UTC, jan--f commented
jenkins test make check

2020-09-08 12:04 UTC, merged

2020-09-08 14:38 UTC, andrewschoen commented
@jan--f thanks for the merge! Would you please take a look at the backports as well? #36952 and #36953