rpm,deb: drop /etc/sudoers.d/cephadm
ceph/ceph pull request #36972
Opened 2020-09-03 09:47 UTC by smithfarm

Current behavior (without this patch) is:

1. cephadm package installs cephadm at /usr/sbin/cephadm
2. cephadm package installs /etc/sudoers.d/cephadm
3. !!! BUT this file refers to a non-existent executable (/usr/bin/cephadm) !!!
4. the PR that introduced this sudoers file (and this discrepancy) was merged in 2019
5. nobody noticed the discrepancy until now

My conclusion: the file /etc/sudoers.d/cephadm is not needed for cephadm to
work.

Fixes: https://tracker.ceph.com/issues/47112
Signed-off-by: Nathan Cutler <ncutler@suse.com>

2020-09-03 09:54 UTC, sebastian-philipp approved these changes

2020-09-03 10:26 UTC, tchaikov requested changes
could you replace "build/ops" with "rpm,debian" in the title?

2020-09-03 20:09 UTC, ddiss approved these changes

2020-09-04 01:50 UTC, tchaikov approved these changes

2020-09-07 06:43 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-09-06_13:32:55-rados-wip-kefu-testing-2020-09-06-2017-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-07_01:57:21-rados-wip-kefu-testing-2020-09-06-2017-distro-basic-smithi

failures tracked by 

- https://tracker.ceph.com/issues/47306
- https://tracker.ceph.com/issues/47179

and i tested locally using

```sh
../qa/run-standalone.sh osd-backfill-prio.sh
```

it passed.

2020-09-07 06:44 UTC, merged