ceph-volume: fix simple activate when legacy osd
ceph/ceph pull request #37093
Opened 2020-09-10 23:35 UTC by guits

`ceph-volume simple activate --all` relies on the presence of json files
in `/etc/ceph/osd` that was created with `ceph-volume simple scan`
command.

In a cluster lifecycle, it is very likely an OSD which was deployed with
ceph-disk at some point gets removed or replaced. It means the corresponding
json file in `/etc/ceph/osd` becomes unrelevant. It makes `ceph-volume
simple activate --all` fails because it tries to mount non existing
partitions.
The idea here is to simply warn the user that the osd described in the
json file doesn't exist anymore and exit properly instead of throwing an
error.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1877672

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-09-11 08:08 UTC, guits commented
jenkins test ceph-volume tox

2020-09-11 08:08 UTC, guits commented
jenkins test ceph-volume all

2020-09-11 16:07 UTC, andrewschoen approved these changes

2020-09-15 09:17 UTC, guits commented
@andrewschoen what are we missing to get this patch merged?

2020-09-15 12:25 UTC, jan--f requested changes
I really don't think this is the right approach. When a simple OSD is removed or re-deployed with lvm, the json file should be removed. We musn't return from activate with success when there was an error. This code path is also taken by the systemd units for simple OSDs, so this change here will no hide failures to bring up osds after reboot.

Instead we can add a `try..except` around the `activate` call the loop only if `--all` is passed...[here](https://github.com/ceph/ceph/blob/a1d78b3e1bb429080741cc23827ce1ce795e8757/src/ceph-volume/ceph_volume/devices/simple/activate.py#L285).

2020-09-16 08:11 UTC, jan--f commented
jenkins test ceph-volume all

2020-09-16 08:11 UTC, jan--f commented
jenkins test ceph-volume tox

2020-09-16 08:53 UTC, guits commented
jenkins test ceph-volume tox

2020-09-16 08:53 UTC, guits commented
jenkins test ceph-volume all

2020-09-16 08:54 UTC, jan--f requested changes
Please also add a tracker ticket and link it, so we can properly track the backports for this.

2020-09-16 09:09 UTC, jan--f commented
Sigh re. tox. @guits do you know if this is just an outdated jenkins worker or do we support a platform that still supports 3.5?

2020-09-16 09:14 UTC, guits commented
jenkins test ceph-volume tox

2020-09-16 09:14 UTC, guits commented
jenkins test ceph-volume all

2020-09-16 09:14 UTC, guits commented
> Please also add a tracker ticket and link it, so we can properly track the backports for this.

added the tracker details

2020-09-16 09:19 UTC, guits commented
> Sigh re. tox. @guits do you know if this is just an outdated jenkins worker or do we support a platform that still supports 3.5?

Looks like it's failing only when running on "slave-ubuntu" nodes

2020-09-16 11:09 UTC, guits commented
jenkins test ceph-volume tox

2020-09-16 11:09 UTC, guits commented
jenkins test volume lvm testing centos8-bluestore-dmcrypt

2020-09-16 11:09 UTC, guits commented
jenkins test ceph-volume lvm testing centos8-bluestore-dmcrypt

2020-09-16 11:10 UTC, guits commented
jenkins test lvm centos8-bluestore-dmcrypt

2020-09-16 11:11 UTC, guits commented
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

2020-09-16 12:22 UTC, jan--f approved these changes

2020-09-16 12:25 UTC, merged