mds: make purge_queue delete objects asynchronously and keep accepting pushes
ceph/ceph pull request #37095
Opened 2020-09-11 01:49 UTC by gmayyyha

Signed-off-by: Yanhu Cao <gmayyyha@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-22 01:09 UTC, gmayyyha commented
@batrick @ukernel Please help to review.

2020-10-22 01:25 UTC, batrick commented
@kotreshhr please review this.

2020-10-27 05:46 UTC, kotreshhr commented
> @kotreshhr please review this.

Sure @batrick I will take a look at it.

2020-11-17 09:54 UTC, kotreshhr reviewed
how is it determined that the objecter has slow requests ? The PR looks good to me otherwise.

2020-12-22 11:51 UTC, gmayyyha commented
> how is it determined that the objecter has slow requests ? The PR looks good to me otherwise.

 Under high load, storing data to osd may take a long time.

2020-12-22 20:52 UTC, batrick requested changes

2020-12-22 20:52 UTC, batrick commented on src/mds/PurgeQueue.cc
> +  C_IO_PurgeItem_Commit(PurgeQueue *pq, std::vector<PurgeItemCommitOp> &ops, uint64_t expire_to)
```suggestion
  C_IO_PurgeItem_Commit(PurgeQueue *pq, std::vector<PurgeItemCommitOp> ops, uint64_t expire_to)
```

2020-12-22 20:52 UTC, batrick commented on src/mds/PurgeQueue.cc
> +    : purge_queue(pq), expire_to(expire_to) {
```suggestion
    : purge_queue(pq), ops_vec(std::move(ops), expire_to(expire_to) {
```

2020-12-22 20:52 UTC, batrick commented on src/mds/PurgeQueue.cc
> +    ops_vec.swap(ops);
```suggestion
```

2020-12-22 20:52 UTC, batrick commented on src/mds/PurgeQueue.cc
> +    finisher.queue(new C_IO_PurgeItem_Commit(this, ops_vec, expire_to));
```suggestion
    finisher.queue(new C_IO_PurgeItem_Commit(this, std::move(ops_vec), expire_to));
```

2020-12-22 20:52 UTC, batrick commented on src/mds/PurgeQueue.h
> +  void _commit_ops(int r, std::vector<PurgeItemCommitOp> &ops_vec, uint64_t expire_to);
```suggestion
  void _commit_ops(int r, const std::vector<PurgeItemCommitOp>& ops_vec, uint64_t expire_to);
```

2020-12-22 20:52 UTC, batrick commented on src/mds/PurgeQueue.cc
> +void PurgeQueue::_commit_ops(int r, std::vector<PurgeItemCommitOp> &ops_vec, uint64_t expire_to)
```suggestion
void PurgeQueue::_commit_ops(int r, const std::vector<PurgeItemCommitOp>& ops_vec, uint64_t expire_to)
```

2020-12-22 20:52 UTC, batrick commented on src/mds/PurgeQueue.cc
> +      derr << "Invalid purge op: " << op.type << dendl;
```suggestion
      derr << "Invalid purge op: " << op.type << dendl;
      ceph_abort();
```

2020-12-23 03:02 UTC, gmayyyha commented
@batrick all done.

2020-12-23 17:10 UTC, batrick approved these changes

2021-01-13 16:22 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2021-01-12_22:03:59-fs-wip-pdonnell-testing-20210112.170550-distro-basic-smithi/

2021-01-13 16:27 UTC, merged