octopus: mgr/dashboard: Improve notification badge
ceph/ceph pull request #37090
Opened 2020-09-10 18:27 UTC by shyukri

backport tracker: https://tracker.ceph.com/issues/46961

---

backport of https://github.com/ceph/ceph/pull/36150
parent tracker: https://tracker.ceph.com/issues/45414

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-09-18 10:17 UTC, nizamial09 commented
jenkins test make check

2020-09-18 10:31 UTC, aaSharma14 approved these changes
LGTM! Thanks :)

2020-09-18 10:32 UTC, aaSharma14 commented
jenkins test api

2020-09-21 06:59 UTC, nizamial09 requested changes
Since octopus is not adapted the SASS implementation which is done on master only, some scss variables should be changed to match the octopus variable calling format.

2020-09-21 07:02 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.scss
> +    background-color: bd.$color-primary;
```suggestion
background-color: $color-primary;```

2020-09-21 07:02 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.scss
> +    border: 2px solid bd.$color-navbar-bg;
```suggestion
border: 2px solid $color-navbar-bg;
```

2020-09-21 07:03 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.scss
> +    background-color: bd.$color-solid-white;
```suggestion
background-color: $color-solid-white;
```

2020-09-21 07:03 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.scss
> +    border-color: bd.$color-primary;
```suggestion
border-color: $color-primary;
```

2020-09-23 18:30 UTC, nizamia09 commented
jenkins test make check

2020-09-24 09:44 UTC, smithfarm commented
```
194/196 Test #141: mgr-dashboard-frontend-unittests ........***Failed  389.36 sec

> ceph-dashboard@0.0.0 prebuild /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend
> npm run env_build


> ceph-dashboard@0.0.0 env_build /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend
> cp src/environments/environment.tpl.ts src/environments/environment.prod.ts && cp src/environments/environment.tpl.ts src/environments/environment.ts  && node ./environment.build.js

Environment variables have been set

> ceph-dashboard@0.0.0 build /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend
> export _locale=${LOCALE:-$npm_package_config_locale}; if [ ${_locale} = $npm_package_config_locale ]; then export _file=; else export _file=src/locale/messages.${_locale}.xlf; fi; ng build --outputPath=dist/${_locale} --i18nFile=${_file} --i18nLocale=${_locale} "--prod" "--progress=false"


chunk {0} runtime.49b89bfc1d3261f8791e.js (runtime) 2.33 kB [entry] [rendered]
chunk {1} 1.0e69327619843d9d6285.js () 287 kB  [rendered]
chunk {2} main.e203e6688296770b699a.js (main) 5.92 MB [initial] [rendered]
chunk {3} polyfills.513b02b42d061373f212.js (polyfills) 36.2 kB [initial] [rendered]
chunk {4} styles.58a2c96c3b87bd02e7a7.css (styles) 205 kB [initial] [rendered]
chunk {5} 5.790f6e27c71dc211049d.js () 168 kB  [rendered]
chunk {6} 6.86c707c27ae5cb97e30a.js () 193 kB  [rendered]
chunk {7} 7.8c5c2bbb556260a5cc3e.js () 258 kB  [rendered]
chunk {8} 8.da6c5e0c4437c7380e6f.js () 61.1 kB  [rendered]
chunk {scripts} scripts.76632aba1e576c7cc54a.js (scripts) 205 kB [entry] [rendered]
Date: 2020-09-23T18:45:56.136Z - Hash: d4dbe4fa8e5b80b5b8ac - Time: 187441ms

> ceph-dashboard@0.0.0 test:ci /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend
> JEST_SILENT_REPORTER_DOTS=true jest --coverage --reporters jest-silent-reporter

...................................................................
  ● Test suite failed to run

    src/app/core/navigation/notifications/notifications.component.spec.ts:24:16 - error TS2304: Cannot find name 'i18nProviders'.

    24     providers: i18nProviders
                      ~~~~~~~~~~~~~
    src/app/core/navigation/notifications/notifications.component.spec.ts:30:30 - error TS2339: Property 'inject' does not exist on type 'TestBedStatic'.

    30     summaryService = TestBed.inject(SummaryService);
                                    ~~~~~~
    src/app/core/navigation/notifications/notifications.component.spec.ts:31:35 - error TS2339: Property 'inject' does not exist on type 'TestBedStatic'.

    31     notificationService = TestBed.inject(NotificationService);
                                         ~~~~~~

......................................................................................................................................................................................................

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceph-dashboard@0.0.0 test:ci: `JEST_SILENT_REPORTER_DOTS=true jest --coverage --reporters jest-silent-reporter`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ceph-dashboard@0.0.0 test:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

2020-09-28 07:38 UTC, nizamial09 requested changes
Master uses a typescript version which is greater than the octopus. So TestBed.inject(...) is not usable in octopus codes, instead use TestBed.get(...)

2020-09-28 07:38 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.spec.ts
> +import { configureTestBed } from '../../../../testing/unit-test-helper';
```suggestion
import { configureTestBed, i18nProviders } from '../../../../testing/unit-test-helper';

2020-09-28 07:38 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.spec.ts
> +    notificationService = TestBed.inject(NotificationService);
```suggestion
    summaryService = TestBed.get(SummaryService);
    notificationService = TestBed.get(NotificationService);

2020-09-28 12:58 UTC, shyukri commented
jenkins test ceph dashboard

2020-09-28 13:03 UTC, shyukri commented
jenkins test dashboard

2020-09-28 14:15 UTC, shyukri commented
jenkins test docs

2020-09-28 14:15 UTC, shyukri commented
jenkins render docs

2020-09-28 15:12 UTC, nizamial09 approved these changes
LGTM! Thank you

2020-10-04 15:53 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri7-testing-2020-10-04-0852-octopus](https://trello.com/c/tLpholMk/1031-wip-yuri7-testing-2020-10-04-0852-octopus)

2020-10-08 18:55 UTC, yuriw commented
@epuertat @callithea this was tested, pls approve and merge at will

2020-10-08 19:17 UTC, callithea approved these changes
Lgtm, thank you!

2020-10-09 11:43 UTC, nizamial09 commented
jenkins test docs

2020-10-09 12:00 UTC, merged