[WIP] cephadm: Remove root and packaged mode
ceph/ceph pull request #37103
Opened 2020-09-11 11:37 UTC by jmolmo

Sharing to get fast feedback :-)
I think that with this modifications everything continues working ( i still do not know what will happen upgrading ).  Maybe i will need to add some modifications to support upgrade and version management but...
-> this is the first step to "package" cephadm script in a Python executable file having the possibility to "split" the code in several modules and to use libraries.

Advantages:
- Now only one way to use the cephadm tool, calling it directly.
- Removed tricks with injected_args and injected_stdin variables.
  No more source code modification in execution time
- Now the cephadm script used to install a cluster is linked to this cluster
  This allows us to have different ceph clusters in the same hosts
- Only need to install the cephadm script in the bootstrap host
      - The cephadm tool is spreaded each time a new host is added
      - The possibility to use the wrong cephadm tool ( installed as rpm or not) is completely avoided
      - We only need to get/install the cephadm tool in the bootstrap node. No need to access any external repo in the other cluster hosts
      - The containers (the mgr basically) uses always the cephadm script version installed in the cluster folder of the host.

 
- Things pending to do:
  - Version management: 
      - Avoid mix of cephadm versions in the cluster after an upgrade. 
      - Avoid to use incompatible versions of cephadm tool and cephadm orchestrator.
  - Upgrade cluster: Now we do not have packaged/root mode ... things have changed

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

2020-09-11 14:04 UTC, sebastian-philipp requested changes

2020-09-11 14:04 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/module.py
> +                    ['mkdir', '-p', os.path.dirname(cephadm_path)])
IMO this should go into /tmp/$(MGR's container image ID) or so.

2020-09-11 14:04 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/module.py
> +                    stdin=self._cephadm.encode('utf-8'))
prone to races. Might make sense to do *one* of those:

1. use a unique name
2. copy to a temp file name
3. execute a `mv` to the final file name

2020-09-11 14:04 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/module.py
> +        self._copy_cephadm(spec.hostname, spec.addr)
this is too brittle. We have to make sure we create the cephadm binary whenever it is missing

2020-09-11 14:12 UTC, sebastian-philipp commented
> * Now the cephadm script used to install a cluster is linked to this cluster
>   This allows us to have different ceph clusters in the same hosts

This is unrelated. Especially as two different clusters might run two different ceph versions

> * Only need to install the cephadm script in the bootstrap host
>   - The cephadm tool is spreaded each time a new host is added

We need to differenicate the cephadm tool that is used to deploy daemon and the cephadm convenience tool to ease debugging. both can differ to each other.

>   - The possibility to use the wrong cephadm tool ( installed as rpm or not) is completely avoided

Sounds like a different PR

>   - The containers (the mgr basically) uses always the cephadm script version installed in the cluster folder of the host.

actually we need to use the cephadm binary shipped within the MGR container image. 

> * Things pending to do:
>   
>   * Version management:

different PR
>     
>     * Avoid mix of cephadm versions in the cluster after an upgrade.

please not part of this PR

>     * Avoid to use incompatible versions of cephadm tool and cephadm orchestrator.
>   * Upgrade cluster: Now we do not have packaged/root mode ... things have changed

please not part of this PR

> 
> Signed-off-by: Juan Miguel Olmo Martínez [jolmomar@redhat.com](mailto:jolmomar@redhat.com)
> 
> * [ ]  References tracker ticket
> * [ ]  Updates documentation if necessary
> * [ ]  Includes tests for new functionality or reproducer for bug

2020-09-11 15:08 UTC, sebastian-philipp commented
@jmolmo the reason for the request to split your PR is that I'd like to divide the PR into at lease two parts:

1. purely technical PRs getting rid of e.g. `injected_args` that don't alter the visible behavior of cephadm
2. An change in semantics that do change how cephadm is seen, like merging the root and package mode. 

Cause I'd like to discuss (2) independent of (1) to get (1) merged soon to not block future development.

2020-09-14 18:31 UTC, sebastian-philipp commented
Please don't misunderstand me: General, I really like this PR!

2020-09-25 10:12 UTC, jmolmo commented on src/pybind/mgr/cephadm/module.py
> +                self._cephadm = f.read()
ok

2020-09-30 13:49 UTC, jmolmo commented
Closed in favour of new prs splitting the things proposed here

2020-09-30 13:49 UTC, closed without merging