mgr/dashboard: replace assertDictContainsSubset() with assertLessEqual()
ceph/ceph pull request #37158
Opened 2020-09-15 12:15 UTC by tchaikov

to silence the warnings like

tests/test_access_control.py::AccessControlTest::test_show_all_users
  /usr/lib/python3.6/unittest/case.py:1126: DeprecationWarning: assertDictContainsSubset is deprecated
    DeprecationWarning)

as assertDictContainsSubset() method was deprecated, see also
https://dev.rbcafe.com/python/python-3.5.1/whatsnew/3.2.html#unittest

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-15 15:35 UTC, votdev requested changes
I would like to suggest to apply this patch to only check what is important.
```
--- src/pybind/mgr/dashboard/tests/test_access_control.py	(revision fc933021ce20afafa251cc29d7c1df8f83b9ff15)
+++ src/pybind/mgr/dashboard/tests/test_access_control.py	(date 1600183982297)
@@ -389,8 +389,7 @@
             uroles.sort()
             user = self.exec_cmd('ac-user-add-roles', username=username,
                                  roles=[role])
-            self.assertLessEqual(
-                {'roles': uroles}.items(), user.items())
+            self.assertLessEqual(uroles, user['roles'])
         self.validate_persistent_user(username, uroles)
         self.assertGreaterEqual(user['lastUpdate'], user_orig['lastUpdate'])
 
@@ -398,9 +397,8 @@
         user_orig = self.test_create_user()
         user = self.exec_cmd('ac-user-add-roles', username="admin",
                              roles=['pool-manager', 'block-manager'])
-        self.assertLessEqual(
-            {'roles': ['block-manager', 'pool-manager']}.items(),
-            user.items())
+        self.assertLessEqual(['block-manager', 'pool-manager'],
+                             user['roles'])
         self.validate_persistent_user('admin', ['block-manager',
                                                 'pool-manager'])
         self.assertGreaterEqual(user['lastUpdate'], user_orig['lastUpdate'])
@@ -427,14 +425,13 @@
         user_orig = self.test_create_user()
         user = self.exec_cmd('ac-user-add-roles', username="admin",
                              roles=['pool-manager'])
-        self.assertLessEqual(
-            {'roles': ['pool-manager']}.items(), user.items())
+        self.assertLessEqual(['pool-manager'], user['roles'])
         self.validate_persistent_user('admin', ['pool-manager'])
         self.assertGreaterEqual(user['lastUpdate'], user_orig['lastUpdate'])
         user2 = self.exec_cmd('ac-user-set-roles', username="admin",
                               roles=['rgw-manager', 'block-manager'])
-        self.assertLessEqual(
-            {'roles': ['block-manager', 'rgw-manager']}.items(), user2.items())
+        self.assertLessEqual(['block-manager', 'rgw-manager'],
+                             user2['roles'])
         self.validate_persistent_user('admin', ['block-manager',
                                                 'rgw-manager'])
         self.assertGreaterEqual(user2['lastUpdate'], user['lastUpdate'])
@@ -461,8 +458,7 @@
         self.test_add_user_roles()
         user = self.exec_cmd('ac-user-del-roles', username="admin",
                              roles=['pool-manager'])
-        self.assertLessEqual(
-            {'roles': ['block-manager']}.items(), user.items())
+        self.assertLessEqual(['block-manager'], user['roles'])
         self.validate_persistent_user('admin', ['block-manager'])
 
     def test_del_user_roles_not_existent_user(self):
```

2020-09-15 16:11 UTC, tchaikov commented
@votdev thanks for your patch. applied and repushed. also i added your Signed-off-by line instead of mine.

2020-09-17 01:57 UTC, tchaikov commented
jenkins test make check

2020-09-17 04:43 UTC, tchaikov commented
@votdev ping?

2020-09-18 06:42 UTC, votdev approved these changes

2020-09-18 06:43 UTC, votdev commented
jenkins test api

2020-09-18 07:18 UTC, merged

2020-09-18 07:19 UTC, tchaikov commented
```
2020-09-18T06:58:39.752+0000 7f7577aa6540 -1  Processor -- bind unable to bind to v2:172.21.1.44:40464/0: (98) Address already in use
2020-09-18T06:58:39.752+0000 7f7577aa6540 -1  Processor -- bind was unable to bind. Trying again in 5 seconds 
2020-09-18T06:58:44.751+0000 7f7577aa6540 -1  Processor -- bind unable to bind to v2:172.21.1.44:40464/0: (98) Address already in use
2020-09-18T06:58:44.751+0000 7f7577aa6540 -1  Processor -- bind was unable to bind. Trying again in 5 seconds 
2020-09-18T06:58:49.751+0000 7f7577aa6540 -1  Processor -- bind unable to bind to v2:172.21.1.44:40464/0: (98) Address already in use
2020-09-18T06:58:49.751+0000 7f7577aa6540 -1  Processor -- bind was unable to bind after 3 attempts: (98) Address already in use
2020-09-18T06:58:49.751+0000 7f7577aa6540 -1 unable to bind monitor to [v2:172.21.1.44:40464/0,v1:172.21.1.44:40465/0]
Using guessed paths /home/jenkins-build/build/workspace/ceph-api/build/lib/ ['/home/jenkins-build/build/workspace/ceph-api/qa', '/home/jenkins-build/build/workspace/ceph-api/build/lib/cython_modules/lib.3', '/home/jenkins-build/build/workspace/ceph-api/src/pybind']
Traceback (most recent call last):
  File "../qa/tasks/vstart_runner.py", line 1596, in <module>
    exec_test()
  File "../qa/tasks/vstart_runner.py", line 1412, in exec_test
    remote.run(args=args, env=vstart_env, timeout=(3 * 60))
  File "../qa/tasks/vstart_runner.py", line 357, in run
    return self._do_run(**kwargs)
  File "../qa/tasks/vstart_runner.py", line 425, in _do_run
    proc.wait()
  File "../qa/tasks/vstart_runner.py", line 208, in wait
    raise CommandFailedError(self.args, self.exitstatus)
teuthology.exceptions.CommandFailedError: Command failed with status 1: ['../src/vstart.sh', '-n', '--nolockdep']
```