nautilus: mgr/dashboard: Monitoring: Fix for the infinite loading bar action
ceph/ceph pull request #37161
Opened 2020-09-15 13:08 UTC by nizamial09

**Only seen in nautilus**
Intended to fix the unusual behaviour in the All Alerts tab where the loading bar progressess continously until one of the alerts is selected.

To reproduce:
Navigate to cluster -> Monitoring -> All Alerts tab. You can see the progress bar at the bottom of the table.

Fixes: https://tracker.ceph.com/issues/47435

Signed-off-by: nizamial09 <nia@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-15 15:41 UTC, nizamial09 commented
jenkins test make check

2020-09-15 17:58 UTC, epuertat approved these changes
Thanks!

2020-09-16 08:59 UTC, nizamial09 commented
jenkins test make check

2020-09-16 11:57 UTC, nizamial09 commented
jenkins test make check

2020-09-16 13:13 UTC, nizamial09 commented
jenkins test make check

2020-09-16 13:51 UTC, alfonsomthd approved these changes

2020-09-17 05:38 UTC, smithfarm requested changes
Please remove the `nautilus: ` prefix from the commit message title.

We use that prefix on the PR titles, but not in the commit messages.

Thanks!

2020-09-17 07:30 UTC, nizamial09 commented
> Please remove the `nautilus: ` prefix from the commit message title.
> 
> We use that prefix on the PR titles, but not in the commit messages.
> 
> Thanks!

@smithfarm Done, thanks.

2020-09-17 11:30 UTC, nizamial09 commented
jenkins test dashboard

2020-09-18 10:57 UTC, merged