[DNM] client: add more debug logs for setxattr
ceph/ceph pull request #37174
Opened 2020-09-16 01:48 UTC by lxbsz

For: https://tracker.ceph.com/issues/47294
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-22 20:24 UTC, batrick commented
jenkins test api

2020-11-16 17:46 UTC, batrick commented
@lxbsz please rebase.

2020-11-17 01:48 UTC, lxbsz commented
> @lxbsz please rebase.

Done. Thanks.

2020-11-18 20:00 UTC, batrick commented
jenkins test docs

2020-12-24 04:36 UTC, batrick commented
Fix for this problem has been merged: https://tracker.ceph.com/issues/47294

Thanks @lxbsz

2021-01-08 18:38 UTC, batrick commented
https://tracker.ceph.com/issues/47294 is back, reopening this for testing

2021-01-08 23:24 UTC, batrick requested changes
and drop other debug lines. Then we can merge this.

2021-01-08 23:24 UTC, batrick commented on src/client/Client.cc
> +  ldout(cct, 1) << __func__ << ":" << __LINE__ << " name " << name << " value " << value << dendl;
```suggestion
  ldout(cct, 15) << __func__ << ":  name=" << name << dendl;
```

2021-01-08 23:24 UTC, batrick commented on src/client/Client.cc
> +      ldout(cct, 1) << __func__ << ":" << __LINE__ << " name " << name << " value " << value << dendl;
```suggestion
      ldout(cct, 20) << __func__ << ": waiting for latest osdmap" << dendl;
```

2021-01-08 23:24 UTC, batrick commented on src/client/Client.cc
> +      ldout(cct, 1) << __func__ << ":" << __LINE__ << " name " << name << " value " << value << dendl;
```suggestion
      ldout(cct, 20) << __func__ << ": finished waiting for latest osdmap: " << ec << dendl;
```

2021-01-09 22:27 UTC, batrick commented
superseded by #38836

2021-01-09 22:27 UTC, closed without merging

2021-01-10 01:31 UTC, lxbsz commented
Sorry, missed this.