doc: add "fs authorize" subcommand to ceph man page
ceph/ceph pull request #37197
Opened 2020-09-16 16:32 UTC by rishabh-d-dave

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-16 23:38 UTC, batrick requested changes

2020-09-16 23:38 UTC, batrick commented on doc/man/8/ceph.rst
> +``<perms>`` below can be ``r`` or ``rw``.
Cannot also `rwp` be valid?

2020-09-17 04:38 UTC, rishabh-d-dave commented on doc/man/8/ceph.rst
> +``<perms>`` below can be ``r`` or ``rw``.
Added.

2020-09-17 12:34 UTC, rishabh-d-dave commented
jenkins test make check

2020-09-17 13:42 UTC, batrick approved these changes

2020-09-17 13:46 UTC, merged