messenger: remove unused variable
ceph/ceph pull request #37210
Opened 2020-09-17 05:29 UTC by changchengx

Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-17 05:38 UTC, tchaikov approved these changes

2020-09-18 11:55 UTC, tchaikov requested changes
```
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5624-g515bfce2/rpm/el8/BUILD/ceph-16.0.0-5624-g515bfce2/src/tools/crimson/perf_async_msgr.cc: In constructor '{anonymous}::Server::Server(ceph::common::CephContext*, unsigned int)':
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5624-g515bfce2/rpm/el8/BUILD/ceph-16.0.0-5624-g515bfce2/src/tools/crimson/perf_async_msgr.cc:22:85: error: no matching function for call to 'Messenger::create(ceph::common::CephContext*&, const char [6], entity_name_t, const char [7], int, int)'
   22 |     msgr.reset(Messenger::create(cct, "async", entity_name_t::OSD(0), "server", 0, 0));
      |                                                                                     ^
In file included from /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5624-g515bfce2/rpm/el8/BUILD/ceph-16.0.0-5624-g515bfce2/src/tools/crimson/perf_async_msgr.cc:9:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5624-g515bfce2/rpm/el8/BUILD/ceph-16.0.0-5624-g515bfce2/src/msg/Messenger.h:161:21: note: candidate: 'static Messenger* Messenger::create(ceph::common::CephContext*, const string&, entity_name_t, std::string, uint64_t)'
  161 |   static Messenger *create(CephContext *cct,
      |                     ^~~~~~
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5624-g515bfce2/rpm/el8/BUILD/ceph-16.0.0-5624-g515bfce2/src/msg/Messenger.h:161:21: note:   candidate expects 5 arguments, 6 provided

```
see https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2020-09-18-1517/515bfce2ac24d438c3b2a654816fdd05759126c0/crimson/229779/


@changchengx could you update the crimson tests accordingly?

2020-09-21 01:36 UTC, changchengx commented
@tchaikov 
Sorry for missing verifying crimson build results locally.
With this PR, there's no problem when building with enabling crimson.
Let's wait for Jenkin's UT test result.

2020-09-21 02:03 UTC, tchaikov approved these changes

2020-09-21 09:36 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-09-20_14:54:48-rados-wip-kefu-testing-2020-09-18-1517-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-20_14:54:48-rados-wip-kefu-testing-2020-09-18-1517-distro-basic-smithi/

2020-09-21 09:37 UTC, merged