ceph-volume: add no-systemd argument to zap
ceph/ceph pull request #37221
Opened 2020-09-18 03:45 UTC by X0Ken

In some container deployment scenarios, systemd services are not
used, so the no-systemd parameter is useful.

Signed-off-by: wanghongxu <wanghongxu@t2cloud.net>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-18 09:30 UTC, X0Ken commented
jenkins test ceph-volume all

2020-09-18 09:31 UTC, X0Ken commented
jenkins test ceph-volume tox

2020-09-18 12:08 UTC, jan--f requested changes
Thanks! The code looks good but I'd like to ask you to open a tracker ticket on tracker.ceph.com and add the following line to your commit: `Fixes: <tracker url>`

This helps us a lot with backporting.

2020-09-18 12:13 UTC, jan--f requested changes

2020-09-18 12:13 UTC, jan--f commented on src/ceph-volume/ceph_volume/devices/lvm/zap.py
> +            help='Skip check systemd units',
```suggestion
            help='Skip systemd unit checks',
```

2020-09-18 14:52 UTC, X0Ken commented
jenkins test ceph-volume tox

2020-09-18 14:53 UTC, X0Ken commented
jenkins test ceph-volume all

2020-09-20 01:25 UTC, X0Ken commented
jenkins test ceph-volume all

2020-09-20 01:27 UTC, X0Ken commented
jenkins test make check

2020-09-23 09:38 UTC, jan--f commented
@X0Ken please rebase on current master to fix make check

2020-10-04 07:19 UTC, jan--f commented
jenkins test ceph-volume all

2020-10-04 07:19 UTC, jan--f commented
jenkins test ceph-volume tox

2020-10-05 06:34 UTC, jan--f approved these changes

2020-10-05 07:42 UTC, merged