MDS: assert(in->get_parent_dir()) when open_undef_inodes_dirfrags
ceph/ceph pull request #37294
Opened 2020-09-22 06:32 UTC by simpleshuai

MDS: assert(in->get_parent_dir()) when open_undef_inodes_dirfrags
it's better fail at begining
---------------------------------------
bool MDCache::open_undef_inodes_dirfrags(){  
  .....
  for (set<CInode*>::iterator p = rejoin_undef_inodes.begin();
       p != rejoin_undef_inodes.end();
       ++p) {
    CInode *in = *p;
    ceph_assert(!in->is_base());
    fetch_queue.insert(in->get_parent_dir());
  }
......
  for (set<CDir*>::iterator p = fetch_queue.begin();
       p != fetch_queue.end();
       ++p) {
     CDir *dir = *p; **// maybe NULL Ptr for unexpected situation**

Signed-off-by: redickwang <redickwang@tencent.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-22 16:56 UTC, batrick commented
Is this helping you debug an issue or just defensive coding?

2020-09-22 16:58 UTC, batrick requested changes
Please fix your commit message:

````
mds: assert when inode has no parent directory

assert(in->get_parent_dir()) when open_undef_inodes_dirfrags. Elements in fetch_queue maybe NULL for unexpected situation, it's better fail at the beginning

Fixes: https://tracker.ceph.com/issues/47571

Signed-off-by: redickwang <redickwang@tencent.com>
````

See also my usual copy paste:

Please [title your commits according to the conventions of this project](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title). This is required for your PR to be merged.

See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

2020-09-23 01:40 UTC, simpleshuai commented
> Please fix your commit message:
> 
> ```
> mds: assert when inode has no parent directory
> 
> assert(in->get_parent_dir()) when open_undef_inodes_dirfrags. Elements in fetch_queue maybe NULL for unexpected situation, it's better fail at the beginning
> 
> Fixes: https://tracker.ceph.com/issues/47571
> 
> Signed-off-by: redickwang <redickwang@tencent.com>
> ```
> 
> See also my usual copy paste:
> 
> Please [title your commits according to the conventions of this project](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title). This is required for your PR to be merged.
> 
> See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

Done

2020-09-23 15:11 UTC, batrick commented
> Is this helping you debug an issue or just defensive coding?

??

2020-09-27 01:22 UTC, simpleshuai commented
> defensive coding

defensive coding

2020-09-27 01:29 UTC, simpleshuai commented
> > Is this helping you debug an issue or just defensive coding?
> 
> ??

defensive coding， inode's parent directory could be NULL when metadata is damaged

2020-10-13 17:37 UTC, batrick approved these changes

2020-10-20 02:24 UTC, batrick commented
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20201013.174240

2020-10-20 02:27 UTC, merged