msgr: correct default daemon port range
ceph/ceph pull request #37380
Opened 2020-09-24 01:35 UTC by changchengx

The default port range should be between:
  [ms_bind_port_min, ms_bind_port_max]

Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-09-24 04:29 UTC, tchaikov requested changes
IMHO, the title is a kind of misleading. instead of correcting the comment, this change removes the stale comment which does not apply in this context. also, it remove the macro not referenced anywhere.

2020-09-24 04:30 UTC, tchaikov commented
@ukernel do you think it'd be a good idea to drop https://github.com/torvalds/linux/blob/6b2edf27fe26c73cd67b6bf5ffb23dce882e1455/include/linux/ceph/msgr.h#L11-L18 ? i cannot see any code referencing these macros.

2020-09-25 01:47 UTC, changchengx commented
@tchaikov 
I think we could also file one kernel patch to remove it.

2020-09-25 03:30 UTC, tchaikov approved these changes

2020-09-25 09:40 UTC, idryomov approved these changes

2020-09-26 05:01 UTC, tchaikov commented
https://pulpito.ceph.com/kchai-2020-09-26_01:51:27-rados-wip-kefu-testing-2020-09-25-2324-distro-basic-smithi/

2020-09-26 05:02 UTC, merged

2020-09-26 06:53 UTC, tchaikov commented
> @tchaikov
> I think we could also file one kernel patch to remove it.

i'd defer this to kernel developers.