octopus: mgr/dashboard: cluster > manager modules
ceph/ceph pull request #37434
Opened 2020-09-28 14:08 UTC by avanthakkar

backport tracker: https://tracker.ceph.com/issues/47675

---

backport of https://github.com/ceph/ceph/pull/37387
parent tracker: https://tracker.ceph.com/issues/47484

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-09-30 06:12 UTC, alfonsomthd approved these changes

2020-09-30 06:30 UTC, nizamial09 approved these changes

2020-10-02 11:55 UTC, votdev requested changes
I'm not sure if this PR should introduce `src/pybind/mgr/dashboard/frontend/cypress/integration/ui/navigation.po.ts`. The origin PR only [fixes the menu name](https://github.com/ceph/ceph/pull/37387/files#diff-b6c88551e037b8bc300f0a0952689dc1R29). This PR instead will introduce a completely new test case that is not related to the PR. IMO this file should be removed. If the file to be fixed is not in the branch, then it doesn't need to be added.

2020-10-03 01:17 UTC, smithfarm requested changes
What @votdev said. The changes in src/pybind/mgr/dashboard/frontend/cypress/integration/ui/navigation.po.ts are problematic. The master PR https://github.com/ceph/ceph/pull/37387/commits/30b41fba49c9c128559117ccbce349389a6198a3 changes a single character in this file, but the octopus backport adds the entire file? This is not correct. If you wanted to add the file to octopus, you would need to backport the PR that introduced the file in master.

2020-10-04 16:12 UTC, smithfarm commented
@avanthakkar Your commit message's Conflicts section still says:

```
 Conflicts:
	src/pybind/mgr/dashboard/frontend/cypress/integration/ui/navigation.po.ts
  - Adapted changes in this file to octopus code.
```

Would it make sense, instead of "Adapted changes in this file to octopus code", to write something more descriptive, like "Omitted the changes to this file because the file does not exist in octopus"?

2020-10-04 17:30 UTC, avanthakkar commented
> @avanthakkar Your commit message's Conflicts section still says:
> 
> ```
>  Conflicts:
> 	src/pybind/mgr/dashboard/frontend/cypress/integration/ui/navigation.po.ts
>   - Adapted changes in this file to octopus code.
> ```
> 
> Would it make sense, instead of "Adapted changes in this file to octopus code", to write something more descriptive, like "Omitted the changes to this file because the file does not exist in octopus"?

Yes, sure!

2020-10-04 19:22 UTC, avanthakkar commented
jenkins test dashboard

2020-10-06 12:51 UTC, s0nea commented
jenkins test dashboard

2020-10-06 13:00 UTC, s0nea approved these changes
LGTM

2020-10-20 12:07 UTC, avanthakkar commented
jenkins test dashboard

2020-10-21 13:53 UTC, avanthakkar commented
> I'm not sure if this PR should introduce `src/pybind/mgr/dashboard/frontend/cypress/integration/ui/navigation.po.ts`. The origin PR only [fixes the menu name](https://github.com/ceph/ceph/pull/37387/files#diff-b6c88551e037b8bc300f0a0952689dc1R29). This PR instead will introduce a completely new test case that is not related to the PR. IMO this file should be removed. If the file to be fixed is not in the branch, then it doesn't need to be added.

Removed it! Can you PTAL if everything else look good?

2020-10-21 14:22 UTC, votdev approved these changes

2020-10-21 16:28 UTC, merged