mgr/dashboard: Show warning when replicated size is 1
ceph/ceph pull request #37523
Opened 2020-10-02 09:13 UTC by Exotelis

Issues a warning when creating a replicated pool and the replicated size
is 1. It won't stop the user from creating the pool, but will give the
user a hint that no replication will be created.

This pr is also going to add a new color to the bootstrap theme. In my opinion the orange has a better contrast on a white background. We should discuss if it would make sense to use orange for warnings instead of yellow.

Fixes: https://tracker.ceph.com/issues/42404
Signed-off-by: Sebastian Krah <skrah@suse.com>

![replicated_size1](https://user-images.githubusercontent.com/7863239/94907321-44c56e00-04a0-11eb-870a-109bb6197d70.png)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-02 09:27 UTC, alfonsomthd commented
jenkins test dashboard

2020-10-02 10:15 UTC, votdev requested changes

2020-10-02 10:15 UTC, votdev commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
> +                    i18n>Note: A size of 1 will not create a replication of the
```suggestion
                    i18n>A size of 1 will not create a replication of the
```

2020-10-02 10:15 UTC, votdev commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
> +                object. The 'Replicated size' includes the object itself</span>
```suggestion
                object. The 'Replicated size' includes the object itself.</span>
```

2020-10-05 07:56 UTC, s0nea approved these changes

2020-10-05 07:56 UTC, s0nea commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-form/pool-form.component.html
> +                    i18n>A size of 1 will not create a replication of the
Just as an idea:

```suggestion
                    i18n>A size of 1 will not provide a replication of the
```

2020-10-05 13:26 UTC, callithea approved these changes
lgtm

2020-10-05 20:33 UTC, nizamial09 approved these changes
LGTM!

2020-10-05 20:38 UTC, nizamial09 commented
Also yeah it would be good if we can fix a color for the warning (orange or yellow) I prefer the orange as it looks better. @Exotelis

2020-10-06 09:11 UTC, merged

2020-10-06 19:49 UTC, epuertat commented
Sorry, I came late to this one (crazy week 😅  ). I wonder if we should allow users to make sub-optimal choices. If Ceph recommends a minimum of 3 replicas, we shouldn't probably allow users to set anything less than that. Additionally, more than 3 replicas is unusual as well (I bet 99% of the replicated deployments have just 3 replicas), so... Does it make sense to simply allow users to choose the number of replicas at all? If users want to try with 1 or 5 replicas, it's likely they're advanced users that won't use the dashboard at all.