cephadm: Push ceph-iscsi config options into mon-store
ceph/ceph pull request #37588
Opened 2020-10-08 01:04 UTC by matthewoliver

Currently the ceph-iscsi config options get placed in the
iscsi-gateway.cfg but this is volume mounted into the container and
lives under `/var/lib/ceph/<fsid>/<iscsi service>/iscsi-gateway.cfg`. This is
fine for day 1 situations but horrible on day 2.

To make this easier a PR was pushed to ceph-iscsi[0] which taught it how
to look in the mon config-key store for values to config options. This
took the same approach as RGW. A config value starting with a
`config://` will be treated as key in the mon store. E.g:

  config://my/awesome/key

Will go look for the value of `my/awesome/key`.

Now that the ceph-iscsi PR has merged, it's time to put this into
cephadm/orch.
This patch adds a new option to the iscsi spec called `mon_key_prefix`
which defaults to `iscsi`. Which allows someone to deploy a ceph-iscsi
service with either globally shared options or can seperate as required.

Note that because we set config-key get cap for the iscsi user to only
access keys starting with `iscsi/` this is also a hard requirement. By
default it'll place config options under `iscsi/..` keys:

  iscsi/trusted_ip_list
  iscsi/api_port
  iscsi/api_user
  iscsi/api_password
  iscsi/api_secure

If you want to have say 2 different sets some these options you could
always deploy services with different `mon_key_prefix`'s say as
`iscsi/datacenterA` and `iscsi/datacenterB`. Then they look at different
locations:

  iscsi/datacenterA/trusted_ip_list
  iscsi/dataventerA/api_port
  ...
  iscsi/datacenterB/trusted_ip_list
  iscsi/dataventerB/api_port
  ...

Best part is, now if you want to change a value, you don't need to dig
around and find a config file or do a redeloy, just run a `ceph config-key set` and
then restart the service.

[0] https://github.com/ceph/ceph-iscsi/pull/217

Signed-off-by: Matthew Oliver <moliver@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-08 01:06 UTC, matthewoliver commented on src/pybind/mgr/cephadm/services/iscsi.py
> +                            f'allow command "config-key get" with "key" prefix "iscsi/"',
opps I can remove the 'f' here. I was going to make the prefix cap match what ever the user put in. But currently the ceph-iscsi ssl certs look for iscsi/ so we need it here. I might go and push the ssl certs into the ceph-iscsi config file so we can loose this requirement.

2020-11-20 15:04 UTC, sebastian-philipp requested changes

2020-11-20 15:04 UTC, sebastian-philipp commented on src/python-common/ceph/deployment/service_spec.py
> +            self.mon_config_prefix = 'iscsi'
hm. well. `service_name` `iscsi.iscsi`, thus won't work here. We could use `service_id`. but that would need to be supported by the daemon. which is not the case. thus :-1: for changing this. but adding a code comment wouldn't be wrong.

2021-01-28 16:25 UTC, sebastian-philipp commented
right now, I don't have the bandwidth to look into this.

2021-09-29 13:07 UTC, closed without merging

2021-10-15 08:53 UTC, sebastian-philipp commented
Hi @ideepika As you're looking into iscsi right now: Is this change something we want in eventually?

2021-10-21 09:11 UTC, ideepika commented
> Hi @ideepika As you're looking into iscsi right now: Is this change something we want in eventually?

hey @sebastian-philipp +1 to the idea, checked with other folks as well, right now in other RBD pieces(rbd mirroring) as well we support similar way letting a user set config values, and having multiple ways to set config values should be a good addition overall.