mds: ignore sequence values on REQUEST_CLOSE
ceph/ceph pull request #37619
Opened 2020-10-09 16:05 UTC by jtlayton

When unmounting, clients send a REQUEST_CLOSE and just wait for the
reply before eventually giving up after a timeout and proceeding. If the
request crossed paths with a message from the server that bumped the seq
number, then the MDS will drop the request on the floor.

The clients never retransmit this request so the client just hangs,
sometimes even resulting in a blocklisting event when caps aren't
returned.

A REQUEST_CLOSE is an indicator that the client is unmounting. It's not
going to decide to not do that because the sequence number changed. Make
the MDS ignore the sequence on a REQUEST_CLOSE.

Fixes: https://tracker.ceph.com/issues/47563
Signed-off-by: Jeff Layton <jlayton@redhat.com>

2020-10-09 16:08 UTC, jtlayton commented
I had originally done a patch to have the client retry REQUEST_CLOSE every second until it got a response, but @idryomov objected (probably correctly). This is an alternative approach -- have the MDS ignore seq values on REQUEST_CLOSE, and we'll also change the client to not bother waiting on the reply.

2020-10-09 17:32 UTC, batrick approved these changes

2020-10-09 18:52 UTC, batrick commented
jenkins test api

2020-10-09 20:25 UTC, jtlayton commented
Note too that I intend to couple this with a patchset for the kclient to not block on unmounting, and we should probably make libcephfs follow a similar approach.

2020-10-10 18:41 UTC, idryomov requested changes
> The clients never retransmit this request so the client just hangs,
> sometimes even resulting in a blocklisting event when caps aren't
> returned.

After taking a look at the surrounding code, it really seemed like it had been written with the expectation that REQUEST_CLOSE would be resent, so I dug around in the clients.  I don't fully understand these "push" sequence numbers yet, but there is probably some race that requires the client to confirm that it saw the sequence number, even if the session is about to go.  @liewegas is probably the only one who might remember at this point.

ceph-fuse appears to send REQUEST_CLOSE whenever it receives a "push" message (CEPH_MSG_CLIENT_CAPS, CEPH_MSG_CLIENT_SNAP, CEPH_MDS_LEASE_REVOKE, etc) with the session in STATE_CLOSING.  See got_mds_push() in Client.cc.

The kernel client doesn't to that, but it has the code to retry REQUEST_CLOSE every five seconds.  See check_session_state() which is called from delayed_work() in mds_client.c.  It looks like it got broken by Xiubo's commit fa9967734227 ("ceph: fix potential mdsc use-after-free crash") which effectively disabled all of delayed_work() if mdsc->stopping is set.
If we fix that, we should be good.

2020-10-12 11:17 UTC, jtlayton commented
That may be how it worked before, but what purpose does the sequence number serve here? AFAICS, there is no benefit in having the MDS pay attention to the sequence on a REQUEST_CLOSE. We should just ignore it and do what the client is asking.

2020-10-12 12:45 UTC, lxbsz commented
@jtlayton 
BTW, if the MDS is doing the revoking, and if we just ignore and close the session here, will the MDS timeout waiting the revoking reply likes in [1] ?

[1] https://tracker.ceph.com/issues/47565

2020-10-12 13:13 UTC, jtlayton commented
> @jtlayton
> BTW, if the MDS is doing the revoking, and if we just ignore and close the session here, will the MDS timeout waiting the revoking reply likes in [1] ?

I wouldn't think so. If the MDS is tearing down the session, then it should wake up those waiters as part of the state teardown. If not, then that sounds potentially like another bug.

2020-10-12 13:22 UTC, lxbsz commented
> > @jtlayton
> > BTW, if the MDS is doing the revoking, and if we just ignore and close the session here, will the MDS timeout waiting the revoking reply likes in [1] ?
> 
> I wouldn't think so. If the MDS is tearing down the session, then it should wake up those waiters as part of the state teardown. If not, then that sounds potentially like another bug.

Yeah, this sounds sane, I didn't check the code carefully so was not sure. As @idryomov mentioned we maybe changing the proto here with this changes.

2020-10-12 13:54 UTC, jtlayton commented
Yes, if we're going to keep the client retransmitting then we probably do want to continue just dropping these requests on the floor when the seq number doesn't match. I'll close this out and pursue a client-side-only fix.

2020-10-12 13:54 UTC, closed without merging