qa/tasks: add 'nosharesb' mount option to disable sharing superblock
ceph/ceph pull request #37652
Opened 2020-10-13 10:59 UTC by lxbsz

When unmounting, the kernel may defer detaching the mount from the
tree, so when do a new mount it will see a ghost mountpoint.

Fixes: https://tracker.ceph.com/issues/46883
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-13 15:20 UTC, batrick approved these changes

2020-10-13 17:23 UTC, batrick commented
cc @jtlayton

2020-10-14 02:47 UTC, lxbsz commented
> Oh, this option is not yet available in the kernel, right? So let's hold off on this until that's merged or a better alternative is found.

Yeah, forgot to mention it.

2020-10-14 19:02 UTC, jtlayton commented
I don't think we want this. This seems like a hacky workaround for something that's possibly a real bug. I think we ought to find and fix the root cause if there are problems with unmounting. At the very least, I'd like a thorough explanation of why this is needed.

2020-10-15 07:13 UTC, lxbsz commented
> I don't think we want this. This seems like a hacky workaround for something that's possibly a real bug. I think we ought to find and fix the root cause if there are problems with unmounting. At the very least, I'd like a thorough explanation of why this is needed.

Okay, let's try to trigger a crash manully when it fails to umount and return busy to get the coredump.

2020-10-15 07:16 UTC, lxbsz commented
@jtlayton @batrick 
I am also thinking should we enable the debug info for fs/ceph/* files for the tethology test ? For many issues it will be very helpful if we have that logs.

2020-10-15 09:47 UTC, lxbsz commented
@batrick @jtlayton 
This should be caused by not killing the background process, which is holding the mountpoint directory file descripters, before unmounting the mountpoint. More detail please see [1] .

I have pushed a new commit, this should fix it. Please take a look, thanks.

[1] https://tracker.ceph.com/issues/46883?issue_count=27&issue_position=11&next_issue_id=47005&prev_issue_id=47565#note-9

2020-10-15 19:52 UTC, batrick requested changes

2020-10-15 19:52 UTC, batrick commented on qa/tasks/cephfs/kernel_mount.py
>              opts += 'name=' + self.client_id
```suggestion
            opts += ',name=' + self.client_id
```

2020-10-16 00:59 UTC, lxbsz commented on qa/tasks/cephfs/kernel_mount.py
>              opts += 'name=' + self.client_id
Done. Thanks.

2020-10-20 08:15 UTC, rishabh-d-dave approved these changes

2020-10-21 06:11 UTC, mchangir reviewed
nit: typo in `unmouting` word in commit subject line

2020-10-21 08:04 UTC, lxbsz commented
> nit: typo in `unmouting` word in commit subject line

Done, thanks :-)

2020-10-25 23:23 UTC, batrick approved these changes
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20201024.032205

failures unrelated

2020-10-25 23:26 UTC, merged