nautilus: mon: have 'mon stat' output json as well
ceph/ceph pull request #37706
Opened 2020-10-19 09:01 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/47899

---

backport of https://github.com/ceph/ceph/pull/37635
parent tracker: https://tracker.ceph.com/issues/46816

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-10-19 10:46 UTC, tchaikov approved these changes

2020-10-19 10:51 UTC, tchaikov requested changes

2020-10-19 10:51 UTC, tchaikov commented on src/mon/MonmapMonitor.cc
> +      mon->monmap->dump_summary(f.get());
might want to backport 3e7c185bd4b2312f9801b8664fb175801c904871 as well

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonmapMonitor.cc:282:20: error: 'class MonMap' has no member named 'dump_summary'
  282 |       mon->monmap->dump_summary(f.get());
      |                    ^~~~~~~~~~~~
src/mon/CMakeFiles/mon.dir/build.make:350: recipe for target 'src/mon/CMakeFiles/mon.dir/MonmapMonitor.cc.o' failed
```

2020-10-26 15:05 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri7-testing-2020-10-26-0802-nautilus](https://trello.com/c/aTkrbBpe/1046-wip-yuri7-testing-2020-10-26-0802-nautilus)

2020-10-26 16:07 UTC, smithfarm commented
@tchaikov Done

2020-10-26 20:57 UTC, smithfarm commented
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonMap.cc: In member function 'void MonMap::dump_summary(ceph::Formatter*) const':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonMap.cc:366:48: error: 'to_string' is not a member of 'ceph'
  366 |   f->dump_string("min_mon_release_name", ceph::to_string(min_mon_release));
      |                                                ^~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonMap.cc:366:48: note: suggested alternatives:
In file included from /usr/include/c++/9/string:55,
                 from /usr/include/c++/9/stdexcept:39,
                 from /usr/include/c++/9/optional:38,
                 from /usr/include/c++/9/bits/node_handle.h:39,
                 from /usr/include/c++/9/bits/stl_tree.h:72,
                 from /usr/include/c++/9/set:60,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/encoding.h:17,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/uuid.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonMap.h:25,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonMap.cc:4:
/usr/include/c++/9/bits/basic_string.h:6598:3: note:   'std::__cxx11::to_string'
 6598 |   to_string(long double __val)
      |   ^~~~~~~~~
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/uuid.h:15,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonMap.h:25,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MonMap.cc:4:
/opt/ceph/include/boost/uuid/uuid_io.hpp:149:20: note:   'boost::uuids::to_string'
  149 | inline std::string to_string(uuid const& u)
      |                    ^~~~~~~~~
src/CMakeFiles/common-objs.dir/build.make:183: recipe for target 'src/CMakeFiles/common-objs.dir/mon/MonMap.cc.o' failed
make[3]: *** [src/CMakeFiles/common-objs.dir/mon/MonMap.cc.o] Error 1
```

2020-11-09 17:02 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri-testing-2020-11-09-0849-nautilus](https://trello.com/c/8QRaMPqU/1061-wip-yuri-testing-2020-11-09-0849-nautilus)

2020-11-16 10:45 UTC, jecluis approved these changes
lgtm

2020-11-16 11:14 UTC, smithfarm commented
jenkins test make check (logs are gone)

2020-11-20 12:31 UTC, smithfarm commented
@yuriw Would be nice to have this one in 14.2.15.

2020-11-20 12:31 UTC, smithfarm commented
jenkins test make check

2020-11-20 12:33 UTC, smithfarm commented
@tchaikov I tried to fulfill your change request. Please take another look?

2020-11-20 12:53 UTC, tchaikov approved these changes

2020-11-24 17:47 UTC, merged