cephadm: log console to stdout
ceph/ceph pull request #37712
Opened 2020-10-19 19:06 UTC by dsavineau

Currently the cephadm CLI console uses stderr for info/debug/warning
statements instead of stdout.
This is coming from the logging stream handler that uses sys.stderr by
default [1].

Fixes: https://tracker.ceph.com/issues/47905

[1] https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-20 16:41 UTC, mgfritch approved these changes

2020-10-21 14:23 UTC, batrick approved these changes

2020-10-22 05:52 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-10-21_07:01:44-rados-wip-kefu-testing-2020-10-21-1144-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-10-22_03:25:39-rados-wip-kefu-testing-2020-10-21-2116-distro-basic-smithi/

quite a few cephadm tests failed. not sure if they are related.

2020-10-24 03:39 UTC, tchaikov commented
https://pulpito.ceph.com/kchai-2020-10-23_10:21:03-rados-wip-kefu-testing-2020-10-23-1631-distro-basic-smithi

2020-11-04 18:54 UTC, mgfritch commented
QA run failed:
https://pulpito.ceph.com/mgfritch-2020-11-03_14:22:58-rados:cephadm-wip-mgfritch-testing-2020-11-02-1045-distro-basic-smithi/

Failures:
https://tracker.ceph.com/issues/48118
https://tracker.ceph.com/issues/48119
https://tracker.ceph.com/issues/48120

2020-11-04 18:55 UTC, mgfritch requested changes
Unfortunately this is not going to work as many of cephadm operations depend on using stderr for a log channel and stdout for JSON output ... (https://github.com/ceph/ceph/pull/37712#issuecomment-721912058)

2020-11-05 06:41 UTC, guits commented
> Unfortunately this is not going to work as many of cephadm operations depend on using stderr for a log channel and stdout for JSON output ... ([#37712 (comment)](https://github.com/ceph/ceph/pull/37712#issuecomment-721912058))

@mgfritch Just curious, why are we dedicating stdout for json output only?

2020-11-05 20:39 UTC, mgfritch commented
> > Unfortunately this is not going to work as many of cephadm operations depend on using stderr for a log channel and stdout for JSON output ... ([#37712 (comment)](https://github.com/ceph/ceph/pull/37712#issuecomment-721912058))
> 
> @mgfritch Just curious, why are we dedicating stdout for json output only?

Many commands consumed by mgr/cephadm depend on this behavior
(not an exhaustive list):
* `cephadm ls`
* `cephadm gather-facts`
* `cphadm deploy ..`
* `cephadm volume -- lvm list --format json`
* etc.

Is there a need to change the default python logging behavior?

2020-11-16 15:59 UTC, sebastian-philipp commented
Hm we need to differentiate between `cephadm bootstrap` and other commands. In a way, bootstrap is special, as it is supposed to print it's status to stdout. Hm. 

:+1: for **not** changing the default fd to stdout.

2020-11-18 16:08 UTC, closed without merging