Osd io path
ceph/ceph pull request #37710
Opened 2020-10-19 14:23 UTC by ideepika

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-19 16:14 UTC, sebastian-philipp requested changes

2020-10-19 16:14 UTC, sebastian-philipp commented on src/cephadm/cephadm
> +        'deploy', help='deploy a daemon')
looks like a rebase error.

2020-10-19 16:14 UTC, sebastian-philipp commented on src/cephadm/cephadm
> +                        % (get_fqdn(), get_fqdn()))
Is this supposed to be a POC or a real feature to cephadm?

2020-10-19 22:24 UTC, ideepika commented on src/cephadm/cephadm
> +                        % (get_fqdn(), get_fqdn()))
it needs to be tested and polished a bit right now, . Since Jaeger is also using containerized model for deploying it's services, I think it would be best to add those services using cephadm.

2020-10-20 22:57 UTC, sebastian-philipp commented on src/cephadm/cephadm
> +                        % (get_fqdn(), get_fqdn()))
this looks indeed very similar to our monitoring containers. Might make sense to build something similar to how we deploy prometheus. 

This current approach has some big disadvantages:

* It introduces a new command just for this single service type
* ^^ means, it's super hard to add this to an automated deployment
* It doesn't survive reboots
* it won't be listed in `ceph orch ls`

No. please integrate it properly, like prometheus, or node-exporter

2020-10-21 06:06 UTC, ideepika commented on src/cephadm/cephadm
> +                        % (get_fqdn(), get_fqdn()))
this does makes sense, thanks for feedback, will update soon.

2022-03-08 17:49 UTC, rzarzynski commented
@ideepika: may we close or is this still alive?

2022-03-08 18:15 UTC, ideepika commented
@rzarzynski i think we can close it for now, thanks!

2022-03-08 18:15 UTC, closed without merging