client: fix inode ll_ref reference count leak
ceph/ceph pull request #37735
Opened 2020-10-21 07:27 UTC by sepia-liu

Fixes: https://tracker.ceph.com/issues/47918

Signed-off-by: sepia-liu <liuwei_coder@163.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-21 20:09 UTC, batrick approved these changes
Good catch!

2020-10-22 19:36 UTC, jtlayton commented
I've looked over the code, but I don't see where the extra reference comes from. @sepia-liu , could you explain that in the patch description?

2020-10-22 19:39 UTC, batrick requested changes

2020-10-22 19:39 UTC, batrick commented on src/client/Client.cc
> +	*target = tmptarget.get();;
```suggestion
	*target = std::move(tmptarget);
```

2020-10-22 19:43 UTC, jtlayton commented
> I've looked over the code, but I don't see where the extra reference comes from. @sepia-liu , could you explain that in the patch description?

NVM, I see now. The caller is not expected to _ll_put the resulting InodeRef, so we just don't need this period.

2020-10-22 19:49 UTC, batrick commented on src/client/Client.cc
> +	*target = tmptarget.get();;
(This avoids an unnecessary atomic increment/decrement.)

2020-10-24 03:19 UTC, batrick approved these changes

2020-10-25 23:24 UTC, batrick commented
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20201024.032205

failures unrelated.

2020-10-25 23:28 UTC, merged