ceph-volume: remove mention of dmcache from docs and help text
ceph/ceph pull request #37741
Opened 2020-10-21 16:01 UTC by andrewschoen

With the introduction of bluestore dmcache is no longer needed and
is no longer supported with `ceph-volume lvm`.

Resolves: rhbz#1876827

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

2020-10-27 14:57 UTC, jan--f requested changes
Please add a tracker ticket and mention it in the commit and PR description so we can track the backports. Otherwise LGTM.

2020-10-29 10:49 UTC, rishabh-d-dave approved these changes

2020-10-29 10:53 UTC, rishabh-d-dave reviewed
I am holding back the approval after reading Jan's comment.

2020-10-29 10:53 UTC, rishabh-d-dave requested changes
I am holding back the approval after reading Jan's comment.

2020-10-29 14:47 UTC, andrewschoen commented
> Please add a tracker ticket and mention it in the commit and PR description so we can track the backports. Otherwise LGTM.

I've created the tracker ticket and updated the commit. Thanks!

2020-10-30 09:09 UTC, jan--f approved these changes

2020-11-05 12:51 UTC, rishabh-d-dave approved these changes

2020-11-09 10:33 UTC, merged