mgr/dashboard: update QoS values when editing a Pool/RBD image
ceph/ceph pull request #37742
Opened 2020-10-21 17:11 UTC by avanthakkar

Fixes: https://tracker.ceph.com/issues/47900

Signed-off-by: Avan Thakkar <athakkar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-21 17:24 UTC, avanthakkar commented
Currently with the changes made, if the page is refreshed the value gets reset again to default values (i.e. 0 B/s or 0 IOPS), because every time the pool-form page is loaded the configuration form is created, so the value doesn't isn't retained. So any suggestion on how to retain the Qos field values even if the code is re-compiled or the page is refreshed? I tried replacing ngOnInit with ngOnChanges to detect changes calculated in getDirtyValues() (I tried storing values in both result object and config.value), but no luck!

2020-11-11 06:56 UTC, avanthakkar commented
The issue is resolved now. In order to check with real case values, I still have to add e2e test cases.

2020-11-11 11:44 UTC, avanthakkar commented
jenkins test make check

2020-11-11 11:44 UTC, avanthakkar commented
jenkins test dashboard

2020-11-11 13:30 UTC, s0nea commented
jenkins test dashboard

2020-11-12 18:56 UTC, avanthakkar commented
jenkins test docs

2020-11-13 18:33 UTC, epuertat approved these changes
Great job! This was a tricky one @avanthakkar !

2020-11-16 09:55 UTC, alfonsomthd requested changes

2020-11-16 09:58 UTC, alfonsomthd commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-configuration-form/rbd-configuration-form.component.spec.ts
> +      component.initializeData = new ReplaySubject<any>();
If only the last value is to be replayed, better to set bufferSize to 1.

2020-11-16 09:59 UTC, alfonsomthd commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/block/rbd-configuration-form/rbd-configuration-form.component.spec.ts
> +      component.initializeData = new ReplaySubject<any>();
If only the last value is to be replayed, better to set bufferSize to 1.

2020-11-17 09:22 UTC, alfonsomthd approved these changes
LGTM

2020-11-17 10:35 UTC, avanthakkar commented
jenkins test dashboard

2020-11-18 09:28 UTC, merged