nautilus: mgr/dashboard: Datatable catches select events from other datatables
ceph/ceph pull request #37756
Opened 2020-10-22 14:02 UTC by tspmelo

backport tracker: https://tracker.ceph.com/issues/47198

---

backport of https://github.com/ceph/ceph/pull/36590
parent tracker: https://tracker.ceph.com/issues/46903

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-10-26 15:38 UTC, tspmelo commented
jenkins test api

2020-10-27 14:55 UTC, votdev requested changes

2020-10-27 14:55 UTC, votdev commented on src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
>      this.onSelect();
`ERROR in src/app/shared/datatable/table/table.component.ts(454,5): error TS2554: Expected 1 arguments, but got 0.`

```suggestion
    this.onSelect(this.selection);
```

2020-10-27 14:59 UTC, votdev commented
Finally you need to apply this patch to get it running:
```
--- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html	(revision 121764eb963fc150b67772cffde79eb936ecb9f2)
+++ src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html	(date 1603810690641)
@@ -87,7 +87,7 @@
                  [cssClasses]="paginationClasses"
                  [selectionType]="selectionType"
                  [selected]="selection.selected"
-                 (select)="onSelect()"
+                 (select)="onSelect($event)"
                  [sorts]="userConfig.sorts"
                  (sort)="changeSorting($event)"
                  [columns]="tableColumns"
===================================================================
--- src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts	(revision 121764eb963fc150b67772cffde79eb936ecb9f2)
+++ src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts	(date 1603810558604)
@@ -451,7 +451,7 @@
       return;
     }
     this.selection.selected = newSelected;
-    this.onSelect();
+    this.onSelect(this.selection);
   }
 
   onSelect($event: any) {
```

2020-11-17 09:58 UTC, callithea approved these changes

2020-11-18 10:25 UTC, votdev approved these changes

2020-11-26 11:41 UTC, merged