do_cmake: build fails on fedora-33 due to python version
ceph/ceph pull request #37773
Opened 2020-10-23 14:48 UTC by sunnyku

Traceback:
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Python3: Found unsuitable version "3.9.0", but required is
  exact version "3.8" (found /usr/bin/python3, found components: Interpreter
  Development)

Solution:
Using PYBUILD="3" when fedora version is greater than 32.

Signed-off-by: Sunny Kumar <sunkumar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-23 16:00 UTC, tchaikov commented on do_cmake.sh
> +              PYBUILD="3"
what if some developer installs python3.9 on fedora31/fedora32? on which python3.9 is not fully supported, and lots of packages are missing.

2020-10-23 16:01 UTC, tchaikov requested changes
the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

2020-10-23 17:44 UTC, smithfarm commented
To follow up on what @tchaikov wrote, the general idea is that what you wrote under "Solution" (in the commit message) should actually be the commit title. The title of the commit should describe what the commit is doing, not what problem it is solving.

     do_cmake: use PYBUILD="3" when fedora version is greater than 32

(where "use" is the "imperative" form of the verb "to use")

You can see examples of commit message titles by doing `git log --oneline --no-merges`

2020-10-26 18:21 UTC, sunnyku commented
jenkins test make check

2020-10-27 17:51 UTC, tchaikov approved these changes

2020-10-30 15:15 UTC, jdurgin approved these changes

2020-10-30 15:16 UTC, merged