ceph-volume: consume mount opt in simple activate
ceph/ceph pull request #37808
Opened 2020-10-26 19:23 UTC by dsavineau

When running ceph-volume simple activate command on a Filestore OSD
then the data device is mounted without any specific options so the
one from the ceph configuration file are ignored.
When deploying Filestore with the lvm subcommand then everything is
fine because the filestore_activate method uses mount_osd which relies
on the mount options defined in the ceph configuration file (if any).

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1891557

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-26 19:25 UTC, dsavineau commented
jenkins test ceph-volume tox

2020-10-26 21:08 UTC, dsavineau commented
jenkins test ceph-volume all

2020-10-27 15:00 UTC, jan--f requested changes
The change looks good.
As I expect this will need to be backported, please create a tracker ticket and link it in the PR.

2020-10-27 16:56 UTC, guits approved these changes

2020-10-28 08:17 UTC, jan--f approved these changes

2020-10-28 08:21 UTC, merged