nautilus: mon/MonMap: fix unconditional failure for init_with_hosts
ceph/ceph pull request #37816
Opened 2020-10-26 21:02 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/47986

---

backport of https://github.com/ceph/ceph/pull/37758
parent tracker: https://tracker.ceph.com/issues/47951

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-10-27 00:27 UTC, wido approved these changes

2020-10-27 07:51 UTC, smithfarm commented
```
Could not find executable /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_mon_monmap
```

2020-10-27 07:51 UTC, smithfarm commented
jenkins test make check

2020-10-27 08:21 UTC, smithfarm commented
make check failure appears to be related - unit tests are either not building at all, or not getting installed in the right place?

2020-10-27 18:16 UTC, batrick requested changes

2020-10-27 18:16 UTC, batrick commented on src/test/mon/MonMap.cc
> +  boost::intrusive_ptr<CephContext> cct = new CephContext(CEPH_ENTITY_TYPE_MON);
Drop this change from `test/mon: fix compiler errors in MonMap unittest ` and the others. This is causing the build failure.

2020-10-27 18:25 UTC, smithfarm commented
@batrick Thanks! Done. 

Shall I make the same change over at https://github.com/ceph/ceph/pull/37817 (the octopus backport of this same fix)?

2020-10-27 18:28 UTC, batrick commented
> @batrick Thanks! Done.
> 
> Shall I make the same change over at #37817 (the octopus backport of this same fix)?

Yes, I think so.

2020-10-27 19:03 UTC, smithfarm commented
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc: In member function 'virtual void MonMapTest_DISABLED_build_initial_config_from_dns_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc:102:36: error: request for member 'get' in 'cct', which is of pointer type 'CephContext*' (maybe you meant to use '->' ?)
  102 |   int r = monmap.build_initial(cct.get(), false, std::cerr);
      |                                    ^~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc: In member function 'virtual void MonMapTest_DISABLED_build_initial_config_from_dns_fail_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc:139:36: error: request for member 'get' in 'cct', which is of pointer type 'CephContext*' (maybe you meant to use '->' ?)
  139 |   int r = monmap.build_initial(cct.get(), false, std::cerr);
      |                                    ^~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc: In member function 'virtual void MonMapTest_DISABLED_build_initial_config_from_dns_with_domain_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc:200:36: error: request for member 'get' in 'cct', which is of pointer type 'CephContext*' (maybe you meant to use '->' ?)
  200 |   int r = monmap.build_initial(cct.get(), false, std::cerr);
      |                                    ^~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc: In member function 'virtual void MonMapBuildInitial_build_initial_mon_host_from_dns_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc:225:36: error: request for member 'get' in 'cct', which is of pointer type 'CephContext*' (maybe you meant to use '->' ?)
  225 |   int r = monmap.build_initial(cct.get(), false, std::cerr);
      |                                    ^~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc: In member function 'virtual void MonMapBuildInitial_build_initial_mon_host_from_dns_fail_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/MonMap.cc:237:36: error: request for member 'get' in 'cct', which is of pointer type 'CephContext*' (maybe you meant to use '->' ?)
  237 |   int r = monmap.build_initial(cct.get(), false, std::cerr);
      |                                    ^~~
src/test/mon/CMakeFiles/unittest_mon_monmap.dir/build.make:62: recipe for target 'src/test/mon/CMakeFiles/unittest_mon_monmap.dir/MonMap.cc.o' failed
make[3]: *** [src/test/mon/CMakeFiles/unittest_mon_monmap.dir/MonMap.cc.o] Error 1
```

2020-10-27 19:04 UTC, smithfarm commented
@batrick Should be merely `cct` instead of `cct.get()` ?

2020-10-27 19:31 UTC, batrick commented
> @batrick Should be merely `cct` instead of `cct.get()` ?

Yes, sorry.

2020-10-27 19:39 UTC, smithfarm commented
OK, looks like this is ready for:

1. integration test
2. merge
3. 14.2.13 release :-)

2020-10-27 19:43 UTC, smithfarm commented
@batrick I guess the 14.2.13 release notes should contain some verbiage explaining the regression. How should we phrase it? Something like this

"This release fixes a regression introduced in 14.2.12 which broke deployments that referred to MON hosts using DNS names instead of IP addresses in the `mon_host` parameter in `/etc/ceph/ceph.conf`."

?

2020-10-27 20:33 UTC, batrick commented
Yes, that sounds good.

2020-10-27 21:27 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri5-testing-2020-10-27-1421-nautilus ***](https://trello.com/c/RlmpjCxD/1051-wip-yuri5-testing-2020-10-27-1421-nautilus)

2020-10-27 21:39 UTC, djgalloway commented
If this is urgent, @yuriw text me when it's merged and I'll start the build tonight.

2020-10-28 01:33 UTC, neha-ojha approved these changes

2020-10-28 18:13 UTC, batrick approved these changes

2020-10-28 18:17 UTC, merged