octopus: os/bluestore: attach csum for compressed blobs
ceph/ceph pull request #37861
Opened 2020-10-27 09:47 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/47892

---

backport of https://github.com/ceph/ceph/pull/37168
parent tracker: https://tracker.ceph.com/issues/47475

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-10-27 10:09 UTC, smithfarm commented
jenkins test make check

2020-10-27 11:36 UTC, smithfarm commented
jenkins test api

2020-10-27 12:17 UTC, ifed01 approved these changes

2020-10-27 13:01 UTC, smithfarm commented
jenkins test dashboard

2020-10-27 14:18 UTC, smithfarm commented
Not sure what the "ceph dashboard tests" are, and how they differ from the "ceph API tests" (if at all).

2020-11-30 22:59 UTC, ifed01 requested changes
This has got plenty of unrelated commits! Something is wrong with the backport

2020-12-01 19:49 UTC, smithfarm commented
> This has got plenty of unrelated commits! Something is wrong with the backport

@ifed01 That was a side effect of the 15.2.7 hotfix release, which involved force-pushing the `octopus` named branch. The extra commits are already there in octopus, but when the branch gets force pushed, the github UI gets confused. 

Anyway, I rebased the PR and now the commits should be gone. Just noting that the PR could have been merged as-is and nothing bad would have happened.

2020-12-04 11:22 UTC, ifed01 commented
jenkins test make check

2020-12-04 12:12 UTC, ifed01 approved these changes

2020-12-04 15:57 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri2-testing-2020-11-26-0903-octopus (old wip-yuri2-testing-2020-11-23-1241-octopus (old wip-yuri2-testing-2020-11-05-1029-octopus))](https://trello.com/c/kx1gvBXw/1058-wip-yuri2-testing-2020-11-26-0903-octopus-old-wip-yuri2-testing-2020-11-23-1241-octopus-old-wip-yuri2-testing-2020-11-05-1029-oc)

2020-12-17 17:22 UTC, merged