octopus: os/bluestore: Support flock retry
ceph/ceph pull request #37860
Opened 2020-10-27 09:46 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/47708

---

backport of https://github.com/ceph/ceph/pull/34566
parent tracker: https://tracker.ceph.com/issues/46124

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2020-10-27 10:18 UTC, smithfarm commented
```
1 tests failed out of 196

Total Test time (real) = 536.84 sec

The following tests FAILED:
	192 - unittest_seastar_messenger (Child aborted)
```

2020-10-27 10:18 UTC, smithfarm commented
jenkins test make check

2020-11-30 23:01 UTC, ifed01 requested changes
backport is broken, 481 commits hve been staged

2020-12-01 19:50 UTC, smithfarm commented
> backport is broken, 481 commits hve been staged

Not broken - just a cosmetic irritation. See explanation posted at https://github.com/ceph/ceph/pull/37861#issuecomment-736779039

2020-12-04 11:20 UTC, ifed01 approved these changes

2020-12-04 15:57 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri2-testing-2020-11-26-0903-octopus (old wip-yuri2-testing-2020-11-23-1241-octopus (old wip-yuri2-testing-2020-11-05-1029-octopus))](https://trello.com/c/kx1gvBXw/1058-wip-yuri2-testing-2020-11-26-0903-octopus-old-wip-yuri2-testing-2020-11-23-1241-octopus-old-wip-yuri2-testing-2020-11-05-1029-oc)

2020-12-17 19:17 UTC, yuriw commented
Jenkins test this please

2020-12-17 20:53 UTC, merged