qa/suites/rados/monthrash: fix failed to reach quorum size 9 before timeout expired
ceph/ceph pull request #37904
Opened 2020-10-30 13:38 UTC by ideepika

when mon delay is injected, mon's need more time to come back up,
increasing `mon client directed command retry` keeps them from failing
until all mons go up.

fixes: https://tracker.ceph.com/issues/45761
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-10-30 19:03 UTC, neha-ojha commented
@ideepika could you please add the test runs you did to reproduce https://tracker.ceph.com/issues/45761 and the one where you verified this change?

2020-11-02 14:18 UTC, ideepika commented
> @ideepika could you please add the test runs you did to reproduce https://tracker.ceph.com/issues/45761 and the one where you verified this change?

I added config I used to reproduce in the tracker, as I used interactive on error mode, I don't have a log stored somewhere for success or failure results for the test runs rn.

2020-11-22 05:46 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-11-21_05:41:14-rados-wip-kefu-testing-2020-11-19-1104-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-21_05:41:14-rados-wip-kefu-testing-2020-11-19-1104-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-22_03:37:22-rados-wip-kefu-testing-2020-11-19-1104-distro-basic-smithi/

quite a few cephadm tests failed.

```
2020-11-22T04:08:07.730 INFO:teuthology.orchestra.run.smithi112.stderr:DEBUG:cephadm:Running command: /bin/podman pull docker.io/ceph/ceph:v15.2.0
2020-11-22T04:08:09.287 INFO:teuthology.orchestra.run.smithi112.stderr:DEBUG:cephadm:/bin/podman:stderr Trying to pull docker.io/ceph/ceph:v15.2.0...
2020-11-22T04:08:39.583 INFO:teuthology.orchestra.run.smithi112.stderr:DEBUG:cephadm:/bin/podman:stderr   toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2020-11-22T04:08:39.583 INFO:teuthology.orchestra.run.smithi112.stderr:DEBUG:cephadm:/bin/podman:stderr Error: unable to pull docker.io/ceph/ceph:v15.2.0: Error initializing source docker://ceph/ceph:v15.2.0: (Mirrors also failed: [vossi04.front.sepia.ceph.com:5000/ceph/c
eph:v15.2.0: error pinging docker registry vossi04.front.sepia.ceph.com:5000: Get "http://vossi04.front.sepia.ceph.com:5000/v2/": dial tcp 172.21.10.4:5000: connect: no route to host]): docker.io/ceph/ceph:v15.2.0: Error reading manifest v15.2.0 in docker.io/ceph/ceph: to
omanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2020-11-22T04:08:39.589 INFO:teuthology.orchestra.run.smithi112.stderr:INFO:cephadm:Non-zero exit code 125 from /bin/podman pull docker.io/ceph/ceph:v15.2.0
2020-11-22T04:08:39.589 INFO:teuthology.orchestra.run.smithi112.stderr:INFO:cephadm:/bin/podman:stderr Trying to pull docker.io/ceph/ceph:v15.2.0...
2020-11-22T04:08:39.589 INFO:teuthology.orchestra.run.smithi112.stderr:INFO:cephadm:/bin/podman:stderr   toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2020-11-22T04:08:39.590 INFO:teuthology.orchestra.run.smithi112.stderr:INFO:cephadm:/bin/podman:stderr Error: unable to pull docker.io/ceph/ceph:v15.2.0: Error initializing source docker://ceph/ceph:v15.2.0: (Mirrors also failed: [vossi04.front.sepia.ceph.com:5000/ceph/ce
ph:v15.2.0: error pinging docker registry vossi04.front.sepia.ceph.com:5000: Get "http://vossi04.front.sepia.ceph.com:5000/v2/": dial tcp 172.21.10.4:5000: connect: no route to host]): docker.io/ceph/ceph:v15.2.0: Error reading manifest v15.2.0 in docker.io/ceph/ceph: too
manyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2020-11-22T04:08:39.591 INFO:teuthology.orchestra.run.smithi112.stderr:Traceback (most recent call last):
2020-11-22T04:08:39.591 INFO:teuthology.orchestra.run.smithi112.stderr:  File "/home/ubuntu/cephtest/cephadm", line 4245, in <module>
2020-11-22T04:08:39.591 INFO:teuthology.orchestra.run.smithi112.stderr:    r = args.func()
2020-11-22T04:08:39.591 INFO:teuthology.orchestra.run.smithi112.stderr:  File "/home/ubuntu/cephtest/cephadm", line 966, in _default_image
2020-11-22T04:08:39.591 INFO:teuthology.orchestra.run.smithi112.stderr:    return func()
2020-11-22T04:08:39.592 INFO:teuthology.orchestra.run.smithi112.stderr:  File "/home/ubuntu/cephtest/cephadm", line 2122, in command_bootstrap
2020-11-22T04:08:39.592 INFO:teuthology.orchestra.run.smithi112.stderr:    call_throws([container_path, 'pull', args.image])
2020-11-22T04:08:39.592 INFO:teuthology.orchestra.run.smithi112.stderr:  File "/home/ubuntu/cephtest/cephadm", line 694, in call_throws
2020-11-22T04:08:39.592 INFO:teuthology.orchestra.run.smithi112.stderr:    raise RuntimeError('Failed command: %s' % ' '.join(command))
2020-11-22T04:08:39.592 INFO:teuthology.orchestra.run.smithi112.stderr:RuntimeError: Failed command: /bin/podman pull docker.io/ceph/ceph:v15.2.0
```

seems we are still pulling from docker.io.

2020-11-24 00:50 UTC, neha-ojha requested changes
I don't think we should merge this without figuring out the root cause.

2020-11-24 01:14 UTC, badone commented
> I don't think we should merge this without figuring out the root cause.

Pretty sure they are failing due to docker rate limiting container image pulls from their registry.

2020-11-24 01:18 UTC, neha-ojha commented
> > I don't think we should merge this without figuring out the root cause.
> 
> Pretty sure they are failing due to docker rate limiting container image pulls from their registry.

@badone: how does qa/suites/rados/monthrash depend on docker?

2020-11-24 01:21 UTC, badone commented
@neha-ojha 

```
Error reading manifest v15.2.0 in docker.io/ceph/ceph: too
manyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

2020-11-24 01:26 UTC, badone commented
@neha-ojha Sorry, totally misunderstood your initial post. Moving on.

2020-11-24 01:30 UTC, tchaikov commented
https://pulpito.ceph.com/kchai-2020-11-22_03:37:22-rados-wip-kefu-testing-2020-11-19-1104-distro-basic-smithi/5646187/ timed out waiting for the quorum.

2021-04-29 05:48 UTC, closed without merging