ceph-volume: fix lvm batch auto with full SSDs
ceph/ceph pull request #37942
Opened 2020-11-03 23:34 UTC by dsavineau

The ceph-volume lvm batch --auto introduced by [1] breaks the backward
compatibility when using non rotational devices only (SSD and/or NVMe).
Those devices are reaffected as bluestore db or filestore journal
devices while we want them as data devices.

Fixes: https://tracker.ceph.com/issues/48106

[1] https://github.com/ceph/ceph/pull/34740

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-04 08:25 UTC, guits approved these changes

2020-11-04 09:20 UTC, jan--f requested changes
Would you mind adding a unit test for this too please? This should certainly be caught in our CI not rooks.

2020-11-04 09:20 UTC, jan--f commented on src/ceph-volume/ceph_volume/devices/lvm/batch.py
> +            return
Sorry to be nit-picky about this, but I think in a few month time nobody will remember the reason for this comparison.

I think something more explicit would be good here.

```suggestion
        if ssd and not rotational:
            # no need for additional sorting, we'll only deploy standalone on ssds
            return
```

2020-11-04 14:34 UTC, dsavineau commented
jenkins test ceph-volume tox

2020-11-05 08:49 UTC, jan--f commented
jenkins test ceph-volume all

2020-11-05 08:50 UTC, jan--f approved these changes
Thanks guys, looks good!

2020-11-05 12:34 UTC, guits commented
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

2020-11-05 13:09 UTC, rishabh-d-dave approved these changes

2020-11-05 15:25 UTC, dsavineau commented
@jan--f @guits I was wondering if we should add more tests for `_sort_rotational_disks` because we only added one test for the full SSD scenario but I guess we should also have a test for
  - full HDD scenario
  - bluestore mixed HDD/SSD scenario (for db_devices)
  - filestore mixed HDD/SSD scenario (for journal_devices)

What do you think ?

2020-11-05 15:42 UTC, guits commented
@dsavineau in a perfect world, we should even have 100% coverage, so yes we should add these tests.
Maybe this could be done in a dedicated PR if we want to get this fix merged quickly (although we would have to wait for a new release to include this fix anyway...)

your call... guys 🙂

2020-11-09 10:29 UTC, jan--f commented
@dsavineau  More tests are always more than welcome! I'll merge this here tomorrow, unless you'll let me know more tests are going to be added here, so up to you.

In any case I have added https://tracker.ceph.com/issues/48150 to track the need for more tests.

2020-11-09 15:32 UTC, dsavineau commented
jenkins test ceph-volume tox

2020-11-09 15:32 UTC, dsavineau commented
jenkins test ceph-volume all

2020-11-09 15:49 UTC, jan--f commented
@andrewschoen Looks like #37741 broke a tox test. Mind having a look at it?

2020-11-09 15:55 UTC, dsavineau commented
jenkins test ceph-volume tox

2020-11-09 15:56 UTC, dsavineau commented
jenkins test ceph-volume all

2020-11-09 17:03 UTC, jan--f commented
jenkins test make check

2020-11-10 07:29 UTC, jan--f commented
> @andrewschoen Looks like #37741 broke a tox test. Mind having a look at it?

Nevermind @andrewschoen  :) Thanks everyone!

2020-11-10 07:31 UTC, merged