src/rgw: cls async APIs
ceph/ceph pull request #37974
Opened 2020-11-06 14:34 UTC by dorindabassey

enforcing cls async APIs for all RGW code

Fixes: https://tracker.ceph.com/issues/45622

Signed-off-by: dorindabassey <dorindabassey@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-06 14:38 UTC, dorindabassey commented
Hi @yuvalif please review

2020-11-07 16:21 UTC, yuvalif requested changes
after setting the flag in the CMakeList.txt file you should:
- find all compilation errors
- for each one, you should change the API invoked from the synchronous one to the a-synchronous one
- no need to "ifndef" anything

2020-11-15 16:15 UTC, yuvalif commented on src/cls/otp/cls_otp_client.h
> +#endif
see comment in lines 25-26. these functions should not be called from inside the RGW (they are using IoCtx - hence sync calls).
they should be inside the `ifndef`

2020-11-15 16:16 UTC, yuvalif commented on src/cls/version/cls_version_client.h
> +
please keep the `ifndef`

2020-11-15 16:18 UTC, yuvalif commented on src/rgw/rgw_gc.cc
> +      cls_rgw_gc_list_op();
is this a new function?
where is it defined?

2020-11-15 16:19 UTC, yuvalif commented on src/rgw/rgw_lc.cc
> +/*  ret = guard_lc_modify(store, bucket, cookie,
why is this code commented?

2020-11-15 16:20 UTC, yuvalif requested changes
not clear where did all the logic go?
where are the new function defined?

2020-11-17 10:18 UTC, dorindabassey commented
Hi Yuval,

I realized what I was supposed to do regarding the PR, so I made updates on
it here https://github.com/ceph/ceph/pull/38124
Thanks.

On Nov 15, 2020 17:20, "Yuval Lifshitz" <notifications@github.com> wrote:

> *@yuvalif* requested changes on this pull request.
>
> not clear where did all the logic go?
> where are the new function defined?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ceph/ceph/pull/37974#pullrequestreview-530813023>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMUO6AN6GXH5JGJBAZCXB33SP75WFANCNFSM4TMX7MFQ>
> .
>

2020-11-19 19:20 UTC, closed without merging