Mon: FreeBSD returns ENOENT on resolv error
ceph/ceph pull request #38026
Opened 2020-11-11 14:22 UTC by wjwithagen

Tracker: https://tracker.ceph.com/issues/48183

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-11 19:15 UTC, batrick approved these changes

2020-11-12 01:59 UTC, tchaikov requested changes
could you please use 

> test/mon: return ENOENT on resolv error on FreeBSD

as the title of the commit message?

2020-11-15 03:54 UTC, tchaikov commented
@wjwithagen i still don't like the title, which claims that "FreeBSD returns ENOENT".  this is a fact, not the change you made in this patch. so could you put it in the body of the commit message, as the reason why we need your change? and use 

> return ENOENT on resolv error on FreeBSD

as the title instead?

2020-11-15 09:11 UTC, wjwithagen commented
@tchaikov 
Used a slightly different wording from yours, but it is descriptive.

2020-11-15 11:53 UTC, tchaikov approved these changes

2020-11-15 16:09 UTC, merged