client: do not use g_conf().get_val<>() in libcephfs
ceph/ceph pull request #38033
Opened 2020-11-12 01:17 UTC by lxbsz

The g_conf() will try to dereference the "g_ceph_context" to get
the "_conf", but the "g_ceph_context" won't be set in none fuse
use case in libcephfs, so it will crash in when doing
g_conf().get_val<>.

Switch to use cct->_conf.get_val<> instead.

Fixes: https://tracker.ceph.com/issues/48206
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-12 01:57 UTC, tchaikov approved these changes

2020-11-13 17:09 UTC, batrick requested changes
Please also fix `get_fuse_groups` in `fuse_ll.cc`. (It won't crash there but we should be consistent.)

2020-11-14 01:30 UTC, lxbsz commented
> Please also fix `get_fuse_groups` in `fuse_ll.cc`. (It won't crash there but we should be consistent.)

Sure, done. Thanks.

2020-11-17 04:11 UTC, lxbsz commented
jenkins test api

2020-11-17 04:19 UTC, batrick approved these changes

2020-11-18 20:00 UTC, batrick commented
jenkins test api

2020-11-19 02:47 UTC, batrick requested changes

2020-11-19 02:47 UTC, batrick commented on src/client/fuse_ll.cc
> +  if (cct->_conf.get_val<bool>("fuse_set_user_groups")) {
```suggestion
  if (cfuse->client->cct->_conf.get_val<bool>("fuse_set_user_groups")) {
```

Fixes build error:

````
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-7334-gdb29fdf8/rpm/el8/BUILD/ceph-16.0.0-7334-gdb29fdf8/src/client/fuse_ll.cc: In function 'void get_fuse_groups(UserPerm&, fuse_req_t)':
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-7334-gdb29fdf8/rpm/el8/BUILD/ceph-16.0.0-7334-gdb29fdf8/src/client/fuse_ll.cc:139:7: error: 'cct' was not declared in this scope
   if (cct->_conf.get_val<bool>("fuse_set_user_groups")) {
       ^~~
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-7334-gdb29fdf8/rpm/el8/BUILD/ceph-16.0.0-7334-gdb29fdf8/src/client/fuse_ll.cc:139:7: note: suggested alternative: 'cc_t'
   if (cct->_conf.get_val<bool>("fuse_set_user_groups")) {
       ^~~
       cc_t
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-7334-gdb29fdf8/rpm/el8/BUILD/ceph-16.0.0-7334-gdb29fdf8/src/client/fuse_ll.cc:139:26: error: expected primary-expression before 'bool'
   if (cct->_conf.get_val<bool>("fuse_set_user_groups")) {
                          ^~~~
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-7334-gdb29fdf8/rpm/el8/BUILD/ceph-16.0.0-7334-gdb29fdf8/src/client/fuse_ll.cc:139:26: error: expected ')' before 'bool'
   if (cct->_conf.get_val<bool>("fuse_set_user_groups")) {
      ~                   ^~~~
                          )
````

2020-11-20 10:03 UTC, lxbsz commented on src/client/fuse_ll.cc
> +  if (cct->_conf.get_val<bool>("fuse_set_user_groups")) {
Done. Thanks.

2020-11-21 02:31 UTC, batrick commented
jenkins test docs

2020-11-21 02:31 UTC, batrick commented
jenkins test api

2020-11-24 19:09 UTC, batrick approved these changes

2020-12-02 20:06 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2020-12-02_07:09:18-fs-wip-pdonnell-testing-20201202.050726-distro-basic-smithi/

2020-12-02 20:08 UTC, merged