cephadm: reference the last local image by name
ceph/ceph pull request #38032
Opened 2020-11-11 22:22 UTC by mgfritch

use the image name rather than repo/tag combo when inferring the last
used local ceph image

Fixes: https://tracker.ceph.com/issues/48205
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-12 16:58 UTC, jmolmo approved these changes

2020-11-13 05:29 UTC, bk201 commented on src/cephadm/cephadm
> +        logger.error('Cannot get the last local ceph image: %s' % (e))
(Optional) make logging lazy.
```suggestion
        logger.error('Cannot get the last local ceph image: %s', e)
```

2020-11-13 05:31 UTC, bk201 commented
+1 for using JSON output, but I found some issues:
- With Podman version `1.6.4`, the JSON output is not sorted by created time.
  ```
  [root@mgr0 ~]# podman images --filter label=ceph=True --filter dangling=false
  REPOSITORY                                                                TAG       IMAGE ID       CREATED       SIZE
  docker.io/ceph/daemon-base                                                master    90a79f3d6091   3 hours ago   1.03 GB
  docker.io/ceph/daemon-base                                                octopus   268474bf5f83   3 hours ago   964 MB
  registry.opensuse.org/filesystems/ceph/master/upstream/images/ceph/ceph   latest    48838b784d46   3 days ago    973 MB
  [root@mgr0 ~]# podman images --filter label=ceph=True --filter dangling=false --format=json
  [
      {
          "id": "268474bf5f8352922fabed0c801f8bc79a7c5ae12f6e88fa2548e856c2241908",
          "names": [
              "docker.io/ceph/daemon-base:octopus"
          ],
          "digest": "sha256:b3cd16aeed81a21ffb087e72fd4e6083b6ea6a1b54a1a827f497700a1b4a23e2",
          "digests": [
              "sha256:b3cd16aeed81a21ffb087e72fd4e6083b6ea6a1b54a1a827f497700a1b4a23e2"
          ],
          "created": "2020-11-13T02:07:10.842245189Z",
          "size": 964340471,
          "readonly": false
      },
      {
          "id": "90a79f3d60916a8efc7c10d2d72e8e2e2622e9d035d6c44d22547b2670355201",
          "names": [
              "docker.io/ceph/daemon-base:master"
          ],
          "digest": "sha256:5b05eb39161de8398cee2f20c3240c3bbde20a5b8766078c0691977d8466e669",
          "digests": [
              "sha256:5b05eb39161de8398cee2f20c3240c3bbde20a5b8766078c0691977d8466e669"
          ],
          "created": "2020-11-13T02:07:13.492865116Z",
          "size": 1032803567,
          "readonly": false
      },
      {
          "id": "48838b784d4664f6be22bdd20d096802c411633509458e45dc9757f6ec5eecb2",
          "names": [
              "registry.opensuse.org/filesystems/ceph/master/upstream/images/ceph/ceph:latest"
          ],
          "digest": "sha256:9fb75d4cf92990bc9e2e15f93692c0565bdf6c3e4dbdb7bc053ff1ad7899b927",
          "digests": [
              "sha256:9fb75d4cf92990bc9e2e15f93692c0565bdf6c3e4dbdb7bc053ff1ad7899b927"
          ],
          "created": "2020-11-10T00:16:27Z",
          "size": 973012349,
          "readonly": false
      }
  ]
  ```
  The fisrt image might not be the latest image. I didn't see this in Podman version `2.0.6`. Sorting might be implemented after `1.9.0` (https://github.com/containers/podman/commit/1d7cb7cc48d06631e2bdfd0e25eeccc8e87b042f). Do we have a minimum supported Podman version?
- Docker doesn't support `--format=json` (Tested `19.03.12`), should we care?

2020-11-13 18:15 UTC, mgfritch commented
good catch @bk201 !  maybe we should filter these down to the most recent created time?

2020-11-16 15:25 UTC, sebastian-philipp reviewed
would be great to have a pytest for this. like a hardcoded json output

2020-11-18 02:46 UTC, mgfritch commented
> +1 for using JSON output, but I found some issues:

Unfortunately, docker does not support the the json format arg.

Reworked this PR to use the repository digest instead of tag, which appears more portable and is likely what we want anyway ..

2020-11-18 03:16 UTC, mgfritch commented
jenkins retest this please

2020-11-18 14:17 UTC, sebastian-philipp requested changes
this needs a test, like 

https://github.com/ceph/ceph/pull/38162/files#diff-b09348d8cad3c66ac3c85c3a0a63ad6ffa323c1e7f6a2b2812a512559d8c1749R281-R283

2020-11-18 15:20 UTC, sebastian-philipp approved these changes

2020-11-23 07:38 UTC, guits approved these changes

2020-11-28 08:17 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-11-27_14:17:32-rados-wip-kefu-testing-2020-11-27-2029-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-28_00:28:33-rados-wip-kefu-testing-2020-11-27-2029-distro-basic-smithi/

the failure of "mon-last-epoch-clean.sh" is addressed by #38239 
the cephadm failures were due to out of quota of requests to docker.io

2020-12-08 11:08 UTC, sebastian-philipp commented
https://pulpito.ceph.com/swagner-2020-12-07_12:07:52-rados:cephadm-wip-swagner3-testing-2020-12-07-1114-distro-basic-smithi/

Failures:

* https://tracker.ceph.com/issues/48491
* docker.io rate limit

2020-12-08 11:12 UTC, merged

2021-01-05 16:32 UTC, smithfarm commented
@sebastian-philipp This hasn't been backported yet, right?

2021-01-05 19:54 UTC, sebastian-philipp commented
not yet