mon/OSDMonitor, mon/PaxosService: additional debug outputs when trimming
ceph/ceph pull request #38070
Opened 2020-11-13 21:50 UTC by dvanders

Adds some additional dout's to help troubleshooting cases where osdmaps are not trimmed.

2020-11-17 05:22 UTC, tchaikov commented on src/mon/OSDMonitor.cc
> +    dout(10) << __func__ << ": quorum not formed, trim_to = 0" << dendl;
could you take the opportunity to drop the ":" to be more consistent with the rest of this file?

2020-11-17 05:22 UTC, tchaikov commented on src/mon/OSDMonitor.cc
> +      dout(10) << __func__ << ": pgs creating, trim_to = 0" << dendl;
ditto.

2020-11-17 05:25 UTC, tchaikov requested changes
https://github.com/ceph/ceph/pull/38070/files#r524870084

2020-11-17 10:35 UTC, jecluis approved these changes

2020-11-17 11:01 UTC, tchaikov approved these changes

2020-11-22 05:39 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2020-11-21_05:41:14-rados-wip-kefu-testing-2020-11-19-1104-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-21_05:41:14-rados-wip-kefu-testing-2020-11-19-1104-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-22_03:37:22-rados-wip-kefu-testing-2020-11-19-1104-distro-basic-smithi/

2020-11-22 05:39 UTC, merged