doc/cephfs: update doc due to code changes
ceph/ceph pull request #38126
Opened 2020-11-17 10:42 UTC by Rethan

After pr #37608, ceph health detail output message
have changed when mds has slow requests. So update
doc according to output.

Signed-off-by: haoyixing <haoyixing@kuaishou.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-17 14:40 UTC, joscollin commented
jenkins test signed

2020-11-17 16:26 UTC, batrick requested changes
Please [prefix the title of your commit message with the sub-component you are changing](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title) `doc`. This is required for your PR to be merged.

See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

2020-11-18 01:49 UTC, Rethan commented
> Please [prefix the title of your commit message with the sub-component you are changing](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title) `doc`. This is required for your PR to be merged.
> 
> See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

Thanks for your advice, will pay more attention to commit message.

2020-11-18 20:08 UTC, batrick approved these changes

2020-11-18 20:17 UTC, merged