ceph-volume: fix filestore/dmcrypt activate
ceph/ceph pull request #38147
Opened 2020-11-18 07:56 UTC by guits

when the journal luks is opened with `encryption_utils.luks_open()` the
device is mapped with the value `ceph.%s_uuid' % device_type`.

since `data_lv.tags['ceph.journal_uuid']` is defined anyway it means
`activate_filestore()` can use it to define `journal_uuid` whatever
the value of `osd_journal_lv`.

Closes: https://tracker.ceph.com/issues/48271

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-11-18 08:03 UTC, guits commented
jenkins test ceph-volume tox

2020-11-18 08:04 UTC, guits commented
jenkins test ceph-volume all

2020-11-18 10:22 UTC, jan--f commented
Thanks!
I also left a comment on the bug, do you have a root cause for this? The fix looks fine I think, just trying to understand why this went wrong.

2020-11-18 11:48 UTC, guits commented
@jan--f I've spent some time to figure out that, I can't understand at the moment.
In fact, this is weird because the related code doesn't seem to have been modified recently despite the recent lvm batch refactor. On the other hand, I have a hard time imagining this bug is present for so long :thinking:

2020-11-18 16:46 UTC, jan--f commented
jenkins test ceph-volume tox

2020-11-18 16:47 UTC, jan--f approved these changes
Nice fix indeed. Thanks a lot!
ready to merge once all tests pass.

2020-11-18 16:56 UTC, jan--f requested changes
Missed the return of the lv_uuid.

2020-11-18 16:56 UTC, jan--f commented on src/ceph-volume/ceph_volume/devices/lvm/prepare.py
>          return path, uuid, tags
```suggestion
            lv_uuid = name_uuid
        return path, lv_uuid, tags
```

2020-11-19 08:23 UTC, guits commented
jenkins test ceph-volume tox

2020-11-19 08:23 UTC, guits commented
jenkins test ceph-volume all

2020-11-19 08:44 UTC, guits commented
jenkins test ceph-volume tox

2020-11-19 08:45 UTC, guits commented
jenkins test ceph-volume all

2020-11-19 13:24 UTC, guits commented
jenkins test ceph-volume centos8-bluestore-mixed_type_dmcrypt

2020-11-19 13:24 UTC, guits commented
jenkins test centos8-filestore-mixed_type

2020-11-19 13:24 UTC, guits commented
jenkins test ceph-volume centos8-filestore-mixed_type

2020-11-19 13:25 UTC, guits commented
jenkins test ceph-volume bluestore-mixed_type_dmcrypt

2020-11-19 13:25 UTC, guits commented
jenkins test volume batch centos8-bluestore-mixed_type_dmcrypt

2020-11-19 13:26 UTC, guits commented
jenkins test ceph-volume batch centos8-filestore-mixed_type

2020-11-19 13:26 UTC, guits commented
jenkins test ceph-volume batch centos8-bluestore-dmcrypt

2020-11-19 13:26 UTC, guits commented
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

2020-11-19 13:27 UTC, guits commented
jenkins test ceph-volume batch centos8-bluestore-mixed_type_dmcrypt

2020-11-19 14:47 UTC, guits commented
jenkins test ceph-volume tox

2020-11-19 14:49 UTC, guits commented
jenkins test ceph-volume all

2020-11-19 15:47 UTC, jan--f approved these changes
Thx for adding tests!

2020-11-19 19:41 UTC, dsavineau approved these changes

2020-11-19 21:10 UTC, merged