doc: release notes for octopus & nautilus backports
ceph/ceph pull request #38142
Opened 2020-11-17 19:54 UTC by theanalyst

Combining the two into a single pr for ease of reviews

2020-11-17 20:09 UTC, jdurgin approved these changes

2020-11-17 20:17 UTC, idryomov requested changes

2020-11-17 20:17 UTC, idryomov commented on doc/releases/nautilus.rst
> +* rgw: use yum rather than dnf for teuthology testing of rgw-orphan-list (`pr#37805 <https://github.com/ceph/ceph/pull/37805>`_, J. Eric Ivancich)
The changelog doesn't actually include the replay attack fixes.  It looks like Yuri merged them directly, so there is no PR to reference, but perhaps something like "mon/MonClient: bring back CEPHX_V2 authorizer challenges" should be added?

2020-11-17 20:17 UTC, idryomov commented on doc/releases/octopus.rst
> +This is the 6th backport release in the Octopus series. This releases fixes a
releases -> release

2020-11-17 20:17 UTC, idryomov commented on doc/releases/octopus.rst
> +security flaw affecting Messenger V2 for Octopus & Nautilus. We recommend users
Similarly, "flaw affecting both Messenger v1 and Messenger v2, among ...".

In octopus and master (but not in nautilus), both msgr1 and msgr2 are affected.

2020-11-17 20:17 UTC, idryomov commented on doc/releases/nautilus.rst
> +* CVE 2020-25660: Fix a regression in Messenger V2 replay attacks
"CVE 2020-25660: CEPHX_V2 replay attack protection lost (only for Messenger v2)"

2020-11-17 20:17 UTC, idryomov commented on doc/releases/octopus.rst
> +* CVE 2020-25660: Fix a regression in Messenger V2 replay attacks
Similarly, "CVE 2020-25660: CEPHX_V2 replay attack protection lost (both for Messenger v1 and Messenger v2)"

2020-11-18 20:09 UTC, yuriw approved these changes

2020-11-21 18:32 UTC, idryomov requested changes

2020-11-21 18:32 UTC, idryomov commented on doc/releases/nautilus.rst
> +security flaw affecting Messenger V2 for Octopus, among other fixes
```suggestion
security flaw affecting Messenger v2, among other fixes
```

2020-11-21 18:32 UTC, idryomov commented on doc/releases/nautilus.rst
> +  Messenger v2 (Ilya Dryomov)
```suggestion
* CVE 2020-25660: CEPHX_V2 replay attack protection lost, for Messenger v2 (Ilya Dryomov)
```

2020-11-21 18:32 UTC, idryomov commented on doc/releases/nautilus.rst
> +* mon/MonClient: bring back CEPHX_V2 authorizer challenges (Iyla Dryomov)
```suggestion
* mon/MonClient: bring back CEPHX_V2 authorizer challenges (Ilya Dryomov)
```

2020-11-21 18:32 UTC, idryomov commented on doc/releases/octopus.rst
> +security flaw affecting Messenger v1 & v2.. We recommend users
```suggestion
security flaw affecting Messenger v1 & v2. We recommend users
```

2020-11-21 18:32 UTC, idryomov commented on doc/releases/octopus.rst
> +  Messenger v2 (Ilya Dryomov)
```suggestion
* CVE 2020-25660: CEPHX_V2 replay attack protection lost, for Messenger v1 & v2 (Ilya Dryomov)

Changelog
---------

* mon/MonClient: bring back CEPHX_V2 authorizer challenges (Ilya Dryomov)
```

2020-11-21 18:34 UTC, idryomov commented
@theanalyst Still some confusion around msgr1 vs msgr2 and mention of octopus in the nautilus release note.  I've left suggestions this time to make it easier.

2020-11-23 18:26 UTC, idryomov commented
Looks good.  Please squash the last commit (nautilus bits into the nautilus commit and octopus bits into the octopus commit) and I'll merge.

2020-11-24 15:48 UTC, idryomov commented
Never mind, I did it myself.

2020-11-24 16:22 UTC, idryomov approved these changes

2020-11-24 16:23 UTC, merged