rgw: disable prefetch in rgw_file to fix 3x read amplification
ceph/ceph pull request #38167
Opened 2020-11-18 15:31 UTC by kajetanj

rgw: This PR disables prefetch in rgw_file (used by NFS-Ganesha).

Each call to `rgw_read` (`rgw_file.cc`) invokes three calls to `RGWRados::get_obj_state` with `RGWObjState::prefetch_data = true`. It results in great read amplification. If `length` argument in `rgw_read` call is smaller than `rgw_max_chunk_size`, then the amplification is threefold.

Signed-off-by: Kajetan Janiak <kjaniak@cloudferro.com>

2020-11-18 15:40 UTC, mattbenjamin commented
@kajetanj thanks for spotting this;  at the moment, I think it probably is correct to avoid prefetching in general, but we might be able to address this in future and also take advantage of range prefetch (@ofriedma) and some additional infrastructure to get benefit from caching in future?  It's definitely not intended that there be multiple prefetch attempts, so we'd have to fix that, also

2020-11-18 15:41 UTC, mattbenjamin commented
@kajetanj can you create a tracker issue and attach it to his PR?

2020-11-18 15:45 UTC, mattbenjamin approved these changes
lgtm (but please update with tracker issue)

2020-11-18 15:46 UTC, kajetanj commented
@mattbenjamin my account on tracker is pending administrator approval. Would you like me to include full reproduction steps or just describe the issue?

2020-11-18 16:01 UTC, mattbenjamin commented
@kajetanj either is fine;  what's your account name in tracker?  I can try to expedite it

2020-11-18 16:23 UTC, kajetanj commented
@mattbenjamin it is `kjaniak`. Thanks.

2020-11-18 16:29 UTC, ofriedma requested changes
I think it would be with less changes just to change line 1975 to false from true
```suggestion
RGWGetObj::get_data = false; // XXX
```

2020-11-18 16:31 UTC, mattbenjamin commented
> 
> 
> I think it would be with less changes just to change line 1975 from true to false
> 
> ```
> RGWGetObj::get_data = false; // XXX
> ```

I don't agree with this advice.  @kajetanj 's proposal is fine, and will inline just fine.

Matt

2020-11-19 09:55 UTC, kajetanj commented
@mattbenjamin Tracker issue added (link in the first comment).
@ofriedma 

> I think it would be with less changes just to change line 1975 from true to false
> 
> ```
> RGWGetObj::get_data = false; // XXX
> ```

it would cause problems in `RGWGetObj::execute`, `rgw_op.cc:2220`
```
  if (!get_data || ofs > end) {
    send_response_data(bl, 0, 0);
    return;
  }
```

2020-11-19 13:53 UTC, ofriedma approved these changes

2020-11-19 14:13 UTC, kajetanj commented
Could we backport this to Nautilus?

2020-11-19 15:21 UTC, dang commented
Just mark the tracker with the backports you want.

2020-11-19 16:04 UTC, kajetanj commented
@dang it seems I can't edit an existing issue, so I added a note

2020-11-19 16:12 UTC, mattbenjamin commented
done:  we want octopus, nautilus, I believe

2020-11-23 13:49 UTC, mattbenjamin commented
@dang tested by hand in a Nautilus backport, passed librgw_file_nfsns, the main unit file.

2020-11-23 15:30 UTC, dang approved these changes

2020-11-25 23:02 UTC, mattbenjamin commented
I've proved non-regression in unit tests run by hand, maybe worth confirming perf result

2020-12-03 12:55 UTC, merged