src/CMakeLists.txt: add lua version
ceph/ceph pull request #38217
Opened 2020-11-20 14:07 UTC by ideepika

fixes: https://tracker.ceph.com/issues/48312
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-22 08:50 UTC, yuvalif approved these changes

2020-11-23 08:06 UTC, tchaikov requested changes
could you change the title to something like

> cmake: require Lua 5.3 and up

?

2020-11-23 09:46 UTC, ideepika commented
> could you change the title to something like
> 
> > cmake: require Lua 5.3 and up
> 
> ?

updated, thanks!

2020-11-23 10:19 UTC, tchaikov approved these changes

2020-11-24 09:54 UTC, tchaikov commented
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2020-11-24-1112/bfdd6af5c991e46a8037b6e41ba54ffcbea5b4fb/default/

2020-11-24 10:00 UTC, merged