test/: some Formatter pointers not freed
ceph/ceph pull request #38223
Opened 2020-11-21 08:36 UTC by Rethan

some codes under test use Formatter to output, but Formatter *f
was not freed like elsewere

Signed-off-by: haoyixing <haoyixing@kuaishou.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-11-21 08:40 UTC, tchaikov requested changes
the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

also, might want to use `std::unique_ptr<>` instead.

2020-11-21 10:11 UTC, Rethan commented
> the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend` and `git push -f` for revising the commit message and its title.
> 
> also, might want to use `std::unique_ptr<>` instead.

Thanks for comments and I've made some changes. I also noticed the inappropriate commit message after push (should keep that in mind earlier).

2020-11-21 10:32 UTC, tchaikov approved these changes

2020-11-21 11:01 UTC, merged

2020-11-21 16:50 UTC, wjwithagen commented
Clang certainly does not like this: 
```
src/test/objectstore/store_test.cc:7897:32: error: no viable conversion from 'std::unique_ptr<Formatter>' to 'ceph::Formatter *'
src/test/objectstore/store_test.cc:7941:28: error: no viable conversion from 'std::unique_ptr<Formatter>' to 'ceph::Formatter *'
src/test/objectstore/store_test.cc:8486:44: error: no viable conversion from 'std::unique_ptr<Formatter>' to 'ceph::Formatter *'
````

2020-11-21 16:53 UTC, wjwithagen commented
More exact:
```
src/test/objectstore/store_test.cc:7897:32: error: no viable conversion from 'std::unique_ptr<Formatter>' to 'ceph::Formatter *'
  store->generate_db_histogram(f);
                               ^
src/os/ObjectStore.h:245:55: note: passing argument to parameter 'f' here
  virtual void generate_db_histogram(ceph::Formatter *f) { }

```

2020-11-21 17:07 UTC, wjwithagen commented
So either revert this change, and fix the free problem in another way.
Or we need to add code to help with the conversion `std::unique_ptr -> ceph::Formatter`

2020-11-22 00:43 UTC, ivancich commented
@Rathan, @tchaikov : This commit breaks are Shaman builds as well. For example, see: https://shaman.ceph.com/builds/ceph/wip-rgw-gc-defer-should-not-enqueue/

I see there's no QA run noted.

2020-11-22 02:14 UTC, tchaikov commented
@wjwithagen @ivancich gentlemen, sorry for breaking the build. should be fixed now.

2020-11-22 10:43 UTC, wjwithagen commented
@tchaikov 
Things happen, no problem there.
Saw the fix, and that works for me.