ceph-volume: disable cache for blkid calls
ceph/ceph pull request #38447
Opened 2020-12-04 12:43 UTC by xelexin

Due to bugs in cache managment in blkid, there are possible to have
nonexistence entries. This entries breaks ceph-volume operations by
passing two or more outputs instead of one (eg. /dev/sdk2).

Fixes: https://tracker.ceph.com/issues/48464
Signed-off-by: Rafał Wądołowski <rafal@rafal.net.pl>

2020-12-07 09:46 UTC, rishabh-d-dave requested changes
It's useful to have "Fixes https://tracker.ceph.com/issues/48464" line in the commit. Please add it. LGTM otherwise.

2020-12-07 09:50 UTC, rishabh-d-dave commented
jenkins test ceph-volume tox

2020-12-07 10:00 UTC, rishabh-d-dave commented
jenkins test ceph-volume all

2020-12-07 11:33 UTC, xelexin commented
@rishabh-d-dave done

2020-12-07 14:52 UTC, rishabh-d-dave commented
jenkins test ceph-volume tox

2020-12-07 15:00 UTC, rishabh-d-dave commented
jenkins test ceph-volume all

2020-12-07 19:52 UTC, rishabh-d-dave approved these changes

2020-12-08 12:07 UTC, jan--f approved these changes
Thanks! LGTM.

2020-12-17 15:32 UTC, merged