mgr/volumes/nfs: remove 'ganesha-' prefix from cluster id
ceph/ceph pull request #38510
Opened 2020-12-09 17:07 UTC by varshar16

Orchestrator defines service name as "<service_type>.<service_id>". The ganesha
common config object name in orchestrator is "conf-<service_name>". Volume's
nfs plugin deploys nfs-ganesha clusters with 'ganesha' prefixed to cluster id
and common config object. It can cause unecessary issues in rook and cephadm.
So let's remove the prefix.

Fixes: https://tracker.ceph.com/issues/48514
Signed-off-by: Varsha Rao <varao@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-12-09 18:44 UTC, batrick reviewed
I'm okay with this change but what about making it backwards compatible for folks who setup clusters on Octopus?

2020-12-16 15:46 UTC, varshar16 commented
> I'm okay with this change but what about making it backwards compatible for folks who setup clusters on Octopus?

The way namespace is set, makes backward compatibility complicated.

2020-12-16 15:47 UTC, varshar16 commented
jenkins retest this please

2020-12-22 21:07 UTC, batrick commented
> > I'm okay with this change but what about making it backwards compatible for folks who setup clusters on Octopus?
> 
> The way namespace is set, makes backward compatibility complicated.

I think the most basic form of backwards compatibility is to just load `userconf-ganesha-{user_id}` if `userconf-{user_id}` does not exist? Then always save the new name (and leave the old object behind). Is it not that simple? The daemon names is indeed a little more work?

2021-01-05 11:31 UTC, varshar16 commented
> > > I'm okay with this change but what about making it backwards compatible for folks who setup clusters on Octopus?
> > 
> > 
> > The way namespace is set, makes backward compatibility complicated.
> 
> I think the most basic form of backwards compatibility is to just load `userconf-ganesha-{user_id}` if `userconf-{user_id}` does not exist? Then always save the new name (and leave the old object behind). Is it not that simple? The daemon names is indeed a little more work?

As discussed change to config object is not required to maintain backward compatibility. Rather will require changes to namespace.

2021-01-07 15:55 UTC, batrick requested changes

2021-01-07 15:55 UTC, batrick commented on PendingReleaseNotes
> +  orchestartor backends. Please delete any existing nfs-ganesha clusters and
```suggestion
  orchestrator backends. Please delete any existing nfs-ganesha clusters prior to upgrading and
```

2021-01-07 15:55 UTC, batrick commented on PendingReleaseNotes
> +  redeploy new clusters.
```suggestion
  redeploy new clusters after upgrading to Pacific.
```

2021-01-08 07:10 UTC, varshar16 commented on PendingReleaseNotes
> +  orchestartor backends. Please delete any existing nfs-ganesha clusters and
Done

2021-01-08 07:10 UTC, varshar16 commented on PendingReleaseNotes
> +  redeploy new clusters.
Done

2021-01-08 11:01 UTC, varshar16 commented
Tests Passed: http://qa-proxy.ceph.com/teuthology/varsha-2021-01-08_10:15:12-rados-wip-nfs-remove-ganesha-prefix-distro-basic-smithi/

2021-01-08 18:39 UTC, batrick approved these changes

2021-01-08 18:39 UTC, merged