ceph-volume: util.disk.is_locked_raw_device refactor
ceph/ceph pull request #38535
Opened 2020-12-10 22:01 UTC by guits

The current implementation of `is_locked_raw_device()` tries to open and
acquire an exclusive lock on the device, this might trigger udev events
and cause race condition.

using `lslocks` which is present on all Linux distribution as part of
`util-linux` reads `/proc/locks` and doesn't trigger udev events.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-12-17 15:20 UTC, jan--f requested changes
Hmm this doesn't seem to work for me on a test cluster.
```
node1:~ # ceph-volume inventory /dev/vdb

====== Device report /dev/vdb ======

     path                      /dev/vdb
     available                 False
     rejected reasons          Insufficient space (<10 extents) on vgs, LVM detected, locked
     device id                 352947
     removable                 0
     ro                        0
     vendor                    0x1af4
     model                     
     sas address               
     rotational                1
     scheduler mode            mq-deadline
     human readable size       8.00 GB
    --- Logical Volume ---
     name                      osd-block-4f128d5e-bd8d-4456-a45d-4628f6ffd426
     osd id                    1
     cluster name              ceph
     type                      block
     osd fsid                  4f128d5e-bd8d-4456-a45d-4628f6ffd426
     cluster fsid              ab6d3dac-e42a-41a6-a9e7-7cbbba0cdf48
     osdspec affinity          
     block uuid                s1vl8i-LEEc-QLQb-VsVR-TEId-MiG0-IpV6Le
node1:~ # lslocks --raw --noheading --output path
/var/lib/ceph/osd/ceph-5/fsid
/dev/dm-1
/var/lib/ceph/osd/ceph-12/fsid
/dev/dm-2
/run/lvmetad.pid
/var/lib/ceph/mon/ceph-node1/store.db/LOCK
/var/lib/ceph/osd/ceph-1/fsid
/dev/dm-0
```

Given that we are unsure what this check protects I'd rather err on the side of caution before changing this. My concern is that this could mark previously excluded disks suddenly as available. Likely this will cause c-v to error out somewhere else, but if not this can get uncomfrtable. Consider this in the same cluster:
```
node1:~ # ceph-volume inventory /dev/vda

====== Device report /dev/vda ======

     path                      /dev/vda
     available                 False
     rejected reasons          locked
     device id                 
     removable                 0
     ro                        0
     vendor                    0x1af4
     model                     
     sas address               
     rotational                1
     scheduler mode            mq-deadline
     human readable size       42.00 GB
```
/dev/vda is the root disk. While I don't think c-v would try to deploy an osd there, this could break other workflows, e.g. an automated batch call that is triggered on all devices marked available.

2020-12-17 15:30 UTC, guits commented
@jan--f that's why i finally set the label "DNM", I realized something isn't clear, I'll try to take a better look at this soon

2021-01-13 15:45 UTC, andrewschoen commented
> Hmm this doesn't seem to work for me on a test cluster.
> 
> ```
> node1:~ # ceph-volume inventory /dev/vdb
> 
> ====== Device report /dev/vdb ======
> 
>      path                      /dev/vdb
>      available                 False
>      rejected reasons          Insufficient space (<10 extents) on vgs, LVM detected, locked
>      device id                 352947
>      removable                 0
>      ro                        0
>      vendor                    0x1af4
>      model                     
>      sas address               
>      rotational                1
>      scheduler mode            mq-deadline
>      human readable size       8.00 GB
>     --- Logical Volume ---
>      name                      osd-block-4f128d5e-bd8d-4456-a45d-4628f6ffd426
>      osd id                    1
>      cluster name              ceph
>      type                      block
>      osd fsid                  4f128d5e-bd8d-4456-a45d-4628f6ffd426
>      cluster fsid              ab6d3dac-e42a-41a6-a9e7-7cbbba0cdf48
>      osdspec affinity          
>      block uuid                s1vl8i-LEEc-QLQb-VsVR-TEId-MiG0-IpV6Le
> node1:~ # lslocks --raw --noheading --output path
> /var/lib/ceph/osd/ceph-5/fsid
> /dev/dm-1
> /var/lib/ceph/osd/ceph-12/fsid
> /dev/dm-2
> /run/lvmetad.pid
> /var/lib/ceph/mon/ceph-node1/store.db/LOCK
> /var/lib/ceph/osd/ceph-1/fsid
> /dev/dm-0
> ```
> 
> Given that we are unsure what this check protects I'd rather err on the side of caution before changing this. My concern is that this could mark previously excluded disks suddenly as available. Likely this will cause c-v to error out somewhere else, but if not this can get uncomfrtable. Consider this in the same cluster:

I've looked into how `is_locked_raw_device` is used and it seems like it's only used for reporting purposes. I share the same concern you do though. While it doesn't seem as `ceph-volume` itself is making any decisions based of that `locked` property, other scripts might be running `ceph-volume inventory` and trying to deploy on any devices that are listed as available.

Another option here could be to deprecate that `locked` property from the `ceph-volume inventory` output and remove the function entirely. We'd have to do that over multiple releases and log deprecation warnings though if we wanted to be really careful.

2022-07-08 18:24 UTC, guits commented
jenkins test ceph-volume tox

2022-07-13 18:24 UTC, adk3798 commented
jenkins test api

2022-11-27 22:02 UTC, closed without merging