doc: add explanatory note about cache trim rate setting
ceph/ceph pull request #38587
Opened 2020-12-15 12:40 UTC by jan--f

Fixes: https://tracker.ceph.com/issues/48585

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2020-12-15 14:26 UTC, zdover23 commented
LGTM.

2020-12-15 14:32 UTC, ayushontop reviewed
is it necessary?

2020-12-15 14:42 UTC, batrick requested changes

2020-12-23 14:59 UTC, batrick commented
retest this please

2021-01-06 21:34 UTC, batrick approved these changes

2021-01-06 21:35 UTC, merged