msg: using swith-case replease if-else.
ceph/ceph pull request #38811
Opened 2021-01-08 07:28 UTC by majianpeng

For point of performance, swith-case is better than if-else for blackhole check.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-01-08 07:30 UTC, tchaikov approved these changes

2021-01-08 07:30 UTC, tchaikov commented on src/msg/Connection.cc
> +      res = conf->ms_blackhole_mon;
```suggestion
      return conf->ms_blackhole_mon;
```

2021-01-08 07:32 UTC, tchaikov commented
@majianpeng could you fix the typos in the commit message?

2021-01-08 07:39 UTC, majianpeng commented
@tchaikov . update by your suggestions. Thanks!

2021-01-08 08:08 UTC, tchaikov requested changes

2021-01-08 08:08 UTC, tchaikov commented on src/msg/Connection.cc
> +      break;
might want to drop `break` here.

2021-01-08 08:08 UTC, tchaikov commented on src/msg/Connection.cc
> +      break;
ditto.

2021-01-08 08:08 UTC, tchaikov commented on src/msg/Connection.cc
> +  }
```suggestion
  default:
    return false;
  }
```

2021-01-08 08:08 UTC, tchaikov commented on src/msg/Connection.cc
> +    case CEPH_ENTITY_TYPE_MON:
also, we don't add indent before `case`. please reference other places in the source code.

2021-01-08 08:47 UTC, tchaikov approved these changes

2021-01-08 08:49 UTC, majianpeng commented
@tchaikov . Thanks for careful review code.

2021-01-12 04:20 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-01-10_14:19:31-rados-wip-kefu2-testing-2021-01-10-1949-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-01-11_11:52:22-rados-wip-kefu2-testing-2021-01-10-1949-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/46323
- https://tracker.ceph.com/issues/48777

2021-01-12 04:20 UTC, merged