qa/tasks/ceph: fix failure on interactive on error when ctx.archive is missing
ceph/ceph pull request #38817
Opened 2021-01-08 15:04 UTC by ideepika

```
   File "/home/teuthworker/src/github.com_ideepika_ceph_wip-tracker-48613/qa/tasks/ceph.py", line 81, in update_archive_setting
        with open(os.path.join(ctx.archive, 'info.yaml'), 'r+') as info_file:
      File "/home/ideepika/teuthology/virtualenv/lib/python3.6/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-01-08 16:23 UTC, tchaikov commented on qa/tasks/ceph.py
> +    if ctx.archive is not None:
```suggestion
    if ctx.archive not None:
         return
```

2021-01-08 16:27 UTC, tchaikov requested changes
might want to update the title of the commit to be more specific. you might want to fill the body with the details on what issue this change addresses instead.

2021-01-08 17:27 UTC, ideepika commented
> might want to update the title of the commit to be more specific. you might want to fill the body with the details on what issue this change addresses instead.

that be more clear, thanks for the feedback @tchaikov!

2021-01-11 16:08 UTC, tchaikov approved these changes

2021-01-20 21:21 UTC, merged