[RFC] mgr/cephadm: Use our image for remote tool execution
ceph/ceph pull request #38926
Opened 2021-01-15 10:40 UTC by sebastian-philipp

Fixes: https://tracker.ceph.com/issues/48870

This deals with a cephadm upgrade issue:

1. user calls `ceph orch upgrade`
2. mgr/cephadm calls `ceph orch config set mgr.x container_image <new-container>`
3. standby mgr gets upgraded
4. mgr failover to new mgr
5. mgr/cephadm calls `_refresh_host_devices`
6. `_refresh_host_devices` calls` ceph orch config get osd container_image`.
  But this returns the old image
7. `_refresh_host_devices` calls `ceph-volume ... --filter-for-batch`
  with an image that doesn't support `filter-for-batch`

The idea is to _always_ call tools with the same container image as
run by the active mgr. This way we don't need to deal with CLI changes at all.
Downside is: tools need to be able to cope with being called
with alternating versions on the same host.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-01-15 12:30 UTC, jmolmo commented on src/pybind/mgr/cephadm/module.py
> +    def this_daemon_name(self) -> str:
I like more "active_mgr_name"

2021-01-15 12:45 UTC, jmolmo requested changes
In **serve.py**:

I think this `cephadmNoImage` should be changed also to `self.this_daemon_name`
```python
    def _refresh_facts(self, host: str) -> Optional[str]:
        try:	        try:
            out, err, code = self._run_cephadm(	            out, err, code = self._run_cephadm(
                host, cephadmNoImage, 'gather-facts', [],	                host, cephadmNoImage, 'gather-facts', [],
                error_ok=True, no_fsid=True)	                error_ok=True, no_fsid=True)
```

In **cephadmservice.py**:

`self.mgr.get_mgr_id()` not changed by `self.mgr.this_daemon_name`
```python
    def fail_over(self) -> None:
        if not self.mgr_map_has_standby():
            raise OrchestratorError('Need standby mgr daemon', event_kind_subject=(
                'daemon', 'mgr' + self.mgr.get_mgr_id()))
```

And another couple of  replacements of `self.mgr.get_mgr_id `in **monitoring.py**:

```
 ./services/monitoring.py:120:           if dd.daemon_id == self.mgr.get_mgr_id():
./services/monitoring.py:195:            if dd.daemon_id == self.mgr.get_mgr_id():
```

2021-01-15 13:46 UTC, sebastian-philipp commented
> In **serve.py**:
> 
> I think this `cephadmNoImage` should be changed also to `self.this_daemon_name`
> 
> ```python
>     def _refresh_facts(self, host: str) -> Optional[str]:
>         try:	        try:
>             out, err, code = self._run_cephadm(	            out, err, code = self._run_cephadm(
>                 host, cephadmNoImage, 'gather-facts', [],	                host, cephadmNoImage, 'gather-facts', [],
>                 error_ok=True, no_fsid=True)	                error_ok=True, no_fsid=True)
> ```

does `gather-facts` require a container image?

> 
> In **cephadmservice.py**:
> 
> `self.mgr.get_mgr_id()` not changed by `self.mgr.this_daemon_name`
> 
> ```python
>     def fail_over(self) -> None:
>         if not self.mgr_map_has_standby():
>             raise OrchestratorError('Need standby mgr daemon', event_kind_subject=(
>                 'daemon', 'mgr' + self.mgr.get_mgr_id()))
> ```
> 
> And another couple of replacements of `self.mgr.get_mgr_id `in **monitoring.py**:
> 
> ```
>  ./services/monitoring.py:120:           if dd.daemon_id == self.mgr.get_mgr_id():
> ./services/monitoring.py:195:            if dd.daemon_id == self.mgr.get_mgr_id():
> ```

Thanks!

2021-01-15 14:06 UTC, jmolmo commented
Forget my comment about "gather-facts" it does not use any daemon ( I was wrong thinking that disk info was getting also from ceph-volume).

2021-01-18 16:51 UTC, sebastian-philipp commented
https://pulpito.ceph.com/swagner-2021-01-18_11:44:14-rados:cephadm-wip-swagner3-testing-2021-01-15-1455-distro-basic-smithi/

Failures

https://tracker.ceph.com/issues/48894
https://tracker.ceph.com/issues/48715
https://tracker.ceph.com/issues/48142

2021-01-19 03:46 UTC, tserong commented
> Downside is: tools need to be able to cope with being called with alternating versions on the same host.

I don't understand this point. Can you elaborate please?

2021-01-19 12:22 UTC, sebastian-philipp commented
> > Downside is: tools need to be able to cope with being called with alternating versions on the same host.
> 
> I don't understand this point. Can you elaborate please?

In case we merge this PR, we're facing a new potential problem:

The upgrade works by upgrading one MGR at a time. which means, while the upgrade is in progress, there is a potential to failover between MGRs running different versions. If we now bind the ceph-volume container image version to the active MGR, a MGR failover to an older version then will call ceph-volume also with the older version. 

Imagine we have to MGRs: active mgr.x running 15.2.8 and standby mgr.y running 15.2.5. We'd call ceph-volume version 15.2.8 on all hosts as this is the active MGR version. Then we failover to mgr.y. Suddenly, we'd call ceph-volume on all hosts in version 15.2.5. I'm not sure @jan--f would appreciate this behavior of cephadm.

2021-01-20 05:11 UTC, tserong commented
I guess whether it matters or not depends on what we're doing with ceph-volume (or whatever other tools are used). If it's just querying state I'm having a hard time seeing this being a problem. But if (to use your example version numbers) ceph-volume 15.2.8 were used to actually change something (say, deploy a new OSD), and this relied on some feature not present in 15.2.5, then I can see how 15.2.5 might theoretically get confused if we switched back to it.

2021-02-05 13:56 UTC, liewegas approved these changes

2021-02-09 11:11 UTC, sebastian-philipp commented
jenkins retest this

2021-02-09 11:11 UTC, sebastian-philipp commented
jenkins retest this please

2021-02-12 00:04 UTC, sebastian-philipp commented
* https://pulpito.ceph.com/swagner-2021-02-10_11:41:39-rados:cephadm-wip-swagner-testing-2021-02-09-1126-distro-basic-smithi/
* https://pulpito.ceph.com/swagner-2021-02-11_10:31:33-rados:cephadm-wip-swagner-testing-2021-02-09-1126-distro-basic-smithi/

Failures:

* https://tracker.ceph.com/issues/49259
* e2e test

2021-06-15 12:55 UTC, closed without merging