mgr/orchestrator: disallow_untyped_defs = True
ceph/ceph pull request #38954
Opened 2021-01-18 15:46 UTC by sebastian-philipp

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-01-18 16:31 UTC, tchaikov approved these changes

2021-01-18 16:36 UTC, tchaikov requested changes

2021-01-18 16:36 UTC, tchaikov commented on src/pybind/mgr/orchestrator/_interface.py
> +class InnerCliCommandCallable(Protocol):
`Protocol` might not be defined.

2021-01-19 10:25 UTC, sebastian-philipp commented on src/pybind/mgr/orchestrator/_interface.py
> +class InnerCliCommandCallable(Protocol):
added in python 3.8. sigh.

2021-01-19 10:54 UTC, sebastian-philipp commented
jenkins test api

2021-01-19 11:21 UTC, tchaikov approved these changes

2021-01-19 16:36 UTC, mgfritch approved these changes
nit, but otherwise lgtm!

2021-01-19 16:36 UTC, mgfritch commented on src/pybind/mgr/cephadm/module.py
> +    def process(self, completions: List[CephadmCompletion]) -> None:  # type: ignore
```suggestion
    def process(self, completions: List[orchestrator.Completion]) -> None:  # type: ignore
```

interesting, Liskov substitution principle ... use the super class here and implement the `evaluate` attr?

2021-01-20 11:46 UTC, sebastian-philipp commented
https://pulpito.ceph.com/swagner-2021-01-20_09:35:12-rados:cephadm-wip-swagner-testing-2021-01-19-1509-distro-basic-smithi/

lots of pull failures today.

2021-01-20 11:46 UTC, merged