pacific: os/bluestore: fix deferred_queue locking
ceph/ceph pull request #38989
Opened 2021-01-20 17:16 UTC by neha-ojha

https://github.com/ceph/ceph/pull/30027 introduced a gap in osr
protection (in _deferred_queue()) which could cause improper deferred_pending value while
processing osr from _deferred_aio_finish().
As a result both segmentation fault in _deferred_aio_finish() or deadlock could occur.

Fixes: https://tracker.ceph.com/issues/48776

Signed-off-by: Igor Fedotov <ifedotov@suse.com>
(cherry picked from commit ac73df71584eb482e626f38e4a12f4c044db3231)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-01-20 17:29 UTC, tchaikov commented
@neha-ojha @jdurgin @liewegas so we don't backport master changes back to pacific in bulk anymore, but instead start cherry-picking from it?

2021-01-20 18:22 UTC, neha-ojha commented
> @neha-ojha @jdurgin @liewegas so we don't backport master changes back to pacific in bulk anymore, but instead start cherry-picking from it?

@tchaikov the plan is to create a pacific backport PR as soon as the master PR merges

2021-01-20 18:53 UTC, jdurgin approved these changes

2021-01-20 20:12 UTC, ifed01 requested changes
Please hold on till  the additional PR comes in: https://github.com/ceph/ceph/pull/38992

See its description for the rationales.

2021-01-25 18:12 UTC, neha-ojha commented
Includes https://github.com/ceph/ceph/pull/38992

2021-01-25 19:52 UTC, ifed01 approved these changes

2021-01-25 19:52 UTC, ifed01 commented
jenkins test make check

2021-01-26 00:17 UTC, neha-ojha commented
jenkins test make check

2021-01-26 16:41 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri7-testing-2021-01-26-0840-pacific](https://trello.com/c/RN6qY3JS/1122-wip-yuri7-testing-2021-01-26-0840-pacific)

2021-01-27 20:19 UTC, yuriw commented
test this please

2021-01-27 23:51 UTC, merged