rbd: change rbd showmapped format of image name
ceph/ceph pull request #39012
Opened 2021-01-22 02:25 UTC by Rethan

When format is plain, for both rbd showmapped -t krbd and -t nbd, image name column is "image",
when format is json, only for -t nbd, the key is "image". For -t rbd, it's "name", maybe can
change them to a same pattern.

Signed-off-by: haoyixing <haoyixing@kuaishou.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-01-22 07:38 UTC, Rethan commented
before change
rbd map list in plain format
![image](https://user-images.githubusercontent.com/8347603/105460940-7a000100-5cc7-11eb-821a-ea932d496e3d.png)
nbd map list in plain format
![image](https://user-images.githubusercontent.com/8347603/105461032-9b60ed00-5cc7-11eb-8d42-09281babe4a3.png)
rbd map list in json format
![image](https://user-images.githubusercontent.com/8347603/105461055-a4ea5500-5cc7-11eb-8be7-3d88ab7cf3f6.png)
nbd map list in json format
![image](https://user-images.githubusercontent.com/8347603/105461064-a87ddc00-5cc7-11eb-88a8-379ac0e2844d.png)

after change
rbd map list in json format
![image](https://user-images.githubusercontent.com/8347603/105461142-c1868d00-5cc7-11eb-8fb0-ed1639ff45a9.png)
change key to "image" as others

2021-02-03 13:37 UTC, Rethan commented
@tchaikov please help to review if that's convenient

2021-02-23 10:08 UTC, Rethan commented
ping?

2021-03-27 08:49 UTC, trociny approved these changes
LGTM

@idryomov Are you fine with it?

2021-03-28 09:30 UTC, idryomov requested changes
It's been "name" for a long time -- since 2013 when json/xml formatting was introduced.  And "name" is used in many other places, including `rbd info` and `rbd du`.  So if anything it is `-t nbd` that is inconsistent.

I think we need to pick one and switch to it everywhere with an accompanying release note.  Changing just `-t krbd` is not a way to go.

2021-04-02 05:08 UTC, Rethan commented
> It's been "name" for a long time -- since 2013 when json/xml formatting was introduced. And "name" is used in many other places, including `rbd info` and `rbd du`. So if anything it is `-t nbd` that is inconsistent.
> 
> I think we need to pick one and switch to it everywhere with an accompanying release note. Changing just `-t krbd` is not a way to go.

Both "image" and "name" have many occurrances, so change to either will bring several changes. I just change them all to "name".

2021-04-03 10:24 UTC, idryomov requested changes
Between "name" and "image", I'd go with "image".  And while at it, also change "id" to "image_id" for consistency with "snapshot" and "snapshot_id".  There are probably other inconsistencies and maybe type errors too -- we need to do a thorough audit and bundle these fixes together, documented in a single release note.

2021-06-11 04:46 UTC, trociny approved these changes
LGTM
@idryomov what do you think?

2022-01-10 01:59 UTC, closed without merging