cephadm: refactor call() using asyncio.asyncio.StreamReader
ceph/ceph pull request #39043
Opened 2021-01-24 07:00 UTC by tchaikov

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-01-25 12:39 UTC, tchaikov commented
https://pulpito.ceph.com/kchai-2021-01-25_11:56:01-rados-wip-kefu-testing-2021-01-25-1755-distro-basic-smithi/ none of the failures is related.

2021-01-25 13:18 UTC, sebastian-philipp commented
https://pulpito.ceph.com/kchai-2021-01-25_11:56:01-rados-wip-kefu-testing-2021-01-25-1755-distro-basic-smithi/5827809

```
2021-01-25T12:22:25.942 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]: Traceback (most recent call last):
2021-01-25T12:22:25.943 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
2021-01-25T12:22:25.943 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     self.run()
2021-01-25T12:22:25.943 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/usr/lib64/python3.6/threading.py", line 864, in run
2021-01-25T12:22:25.943 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     self._target(*self._args, **self._kwargs)
2021-01-25T12:22:25.944 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 6491, in _scrape_host_facts
2021-01-25T12:22:25.944 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     data = json.loads(facts.dump())
2021-01-25T12:22:25.944 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 6130, in dump
2021-01-25T12:22:25.944 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     data = {k: getattr(self, k) for k in dir(self)
2021-01-25T12:22:25.945 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 6132, in <dictcomp>
2021-01-25T12:22:25.945 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     isinstance(getattr(self, k),
2021-01-25T12:22:25.945 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 6116, in kernel_parameters
2021-01-25T12:22:25.945 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     out, _, _ = call_throws(self.ctx, ['sysctl', '-a'], verbosity=CallVerbosity.SILENT)
2021-01-25T12:22:25.946 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 1306, in call_throws
2021-01-25T12:22:25.946 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     out, err, ret = call(ctx, command, desc, verbosity, timeout, **kwargs)
2021-01-25T12:22:25.946 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 1286, in call
2021-01-25T12:22:25.946 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     returncode, out, err = async_run(run_with_timeout())
2021-01-25T12:22:25.947 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 1228, in async_run
2021-01-25T12:22:25.947 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     return loop.run_until_complete(coro)
2021-01-25T12:22:25.947 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
2021-01-25T12:22:25.947 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     return future.result()
2021-01-25T12:22:25.947 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 1266, in run_with_timeout
2021-01-25T12:22:25.948 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     **kwargs)
2021-01-25T12:22:25.948 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/usr/lib64/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
2021-01-25T12:22:25.948 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     bufsize, **kwargs)
2021-01-25T12:22:25.948 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/usr/lib64/python3.6/asyncio/unix_events.py", line 203, in _make_subprocess_transport
2021-01-25T12:22:25.949 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     self._child_watcher_callback, transp)
2021-01-25T12:22:25.949 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/usr/lib64/python3.6/asyncio/unix_events.py", line 867, in add_child_handler
2021-01-25T12:22:25.949 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:     "Cannot add child handler, "
2021-01-25T12:22:25.949 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]: RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2021-01-25T12:22:25.950 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]: host thread not running
2021-01-25T12:22:25.950 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:20:01 smithi035 bash[38765]: unable to run systemctl: Cannot add child handler, the child watcher does not have a loop attached
```

2021-01-25 13:59 UTC, tchaikov commented
@sebastian-philipp 
```
2021-01-25T12:22:25.947 INFO:tasks.workunit.client.0.smithi035.stdout:Jan 25 12:19:51 smithi035 bash[38765]:   File "/var/lib/ceph/00000000-0000-0000-0000-0000deadbeef/cephadm", line 1228, in async_run
```

it was somehow testing the version without this patch. see https://github.com/ceph/ceph/pull/39043/files#diff-d0f7acffbce59b9e36a1479d1b1f32955cd811ab8b0b1aa0018a2003f0c4d73eL1228

2021-01-26 03:13 UTC, pcuzner requested changes
ls works, gather-facts works...but ceph-volume intentory fails;
<pre>
[root@cephadmtest cca4d380-5f57-11eb-bbb0-52540076f84a]# ./cephadm ceph-volume inventory
Traceback (most recent call last):
  File "./cephadm", line 7530, in <module>
    main()
  File "./cephadm", line 7519, in main
    r = ctx.func(ctx)
  File "./cephadm", line 1522, in _infer_fsid
    elif ctx.has("name") or not ctx.name:
  File "./cephadm", line 162, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'CephadmContext' object has no attribute 'name'
</pre>

2021-01-26 03:13 UTC, pcuzner commented on src/cephadm/cephadm
> +            stdout, stderr = await syncio.gather(tee(process.stdout),
syncio .. asyncio?

2021-01-26 04:10 UTC, tchaikov commented on src/cephadm/cephadm
> +            stdout, stderr = await syncio.gather(tee(process.stdout),
fixed and repushed.

2021-01-26 04:26 UTC, pcuzner commented
as before, ls works, gather-facts works
ceph-volume inventory fails
<pre>
[root@cephadmtest cca4d380-5f57-11eb-bbb0-52540076f84a]# ./cephadm ceph-volume inventory                 
Traceback (most recent call last):                                                                       
  File "./cephadm", line 7527, in <module>
    main()
  File "./cephadm", line 7516, in main
    r = ctx.func(ctx)
  File "./cephadm", line 1519, in _infer_fsid
    elif ctx.has("name") or not ctx.name:
  File "./cephadm", line 162, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'CephadmContext' object has no attribute 'name'

</pre>

and attempting to use the exporter fails
<pre>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 6457, in _scrape_host_facts
    data = json.loads(facts.dump())
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 6096, in dump
    data = {k: getattr(self, k) for k in dir(self)
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 6098, in <dictcomp>
    isinstance(getattr(self, k),
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 6082, in kernel_parameters
    out, _, _ = call_throws(self.ctx, ['sysctl', '-a'], verbosity=CallVerbosity.SILENT)
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 1272, in call_throws
    out, err, ret = call(ctx, command, desc, verbosity, timeout, **kwargs)
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 1254, in call
    stdout, stderr, returncode = async_run(run_with_timeout())
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 1198, in async_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/var/lib/ceph/cca4d380-5f57-11eb-bbb0-52540076f84a/cephadm", line 1241, in run_with_timeout
    stderr=asyncio.subprocess.PIPE)
  File "/usr/lib64/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 203, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 867, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

</pre>

I'm taking your version and dropping it straight into my local cluster and see the above issues. What am I missing?

2021-01-26 05:04 UTC, tchaikov commented
@pcuzner i just realized that `self._scrape_host_facts()` and friends are run in a separated thread. but we can only plan signal handler in the main thread using `async_run()` if `asyncio.run()` is not available. let me think about this...

2021-01-26 08:14 UTC, tchaikov commented
@pcuzner fixed and repushed.

2021-01-26 09:44 UTC, tchaikov commented
https://pulpito.ceph.com/kchai-2021-01-26_09:42:05-rados:cephadm-wip-cephadm-call-distro-basic-smithi/

2021-01-26 14:13 UTC, tchaikov commented
jenkins test api

2021-01-26 15:10 UTC, liewegas commented
> @pcuzner i just realized that `self._scrape_host_facts()` and friends are run in a separated thread. but we can only plan signal handler in the main thread using `async_run()` if `asyncio.run()` is not available. let me think about this...

Perhaps https://github.com/ceph/ceph/pull/39031 ? I think the simplified select() construction is pretty easy to follow.

2021-01-26 15:19 UTC, tchaikov commented
@liewegas i fixed the issue already. see https://pulpito.ceph.com/kchai-2021-01-26_13:02:43-rados:cephadm-wip-cephadm-call-distro-basic-smithi/. none of the tests is related.

but i am fine either way.

2021-01-26 20:20 UTC, pcuzner approved these changes

2021-01-26 20:25 UTC, pcuzner commented
Not sure whether this is related but in older versions of cephadm, you could run the cephadm ceph-volume inventory command without a problem - now, you have to specify cephadm ceph-volume --fsid <wah> inventory even if your host only has one cluster defined.

@tchaikov ?

2021-01-27 00:49 UTC, tchaikov commented
@pcuzner what error do you have when running `cephadm ceph-volume inventory `?

2021-01-27 02:02 UTC, tchaikov commented
created #39095 to address the `infer_fsid()` issue.

2021-01-27 02:03 UTC, tchaikov commented
@sebastian-philipp ping?

2021-01-27 16:46 UTC, merged