nautilus: An empty bucket or OSD is not an error
ceph/ceph pull request #39126
Opened 2021-01-28 11:16 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/48987

---

backport of https://github.com/ceph/ceph/pull/38958
parent tracker: https://tracker.ceph.com/issues/48884

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-01-28 13:14 UTC, smithfarm commented
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/TestOSDMap.cc: In member function 'virtual void OSDMapTest_BUG_48884_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/TestOSDMap.cc:1554:65: error: too few arguments to function 'void print_osd_utilization(const OSDMap&, const PGMap&, std::ostream&, ceph::Formatter*, bool, const string&, const string&)'
   print_osd_utilization(osdmap, pgmap, ss, f.get(), true, "root");
                                                                 ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/TestOSDMap.cc:3:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSDMap.h:1523:6: note: declared here
 void print_osd_utilization(const OSDMap& osdmap,
      ^~~~~~~~~~~~~~~~~~~~~
src/test/osd/CMakeFiles/unittest_osdmap.dir/build.make:62: recipe for target 'src/test/osd/CMakeFiles/unittest_osdmap.dir/TestOSDMap.cc.o' failed
make[3]: *** [src/test/osd/CMakeFiles/unittest_osdmap.dir/TestOSDMap.cc.o] Error 1
```

2021-01-28 13:43 UTC, smithfarm commented
@badone The new `unittest_osdmap` test does not pass in nautilus. Can you take a look?

```
[ RUN      ] OSDMapTest.BUG_48884
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/TestOSDMap.cc:1564: Failure
      Expected: obj->get_data_val().str
      Which is: "0"
To be equal to: "3904"
[  FAILED  ] OSDMapTest.BUG_48884 (10 ms)
```

@badone (Feel free to close this PR and open a new one if you deem fixing this one too complicated.)

2021-01-28 21:15 UTC, badone commented
@smithfarm Sure, taking a look.

2021-01-29 02:36 UTC, badone requested changes

2021-01-29 02:36 UTC, badone commented on src/test/osd/TestOSDMap.cc
> +  print_osd_utilization(osdmap, pgmap, ss, f.get(), true, "root", "item");
So close.

```print_osd_utilization(osdmap, pgmap, ss, f.get(), true, "", "root");```

2021-02-03 12:59 UTC, smithfarm commented
@badone Please take a re-look?

2021-02-03 20:14 UTC, badone approved these changes
Perfect

2021-03-03 16:04 UTC, merged