ceph-volume: skip slot check in batch mode if size given
ceph/ceph pull request #39286
Opened 2021-02-04 04:27 UTC by jshen28

if requested size is given, slots check could be ignored.
this will allow reuse existing block db device when
a new osd is requested and block db has space

https://tracker.ceph.com/issues/49096

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-05 08:34 UTC, guits reviewed
LGTM, I've tested this patch, it works and doesn't break existing behavior (backward compatibility concern).
Unless I'm missing something, I think it's good to go. @jan--f any thoughts?

Maybe we are missing a test for this.

2021-02-05 08:44 UTC, jshen28 commented
thank you for the feedback, I will try to add some unit tests

2021-02-08 08:35 UTC, guits commented
jenkins test ceph-volume tox

2021-02-08 15:29 UTC, guits commented
jenkins test ceph-volume tox

2021-02-09 00:10 UTC, guits approved these changes

2021-02-09 18:07 UTC, jan--f requested changes
I see a scenario here where this will break:
Consider a user passes both `--slots` and `--size`. This is a legitimate use case when users want to underprovision a solid state device (by using `--size`) while reserving space for OSDs to be deployed later (via `--slots`). In this scenario the `--slots` argument is ignored.
The `batch` subcommand is really aimed at deploying multiple related OSDs (the drive groups concept is related here). To create individual OSDs the` create` subcommand should be used.

The log looks like this is a rook use case? Maybe we should take a look at what's happening at this level.

2021-02-10 00:27 UTC, jshen28 commented
thank you for replying.. actually it is not really a solely rook use case imo... 

1. I think force user to enumerate every osd is pretty cumbersome...
2. sorry but it's not quite clear to me what does underprovision ssd mean. because imo if both slots and sizes are given, slots will not be ignored at the prepare level.

2021-02-17 13:34 UTC, jan--f commented
> @jan--f thank you for replying.. actually it is not really a solely rook use case imo...
> 
>     1. I think force user to enumerate every osd is pretty cumbersome...
If a user doesn't want to deploy multiple osds, the `create` or `prepare`/`activate` subcommands should be used.
> 
>     2. sorry but it's not quite clear to me what does underprovision ssd mean.
Underprovisioning refers to setting up wal/db partitions in such a way, that they don't use the whole SSD. Say a 120 GB SSD is provisioned with 5 wal/db volumes of size 20GB each. I suppose one reason to do that is to have consisten OSD layouts? Not 100% sure but its out there.

> because imo if both slots and sizes are given, slots will not be ignored at the prepare level. [here](https://github.com/ceph/ceph/blob/3ccf7cb8ca6695b3542492b640a2f4a1b356eb26/src/ceph-volume/ceph_volume/api/lvm.py#L946) and [here](https://github.com/ceph/ceph/blob/3ccf7cb8ca6695b3542492b640a2f4a1b356eb26/src/ceph-volume/ceph_volume/devices/lvm/prepare.py#L176)
Correct, those code path don't have to check cause that is done in batch.py, which you try to disable.

Consider a host with five spinners and an SSD (that will be underprovisioned as described above). One of the spinners however is currently out of commission. The c-v command would look something like this: `ceph-volume lvm batch --db_slots 5 --db-size 20G --db-devices /dev/nvme0n1 /dev/sdb /dev/sdc /dev/sdd /dev/sde`
Once the 5th spinner is installed the user can deploy the final OSD by simply calling `ceph-volume lvm batch --db_slots 5 --db-size 20G --db-devices /dev/nvme0n1 /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf`

2021-02-18 00:21 UTC, jshen28 commented
> @jan--f thank you for replying.. actually it is not really a solely rook use case imo...
> 
> 1. I think force user to enumerate every osd is pretty cumbersome...
> 2. sorry but it's not quite clear to me what does underprovision ssd mean. because imo if both slots and sizes are given, slots will not be ignored at the prepare level. [here](https://github.com/ceph/ceph/blob/3ccf7cb8ca6695b3542492b640a2f4a1b356eb26/src/ceph-volume/ceph_volume/api/lvm.py#L946) and [here](https://github.com/ceph/ceph/blob/3ccf7cb8ca6695b3542492b640a2f4a1b356eb26/src/ceph-volume/ceph_volume/devices/lvm/prepare.py#L176)

2021-02-18 00:26 UTC, jshen28 commented
@jan--f thank you for reply.

>> 1. I think force user to enumerate every osd is pretty cumbersome...
> If a user doesn't want to deploy multiple osds, the create or prepare/activate subcommands should be used.

so are you saying that if an osd is broken, instead of `lvm batch`, user should switch to `lvm prepare/activate`?

> Consider a host with five spinners and an SSD (that will be underprovisioned as described above). One of the spinners however is currently out of commission. The c-v command would look something like this: `ceph-volume lvm batch --db_slots 5 --db-size 20G --db-devices /dev/nvme0n1 /dev/sdb /dev/sdc /dev/sdd /dev/sde`
Once the 5th spinner is installed the user can deploy the final OSD by simply calling `ceph-volume lvm batch --db_slots 5 --db-size 20G --db-devices /dev/nvme0n1 /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf`

right but if `db size` is given, then do `db-slots` option still be relevant here? because anyway new lv will be created by the given size and db-slot will be ignored in the end.

2021-03-20 12:19 UTC, jshen28 commented
@travisn do you think refactor rook to adapt to the new ceph-volume logic is valid? I saw 2 issues

1. previous ceph-volume does not require enumerating every disk into one huge command
2. it is hard to share the same metadata device for osds with different device class

2021-11-17 00:21 UTC, closed without merging