src/script: utility script to open all failed jobs at once on teuthology server
ceph/ceph pull request #39302
Opened 2021-02-04 15:34 UTC by ideepika

uses vim tabs + result.log from teuthology to open failed+dead jobs all
in vim tabs.
Been using it for rados batch analysis and it did help me simply workflow,
thought to share with other folks as well.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-04 19:18 UTC, yuriw commented
@ideepika cool !
How exactly do you use it ?

2021-02-04 19:18 UTC, yuriw approved these changes
:+1:

2021-02-05 05:40 UTC, tchaikov requested changes
i am inclined to not include this script in ceph repo. IMHO, not all ceph related scripts should be hosted here even if they are useful to some developers. i am in favor of including scripts which are part of our processes, like CI process, deploy process, build process, release process.

2021-02-05 07:38 UTC, ideepika commented
@tchaikov that seems logical, maybe we can someplace else to share them, as these are generally low hanging fruits, in terms of improving developer's productivity. 
Closing this one, in favour of your reasoning for now, thanks!

2021-02-05 07:38 UTC, closed without merging

2021-02-05 07:42 UTC, ideepika commented
> @ideepika cool !
> How exactly do you use it ?
1. copy this script somewhere on teuthology server
2. just run something like: example: python3 open_failed_logs.py yuriw-2021-01-06_21:20:32-rados-wip-yuri3-testing-2021-01-06-0820-octopus-distro-basic-smithi

o/p:
will list all jobs that will be opened on terminal o/p and open all failed+dead jobs in vim tabs