tools/kvstore-tool: implement 'dissect' command
ceph/ceph pull request #39394
Opened 2021-02-10 12:11 UTC by ifed01

This command shows information on key/value counts and lengths for KV  DB.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-11 13:13 UTC, aclamk requested changes
- [ ] update documentation

I think it could be improved by adding ability for histogram for single prefix.

2021-02-11 13:13 UTC, aclamk commented on src/tools/ceph_kvstore_tool.cc
> +    st.dissect();
I feel like "dissect" sounds unintuitive. 
How about "kv_hist[ogram]". But is is just a proposal.

2021-02-11 13:13 UTC, aclamk commented on src/tools/kvstore_tool.cc
> +  iter->seek_to_first();
Is it difficult to be able to provide size histogram stats for selected prefix?

2021-02-12 13:04 UTC, ifed01 commented
@aclamk - resolved your comments, please take a look

2021-02-12 14:48 UTC, aclamk approved these changes
Great stuff.

2021-02-21 16:51 UTC, merged