cephadm: Allow to use paths in all <_devices> drivegroup sections
ceph/ceph pull request #39415
Opened 2021-02-11 12:38 UTC by jmolmo

This will allow to use specific device paths for OSD non collocated

Fixes: https://tracker.ceph.com/issues/49191
Fixes: https://tracker.ceph.com/issues/46558

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

## Checklist
- [ x  ] References tracker ticket
- [ x ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-11 13:54 UTC, sebastian-philipp requested changes
lgtm, some pytest integration would be great here

2021-02-11 15:44 UTC, sebastian-philipp commented
conflicts with #39415 but I think your PR is better. I'll rebase

2021-02-11 16:17 UTC, jmolmo commented
> conflicts with #39415 but I think your PR is better. I'll rebase

It conflicts with itself?

2021-02-11 16:32 UTC, sebastian-philipp commented
> > conflicts with #39415 but I think your PR is better. I'll rebase
> 
> It conflicts with itself?

:see_no_evil:

#39410

2021-02-24 14:39 UTC, sebastian-philipp commented
https://pulpito.ceph.com/swagner-2021-02-22_13:54:50-rados:cephadm-wip-swagner4-testing-2021-02-22-1119-distro-basic-smithi/

2021-02-24 14:40 UTC, sebastian-philipp approved these changes

2021-02-24 14:40 UTC, merged