mgr/cephadm: SpecStore: use d-under accessor methods
ceph/ceph pull request #39458
Opened 2021-02-13 12:57 UTC by sebastian-philipp

This fixes a conflict between:

* 1fcdad17685a8884135a2cda0cdfe3525e325474
* 2c7f899124207d0d4866e16d9eb5609777ea22e8

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-13 13:12 UTC, tchaikov approved these changes

2021-02-14 02:46 UTC, adk3798 requested changes

2021-02-14 02:46 UTC, adk3798 commented on src/pybind/mgr/cephadm/services/monitoring.py
> +                    AlertManagerSpec, self.mgr.spec_store[service_name])
```suggestion
                    AlertManagerSpec, self.mgr.spec_store[service_name].spec)
```
I believe this returns a SpecDescription but we want the actual service spec (same for the other three)

2021-02-15 00:15 UTC, adk3798 approved these changes

2021-02-15 09:16 UTC, merged

2021-02-15 09:17 UTC, sebastian-philipp commented
let's merge it to unblock other PRs. @tchaikov please let me know if this doesn't pass teuthology