pacific: mgr/cephadm: based sleep interval on configured intervals/timeouts
ceph/ceph pull request #39483
Opened 2021-02-15 18:50 UTC by liewegas

Backport of #39381

Set a semi-arbitrary floor of 15 seconds.

Signed-off-by: Sage Weil <sage@newdream.net>
(cherry picked from commit e15c9a24dc7e98172eefdfe852cd75eaa1742895)

2021-02-16 09:24 UTC, jmolmo requested changes
I think that is better to create a new specific setting for set the frequency of cephadm orchestrator main loop. 
In my view the approach proposed is interesting but requires lot of effort from the final user that only wants to change a simple thing. Just to explain and document how to increase or decrease the cephadm main loop frequency and their implications is going to be complex.

2021-02-16 09:30 UTC, jmolmo approved these changes
Sorry. In the first moment I didn't realize that this is a backport and i miss the first revision of this change. In any case ... I continue thinking that it would be nice to have a specific setting for this.

2021-02-16 18:22 UTC, liewegas commented
> I think that is better to create a new specific setting for set the frequency of cephadm orchestrator main loop.
> In my view the approach proposed is interesting but requires lot of effort from the final user that only wants to change a simple thing. Just to explain and document how to increase or decrease the cephadm main loop frequency and their implications is going to be complex.

I think the problem with making this a separate option is that if you just want to refresh the device state more often then you *also* have to know to change some other option or else it won't have any effect.  That's just confusing.  Also, if you change the sleep interval without changing the other options for cache timeout etc, then there will be no visible effect.

It seems natural for cephadm to figure out how long it should sleep before there is something important for it to do...

2021-02-22 16:38 UTC, yuriw commented
![](https://github.trello.services/images/mini-trello-icon.png) [wip-yuri7-testing-2021-02-22-0837-pacific](https://trello.com/c/ps8f45yv/1151-wip-yuri7-testing-2021-02-22-0837-pacific)

2021-02-28 16:07 UTC, merged