qa: test nowsync option in kernel client workflows
ceph/ceph pull request #39505
Opened 2021-02-17 02:41 UTC by batrick

This might be incomplete if mounts fail because `nowsync` is unrecognized.

2021-02-17 10:39 UTC, idryomov requested changes
Need to supply "wsync" explicitly in yes.yaml instead of keeping it empty.  Otherwise, once the kernel default changes, we would lose "wsync" coverage.

2021-02-17 14:53 UTC, batrick commented
> Need to supply "wsync" explicitly in yes.yaml instead of keeping it empty. Otherwise, once the kernel default changes, we would lose "wsync" coverage.

Thanks, done.

2021-02-17 14:56 UTC, jtlayton approved these changes
LGTM

2021-02-17 16:47 UTC, idryomov approved these changes
> This might be incomplete if mounts fail because `nowsync` is unrecognized.

It should be fine -- "distro" kernel is used only in combination with RHEL 8.3 which does support async dirops.  Everything else seems to use our "testing" kernel.

2021-02-25 03:13 UTC, batrick commented
Looks like we sniffed out a bug:

https://pulpito.ceph.com/pdonnell-2021-02-24_05:54:31-fs-wip-pdonnell-testing-20210224.040859-distro-basic-gibba/

failures are like: https://pulpito.ceph.com/pdonnell-2021-02-24_05:54:31-fs-wip-pdonnell-testing-20210224.040859-distro-basic-gibba/5911447/

All failures are apparently with the stock RHEL 8 kernel with `-o nowsync`.

cc @jtlayton

2021-02-25 03:16 UTC, batrick commented
Kernel log contains junk:

````
2021-02-24T11:47:16.452213+00:00 gibba036 kernel: XFS (dm-2): Ending clean mount
2021-02-24T11:47:16.721212+00:00 gibba036 kernel: XFS (dm-3): Mounting V5 Filesystem
2021-02-24T11:47:16.727212+00:00 gibba036 kernel: XFS (dm-3): Ending clean mount
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@2021-02-24T11:50:58.906166+00:00 gibba036 kernel: Linux version 4.18.0-240.1.1.el8_3.x86_64 (mockbuild@x86-vm-09.build.eng.bos.redhat.com) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Fri Oct 16 13:36:46 EDT 2020
2021-02-24T11:50:58.906177+00:00 gibba036 kernel: Command line: BOOT_IMAGE=(hd0,msdos1)/boot/vmlinuz-4.18.0-240.1.1.el8_3.x86_64 root=UUID=3b6f09d8-1f6d-44b1-8eae-585ac69873c0 ro crashkernel=auto console=ttyS1,115200
````

From: /ceph/teuthology-archive/pdonnell-2021-02-24_05:54:31-fs-wip-pdonnell-testing-20210224.040859-distro-basic-gibba/5911447/remote/gibba036/syslog/kern.log.gz

2021-02-25 06:23 UTC, idryomov commented
Argh, the upstream code had to be adopted for the old mount API and it looks like a break went missing in the `nowsync` case so it falls through to a BUG_ON: https://github.com/kernelim/linux/blob/1bad977f89dabc625c1e3beaae54f54d3add5bf4/fs/ceph/super.c#L408-L414

2021-02-26 17:30 UTC, batrick commented
Leaving this in draft state until the RHEL stock kernel is fixed. @idryomov any idea how long until the fix will be available for the rhel distro kernel used in sepia?

2021-02-26 17:33 UTC, idryomov commented
Not really.  I would guess at least a month, probably more...

2021-03-16 17:56 UTC, batrick commented
Waiting on: https://bugzilla.redhat.com/show_bug.cgi?id=1932753

2021-05-24 19:41 UTC, jtlayton commented
> Waiting on: https://bugzilla.redhat.com/show_bug.cgi?id=1932753

This is fixed now in RHEL 8.4 kernels, but I'm still having trouble getting it cloned for 8.3.z. Hopefully we'll get that sorted soon though.

2021-06-02 13:36 UTC, jtlayton commented
> > Waiting on: https://bugzilla.redhat.com/show_bug.cgi?id=1932753
> 
> This is fixed now in RHEL 8.4 kernels, but I'm still having trouble getting it cloned for 8.3.z. Hopefully we'll get that sorted soon though.

Evidently there are no more zstream updates planned for RHEL 8.3, so fixing this in 8.4 is as far as it will go. Should we plan to go ahead and merge this now that 8.4 is released?

2021-06-02 14:34 UTC, idryomov commented
I think `qa/cephfs/mount/kclient/overrides/distro/stock/rhel_8.yaml` needs to be updated for 8.4.

2021-06-03 19:43 UTC, batrick commented
Will test this with #41683

2021-06-12 00:06 UTC, batrick commented
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-11

stock kernel looks good now!

2021-06-12 00:10 UTC, merged