pacific: cephadm backport February (2)
ceph/ceph pull request #39559
Opened 2021-02-18 18:43 UTC by jmolmo

Backport of #38549, #38883, #39058, #39355, #38505, #39364, #39381, #39384, #39385, #39398, #39384, #39404, #39430, #38881, #39458, #39473, #39482, #39424, #39490, #39323, #39467, #39464, #39496

conflicts: 
#38549 (src/pybind/mgr/cephadm/serve.py, src/pybind/mgr/cephadm/services/nfs.py, src/pybind/mgr/cephadm/tests/test_services.py)
#38883 (src/pybind/mgr/cephadm/inventory.py, src/pybind/mgr/cephadm/module.py, src/pybind/mgr/cephadm/tests/test_cephadm.py
#39058 (src/pybind/mgr/cephadm/tests/test_upgrade.py)
#38505 (doc/dev/cephadm/index.rst)
#38881 (src/cephadm/cephadm)

2021-02-19 12:25 UTC, sebastian-philipp requested changes

2021-02-19 12:25 UTC, sebastian-philipp commented on src/cephadm/cephadm
> +DEFAULT_IMAGE = 'docker.io/ceph/daemon-base:latest-master-devel'
DEFAULT_IMAGE = 'docker.io/ceph/daemon-base:latest-pacific-devel'

2021-02-19 15:28 UTC, jmolmo commented on src/cephadm/cephadm
> +DEFAULT_IMAGE = 'docker.io/ceph/daemon-base:latest-master-devel'
fixed

2021-02-22 13:54 UTC, sebastian-philipp commented
I still don't get why you have so many conflicts

2021-02-23 03:31 UTC, ktdreyer approved these changes
I've tested this on RHEL 8.

2021-02-23 09:45 UTC, sebastian-philipp commented
too many conflicts. replaced by #39623

2021-02-23 10:14 UTC, closed without merging