mgr/volumes: Bump up AuthMetadataManager's version
ceph/ceph pull request #39572
Opened 2021-02-19 11:33 UTC by kotreshhr

With ceph_volume_client and mgr-volumes co-existing
for sometime, the version of both needs to be same.
The ceph_volume_client version <=5 can't decode
'subvolumes' key in auth-metadata file. Hence to
handle version in-compatibility, the version of
ceph_volume_client is bumped up to 6 and the same
needs to be done in mgr-volume's AuthMetadataManager.

Fixes: https://tracker.ceph.com/issues/49374
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-19 20:12 UTC, ajarr approved these changes

2021-02-19 20:12 UTC, ajarr commented on src/pybind/mgr/volumes/fs/operations/versions/auth_metadata.py
> +        data['compat_version'] = 6
instead do this in  auth_metadata_set()?

2021-02-19 20:13 UTC, ajarr requested changes

2021-02-19 20:13 UTC, ajarr commented on src/pybind/mgr/volumes/fs/operations/versions/auth_metadata.py
> +        data['compat_version'] = 6
instead do this in auth_metadata_set()?

2021-02-20 08:47 UTC, kotreshhr commented on src/pybind/mgr/volumes/fs/operations/versions/auth_metadata.py
> +        data['compat_version'] = 6
Oh yes, right!

2021-02-20 08:49 UTC, kotreshhr commented on src/pybind/mgr/volumes/fs/operations/versions/auth_metadata.py
> +        data['compat_version'] = 6
Done

2021-02-20 15:31 UTC, ajarr approved these changes

2021-02-23 04:08 UTC, kotreshhr commented
Teuthology Results:

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-22_06:49:11-fs:volumes-wip-khiremat-39572-3-distro-basic-smithi/

2021-02-23 04:16 UTC, merged