doc/radosgw/cloud-sync-module: fix typos
ceph/ceph pull request #39605
Opened 2021-02-22 09:51 UTC by inspur-wyq

Signed-off-by: wangyunqing wangyunqing@inspur.com

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-22 14:36 UTC, zdover23 requested changes

2021-02-22 14:36 UTC, zdover23 commented on doc/radosgw/cloud-sync-module.rst
> +Represents a connection to the remote cloud service. Contains ``connection_id`, ``access_key``,
Shouldn't this be ``connection_id`` ? (I mean: shouldn't this have two backticks after "connection_id"?)

2021-03-05 05:18 UTC, tchaikov approved these changes

2021-03-05 05:19 UTC, tchaikov commented
@zdover23 could you please take another look? it seems that @inspur-wyq has addressed your comment.

2021-04-25 12:15 UTC, merged