pybind/cephfs: DT_REG and DT_LNK values are wrong
ceph/ceph pull request #39664
Opened 2021-02-24 11:35 UTC by varshar16

DT_REG and DT_LNK don't match with values defined in
/usr/include/dirent.h

define DT_REG		8
define DT_LNK		10

This patch corrects them.

Signed-off-by: Varsha Rao <varao@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-24 11:53 UTC, jtlayton approved these changes

2021-02-24 14:51 UTC, batrick requested changes
Needs a tracker ticket for backport.

2021-02-24 16:22 UTC, varshar16 commented
> Needs a tracker ticket for backport.

I have added it.

2021-02-24 16:42 UTC, batrick approved these changes

2021-02-26 17:27 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2021-02-26_05:55:31-fs-wip-pdonnell-testing-20210226.035303-distro-basic-smithi/

2021-02-26 17:32 UTC, merged