doc: snap-schedule documentation
ceph/ceph pull request #39671
Opened 2021-02-24 15:15 UTC by jan--f

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-02-24 15:19 UTC, jan--f commented
jenkins render docs

2021-02-24 17:21 UTC, batrick commented
> jenkins render docs

FYI, this is no longer necessary. You can see the rendered docs by clicking the "Details" link for the `docs/readthedocs.org:ceph` jenkins check.

the build is currently failing too, please take a look @jan--f

2021-02-24 17:23 UTC, batrick requested changes

2021-02-24 17:23 UTC, batrick commented on doc/mgr/snap_schedule.rst
> +.. _mgr-snap_schedule:
Let's put this in the `doc/cephfs` tree. Then link to itt from the TOC.

2021-03-06 17:05 UTC, batrick commented
@jan--f ping

2021-03-08 21:27 UTC, batrick requested changes
otherwise LGTM, thanks!

2021-03-08 21:27 UTC, batrick commented on doc/cephfs/snap-schedule.rst
> +The start time is specified as a time string (see DOC BELOW LINK). By default
`DOC BELOW LINK` todo item?

2021-03-10 17:25 UTC, jan--f commented on doc/cephfs/snap-schedule.rst
> +The start time is specified as a time string (see DOC BELOW LINK). By default
oh yes good catch, thx and fixed.

2021-03-11 17:22 UTC, batrick approved these changes

2021-03-11 17:23 UTC, merged