doc: add tow Bucket Lifecycle RGW Settings
ceph/ceph pull request #39751
Opened 2021-03-01 02:28 UTC by Huber-ming

Add tow Bucket Lifecycle RGW Settings.

Signed-off-by: Huber-ming <zhangsm01@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-01 14:17 UTC, mattbenjamin reviewed
thanks for adding these;  I think maybe I would put these near or at the top of the Lifecycle Settings section, because they are very basic;  I don't think "Additional Lifecycle Settings" is adding very much, there's nothing really "additional" about these specifically.  That said, there is a tricky aspect to rgw_lc_max_objs--which is that we don't have dynamic resharding for the queues, and it can be unsafe to change the sharding when there are already lifecycle rules present.  There's no current workaround for that, really.

2021-03-15 09:07 UTC, Huber-ming commented
jenkins test signed

2021-03-15 09:20 UTC, Huber-ming commented
@mattbenjamin  hi, the commit has `Signed-off-by`, why `Signed-off-by` check fails?

2021-06-11 02:55 UTC, tchaikov commented
jenkins test signed

2021-06-11 04:21 UTC, tchaikov commented
@Huber-ming i think the reason why the check failed was that the title of your commit message reads

> add tow Bucket Lifecycle RGW Settings 

but all changes which only involves files under `doc/` directory should have a commit message whose title starts with "doc".

in this case, the title of the PR fulfills the requirement. but the title of the commit does not. you might need to revise your commit message accordingly.

2022-07-06 01:34 UTC, anthonyeleven requested changes
Requested some minor changes.  Also, the PR and commit titles should be something like

"doc/radosgw: Add two bucket lifecycle settings"

2022-07-06 01:34 UTC, anthonyeleven commented on doc/radosgw/config-ref.rst
> +the Ceph configuration file under the ``[client.radosgw.{instance-name}]`` section.
s/file//

2022-07-06 01:34 UTC, anthonyeleven commented on doc/radosgw/config-ref.rst
> +:Description: Enables the lifecycle maintenance thread. This is required on at least one rgw for each zone.
s/rgw/RGW/

2022-11-27 23:01 UTC, closed without merging