qa/ceph_manager: accepts commands as str too
ceph/ceph pull request #39775
Opened 2021-03-02 04:41 UTC by rishabh-d-dave

Modify `CephManager.run_cluster_cmd()` to accept command arguments as
string as well since typing commands as strings is much lesser effort
than typing as list. This brings the interface a step closter to
`teuthology.orchestra.remote.run()`'s interface since it too can accept
commands arguments as string.

The change in `cephfs_test_case.py` is just to allow testing this PR
locally and on teuthology.

Signed-off-by: Rishabh Dave <ridave@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-02 10:55 UTC, lxbsz commented
> Modify `CephManager.run_cluster_cmd()` to accept command arguments as
> string as well since typing commands as strings is much lesser effort
> than typing as list. This brings the interface a step closter to
s/closter/closer ?

2021-03-02 10:56 UTC, lxbsz approved these changes
LGTM.

2021-03-02 11:25 UTC, rishabh-d-dave commented
> > Modify `CephManager.run_cluster_cmd()` to accept command arguments as
> > string as well since typing commands as strings is much lesser effort
> > than typing as list. This brings the interface a step closter to
> 
> s/closter/closer ?

Corrected the mistake in commit message.

2021-03-02 19:27 UTC, batrick requested changes

2021-03-02 19:27 UTC, batrick commented on qa/tasks/ceph_manager.py
> +            kwargs = shlex.split(kwargs['args'])
```suggestion
            kwargs['args'] = shlex.split(kwargs['args'])
```

?

2021-03-03 14:45 UTC, batrick approved these changes

2021-03-03 14:46 UTC, batrick commented
@tchaikov @neha-ojha please add this to your integration branch.

2021-03-03 19:40 UTC, neha-ojha commented
needs a rebase

2021-03-04 05:22 UTC, rishabh-d-dave commented
@neha-ojha Rebased my PR.

2021-03-05 19:31 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2021-03-05_06:25:39-fs-wip-pdonnell-testing-20210305.032405-distro-basic-smithi/

Failures are:
- https://tracker.ceph.com/issues/48203 (stock kernel update required)
- https://tracker.ceph.com/issues/49240
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/47723 (stock kernel update required?)
- https://tracker.ceph.com/issues/49605

2021-03-05 19:32 UTC, batrick commented
Passes CephFS qa.

2021-03-07 15:52 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-03-06_09:19:54-rados-wip-kefu-testing-2021-03-06-1553-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-07_12:30:50-rados-wip-kefu-testing-2021-03-07-1842-distro-basic-smithi/


failures tracked by

- https://tracker.ceph.com/issues/49638
- https://tracker.ceph.com/issues/49484

2021-03-07 15:52 UTC, merged