doc: update affiliation for myoungwon
ceph/ceph pull request #39799
Opened 2021-03-03 06:07 UTC by myoungwon

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsumg.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-03 06:16 UTC, myoungwon commented
I moved to Samsung Electronics one and a half years ago, but my affiliation hasn't been changed correctly here. 
Can I update this?
(Samsung become premier member of Ceph foundation, and supports contribution)

2021-03-03 06:51 UTC, tchaikov approved these changes

2021-03-03 13:18 UTC, zdover23 commented
jenkins test make check arm64

2021-03-03 19:33 UTC, batrick requested changes
Your signed-off-by is also has the typo (.gitconfig misconfiguration?)

2021-03-03 19:33 UTC, batrick commented on doc/governance.rst
> + * Myoungwon Oh <myoungwon.oh@samsumg.com>
```suggestion
 * Myoungwon Oh <myoungwon.oh@samsung.com>
```

?

2021-03-04 00:36 UTC, myoungwon commented
@batrick Thanks. Done.

2021-03-04 00:49 UTC, neha-ojha approved these changes

2021-03-04 04:04 UTC, batrick approved these changes

2021-03-04 04:06 UTC, merged