octopus: `cephadm ls` broken for SUSE downstream alertmanager container
ceph/ceph pull request #39802
Opened 2021-03-03 09:33 UTC by p-se

Binary in downstream container is named `prometheus-alertmanager` instead of `alertmanager`.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-03 12:43 UTC, sebastian-philipp approved these changes

2021-03-03 12:44 UTC, sebastian-philipp requested changes
when doing the cherry-pick and you encounter conflicts, please remove the `#` characters from the commit message that highlight conflicts. 

See https://github.com/ceph/ceph/pull/39804/commits/514fc603d019f304f20b666e523dcce83689f0ca for an example

2021-03-09 17:20 UTC, smithfarm commented
@p-se This appears to be a cherry-pick of https://github.com/ceph/ceph/pull/39722 - correct?

Did you combine all three commits from https://github.com/ceph/ceph/pull/39722 into a single commit?

Commits from master should be cherry-picked individually. If you only need to cherry-pick one commit from master, then could you please explain in the PR description why the other two commits were omitted?

2021-03-10 08:11 UTC, p-se commented
> @p-se This appears to be a cherry-pick of #39722 - correct?
> 
> Did you combine all three commits from #39722 into a single commit?
> 
> Commits from master should be cherry-picked individually. If you only need to cherry-pick one commit from master, then could you please explain in the PR description why the other two commits were omitted?

@smithfarm I combined two commits from master into one that should've been one commit in the first place, but I failed to squash them in the PR to master. Which commits that are is in the commit message.

2021-03-10 09:41 UTC, smithfarm commented
@p-se What about the third commit from the master PR? I'm assuming that was omitted here for a reason, but I don't see that noted anywhere?

2021-03-10 12:52 UTC, sebastian-philipp approved these changes

2021-03-11 08:25 UTC, p-se commented
> @p-se What about the third commit from the master PR? I'm assuming that was omitted here for a reason, but I don't see that noted anywhere?

@smithfarm The third commit does not resolve the issue that is supposed to be fixed. It does, strictly speaking not belong to the PR (neither master nor this one). Hence, I didn't think it would be necessary to explain why it wasn't cherry picked. 

Do you think it should be either part of this backport or be mentioned in the commit message, why it wasn't cherry picked?

2021-03-11 17:41 UTC, smithfarm commented
> Do you think it should be either part of this backport or be mentioned in the commit message, why it wasn't cherry picked?

@p-se It's enough to mention that somewhere in this PR, which you just did ;-) Part of reviewing a backport is verifying that all commits from the master PR were cherry-picked. So it helps reviewers if you provide an explanation of any differences up front.

2021-04-14 04:56 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-04-12_02:35:25-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-12_13:55:39-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-smithi/

i think most of cephadm test failures are caused by https://tracker.ceph.com/issues/49293

2021-04-25 02:56 UTC, tchaikov commented
jenkins test api

2021-04-27 06:12 UTC, merged