mds: fix race of fetching large dirfrag
ceph/ceph pull request #39848
Opened 2021-03-05 06:39 UTC by chenerqi

When a dirfrag contains more than 'mds_dir_keys_per_op' items, MDS needs to send multiple 'omap-get-vals' requests to fetch the dirfrag completely. There is a race if MDS commits the dirfrag in the middle of these 'omap-get-vals' requests.

Re-fetch from the beginning if dirfrag get committed in the middle of omap-get-vals requests.

Fixes: https://tracker.ceph.com/issues/49617
Signed-off-by: Erqi Chen <chenerqi@kuaishou.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-05 07:10 UTC, tchaikov commented on src/mds/CDir.cc
> +      dir->_omap_fetch(nullptr, fin);
```suggestion
      omap.clear();
      dir->_omap_fetch(fin, {});
```

2021-03-06 16:46 UTC, batrick requested changes
Otherwise LGTM. Thanks for your contribution.

2021-03-06 16:46 UTC, batrick commented on src/mds/CDir.cc
> +#endif
This is a performance change. Please pull it out into another PR.

2021-03-10 14:14 UTC, sidharthanup approved these changes

2021-03-11 17:10 UTC, batrick approved these changes

2021-03-17 03:20 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2021-03-15_22:16:56-fs-wip-pdonnell-testing-20210315.182203-distro-basic-smithi/

- https://tracker.ceph.com/issues/49842
- https://tracker.ceph.com/issues/49466
- https://tracker.ceph.com/issues/49822
- https://tracker.ceph.com/issues/49240
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/49500
- https://tracker.ceph.com/issues/49843
- https://tracker.ceph.com/issues/49845
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/49605

and failure caused by PR: https://github.com/ceph/ceph/pull/39969

2021-03-17 03:23 UTC, merged