mgr/cephadm: remove duplicate labels when adding a host
ceph/ceph pull request #39857
Opened 2021-03-05 15:15 UTC by adk3798

Fixes: https://tracker.ceph.com/issues/49626

Signed-off-by: Adam King <adking@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-05 16:11 UTC, mgfritch approved these changes
works! but somewhat wonder if the `HostSpec` class should be doing the handling

2021-03-08 10:01 UTC, jmolmo approved these changes
I like a lot the way to avoid the duplicate label!!!

2021-03-08 10:29 UTC, sebastian-philipp requested changes

2021-03-08 10:29 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/inventory.py
>          self._inventory[spec.hostname] = spec.to_json()
How do we deal with clusters that are already affected by this? Maybe we should change `HostSpec.{from,to}_json()´ instead?
.

2021-03-09 18:18 UTC, adk3798 commented
changed this to remove duplicates in HostSpec from/to json functions rather than in the add host command.

2021-03-11 11:20 UTC, sebastian-philipp approved these changes
much better.

2021-03-12 11:02 UTC, sebastian-philipp commented
https://pulpito.ceph.com/swagner-2021-03-11_16:09:20-rados:cephadm-wip-swagner-testing-2021-03-11-1320-distro-basic-smithi/

Lots of errors:

* https://tracker.ceph.com/issues/49633
* https://tracker.ceph.com/issues/49740
* upgrade suite is totally broken
* `tasks.cephadm_cases.test_cli.TestCephadmCLI.test_cephfs_mirror` broke yesterday or the day before.

2021-03-12 11:04 UTC, merged