mgr/cephadm: simplify handling for rgw
ceph/ceph pull request #39877
Opened 2021-03-05 21:01 UTC by liewegas

- radosgw-admin fiddling with zone/realm config is out of scope
- remove naming constraints
- keep the --rgw-zone= and --rgw-realm= arguments, but make them optional.  if omitted, we'll get the simple non-multisite rgw behavior with autocreated pools etc.
- update rook to match

Existing octopus deployments will continue to work: they follow the old naming convention, and we're just allowing new specs to deviate from that convention.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-07 13:11 UTC, ofriedma requested changes
I think that we should add rgw-zonegroup parameter too so we will be able to create and use non-default zonegroup name, otherwise LGTM

2021-03-07 14:59 UTC, liewegas commented
> I think that we should add rgw-zonegroup parameter too so we will be able to create and use non-default zonegroup name, otherwise LGTM

Since cephadm isn't creating the zone, zonegroup, or realm any more, I don't think adding the argument will serve any purpose.  IIUC, there isn't any rgw_zonegroup parameter needed during startup... setting the rgw_realm and rgw_zone options for the newly created service is the only reason we are providing those parameters at this point.

2021-03-07 15:00 UTC, liewegas commented
jenkins run make test

2021-03-08 14:04 UTC, sebastian-philipp requested changes

2021-03-08 14:04 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/tests/test_spec.py
>              hostname=None,
keep this test?

2021-03-08 14:04 UTC, sebastian-philipp commented on src/pybind/mgr/cephadm/tests/test_spec.py
>          ),
keep this test?

2021-03-08 14:14 UTC, liewegas commented on src/python-common/ceph/deployment/service_spec.py
> -                service_id = '%s.%s' % (rgw_realm, rgw_zone)
What users would this affect, though?  IIUC this code only runs at apply time, so it's already happened for the existing users.  And the CLI change is already a breaking change (it has to be to remove realm/zone creation).

2021-03-08 14:27 UTC, liewegas commented on src/pybind/mgr/cephadm/tests/test_cephadm.py
> -            (RGWSpec(rgw_realm='realm', rgw_zone='zone'), CephadmOrchestrator.apply_rgw),
that throws an exception from validate() since there is no service_id....

2021-03-08 14:37 UTC, sebastian-philipp commented on src/python-common/ceph/deployment/service_spec.py
> -                service_id = '%s.%s' % (rgw_realm, rgw_zone)
> (it has to be to remove realm/zone creation)

I think that's a behavior change and as we provide a simpler setup for simpler use cases, I think this is reasonable. 

I'm just not sure we need to break the CLI that much. Like e.g. https://documentation.suse.com/ses/7/single-html/ses-deployment/index.html#deploy-cephadm-day2-service-ogw  or so

2021-03-08 19:49 UTC, liewegas commented on src/python-common/ceph/deployment/service_spec.py
> -                service_id = '%s.%s' % (rgw_realm, rgw_zone)
AFAICS i don't think we need this for the example you link to because it defines ``service_id``...

2021-03-09 10:14 UTC, jmolmo commented on src/python-common/ceph/deployment/service_spec.py
> -        if not self.rgw_realm:
I think this check now is the opposite..... 
If the user sets a realm and a zone ... It is worth to check if the realm and the zone exists ? 
What if the user only specifies the realm or the zone .... should we use "default" for the missing piece?

2021-03-09 10:44 UTC, jmolmo approved these changes
I think you want to keep the orchestrator as a thin management layer, and this change really goes in that direction.
My only concern is that with this approach cephadm does not fully replace other installation tools.

Keep simple the orchestrator layer will help to provide a consistent interface (baremetal, k8s) and my view is that this is positive .. but in my opinion we must work in parallel in providing tools that make the final user life more easy, and over all, if we change the installation method we must avoid to lose functionality if we compare with previous installation tools. 

With this change I understand that the Ceph dashboard is going to be the only tool provided to install and manage a Ceph cluster. Is that true?

2021-03-09 12:18 UTC, epuertat commented
@liewegas I lack the context for this change, as I don't find any tracker/reference linked.

Please correct me if I'm wrong, but as a side effect of this, from now on when ceph-dashboard implements RGW zones/etc. management, we'll have to figure out another mechanism/tool providing orchestrator-like CLI access (since `radosgw-admin` is not available as MonCommand), and then additionally call the orchestrator for deploying/restarting/removing the impacted RGW daemons accordingly. Why not keeping zone/zg/realm config changes tightly coupled with their associated service lifecycles, rather than spreading their management across different tools and interfaces?

I don't know about DeepSea, but compared to Ceph-ansible this is opening a feature gap, as [it supported multi-site deployment](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-rgw/tasks/multisite/main.yml).

2021-03-09 13:51 UTC, liewegas commented
> @liewegas I lack the context for this change, as I don't find any tracker/reference linked.
> 
> Please correct me if I'm wrong, but as a side effect of this, from now on when ceph-dashboard implements RGW zones/etc. management (which is a goal for Quincy), we'll have to figure out another mechanism/tool providing orchestrator-like CLI access (since `radosgw-admin` is not available as MonCommand), and then additionally call the orchestrator for deploying/restarting/removing the impacted RGW daemons accordingly. Why not keeping zone/zg/realm config changes tightly coupled with their associated service lifecycles, rather than spreading their management across different tools and interfaces?
> 
> I don't know about DeepSea, but compared to Ceph-ansible this is opening a feature gap, as [it supported multi-site deployment](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-rgw/tasks/multisite/main.yml).

I would put it this way: responsibility for fiddling with the zone/realm configuration doesn't belong in cephadm, because realm configuration is very complex and cephadm lacks the knowledge of the users' intentions to do it well.  The ceph-ansible support for setting up multisite assumes a particular vanilla kind of deployment, but we need to be able to deploy daemons for more complex multisite configurations.

Alternatives:
- put a series of more friendly commands in mgr/orchestrator, where it could be leveraged by both rook and cephadm, or
- create a new 'ceph rgw ...' CLI subnamespace (which tbh is where i wish we could move all of radosgw-admin).  This would be more analogous to mgr/volumes, which creates a 'ceph fs volume create' command that (as a last step) tells the orchestrator API to start up the MDS daemons.

To get a simplified experience, I think we should start with what the CLI/GUI UX should look like, and then work backwards from there.  

The main part I'm worried about is if/how we should allow you to define a multisite realm configuration in an orchestrator .spec file... is that something we should support?  If so, then we'll probably have some bit in cephadm that takes the blob describing the multisite config an calls out to generic orchestrator code to go make it so before deploying the services...

2021-03-09 13:56 UTC, sebastian-philipp commented
> The main part I'm worried about is if/how we should allow you to define a multisite realm configuration in an orchestrator .spec file... is that something we should support? If so, then we'll probably have some bit in cephadm that takes the blob describing the multisite config an calls out to generic orchestrator code to go make it so before deploying the services...

If we want to have some form of cluster specification to be able to repeatedly create the cluster, we would need to support this somehow. I think this is supported by ansible, right?

2021-03-09 14:34 UTC, liewegas commented
> > The main part I'm worried about is if/how we should allow you to define a multisite realm configuration in an orchestrator .spec file... is that something we should support? If so, then we'll probably have some bit in cephadm that takes the blob describing the multisite config an calls out to generic orchestrator code to go make it so before deploying the services...
> 
> If we want to have some form of cluster specification to be able to repeatedly create the cluster, we would need to support this somehow. I think this is supported by ansible, right?

Yeah.  So, maybe there is a module (in mgr/orchestrator somewhere) that knows how to parse a section describing the realm configuration and apply it?  Or maybe rgw already has such a way to fully specify the config in one go.

2021-03-09 14:36 UTC, liewegas commented
Or, maybe services can have "pre-exec" steps, which are just CLI commands to exec in a shell before the service is created, somewhat analogous to the new config section.  Kind of a kludge, but sufficient.

2021-03-09 14:45 UTC, sebastian-philipp commented
> Yeah. So, maybe there is a module (in mgr/orchestrator somewhere) that knows how to parse a section describing the realm configuration and apply it? Or maybe rgw already has such a way to fully specify the config in one go.

This is getting big pretty quickly. https://github.com/rook/rook/blob/master/design/ceph/object/ceph-multisite-overview.md#ceph-multisite-data-model

```yaml
realms:
  myrealm1: 
    zone_groups:
    - group1
    - group2
    master_zone_group: group1
    pull_from: ...
zone_groups:
  group1: 
    zones:
    - zone1  
    - zone2
    master_zone: zone1
zones:
  zone1:
    pools: ...
```

this looks pretty unrealistic to build just for cephadm.

2021-03-09 23:20 UTC, sebastian-philipp commented
@ofriedma want to review this?

2021-03-10 11:37 UTC, ofriedma approved these changes

2021-03-10 12:58 UTC, merged

2021-03-10 13:00 UTC, sebastian-philipp commented
Follow-ups:

* Would be great to have https://docs.ceph.com/en/octopus/cephadm/install/#deploy-rgws updated to recommend using --rgw-realm and --rgw-zone explicitly 
* We're missing RGW in the cephad/upgrade suite