ceph-volume: `get_first_lv()` refactor
ceph/ceph pull request #39907
Opened 2021-03-08 09:10 UTC by guits

As indicated by commit 17957d9beb42a04b8f180ccb7ba07d43179a41d3 this
fuction was meant to avoid writing something like following:

```
lvs = get_lvs()
if len(lvs) >= 1:
	lvs = lv[0]
```

This function should raise a `RuntimeError` exception if 0 or more than
1 LV is returned.
The current name of the function is confusing and can lead to thinking that
we just want the first LV returned, even though it returns more than 1
LV, let's rename it to `get_single_lv()`

Closes: https://tracker.ceph.com/issues/49643

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-03-08 09:36 UTC, guits commented
jenkins test ceph-volume tox

2021-03-08 12:05 UTC, rishabh-d-dave requested changes
Two things -

* `get_single_lv()` must return `None` when no LV matches the filter. This is so because in many places in c-v codebase we expect `get_single_lv()/get_first_lv()` to return an empty list. So, raising an exception is inappropriate. Passing `None` would be a perfect. Apologies since I failed to consider this when I suggested these changes to `get_first_lv()`.

* It would be nice to make same changes to `get_first_pv()` and `get_first_vg()`.

2021-03-08 12:05 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/tests/api/test_lvm.py
>          assert api.get_lvs() == []
These tests don't make any sense anymore. Let's get rid of them.

2021-03-08 12:05 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/tests/api/test_lvm.py
> +    def test_get_single_lv_raises_none_error(self, m_get_lvs):
This would require a change if you go by my recommendation.

2021-03-08 12:12 UTC, rishabh-d-dave commented
Following two change requests would also fix unit test failures -
https://github.com/ceph/ceph/pull/39907#discussion_r589370840
https://github.com/ceph/ceph/pull/39907#pullrequestreview-606219362

2021-03-08 12:17 UTC, rishabh-d-dave requested changes

2021-03-08 12:17 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/tests/api/test_lvm.py
> +        fake_lvs.append(api.Volume(lv_name='lv1', lv_path='/dev/vg2/lv1', vg_name='vg2', lv_tags='', lv_uuid='fake-uuid'))
nit: IMO, it would be nice to wrap these at 80.

2021-03-08 12:17 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/api/lvm.py
> +        raise RuntimeError('Filters {} matched more than 1 LV present on this host.'.format(filters))
`filters` are `dict`, they need to be converted to `str` first. Also, wrapping this at 80 would be nice.
```suggestion
    if len(lvs) == 0:
        raise RuntimeError('Filters {} did not match any lv present on this host.'.format(str(filters)))
    if len(lvs) > 1:
        raise RuntimeError('Filters {} matched more than 1 LV present on this host.'.format(str(filters)))
```

2021-03-08 12:18 UTC, rishabh-d-dave commented
Following three change requests would also fix unit test failures -
https://github.com/ceph/ceph/pull/39907#discussion_r589370840
https://github.com/ceph/ceph/pull/39907#pullrequestreview-606219362
https://github.com/ceph/ceph/pull/39907#discussion_r589379124

2021-03-08 12:38 UTC, rishabh-d-dave commented
make check failure is unrelated.

2021-03-08 16:34 UTC, rishabh-d-dave requested changes

2021-03-08 16:34 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/api/lvm.py
> +    return lvs[0]
We need `get_single_lv()` to raise exception in case of multiple matches.

2021-03-08 16:47 UTC, guits commented
jenkins test ceph-volume tox

2021-03-10 08:46 UTC, guits commented
jenkins test ceph-volume tox

2021-03-10 08:46 UTC, guits commented
jenkins test ceph-volume all

2021-03-10 09:54 UTC, guits commented
jenkins test ceph-volume tox

2021-03-10 14:19 UTC, guits commented
jenkins test ceph-volume all

2021-03-10 14:57 UTC, guits commented
jenkins test ceph-volume lvm centos8-filestore-dmcrypt

2021-03-15 12:35 UTC, rishabh-d-dave approved these changes
Since it's not immediately apparent to the reader which methods are meant by `get_single_*()`, IMO it would be nice if the commit message specifically mentions "`get_single_pv()`, `get_single_vg()` and `get_single_lv()` in `api/lvm.py`" for the clarity and convenience. And usually in ceph.git commits we don't normally use markdown syntax, although I don't mind them.

Looks good to me.

EDIT: Oh, one more thing: it would've been nicer if `get_single_pv()` and `get_single_vg()` were refactored in separate commits. It makes reviewing a little more easier.

2021-03-15 12:35 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/api/lvm.py
> +            raise(RuntimeError('No PV was found.'))
nit: no need for parentheses -
```suggestion
            raise RuntimeError('No PV was found.')
```

2021-03-15 12:35 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/api/lvm.py
>      Wrapper of get_pv meant to be a convenience method to avoid the phrase::
nit:
```suggestion
    Wrapper of get_pvs() meant to be a convenience method to avoid the phrase::
```

2021-03-15 12:35 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/api/lvm.py
>      Wrapper of get_vg meant to be a convenience method to avoid the phrase::
nit

```suggestion
    Wrapper of get_vgs() meant to be a convenience method to avoid the phrase::
```

2021-03-15 12:35 UTC, rishabh-d-dave commented on src/ceph-volume/ceph_volume/api/lvm.py
>      Wrapper of get_lv meant to be a convenience method to avoid the phrase::
nit
```suggestion
    Wrapper of get_lvs() meant to be a convenience method to avoid the phrase::
```

2021-04-07 07:15 UTC, guits commented
jenkins test ceph-volume tox

2021-04-07 07:15 UTC, guits commented
jenkins test ceph-volume all

2021-04-07 11:20 UTC, rishabh-d-dave commented
@guits All CI tests passed. You can merge it now.

2021-04-07 11:32 UTC, merged

2021-07-02 01:02 UTC, guits commented
@rishabh-d-dave shouldn't we have backported this one ?

2021-07-02 13:59 UTC, rishabh-d-dave commented
@guits Since this PR prevents a potential bug, on ceph-volume we would backport this PR. You can use the backport script for convenience.