doc/dev: rewrite "preparation" in adoption.rst
ceph/ceph pull request #39916
Opened 2021-03-08 16:26 UTC by zdover23

This rewrites the "Adoption" section of
preparation.rst in the Cephadm manual.

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-09 14:14 UTC, sebastian-philipp requested changes

2021-03-09 14:31 UTC, zdover23 commented on doc/cephadm/adoption.rst
> +   example, ``docker.io/ceph/ceph:v15.2.0`` will work. The latest stable
I'm going to take out the sentence that mentions the specific release. That should help to future-proof this part of the docs.

2021-03-11 11:09 UTC, sebastian-philipp approved these changes

2021-03-11 11:10 UTC, sebastian-philipp requested changes
the title of the commit should start with `doc/cephadm: `

2021-03-11 19:42 UTC, zdover23 commented
> the title of the commit should start with `doc/cephadm: `

Ach. So it should.

2021-03-15 14:25 UTC, sebastian-philipp approved these changes

2021-03-15 14:25 UTC, merged