rgw/notifications: get/delete of specific notification
ceph/ceph pull request #39945
Opened 2021-03-09 11:30 UTC by yuvalif

note this is a fix to the tool and documentation not the code
(specific delete/get already supported in he code)

Fixes: https://tracker.ceph.com/issues/48369

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-15 15:49 UTC, yuvalif commented
this is fixing the aws cli but breaking the boto3 python API, when no notification is passed (the standard case)
more investigation is needed so that both options would work in python

2021-05-26 05:46 UTC, gauravsitlani commented
@yuvalif I have tested the steps using aws cli , its working as expected.

2021-05-26 07:06 UTC, yuvalif commented
> @yuvalif I have tested the steps using aws cli , its working as expected. Shall i repeat the tests with boto3 scripts as well ?

this would be great. thanks!

2022-01-09 17:08 UTC, mattbenjamin commented
@gauravsitlani are you still working on this?

2022-07-06 01:35 UTC, anthonyeleven approved these changes

2022-07-06 01:35 UTC, anthonyeleven commented on examples/boto3/README.md
> +```
"Get all notifications configured on a bucket:"

2022-07-06 01:35 UTC, anthonyeleven requested changes
See comments

2022-10-28 22:03 UTC, closed without merging