octopus: krbd: make sure the device node is accessible after the mapping
ceph/ceph pull request #39968
Opened 2021-03-09 21:54 UTC by dillaman

https://tracker.ceph.com/issues/49438

2021-03-10 07:55 UTC, trociny approved these changes

2021-03-16 21:07 UTC, idryomov requested changes
There is a bug in the original patch, let's hold on merging.

2021-03-17 19:28 UTC, idryomov commented
Added https://github.com/ceph/ceph/pull/40178

2021-03-18 13:11 UTC, idryomov commented
https://pulpito.ceph.com/dis-2021-03-18_12:05:57-krbd-wip-49438-octopus-testing-basic-gibba/

2021-03-18 13:11 UTC, idryomov approved these changes

2021-03-18 16:48 UTC, merged