octopus: common/mempool: Improve mempool shard selection
ceph/ceph pull request #39978
Opened 2021-03-09 23:58 UTC by singuliere

backport tracker: https://tracker.ceph.com/issues/49053

---

backport of https://github.com/ceph/ceph/pull/39057
parent tracker: https://tracker.ceph.com/issues/49052

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-03-12 17:29 UTC, neha-ojha requested changes

2021-03-12 17:29 UTC, neha-ojha commented on src/test/test_mempool.cc
> +TEST(mempool, check_shard_select)
This is failing https://jenkins.ceph.com/job/ceph-pull-requests/70918/consoleFull#19716391392a811ea2-3e7b-466b-84b4-d13df7e35809

2021-03-14 11:51 UTC, singuliere commented
jenkins test make check

2021-03-14 11:54 UTC, singuliere commented
Marking as WIP until https://tracker.ceph.com/issues/49781 is resolved

2021-04-08 15:41 UTC, singuliere commented
jenkins test make docs

2021-04-11 03:27 UTC, tchaikov commented
@neha-ojha your comment should have been addressed. could you kindly take another look?

2021-04-12 23:54 UTC, neha-ojha approved these changes
nit: the commit message for c0969de17fc5015c691f4104c263e4009fa5010e should say ` #include <thread> `

2021-04-13 11:26 UTC, aclamk approved these changes

2021-04-21 10:25 UTC, singuliere commented
jenkins test this please

2021-04-24 21:50 UTC, singuliere commented
jenkins test this please

2021-05-14 17:43 UTC, merged