nautilus: mgr/dashboard: test prometheus rules through promtool
ceph/ceph pull request #39984
Opened 2021-03-10 05:15 UTC by aaSharma14

backport tracker: https://tracker.ceph.com/issues/49656

---

backport of https://github.com/ceph/ceph/pull/39246
parent tracker: https://tracker.ceph.com/issues/45415

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-03-15 09:22 UTC, callithea requested changes
Could you please remove the additional whitespace changes in `src/test/CMakeLists.txt`?

2021-03-15 11:14 UTC, aaSharma14 commented
> Could you please remove the additional whitespace changes in `src/test/CMakeLists.txt`?

Thanks @callithea . Done

2021-03-15 11:20 UTC, tchaikov commented
is this a bug fix? if not, why do we need to backport it?

2021-03-15 12:41 UTC, aaSharma14 commented
> is this a bug fix? if not, why do we need to backport it?

This PR is adding unit tests for the prometheus rules. Tiil now we needed to manually do the testing for the alerts. Backporting this would be good IMO.

2021-03-15 13:08 UTC, callithea approved these changes

2021-04-12 12:16 UTC, avanthakkar approved these changes

2021-04-12 12:48 UTC, tchaikov requested changes
this change has been reworked on master. could please cherry-pick the follow-up changes as well?

2021-04-16 07:05 UTC, aaSharma14 commented
> this change has been reworked on master. could please cherry-pick the follow-up changes as well?

Thanks @tchaikov . Cherry-picked those changes as well. Please take a look.

2021-04-16 15:48 UTC, tchaikov commented on install-deps.sh
> +=======
this change does not look right.

2021-04-20 07:43 UTC, tchaikov commented
i don't think we need to install libboost 1.75 for building nautilus. neither do we need to build with libzbd on nautilus. so i'd suggest remove those commits from this backport PR.

2021-04-20 08:03 UTC, aaSharma14 commented
> i don't think we need to install libboost 1.75 for building nautilus. neither do we need to build with libzbd on nautilus. so i'd suggest remove those commits from this backport PR.

Thanks @tchaikov . I have removed those commits. Are the current commits okay for this backport? Or I need to change something else?

2021-04-20 14:11 UTC, idryomov requested changes
Please get rid of those merge commits by rebasing on latest nautilus and drop boost-related changes.  They might be needed but shouldn't be included in the dashboard backport PR.

2021-04-21 10:28 UTC, idryomov requested changes
You are missing "cherry-picked from" annotations, please use `git cherry-pick -x`.

Conflicts should be documented in the commit message -- what led to the conflict (i.e. what changes are missing in nautilus), how the conflict was resolved, etc.

2021-04-21 11:59 UTC, aaSharma14 commented
jenkins test make check

2021-04-22 07:33 UTC, aaSharma14 commented
jenkins test api

2021-04-22 07:33 UTC, aaSharma14 commented
> You are missing "cherry-picked from" annotations, please use `git cherry-pick -x`.
> 
> Conflicts should be documented in the commit message -- what led to the conflict (i.e. what changes are missing in nautilus), how the conflict was resolved, etc.

Thanks @idryomov . Will modify the commit message

2021-04-22 10:57 UTC, idryomov requested changes
`cherry picked from` annotations are still missing which suggests that you didn't use `git cherry-pick -x`.  The conflict resolution is messed up as well: your first commit is adding `<<<<<<< HEAD`, etc markers and then the second commit drops them.  These markers should not be there.

I suggest that you start from a clean slate, use `git cherry-pick -x` and make sure conflicts are resolved and documented properly in *each* commit.  Refer to https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules for details.

2021-04-22 10:58 UTC, idryomov commented
@smithfarm Can you or someone else on the backports teams help Aashish with the process?

2021-04-22 11:07 UTC, smithfarm commented
The first thing to clarify is: which commits from master need to be cherry-picked?

I see one commit from #39246 and then there is https://github.com/ceph/ceph/pull/40205 which seems to be related...

2021-04-22 11:18 UTC, smithfarm commented
ah, I see the Pacific backport has 4 commits: #40929

maybe those 4, then?

2021-04-23 12:33 UTC, aaSharma14 commented
> `cherry picked from` annotations are still missing which suggests that you didn't use `git cherry-pick -x`. The conflict resolution is messed up as well: your first commit is adding `<<<<<<< HEAD`, etc markers and then the second commit drops them. These markers should not be there.
> 
> I suggest that you start from a clean slate, use `git cherry-pick -x` and make sure conflicts are resolved and documented properly in _each_ commit. Refer to https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules for details.

Thanks @idryomov Addressed your comments.

2021-04-23 20:26 UTC, idryomov reviewed
My concerns have been addressed.  Deferring to the Dashboard team -- the PR has changed quite a lot, please re-review.

2021-04-26 10:21 UTC, nizamial09 approved these changes

2021-04-26 10:37 UTC, alfonsomthd approved these changes

2021-04-27 17:18 UTC, merged