client: notify and stop the tick thread when destructing the Client
ceph/ceph pull request #40028
Opened 2021-03-11 10:43 UTC by lxbsz

When the test is aborted and it won't get any chance to run the
Client::unmount() and Client::shutdown() functions, so the tick
thread may still running and will access the cct->_conf when it
is destructing, which will case crash.

Fixes: https://tracker.ceph.com/issues/49725
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-11 16:05 UTC, batrick requested changes
What would be better than `libcephfs: move cct member ahead of the client` is to hold an intrusive ptr for the CephContext in `Client`. Rather than using the raw pointer from `Dispatcher`.

2021-03-12 00:38 UTC, lxbsz commented
> What would be better than `libcephfs: move cct member ahead of the client` is to hold an intrusive ptr for the CephContext in `Client`. Rather than using the raw pointer from `Dispatcher`.

Yeah, sounds a perfect approach. Will change it.

2021-03-12 17:05 UTC, batrick approved these changes

2021-03-17 03:20 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2021-03-15_22:16:56-fs-wip-pdonnell-testing-20210315.182203-distro-basic-smithi/

- https://tracker.ceph.com/issues/49842
- https://tracker.ceph.com/issues/49466
- https://tracker.ceph.com/issues/49822
- https://tracker.ceph.com/issues/49240
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/49500
- https://tracker.ceph.com/issues/49843
- https://tracker.ceph.com/issues/49845
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/49605

and failure caused by PR: https://github.com/ceph/ceph/pull/39969

2021-03-17 03:25 UTC, merged