doc: mds cap acquisition readdir throttle documentation
ceph/ceph pull request #40058
Opened 2021-03-12 08:15 UTC by kotreshhr

Fixes: https://tracker.ceph.com/issues/49763
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-12 08:16 UTC, kotreshhr commented
jenkins render docs

2021-03-12 16:49 UTC, batrick requested changes
Otherwise LGTM

2021-03-12 16:49 UTC, batrick commented on doc/cephfs/cache-configuration.rst
> +the directory.
```suggestion
caps recall. Each readdir call increments the counter by the number of files in the result.
```

2021-03-12 16:50 UTC, batrick commented
> jenkins render docs

You don't need to do this anymore. Just look at the "Details" link for the "docs/readthedocs.org:ceph" check.

2021-03-18 02:40 UTC, batrick approved these changes

2021-03-18 02:41 UTC, merged