mgr/dashboard: Fix for broken User management role cloning
ceph/ceph pull request #40216
Opened 2021-03-18 13:04 UTC by nizamial09

Cloning a role in user management gets hit with a 415 error.

Fixes: https://tracker.ceph.com/issues/49880
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-18 13:17 UTC, nizamial09 commented
jenkins test make check

2021-03-19 06:09 UTC, nizamial09 commented
jenkins test make check

2021-03-19 06:36 UTC, nizamial09 commented
jenkins test make check

2021-03-19 09:21 UTC, nizamial09 commented
jenkins test make check

2021-03-19 10:33 UTC, avanthakkar requested changes
LGTM! Just the unit-tests are failing (locally) , so you need to adapt the role.service.spec.ts accordingly - 
`it('should call clone', () => {
    service.clone('foo', 'bar').subscribe();
    const req = httpTesting.expectOne('api/role/foo/clone');
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({"new_name":"bar"});
  });`

2021-03-22 06:11 UTC, nizamial09 commented
> LGTM! Just the unit-tests are failing (locally) , so you need to adapt the role.service.spec.ts accordingly 

Thanks @avanthakkar Took care of it. PTAL.

2021-03-22 06:38 UTC, avanthakkar approved these changes

2021-03-23 04:47 UTC, aaSharma14 approved these changes

2021-03-23 07:55 UTC, alfonsomthd approved these changes

2021-03-23 19:10 UTC, merged