cephadm: synchronize container timezone with host
ceph/ceph pull request #40284
Opened 2021-03-21 07:04 UTC by melissa-kun-li

synchronize timezone in podman and docker containers from default UTC to host's timezone

Fixes: https://tracker.ceph.com/issues/49449
Signed-off-by: Melissa Li <li.melissa.kun@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-21 13:15 UTC, liewegas approved these changes
looks good!

2021-03-22 17:44 UTC, liewegas requested changes
On Ubuntu, I see
<pre>
autriche:~ (master) 12:43 PM $ ls -al /etc/timezone /etc/localtime
lrwxrwxrwx 1 root root 35 Jan 29 06:39 /etc/localtime -> /usr/share/zoneinfo/America/Chicago
-rw-r--r-- 1 root root 16 Jan 29 06:39 /etc/timezone
</pre>
On fedora/rhel/centos, I see
<pre>
gnit:build (test-tz) 12:43 PM $ ls -al /etc/timezone /etc/localtime
ls: cannot access '/etc/timezone': No such file or directory
lrwxrwxrwx. 1 root root 37 Sep 29  2017 /etc/localtime -> ../usr/share/zoneinfo/America/Chicago
</pre>

2021-03-22 20:52 UTC, melissa-kun-li commented
Removed /etc/timezone. Does the timezone in `date` match the timezone in the logs for all distros? I'm not sure how to check

2021-03-23 02:19 UTC, melissa-kun-li commented
jenkins test make check

2021-03-24 00:11 UTC, liewegas commented
```
2021-03-23T23:13:53.670 INFO:tasks.workunit.client.0.smithi081.stderr:++ sudo /home/ubuntu/cephtest/clone.client.0/qa/workunits/cephadm/../../../src/cephadm/cephadm --image quay.ceph.io/ceph-ci/ceph:master shell --date
2021-03-23T23:13:53.828 INFO:tasks.workunit.client.0.smithi081.stderr:usage: cephadm [-h] [--image IMAGE] [--docker] [--data-dir DATA_DIR]
2021-03-23T23:13:53.829 INFO:tasks.workunit.client.0.smithi081.stderr:               [--log-dir LOG_DIR] [--logrotate-dir LOGROTATE_DIR]
2021-03-23T23:13:53.829 INFO:tasks.workunit.client.0.smithi081.stderr:               [--unit-dir UNIT_DIR] [--verbose] [--timeout TIMEOUT]
2021-03-23T23:13:53.829 INFO:tasks.workunit.client.0.smithi081.stderr:               [--retry RETRY] [--env ENV] [--no-container-init]
2021-03-23T23:13:53.829 INFO:tasks.workunit.client.0.smithi081.stderr:               {version,pull,inspect-image,ls,list-networks,adopt,rm-daemon,rm-cluster,run,shell,enter,ceph-volume,unit,logs,bootstrap,deploy,check-host,prepare-host,add-repo,rm-repo,install,registry-login,gather-facts,exporter,host-maintenance,verify-prereqs}
2021-03-23T23:13:53.830 INFO:tasks.workunit.client.0.smithi081.stderr:               ...
2021-03-23T23:13:53.830 INFO:tasks.workunit.client.0.smithi081.stderr:cephadm: error: unrecognized arguments: --date
2021-03-23T23:13:53.844 INFO:tasks.workunit.client.0.smithi081.stderr:+ presync_timezone=
2021-03-23T23:13:53.844 INFO:tasks.workunit.client.0.smithi081.stderr:+ cleanup
2021-03-23T23:13:53.845 INFO:tasks.workunit.client.0.smithi081.stderr:+ '[' true = false ']'
```
/a/sage-2021-03-23_22:31:12-rados:cephadm-wip-sage-testing-2021-03-23-1606-distro-basic-smithi/5990980

2021-03-24 07:43 UTC, melissa-kun-li commented
I made my `cephadm` binary executable with `chmod +x cephadm` and bootstrapped a cluster, checking the date in the cephadm shell:
[![Screen-Shot-2021-03-24-at-3-17-09-AM.png](https://i.postimg.cc/3JbNLwnN/Screen-Shot-2021-03-24-at-3-17-09-AM.png)](https://postimg.cc/56LfyfcW)

I checked if `cephadm` logs would also have timezone changed from UTC to local.

When I check daemon logs, the timezone is correct: 
[![Screen-Shot-2021-03-24-at-2-37-53-AM.png](https://i.postimg.cc/P5THQnkJ/Screen-Shot-2021-03-24-at-2-37-53-AM.png)](https://postimg.cc/2VcgCJyN)

When I enable debug-level messages and run `ceph -W cephadm --watch-debug`, timezone is also correct:

[![Screen-Shot-2021-03-24-at-1-31-18-AM.png](https://i.postimg.cc/nzRr6cp3/Screen-Shot-2021-03-24-at-1-31-18-AM.png)](https://postimg.cc/bDnqnPGn)

However, when I run `ceph log last cephadm`, the timezone is incorrect because it's UTC (+0000):

[![Screen-Shot-2021-03-24-at-2-39-30-AM.png](https://i.postimg.cc/qvwN8GWf/Screen-Shot-2021-03-24-at-2-39-30-AM.png)](https://postimg.cc/cvK1WfsT)

2021-03-25 06:01 UTC, melissa-kun-li commented
From my previous comment, I wonder if the issue with the timezone not appearing correctly for the `ceph log last cephadm` is within the scope of the original issue raised on the bugtracker? @sebastian-philipp

2021-03-25 14:19 UTC, liewegas commented
Those timestamps are rendered to a string inside the monitor container..
which is probably still UTC.

I'm of two minds here: I'm not actually sure we want to use the host TZ
instead of UTC everywhere; as a general rule I've found that using UTC for
servers is the way to go since they are frequently in a different TZ than
the user.  However, that probably means the host should be UTC so that the
admin can make that choice...

On Thu, Mar 25, 2021 at 1:01 AM Melissa ***@***.***> wrote:

> From my previous comment, I wonder if the issue with the timezone not
> appearing correctly for the ceph log last cephadm is within the scope of
> the original issue raised on the bugtracker? @sebastian-philipp
> <https://github.com/sebastian-philipp>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ceph/ceph/pull/40284#issuecomment-806387301>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADJXB4L6KVUMW5A47LFQRDTFLGTLANCNFSM4ZRIGOSA>
> .
>

2021-03-26 07:09 UTC, melissa-kun-li commented
Ohh I see. hmm so with the proposed change right now, do we still want the container timezone to be synced with the host? If not, we can close this PR

2021-04-14 14:06 UTC, sebastian-philipp commented
um. added this PR to my list to review

2021-07-07 09:34 UTC, closed without merging