[DNM] Add libcephsqlite!
ceph/ceph pull request #40292
Opened 2021-03-21 15:20 UTC by tchaikov

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-22 17:54 UTC, batrick commented
LGTM. You can rebase now.

2021-03-23 03:49 UTC, tchaikov commented
@batrick actually, i am not quite satisfied with the outcome of this changeset. because there still a bunch of weak symbols exposed by libcephsqlite even with this change. most of them are from boost, but i cannot find a simple way to hide them. `dpkg-gensymbols` finds them when looking at libcephsqlite.so, and considers them new symbols introduced by the latest version of `libcephsqlite.so` on top of the ones declared in the .symbols file. this does not hurt, as no symbols are *removed*. but still, it's not perfect. i also looked into https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html, but it seems it does not give us more control over the symbol visibility in addition to what i am using in this changeset. it's just more convenient.

2021-03-23 10:23 UTC, tchaikov commented
jenkins test make check

2021-03-23 14:03 UTC, batrick requested changes
> @batrick actually, i am not quite satisfied with the outcome of this changeset. because there still a bunch of weak symbols exposed by libcephsqlite even with this change. most of them are from boost, but i cannot find a simple way to hide them. 

Is this is a consequence of the shared library not being versioned? I would think other libraries like librados would have the same issue?

2021-03-23 15:30 UTC, tchaikov commented on debian/control
> -         libsqlite3-mod-ceph,
thanks! will add this tag in the commit message.

2021-03-23 15:36 UTC, tchaikov commented
> > @batrick actually, i am not quite satisfied with the outcome of this changeset. because there still a bunch of weak symbols exposed by libcephsqlite even with this change. most of them are from boost, but i cannot find a simple way to hide them.
> 
> Is this is a consequence of the shared library not being versioned? 

no, they are orthogonal. 

> I would think other libraries like librados would have the same issue?

yes. we never added the .symbols file for librados or other packaged public shared libraries, not because `dh_makeshlibs` is able to figure out the shlib deps correctly for us. just because we always hardwire the dependencies in debian/control. `libcephsqlite` is the first one. because `dh_makeshlibs` failed to do set the subvar for us, and more importantly, to ~~replace the light bulb~~ root cause of failure caused by the buggy packaging took the efforts of 3 engineers. so i felt obliged to figure it out.

2021-03-24 07:43 UTC, tchaikov commented
@batrick added the "Fixes" tag in the commit message and repushed.

2021-03-24 21:24 UTC, batrick approved these changes

2021-03-26 06:28 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-03-25_06:40:11-rados-wip-kefu-testing-2021-03-25-1305-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-25_14:56:28-rados-wip-kefu-testing-2021-03-25-2042-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-26_05:32:58-rados-wip-kefu-testing-2021-03-26-1134-distro-basic-smithi/

2021-03-26 06:28 UTC, merged