qa/cephfs: modify get_key_from_keyfile() in mount.py
ceph/ceph pull request #40434
Opened 2021-03-26 11:41 UTC by rishabh-d-dave

CephFSMount.get_key_from_keyfile() should raise an exception instead of
returning None if key is not found in keyring file.

Fixes: https://tracker.ceph.com/issues/50010

## Checklist
- [x] References tracker ticket

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-26 11:42 UTC, rishabh-d-dave commented
Depends on https://github.com/ceph/ceph/pull/37667 since the commit also has a minor re-write of the method.

2021-07-13 15:27 UTC, batrick requested changes

2021-07-13 15:27 UTC, batrick commented on qa/tasks/cephfs/mount.py
> +        keyring = str(self.client_remote.read_file(self.client_keyring_path))
```suggestion
        keyring = self.client_remote.read_file(self.client_keyring_path, stdout=StringIO())
```

2021-07-14 13:24 UTC, rishabh-d-dave commented on qa/tasks/cephfs/mount.py
> +        keyring = str(self.client_remote.read_file(self.client_keyring_path))
Done, thanks!

2021-07-16 00:45 UTC, batrick approved these changes

2021-07-16 00:47 UTC, batrick commented on qa/tasks/cephfs/mount.py
> +                                               stdout=StringIO())
Actually, do we need to add `sudo=True` for this? You dropped that without explanation.

2021-11-24 04:13 UTC, vshankar commented
@rishabh-d-dave is this still DNM?

2022-05-05 09:35 UTC, rishabh-d-dave commented
Waiitng for https://github.com/ceph/ceph/pull/37667 to merge now.

2022-05-06 04:25 UTC, rishabh-d-dave commented
@vshankar This PR too can be added to weekly QA run. I'll test it out myself before that since it's pretty old.

2022-05-06 09:37 UTC, joscollin approved these changes

2022-05-06 10:06 UTC, rishabh-d-dave commented
Tests ran fine: the key was picked successfully from the keyring by the code added here. Link - http://pulpito.front.sepia.ceph.com/rishabh-2022-05-06_09:16:10-fs-wip-rishabh-fs-auth-subcmd-distro-basic-smithi

```
sudo nsenter --net=/var/run/netns/ceph-ns--home-ubuntu-cephtest-mnt.0 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage /bin/mount -t ceph :/ /home/ubuntu/cephtest/mnt.0 -v -o norequire_active_mds,secret=AQCK7HRiSg3HJhAAQWz8eJTBiFJB049akOrZpw==,conf=/etc/ceph/ceph.conf,norbytes,name=testuser,mds_namespace=cephfs2
```

2022-05-06 10:10 UTC, rishabh-d-dave commented
This PR is still DNM because it won't work fine vstart_runner.py unless PR #37667 is merged.

2022-05-11 09:27 UTC, rishabh-d-dave commented
Removing DNM since PR #37667 is merged now.

2022-06-01 07:25 UTC, rishabh-d-dave commented
http://pulpito.front.sepia.ceph.com/rishabh-2022-05-31_14:44:01-fs-wip-vshankar-testing-20220527-073645-distro-basic-smithi/

2022-06-03 04:08 UTC, rishabh-d-dave commented
make check if failing to due to a bug -
```
  × git checkout -q master did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.
```
make check job - https://jenkins.ceph.com/job/ceph-pull-requests/96601/consoleFull#-1999443340e840cee4-f4a4-4183-81dd-42855615f2c1

2022-06-03 04:10 UTC, rishabh-d-dave commented
Rebasing to get rid of this bug.

2022-06-03 05:37 UTC, rishabh-d-dave commented
jenkins test make check arm64

2022-06-03 06:56 UTC, rishabh-d-dave commented
jenkins test make check arm64

2022-06-06 05:36 UTC, vshankar approved these changes

2022-06-06 05:49 UTC, merged