doc/security: add security section
ceph/ceph pull request #40504
Opened 2021-03-30 17:48 UTC by liewegas

- how to report an issue
- describe process for handling vulnerability
- list past issues

Signed-off-by: Sage Weil <sage@newdream.net>

2021-03-30 18:50 UTC, liewegas commented
jenkins render docs

2021-03-30 21:30 UTC, jecluis approved these changes

2021-03-30 21:33 UTC, idryomov requested changes
LGTM, but some CVEs are clearly missing so I did a quick grep.  Probably didn't get all of them as it didn't catch a couple that you listed, but better than nothing for 2020 ;)

2021-03-30 21:33 UTC, idryomov commented on doc/security/index.rst
> +* 2018-07-10 `CVE-2018-1129 <https://www.cvedetails.com/cve/CVE-2018-1129/>`_
missing CVE-2018-1128

2021-03-30 21:33 UTC, idryomov commented on doc/security/index.rst
> +
missing CVE-2020-1699, CVE-2020-1700, CVE-2020-1759, CVE-2020-1760,  CVE-2020-10736, CVE-2020-10753,  CVE-2020-12059, CVE-2020-25660, CVE-2020-25677, CVE-2020-25678, CVE-2020-27781

2021-03-30 21:33 UTC, idryomov commented on doc/security/index.rst
> +
missing CVE-2019-10222

2021-03-30 21:33 UTC, idryomov commented on doc/security/index.rst
> +* 2019-03-27 `CVE-2019-3821 <https://www.cvedetails.com/cve/CVE-2019-3821/>`_
missing CVE-2018-14662, CVE-2018-16846, CVE-2018-16889

2021-03-30 23:51 UTC, jdurgin approved these changes

2021-03-31 00:03 UTC, neha-ojha approved these changes

2021-03-31 12:00 UTC, hpvyas commented on doc/security/index.rst
> +| 2017-12-12 | `CVE-2017-12155`_ | 6.3 Medium  | ceph.client.openstack.keyring world readable            |
CVE-2017-12155 affects OpenStack product, issue was fixed in "openstack-tripleo-heat-templates/puppet-tripleo", did we ever fixed it in ceph?

2021-03-31 12:03 UTC, hpvyas commented on doc/security/index.rst
> ++------------+-------------------+-------------+---------------------------------------------------------+
CVE-2015-3010 and CVE-2015-4053 were fixed in ceph-deploy (https://github.com/ceph/ceph-deploy) and not ceph.

2021-03-31 12:04 UTC, hpvyas commented on doc/security/index.rst
> +
Couple of more missing CVEs fixed in Ceph:

CVE-2015-5245   https://nvd.nist.gov/vuln/detail/CVE-2015-5245
CVE-2016-5009   https://nvd.nist.gov/vuln/detail/CVE-2016-5009
CVE-2016-7031   https://nvd.nist.gov/vuln/detail/CVE-2016-7031
CVE-2016-8626   https://nvd.nist.gov/vuln/detail/CVE-2016-8626
CVE-2016-9579   https://nvd.nist.gov/vuln/detail/CVE-2016-9579
CVE-2019-19337  https://nvd.nist.gov/vuln/detail/CVE-2019-19337

2021-03-31 19:38 UTC, idryomov commented
jenkins render docs

2021-04-01 14:49 UTC, merged