pacific: cmake: pass unparsed args to add_ceph_test()
ceph/ceph pull request #40523
Opened 2021-03-31 12:06 UTC by tchaikov

backport of #40496 

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-31 12:46 UTC, rzarzynski requested changes

2021-03-31 12:46 UTC, rzarzynski commented on src/test/crimson/seastore/CMakeLists.txt
> +<<<<<<< HEAD
Oops.

2021-03-31 12:55 UTC, tchaikov commented on src/test/crimson/seastore/CMakeLists.txt
> +<<<<<<< HEAD
@rzarzynski fixed and repushed.

2021-03-31 13:07 UTC, rzarzynski approved these changes

2021-03-31 13:12 UTC, ronen-fr approved these changes

2021-04-01 01:42 UTC, tchaikov commented
jenkins test make check

2021-04-01 01:42 UTC, tchaikov commented
jenkins test api

2021-04-01 02:38 UTC, merged