mds/scrub: background scrub error fixes
ceph/ceph pull request #40520
Opened 2021-03-31 09:53 UTC by mchangir

Accommodate new files and raw stats errors for dirty inodes and declare
scrub as passed.

Fixes: https://tracker.ceph.com/issues/48805
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-03-31 18:24 UTC, batrick requested changes

2021-04-01 07:19 UTC, mchangir commented on src/mds/CInode.cc
> +          auto ino = [this]() { return in->ino(); };
oh, the `mdcache` and `ino` definitions are required to keep `dout()` happy. The `dout` macro definition expects those identifiers to be available in the scope.

2021-04-01 07:21 UTC, mchangir commented on src/mds/CInode.cc
> +        auto ino = [this]() { return in->ino(); };
`mdcache` and `ino` are required to keep `dout()` macro happy

2021-04-01 07:21 UTC, mchangir commented on src/mds/CInode.cc
> +        dout(20) << "raw stats check passed" << dendl;
oops! I missed adding the inode to the log

2021-04-06 21:18 UTC, batrick approved these changes

2021-04-08 02:32 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2021-04-07_02:12:41-fs-wip-pdonnell-testing-20210406.213012-distro-basic-smithi/

- https://tracker.ceph.com/issues/50215
    qa: "log [ERR] : error reading sessionmap 'mds2_sessionmap'"
- https://tracker.ceph.com/issues/49466
    qa: "Command failed on gibba030 with status 1: 'set -ex\nsudo dd of=/tmp/tmp.ZEeZBasJer'"
- https://tracker.ceph.com/issues/50216
    qa: "ls: cannot access 'lost+found': No such file or directory"
- https://tracker.ceph.com/issues/48773
    qa: scrub does not complete
- https://tracker.ceph.com/issues/49845
    qa: failed umount in test_volumes
- https://tracker.ceph.com/issues/50220
    qa: dbench workload timeout
- https://tracker.ceph.com/issues/50221
    qa: snaptest-git-ceph failure in git diff
- https://tracker.ceph.com/issues/50222
    osd: 5.2s0 deep-scrub : stat mismatch
- https://tracker.ceph.com/issues/50223
    qa: "client.4737 isn't responding to mclientcaps(revoke)"
- https://tracker.ceph.com/issues/50224
    qa: test_mirroring_init_failure_with_recovery failure


a bug in standby-replay is cluttering the results -- I'll rerun with the fix.

2021-04-08 18:32 UTC, batrick commented
https://pulpito.ceph.com/pdonnell-2021-04-08_04:31:36-fs-wip-pdonnell-testing-20210408.024225-distro-basic-smithi/
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20210408.142238 (with logic inversion / QA fix)

- https://tracker.ceph.com/issues/50246
    mds: failure replaying journal (EMetaBlob)
- https://tracker.ceph.com/issues/50250
    mds: "log [WRN] : Scrub error on inode 0x10000004506 (/client.0/tmp/clients/client3/~dmtmp/COREL) see mds.a log and `damage ls` output for details"

2021-04-08 18:34 UTC, merged