pacific: cephfs: minor ceph-dokan improvements
ceph/ceph pull request #40627
Opened 2021-04-06 18:10 UTC by petrutlucian94

backport tracker: https://tracker.ceph.com/issues/50187

---

backport of https://github.com/ceph/ceph/pull/39939
parent tracker: https://tracker.ceph.com/issues/49662

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-04-20 06:06 UTC, petrutlucian94 commented
jenkins retest this please

2021-04-20 13:31 UTC, petrutlucian94 commented
jenkins retest this please

2021-04-20 15:12 UTC, idryomov requested changes
Please get rid of the merge commit.  Sorry for the confusion with branches!

2021-04-20 23:56 UTC, batrick commented
jenkins test docs

2021-04-20 23:56 UTC, batrick commented
jenkins test api

2021-04-21 01:41 UTC, batrick commented
jenkins test api

2021-04-21 06:13 UTC, petrutlucian94 commented
jenkins test api

2021-04-21 07:33 UTC, idryomov approved these changes

2021-04-21 09:47 UTC, petrutlucian94 commented
jenkins test api

2021-04-21 13:50 UTC, batrick commented
jenkins test api

2021-04-22 03:39 UTC, batrick commented
jenkins test api

2021-04-23 03:05 UTC, batrick approved these changes

2021-04-23 14:42 UTC, merged