Data allocate fraction
ceph/ceph pull request #40659
Opened 2021-04-08 08:47 UTC by PepperJo

This PR allows to partially allocate a data device when preparing/deploying an OSD with ceph-volume or through the device group specification. The fraction can be between (0,1.0] where a fraction of e.g. 0.8 will allocate 80% of the data device, i.e. the lvm size will only account for 80% of the device's capacity. The rest of the device will not be allocated. This can be used to alleviate write performance degradation of Flash SSDs.
This PR adds `--data-allocate-fraciton` to ceph-volume lvm batch and the `data_allocate_fraction` feature to the device group specification.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-04-23 08:54 UTC, sebastian-philipp commented
Added [needs-review]

2021-06-02 20:13 UTC, andrewschoen requested changes
Overall this looks good. I think we need to add tests for `data_allocate_fraction` though. Tests for other argument validators can be found in `tests.util.test_arg_validators` as an example.

2021-06-02 20:13 UTC, andrewschoen commented on src/ceph-volume/ceph_volume/devices/lvm/batch.py
> +        def data_allocate_fraction(pct):
Could you move this function to `utils.arg_validators` please? You can see an example usage with `arg_validators.ValidDevice` here: https://github.com/ceph/ceph/pull/40659/files#diff-37d41dc2d64315970e0a32c6d84be634f82c62a15c4e3144020ea2be88641601R200

2021-06-03 16:45 UTC, andrewschoen commented
jenkins test ceph-volume all

2021-06-03 16:46 UTC, andrewschoen commented
jenkins test ceph-volume tox

2021-06-04 14:34 UTC, andrewschoen commented
jenkins test ceph-volume all

2021-06-04 14:34 UTC, andrewschoen commented
jenkins test ceph-volume tox

2021-06-04 15:52 UTC, andrewschoen commented
jenkins test ceph-volume tox

2021-06-04 16:56 UTC, PepperJo commented
@andrewschoen thanks for your review. I moved the function as suggested and added a few tests.

2021-06-04 19:35 UTC, andrewschoen commented
jenkins test ceph-volume all

2021-06-04 19:40 UTC, andrewschoen commented
> @andrewschoen thanks for your review. I moved the function as suggested and added a few tests.

@PepperJo thank you for the work! These changes look great. If the CI finishes clean, I'll approve this.

2021-06-05 08:55 UTC, PepperJo commented
@andrewschoen I checked the failed tests and if I interpret them correctly there seems to be a problem with `fetch ceph red hat development repository`? That seems to be unrelated to my changes.

2021-06-07 14:20 UTC, andrewschoen commented
jenkins test ceph-volume all

2021-06-07 14:22 UTC, andrewschoen commented
> @andrewschoen I checked the failed tests and if I interpret them correctly there seems to be a problem with `fetch ceph red hat development repository`? That seems to be unrelated to my changes.

@PepperJo I agree, they do look unrelated. It looks like there was some trouble accessing some dev repos to test with, which I suspect is transient. I'll try again as these tests did all pass on previous runs.

2021-06-07 15:46 UTC, andrewschoen commented
jenkins test ceph-volume lvm centos8-filestore-dmcrypt

2021-06-07 17:28 UTC, andrewschoen commented
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

2021-06-07 17:49 UTC, andrewschoen commented
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

2021-06-07 19:05 UTC, andrewschoen approved these changes

2021-06-07 19:06 UTC, merged

2021-06-08 07:56 UTC, PepperJo commented
@andrewschoen Thank you!