octopus: mon/MgrMonitor: populate available_modules from promote_standby()
ceph/ceph pull request #40757
Opened 2021-04-10 17:58 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/49816

---

backport of https://github.com/ceph/ceph/pull/40078
parent tracker: https://tracker.ceph.com/issues/49778

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-04-10 18:01 UTC, smithfarm commented
The second commit in https://github.com/ceph/ceph/pull/40078 (which is the master PR I'm trying to backport here) appears to be dependent on edf1ea2 which is just one commit of a total of 12 in https://github.com/ceph/ceph/pull/39504

I'm not really confident in my approach here, so I'd be grateful for reviews and/or advice on how to proceed.

2021-04-10 18:05 UTC, liewegas requested changes
I think we should only backport 692ed5ad216aac49b6dd4c6485fe431bb1b91458

2021-04-10 20:50 UTC, smithfarm commented
@liewegas Thanks; done.

2021-04-11 13:46 UTC, liewegas approved these changes

2021-04-14 04:49 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-04-12_02:35:25-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-12_13:55:39-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-smithi/

i think most of cephadm test failures are caused by https://tracker.ceph.com/issues/49293

2021-04-24 10:11 UTC, tchaikov commented
jenkins retest this please

2021-04-25 02:49 UTC, merged