nautilus: mgr/PyModule: put mgr_module_path before Py_GetPath()
ceph/ceph pull request #40753
Opened 2021-04-10 16:39 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/50073

---

backport of https://github.com/ceph/ceph/pull/40505
parent tracker: https://tracker.ceph.com/issues/50046

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-04-10 17:48 UTC, smithfarm commented
```
The following tests FAILED:
	124 - unittest_journal (Timeout)
```

2021-04-10 17:48 UTC, smithfarm commented
jenkins test make check

2021-04-12 13:46 UTC, jdurgin approved these changes

2021-04-12 13:56 UTC, tchaikov approved these changes

2021-04-27 23:42 UTC, ideepika commented
failure importing mgr_module_path with this change, needs fix.
https://pulpito.ceph.com/yuriw-2021-04-22_18:57:38-rados-wip-yuri-testing-2021-04-22-0825-nautilus-distro-basic-smithi/

2021-04-28 03:17 UTC, tchaikov requested changes

2021-04-28 03:17 UTC, tchaikov commented on src/mgr/PyModule.cc
> +      wstring sys_path(wstring(begin(paths), end(paths)) + Py_GetPath());
since we still need to support python2. might want to apply the same change to the `#else` branch at line 351.

2021-04-28 07:13 UTC, smithfarm commented
@tchaikov Like this?

2021-04-28 07:16 UTC, tchaikov approved these changes

2021-04-29 12:18 UTC, smithfarm commented
```
The following tests FAILED:
	125 - unittest_journal (Timeout)
```

2021-04-29 12:18 UTC, smithfarm commented
jenkins test make check

2021-04-29 13:46 UTC, smithfarm commented
```
180/180 Test #125: unittest_journal ........................***Timeout 3600.10 sec
```

2021-04-29 13:46 UTC, smithfarm commented
jenkins test make check

2021-04-29 17:00 UTC, smithfarm commented
```
The following tests FAILED:
	125 - unittest_journal (Timeout)
```

This failure reproduced three times in a row :-(

2021-05-04 15:31 UTC, yuriw commented
test this please

2021-05-05 14:38 UTC, yuriw commented
test this please

2021-05-05 15:24 UTC, tchaikov commented
@yuriw the doc build failure should be addressed by #41167 . could you kindly include it in your next batch, so it can be tested and merged sooner if it does not introduce any regression?

2021-05-05 18:03 UTC, yuriw commented
test this please

2021-05-05 19:23 UTC, yuriw commented
test this please

2021-05-05 21:04 UTC, merged