octopus: client: add ability to lookup snapped inodes by inode number
ceph/ceph pull request #40768
Opened 2021-04-10 21:09 UTC by smithfarm

backport tracker: https://tracker.ceph.com/issues/49513

---

backport of https://github.com/ceph/ceph/pull/39294
parent tracker: https://tracker.ceph.com/issues/48991

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-04-13 11:26 UTC, jtlayton approved these changes

2021-04-19 17:17 UTC, batrick commented
blocked by fix for https://tracker.ceph.com/issues/50216#change-192030

cc @lxbsz

2021-05-11 19:38 UTC, batrick requested changes
Please include https://tracker.ceph.com/issues/50625

2021-05-12 09:00 UTC, smithfarm commented
> Please include https://tracker.ceph.com/issues/50625

OK, I guess you meant https://tracker.ceph.com/issues/50623 ? Done.

2021-05-12 12:52 UTC, lxbsz commented
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSDaemon.cc:45:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/SnapServer.h: In member function 'void SnapServer::mark_base_recursively_scrubbed(inodeno_t)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/SnapServer.h:57:17: error: 'MDS_INO_ROOT' was not declared in this scope; did you mean 'CEPH_INO_ROOT'?
   57 |     if (ino ==  MDS_INO_ROOT)
      |                 ^~~~~~~~~~~~
      |                 CEPH_INO_ROOT
make[3]: *** [src/mds/CMakeFiles/mds.dir/build.make:89: src/mds/CMakeFiles/mds.dir/MDSDaemon.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 28%] Building CXX object src/tools/rbd_mirror/CMakeFiles/rbd_mirror_internal.dir/LeaderWatcher.cc.o
  CC lib/scsi/scsi_rpc.o
```

You should `s/MDS_INO_ROOT/CEPH_INO_ROOT/` in `MDSDaemon.cc`.

2021-05-12 15:34 UTC, smithfarm commented
> You should s/MDS_INO_ROOT/CEPH_INO_ROOT/ in MDSDaemon.cc.

I guess you mean "in `src/mds/SnapServer.h`"

2021-05-12 16:20 UTC, smithfarm commented
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc: In member function 'CInode* MDCache::create_root_inode()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:465:3: error: 'i' was not declared in this scope; did you mean 'bi'?
  465 |   i->inode.uid = g_conf()->mds_root_ino_uid;
      |   ^
      |   bi
```

2021-05-13 01:00 UTC, lxbsz approved these changes

2021-05-19 17:29 UTC, yuriw commented
@smithfarm this seems to be failing the build:

/src/test/libcephfs/test.cc: In member function 'virtual void LibCephFS_LookupVino_Test::TestBody()': /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/14.2.21-257-ge1f9754b/rpm/el8/BUILD/ceph-14.2.21-257-ge1f9754b/src/test/libcephfs/test.cc:2498:16: error: 'ceph_mksnap' was not declared in this scope    ASSERT_EQ(0, ceph_mksnap(cmount,

 dir_path, snap_name, 0755, nullptr, 0));

https://shaman.ceph.com/builds/ceph/wip-yuri7-testing-2021-05-19-0805-octopus/

@batrick - is this a must for next octopus point ?

2021-05-19 17:48 UTC, smithfarm commented
@yuriw Indeed, there is no `ceph_mksnap` in octopus, so that error makes sense. I'm surprised that `make check` didn't flag it.

@batrick Is it feasible to simply drop the `ceph_mksnap` line from the test, or is something more convoluted in order?

2021-05-19 18:27 UTC, jtlayton commented
If you just drop the line, then the test will probably not pass (or at least, not work correctly). We could change it to just do a mkdir .snap/snap_name, I suppose instead of calling ceph_mksnap.

Alternately, we could just also backport the patch that adds ceph_mksnap, but I haven't looked at how involved that is.

2021-05-21 07:35 UTC, smithfarm commented
> We could change it to just do a mkdir .snap/snap_name, I suppose instead of calling ceph_mksnap.

Can you post a little diff?

> Alternately, we could just also backport the patch that adds ceph_mksnap, but I haven't looked at how involved that is.

https://github.com/ceph/ceph/pull/37721

I doubt if that's feasible for nautilus...

2021-05-26 12:18 UTC, smithfarm commented
Over in the nautilus backport - https://github.com/ceph/ceph/pull/40769 - @jtlayton added a patch with a minimalistic `ceph_mksnap` implementation.

Presumably that's the way forward here, as well.

2021-05-26 13:52 UTC, smithfarm commented
@batrick Has your change request been addressed?

2021-05-27 14:32 UTC, jtlayton commented
@smithfarm : you may need the updated patch in #40769. The testcase also calls ceph_rmsnap, so we need an alternative implementation of that too.

2021-06-10 21:43 UTC, batrick approved these changes

2021-06-15 14:46 UTC, merged