rbd-nbd: add ability to restore nbd devices
ceph/ceph pull request #40809
Opened 2021-04-12 10:28 UTC by pkalever

Problem:                                                                       
-------                                                                        
Currently, with the rbd-nbd tool, we can map the nbd devices and scale         
them as needed. But in case if the node is rebooted, there is no way to restore
the nbd device mappings and one has to do remap of the big list of devices     
manually. This is a serious problem in container environments, if the container
hosting the rbd-nbd processes is restarted, all the mapping is just gone and   
The application will start seeing the IO errors.                               
                                                                               
Solution:                                                                      
--------                                                                       
With these changes, on every successful Map operation, we save the             
details of the nbd device mappings to a persistent file (here on called as     
saveconfig file) in the JSON format which will be used for restore. Similarly, 
on Unmap we clean the JSON object related to the device.                       
                                                                               
Thanks to the attach command, the restore command will leverage it and         
brings the rbd-nbd processes to life.                                          
                                                                               
The default path of the JSON file is /etc/ceph/saveconfig.json                 
                                                                               
Example usage:                                                                 
-------------
```                                                                  
$ rbd-nbd list-mapped                                                          
id      pool           namespace  image    snap  device                        
617318  rbd-pool                  image1   -     /dev/nbd0                     
617356  rbd-pool                  image2   -     /dev/nbd1                     
617394  rbd-pool                  image3   -     /dev/nbd2                     
617433  rbd-pool                  image4   -     /dev/nbd3                     
617472  rbd-pool                  image5   -     /dev/nbd4                     
                                                                               
$ pkill -9 rbd-nbd                                                             
```

#### Restore all from default location:
```
$ rbd-nbd restore                                                              
=> Attempting to attach: /dev/nbd0 -> rbd-pool/image1                          
SUCCESS                                                                        
=> Attempting to attach: /dev/nbd1 -> rbd-pool/image2                          
SUCCESS                                                                        
=> Attempting to attach: /dev/nbd2 -> rbd-pool/image3                          
SUCCESS                                                                        
=> Attempting to attach: /dev/nbd3 -> rbd-pool/image4                          
SUCCESS                                                                        
=> Attempting to attach: /dev/nbd4 -> rbd-pool/image5                          
SUCCESS                                                                        
```

#### Restore partial list from default location:
```
$ rbd-nbd restore --attach-list="rbd-pool/image1,/dev/nbd4"
=> Attempting to attach: /dev/nbd0 -> rbd-pool/image1      
SUCCESS                                                    
=> Attempting to attach: /dev/nbd4 -> rbd-pool/image5      
SUCCESS                                                    
```

#### Restore partial list from default location with id, keyfile and mon_host:
```
$ rbd-nbd --id="admin" --keyfile=/tmp/keyfile -m "10.70.1.100:6789" restore --attach-list="rbd-pool/image2,/dev/nbd3"
=> Attempting to attach: /dev/nbd1 -> rbd-pool/image2
SUCCESS
=> Attempting to attach: /dev/nbd3 -> rbd-pool/image4
SUCCESS
```

#### Restore from configurable saveconfig file location:
```
$ ./bin/rbd-nbd map --saveconfig-file /tmp/rbd-nbd-cfg.json
$ ./bin/rbd-nbd restore --saveconfig-file /tmp/rbd-nbd-cfg.json
$ ./bin/rbd-nbd unmap
```

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-04-12 10:31 UTC, pkalever commented
cc: @lxbsz @nixpanic @Madhu-1 @oritwas

2021-04-12 17:04 UTC, trociny commented
@pkalever Was it discussed earlier in Ceph community before you started working on this?

Because, although the feature looks useful to me and you did a great job here, I hate to say, I am not sure it is the right approach.

It seems like it could be done on a higher layer, keeping the rbd-nbd simple. Moreover it could be more generic, so it could also handle krbd and FreeFSD's rbd-ggate.

We tried to make these drivers provide similar interface so you could use `rbd -t <device-type> map|unmap|list` and it would work in similar way for `kernel`, `nbd`, and `ggate` types.

The functionality provided here resembles rbdmap we have for krbd. And we actually have a feature request to make it generic and work not only for rbdmap [2, 3], and @lxbsz seemed to start working on it, although I have no idea if there have been any progress so far. I don't say we have to stick to rbdmap (I have never used personally) but it would be great if we came with something more generic. Probably you could just move your code from `rbd-nbd` to `rbd`?

Note, it is just my humble opinion though. I would love to see what other people think about it. That is why I asked if there were some discussion about this.

[1] https://docs.ceph.com/en/latest/man/8/rbdmap/
[2] https://tracker.ceph.com/issues/20762
[3] https://tracker.ceph.com/issues/48257

2021-04-12 17:04 UTC, trociny commented
@idryomov Do you have any opinion about this?

2021-04-13 01:15 UTC, lxbsz commented
> @pkalever Was it discussed earlier in Ceph community before you started working on this?
> 
> Because, although the feature looks useful to me and you did a great job here, I hate to say, I am not sure it is the right approach.
> 
> It seems like it could be done on a higher layer, keeping the rbd-nbd simple. Moreover it could be more generic, so it could also handle krbd and FreeFSD's rbd-ggate.
> 
> We tried to make these drivers provide similar interface so you could use `rbd device map|unmap|list -t <device-type>` and it would work in similar way for `kernel`, `nbd`, and `ggate` types.
> 
> The functionality provided here resembles `rbdmap` [1] we have for krbd. And we actually have a feature request to make it generic and work not only for rbdmap [2, 3], and @lxbsz seemed to start working on it, although I have no idea if there have been any progress so far. I don't say we have to stick to rbdmap (I have never used personally) but it would be great if we came with something more generic. Probably you could just move your code from `rbd-nbd` to `rbd`?

This look good to me, I haven't start that yet and not recently, because I am not sure whether could this work for the containers in rbd-nbd.

While for now, this approach maybe a very good start for this feature IMHO, and let's make it more generic after this if possible later.

BRs

2021-04-13 06:32 UTC, trociny commented
> While for now, this approach maybe a very good start for this feature IMHO, and let's make it more generic after this if possible later.

When added to rbd-nbd it will be difficult to remove later as it may already be used so we will have to maintain both.

My actual proposal it to move the current implementation from `rbd-nbd` to `rbd` (tools/rbd/action/Device.cc). So, instead of calling `rbd-nbd restore` you could call `rbd device restore --device-type ndb`. And if it is not trivial to add support for other device types you can just can make commands return EOPNOTSUPP for now, just make it work for rbd-nbd. @pkalever do you see problems with this?

2021-04-13 07:38 UTC, idryomov commented
Honestly, I'm confused by the description of the problem:

> But in case if the node is rebooted, there is no way to restore the nbd device mappings and one has to do remap of the big list of devices manually. This is a serious problem in container environments, if the container hosting the rbd-nbd processes is restarted, all the mapping is just gone and The application will start seeing the IO errors.

If the node is rebooted, there won't be any applications there.  When the node is back, a static list of mappings in `rbdmap`-like format should be enough.  Extending `rbdmap` script to handle nbd is trivial, no `rbd` or `rbd-nbd` changes needed.

If the container hosting `rbd-nbd` processes is restarted, but the node is not rebooted, that's an entirely different use case.  Which one is being targeted here?

2021-04-14 11:35 UTC, pkalever commented
Hello @trociny,

It was a holiday for me yesterday, sorry for my delayed response.


#### Reply on comment 1:


> @pkalever Was it discussed earlier in Ceph community before you started working on this?

This is my first contribution to ceph, I'm unaware of the pattern, so excuse me if this feature appears as a surprise.
And, thanks for the info, I will make sure to bring it up in the community meetings if there are any major changes from me in the future.

> 
> Because, although the feature looks useful to me and you did a great job here, I hate to say, I am not sure it is the right approach.
> 
> It seems like it could be done on a higher layer, keeping the rbd-nbd simple. Moreover, it could be more generic, so it could also handle krbd and FreeFSD's rbd-ggate.
> 
> We tried to make these drivers provide similar interface so you could use `rbd device map|unmap|list -t <device-type>` and it would work in similar way for `kernel`, `nbd`, and `ggate` types.
> 

This certainly sounds cool, and it's very much understandable that one simple interface is what we expect.


> The functionality provided here resembles `rbdmap` [1] we have for krbd. And we actually have a feature request to make it generic and work not only for rbdmap [2, 3], and @lxbsz seemed to start working on it, although I have no idea if there have been any progress so far. I don't say we have to stick to rbdmap (I have never used personally) but it would be great if we came with something more generic. Probably you could just move your code from `rbd-nbd` to `rbd`?

I haven't heard of rbdmap tool before, on first glance I see it's a script, and IMHO that will not be enough in the long run.
Expect the response to the second part of the question below.

> 
> Note, it is just my humble opinion though. I would love to see what other people think about it. That is why I asked if there were some discussion about this.
> 


#### Reply on comment 2:



> When added to rbd-nbd it will be difficult to remove later as it may already be used so we will have to maintain both.
> 
> My actual proposal it to move the current implementation from `rbd-nbd` to `rbd` (tools/rbd/action/Device.cc). So, instead of calling `rbd-nbd restore` you could call `rbd device restore --device-type ndb`. And if it is not trivial to add support for other device types you can just can make commands return EOPNOTSUPP for now, just make it work for rbd-nbd. @pkalever do you see problems with this?

Thanks for welcoming the changes.

Also, thanks for the hint, I looked at tools/rbd/action/Device.cc, and here is what I understand at my first glance:
Device.cc is like top layer generic CLI parser, which tries to accept the CLI commands from various backend device types (Kernel, Nbd, Ggate, ... etc.), but the specific device level additional options (which are uncommon) are still parsed at the respective src/tools/rbd/action/Nbd.cc, src/tools/rbd/action/Ggate.cc, etc. Also noticed that the generic rbd CLI interface is forking a subprocess, calling the specific backend device level CLI process (at least with nbd, gate) (hence will have to go through another round of parsing in the respective individual CLI's)

Coming back to the changes w.r.t this PR, which is the `restore` of mapping on restart of node (and pod in container env), I think we are dealing with saving various options per device which is subject to a given device type. If that is the case, I think we should leave the logic of all the details that the specific device type wants to save per device in the saveconfig.json to that device type-specific code. And for simplicity, integrate the new CLI level restore option with the generic rbd CLI interface.


That said, at some point in time we should deprecate the individual CLI's (rbd-nbd, rbd-ggate, etc) and for that, we need to start preparing our users to adapt to the upcoming integrated CLI changes, this way we will stop duplicating the CLI parsing logic in the individual CLI's and generic CLI.

One example, not to point out or hurt anyone, rather just to give an example, the `recent` attach command to nbd was a great value-added feature, and I see its integration is missing at the generic CLI interface. This is the problem that we will end up with by maintaining both generic CLI and individual CLIs.


@trociny, great comments!! I'm happy to get corrected and/or hear your further thoughts.

2021-04-14 11:54 UTC, pkalever commented
Hello @idryomov 

> Honestly, I'm confused by the description of the problem:
> 
> > But in case if the node is rebooted, there is no way to restore the nbd device mappings and one has to do remap of the big list of devices manually. This is a serious problem in container environments, if the container hosting the rbd-nbd processes is restarted, all the mapping is just gone and The application will start seeing the IO errors.
> 
> If the node is rebooted, there won't be any applications there. When the node is back, a static list of mappings in `rbdmap`-like format should be enough. Extending `rbdmap` script to handle nbd is trivial, no `rbd` or `rbd-nbd` changes needed.
> 
> If the container hosting `rbd-nbd` processes is restarted, but the node is not rebooted, that's an entirely different use case. Which one is being targeted here?

To be honest, when I started working on this, with this approach I was trying to address both cases you have listed above [although my primary goal was to fix the containers one].

But, thanks for highlighting this, I just realized that I forget to add a force option upon which the `rbd-nbd restore` should attempt to do a fresh `map` (ignoring the recoded device number) instead of `attach`. I will fix this part with the next respin. Also as you pointed it confusing, I shall try to re-frame the problem statement with the next respin.

Cheers!

2021-04-14 12:29 UTC, idryomov reviewed
Before you respin, I think we need to discuss whether adding this functionality to `rbd-nbd` is a good idea.  So far, I don't see any reason this couldn't be done externally by (an equivalent of) a simple shell script.  Since you said that the container restart case was the primary goal, let's focus on it.  The reboot case should be taken care of by #40844.  Some questions to kick off the discussion:

- What is achieved by storing the mapping details at map time?  Could you just grab `rbd device list` output before restarting the container?  If not, what is missing from `rbd device list` output?

- What is the use case for partial restoring (i.e. filtering by device node and image spec)?

- What is achieved by having `rbd-nbd` do the restore (i.e. fork itself for each device, etc)?  Could whoever grabbed `rbd device list` output just iterate through it and call `rbd-nbd attach` for each entry?

2021-04-14 13:46 UTC, pkalever commented
> Before you respin, I think we need to discuss whether adding this functionality to `rbd-nbd` is a good idea. So far, I don't see any reason this couldn't be done externally by (an equivalent of) a simple shell script. Since you said that the container restart case was the primary goal, let's focus on it. The reboot case should be taken care of by #40844. Some questions to kick off the discussion:

Sure I will wait until I see an ack on the approach from you or @trociny or @lxbsz 

> 
> * What is achieved by storing the mapping details at map time?  Could you just grab `rbd device list` output before restarting the container?  If not, what is missing from `rbd device list` output?

A more meaningful understanding can be achieved if we visualize the problem from container setups. Let me take you through it:
- In container environments, the rbd-nbd processes will be run inside the container (not on node), so if the container hosting the rbd-nbd processes is restarted, then all the rbd-nbd processes are terminated. So post the container restart the `rbd-nbd list` will result in empty!
- As we cannot always predict when the container is restarted, it's not possible to capture the `list` output prior in time.
- Also the user may pass various options to rbd-nbd at map time, not all will be listed with `list`


> * What is the use case for partial restoring (i.e. filtering by device node and image spec)?

- In simple terms, the restore/map request call in Ceph-CSI is per device and is not like one-shot restore per node.
**In detail:**
With Ceph-CSI, upon restart of the node plugin pod (pod which runs the rbd-nbd and also is responsible to attach/map and mount the device), ideally, the sidecar which talk to Kubernetes gets the list of VolumeAttachments (mounts/devices) that need to be reattached per node. For each RBD device, a new NodeStageVolume call will be sent to the Ceph-CSI container.
The main Ceph-CSI container on the node will need to handle the NodeStageVolume call by calling `rbd-nbd restore` with respective image-spec and all other various options per device.
It's also important to note this is how Kubernetes expect its CSI calls to get handled, nothing to do with ceph-CSI in specific.

- Also we cannot restore every device because, we never know, in the meanwhile some application pods (nbd mounts) might have got migrated to a new node, which means we don't have to restore/reattach them.


> * What is achieved by having `rbd-nbd` do the restore (i.e. fork itself for each device, etc)?  Could whoever grabbed `rbd device list` output just iterate through it and call `rbd-nbd attach` for each entry?

Right, if we want someone to read the saveconfig.json and execute the `attach` commands, then that will become a new tool again. And we have to take the additional responsibility for maintaining compatibility between the new tool and rbd-nbd every time we make some changes to the rbd-nbd options.

Thanks!

2021-04-14 14:39 UTC, wjwithagen commented
I'm just a simple soul that likes KISS.
And not understanding the full details for the containerization I feel that the lower level rbd-mounters should not not be bothered with the administrative tools.

This sound horribly to a sort of `fstab` for rbd images, and when the Kubernites process maintains this file, I think does exactly what is meant for. Where I would use the `rbd` tool like `mount` to process the `rbdmap` file.

2021-04-14 14:58 UTC, idryomov commented
> As we cannot always predict when the container is restarted, it's not possible to capture the list output prior in time.

Is that really the case?  I might be missing some k8s / CSI spec detail here, but I would argue that if the container gets killed (as opposed to being gracefully restarted for an upgrade), we shouldn't be restoring anything.  I mean, `rbd-plugin` pod is special, it can't be treated like a throwaway container that can just be killed at any time...  And on graceful restart, it should be possible to capture `rbd device list` output or similar.

> Also the user may pass various options to rbd-nbd at map time, not all will be listed with list

This can be addressed fairly easily.

> Also we cannot restore every device because, we never know, in the meanwhile some application pods (nbd mounts) might have got migrated to a new node, which means we don't have to restore/reattach them.

I see, thanks for the explanation.

> Right, if we want someone to read the saveconfig.json and execute the attach commands, then that will become a new tool again. And we have to take the additional responsibility for maintaining compatibility between the new tool and rbd-nbd every time we make some changes to the rbd-nbd options.

I don't see anything wrong with a new tool.  This tool would be using exactly one command, `rbd-nbd attach`, which should be stable.  The equivalent `rbd map` and related commands have remained largely the same and backwards compatible for about ten years.

Also, I'm not saying that this tool (a script, really) must be maintained outside of Ceph.  It can very well be part of Ceph, just not part of `rbd` or `rbd-nbd`.

2021-04-14 15:00 UTC, idryomov commented
> This sound horribly to a sort of `fstab` for rbd images, and when the Kubernites process maintains this file, I think does exactly what is meant for. Where I would use the `rbd` tool like `mount` to process the `rbdmap` file.

I'm having trouble parsing this paragraph ;)

2021-04-14 15:26 UTC, wjwithagen commented
> 
> 
> > This sound horribly to a sort of `fstab` for rbd images, and when the Kubernites process maintains this file, I think does exactly what is meant for. Where I would use the `rbd` tool like `mount` to process the `rbdmap` file.
> 
> I'm having trouble parsing this paragraph ;)

Sorry about that....

The file that is maintained is actually a receipt to connect to all rbd images, just as fstab tells you where to mount the storage devices. Mount is the all-purpose entry used to execute the rules in /etc/fstab. And that handles all kinds of device and per device different options. YNow you can use `mount_nfs <params>` but normally you'd call it like `mount -t nfs <params>`,

And what we are talking about is just the same, but now its about RBD images and mounting to a device that it was previously mounted to. Could be a file structure similar to fstab.

So why not use `rbd` as the frontend for all this: `rbd -f /etc/rbdmap mount`.

2021-04-14 16:00 UTC, pkalever commented
> > Also the user may pass various options to rbd-nbd at map time, not all will be listed with list
> 
> This can be addressed fairly easily.

Just out of my curiosity,
Do you mean to capture various `map` options per device within the output of `rbd-nbd list`?

like:
```
  --device <device path>        Specify nbd device path (/dev/nbd{num})
  --encryption-format           Image encryption format
                                (possible values: luks1, luks2)
  --encryption-passphrase-file  Path of file containing passphrase for unlocking image encryption
  --exclusive                   Forbid writes by other clients
  --io-timeout <sec>            Set nbd IO timeout
  --max_part <limit>            Override for module param max_part
  --nbds_max <limit>            Override for module param nbds_max
  --quiesce                     Use quiesce callbacks
  --quiesce-hook <path>         Specify quiesce hook path
                                (default: libexec/rbd-nbd/rbd-nbd_quiesce)
  --read-only                   Map read-only
  --reattach-timeout <sec>      Set nbd re-attach timeout
                                (default: 30)
  --try-netlink                 Use the nbd netlink interface
---
  --conf/-c FILE    read configuration from the given configuration file
  --id/-i ID        set ID portion of my name
  --name/-n TYPE.ID set name
  --cluster NAME    set cluster name (default: ceph)
  --setuser USER    set uid to user or uid (and gid to user's gid)
  --setgroup GROUP  set gid to group or gid
  --version         show version and quit

  -d                run in foreground, log to stderr
  -f                run in foreground, log to usual location
```

> 
> > Also we cannot restore every device because, we never know, in the meanwhile some application pods (nbd mounts) might have got migrated to a new node, which means we don't have to restore/reattach them.
> 
> I see, thanks for the explanation.
> 
> > Right, if we want someone to read the saveconfig.json and execute the attach commands, then that will become a new tool again. And we have to take the additional responsibility for maintaining compatibility between the new tool and rbd-nbd every time we make some changes to the rbd-nbd options.
> 
> I don't see anything wrong with a new tool. This tool would be using exactly one command, `rbd-nbd attach`, which should be stable. The equivalent `rbd map` and related commands have remained largely the same and backwards compatible for about ten years.

I mean to say, if we have to introduce a new tool to read the saveconfig.json (data that we are storing at the time of map) captured by `rbd-nbd map`, won't it be additional maintenance. Rather, I don't see anything wrong in `rbd-nbd` or `rbd` reading the file that was created by itself.

Why should this go into a script when we have a lot of control with the `rbd/rbd-nbd` itself? 

> 
> Also, I'm not saying that this tool (a script, really) must be maintained outside of Ceph. It can very well be part of Ceph, just not part of `rbd` or `rbd-nbd`.

If we are stressing on a more generic way for organizing this mapping, the go-to way is:

- top level rbd interface (May be Device.CC) implement `restore` command
- src/tools/rbd/action/Nbd.cc, src/tools/rbd/action/Ggate.cc, src/tools/rbd/action/Kernel.cc ...etc. -> let the individual device types decide the logic on what to store/retreive from the saveconfig.json per device.
- And on `rbd device restore -t <type>` Let the `rbd` itself parse through the various JSON objects and format the device level commands and fork (very like what is done for `rbd device map -t <type>` now)

Thanks!

2021-04-15 15:29 UTC, trociny commented
> This is my first contribution to ceph, I'm unaware of the pattern, so excuse me if this feature appears as a surprise.
> And, thanks for the info, I will make sure to bring it up in the community meetings if there are any major changes from me in the future.

You are completely free to do it in a way you want. It just will be sad if after the discussion it will turn out you will have to do many changes or even chose another approach. Discussing this in advance allows to avoid this.

2021-04-15 15:34 UTC, trociny commented
> One example, not to point out or hurt anyone, rather just to give an example, the `recent` attach command to nbd was a great value-added feature, and I see its integration is missing at the generic CLI interface. This is the problem that we will end up with by maintaining both generic CLI and individual CLIs.

At the time when attach was added it was not clear how useful it would be and how it would be used, so we decided not to provide it via `rbd` yet. But if you think it would be useful, I don't see much problems with extending it.

2021-04-16 13:48 UTC, pkalever commented
Hello @trociny 

> > * src/tools/rbd/action/Nbd.cc, src/tools/rbd/action/Ggate.cc, src/tools/rbd/action/Kernel.cc ...etc. -> let the individual device types decide the logic on what to store/retreive from the saveconfig.json per device.
> 
> I don't quite understand why you need this special handling per device type? Why can't you just save everything that was passed as arguments when map was called and succeeded and then restore everything that was saved? I guess there is some complication but I would like to know, probably it could be solved some other way.

Adding the per device config in a [ {key1: value1, key2: value2, ...} ] fashion gives us more flexibility while retrieving the data from the JSON file.
For example:
* when restoring the list of devices or even when restoring a single device parsing though the objects become simple, we can get the matching device number or matching image ID very easily.
* Also, if you see the code, we don't save every argument mentioned at the CLI (this not only saves some space), we only store non defaults. This helps, if in future versions if we add new defaults (say older default of an argument is 30, but later version made it to 60) the config files will still honor the new defaults (because the default values are always read from the code).
* Also say if an argument is deprecated, although it's present in the config file it won't terminate the command (saying arg unknown) because the code just ignores or not uses it from config, this is very unlikely honored if we dump the CLI command directly as one single string to the config file.


---


> > This is my first contribution to ceph, I'm unaware of the pattern, so excuse me if this feature appears as a surprise.
> > And, thanks for the info, I will make sure to bring it up in the community meetings if there are any major changes from me in the future.
> 
> You are completely free to do it in a way you want. It just will be sad if after the discussion it will turn out you will have to do many changes or even chose another approach. Discussing this in advance allows to avoid this.

Yes, I completely agree and respect your point.

----

> > One example, not to point out or hurt anyone, rather just to give an example, the `recent` attach command to nbd was a great value-added feature, and I see its integration is missing at the generic CLI interface. This is the problem that we will end up with by maintaining both generic CLI and individual CLIs.
> 
> At the time when attach was added it was not clear how useful it would be and how it would be used, so we decided not to provide it via `rbd` yet. But if you think it would be useful, I don't see much problems with extending it.

That was just an example, but now I get why it was letf out.
Sure I will send the PR to extend the `attach` command to rbd interface sometime next week.


Thanks!

2021-04-16 14:54 UTC, trociny commented
> Adding the per device config in a [ {key1: value1, key2: value2, ...} ] fashion gives us more flexibility while retrieving the data from the JSON file.
> For example:
> 
> * when restoring the list of devices or even when restoring a single device parsing though the objects become simple, we can get the matching device number or matching image ID very easily.

Valid point about `device`, as it is rbd-specific option and we need it for attach when restoring. The image spec seems not necessary, can be passed as is. Or at least it does not depend on a device type so could be handled in generic way if needed.

> * Also, if you see the code, we don't save every argument mentioned at the CLI (this not only saves some space), we only store non defaults. This helps, if in future versions if we add new defaults (say older default of an argument is 30, but later version made it to 60) the config files will still honor the new defaults (because the default values are always read from the code).

It is rather strange to me. If I specify an option via command line (or config) I don't care if the value matches the default or not, it means I always want this value, even (especially) if the default is changed.

> * Also say if an argument is deprecated, although it's present in the config file it won't terminate the command (saying arg unknown) because the code just ignores or not uses it from config, this is very unlikely honored if we dump the CLI command directly as one single string to the config file.

After deprecating an argument we still keep it for several releases as NOP, so there should not be problems with it after upgrade.

So, I still don't see problems with just storing all options provided on map and using them with attach on restore. The only issue is with the `device` option, which is not generic (rbd-nbd specific) may be provided on map but not necessary, but should be provided on `attach`. When storing on map, we may learn the device from what map returns, and use it as the key (index) when storing in the file, i.e. 'dev : [options]'. Or we might want to make `--device` mandatory for `map` if `--save` option is used.

It might be helpful here to see how you are going to implement generic `rbd attach|detach` (as it looks like you have plans for this). Because we might want to make `--device` generic for all types and this will be helpful for save/restore case too. Or we may want it as a positional argument here: `rbd attach <device> <image_spec>`...

Anyway, this is just my suggestions to make it more generic.

I still would prefer if save/restore was handled on a higher level, i.e. by the THING that does map. If not here, then `rbd` is better than `rbd-nbd`. But this is just my opinion. I will not have objection to have this in `rbd-nbd`, just will not like it much, as it does not look like its job.

2021-04-16 15:38 UTC, pkalever commented
@trociny 
Most of the points make sense to me. Just to add some clarification on my previous comments, I didn't mean to say, saving everything that was passed as arguments doesn't work here. I was just trying to highlight the fact that saving individual arguments separately per device has its own advantages and flexibility as mentioned above.

But If we want to take a more generic approach for saving the config by avoiding device type level logic, then dumping the command strings to the config file might work. We can have one config-file, like:

```
{
   "nbd":[
      {
         "cmd":"rbd-nbd-pool/image1 --try-netlink --reattach-timeout 350",
         "type-specific":"--device /dev/nbd0"
      },
      {
         "cmd":"rbd-nbd-pool/image2 --try-netlink --reattach-timeout 350",
         "type-specific":"--device /dev/nbd1"
      }
   ],
   "kernel":[
      {
         "cmd":"rbd-pool/image1  --id client --keyring /etc/ceph/ceph.client.keyring",
         "type-specific":"xyz option"
      },
      {
         "cmd":"rbd-pool/image2  --id client --keyring /etc/ceph/ceph.client.keyring",
         "type-specific":"xyz option"
      }
   ],
   "ggate":[
      {
         "cmd":"bla bla1",
         "type-specific":"xyz option"
      },
      {
         "cmd":"bla bla 2",
         "type-specific":"xyz option"
      }
   ],
   "wnbd":[
      {
         "cmd":"bla wnbd1",
         "type-specific":"xyz option"
      },
      {
         "cmd":"bla bla 2",
         "type-specific":"xyz option"
      }
   ]
}
```

(For github PR history context purpose) The current implementation as per this PR (nbd specific) looks like this:
```
{                                             
    "devices" : [                             
        {                                     
            "image_spec" : "rbd-pool/image1", 
            "device" : "/dev/nbd0",           
            "try_netlink" : true,             
            "reattach_timeout" : 350          
        },                                    
        {                                     
            "image_spec" : "rbd-pool/image2", 
            "device" : "/dev/nbd1",           
            "try_netlink" : true,
            "quiesce": true,             
            "reattach_timeout" : 350,
            "encryption_format": 1,
            "encryption_passphrase_file": "/some-path",
            "io_timeout": 120,
            "max_part": 100
        }                                     
    ]                                         
}                                             
```

I welcome your thoughts.

Thanks!

2021-04-17 06:53 UTC, trociny commented
> {
>    "nbd":[
>       {
>          "cmd":"rbd-nbd-pool/image1 --try-netlink --reattach-timeout 350",
>          "type-specific":"--device /dev/nbd0"
>       },
>       {
>          "cmd":"rbd-nbd-pool/image2 --try-netlink --reattach-timeout 350",
>          "type-specific":"--device /dev/nbd1"
>       }
>    ],
>    "kernel":[

I think you can do it in any way that is convenient for you to store and then retrieve and pass to attach. Just some suggestions:

I would probably have a separate file per device type, so you would not need to have this additional level in the file.

I don't like very much that it is stored in /etc. Why not somewhere in /var/lib/ceph? I used to use /etc for "real" configs only, and it might be read-only.

As we will always want the device to reattach I would use the device as the main key, i.e. it would be something like:
```
{
  "/dev/nbd0" : {options},
  "/dev/nbd1" : {options}, 
  ...
}
```

If we decide to do this save/restore with `rdb` (rbd/action/Device.cc), then I would look how it was going to be used. Right now we map with:
```
int execute_map(const po::variables_map &vm,
                const std::vector<std::string> &ceph_global_init_args) {
  return (*get_device_operations(vm)->execute_map)(vm, ceph_global_init_args);
}
```
I suppose it could be changed to something like:
```
int execute_map(const po::variables_map &vm,
                const std::vector<std::string> &ceph_global_init_args) {
  std::string dev;
  int r = (*get_device_operations(vm)->execute_map)(vm, ceph_global_init_args, &dev);
  if (r < 0){
    return;
  }
  if (saveconfig) {
    save_config(dev, vm, ceph_global_init_args);
  }
  std::cout << dev << std::endl;
  return 0;
}
```
So `save_config` would pack `vm` and `ceph_global_init_args`, and on restore,  `restore_config` would give them back into `dev`, `vm`, and `ceph_global_init_args`, and you would call the attach like:
```
r = (*get_device_operations(vm)->execute_attach)(dev, vm, ceph_global_init_args);
```
I may be wrong in details, and I don't insist on this approach in any way. And before starting doing it I would like we agree that we do want to do this in `rbd device`.

2021-04-17 07:28 UTC, pkalever commented
> I think you can do it in any way that is convenient for you to store and then retrieve and pass to attach. Just some suggestions:
> 
> I would probably have a separate file per device type, so you would not need to have this additional level in the file.

I'm not a favorite to have a single file, I'm ok to make it a split (per device type)

> 
> I don't like very much that it is stored in /etc. Why not somewhere in /var/lib/ceph? I used to use /etc for "real" configs only, and it might be read-only.

sure, I was expecting a suggestion about the path, I will adopt /var/lib/ceph/config/ or something similar

> 
> As we will always want the device to reattach I would use the device as the main key, i.e. it would be something like:
> 
> ```
> {
>   "/dev/nbd0" : {options},
>   "/dev/nbd1" : {options}, 
>   ...
> }
> ```

Let's say if the device is detached (process crashed or force terminated) and didn't get attached within the reattached timeout range, then the device number might be lost and some other image-spec might get the same device number, right? In that case, we might override the options with new image-spec details.

Also let say, if we have to use the image-spec as the key, then 2 or more processes can use the same image-spec to map (I don't know if this is intentional or a bug)

I thought about this, and mentioned `cmd` as key, but I like if `device` or `image_spec` is a key, may be this needs some discussion.



> 
> If we decide to do this save/restore with `rdb` (rbd/action/Device.cc), then I would look how it was going to be used. Right now we map with:
> 
[...]
> 
> I may be wrong in details, and I don't insist on this approach in any way. And before starting doing it I would like we agree that we do want to do this in `rbd device`.

Sure, I don't have any problem in moving this code logic to Device.cc i.e. support this with `rbd device` command.
And I will keep your code level suggestion in mind and revisit this when I start coding on it.



Thanks @trociny

2021-04-17 09:21 UTC, trociny commented
> Let's say if the device is detached (process crashed or force terminated) and didn't get attached within the reattached timeout range, then the device number might be lost and some other image-spec might get the same device number, right? In that case, we might override the options with new image-spec details.

I know a little about the use case (just some assumptions), but how it is going to be used if the device may change? This looks like not very sane to me. How the user (the consumer of the nbd device) will be sure it is still its own image?

I am thinking that we might even want to allow `rbd map --save-config` only if also `--device` is specified explicitly? So the user should know (reserve) the device in advance?

> Also let say, if we have to use the image-spec as the key, then 2 or more processes can use the same image-spec to map (I don't know if this is intentional or a bug)

Yes, we don't forbid this, and I can image cases when it may be useful, at least for testing. But you may introduce this restriction for `--save-config` case, if you really want it and fits your use case (which, again, I know little about).

> I thought about this, and mentioned `cmd` as key, but I like if `device` or `image_spec` is a key, may be this needs some discussion.

Ok. Actually just reading what you wrote about the use case [1], I am starting to worry if Ceph-CSI is doing right things. I don't see why it is using `attach` on pod restart? `unmap`/`map` seems the right approach here.

`attach` is needed only if you want to restart `rbd-nbd` process by some reason without restarting the pod, which I suppose is safe (and useful) when upgrading rbd-nbd, and may be in some other circumstances, but in general the usage case is rather limited. Even restarting (reattaching) rbd-nbd when it died without need to restart the pod, although looks useful, I don't know how sane it is. It may work and probably may be useful, but I am not sure the consumer (the fs on top the nbd device) will always be able to handle such reattaches after the crash (I have never investigated that case yet though).

Probably Ceph-CSI uses attach because it does not use unmap but just kill rbd-ndb process, and then on `map` it will take another device while you would prefer the old one for some reasons? Then `attach` will do the trick, though it does not look safe as map in general case.

Anyway, thinking about the use case I am not sure am quite understand why we need this save/restore functionality on rbd side, it seems Ceph-CSI could do it itself if it really needs it? Could you please explain once more the real usage case scenario, how it is going to be used?

[1] https://github.com/ceph/ceph/pull/40809#issuecomment-819530878

2021-04-17 12:01 UTC, idryomov commented
> Anyway, thinking about the use case I am not sure am quite understand why we need this save/restore functionality on rbd side, it seems Ceph-CSI could do it itself if it really needs it? Could you please explain once more the real usage case scenario, how it is going to be used?

Very much agree.  Here are my thoughts:

- `rbd-nbd attach` is horrendously easy to misuse.  There is no safety catch, you can attach any `rbd-nbd` instance to any device.  Here is one example:

  ```
  $ sudo rbd-nbd map --try-netlink rbd/ext4-image
  /dev/nbd0
  $ sudo blkid /dev/nbd0
  /dev/nbd0: UUID="bfc444b4-64b1-418f-8b36-6e0d170cfc04" TYPE="ext4"
  $ sudo pkill -9 rbd-nbd
  $ sudo rbd-nbd attach --try-netlink --device /dev/nbd0 rbd/xfs-image
  /dev/nbd0
  $ sudo blkid /dev/nbd0
  /dev/nbd0: UUID="d29bf343-6570-4069-a9ea-2fa156ced908" TYPE="xfs"
  ```
  
  If ext4 on `rbd/ext4-image` was mounted, the kernel crash is really the best you can hope for at that point.  If it doesn't crash right away, XFS on `rbd/xfs-image` would get corrupted.  If there was an application using `/dev/nbd0` directly (as a raw block PV), it wouldn't be happy either.

  I don't think we should be attempting to generalize such dangerous functionality.  Wrapping it into a new `restore` action would make shooting yourself in the foot even easier IMO: the user can supply the wrong `saveconfig` file, the default one may get out of sync, etc.  Even if we add some restrictions such as saving the mapping only if `--device` is specified, etc someone out there would definitely get burned and potentially lose their data.

  In contrast, ceph-csi is a tightly controlled environment.  It already takes a bunch of shortcuts, uses some rather dangerous `mkfs.ext4` options, etc precisely because the image, from how it is created, optionally formatted, mapped and all the way to how it is deleted is never exposed to the user.  Building on that, ceph-csi could use `rbd-nbd attach` in a fairly safe manner.

- a single `saveconfig` file isn't going to work in the general case.  Sooner or later two racing mappings/unmappings would corrupt it, so you either need some locking mechanism, or a directory with a file per mapping or a proper database.  We can't predict what different users would do and when.  OTOH ceph-csi has a single entity (the plugin pod) handling all mapping and unmapping actions on the node -- there should be no concurrency issues there.

- `krbd` doesn't have a concept of attach/reattach.  The kernel is in charge of handing out devices.  Looking at `ggate`, I don't see a separate "pick a device" step, so it seems similar to `krbd` in this regard.  So, if promoted to `rbd device`, the `attach` or the proposed `restore` actions would still be specific to `nbd`.

To sum up, my impression is that this can and should be implemented entirely in ceph-csi.  In an earlier comment I said that we could extend `rbd device list` to also dump mapping options, but I don't think even that is needed.  The plugin could just record the command line arguments (that it itself generates!) and pass them to `rbd-nbd attach` later.

2021-04-17 12:24 UTC, idryomov commented
@wjwithagen 

> The file that is maintained is actually a receipt to connect to all rbd images, just as fstab tells you where to mount the storage devices. Mount is the all-purpose entry used to execute the rules in /etc/fstab. And that handles all kinds of device and per device different options. YNow you can use `mount_nfs <params>` but normally you'd call it like `mount -t nfs <params>`,
> 
> And what we are talking about is just the same, but now its about RBD images and mounting to a device that it was previously mounted to. Could be a file structure similar to fstab.

The difference is that `/etc/fstab` is static, maintained by the administrator.  We have something similar, `/etc/ceph/rbdmap`.

What is being proposed is dynamic and in filesystem terms would be more like "go and mount the filesystems I had mounted at a random point in the past", except that block device mappings don't work the same way as mount points -- you can't map one block device "on top" of another (i.e. to the same device node).  See my previous comment on ensuing data corruption and concurrency issues.

Do you know if `ggate` allows a user to pick a device to map to?

2021-04-17 12:25 UTC, idryomov requested changes
This needs a design discussion before going any further.

2021-04-17 13:00 UTC, trociny commented
> Do you know if `ggate` allows a user to pick a device to map to?

Yes, it is possible.

2021-04-17 14:17 UTC, idryomov commented
Yeah, I saw that it takes an optional `--device`.  Sorry, what I meant to ask is if it allows to pick a device to *(re)attach* to.  Does it behave similarly to `nbd` where no explicit release step appears to be necessary if the daemon is gone or is it safe and won't allow to attach to a device that hasn't been properly released?

2021-04-17 14:19 UTC, pkalever commented
@trociny 

> > I thought about this, and mentioned `cmd` as key, but I like if `device` or `image_spec` is a key, may be this needs some discussion.
> 
> Ok. Actually just reading what you wrote about the use case [1], I am starting to worry if Ceph-CSI is doing right things. I don't see why it is using `attach` on pod restart? `unmap`/`map` seems the right approach here.
> 
> `attach` is needed only if you want to restart `rbd-nbd` process for some reason without restarting the pod, which I suppose is safe (and useful) when upgrading rbd-nbd, and may be in some other circumstances, but in general the usage case is rather limited. Even restarting (reattaching) rbd-nbd when it died without the need to restart the pod, although looks useful, I don't know how sane it is. It may work and probably may be useful, but I am not sure the consumer (the fs on top the nbd device) will always be able to handle such reattaches after the crash (I have never investigated that case yet though).
> 
> Probably Ceph-CSI uses attach because it does not use unmap but just kill rbd-ndb process, and then on `map` it will take another device while you would prefer the old one for some reasons? Then `attach` will do the trick, though it does not look safe as map in general case.
> 
> Anyway, thinking about the use case I am not sure am quite understand why we need this save/restore functionality on rbd side, it seems Ceph-CSI could do it itself if it really needs it? Could you please explain once more the real usage case scenario, how it is going to be used?
> 
> [1] [#40809 (comment)](https://github.com/ceph/ceph/pull/40809#issuecomment-819530878)

Think it like, the ceph-csi calls `rbd-nbd map` when the new app pod creation request is made using the given volume name (PVC), and it does the `unmap` when the pod is deleted.

`attach` is needed at the time of the node-plugin pod (which runs rbd-nbd processes) upgrades or just for any random restart of the node-plugin pod. Think the node-plugin pod restart just like an ungraceful rbd-nbd process terminate (nothing more or less), the nbd device is used by application pod, which will be still in running state, meaning the IO is ongoing.

That said, we need a `attach` command here rather than `map` because we do not want to drop the inflight IO. Hope that answers it all.

Thanks!

2021-04-17 14:28 UTC, pkalever commented
@idryomov 

> > Anyway, thinking about the use case I am not sure am quite understand why we need this save/restore functionality on rbd side, it seems Ceph-CSI could do it itself if it really needs it? Could you please explain once more the real usage case scenario, how it is going to be used?
> 
> Very much agree. Here are my thoughts:
> 
> * `rbd-nbd attach` is horrendously easy to misuse.  There is no safety catch, you can attach any `rbd-nbd` instance to any device.  Here is one example:
>   ```
>   $ sudo rbd-nbd map --try-netlink rbd/ext4-image
>   /dev/nbd0
>   $ sudo blkid /dev/nbd0
>   /dev/nbd0: UUID="bfc444b4-64b1-418f-8b36-6e0d170cfc04" TYPE="ext4"
>   $ sudo pkill -9 rbd-nbd
>   $ sudo rbd-nbd attach --try-netlink --device /dev/nbd0 rbd/xfs-image
>   /dev/nbd0
>   $ sudo blkid /dev/nbd0
>   /dev/nbd0: UUID="d29bf343-6570-4069-a9ea-2fa156ced908" TYPE="xfs"
>   ```
>   
>   If ext4 on `rbd/ext4-image` was mounted, the kernel crash is really the best you can hope for at that point.  If it doesn't crash right away, XFS on `rbd/xfs-image` would get corrupted.  If there was an application using `/dev/nbd0` directly (as a raw block PV), it wouldn't be happy either.
>   I don't think we should be attempting to generalize such dangerous functionality.  Wrapping it into a new `restore` action would make shooting yourself in the foot even easier IMO: the user can supply the wrong `saveconfig` file, the default one may get out of sync, etc.  Even if we add some restrictions such as saving the mapping only if `--device` is specified, etc someone out there would definitely get burned and potentially lose their data.
>   In contrast, ceph-csi is a tightly controlled environment.  It already takes a bunch of shortcuts, uses some rather dangerous `mkfs.ext4` options, etc precisely because the image, from how it is created, optionally formatted, mapped and all the way to how it is deleted is never exposed to the user.  Building on that, ceph-csi could use `rbd-nbd attach` in a fairly safe manner.

Thanks for the real-world example, storing the device numbers and their UUID (from blkid or /dev/disk/by-uuid/) is a must for `attach` command, to avoid such kinds of corruption and loss of data.

So on `map` we should store the `device-number:<UUID>` in the config and on the next `attach` command we should verify the UUID of the received device-number (from command args), if it is matching only then we proceed for `attach` operation. I see a need for such kind of device-number to UUID validation even for the non-container use case.


> * a single `saveconfig` file isn't going to work in the general case.  Sooner or later two racing mappings/unmappings would corrupt it, so you either need some locking mechanism, or a directory with a file per mapping or a proper database.  We can't predict what different users would do and when.  OTOH ceph-csi has a single entity (the plugin pod) handling all mapping and unmapping actions on the node -- there should be no concurrency issues there.

Yes we can keep the files separate, while performing creates/deletes of entries in the config, taking a blocking lock on the file itself (fcntl) should be good enough, as the save/remove object operation is not time taking, I don't see a potential problem.

> * `krbd` doesn't have a concept of attach/reattach.  The kernel is in charge of handing out devices.  Looking at `ggate`, I don't see a separate "pick a device" step, so it seems similar to `krbd` in this regard.  So, if promoted to `rbd device`, the `attach` or the proposed `restore` actions would still be specific to `nbd`.

I agree krbd doesn't need `attach`, but it can still get benefited from this dynamic config file for performing remapping for all or partial devices at any given time. And of course, as @trociny mentioned ggate might get benefited from this too.

>This needs a design discussion before going any further.

Sure, anytime.

Thanks!

2021-04-17 15:07 UTC, idryomov commented
> So on map we should store the device-number:<UUID> in the config and on the next attach command we should verify the UUID of the received device-number (from command args), if it is matching only then we proceed for attach operation. I see a need for such kind of device-number to UUID validation even for the non-container use case.

I'm not entirely sure what you mean by `device-number`, but if it is a `major:minor` pair then it won't work because major and minor numbers won't change.  These device nodes are created statically and exist independent of whether something is attached.  If `/dev/nbd0` was `43:0` for image `rbd/ext4-image`, it will stay `43:0` after an improper attach of `rbd/xfs-image`.

For UUID, an image that has just been created and mapped won't have a UUID because there won't be anything on it.  So there is nothing to capture on map.  And even if you capture later, e.g. before the pod goes down, it still won't have a UUID if it is a raw block PV (`volumeMode: Block`).

2021-04-17 15:51 UTC, pkalever commented
> For UUID, an image that has just been created and mapped won't have a UUID because there won't be anything on it. So there is nothing to capture on map. And even if you capture later, e.g. before the pod goes down, it still won't have a UUID if it is a raw block PV (`volumeMode: Block`).

My bad, I thought UUID is device-specific which will be assigned on map creation. OK if we do not have a way to identify the device uniquely(it would have been easy), then I can think of only one way for now (I will have to think on this with a fresh approach later), In the do_map() I assume somewhere we will be checking for a free device (/dev/nbd0, /dev/nbd1 ..) and get a non-used one, so why not also check additionally in the saveconfig.json for occupied devices, so that we never assign the used one at the first place (Just a thought)?

2021-04-17 17:10 UTC, trociny commented
> Think it like, the ceph-csi calls `rbd-nbd map` when the new app pod creation request is made using the given volume name (PVC), and it does the `unmap` when the pod is deleted.
> 
> `attach` is needed at the time of the node-plugin pod (which runs rbd-nbd processes) upgrades or just for any random restart of the node-plugin pod. Think the node-plugin pod restart just like an ungraceful rbd-nbd process terminate (nothing more or less), the nbd device is used by application pod, which will be still in running state, meaning the IO is ongoing.

I hope it is rather graceful terminate, i.e. the process is killed with TERM signal or `detach` command is used. In this case the rbd-nbd will wait for pendinding io to complete before terminating. With ungraceful terminate (e.g. `kill -9`, abort) there is a chance some requests will be lost, which I suppose will cause the consumer (fs) to get stuck or an error returned.

> That said, we need a `attach` command here rather than `map` because we do not want to drop the inflight IO. Hope that answers it all.

This looks like a valid use case. But I still don't see why you need save/restore functionality here. How did you plan to use it?

2021-04-19 08:19 UTC, pkalever commented
> > * `rbd-nbd attach` is horrendously easy to misuse.  There is no safety catch, you can attach any `rbd-nbd` instance to any device.  Here is one example:
> >   ```
> >   $ sudo rbd-nbd map --try-netlink rbd/ext4-image
> >   /dev/nbd0
> >   $ sudo blkid /dev/nbd0
> >   /dev/nbd0: UUID="bfc444b4-64b1-418f-8b36-6e0d170cfc04" TYPE="ext4"
> >   $ sudo pkill -9 rbd-nbd
> >   $ sudo rbd-nbd attach --try-netlink --device /dev/nbd0 rbd/xfs-image
> >   /dev/nbd0
> >   $ sudo blkid /dev/nbd0
> >   /dev/nbd0: UUID="d29bf343-6570-4069-a9ea-2fa156ced908" TYPE="xfs"
> >   ```

In a different discussion with @lxbsz, we touched on this topic, and here is what we concluded on:

On every `attach` request, we should read the image_spec from the /proc/* and verify if the new image_spec passed with attach request matches with the one in the /proc/* before proceeding to attach.

I think that should solve is dangerous operations.

Thanks!

2021-04-19 08:40 UTC, pkalever commented
> I hope it is rather graceful terminate, i.e. the process is killed with TERM signal or `detach` command is used. In this case the rbd-nbd will wait for pendinding io to complete before terminating. With ungraceful terminate (e.g. `kill -9`, abort) there is a chance some requests will be lost, which I suppose will cause the consumer (fs) to get stuck or an error returned.

Yes, I agree TERM should be used.

> 
> > That said, we need a `attach` command here rather than `map` because we do not want to drop the inflight IO. Hope that answers it all.
> 
> This looks like a valid use case. But I still don't see why you need save/restore functionality here. How did you plan to use it?

After restart of the node-plugin pod, a sidecar container will get the devices list that needs to be reattached by taking to the Kubernetes API server, and generate a per device rbd restore call with the user/keyfile information.


![restartcase (1)](https://user-images.githubusercontent.com/12432241/115206366-25c6ba80-a118-11eb-9fcd-cf93ad0fdd19.png)


The ceph-csi doesn't know about the device-specific details and various options that are supplied with the map, we want rbd to provide that intelligence so that the users have to just give an image name (needed for partial/single device restore case only) at the time of restore, the rest will be taken care of by the rbd utility.

This will help a lot of alike users who might not be interested in implementing the logic of maintaining such device-specific information and avoid duplicating such logic everywhere.

Implementing such logic just in rbd will save a lot of effort with the tools/users using rbd.

Not just that, with the generalization of the code (Device.cc) rbd-nbd, krbd, ggate ... etc, will be benefited with its dynamic config ability for the restore-all feature.

Thanks!

2021-04-19 10:25 UTC, idryomov commented
> On every `attach` request, we should read the image_spec from the /proc/* and verify if the new image_spec passed with attach request matches with the one in the /proc/* before proceeding to attach.
> 
> I think that should solve this dangerous operation.

Do you mean parsing image spec from `/proc/<rbd-nbd pid>/cmdline`?

If `rbd-nbd` process is killed, there won't be a `/proc` entry for it...

2021-04-19 10:41 UTC, idryomov commented
> The ceph-csi doesn't know about the device-specific details and various options that are supplied with the map, we want rbd to provide that intelligence so that the users have to just give an image name (needed for partial/single device restore case only) at the time of restore, the rest will be taken care of by the rbd utility.

ceph-csi knows and is deeply involved with device-specific details -- ceph-csi is what chooses the `device-type` to be used in the first place.  Similarly, ceph-csi knows all options that are supplied with to `map` -- ceph-csi is what generates and supplies them.

> 
> This will help a lot of alike users who might not be interested in implementing the logic of maintaining such device-specific information and avoid duplicating such logic everywhere.
> 
> Implementing such logic just in rbd will save a lot of effort with the tools/users using rbd.

Do you have an example of such a user?  From what I've heard so far, this seems *really* specific to the combination of ceph-csi and `--device-type nbd`.

> 
> Not just that, with the generalization of the code (Device.cc) rbd-nbd, krbd, ggate ... etc, will be benefited with its dynamic config ability for the restore-all feature.

I think we have established that at least for `krbd` dynamic restore is of virtually no use.

2021-04-20 07:30 UTC, lxbsz commented
> > On every `attach` request, we should read the image_spec from the /proc/* and verify if the new image_spec passed with attach request matches with the one in the /proc/* before proceeding to attach.
> > I think that should solve this dangerous operation.
> 
> Do you mean parsing image spec from `/proc/<rbd-nbd pid>/cmdline`?
> 
> If `rbd-nbd` process is killed, there won't be a `/proc` entry for it...

I misunderstood the use case. I thought the parsing would do after the attach succeeds.

How about in rbd-nbd add one limitation about the map/attach commands ?

Such as add one global config option in /etc/rbd-nbd or in CMakefile when building the rbd-nbd tool, if it is true then the `--device` must be present in the `map/attach` commands. Then the userspace could in charge of which nbdX device should be used instead of kernel to assigne a random one from the free nbdX list.

And will also record the mapped or inused `nbdX` device somewhere, and only after the `unmap` cmd is successfully ran will it be removed from it. Only those are not recorded `nbdX` could be free to use for new `map/attach`.

Could this resolve the above dangerous operation ?

2021-04-20 08:48 UTC, trociny commented
> Could this resolve the above dangerous operation ?

No. You still have a possibility to attach a different image.

The only way I suppose would be if nbd driver could store some metadata provided by the process, and this metadata did not disappear when the process died (until reattach timeout). Then the rbd-nbd could store the image spec there, and  when trying to reattach it would compare the old spec with the new one.

And still we might want to make it optional, because there may be cases when reattaching with different image spec is useful, e.g. for live migration.

2021-04-20 09:53 UTC, lxbsz commented
> > Could this resolve the above dangerous operation ?
> 
> No. You still have a possibility to attach a different image.
> 
> The only way I suppose would be if nbd driver could store some metadata provided by the process, and this metadata did not disappear when the process died (until reattach timeout). Then the rbd-nbd could store the image spec there, and when trying to reattach it would compare the old spec with the new one.
> 

In one spcified pool ? Just like the ceph-iscsi does ?

Or just use the saveconfig file under /var/lib/ceph/, whose name is generated from the spec + nbdX, which will include the pool id, image name, nbdX, etc and should be unique ?

> And still we might want to make it optional, because there may be cases when reattaching with different image spec is useful, e.g. for live migration.

2021-04-20 10:17 UTC, idryomov commented
> In one spcified pool ? Just like the ceph-iscsi does ?
> 
> Or just use the saveconfig file under /var/lib/ceph/, whose name is generated from the spec + nbdX, which will include the pool id, image name, nbdX, etc and should be unique ?

No, in the kernel -- stored and maintained by the nbd driver.  Anything less than that, in particular anything based on `saveconfig` file(s), is not safe.

2021-04-20 11:24 UTC, pkalever commented
> > In one spcified pool ? Just like the ceph-iscsi does ?
> > Or just use the saveconfig file under /var/lib/ceph/, whose name is generated from the spec + nbdX, which will include the pool id, image name, nbdX, etc and should be unique ?
> 
> No, in the kernel -- stored and maintained by the nbd driver. Anything less than that, in particular anything based on `saveconfig` file(s), is not safe.

For me, this seems a simple solution, rather we deal with changes in the kernel module:
On `Map`: save the device and the image_spec in the config file
On `Attach`: Read the config file and check the device mentioned at the command args is used by only the image_spec provided. If any other image_spec is using the same device then fail with the error (we can provide a --force option to continue). 
On `Unmap`: Remove the object matching image_spec and device

To avoid races, take a lock on the config file for every operation needed.

Is there still anything unsolved or unsafe with the above approach?

2021-04-20 11:40 UTC, trociny commented
> Is there still anything unsolved or unsafe with the above approach?

Yes. At least who is going to remove stale entries from "saved config"?

An rbd-nbd process may be terminated without unmap with no intention to be reattached. The kernel would automatically do cleanup after the reattach timeout.

2021-04-20 11:46 UTC, pkalever commented
> > On every `attach` request, we should read the image_spec from the /proc/* and verify if the new image_spec passed with attach request matches with the one in the /proc/* before proceeding to attach.
> > I think that should solve this dangerous operation.
> 
> Do you mean parsing image spec from `/proc/<rbd-nbd pid>/cmdline`?
> 
> If `rbd-nbd` process is killed, there won't be a `/proc` entry for it...

Got it, I had mistakenly assumed that the /sys/module/nbdX/ will have some details about the image spec it got mapped to.

----

> > The ceph-csi doesn't know about the device-specific details and various options that are supplied with the map, we want rbd to provide that intelligence so that the users have to just give an image name (needed for partial/single device restore case only) at the time of restore, the rest will be taken care of by the rbd utility.
> 
> ceph-csi knows and is deeply involved with device-specific details -- ceph-csi is what chooses the `device-type` to be used in the first place. Similarly, ceph-csi knows all options that are supplied with to `map` -- ceph-csi is what generates and supplies them.

I mean to say as of now, we don't maintain the device details and their respective image_spec details after map operation.

> 
> > This will help a lot of alike users who might not be interested in implementing the logic of maintaining such device-specific information and avoid duplicating such logic everywhere.
> > Implementing such logic just in rbd will save a lot of effort with the tools/users using rbd.
> 
> Do you have an example of such a user? From what I've heard so far, this seems _really_ specific to the combination of ceph-csi and `--device-type nbd`.

I don't know exactly, but any containerized platform using rbd-nbd will look for such capability.  And I assume everything is containerized in the near future, that way I expect more similar use cases to come.

> 
> > Not just that, with the generalization of the code (Device.cc) rbd-nbd, krbd, ggate ... etc, will be benefited with its dynamic config ability for the restore-all feature.
> 
> I think we have established that at least for `krbd` dynamic restore is of virtually no use.

Okay, but I mean to say, to keep the rbd interface look-alike, if rbd-nbd is using it then krbd and rbd-ggate can also use the same model. So that the interface and the config file maintenance are the same for all the tools under rbd.


Thanks!

2021-04-20 12:15 UTC, pkalever commented
> > Is there still anything unsolved or unsafe with the above approach?
> 
> Yes. At least who is going to remove stale entries from "saved config"?
> 
> An rbd-nbd process may be terminated without unmap with no intention to be reattached. The kernel would automatically do cleanup after the reattach timeout.

Right.
Okay, maybe you might have thought about this already:
1. If there is a next attach:
Then update/override the config file object with the new device and options.
2. If there is no planned attach:
This is by far a very rare case, I don't see a reason why there will be no planned reattach. Just in case, maybe some kind of manual clean-up is needed here, but again I don't see this as a critical issue.
If we have plans to demonize rbd-nbd, a crawl on the config at the time of init() should help clean unused or deleted image_spec 
related objects Or maybe set up a timely cron job. 


---
BTW at some point I also want to open a discussion about daemonizing rbd-nbd, maybe I will open a new tracker for this later, but I had a plan about this. This should help us save resources, like no of processes used, performance benefit from reusing the shared buffers, reusing the RADOS connection objects etc.. did anyone thought on these lines before?

Thanks!

2021-04-20 20:59 UTC, idryomov commented
> BTW at some point I also want to open a discussion about daemonizing rbd-nbd, maybe I will open a new tracker for this later, but I had a plan about this. This should help us save resources, like no of processes used, performance benefit from reusing the shared buffers, reusing the RADOS connection objects etc.. did anyone thought on these lines before?

It has come up a couple of times, but nothing concrete.  I don't think it would change anything with respect to the fact that attach in its current form is fundamentally unsafe for general use -- the same concerns would apply to a single daemon working on multiple images.  Absent kernel changes, the only way to make attach safe seems to be to exploit and build on the nature of ceph-csi: tightly controlled environment, uniquely named images, etc.

2021-04-30 07:02 UTC, pkalever commented
> > BTW at some point I also want to open a discussion about daemonizing rbd-nbd, maybe I will open a new tracker for this later, but I had a plan about this. This should help us save resources, like no of processes used, performance benefit from reusing the shared buffers, reusing the RADOS connection objects etc.. did anyone thought on these lines before?
> 
> It has come up a couple of times, but nothing concrete. I don't think it would change anything with respect to the fact that attach in its current form is fundamentally unsafe for general use -- the same concerns would apply to a single daemon working on multiple images. Absent kernel changes, the only way to make attach safe seems to be to exploit and build on the nature of ceph-csi: tightly controlled environment, uniquely named images, etc.

Sorry for clubbing it here. Yes, demonizing is a different topic, I asked about it, to get an overall idea w.r.t the plans.

I spend some time to patch nbd kernel module to avoid the dangerous operation that we discussed before, here is the link [1]

For anyone who is interested in testing kernel nbd changes [1], needs userspace rbd-nbd changes [2]


Assuming the kernel patch will get in, and given the dangerous operation is avoided now, can I get an ack on this for moving this code to rbd integrated cli?

As far as I can see @trociny and @lxbsz is in agreement with moving the code to Device.cc, I'm counting on @idryomov 

[1] https://lkml.org/lkml/2021/4/29/274
[2] [0001-rbd-nbd-defend-on-attach-for-image-and-device-mismat.txt](https://github.com/ceph/ceph/files/6403406/0001-rbd-nbd-defend-on-attach-for-image-and-device-mismat.txt)

Thanks!

2021-05-03 07:48 UTC, idryomov commented
> For anyone who is interested in testing kernel nbd changes [1], needs userspace rbd-nbd changes [2]

The kernel patch seems fine, at least at a high level.  However @trociny mentioned that we might want to have a way to override the safety check:

> And still we might want to make it optional, because there may be cases when reattaching with different image spec is useful, e.g. for live migration.

I don't have a strong opinion here, just bumping so it doesn't get lost.

>
> Assuming the kernel patch will get in, and given the dangerous operation is avoided now, can I get an ack on this for moving this code to rbd integrated cli?

The attached `rbd-nbd` patch is not sufficient for promoting to `rbd` CLI because the interface would need to be restricted to new kernels -- older unsafe kernels must be refused.  Also, I don't think an image spec alone is reliable because one can trash the image and create a new one with the same name in less than a second.  I think we need some sort of a cookie -- a u64 or even a UUID for identifying the mapping.

2021-05-03 08:00 UTC, idryomov commented
From an ack perspective, I see three separate pieces:

a) making `rbd-nbd attach` safe.  Definitely useful!

b) promoting `rbd-nbd attach` and `rbd-nbd detach` actions to `rbd` CLI.  Here, since `krbd` doesn't have a concept of attach/detach, I would like to understand whether `ggate` can make use of them and if so, how similar the semantics are going to be.  Things like the safety, the difference between `detach` and `unmap` (for `nbd`, `rbd-nbd detach` is a literal `SIGTERM`), etc.  If the semantics are close enough, let's do it.  Otherwise, if it's going to be just `nbd` (and just on new kernels) it probably shouldn't be promoted.

c) the whole `saveconfig` functionality.  Here, I'll repeat my previous comment: it seems *really* specific to the combination of CSI and `nbd`.  It hasn't come up before and no concrete use case outside of ceph-csi has been presented.  So far I don't see a value in implementing it in rbd.

2021-05-03 08:20 UTC, trociny commented
@pkalever The kernel patch looks very useful to me. Thanks!

The necessary changes to rbd-nbd to support the new kernel feature are welcome! And if it were some sort of a cookie instead of the image spec for identification I would withdraw my requirement to make it optional. I would need it optional if the image spec were used as an identifier, because an image migration (e.g. to some other pool) is one of the cases where detach/attach may be useful (to make it "live" for the client), and the image spec is changed in this case.

As for "saveconfig" functionality, initially I said that although I did not like it much I would prefer it to be in rbd instead of rbd-nbd if we really needed it. But after our discussion here I like the idea less and less, because it really looks like the thing that should be implemented in ceph-csi.

2021-05-03 09:13 UTC, wjwithagen commented
> a) making `rbd-nbd attach` safe. Definitely useful!
> 
> b) promoting `rbd-nbd attach` and `rbd-nbd detach` actions to `rbd` CLI. Here, since `krbd` doesn't have a concept of attach/detach, I would like to understand whether `ggate` can make use of them and if so, how similar the semantics are going to be. Things like the safety, the difference between `detach` and `unmap` (for `nbd`, `rbd-nbd detach` is a literal `SIGTERM`), etc. If the semantics are close enough, let's do it. Otherwise, if it's going to be just `nbd` (and just on new kernels) it probably shouldn't be promoted.

From a FreeBSD/`rbd-ggate` perspective:
I too am really trying to understand the difference between `unmap` and `detach` , but not being very familiar with the Linux side I guess that `unmap` destroys the device, and `detach` keeps the device? And when being detached, access to the device is stalled until something is attached again?

As said `rbd-nbd detach` just signals `SIGTERM`. With `rbd-ggate` that will destroy the device in `/dev/` leaving the entry up for grabs. On the otherhand, when `/dev/ggate0` is used by a filesystem mount then trying to bluntly reconnect gives:
```
# bin/rbd-ggate --device /dev/ggate0 map testrbdggate47177/test
rbd::ggate: failed to create ggate device: (17) File exists
```
Trying to access the mount-point after `rbd-ggate` has crashed gives hard to kill programs that are suspended on that mount.
On the otherhand, if the underlying rbd-image gets blocked due to not enough backing OSDs, work continues once there are enough OSDs up to safely continue.

Now if I look at the options with `geom_gate` and other tools, they particularly specify (from `man ggatel`):
```
rescue       Take over a previously created provider and handle pending
                  and future requests.  This is useful if the initial ggatel
                  process died.  To prevent data loss, the given path must
                  lead to the regular file or device that was used to create
                  the provider.
```
So it is possible to pickup a previously connection to a created device.

And thus I think it should be possible to offer similar semantics in `rbd-ggate`. 
But it is currently not implemented.

2021-05-05 06:08 UTC, pkalever commented
> The attached `rbd-nbd` patch is not sufficient for promoting to `rbd` CLI because the interface would need to be restricted to new kernels -- older unsafe kernels must be refused. Also, I don't think an image spec alone is reliable because one can trash the image and create a new one with the same name in less than a second. I think we need some sort of a cookie -- a u64 or even a UUID for identifying the mapping.

I agree with this and yes cookie sounds good. If we need to generate a UUID per mapping then it must be taken care of by the rbd-nbd itself. Can you add some ideas on how you think this should be implemented and maintained in rbd-nbd? I'm worried and do not want to forward with assumptions.


> From an ack perspective, I see three separate pieces:
> 
> a) making `rbd-nbd attach` safe. Definitely useful!

Yeah, thanks!

> 
> b) promoting `rbd-nbd attach` and `rbd-nbd detach` actions to `rbd` CLI. Here, since `krbd` doesn't have a concept of attach/detach, I would like to understand whether `ggate` can make use of them and if so, how similar the semantics are going to be. Things like the safety, the difference between `detach` and `unmap` (for `nbd`, `rbd-nbd detach` is a literal `SIGTERM`), etc. If the semantics are close enough, let's do it. Otherwise, if it's going to be just `nbd` (and just on new kernels) it probably shouldn't be promoted.

I have not used ggate by myself, I will let others talk about it. I'm happy to contribute with the code changes for this as promised earlier, will keep an eye and follow on the final decision about this topic.

> 
> c) the whole `saveconfig` functionality. Here, I'll repeat my previous comment: it seems _really_ specific to the combination of CSI and `nbd`. It hasn't come up before and no concrete use case outside of ceph-csi has been presented. So far I don't see a value in implementing it in rbd.

Sure, thanks for all your thoughts on this Ilya, I will move this logic to the ceph-csi.

BRs

2021-05-05 06:12 UTC, pkalever commented
> @pkalever The kernel patch looks very useful to me. Thanks!

@trociny Glad to hear that is helping you.

> 
> The necessary changes to rbd-nbd to support the new kernel feature are welcome! And if it were some sort of a cookie instead of the image spec for identification I would withdraw my requirement to make it optional. I would need it optional if the image spec were used as an identifier, because an image migration (e.g. to some other pool) is one of the cases where detach/attach may be useful (to make it "live" for the client), and the image spec is changed in this case.

Sure, I can work on it, I had asked Ilya about his thoughts on the implementation side of it, just to avoid assumptions, will start once we all agree on it.


> As for "saveconfig" functionality, initially I said that although I did not like it much I would prefer it to be in rbd instead of rbd-nbd if we really needed it. But after our discussion here I like the idea less and less, because it really looks like the thing that should be implemented in ceph-csi.

Sure, I will move it to ceph-csi for now. We can always bring it here if there are more usecases in the future.


Thanks for your thoughts!

BRs

2021-05-05 12:57 UTC, pkalever commented
One another thought (on a similar note)
@idryomov ceph-csi uses rbd interface only, hence it will be nice if rbd CLI promotes rbd-nbd attach and detach actions.
For now, at rbd, we can only promote attach/detach with nbd and others can return EOPNOTSUPP.

Thoughts?

2021-05-07 13:12 UTC, idryomov commented
> ```
> To prevent data loss, the given path must
> lead to the regular file or device that was used to create
> the provider.
> ```

@wjwithagen So I take it it would be as easy to shoot yourself in the foot as with current nbd?

2021-05-07 13:23 UTC, wjwithagen commented
> 
> 
> > ```
> > To prevent data loss, the given path must
> > lead to the regular file or device that was used to create
> > the provider.
> > ```
> 
> @wjwithagen So I take it it would be as easy to shoot yourself in the foot as with current nbd?

Yes, once the underlying session is gone, there is currently no way to get to the device.
@trociny was the original author of rbd-ggate, and ATM I'm only patching things up when it does not build, or run.

But I guess it can do with the detach/attach options as well to prevent this foot-shooting.

2021-05-07 13:33 UTC, idryomov commented
> I had asked Ilya about his thoughts on the implementation side of it, just to avoid assumptions, will start once we all agree on it.

We could generate a UUID and store it in omap in the header on image creation. The problem is that existing images won't have that property so we may need to add a new command just for that or make `rbd device map` optionally generate a UUID if it's not already there.

Another approach might be to stick with the spec but encode create timestamp in addition to the spec.  Less reliable, but image timestamps were added a while ago, so relatively few images would be missing them and we could just skip providing the info to the kernel (therefore disallowing `rbd-nbd attach` for them).

I'd prefer the former, since it's more reliable and a per-image UUID will come useful for other things in the future.

2021-05-07 13:39 UTC, idryomov commented
> @idryomov ceph-csi uses rbd interface only, hence it will be nice if rbd CLI promotes rbd-nbd attach and detach actions.
> For now, at rbd, we can only promote attach/detach with nbd and others can return EOPNOTSUPP.

Promoting attach/detach before attach is made safe is just asking for data corruption tickets from frustrated users.

Is there a problem with using `rbd-nbd` in ceph-csi?  The binary is there, in the same container.

2021-05-07 15:48 UTC, trociny commented
> We could generate a UUID and store it in omap in the header on image creation. The problem is that existing images won't have that property so we may need to add a new command just for that or make `rbd device map` optionally generate a UUID if it's not already there.

I was thinking that the UUID could be generated on `rbd-nbd map` command and returned to the user, which could remember it and use on reattach. Do you see issues with such approach?

The problem would be how to return the uuid without breaking compatibility. E.g. on map the  "{dev} {uuid}" string could be returned instead of just "{dev}" as it is currently, if an option like `--return-uuid` is specified (to preserve the compatibility).
 Or it could be shown in `rbd-nbd list-mapped` output (though it would break compatibility). Or yet another command could be added to rbd-nbd like `rbd-nbd status <dev>` that could return the uuid here.

2021-05-07 15:58 UTC, trociny commented
Another thing to consider is that we may map an image snapshot. So we need to store uuid for every snapshot, if we want to permanently store it in the image metadata.

2021-05-09 20:03 UTC, idryomov commented
> I was thinking that the UUID could be generated on `rbd-nbd map` command and returned to the user, which could remember it and use on reattach. Do you see issues with such approach?

Ah, I see.  Now I realize why you said that you would withdraw your requirement to make the kernel enforcement optional -- you meant a *per-mapping* cookie, not a *per-image* one.

It sounds good to me and easier to implement too.  I was leaning towards a persistent per-image UUID because I suspect we will end up needing one in the future anyway, for something entirely unrelated.

We never promised plain unstructured output compatibility.  For `json` and `xml`, it should be compatible -- just a new field.  I think having `list` show it is enough for the initial cut, something like `--device-cookie` can always be added later.

2021-05-11 12:50 UTC, pkalever commented
> > I was thinking that the UUID could be generated on `rbd-nbd map` command and returned to the user, which could remember it and use on reattach. Do you see issues with such approach?
> 
> Ah, I see. Now I realize why you said that you would withdraw your requirement to make the kernel enforcement optional -- you meant a _per-mapping_ cookie, not a _per-image_ one.
> 
> It sounds good to me and easier to implement too. I was leaning towards a persistent per-image UUID because I suspect we will end up needing one in the future anyway, for something entirely unrelated.
> 
> We never promised plain unstructured output compatibility. For `json` and `xml`, it should be compatible -- just a new field. I think having `list` show it is enough for the initial cut, something like `--device-cookie` can always be added later.

I'm some what on the same with @trociny 's idea here.

Repeating the flow to cross-check the missing, before implementing it:
* On each map
   - generate a new UUID
   - request kernel to store the same UUID in `/sys/block/nbd0/backend`
   - return the {dev, UUID} to user, as part of map command output
   - we do not save this UUID anywhere (like in omap or file or elsewhere)
* `list-mapped` should read UUID from `/sys/block/nbd0/backend` and print it.
* On every attach request, user is supposed to pass the required UUID, if UUID doesn't match with `/sys/block/nbd0/backend` we fail.

```
$ rbd-nbd map rbd-pool/image1 --try-netlink
/dev/nbd0, 81adc51d-2dd1-466b-b360-a4a2ad8b2d5c

$ ./bin/rbd-nbd list-mapped
id     pool           namespace  image   snap  device     cookie
16411  cephfs.a.data             image1  -     /dev/nbd0  81adc51d-2dd1-466b-b360-a4a2ad8b2d5c


$ rbd-nbd attach --device=/dev/nbd0 rbd-pool/image1 --cookie 81adc51d-2dd1-466b-b360-a4a2ad8b2d5c
/dev/nbd0

$ cat /sys/block/nbd0/backend
81adc51d-2dd1-466b-b360-a4a2ad8b2d5c
```

Hope I got it right.

2021-05-11 13:02 UTC, trociny commented
> $ rbd-nbd map rbd-pool/image1 --try-netlink
> /dev/nbd0, 81adc51d-2dd1-466b-b360-a4a2ad8b2d5c

If we return the uuid in `list-mapped` output, it is not necessary to return it here -- the caller may find it out by running `list-mapped`.

I am just not very happy about the idea to change the `rbd-nbd map` output, because users may expect it to return the device only and use this in their scripts, like our test script:
 ```
DEV=`rbd-nbd map ...`
```

> $ cat /sys/block/nbd0/backend
> 81adc51d-2dd1-466b-b360-a4a2ad8b2d5c

And, now, taking that the user may get the uuid from `/sys/block/nbd0/backend` I wonder do we really need to modify `list-mapped` to provide it here?

2021-05-11 14:08 UTC, idryomov commented
> Not everyone is aware of `/sys/block/nbdX/backend`, so I think it's good to get it printed with `list-mapped`, provided we already do not want to return with `map`

Yes, users should not need to poke in sysfs.  I see three options:

1) `rbd device map` returning e.g. `/dev/nbd0 81adc51d-2dd1-466b-b360-a4a2ad8b2d5c` when `--device-cookie` is specified (and, as before, `/dev/nbd0` if `--device-cookie` isn't specified)
2) `rbd device list` getting a new (perhaps hidden by default and requiring `--all` or similar) column and json/xml field
3) both of the above

I guess it boils down to whether we want to make it easy to discover the cookie after `rbd device map` runs.  If not, (1) is sufficient and very easy to implement.

2021-05-13 12:00 UTC, pkalever commented
> Yes, users should not need to poke in sysfs. I see three options:
> 
> 1. `rbd device map` returning e.g. `/dev/nbd0 81adc51d-2dd1-466b-b360-a4a2ad8b2d5c` when `--device-cookie` is specified (and, as before, `/dev/nbd0` if `--device-cookie` isn't specified)
> 2. `rbd device list` getting a new (perhaps hidden by default and requiring `--all` or similar) column and json/xml field
> 3. both of the above
> 
> I guess it boils down to whether we want to make it easy to discover the cookie after `rbd device map` runs. If not, (1) is sufficient and very easy to implement.

As per this discussion, I have opened https://github.com/ceph/ceph/pull/41323 which implements both (1) and (2)

Thanks!

2021-12-02 09:51 UTC, pkalever commented
We have introduced a volume healer in ceph-csi to workaround this problem. I'm closing it, in case anyone needed it for generic restore of rbd-nbd devices, this should guide.

Thanks!

2021-12-02 09:51 UTC, closed without merging