Add per-inode fscrypt_priv opaque field
ceph/ceph pull request #40895
Opened 2021-04-16 18:16 UTC by jtlayton

This is still a very rough draft at this point, but should be enough for a PoC. The kernel client side of this is still a WIP.

This basically adds a 16-byte opaque field to inode_t and teaches the MDS to shlep it around alongside the size. The client will use this field to keep track of the "real size" of the inode, and it will always round up the traditional size field to the end of the last fscrypt block.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-04-16 19:15 UTC, batrick requested changes
Need to also encode here: https://github.com/ceph/ceph/blob/master/src/mds/CInode.cc#L1798

and add to the corresponding decode function

2021-04-18 02:40 UTC, jtlayton commented
> Need to also encode here: https://github.com/ceph/ceph/blob/master/src/mds/CInode.cc#L1798
> 
> and add to the corresponding decode function

Thanks Patrick. SQUASH patch added on top that I'll fold into an earlier patch eventually.

2021-04-21 02:02 UTC, batrick requested changes

2021-04-21 02:02 UTC, batrick commented on src/mds/CInode.cc
> +      encode_raw(get_inode()->fscrypt_priv, bl);
A test case to ensure this works properly: changing the encrypted size but **not** changing the CephFS size correctly locks/unlocks the `ifile` lock. Presumably, the kernel won't be sending a redundant update to the size if it does not change but the encrypted size might change.

2021-04-21 10:56 UTC, jtlayton commented on src/mds/mdstypes.h
> +  uint8_t    fscrypt_priv[CEPH_FSCRYPT_PRIVATE_SIZE] = {0};
I think we're going to need to make this variable-length anyway, as I'm going to need to move the crypto context into this field as well.

2021-04-21 10:57 UTC, jtlayton commented
For now I'm going to close out this PR as this is going to require some significant changes to incorporate the crypto context.

2021-04-21 10:57 UTC, closed without merging

2021-04-21 10:58 UTC, jtlayton commented on src/mds/CInode.cc
> +	decode_raw(_inode->fscrypt_priv, p);
Thanks, will fix.