osd/PG.cc: only set auto_repair=true when deep scrub is triggered by repair
ceph/ceph pull request #40949
Opened 2021-04-21 00:34 UTC by neha-ojha

We should not be setting auto_repair=true when is_time_for_deep() is true due to
reasons unrelated to deep scrub errors or need_auto. This adds a misleading
repair flag to the PG state.

Fixes: https://tracker.ceph.com/issues/50446
Signed-off-by: Neha Ojha <nojha@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-04-21 01:08 UTC, jdurgin approved these changes
@ronen-fr thanks for documenting things like the requested_scrub fields - it makes these kinds of changes much easier to understand

2021-04-22 08:22 UTC, ronen-fr approved these changes
LGTM.
I'll try later to go back to old code, and see when was the semantic change introduced.
Probably by me, by mistake...

2021-04-24 05:30 UTC, tchaikov requested changes
```
2021-04-24T04:53:01.706+0000 7f91d2884700 -1 *** Caught signal (Aborted) **
 in thread 7f91d2884700 thread_name:tp_osd_tp

 ceph version 17.0.0-3585-ge14b0611 (e14b06116d158818e73cedb71cf696d989b153a3) quincy (dev)
 1: /lib64/libpthread.so.0(+0x12b20) [0x7f91f1ef6b20]
 2: gsignal()
 3: abort()
 4: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x1a0) [0x556b2772f6ba]
 5: ceph-osd(+0x5b0874) [0x556b2772f874]
 6: (PgScrubber::scrub_finish()+0x1033) [0x556b27b983d3]
 7: (PgScrubber::on_digest_updates()+0x1d0) [0x556b27b98700]
 8: (Scrub::WaitDigestUpdate::react(Scrub::DigestUpdate const&)+0x56) [0x556b27ba5956]
 9: (boost::statechart::simple_state<Scrub::WaitDigestUpdate, Scrub::ActiveScrubbing, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na,
 mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*)+0x9a) [0x556b27baacea]
 10: (boost::statechart::state_machine<Scrub::ScrubMachine, Scrub::NotActive, std::allocator<boost::statechart::none>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&)+0x167) [0x556b27b9fa87]
 11: (PgScrubber::send_replica_maps_ready(unsigned int)+0x28a) [0x556b27b9a0ba]
 12: (PG::forward_scrub_event(void (ScrubPgIF::*)(unsigned int), unsigned int)+0x72) [0x556b278dce82]
 13: (PG::scrub_send_replmaps_ready(unsigned int, ThreadPool::TPHandle&)+0x10a) [0x556b278de44a]
 14: (ceph::osd::scheduler::PGScrubGotReplMaps::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x16) [0x556b27a8dc26]
 15: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0xa58) [0x556b27850d08]
 16: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x5c4) [0x556b27edbdb4]
 17: (ShardedThreadPool::WorkThreadSharded::entry()+0x14) [0x556b27edd154]
 18: (Thread::_entry_func(void*)+0xd) [0x556b27ec2e7d]
 19: /lib64/libpthread.so.0(+0x814a) [0x7f91f1eec14a]
 20: clone()
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

https://pulpito.ceph.com/kchai-2021-04-24_04:07:09-rados-wip-kefu-testing-2021-04-23-2026-distro-basic-smithi/6070023/

~~https://pulpito.ceph.com/kchai-2021-04-24_04:07:09-rados-wip-kefu-testing-2021-04-23-2026-distro-basic-smithi/6070018/~~ EDIT, this one should be an occurrence of https://tracker.ceph.com/issues/49961

2021-04-24 17:16 UTC, neha-ojha commented
> ```
> 2021-04-24T04:53:01.706+0000 7f91d2884700 -1 *** Caught signal (Aborted) **
>  in thread 7f91d2884700 thread_name:tp_osd_tp
> 
>  ceph version 17.0.0-3585-ge14b0611 (e14b06116d158818e73cedb71cf696d989b153a3) quincy (dev)
>  1: /lib64/libpthread.so.0(+0x12b20) [0x7f91f1ef6b20]
>  2: gsignal()
>  3: abort()
>  4: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x1a0) [0x556b2772f6ba]
>  5: ceph-osd(+0x5b0874) [0x556b2772f874]
>  6: (PgScrubber::scrub_finish()+0x1033) [0x556b27b983d3]
>  7: (PgScrubber::on_digest_updates()+0x1d0) [0x556b27b98700]
>  8: (Scrub::WaitDigestUpdate::react(Scrub::DigestUpdate const&)+0x56) [0x556b27ba5956]
>  9: (boost::statechart::simple_state<Scrub::WaitDigestUpdate, Scrub::ActiveScrubbing, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na,
>  mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*)+0x9a) [0x556b27baacea]
>  10: (boost::statechart::state_machine<Scrub::ScrubMachine, Scrub::NotActive, std::allocator<boost::statechart::none>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&)+0x167) [0x556b27b9fa87]
>  11: (PgScrubber::send_replica_maps_ready(unsigned int)+0x28a) [0x556b27b9a0ba]
>  12: (PG::forward_scrub_event(void (ScrubPgIF::*)(unsigned int), unsigned int)+0x72) [0x556b278dce82]
>  13: (PG::scrub_send_replmaps_ready(unsigned int, ThreadPool::TPHandle&)+0x10a) [0x556b278de44a]
>  14: (ceph::osd::scheduler::PGScrubGotReplMaps::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x16) [0x556b27a8dc26]
>  15: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0xa58) [0x556b27850d08]
>  16: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x5c4) [0x556b27edbdb4]
>  17: (ShardedThreadPool::WorkThreadSharded::entry()+0x14) [0x556b27edd154]
>  18: (Thread::_entry_func(void*)+0xd) [0x556b27ec2e7d]
>  19: /lib64/libpthread.so.0(+0x814a) [0x7f91f1eec14a]
>  20: clone()
>  NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
> ```

@tchaikov can you please provide the job id for this?

> 
> https://pulpito.ceph.com/kchai-2021-04-24_04:07:09-rados-wip-kefu-testing-2021-04-23-2026-distro-basic-smithi/
> 
> ~https://pulpito.ceph.com/kchai-2021-04-24_04:07:09-rados-wip-kefu-testing-2021-04-23-2026-distro-basic-smithi/6070018/~ EDIT, this one should be an occurrence of https://tracker.ceph.com/issues/49961

2021-04-24 17:32 UTC, tchaikov commented
@neha-ojha edited.

2021-05-11 21:30 UTC, neha-ojha commented
Closing in favor of https://github.com/ceph/ceph/pull/41258, which is addressing this issue and also doing a cleanup of internal vs external scrub flags.

2021-05-11 21:30 UTC, closed without merging