mds: do not trim the inodes from the lru list in standbyplay
ceph/ceph pull request #40963
Opened 2021-04-21 13:13 UTC by lxbsz

In standby_replay, if some dentries just added and linked not get a
chance to replay the EOpen journals followed, if the upkeep_main() is
excuted, which will may trim them out immediately. Then when playing
the EOpen journals later the replay will fail.

In standby_replay, let's skip trimming them if dentry's linkage inode
is not nullptr.

Fixes: https://tracker.ceph.com/issues/50246
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-04-21 14:43 UTC, batrick requested changes
Great work!

For the commit title `mds: do not trim the inodes from the lru list in standbyplay`, please fix the state name: `standby-replay`.

2021-04-21 14:44 UTC, batrick commented
````
../src/mds/MDCache.cc: In member function 'std::pair<bool, long unsigned int> MDCache::trim_lru(uint64_t, MDCache::expiremap&)':
../src/mds/MDCache.cc:6678:56: error: expected ')' before '{' token
 6678 |     if ((is_standby_replay && dn->get_linkage()->inode) {
      |        ~                                               ^~
      |                                                        )
../src/mds/MDCache.cc:6689:3: error: expected primary-expression before '}' token
 6689 |   }
      |   ^
````

2021-04-22 01:27 UTC, lxbsz commented
> ```
> ../src/mds/MDCache.cc: In member function 'std::pair<bool, long unsigned int> MDCache::trim_lru(uint64_t, MDCache::expiremap&)':
> ../src/mds/MDCache.cc:6678:56: error: expected ')' before '{' token
>  6678 |     if ((is_standby_replay && dn->get_linkage()->inode) {
>       |        ~                                               ^~
>       |                                                        )
> ../src/mds/MDCache.cc:6689:3: error: expected primary-expression before '}' token
>  6689 |   }
>       |   ^
> ```

Sorry, the fix still in my git stash. Will repush it.

2021-04-23 03:11 UTC, batrick approved these changes

2021-05-04 00:30 UTC, batrick commented
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-May-01

2021-05-04 00:48 UTC, merged