monitoring: Use Instance in grafana dashb. Mult Ceph/single Prometheus
ceph/ceph pull request #41047
Opened 2021-04-27 15:23 UTC by juztas

Use Instance filter for multiple Ceph Clusters under single Prometheus source;
All Grafana templates use same timezone (browser)
Remove enforced uid's and or default values (hostname)

Signed-off-by: Justas Balcas juztas@gmail.com

2021-04-27 15:23 UTC, juztas commented
For reference: https://github.com/ceph/ceph/pull/36333

2021-05-05 10:39 UTC, aaSharma14 commented
jenkins test make check

2021-05-05 15:32 UTC, epuertat commented
Hey @juztas thank you for your contribution. You need to take some extra steps for this to adhere to[ Ceph's contributing guidelines](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

Additionally, could you please explain and filter out from this PR the changes not intended (I see changes in many different places which make hard to understand what changes this PR meant to convey). Thanks!

2021-06-14 13:41 UTC, p-se requested changes
Hello @juztas and thank you for your contribution!

As you may have noticed, the suggested changes can't be merged in its current state. @epuertat has provided you a link to the contribution guidelines, but there are two things I want to highlight:

**Sign-off**

The commits need to be signed with a line in the commit message saying `Signed-off-by First Last <some@email.com>`. Without that, we cannot merge the PR. There are checks which would prevent that, even if we wanted to merge it. Every commit needs to contain that line.

**Multiple commits**

The second point is that it's rather difficult to review your changes. Your PR contains a lot of changes which do not necessarily relate to each other and would therefore better be split into several commits. Additionally, it seems to add some changes which Grafana has created automatically and we might not want to have included.

---

Having that said, I took a look anyway and extracted **some** of your proposed changes to a [new pull request](https://github.com/ceph/ceph/pull/41838). It adds the `instance` label to one widget of the Ceph Cluster dashboard page, but on second thought, I'm not sure about that change. [My concerns are raised here](https://github.com/ceph/ceph/pull/41838#issuecomment-860692757). Feel free to add anything you think might be useful.

I have not adopted all of your changes. Please feel free to create a new PR for them to be added or simply adapt this pull request. Either way is fine.

Also, there are some changes which I deliberately have not adopted. The explanations are contained in the review of this pull request. Please, feel free to ask me anything about them or about the aforementioned requirements to get PRs merged.

2021-09-20 11:09 UTC, frittentheke commented
@juztas are you still working on this PR?
If not @epuertat would you accept another attempt at adding a template variable to the dashboards to be able to select one of multiple Ceph clusters?

2021-09-22 16:28 UTC, epuertat commented
> @juztas are you still working on this PR?
> If not @epuertat would you accept another attempt at adding a template variable to the dashboards to be able to select one of multiple Ceph clusters?

Hi @frittentheke, that's more than welcome! Multi-cluster awareness is becoming a thing for Ceph users. As we haven't heard from @juztas since April, feel free to take over this effort. Thank you!

2022-10-29 16:01 UTC, closed without merging