mgr/dashboard: fix RBD namespace validation
ceph/ceph pull request #41058
Opened 2021-04-28 08:25 UTC by navinbarnwal

mgr/dashboard: fix RBD namespace validation
Just adding autocomplete: "off" prevented incorrect suggestions in Firefox.

Fixes: https://tracker.ceph.com/issues/46369
Signed-off-by: Navin Barnwal knbarnwal@gmail.com

2021-04-28 09:03 UTC, navinbarnwal commented
Here is the link for the commit. @epuertat,  Please merge it https://github.com/navinbarnwal/ceph/pull/1

2021-04-28 10:33 UTC, pereman2 commented
@navinbarnwal Now you can squash all 13 commits into 1 so the history is clean and we don't have that much commits which don't do that much. `git reset --soft HEAD~13` then commit with the correct message and force push(`git push -f`). 
If you don't know how to do this you can test by `git checkout -b testbranch` from `navinFeature_branch` branch and see if it's right and you don't break this branch. In this test branch you can see how the PR would look(without creating it).

2021-04-28 11:39 UTC, epuertat commented
@navinbarnwal out of the 6 files in this PR only 1 should be modified. You can check [here](https://devconnected.com/how-to-remove-files-from-git-commit/).

2021-04-28 11:59 UTC, pereman2 approved these changes

2021-04-28 18:23 UTC, navinbarnwal commented
> @navinbarnwal Now you can squash all 13 commits into 1 so the history is clean and we don't have that much commits which don't do that much. `git reset --soft HEAD~13` then commit with the correct message and force push(`git push -f`).
> If you don't know how to do this you can test by `git checkout -b testbranch` from `navinFeature_branch` branch and see if it's right and you don't break this branch. In this test branch you can see how the PR would look(without creating it).

It was really helpful.

2021-04-28 18:23 UTC, navinbarnwal commented
> @navinbarnwal out of the 6 files in this PR only 1 should be modified. You can check [here how to do it](https://devconnected.com/how-to-remove-files-from-git-commit/).

I did it with git stash. Thankx !!

2021-04-29 11:50 UTC, epuertat reviewed
I wonder if this fix is really dealing with the underlying issue... @nizamial09, as you've been recently fixing an issue with an asyncValidator, what do you think about this?

2021-04-29 14:42 UTC, nizamial09 requested changes
@epuertat Yup. This is also a validation issue underneath. It happens both in chrome and firefox. Also the issue is more clear if we are running an octopus version dashboard and firefox. 
What I noticed is that, when we click the `Create` button it runs the validation and it does an incorrect validation. This happens everytime. So we should fix the validation.
Meanwhile I'll look at all other async validators and try to improve them if any needed.

2021-04-29 16:40 UTC, navinbarnwal commented
> @epuertat Yup. This is also a validation issue underneath. It happens both in chrome and firefox. Also the issue is more clear if we are running an octopus version dashboard and firefox.
> What I noticed is that, when we click the `Create` button it runs the validation and it does an incorrect validation. This happens everytime. So we should fix the validation.
> Meanwhile I'll look at all the async validators and try to improve them if any needed.

@nizamial09  I accept that. I just came across Firefox autocomplete issue, assuming that as the only solution for the ticket. I will go through the submit button asyncValidator and fix it myself.

2021-04-30 11:41 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-04-30_03:09:53-rados-wip-kefu-testing-2021-04-30-0020-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-04-30_10:06:45-rados-wip-kefu-testing-2021-04-30-1335-distro-basic-smithi/

2021-05-05 15:59 UTC, navinbarnwal commented
> * https://pulpito.ceph.com/kchai-2021-04-30_03:09:53-rados-wip-kefu-testing-2021-04-30-0020-distro-basic-smithi/
> * https://pulpito.ceph.com/kchai-2021-04-30_10:06:45-rados-wip-kefu-testing-2021-04-30-1335-distro-basic-smithi/

![Screenshot from 2021-05-05 21-29-12](https://user-images.githubusercontent.com/8257144/117171999-0357c100-ade9-11eb-9d6e-b1b9123526e5.png)

2021-05-06 11:44 UTC, Waadkh7 approved these changes

2022-10-29 17:04 UTC, closed without merging