mgr/dashboard: remove NFSv3 support from dashboard
ceph/ceph pull request #41081
Opened 2021-04-29 11:25 UTC by votdev

Fixes: https://tracker.ceph.com/issues/49718
Related to: https://github.com/ceph/ceph/pull/40154

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-04-29 15:07 UTC, mgfritch approved these changes

2021-04-29 16:33 UTC, epuertat commented
jenkins test dashboard

2021-04-29 16:35 UTC, epuertat approved these changes
LGTM! Thanks @votdev !

2021-04-29 16:35 UTC, epuertat commented
@alfonsomthd as you've been recently taking care of NFS stuff, what do you think about this approach?

2021-04-30 09:33 UTC, asettle approved these changes

2021-05-03 15:17 UTC, votdev commented
The last commit removes the 'disabled' property from the v4 checkbox. this way it is still possible to edit existing setups without forcing the export to support v4.
New NFS exports can not select v3, and the form can't be submitted if v4 is not checked.

2021-05-03 16:14 UTC, votdev commented
jenkins test dashboard

2021-05-04 07:04 UTC, alfonsomthd commented
> @alfonsomthd as you've been recently taking care of NFS stuff, what do you think about this approach?

I'm OK with it.

2021-05-04 07:04 UTC, alfonsomthd approved these changes

2021-05-04 07:22 UTC, alfonsomthd commented
@votdev I see that before checking NFSv4, NFSv3 is greyed out to indicate not selectable, but after unchecking andd seeing required red color, when you check again NFSv4 then NFSv3 visually appears as selectable:
step 1:
![Screenshot from 2021-05-04 09-20-09](https://user-images.githubusercontent.com/6780162/116971703-436c5600-acba-11eb-8673-923ef029bec3.png)
step2:
![Screenshot from 2021-05-04 09-20-20](https://user-images.githubusercontent.com/6780162/116971717-48c9a080-acba-11eb-94cb-68b05c147962.png)

2021-05-04 07:39 UTC, alfonsomthd requested changes
https://github.com/ceph/ceph/pull/41081#issuecomment-831735643

2021-05-04 08:15 UTC, votdev commented
> @votdev I see that before checking NFSv4, NFSv3 is greyed out to indicate not selectable, but after unchecking andd seeing required red color, when you check again NFSv4 then NFSv3 visually appears as selectable (the text is not greyed out):
> Step 1:
> ![Screenshot from 2021-05-04 09-20-09](https://user-images.githubusercontent.com/6780162/116971703-436c5600-acba-11eb-8673-923ef029bec3.png)
> Step 2:
> ![Screenshot from 2021-05-04 09-20-20](https://user-images.githubusercontent.com/6780162/116971717-48c9a080-acba-11eb-94cb-68b05c147962.png)

I can not confirm this behaviour with Firefox 88.0 and Chrome 90.0.4430.93.

![Peek 2021-05-04 10-14](https://user-images.githubusercontent.com/1897962/116976608-af05f180-acc1-11eb-9184-358adf05f4f3.gif)

2021-05-04 09:07 UTC, alfonsomthd commented
> I can not confirm this behavior with Firefox 88.0 (creating a new export) and Chrome 90.0.4430.93 (editing an existing export; the second window in the video).

https://user-images.githubusercontent.com/6780162/116982162-c0063100-acc8-11eb-937c-5ba0e51ff91f.mp4


BTW I see in your video that "Create NFS Export" button is placed before "Cancel" button but in master is currently on reverse...

2021-05-04 09:11 UTC, alfonsomthd commented
@votdev Maybe the issue is related to validation logic and not related to this PR.

2021-05-04 09:18 UTC, votdev commented
> @votdev Maybe the issue is related to validation logic and not related to this PR.

Indeed, that's caused by the validation logic. I think we should ignore this little visual issue, otherwise some more code changes are required, and i really want to keep such changes low to do not get unexpected side effects.

2021-05-04 14:26 UTC, alfonsomthd approved these changes

2021-05-05 15:47 UTC, merged