doc/cephfs/nfs: add troubleshooting section and note about export management with volume/nfs interface
ceph/ceph pull request #41091
Opened 2021-04-29 18:15 UTC by varshar16

Fixes: https://tracker.ceph.com/issues/50008

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-04-29 20:57 UTC, batrick requested changes
````
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephfs/fs-nfs-exports.rst:336: WARNING: Content block expected for the "code" directive; none found.
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephfs/fs-nfs-exports.rst:342: WARNING: Content block expected for the "code" directive; none found.
````

2021-04-29 20:58 UTC, batrick commented
content looks good to me

2021-04-30 05:47 UTC, varshar16 commented
> ```
> /home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephfs/fs-nfs-exports.rst:336: WARNING: Content block expected for the "code" directive; none found.
> /home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephfs/fs-nfs-exports.rst:342: WARNING: Content block expected for the "code" directive; none found.
> ```

Fixed

2021-05-01 00:14 UTC, batrick approved these changes

2021-05-01 00:16 UTC, merged