ceph-volume: Raise when no osd_id and no osd_fsid is provided
ceph/ceph pull request #41180
Opened 2021-05-05 16:51 UTC by david-caro

Currently you would get a variable undefined error (for the tags
variable).

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-05-05 17:29 UTC, dsavineau commented
jenkins test ceph-volume tox

2021-05-05 17:30 UTC, dsavineau requested changes

2021-05-05 17:30 UTC, dsavineau commented on src/ceph-volume/ceph_volume/devices/lvm/activate.py
> +            raise RuntimeError('If you pass an an osd ID you need to pass '
```suggestion
            raise RuntimeError('If you pass an osd ID you need to pass '
```

2021-05-06 09:11 UTC, david-caro commented on src/ceph-volume/ceph_volume/devices/lvm/activate.py
> +            raise RuntimeError('If you pass an an osd ID you need to pass '
:facepalm:

2021-05-17 08:07 UTC, david-caro commented
Amended the commit to have signed-off-by

2021-09-30 13:59 UTC, closed without merging

2021-09-30 13:59 UTC, david-caro commented
This was superseded by https://github.com/ceph/ceph/pull/43014