mds/MDLog: make the get_metadata_pool under the mds_lock
ceph/ceph pull request #41254
Opened 2021-05-10 09:33 UTC by lxbsz

There is one rare case that when mds daemon received a new mdsmap
and during decoding it, the metadata_pool will be reset to -1, if
other threads try to get it from old mdsmap it will get a invalid
pool id.

Fixes: https://tracker.ceph.com/issues/50389
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-05-10 14:38 UTC, lxbsz commented
> Please move "mds: defer..." to a separate PR.
> Please move "osdc/Objecter: add more..." to a separate PR.
> Same for "mds: fix possible mds_lock not locked assert". Make a ticket for this one too for backport.
> 
> Also, as we discussed, "mds/MDLog: make the get_metadata_pool under the mds_lock" would be better to just save the metadata pool id in `MDLog::create` in a member in `MDLog` so it does not need to access the mdsmap.

Sure, will do that tomorrow morning.

2021-05-11 16:25 UTC, batrick requested changes
Great work Xiubo!

2021-05-11 23:19 UTC, batrick commented
Running this through QA without the fixes to the nits in my previous review. Let me know if you make any significant changes that will require a new QA run.

2021-05-12 01:41 UTC, lxbsz commented on src/mds/MDSRank.h
> +    int64_t get_metadata_pool()
Done.

2021-05-12 01:41 UTC, lxbsz commented on src/mds/MDSRank.cc
> +  // of the fs, with this we can get ride of the mds_lock
Done.

2021-05-12 01:42 UTC, lxbsz commented
> Running this through QA without the fixes to the nits in my previous review. Let me know if you make any significant changes that will require a new QA run.

Nothing new except the above two issues you pointed out.

2021-05-18 02:37 UTC, batrick commented
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-May-11

2021-05-18 02:42 UTC, batrick approved these changes

2021-05-18 02:46 UTC, merged