mgr/volumes: Add config to insert delay at the beginning of the clone
ceph/ceph pull request #41403
Opened 2021-05-19 13:30 UTC by kotreshhr

Added the config 'delay_snapshot_clone' to insert delay at the beginning
of the clone to avoid races in tests. The default value is set to 0.

Fixes: https://tracker.ceph.com/issues/48231
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-05-20 16:37 UTC, batrick requested changes

2021-05-20 16:37 UTC, batrick commented on src/pybind/mgr/volumes/module.py
> +            'delay_snapshot_clone',
```suggestion
            'snapshot_clone_delay',
```

2021-05-20 16:37 UTC, batrick commented on qa/tasks/cephfs/test_volumes.py
> +        self.config_set('mgr', 'mgr/volumes/delay_snapshot_clone', 0)
and drop all of the restting to 0

2021-05-21 07:06 UTC, kotreshhr commented on src/pybind/mgr/volumes/module.py
> +            'delay_snapshot_clone',
Done

2021-05-22 14:32 UTC, kotreshhr commented
Teuthology result:

http://pulpito.front.sepia.ceph.com/khiremat-2021-05-21_16:22:47-fs:volumes-wip-khiremat-41403-delay-snapshot-clone-2-distro-basic-smithi/

The tests passed with known failure: https://tracker.ceph.com/issues/49845

2021-06-03 16:34 UTC, batrick approved these changes

2021-06-14 02:51 UTC, batrick commented
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-13

2021-06-14 02:52 UTC, merged