os/bluestore: introduce multithireading sync for bluestore's repairer
ceph/ceph pull request #41429
Opened 2021-05-19 23:22 UTC by ifed01

In quick-fix mode bluestore uses 2 threads by default to perform the  repair. Due to lacking synchronization they might corrupt repair  transaction batch.

Fixes: https://tracker.ceph.com/issues/50017

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-05-20 09:52 UTC, aclamk commented
**this is unrelated to commited code**

In some cases, like `_fsck_check_object_omap()`, we put `_record_onode()` into rocksdb transaction and submit it immediately.
In other cases, like `repairer->fix_spanning_blobs()` we put `_record_onode()` into transaction to submit later.
```
    if (broken) {
      derr << "fsck error: " << oid << " - " << broken
           << " zombie spanning blob(s) found, the first one: "
           << *first_broken << dendl;
      if(repairer) {
        auto txn = repairer->fix_spanning_blobs(db);
	_record_onode(o, txn);
      }
    }
  }

  if (o->onode.has_omap()) {
    _fsck_check_object_omap(depth, o, ctx);
  }
  ```
I read it, that it is possible to:
1) fix spanning blobs in onode o, but not commit to DB yet
2) actually commit to DB even more modification of o - regarding omap handling
3) then commit to DB changes from step 1), forgetting fixes from 2)

Am I missing something?
Maybe we should always commit repair steps, and not aggregate them into huge transaction to execute at the end?

2021-05-20 10:31 UTC, aclamk requested changes
Excellent unittest.
Maybe details to fix on implementation.

2021-05-20 10:31 UTC, aclamk commented on src/os/bluestore/BlueStore.h
> +    //NB: not for use in multithreading mode!!!
"// Does not need lock - illegal to call in multithreading fsck" ?

2021-05-20 10:31 UTC, aclamk commented on src/test/objectstore/store_test.cc
> +TEST_P(StoreTestSpecificAUSize, BluestoreBrokenZombieRepairTest) {
+1 for test being in separate commit then fix.

2021-05-20 20:59 UTC, ifed01 commented on src/os/bluestore/BlueStore.cc
> +        repairer->fix_spanning_blobs(
The intention is to avoid private _record_onode() exposure - hence the design

2021-05-20 21:31 UTC, ifed01 commented
> **this is unrelated to commited code**
> 
> In some cases, like `_fsck_check_object_omap()`, we put `_record_onode()` into rocksdb transaction and submit it immediately.
> In other cases, like `repairer->fix_spanning_blobs()` we put `_record_onode()` into transaction to submit later.
> 
> ```
>     if (broken) {
>       derr << "fsck error: " << oid << " - " << broken
>            << " zombie spanning blob(s) found, the first one: "
>            << *first_broken << dendl;
>       if(repairer) {
>         auto txn = repairer->fix_spanning_blobs(db);
> 	_record_onode(o, txn);
>       }
>     }
>   }
> 
>   if (o->onode.has_omap()) {
>     _fsck_check_object_omap(depth, o, ctx);
>   }
> ```
> 
> I read it, that it is possible to:
> 
> 1. fix spanning blobs in onode o, but not commit to DB yet
> 2. actually commit to DB even more modification of o - regarding omap handling
> 3. then commit to DB changes from step 1), forgetting fixes from 2)
> 
> Am I missing something?
> Maybe we should always commit repair steps, and not aggregate them into huge transaction to execute at the end?

I agree that doesn't look elegant enough. Unfortunately it reflects the evolution (overburden) of fsck procedure - it supports  both real errors detection and naming scheme conversion for upgrade purposes. The former was originally designed to use a single repair transaction which looks safer from data consistency point of view. But the latter can't use all-in-one model due to potential data volume. Hence the mixture.
Regarding your concerns about overwriting previous modifications - perhaps you're right and it can fail this way. Will try to reproduce...

2021-05-21 06:56 UTC, aclamk commented on src/os/bluestore/BlueStore.cc
> +        repairer->fix_spanning_blobs(
Thx - I missed that!

2021-05-21 06:59 UTC, aclamk approved these changes

2021-05-21 12:02 UTC, ifed01 commented
> Regarding your concerns about overwriting previous modifications - perhaps you're right and it can fail this way. Will try to reproduce...
@aclamk - FYI: https://tracker.ceph.com/issues/50926
Good catch!

2021-05-23 00:42 UTC, merged

2021-05-23 00:42 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-05-21_12:49:52-rados-wip-kefu-testing-2021-05-21-1851-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-22_15:42:09-rados-wip-kefu-testing-2021-05-22-2207-distro-basic-smithi/

failure tracked by 

- https://tracker.ceph.com/issues/50243
- https://tracker.ceph.com/issues/50151