mon/auth: trigger_propose not active cause mon leader update rotate r…
ceph/ceph pull request #41438
Opened 2021-05-20 09:42 UTC by swg1991

When Paxos in the update state, mon leader need update rotate secret just right. It cause trigger_propose not active and return false. update rotate secret is not timely. For this case，just retry propose . retry three times at most,if retry three times still failed just give up retransmission。

Fixes: https://tracker.ceph.com/issues/50775

Signed-off-by: wenge.song <wenge.song@lenovonetapp.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-05-23 15:39 UTC, swg1991 commented
@idryomov ping?

2021-05-23 20:47 UTC, idryomov reviewed
There are multiple coding style issues, mostly related to missing spaces and braces.  I've highlighted a few instances but all of them would need to be fixed.

More importantly, I don't fully understand the problem you are trying to address yet.  I've asked for additional logs in the tracker ticket, let's continue discussing it there for now.

2021-05-23 20:47 UTC, idryomov commented on src/auth/cephx/CephxKeyServer.cc
> +  added += _rotate_secret(CEPH_ENTITY_TYPE_AUTH,auth_done);
```suggestion
  added += _rotate_secret(CEPH_ENTITY_TYPE_AUTH, auth_done);
```

2021-05-23 20:47 UTC, idryomov commented on src/auth/cephx/CephxKeyServer.cc
> +               << dendl;
Unnecessary change.

2021-05-23 20:47 UTC, idryomov commented on src/auth/cephx/CephxKeyServer.cc
> +    if(auth)
```suggestion
    if (auth) {
```

2021-05-23 20:47 UTC, idryomov commented on src/auth/cephx/CephxKeyServer.cc
> +        auth = 0;
```suggestion
        auth = 0;
      }  
```

2021-05-23 20:47 UTC, idryomov commented on src/mon/AuthMonitor.cc
> +  if( auth == AUTH_PROPOSE_START){
```suggestion
  if (auth == AUTH_PROPOSE_START) {
```

2021-05-23 20:47 UTC, idryomov commented on src/mon/AuthMonitor.cc
> +    dout(10) << __func__ << " updated rotating retry: " <<auth_propose_retry<< dendl;
```suggestion
    dout(10) << __func__ << " updated rotating retry: " << auth_propose_retry << dendl;
```

2021-05-23 20:47 UTC, idryomov commented on src/mon/AuthMonitor.cc
> +  if (!mon.key_server.updated_rotating(rot_inc.rotating_bl, last_rotating_ver,auth))
```suggestion
  if (!mon.key_server.updated_rotating(rot_inc.rotating_bl, last_rotating_ver, auth)) {
```

2021-05-23 20:47 UTC, idryomov commented on src/mon/AuthMonitor.h
> +#define CHECK_AUTH_DONE 0X1
Just `1` and `3`, no need to use hexadecimal here.

2021-05-27 02:03 UTC, swg1991 commented
@jecluis ping ? Do you have free time to  discuss it with us?

2021-05-31 08:58 UTC, jecluis requested changes
I don't particularly like the idea of changing `PaxosService` to accommodate a specific service's needs, especially when this seems like something that's not fully fleshed out. Following Ilya's statement, I'm also not entirely sure what it is you are trying to fix here?

2022-12-28 01:28 UTC, closed without merging