os/bluestore: track bluestore_warn_on_no_per_pg_omap cfg parameter ch…
ceph/ceph pull request #41452
Opened 2021-05-20 18:02 UTC by ifed01

…anges.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-05-21 07:05 UTC, aclamk requested changes
Please add commit mention that functionality for reacting to `bluestore_warn_on_no_per_pg_omap` is already implemented, but observer was not tracking it.

2021-05-21 09:19 UTC, ifed01 commented
> Please add commit mention that functionality for reacting to `bluestore_warn_on_no_per_pg_omap` is already implemented, but observer was not tracking it.

Done.

2021-05-24 14:34 UTC, aclamk approved these changes

2021-05-26 02:33 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-05-25_04:17:20-rados-wip-kefu-testing-2021-05-25-1039-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-25_14:42:43-rados-wip-kefu-testing-2021-05-25-2008-distro-basic-smithi/

failure tracked by

- https://tracker.ceph.com/issues/45423

2021-05-26 02:33 UTC, merged