os/bluestore: improve stray omap logging during fsck.
ceph/ceph pull request #41453
Opened 2021-05-20 18:02 UTC by ifed01

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-05-21 10:01 UTC, aclamk requested changes
I think this commit should be split in two:
- first one improves omap logging
- second that actually fixed problem with stray omaps.

2021-05-21 11:02 UTC, ifed01 commented
> I think this commit should be split in two:
> 
> * first one improves omap logging
> * second that actually fixed problem with stray omaps.

the second part doesn't fixes anything - it just introduces UT to verify if stray detection works fine (and allows to view new logging ;))

2021-05-21 11:03 UTC, ifed01 commented on src/test/objectstore/store_test.cc
> +  ASSERT_EQ(bstore->fsck(false), 1);
that's the case, there is no fix for stray omaps atm.

2021-05-21 11:06 UTC, ifed01 commented on src/test/objectstore/store_test.cc
> +  bstore->mount();
right, that's expected for now. Perhaps should explicitly set bluestore_fsck_on_mount to false though.

2021-05-21 11:20 UTC, ifed01 commented
@aclamk - I've just split the original commit into two parts and did some minor cleanup, please take a look.

2021-05-24 14:31 UTC, aclamk commented on src/test/objectstore/store_test.cc
> +  ASSERT_EQ(bstore->fsck(false), 1);
Aww, sorry to cause trouble - I was sure we are fixing it.

2021-05-24 14:33 UTC, aclamk approved these changes
More useful code, welcome!

2021-05-26 02:33 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-05-25_04:17:20-rados-wip-kefu-testing-2021-05-25-1039-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-25_14:42:43-rados-wip-kefu-testing-2021-05-25-2008-distro-basic-smithi/

failure tracked by

- https://tracker.ceph.com/issues/45423

2021-05-26 02:33 UTC, merged