install-deph.sh: install missing libarchive centos-8
ceph/ceph pull request #41819
Opened 2021-06-11 12:19 UTC by pereman2

When trying to build ceph from ceph-dev and also on my fedora 33 machine I ran into this error:
```bash
+ cmake -GNinja -DWITH_PYTHON3=3.6 -DWITH_CCACHE=ON -DBOOST_J=10 -D ENABLE_GIT_VERSION=OFF ..
cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd

```

it was solved by install the libarchive dependency.
Signed-off-by: Pere Diaz Bou <pdiazbou@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-06-11 12:41 UTC, epuertat approved these changes
👍🏼

2021-06-11 12:42 UTC, alfonsomthd approved these changes

2021-06-11 14:44 UTC, tchaikov reviewed
@pereman2 i'd suggest upgrade cmake instead. it's a bug of cmake packaging and/or it's dependencies. libarchive is cmake's runtime dependency. if a symbol referenced by cmake is missing, it's a bug in cmake and/or libarchive.

FWIW, @djgalloway and i upgraded a bunch of RHEL8/CentOS8 based building hosts in lab to address this very issue recently.

2021-06-11 14:46 UTC, tchaikov requested changes
i'd avoid cluttering `install-deps.sh` with workaround for the packaging issue if possible.

2021-06-14 07:09 UTC, closed without merging

2021-06-14 07:10 UTC, pereman2 commented
Okay.
I'll close this pr

2021-06-14 08:26 UTC, alfonsomthd commented
> @pereman2 i'd suggest upgrade cmake instead. 

@tchaikov it seems it still fails for centos 8:
[root@c86d0be94ae0 ceph]# cat /etc/system-release
CentOS Linux release 8.3.2011

Installed Packages
Name         : cmake
Version      : 3.18.2
Release      : 9.el8
Architecture : x86_64
Size         : 26 M
Source       : cmake-3.18.2-9.el8.src.rpm

2021-06-14 10:05 UTC, tchaikov commented
> > @pereman2 i'd suggest upgrade cmake instead.
> 
> @tchaikov it seems it still fails for centos 8:
> [root@c86d0be94ae0 ceph]# cat /etc/system-release
> CentOS Linux release 8.3.2011
> 
> Installed Packages
> Name : cmake
> Version : 3.18.2
> Release : 9.el8
> Architecture : x86_64
> Size : 26 M
> Source : cmake-3.18.2-9.el8.src.rpm

could you please upgrade libarchive? in my case:
```console
$ rpm -q libarchive
libarchive-3.3.3-1.el8.x86_64
```

2021-06-14 11:00 UTC, alfonsomthd commented
> could you please upgrade libarchive? in my case:
> 
> ```
> $ rpm -q libarchive
> libarchive-3.3.3-1.el8.x86_64
> ```

@tchaikov OK but in this case, shouldn't be better to ensure in ìnstall-deps.sh`that the system effectively has the latest libarchive?

2021-06-14 11:20 UTC, pereman2 commented
I agree with alfonso here. If after running `install_deps.sh` we still don't have all the required deps we either need to document this or add it to the script. Maybe we can have a cleanup of the script if it's cluttered.