os/bluestore: add BtreeAllocator
ceph/ceph pull request #41828
Opened 2021-06-12 13:26 UTC by tchaikov

because the overhead of node of AVL tree need to keep track of its
children, the overhead of tracking each extent is relatively higher
than that of bitmap allocator, per node sizes 80 bytes, per
per mempool stats provided by unittest_alloc_bench. while btree has
lower overhead, as it keep multiple entries in each node / block,
the node size of abseil's btree implementation defaults to 256, so each
node is able to contain up to 256 values. this means we have lower
overhead than the binary-trees like AVL and red-black tree.

 
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-06-14 09:50 UTC, tchaikov commented
per the `btree.stats` which is not exposed by its wrapper, 

-  average_bytes_per_value: 22.7556: each extent takes 22.75 bytes.
- overhead: 40: each b-tree node (which contains up to 256 values) has 40 bytes overhead.

this is much lower than that of AVL tree.

2021-06-14 10:11 UTC, tchaikov commented
test | AVL | btree 
--- | --- | ---
 test_alloc_bench_seq/2 | 577766 ms |  827261 ms

2021-06-14 14:11 UTC, tchaikov commented
```
[ RUN      ] Queue.SpawnAsyncRequest
../src/test/rgw/test_rgw_dmclock_scheduler.cc:425: Failure
Value of: context.stopped()
  Actual: false
Expected: true
[  FAILED  ] Queue.SpawnAsyncRequest (0 ms)
```

2021-06-14 14:11 UTC, tchaikov commented
jenkins test make check

2021-06-15 12:38 UTC, tchaikov commented
jenkins test make check

2021-06-17 08:34 UTC, aclamk commented
I added a memory tracking to aging test: https://github.com/aclamk/ceph/commit/0a2279eae2100037fb67be538eb77b234929c6ee

Summary: 
avl    fragmented allocs=0.727767% #frags=2.00015 free_score=0.756594 time=15590.9ms mempool=3281490 tcmalloc=3283234
bitmap    fragmented allocs=55.3145% #frags=2.60743 free_score=0.583628 time=4836.3ms mempool=18708994 tcmalloc=18710322
btree    fragmented allocs=0.674791% #frags=2.00038 free_score=0.756787 time=8716.12ms mempool=0 tcmalloc=1845818
stupid    fragmented allocs=1.40833% #frags=2.04938 free_score=0.749268 time=29840ms mempool=893859 tcmalloc=895612

btree really looks impressive, Kefu @tchaikov !

I guess it really should add btree to mempool accounting.

2021-06-17 08:37 UTC, aclamk requested changes
Excellent reduction of used memory!
Must move btree to mempool::bluestore_alloc.

2021-06-17 09:18 UTC, tchaikov commented
@aclamk Adam, thank you for profiling the BtreeAllocator!

the btree block / node is more of an implementation details which are not exposed as part of its public interface. so i thought it'd be difficult to inject the `MEMPOOL_CLASS_HELPERS` macro and to define `MEMPOOL_DEFINE_OBJECT_FACTORY()` in an appropriate way. but it seems we can just pass `mempool::bluestore_alloc::pool_allocator<T>` to the btree container templates as their `allocator` template parameter.  just updated with this change.

could you take another look?

2021-06-17 13:29 UTC, markhpc commented
@tchaikov @aclamk Nice job and nice testing!  Cheers from the sidelines. :)

2021-06-18 01:15 UTC, tchaikov commented
@aclamk i reran the aging test with your patch and updated the table in your comment.

2021-06-18 01:15 UTC, tchaikov commented
rebased against master.

2021-06-18 10:14 UTC, tchaikov commented
jenkins test make check

2021-06-18 15:48 UTC, tchaikov commented
jenkins test make check

2021-06-19 13:04 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-06-18_12:04:35-rados-wip-kefu-testing-2021-06-18-1414-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-19_08:35:14-rados-wip-kefu-testing-2021-06-18-1414-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-19_11:27:01-rados-wip-kefu-testing-2021-06-19-1642-distro-basic-smithi/

i don't think the failures were related to this change.

2021-06-19 13:05 UTC, tchaikov commented
@aclamk hi Adam, is there anything else i can do to improve this changeset?

2021-06-24 09:47 UTC, aclamk approved these changes
This is good work.
In my opinion btree allocator should replace avl in any case.

There should be done some work on replacing avl->btree for 'hybrid' strategy. If so, new thresholds for switching from interval to bitmap mode must be calculated.

2021-06-24 11:10 UTC, merged

2021-06-24 11:11 UTC, tchaikov commented
@aclamk yeah, will port the hybrid strategy to btree allocator later on.