mgr/orch: pass dict to yaml.SafeDumper.represent_dict()
ceph/ceph pull request #41847
Opened 2021-06-15 00:38 UTC by tchaikov

yaml.SafeDumper.represent_dict() in turn calls SafeRepresenter.represent_dict().
and SafeRepresenter.represent_dict() calls BaseRepresenter.represent_mapping()
which sets `mapping` to `list(mapping.items())` before dumping it. see
https://github.com/yaml/pyyaml/blob/ee37f4653c08fc07aecff69cfd92848e6b1a540e/lib3/yaml/representer.py#L103-L129

this change alsow silences mypy errors like:

orchestrator/_interface.py: note: In member "yaml_representer" of class "DaemonDescription":
orchestrator/_interface.py:1039: error: Argument 1 to "represent_dict" of "SafeRepresenter" has incompatible type "ItemsView[Any, Any]"; expected "Mapping[Any, Any]"

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-06-15 00:40 UTC, tchaikov commented
we have 
```
mypy run-test: commands[0] | mypy --config-file=../../mypy.ini -m alerts -m balancer -m cephadm -m crash -m dashboard -m devicehealth -m diskprediction_local -m hello -m influx -m iostat -m localpool -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m orchestrator -m progress -m prometheus -m rbd_support -m rook -m snap_schedule -m selftest -m stats -m status -m telegraf -m telemetry -m test_orchestrator -m volumes -m zabbix
orchestrator/__init__.py:6: note: In module imported here:
orchestrator/_interface.py: note: In member "yaml_representer" of class "DaemonDescription":
orchestrator/_interface.py:1039: error: Argument 1 to "represent_dict" of "SafeRepresenter" has incompatible type "ItemsView[Any, Any]"; expected "Mapping[Any, Any]"
orchestrator/_interface.py: note: In member "yaml_representer" of class "ServiceDescription":
orchestrator/_interface.py:1178: error: Argument 1 to "represent_dict" of "SafeRepresenter" has incompatible type "ItemsView[Any, Any]"; expected "Mapping[Any, Any]"
Found 2 errors in 1 file (checked 29 source files)
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/mypy/bin/mypy --config-
```

after the mypy change merged recently. this change should fix it.

2021-06-15 08:13 UTC, sebastian-philipp commented on src/pybind/mgr/orchestrator/tests/test_orchestrator.py
>  events:
Right. the order is important here for the readability.

2021-06-15 08:21 UTC, sebastian-philipp commented
#41854

2021-06-15 09:25 UTC, sebastian-philipp requested changes
I'd prefer my PR. ok?

2021-06-17 11:15 UTC, sebastian-philipp commented
closing this: It was fixed in typshed itself.

2021-06-17 11:16 UTC, closed without merging