doc: small typo (guage --> gauge)
ceph/ceph pull request #41920
Opened 2021-06-17 19:24 UTC by ljflores

There is a small typo in the Perf Counters documentation. The word 'gauge' was spelled incorrectly.

2021-06-17 19:42 UTC, neha-ojha approved these changes

2021-06-18 01:17 UTC, neha-ojha commented
@ljflores the second commit is not necessary, can you please get rid of it

2021-06-18 01:17 UTC, tchaikov requested changes
the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

2021-06-18 14:25 UTC, ljflores commented
Oh wow, I really screwed something up. I think I will just close this PR and submit a new one.

2021-06-18 14:45 UTC, tchaikov commented
@ljflores or you could try:

```console
git reset --hard origin/master
git cherry-pick 739bc8fdd34ace6c58942e86b6b4e1dabd3eb46c
git commit --amend
```

assuming that you have a remote repo named `origin` which points to `git@github.com:ceph/ceph.git`.

2021-06-18 14:52 UTC, ljflores commented
Okay, I did all of that. Would the next step be to push the updated branch to remote? Just want to make sure I'm doing everthing correctly. (i.e. git push origin patch-1)

2021-06-18 15:31 UTC, tchaikov commented
@ljflores i think the next step would be 

```sh
git push -f me patch-1
```

assuming your remote repo is named `me`, and your local branch name is named `patch-1` also.

2021-06-18 17:45 UTC, ljflores commented
There were still some commits behind 6184362 that needed to be removed, so I tried rebasing my branch and dropping the commits that weren't needed. Unfortunately, it seems that commits from other contributors have now been included in this PR. I think this is because if I run "git rebase", or even "git log", I can see the commits I've made in addition to everyone else's. I'm not sure where to go from here, but I'll keep looking to see if there's something wrong on my end.

2021-06-19 08:51 UTC, tchaikov approved these changes

2021-06-19 08:51 UTC, merged