rbd-nbd: support notrim option with map command
ceph/ceph pull request #41954
Opened 2021-06-21 14:13 UTC by pkalever

currently --notrim option works for rbd kernel mounter, but fails with rbd-nbd

$ rbd device --options notrim map rbd-pool/image0
/dev/rbd0
$ rbd device list
id  pool      namespace  image   snap  device
0   rbd-pool             image0  -     /dev/rbd0

$ rbd device --device-type nbd --options try-netlink,notrim map rbd-pool/image0
rbd-nbd: unknown args: --notrim
rbd: rbd-nbd failed with error: /data/ceph/build/bin/rbd-nbd: exit status: 1

With this changes:
$ rbd device --device-type nbd --options try-netlink,notrim map rbd-pool/image0
/dev/nbd0
$ rbd-nbd list-mapped
id    pool      namespace  image   snap  device
6945  rbd-pool             image0  -     /dev/nbd0
$ ps -eo "cmd" |grep [r]bd-nbd
/data/ceph/build/bin/rbd-nbd map rbd-pool/image0 --try-netlink --notrim

Fixes: https://github.com/ceph/ceph-csi/issues/2171

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

2021-06-21 14:14 UTC, pkalever commented
cc: @nixpanic

2021-06-22 06:27 UTC, nixpanic reviewed
Thanks, looks like a reasonable changes to me :+1:

2021-06-23 06:04 UTC, trociny approved these changes
LGTM

2021-06-26 17:09 UTC, idryomov requested changes
Looks good to me but need to add a test case to `qa/workunits/rbd/rbd-nbd.sh`.  There already is a "trim test" one, add a counter example based on it.

2021-06-30 07:27 UTC, idryomov requested changes
A better idea ;)

2021-06-30 07:27 UTC, idryomov commented on qa/workunits/rbd/rbd-nbd.sh
> +_sudo mkfs.ext4 -F -E discard ${DEV} # better idea?
```suggestion
_sudo blkdiscard ${DEV}
```

2021-06-30 07:27 UTC, idryomov commented on qa/workunits/rbd/rbd-nbd.sh
>  _sudo mkfs.ext4 -E discard ${DEV} # better idea?
```suggestion
# should fail discard as at time of mapping notrim was used
expect_false _sudo blkdiscard ${DEV}
```

2021-06-30 07:54 UTC, pkalever commented
> A better idea ;)

Indeed :-)

Thanks, @idryomov, refreshed with the suggested changes now.

2021-06-30 08:56 UTC, idryomov approved these changes

2021-06-30 12:01 UTC, idryomov commented
https://pulpito.ceph.com/dis-2021-06-30_11:33:22-rbd-wip-dis-testing-distro-basic-smithi/

2021-06-30 12:02 UTC, merged