libcephfssqlite: a sqlite3 vfs that use cephfs as the storage engine, v1
ceph/ceph pull request #42078
Opened 2021-06-29 01:00 UTC by mark15213

libcephfssqlite version 1. With this library, cephfs would be able to handle file I/O and storage management for sliqte database. This version of code implemented some basic methods except for the locking mechanism.

Signed-off-by: Shuai Wang <markw8973240@gmail.com>

2021-06-29 04:14 UTC, tchaikov commented
what's the advantage of libcephfssqlite in comparison with libcephsqlite? like, what is its use case or performance characteristics ?

2021-06-29 18:58 UTC, batrick commented
> what's the advantage of libcephfssqlite in comparison with libcephsqlite? like, what is its use case or performance characteristics ?

Generally the "ceph" VFS (libcephsqlite) should be preferred but if the database is on CephFS, this VFS ("cephfs") lets you interact with that database without formally mounting CephFS (ceph-fuse/kernel).

The use-case is likely a metadata store within a ceph-mgr plugin that predominately stores its metadata on CephFS already, like the "volumes" plugin. Putting it in CephFS rather than RADOS can be advantageous because then admins can interact with the database without any special sqlite3 plugins (e.g. if using the kernel client). But admittedly the advantage is small. In the end, this just gives users more options.

Finally, this code is just a prototype at this point. I'll mark this as a draft.

2021-06-29 23:38 UTC, batrick commented on src/CMakeLists.txt
> +  set(cephfssqlite_srcs libcephfssqlite.cc SimpleRADOSStriper.cc)
```suggestion
  set(cephfssqlite_srcs libcephfssqlite.cc)
```

2021-06-29 23:38 UTC, batrick commented on src/CMakeLists.txt
> +  target_link_libraries(cephfssqlite PRIVATE cls_lock_client librados ceph-common SQLite3::SQLite3 ${EXTRALIBS})
```suggestion
  target_link_libraries(cephfssqlite PRIVATE client ceph-common SQLite3::SQLite3 ${EXTRALIBS})
```

2021-06-29 23:38 UTC, batrick commented on src/libcephfssqlite.cc
> +#include "SimpleRADOSStriper.h"
```suggestion
```

2021-06-29 23:38 UTC, batrick commented on src/libcephfssqlite.cc
> +    static const std::regex re1{"^file:/*(\\*[[:digit:]]+)([[:alnum:]-_./]+)\\?vfs=cephfs$"};
sqlite should strip the uri options, so you don't need `vfs=cephfs$`.

2021-07-01 01:49 UTC, tchaikov commented
> > what's the advantage of libcephfssqlite in comparison with libcephsqlite? like, what is its use case or performance characteristics ?
> 
> Generally the "ceph" VFS (libcephsqlite) should be preferred but if the database is on CephFS, this VFS ("cephfs") lets you interact with that database without formally mounting CephFS (ceph-fuse/kernel).
> 
> The use-case is likely a metadata store within a ceph-mgr plugin that predominately stores its metadata on CephFS already, like the "volumes" plugin. 

yeah, this makes lots of sense now. thank you!

> Putting it in CephFS rather than RADOS can be advantageous because then admins can interact with the database without any special sqlite3 plugins (e.g. if using the kernel client). But admittedly the advantage is small. In the end, this just gives users more options.

i see. easier when debugging and/or tuning the sqlite3 db.

> 
> Finally, this code is just a prototype at this point. I'll mark this as a draft.

2021-08-09 15:16 UTC, batrick commented
@mark15213 please push an update with your latest work.

2021-08-16 22:29 UTC, batrick requested changes
Also need some documentation for `libcephfssqlite`. Probably should be a separate page under the ToC "Mounting CephFS":

https://docs.ceph.com/en/latest/cephfs/#mounting-cephfs

2022-11-28 07:01 UTC, closed without merging