ceph-volume: lvm batch: fast_allocations(): avoid ZeroDivisionError
ceph/ceph pull request #42181
Opened 2021-07-05 13:06 UTC by lyind

ceph-volume: Ensures the divisor (`len(phys_devs)`)  is never 0 but always 1 or greater.

Avoid ZeroDivisionError, when specifying only LVs (logical volumes) and 0 physical devices, in ceph-volume function fast_allocations() in batch.py.

Fixes Bug https://tracker.ceph.com/issues/51526
Signed-off-by: Jonas Zeiger <jonas.zeiger@talpidae.net>

2021-07-05 17:11 UTC, lyind commented
In case it helps I tested the code:

### Without PR applied

```
CEPH_VOLUME_DEBUG=1 CEPH_VOLUME_SKIP_RESTORECON=1 DM_DISABLE_UDEV=1 ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 --crush-device-class hdd --block-db-size 71999422464 /dev/sdb --db-devices vg-metadata-0/metadata-0-1 --report
parsing /dev/sdb
parsing vg-metadata-0/metadata-0-1
--> passed data devices: 1 physical, 0 LVM
--> relative data size: 1.0
--> passed block_db devices: 0 physical, 1 LVM
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 412, in main
    plan = self.get_plan(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 450, in get_plan
    args.wal_devices)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 482, in get_deployment_layout
    fast_type)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 524, in fast_allocations
    if (requested_osds - len(lvm_devs)) % len(phys_devs):
ZeroDivisionError: integer division or modulo by zero
```

### With PR applied

```
CEPH_VOLUME_DEBUG=1 CEPH_VOLUME_SKIP_RESTORECON=1 DM_DISABLE_UDEV=1 ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 --crush-device-class hdd --block-db-size 71999422464 /dev/sdb --db-devices vg-metadata-0/metadata-0-1 --report
parsing /dev/sdb
parsing vg-metadata-0/metadata-0-1
--> passed data devices: 1 physical, 0 LVM
--> relative data size: 1.0
--> passed block_db devices: 0 physical, 1 LVM

Total OSDs: 1

  Type            Path                                                    LV Size         % of device
----------------------------------------------------------------------------------------------------
  encryption:     dmcrypt        
  data            /dev/sdb                                                1.55 TB         100.00%
  block_db        vg-metadata-0/metadata-0-1                              67.07 GB        10000.00%

```

2021-07-08 15:36 UTC, guits commented
jenkins test ceph-volume all

2021-07-08 15:49 UTC, dsavineau commented
jenkins test ceph-volume tox

2021-07-19 20:37 UTC, andrewschoen requested changes
Thanks, this looks good. Could you please add a test for this scenario? Similar tests can be found in: `tests/devices/lvm/test_batch.py`.

2021-07-21 08:50 UTC, lyind commented
> Thanks, this looks good. Could you please add a test for this scenario? Similar tests can be found in: `tests/devices/lvm/test_batch.py`.

I added test `test_batch_fast_allocations_one_block_db_length()` to `test_batch.py`.

The test fixture function `mock_lv_device_generator()` in `conftest.py` needed modification, because the generated devices were not recognized as LVs by the tested code (for LVs `dev.is_device = False` and `dev.is_available = True`).

### Test Result Without Fix

```
PYTHONPATH=src/python-common python3 -m pytest src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py 
===================================================== test session starts =====================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/jonas.zeiger/prog/ceph/src/ceph-volume
collected 438 items                                                                                                           

src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py ........................................................... [ 13%]
....................................................................................................................... [ 40%]
...................................................................................................F................... [ 67%]
....................................................................................................................... [ 94%]
......................                                                                                                  [100%]

========================================================== FAILURES ===========================================================
__________________________________ TestBatch.test_batch_fast_allocations_one_block_db_length __________________________________

self = <ceph_volume.tests.devices.lvm.test_batch.TestBatch object at 0x7fdd7ee5fbb0>
factory = <class 'ceph_volume.tests.conftest.Factory'>
conf_ceph_stub = <function conf_ceph_stub.<locals>.apply at 0x7fdd7eb67940>
mock_lv_device_generator = <function mock_lv_device_generator.<locals>.mock_lv at 0x7fdd7efd9550>

    def test_batch_fast_allocations_one_block_db_length(self, factory, conf_ceph_stub,
                                                  mock_lv_device_generator):
        conf_ceph_stub('[global]\nfsid=asdf-lkjh')
        args = factory(block_db_slots=None, get_block_db_size=None)
    
        b = batch.Batch([])
        db_lv_devices = [mock_lv_device_generator()]
>       fast = b.fast_allocations(db_lv_devices, 1, 0, 'block_db')

src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py:228: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ceph_volume.devices.lvm.batch.Batch object at 0x7fdd7ed40910>
devices = [<MagicMock spec='Device' id='140589289050016'>], requested_osds = 1, new_osds = 0, type_ = 'block_db'

    def fast_allocations(self, devices, requested_osds, new_osds, type_):
        ret = []
        if not devices:
            return ret
        phys_devs, lvm_devs = separate_devices_from_lvs(devices)
        mlogger.debug(('passed {} devices: {} physical,'
                       ' {} LVM').format(type_, len(phys_devs), len(lvm_devs)))
    
        ret.extend(get_lvm_fast_allocs(lvm_devs))
    
        # fill up uneven distributions across fast devices: 5 osds and 2 fast
        # devices? create 3 slots on each device rather then deploying
        # heterogeneous osds
>       if (requested_osds - len(lvm_devs)) % len(phys_devs):
E       ZeroDivisionError: integer division or modulo by zero

src/ceph-volume/ceph_volume/devices/lvm/batch.py:521: ZeroDivisionError
---------------------------------------------------- Captured stderr call -----------------------------------------------------
--> passed block_db devices: 0 physical, 1 LVM
=================================================== short test summary info ===================================================
FAILED src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py::TestBatch::test_batch_fast_allocations_one_block_db_length
================================================ 1 failed, 437 passed in 5.46s ================================================
```

### Test Result With Fix PR Applied
```
PYTHONPATH=src/python-common python3 -m pytest src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py 
===================================================== test session starts =====================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/jonas.zeiger/prog/ceph/src/ceph-volume
collected 438 items                                                                                                           

src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py ........................................................... [ 13%]
....................................................................................................................... [ 40%]
....................................................................................................................... [ 67%]
....................................................................................................................... [ 94%]
......................                                                                                                  [100%]

===================================================== 438 passed in 5.52s =====================================================
```

2021-07-21 13:03 UTC, dsavineau commented
jenkins test ceph-volume tox

2021-07-21 18:23 UTC, andrewschoen commented on src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py
> +        args = factory(block_db_slots=None, get_block_db_size=None)
`args` is defined here and not used, which is causing the flake8 tests to fail.

2021-07-21 18:26 UTC, andrewschoen commented
> > Thanks, this looks good. Could you please add a test for this scenario? Similar tests can be found in: `tests/devices/lvm/test_batch.py`.
> 
> I added test `test_batch_fast_allocations_one_block_db_length()` to `test_batch.py`.

@lyind Thanks for adding that test. If you can fix up the flake8 failure I think this should be good to go.

2021-07-22 09:22 UTC, lyind commented
> > > Thanks, this looks good. Could you please add a test for this scenario? Similar tests can be found in: `tests/devices/lvm/test_batch.py`.
> > 
> > 
> > I added test `test_batch_fast_allocations_one_block_db_length()` to `test_batch.py`.
> 
> @lyind Thanks for adding that test. If you can fix up the flake8 failure I think this should be good to go.

@andrewschoen Thank you for your thorough review. I initially experimented with a different approach to test the change and forgot to remove the `args` definition.

2021-07-22 13:36 UTC, dsavineau commented
jenkins test ceph-volume tox

2021-07-22 14:24 UTC, andrewschoen commented
jenkins test ceph-volume all

2021-07-22 14:48 UTC, dsavineau approved these changes

2021-07-22 15:00 UTC, andrewschoen approved these changes

2021-07-25 00:58 UTC, guits commented
jenkins test ceph-volume batch centos8-bluestore-mixed_type

2021-07-25 00:58 UTC, guits commented
jenkins test ceph-volume lvm centos8-filestore-create

2021-07-26 19:31 UTC, guits commented
jenkins test ceph-volume batch centos8-bluestore-mixed_type

2021-07-26 19:57 UTC, guits approved these changes

2021-07-26 19:58 UTC, merged