mgr/cephadm/templates: add jinja2 lint
ceph/ceph pull request #42342
Opened 2021-07-14 19:15 UTC by dsavineau

This adds a jinja2 lint environment in tox for testing the cephadm jinja2
templates.

This patch fixes some minor jinja2 syntax for ganesha and keepalived even if
the current templates work perfectly.

Tags should have one (and only one) space

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-07-14 19:53 UTC, liewegas approved these changes

2021-07-20 11:42 UTC, sebastian-philipp commented
https://pulpito.ceph.com/swagner-2021-07-20_10:26:40-rados:cephadm-wip-swagner2-testing-2021-07-19-1105-distro-basic-smithi/

failure caused by #42389

2021-07-20 11:46 UTC, sebastian-philipp requested changes

2021-07-20 11:46 UTC, sebastian-philipp commented on src/pybind/mgr/tox.ini
> +[testenv:jinjalint]
this is not integrated into make check: 

https://github.com/ceph/ceph/blob/669660e70602c8fe1d4b2a5887f25993bb26f5f1/src/pybind/mgr/CMakeLists.txt#L9

2021-07-20 13:59 UTC, sebastian-philipp approved these changes

2021-07-22 05:28 UTC, merged