Solved issue CLEANUP #51393
ceph/ceph pull request #42364
Opened 2021-07-15 18:58 UTC by Astroakanksha24

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-07-15 18:59 UTC, Astroakanksha24 commented
I am solving this issue under OSD

2021-07-15 19:03 UTC, varshar16 commented
Hi Akansha, please see the submitting patches doc and update the patch with `git commit --amend`.

2021-07-15 19:05 UTC, varshar16 commented
Also add this tracker to the patch: https://tracker.ceph.com/issues/51393

2021-07-15 19:38 UTC, batrick requested changes
Please [sign your commits](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work). This is required for your PR to be merged.

See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

2021-07-16 07:17 UTC, Astroakanksha24 commented
Done.

2021-07-16 07:22 UTC, Astroakanksha24 commented
@varshar16  please check this one!

2021-07-16 07:48 UTC, varshar16 requested changes
The commits are little messed up. Please rebase the commit by `git rebase origin/master`,  update the patch with `git commit --amend` and push amended changes using `git push -f`. Check `git log` or history of this file to get ideas about commit title and message.

2021-07-16 07:48 UTC, varshar16 commented on src/pybind/mgr/volumes/fs/operations/group.py
> +
Remove this extra line. See [this](https://www.flake8rules.com/rules/E302.html) to understand why the extra blank line is required.

2021-07-16 08:14 UTC, varshar16 commented
@Astroakanksha24 you need to still rebase your patch but the final commit looks good. The commit message needs to be
``
Fixes: https://tracker.ceph.com/issues/51385
Signed-off-by: Akanksha Chaudhari <astroakanksha24@gmail.com>
``

2021-07-16 08:15 UTC, varshar16 commented
The commit title is wrong. It needs to be `mgr/volumes/fs/operations/group: add extra blank line`

2021-07-16 09:33 UTC, varshar16 commented
Please fix up the commit message of this commit ca5a9a7
```
Fixes: https://tracker.ceph.com/issues/51385
Signed-off-by: Akanksha Chaudhari <astroakanksha24@gmail.com>
```
And in other replace the tracker ticket with https://tracker.ceph.com/issues/51393

2021-07-16 09:40 UTC, varshar16 commented
There are extra commits. Please rebase your PR

2021-07-16 10:21 UTC, ideepika commented
@Astroakanksha24 I guess this might be helpful, for correcting the history right now I see unrelated commits in this PR:

https://stackoverflow.com/questions/64288648/git-history-screwed-up
1. Once you have pre rebased state, to do correct rebase you need to pass "a commit prior to the one you want to change things"
2. please squash and add related `Fixes:` line as @varshar16 suggested

HTH

2021-07-23 18:56 UTC, closed without merging