mgr/dashboard,prometheus: fix handling of server_addr
ceph/ceph pull request #42716
Opened 2021-08-08 20:30 UTC by sshambar

Commit 157a7b4 corrected the URI published by dashboard/prometheus
to use get_mgr_ip() if the address was the wildcard (eg ::).
However, the change also affected the cherrypy server.socket_host
config value, so the modules could no longer bind to a wildcard.

This patch corrects the commit to not affect the cherrypy config.

It also further corrects the dashboard URI fix to handle the 0.0.0.0
wildcard case (prometheus already had this behavior).

Fixes: 157a7b4183dbd888f106c613a758409d7e07b917
Fixes: http://tracker.ceph.com/issues/52002
Signed-off-by: Scott Shambarger <devel@shambarger.net>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-09-01 16:38 UTC, epuertat commented
@sshambar are you ok with the fix provided by https://github.com/ceph/ceph/pull/42793? If so, can we close this PR? Thanks!

2021-09-03 22:30 UTC, sshambar commented
Updated to fix conflict...

2021-09-07 14:56 UTC, epuertat commented
@liewegas @sebastian-philipp I remember you recently changed this, so what do you think about this change? It'll allow users bind Cherrypy to listen to all interfaces, while still displaying the specific mgr IP address in the `ceph mgr services` output.

@sshambar you need to copy the `# ignore type` hint too. Otherwise, CI doesn't pass.

2021-09-07 16:58 UTC, sshambar commented
> @sshambar you need to copy the `# ignore type` hint too. Otherwise, CI doesn't pass.

Done...was wondering what that strange comment was for :)

2021-09-08 09:23 UTC, sebastian-philipp requested changes

2021-09-08 09:23 UTC, sebastian-philipp commented on src/pybind/mgr/prometheus/module.py
> +        })
This change super deceiving actually. If you want to allow binding to `::` or `0.0.0.0` you have to make this explicit. This change deceiving moves the `cherrypy.config.update` block before we're properly setting server_addr. 

With this change, `cherrypy` and `self.set_uri` would be called with two different `server_addr`. 

If you want to be able to bind to `::`, make it explicit please.

2021-09-08 09:26 UTC, sebastian-philipp commented
> @liewegas @sebastian-philipp I remember you recently changed this, so what do you think about this change? 

Took me a while to understand the intend of this PR.

2021-09-08 14:23 UTC, liewegas approved these changes

2021-09-08 14:24 UTC, liewegas commented
```
./module.py:196:44: E261 at least two spaces before inline comment
1     E261 at least two spaces before inline comment
```

2021-09-08 14:25 UTC, sebastian-philipp commented
@liewegas 

> liewegas approved these changes 42 seconds ago

This PR removes the ability to bind the dashboard to a specific port

2021-09-08 15:56 UTC, sshambar commented
> ```
> ./module.py:196:44: E261 at least two spaces before inline comment
> 1     E261 at least two spaces before inline comment
> ```

Fixed.

2021-09-14 13:13 UTC, sebastian-philipp commented
> > @liewegas
> > > liewegas approved these changes 42 seconds ago
> > 
> > 
> > This PR removes the ability to bind the dashboard to a specific port
> 
> The config for "server_port" and "ssl_server_port" are retrieved on line 109/111, and are passed to cherrypy on line 138.
> 
> Wildcard address binding is independent of the port binding... the change just restores the default behavior prior to the url fix.

Turnd out, we need the ability to, quote, "bind to the current MGR's IP address". Unfortunately this doesn't work using the module's option as this would be a fixed address. That's why I said we need to somehow distinguish between:

1. bind to ::
2. bind to the current MGR's IP address (dynamically generated)
3. bing to a configured IP address as specified by the module option

Any idea?

2021-09-14 15:15 UTC, liewegas commented
Even if we bind the ::, we still have to advertise a URL, so I think this PR makes sense.  If you dont want to bind to ::, but want a specific IP, you can configure that explicitly.. but by default binding to the wildcard and advertising the mgr ip seems just find?

2021-09-14 17:33 UTC, sshambar commented
Rebasing...

2021-09-14 17:57 UTC, sshambar commented
> Turnd out, we need the ability to, quote, "bind to the current MGR's IP address". Unfortunately this doesn't work using the module's option as this would be a fixed address. That's why I said we need to somehow distinguish between:
> 
>     2. bind to the current MGR's IP address (dynamically generated)

Sounds like a candidate for a service tag of some type... perhaps using "_manager._ceph" (or something else that should not appear in DNS as an A/AAAA record) and have that value handled specifically.  The default wildcard covers binding to the manager ip, just not "exclusively" - but this sounds like it should be a feature request that should be vetted and spec'd so that whatever is used can apply to other services too... it'd also be a candidate for a "virtual IP"

2021-10-01 15:31 UTC, epuertat commented
jenkins test dashboard

2021-10-01 15:31 UTC, epuertat approved these changes

2021-10-01 15:41 UTC, epuertat commented
jenkins test dashboard

2021-10-01 16:12 UTC, merged