mgr/dashboard: disable create snapshot with subvolumes
ceph/ceph pull request #42732
Opened 2021-08-10 08:23 UTC by pereman2

It was suggested to disable or show an error when trying to create a snapshot. I decided to go with disabling the button so we can prevent this error without calling the api and even though you can't see, it shows a message as of why you cannot create a snapshot when hovering the button(I don't know how to screenshot hovering the button lmao).

I also found this weird behaviour. Every folder/file in the volume and subvolumes have the same uid and mode but you cannot create directories files on the .snap folder inside a subovolume folder but you can in another place. For example:
```
[mgr self-test eval] >>> cfs.statx('/volumes/_nogroup/subvol', 0xFFFF, 0)
{'mode': 16877, 'nlink': 3, 'uid': 0, 'gid': 0, 'rdev': 0, 'atime': datetime.datetime(2021, 8, 9, 9, 44, 20), 'mtime': datetime.datetime(2021, 8, 9, 9, 44, 20), 'ctime': datetime.datetime(2021, 8, 9, 9, 44, 20), '
ino': 1099511628783, 'size': 125, 'blocks': 1, 'btime': datetime.datetime(2021, 8, 9, 9, 44, 20), 'version': 2}
[mgr self-test eval] >>> cfs.statx('/volumes/_nogroup/subvol/.snap', 0xFFFF, 0)
{'mode': 16877, 'nlink': 2, 'uid': 0, 'gid': 0, 'rdev': 0, 'atime': datetime.datetime(2021, 8, 9, 9, 44, 20), 'mtime': datetime.datetime(2021, 8, 9, 9, 44, 20), 'ctime': datetime.datetime(2021, 8, 9, 9, 44, 20), '
ino': 1099511628783, 'size': 0, 'blocks': 1, 'btime': datetime.datetime(2021, 8, 9, 9, 44, 20), 'version': 2}
[mgr self-test eval] >>> cfs.mkdir('/volumes/_nogroup/subvol/.snap/snapshot', 0o755)
[mgr self-test eval] >>> cfs.mkdir('/volumes/_nogroup/subvol/subfolder', 0o755)
[mgr self-test eval] >>> cfs.mkdir('/volumes/_nogroup/subvol/subfolder/.snap', 0o755)
[mgr self-test eval] >>> cfs.mkdir('/volumes/_nogroup/subvol/subfolder/.snap/snapshot', 0o755) # should this work?
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "cephfs.pyx", line 1022, in cephfs.LibCephFS.mkdir
cephfs.PermissionError: error in mkdir /volumes/_nogroup/subvol/subfolder/.snap/snapshot: Operation not permitted [Errno 1]
[mgr self-test eval] >>> cfs.mkdir('/volumes/_nogroup/subvol/subfolder/nothidden', 0o755)
[mgr self-test eval] >>> cfs.mkdir('/volumes/_nogroup/subvol/subfolder/nothidden/works', 0o755)

[mgr self-test eval] >>> clear
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'clear' is not defined
[mgr self-test eval] >>> ls
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'ls' is not defined
[mgr self-test eval] >>> cfs.mkdir('/subfolder', 0o755)
[mgr self-test eval] >>> cfs.mkdir('/subfolder/.snap/e', 0o755) # this works

```

![image](https://user-images.githubusercontent.com/30913090/128832799-fdb4d87f-3059-420b-9ebe-3e6cf9aa9ef2.png)

Signed-off-by: Pere Diaz Bou <pdiazbou@redhat.com>
Fixes: [ticket URL on tracker.ceph.com, create one if necessary]

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-08-10 13:52 UTC, votdev commented
Is this issue related to https://tracker.ceph.com/issues/48686?

2021-08-12 11:31 UTC, alfonsomthd commented
@pereman2 mak check failed:
`
[lint:prettier] src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.spec.ts
`

2021-08-12 11:53 UTC, alfonsomthd requested changes

2021-08-12 11:53 UTC, alfonsomthd commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.spec.ts
> +        }
```suggestion
        expect(actions[0].disable(empty())).toContain(res);
```

2021-08-12 11:53 UTC, alfonsomthd commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.spec.ts
> +        const res = 'Cannot create snapshots for the sobvolume subvol\'s files/folders';
```suggestion
        const res = 'Cannot create snapshots for the subvolume subvol\'s files/folders';
```

2021-08-12 11:53 UTC, alfonsomthd commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.spec.ts
> +          }
```suggestion
          expect(actions[0].disable(empty())).toBeFalsy();
```

2021-08-12 11:53 UTC, alfonsomthd commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.ts
> +    }
```suggestion
    }

    return false;
```

2021-08-16 06:50 UTC, pereman2 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-directories/cephfs-directories.component.spec.ts
> +        }
done

2021-08-16 16:50 UTC, alfonsomthd commented
jenkins test make check

2021-08-16 16:51 UTC, alfonsomthd commented
jenkins test dashboard

2021-08-16 16:51 UTC, alfonsomthd commented
jenkins test dashboard cephadm

2021-08-17 06:24 UTC, alfonsomthd commented
jenkins test dashboard

2021-08-17 09:58 UTC, alfonsomthd commented
jenkins test dashboard

2021-08-17 10:30 UTC, alfonsomthd commented
jenkins test dashboard

2021-08-17 10:34 UTC, avanthakkar approved these changes

2021-08-17 10:55 UTC, nizamial09 approved these changes
LGTM! Thanks

2021-08-17 12:35 UTC, alfonsomthd approved these changes

2021-08-17 12:35 UTC, merged