mgr/nfs: add more debug log msg
ceph/ceph pull request #42782
Opened 2021-08-16 05:51 UTC by varshar16

Fixes: https://tracker.ceph.com/issues/52274

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-08-16 12:02 UTC, varshar16 commented
jenkins test make check

2021-08-16 15:37 UTC, batrick requested changes

2021-08-16 15:37 UTC, batrick commented on src/pybind/mgr/nfs/export.py
> +        log.debug(f"Succefully created {fsal_type} export-{ex_id} from dict for cluster {cluster_id}")
```suggestion
        log.debug(f"Successfully created {fsal_type} export-{ex_id} from dict for cluster {cluster_id}")
```

2021-08-16 16:34 UTC, varshar16 commented on src/pybind/mgr/nfs/export.py
> +        log.debug(f"Succefully created {fsal_type} export-{ex_id} from dict for cluster {cluster_id}")
Done

2021-08-16 21:06 UTC, batrick approved these changes

2021-08-17 06:21 UTC, alfonsomthd commented on src/pybind/mgr/nfs/cluster.py
> +        log.debug(f"Successfully created nfs-ganesha pool {POOL_NAME}")
Just an observation: [it's recommended to use Lazy Logging](https://medium.com/swlh/why-it-matters-how-you-log-in-python-1a1085851205) (in Dashboard module the linter complains about this).

2021-09-30 01:39 UTC, closed without merging