mgr/dashboard: Fix redirect to active MGR
ceph/ceph pull request #42793
Opened 2021-08-16 12:15 UTC by sebastian-philipp

Fixes: https://tracker.ceph.com/issues/52117
Signed-off-by: Sebastian Wagner <sewagner@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-08-16 14:41 UTC, avanthakkar requested changes
LGTM! Just left some minor changes. Thanks @sebastian-philipp

2021-08-16 14:41 UTC, avanthakkar commented on src/pybind/mgr/dashboard/module.py
> +    prepare_url_prefix, str_to_bool, build_url
`ERROR: /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/module.py Imports are incorrectly sorted and/or formatted.`
```suggestion
    build_url, prepare_url_prefix, str_to_bool
```

2021-08-16 14:41 UTC, avanthakkar commented on src/pybind/mgr/dashboard/module.py
> +            port=server_port,
```suggestion
            port=server_port
```

2021-08-16 14:48 UTC, nizamial09 commented
jenkins test dashboard

2021-08-18 10:01 UTC, sebastian-philipp commented
```
lint run-test-pre: PYTHONHASHSEED='782397422'
lint run-test: commands[0] | flake8
./rest_client.py:331:23: W291 trailing whitespace
./rest_client.py:332:28: W291 trailing whitespace
./rest_client.py:333:28: W291 trailing whitespace

2021-08-19 00:31 UTC, neha-ojha approved these changes
👍

2021-08-19 07:57 UTC, p-se approved these changes
lgtm

2021-08-19 09:42 UTC, avanthakkar approved these changes

2021-08-19 11:12 UTC, merged

2021-08-19 12:27 UTC, tchaikov commented
@alfonsomthd in future, could you please add a "Reviewed-by" line in the commit message of the merge commit when merging a PR?

2021-08-19 12:36 UTC, alfonsomthd commented
> @alfonsomthd in future, could you please add a "Reviewed-by" line in the commit message of the merge commit when merging a PR?

Of course, sorry about that. I completely forgot about it.