(doc) Added msgr on-wire-compression
ceph/ceph pull request #42839
Opened 2021-08-18 21:32 UTC by giladmaya

(doc) Added msgr on-wire-compression (feature introduces in #36517)

2021-08-24 09:04 UTC, JoshSalomon commented
@rzarzynski - any news?

2021-08-24 10:35 UTC, rzarzynski requested changes

2021-08-24 10:35 UTC, rzarzynski commented on doc/dev/msgr2.rst
> +Compression handshake is implemened using msgr2 feature-based handshaking.
```suggestion
Compression handshake is implemented using msgr2 feature-based handshaking.
```

2021-08-24 10:35 UTC, rzarzynski commented on doc/dev/msgr2.rst
> +In this phase, the peers exchange their supported compression methods and if compression is desired.
How about rephrasing this line? _the peers exchange (...) and if compression is desired_ is hard to grasp.

2021-08-24 10:35 UTC, rzarzynski commented on doc/rados/configuration/msgr2.rst
> +The v2 protocol supports two authentication modes:
I doubt this replacement is an improvement. These modes are far more than just authentication (they include e.g. data intgrity0. I propose to leave this intact or dissect into a separated PR.

2021-08-24 10:35 UTC, rzarzynski commented on doc/rados/configuration/msgr2.rst
> +There are a parallel set of options that apply specifically to osds,
```suggestion
There is a parallel set of options that apply specifically to OSDs,
```

2021-08-24 10:35 UTC, rzarzynski commented on doc/rados/configuration/msgr2.rst
> +allowing administrators to set different requirements on communication between osds.
```suggestion
allowing administrators to set different requirements on communication between OSDs.
```

2021-08-24 10:35 UTC, rzarzynski commented on doc/rados/configuration/msgr2.rst
> +  - In multi availability zones deployment, compressing replication messages between osds saves latency.
```suggestion
  - In multi-availability zones deployment, compressing replication messages between OSDs saves latency.
```

2021-08-24 10:36 UTC, rzarzynski commented
Generally LGTM. Just one thing + a bunch of minors / nits.

2021-10-07 19:49 UTC, rzarzynski approved these changes
@JoshSalomon: LGTM. There is a minor typo. It would be preferable to have it fixed before the merge but I would be also fine with a follow-up fix.

2021-10-19 21:55 UTC, merged