mds: Add new flag to MClientSession
ceph/ceph pull request #42846
Opened 2021-08-19 11:32 UTC by kotreshhr

The "error_string" in the metadata of MClientSession is being
parsed by kclient to validate whether the session is blocklisted.
The "error_string" is for humans and shouldn't be relied on it.
Hence added the flag to MClientsession to indicate the session
is blocklisted.

Signed-off-by: Kotresh HR <khiremat@redhat.com>
Fixes: https://tracker.ceph.com/issues/47450

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-08-19 15:34 UTC, kotreshhr commented
jenkins test make check

2021-08-20 02:12 UTC, kotreshhr commented
jenkins test make check

2021-08-23 17:16 UTC, batrick requested changes
Needs encode/decode handlers for the new flag and a version bump on the message.

2021-08-23 17:16 UTC, batrick commented on src/messages/MClientSession.h
> +  static constexpr unsigned FLAG_BLOCKLISTED = (1<<0);
```suggestion
  static constexpr unsigned SESSION_BLOCKLISTED = (1<<0);
```

2021-08-23 17:16 UTC, batrick commented on src/messages/MClientSession.h
>      SafeMessage{CEPH_MSG_CLIENT_SESSION, HEAD_VERSION, COMPAT_VERSION} {
```suggestion
    SafeMessage{CEPH_MSG_CLIENT_SESSION, HEAD_VERSION, COMPAT_VERSION},
    flags(msg_flags) {
```

2021-08-23 17:16 UTC, batrick commented on src/messages/MClientSession.h
> +    flags = msg_flags;
```suggestion
```

2021-08-23 17:18 UTC, batrick commented
Please update tracker to: https://tracker.ceph.com/issues/52382

2021-08-30 08:18 UTC, kotreshhr commented
> Please update tracker to: https://tracker.ceph.com/issues/52382

Done

2021-09-10 17:51 UTC, batrick approved these changes

2021-09-16 02:31 UTC, batrick commented
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-September-10

2021-09-16 02:35 UTC, merged