doc/mgr: Add cli api documentation
ceph/ceph pull request #42996
Opened 2021-08-31 15:51 UTC by Waadkh7

Fixes: https://tracker.ceph.com/issues/52120
Signed-off-by: Waad AlKhoury <walkhour@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-10-04 13:40 UTC, pereman2 reviewed
nits

2021-10-04 13:40 UTC, pereman2 commented on doc/mgr/cli_api_commands.rst
> +  ceph mgr cli benchmark <api> <param> <number of calls> <number of threads>
```suggestion
To run a mgr module command, run::

  ceph mgr cli <command> <param>

List all available mgr module commands with , run::

  ceph mgr cli --help

To benchmark a command, run::

  ceph mgr cli benchmark <command> <param> <number of calls> <number of threads>
```

2021-10-04 13:40 UTC, pereman2 commented on doc/mgr/cli_api_commands.rst
> +The CLI API module expose most ceph-mgr python API via CLI and benchmarking them.
```suggestion
The CLI API module exposes most ceph-mgr python API via CLI. Furthermore, this API can be benchmarked for further testing.
```

2021-11-02 07:42 UTC, alfonsomthd approved these changes

2021-12-02 15:51 UTC, alfonsomthd requested changes

2021-12-02 15:51 UTC, alfonsomthd commented on doc/mgr/cli_api_commands.rst
> +  ceph mgr module enable cli_api_commands
```suggestion
  ceph mgr module enable cli_api
```

2021-12-02 15:51 UTC, alfonsomthd commented on doc/mgr/cli_api_commands.rst
> +  ceph mgr module ls
```suggestion
  ceph mgr module ls | grep cli_api
```

2021-12-02 15:51 UTC, alfonsomthd commented on doc/mgr/index.rst
> +    CLI API Commands module <cli_api_commands>
```suggestion
    CLI API Commands module <cli_api>
```

2021-12-07 08:06 UTC, merged