pacific: pybind/mgr: Fix IPv6 url generation
ceph/ceph pull request #42990
Opened 2021-08-31 10:33 UTC by epuertat

backport tracker: https://tracker.ceph.com/issues/52325

---

backport of https://github.com/ceph/ceph/pull/42793
parent tracker: https://tracker.ceph.com/issues/52117

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-08-31 10:35 UTC, sebastian-philipp requested changes
Please also add #42886

2021-08-31 11:03 UTC, sebastian-philipp approved these changes

2021-08-31 11:24 UTC, avanthakkar approved these changes

2021-09-01 08:01 UTC, pereman2 approved these changes

2021-09-01 12:15 UTC, avanthakkar commented
jenkins test dashboard

2021-09-05 21:07 UTC, avanthakkar commented
jenkins test dashboard

2021-09-07 12:52 UTC, epuertat commented
jenkins test dashboard

2021-09-08 15:51 UTC, merged