mgr/dashboard: Incorrect MTU mismatch warning
ceph/ceph pull request #43019
Opened 2021-09-02 06:41 UTC by aaSharma14

The MTU mismatch warning was being fired for those NIC's as well that are in down state. This PR intends to fix this issue

Fixes:https://tracker.ceph.com/issues/52028
Signed-off-by: Aashish Sharma <aasharma@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-09-02 10:19 UTC, avanthakkar approved these changes
lgtm!

2021-09-07 13:18 UTC, p-se approved these changes
lgtm

2021-09-08 08:40 UTC, aaSharma14 commented
jenkins test dashboard cephadm

2021-09-08 20:10 UTC, epuertat requested changes

2021-09-08 20:10 UTC, epuertat commented on monitoring/prometheus/alerts/ceph_default_alerts.yml
> +        expr: node_network_mtu_bytes{device!="lo"} * (node_network_up{device!="lo"} > 0) != on() group_left() (quantile(0.5, node_network_mtu_bytes{device!="lo"}))
Based on the comments we got from this issue, I think we should additionally ignore the MTU value of interfaces down... and for that we'll need the NIC metadata table!! 🙈

2021-09-09 10:22 UTC, epuertat commented
BTW I see cephadm has now some config check, among which [there's an MTU one](https://tracker.ceph.com/issues/52558). Shall we remove this from here (for consistency) and maybe exposing the MTU alert via Prometheus - Alertmanager?

2021-09-15 13:40 UTC, epuertat approved these changes
+1

2021-09-15 13:40 UTC, merged