mgr/rook: update `ceph orch apply nfs`
ceph/ceph pull request #43046
Opened 2021-09-03 16:20 UTC by josephsawaya

This PR updates the `ceph orch apply nfs` command in the Rook orchestrator to keep up with the changes made to the NFS module by preventing the creation of NFS daemons not using the '.nfs' RADOS pool and creating the pool if it doesn't exist when a user tries to create an NFS daemon.

Depends on [rook #8501](https://github.com/rook/rook/pull/8501)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-09-08 02:05 UTC, varshar16 requested changes
Please address the following comments

2021-09-08 02:05 UTC, varshar16 commented on src/pybind/mgr/rook/rook_cluster.py
> +        service_id = spec.service_id if spec.service_id is not None else ""
`service_id` should never be empty string. Add a check for both None and empty string

2021-09-09 16:31 UTC, varshar16 requested changes
Apart from the comment below, it would be great if you can add qa tests.

2021-09-09 16:31 UTC, varshar16 commented on src/pybind/mgr/rook/rook_cluster.py
> +from nfs.module import Module
Please move this import below `from nfs.cluster import create_ganesha_pool`

2021-09-09 16:31 UTC, varshar16 commented on src/pybind/mgr/rook/rook_cluster.py
> +from nfs.export import NFSRados
Please move this import below `from nfs.cluster import create_ganesha_pool`

2021-09-09 16:31 UTC, varshar16 commented on src/pybind/mgr/rook/rook_cluster.py
> +            raise RuntimeError("service id in NFS service spec cannot be an empty string")
```suggestion
        assert spec.service_id, "service id in NFS service spec cannot be an empty string or None " # for mypy typing
```

2021-09-10 20:29 UTC, varshar16 requested changes
Please move the imports. Otherwise looks good.

2021-09-10 20:29 UTC, varshar16 commented on src/pybind/mgr/rook/rook_cluster.py
> +from nfs.cluster import create_ganesha_pool
According to [PEP 8 style guide](https://www.python.org/dev/peps/pep-0008/#imports), imports should be grouped in the following order:
Standard library imports.
Related third party imports.
Local application/library specific imports

```suggestion
from nfs.cluster import create_ganesha_pool
from nfs.module import Module
from nfs.export import NFSRados
```

2021-09-10 22:50 UTC, varshar16 approved these changes
Please run the qa tests after the depending PR is merged. Otherwise looks good.

2021-09-14 10:28 UTC, jmolmo commented on src/pybind/mgr/rook/module.py
> +        elif service_type == 'ingress':
This is not harmful,, but I think that nobody is going to create an ingress service in a rook cluster, so difficult to reach this point. In any case, i think the operation that must be blocked is the creation of an orchestrator ingress service within the rook orchestrator

2021-09-14 11:52 UTC, jmolmo commented on src/pybind/mgr/rook/rook_cluster.py
> +        assert spec.service_id, "service id in NFS service spec cannot be an empty string or None " # for mypy typing
No error management... we have commented about this problem in other PRs. Basically if we do not include a basic error management in this methods, we are reporting managing programming and unexpected errors  in the same way that errors related to the operative.
At least, we should avoid to dump the stack trace in the console ( is good to do that in the log... but in the console causes panic in final users) 

Example:

```
# ceph orch apply nfs jmo_nfs

Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1564, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 167, in handle_command
    return dispatch[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 415, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 107, in <lambda>
    wrapper_copy = lambda *l_args, **l_kwargs: wrapper(*l_args, **l_kwargs)  # noqa: E731
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/module.py", line 1155, in _apply_nfs
    return self._apply_misc([spec], dry_run, format, no_overwrite)
  File "/usr/share/ceph/mgr/orchestrator/module.py", line 1062, in _apply_misc
    raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 224, in raise_if_exception
    raise e
kubernetes.client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '611aedf2-314e-4f9b-a828-1c2c5a292027', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '21f0f9d3-30f5-4bef-a93b-e25595220817', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'ce436ed7-8716-4a58-8b63-07fd783fdd5c', 'Date': 'Tue, 14 Sep 2021 11:10:23 GMT', 'Content-Length': '908'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"CephNFS.ceph.rook.io \"jmo_nfs\" is invalid: metadata.name: Invalid value: \"jmo_nfs\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"jmo_nfs","group":"ceph.rook.io","kind":"CephNFS","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"jmo_nfs\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}]},"code":422}
```

2021-09-14 11:54 UTC, jmolmo commented on src/pybind/mgr/rook/module.py
>          elif service_type == 'nfs':
Ceph auth keys for the nfs service are not deleted. This is an operation to do in **ALL** the orchestrators

```
# ceph auth ls

client.nfs-ganesha.jmonfs.a
	key: AQChg0Bh5V7ZHRAAFMydhUKjSPKvZRxV7qTBsg==
	caps: [mon] allow r
	caps: [osd] allow rw pool=.nfs namespace=jmonfs

```

2021-09-14 11:55 UTC, jmolmo requested changes
Apart of the issues pointed in the comments, the list of the service is not properly managed:

```
[root@rook-ceph-tools-78cdfd976c-qc6fm /]# ceph orch ls
NAME          PORTS  RUNNING  REFRESHED  AGE  PLACEMENT  
crash                    3/3  0s ago     38m  *          
mgr                      1/1  0s ago     38m  count:1    
mon                      3/3  0s ago     39m  count:3    
nfs.test2nfs             0/1  0s ago     -    count:1  <--------------  Number of nfs pods not updated properly
```

2021-09-17 07:20 UTC, jmolmo approved these changes

2021-09-30 14:43 UTC, sebastian-philipp commented
jenkins test sign

2021-11-11 15:31 UTC, merged