osd: Replacing friend declerations for passkey interface
ceph/ceph pull request #43056
Opened 2021-09-05 19:08 UTC by Matan-B

removing friend decleration from PrimaryLogScrub and ReplicaReservations

Signed-off-by: Matan Breizman <Matan.Brz@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-09-08 08:43 UTC, ronen-fr requested changes
LGTM apart from some minor comments

2021-09-08 08:43 UTC, ronen-fr commented on src/osd/PG.h
> +
rm the extra line in this case

2021-09-08 08:43 UTC, ronen-fr commented on src/osd/PG.h
> +
rm the extra line in this case

2021-09-08 08:43 UTC, ronen-fr commented on src/osd/PG.h
> +class ScrubberPasskey {
Add a short comment to suggest use case.
Something like
"facilitating scrub-related object access to private PG data"

2021-09-08 08:43 UTC, ronen-fr commented on src/osd/PrimaryLogScrub.cc
> +  auto& info{m_pg->get_pg_info(ScrubberPasskey())};  ///< a temporary alias
{}

2021-09-08 08:43 UTC, ronen-fr commented on src/osd/PrimaryLogScrub.cc
> +  auto& info{m_pg->get_pg_info(ScrubberPasskey())};  ///< a temporary alias
to clarify that you are creating an object, not calling a function.

2021-09-08 08:43 UTC, ronen-fr commented on src/osd/pg_scrubber.h
> +  /// ScrubberPasskey Members
The comment is irrelevant here. We do not care about the mechanism at this specific point - just what this member does.

2021-09-09 09:09 UTC, ronen-fr approved these changes

2021-09-09 09:12 UTC, ronen-fr commented
Pls push it into 'ci', to make sure it compiles on all platforms.
Regarding Teuthology tests: not really important, as this a "compilation checked" change,
but do test with, e.g. rados::scrub

2021-09-10 16:36 UTC, jdurgin approved these changes
Nice cleanup! Always good to minimize the interface exposed, especially for an overly broad class like PG!

2021-09-12 12:45 UTC, ronen-fr commented
Compilation-verified change. Still:
Passed Teu testing:
Runs:
original: yuriw-2021-09-09_21:20:54-rados-wip-yuri-testing-2021-09-09-1227-distro-basic-smithi (9F, 16D)
rerun: yuriw-2021-09-10_14:25:47-rados-wip-yuri-testing-2021-09-09-1227-distro-basic-smithi (4F, 1D)

Failures:

#6382926: “cephadm/test_dashboard_e2e.sh” - dashboard related failure. Seems to be https://tracker.ceph.com/issues/52417
#6382927: mgr/rook: might be https://tracker.ceph.com/issues/52321
#6382940: ceph_test_objectstore crash. Opened https://tracker.ceph.com/issues/52576
#6382942: seems the same as #6382926

The dead job: test issue (reimaging)

2021-09-12 12:46 UTC, ronen-fr commented
Extra round of tests (thrash/scrub: all OK):
http://pulpito.front.sepia.ceph.com/matan-2021-09-12_09:32:47-rados:thrash-wip-matanb-scrub-passkey-distro-basic-smithi/

2021-09-12 12:47 UTC, merged