doc/radosgw: Added example for obtaining JWT token via Kerberos.
ceph/ceph pull request #43112
Opened 2021-09-09 09:41 UTC by rh-jpoole

Signed-off-by: James Poole <jpoole@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-09-10 16:17 UTC, ktdreyer commented on doc/radosgw/keycloak.rst
> +    from requests_kerberos import HTTPKerberosAuth, OPTIONAL
requests-kerberos is not well-maintained upstream and Fedora is dropping it entirely. requests-gssapi is an up-to-date replacement.

2021-09-10 16:18 UTC, ktdreyer commented on doc/radosgw/keycloak.rst
> +          kerberos_auth = HTTPKerberosAuth(mutual_authentication=OPTIONAL, force_preemptive=True)
requests-gssapi defaults `mutual_authentication` to `DISABLED`, so we can simplify that here.

2021-09-10 16:19 UTC, ktdreyer commented on doc/radosgw/keycloak.rst
> +            get_auth_response = session.get(base_url + auth_uri + "?" + urllib.parse.urlencode(access_code_params), verify=verify_ssl, auth=kerberos_auth, allow_redirects=False)
Instead of manually using `urlencode()`, we should be able to pass everything through requests' `params` kwarg, and we'll get encoding for free.

2021-09-10 16:20 UTC, ktdreyer commented on doc/radosgw/keycloak.rst
> +          except Exception as e:
Probably better to avoid the `try` and bare `except Exception` here, and just let the exceptions bubble up.

2022-07-01 02:54 UTC, anthonyeleven requested changes
I've left suggestions for docs.  I make no claims about the code; ktdreyer's comments should be considered there.

2022-07-01 02:54 UTC, anthonyeleven commented on doc/radosgw/keycloak.rst
> +The following python script takes various command line arguments to authenticate against Keycloak via Kerberos or Basic authentication to obtain a Java Web
s/python/Python/
s/various//

2022-07-01 02:54 UTC, anthonyeleven commented on doc/radosgw/keycloak.rst
> +Token. This token can then be exchanged for temporary credentials with the RADOS gateway in order to AssumeRoleWithWebIdentity:
s/RADOS gateway/RADOS GateWay (RGW)/

2022-12-12 23:26 UTC, mattbenjamin commented
unstahl

2023-02-11 00:09 UTC, mattbenjamin commented
unstahl

2023-05-12 02:13 UTC, closed without merging