octopus: rgw : add check for tenant provided in RGWCreateRole
ceph/ceph pull request #43270
Opened 2021-09-22 20:01 UTC by cfsnyder

backport tracker: https://tracker.ceph.com/issues/51778

---

backport of https://github.com/ceph/ceph/pull/41858
parent tracker: https://tracker.ceph.com/issues/51206

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-09-23 16:57 UTC, dang requested changes

2021-09-23 16:57 UTC, dang commented on src/rgw/rgw_rest_role.cc
> +  op_ret = role.create(s, true, y);
This bit appears to be wrong; it needs to be the line from above:
op_ret = role.create(true);

2021-10-04 15:25 UTC, cbodley commented
@dang can you please re-review? i think this is otherwise ready to merge

2021-10-04 15:28 UTC, yuriw commented
@dang pls merge if ready, this passed tests

2021-10-04 15:41 UTC, dang approved these changes

2021-10-04 15:42 UTC, dang commented
@yuriw I can't merge, because it says it's not signed off even though it is?

2021-10-04 16:07 UTC, cbodley commented
jenkins test signed

2021-10-04 16:59 UTC, merged