doc: fix reference to non-existent stable branch
ceph/ceph pull request #43388
Opened 2021-10-01 20:09 UTC by e337

doc: fix reference to non-existent stable branch

Fixes: #50499

Signed-off-by: Eunice Lee (eunice337@gmail.com)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-10-01 20:44 UTC, varshar16 commented
https://ceph--43388.org.readthedocs.build/en/43388/install/clone-source/#choose-a-branch

2021-10-01 20:46 UTC, varshar16 requested changes
The change looks good. Please add tracker ticket url(Fixes: https://tracker.ceph.com/issues/50499) to the commit message and also change `doc` -> `doc/install` in commit title.

2021-10-01 22:08 UTC, ideepika commented
jenkins render docs

2021-10-07 03:33 UTC, ideepika commented
> The change looks good. Please add tracker ticket url(Fixes: https://tracker.ceph.com/issues/50499) to the commit message and also change `doc` -> `doc/install` in commit title.

@e337 any updates?

2021-11-18 03:56 UTC, varshar16 commented
jenkins render docs

2022-01-25 21:09 UTC, ljflores commented
jenkins render docs

2022-02-08 09:56 UTC, ideepika commented
@ljflores this looks good to me, if you find the same! :)

2022-02-08 20:28 UTC, ljflores commented
@ideepika agreed, looks good. Just hoping that the docs will render.

2022-02-11 00:18 UTC, ljflores commented
jenkins render docs

2022-02-11 00:19 UTC, ljflores commented
jenkins retest this please

2022-02-15 17:06 UTC, ljflores commented
Thanks @ideepika I'll check

2022-02-15 17:18 UTC, ljflores commented
Checked the rendered page, looks good. Not sure why "render build" is stuck. https://ceph--43388.org.readthedocs.build/en/43388/install/clone-source/

2022-02-15 17:18 UTC, ljflores approved these changes

2022-02-18 22:11 UTC, varshar16 approved these changes

2022-02-19 00:24 UTC, merged