Log and return an error if fs not found
ceph/ceph pull request #43386
Opened 2021-10-01 17:40 UTC by gokceni

Fixes: https://tracker.ceph.com/issues/51630

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-10-01 18:30 UTC, gokceni commented
jenkins restest this please

2021-10-01 19:41 UTC, ljflores commented
```
mypy run-test-pre: PYTHONHASHSEED='2887244939'
mypy run-test: commands[0] | mypy --config-file=../../mypy.ini -m alerts -m balancer -m cephadm -m crash -m dashboard -m devicehealth -m diskprediction_local -m hello -m influx -m iostat -m localpool -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m nfs -m orchestrator -m pg_autoscaler -m progress -m prometheus -m rbd_support -m rook -m snap_schedule -m selftest -m stats -m status -m telegraf -m telemetry -m test_orchestrator -m volumes -m zabbix
snap_schedule/module.py:10: note: In module imported here,
snap_schedule/__init__.py:9: note: ... from here:
snap_schedule/fs/schedule_client.py: note: In member "get_schedule_db" of class "SnapSchedClient":
snap_schedule/fs/schedule_client.py:134: error: Name "false" is not defined
snap_schedule/fs/schedule_client.py:147: error: Argument 2 to "open_ioctx" has incompatible type "Optional[str]"; expected "Union[int, str]"
Found 2 errors in 1 file (checked 31 source files)
```

2021-10-01 19:49 UTC, ideepika commented on src/pybind/mgr/snap_schedule/fs/schedule_client.py
> +            if poolid == false:
if not poolid:

2021-10-01 20:40 UTC, ideepika commented
might want to fix locally: 
`snap_schedule/module.py:10: in <module>
    from .fs.schedule_client import SnapSchedClient
E     File "/home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/snap_schedule/fs/schedule_client.py", line 134
E       if not poolid:
E                    ^
E   IndentationError: unindent does not match any outer indentation level`

2021-10-19 01:24 UTC, batrick requested changes

2021-10-19 01:24 UTC, batrick commented on src/ceph.iml
> +</module>
There seems to be an extraneous commit here and this file is from an IDE? Please undo this change.

2021-10-19 06:33 UTC, ideepika commented
> @ideepika does this one need an approval? Or is there still something wrong with it?

synced with @varshar16 earlier, was waiting on someone from FS team to review, thanks @batrick @ljflores for getting back to it!

2021-11-24 04:22 UTC, vshankar commented
@gokceni ping?

2021-11-24 18:49 UTC, gokceni commented
@vshankar I deleted the iml file. Please feel free to take over this PR since I will not be available for some time

2022-08-30 05:12 UTC, vshankar approved these changes

2022-08-30 05:12 UTC, vshankar commented
@gokceni please rebase.

2023-01-27 06:01 UTC, closed without merging