osd: cleanup multi-condition asserts
ceph/ceph pull request #43394
Opened 2021-10-01 22:08 UTC by bridg8et

fixes: https://trello.com/c/Ri6ixQ5X/615-osd-cleanup-multi-condition-asserts
signed-off-by: Bridget Rios <bridg8et94@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-10-02 00:30 UTC, ideepika commented
hey @bridg8et ! 

You might want to rebase this PR: 

you can do that by: 
1. git rebase -i HEAD~2 
2. you will be seeing 2 commits in the editors, please use drop instead of pick in the second and pick to reword and save it.
3. fix the Signed-off-by: Bridget Rios <bridg8et94@gmail.com>

2021-10-03 02:46 UTC, ideepika commented on src/erasure-code/shec/ErasureCodeShec.cc
> +  ceph_assert((technique == SINGLE)) || ceph_assert((technique == MULTIPLE));
@bridg8et changes looks good overall, just a small change: many places we have not needed double quotes, can you work on those instances eg: ceph_assert((technique == SINGLE))  -> ceph_assert(technique == SINGLE)

2021-10-07 03:35 UTC, ideepika commented
@bridg8et are you working on this?

2021-10-08 13:26 UTC, ideepika commented
@bridg8et I think this PR might take some more time, if it is hampering with OSD contribution requirement, you can always pick any other issue : from here https://tracker.ceph.com/issues/51379 that have not been taken https://pad.ceph.com/p/open-source-day let me know if you need assistance

2022-07-01 09:36 UTC, idryomov requested changes

2022-07-01 09:36 UTC, idryomov commented on src/krbd.cc
> +                     ceph_assert(*m_minnum == udev_device_get_sysattr_value(
This doesn't compile (and if it somehow compiled, it would introduce a bug as it is not an equivalent transformation).

2022-07-01 09:41 UTC, idryomov commented
Closing as it is quite obvious that this change hasn't even been compiled before submission and there seems to be a concern with regard to significantly increasing the number of asserts in the code base.

2022-07-01 09:41 UTC, closed without merging