cephadm: Add support for mariner
ceph/ceph pull request #43401
Opened 2021-10-02 03:14 UTC by romoh

Cephadm: Add mariner as a supported distro.

Using cephadm install commands on [Mariner](https://github.com/microsoft/CBL-Mariner) will result in an error "Distro not supported" though the packages are supported and can be installed manually. This change adds mariner as a supported distro.
Fixed validated on mariner.

Fixes: [pending tracker account approval]
Signed-off-by: [Roaa Sakr](mailto:roaa.sakr@gmail.com)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

2021-10-02 03:39 UTC, varshar16 requested changes
Thanks for contributing. Please change the commit message to:

```
src/cephadm: Add mariner as a supported distro.

Using cephadm install commands on Mariner will result in an error "Distro not supported" though the packages are supported and can be installed manually. This change adds mariner as a supported distro.
Fixed validated on mariner.

Signed-off-by: Roaa Sakr romoh@microsoft.com
```

2021-10-02 03:47 UTC, varshar16 commented
You can make changes to the commit by `git commit --amend` and then force push the changes `git push -f <repo-name> <branch-name>`

2021-10-02 07:51 UTC, sebastian-philipp approved these changes
code lgtm. (excluding the commit message)

2021-10-05 18:35 UTC, varshar16 approved these changes
Looks good! Thank you @romoh

2021-10-05 19:26 UTC, romoh commented
@adk3798 any further changes needed before merge?

2021-10-05 22:41 UTC, varshar16 commented
> @adk3798 any further changes needed before merge?

No changes are required. Your patch will be run through `qa` tests before merging.

2021-10-10 01:37 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2021-10-08_14:12:20-rados-wip-kefu-testing-2021-10-08-0624-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-10-10_00:01:10-rados-wip-kefu-testing-2021-10-08-0624-distro-basic-gibba/

2021-10-10 01:38 UTC, merged