tool: add repair command to ceph-dedup-tool
ceph/ceph pull request #43481
Opened 2021-10-11 02:08 UTC by myoungwon

Until now, ceph-dedup-tool only provides chunk-scrub
,which reports how many dangling references the object has,
but there is no cli command to fix the reference mismach.

Therefore, this commit adds repair command to correct detected
reference mismatch.

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-10-15 05:30 UTC, athanatos commented on src/tools/ceph_dedup_tool.cc
> +      int chunk_ref, base_ref;
Can we define these where they are initialized?

2021-10-15 05:32 UTC, athanatos commented on src/tools/ceph_dedup_tool.cc
> +	ceph_assert(base_ref < chunk_ref);
Let's print an error message and return an error code here.

2021-10-15 16:50 UTC, myoungwon commented
@athanatos I addressed your comments.

2021-10-19 05:27 UTC, athanatos commented on src/tools/ceph_dedup_tool.cc
> +      ret = chunk_io_ctx.getxattr(object_name, CHUNK_REFCOUNT_ATTR, t);
Are we supposed to go through a class operation here?

2021-10-19 05:27 UTC, athanatos approved these changes
LGTM other than my comment

2021-10-19 14:36 UTC, athanatos commented on src/tools/ceph_dedup_tool.cc
> +      ret = chunk_io_ctx.getxattr(object_name, CHUNK_REFCOUNT_ATTR, t);
Ok, seems reasonable.

2021-11-09 12:40 UTC, ronen-fr commented
@myoungwon : can you take a look at the failure of
http://pulpito.front.sepia.ceph.com/yuriw-2021-11-03_15:48:02-rados-wip-yuri7-testing-2021-11-01-1748-distro-basic-smithi/6481640/
?
A similar test without this patch was OK. Might be related.

2021-11-09 19:32 UTC, yuriw commented
@myoungwon this was tested and can be merged after further clarifying comments from above

2021-11-10 01:28 UTC, myoungwon commented
@ronen-fr It seems that this is not related the failure as discussed at (https://github.com/ceph/ceph/pull/43411)
@neha-ojha @athanatos This is probably ready to merge, thoughts?

2021-11-10 01:37 UTC, athanatos commented
@myoungwon I'm not sure what you mean.  The failure @yuriw pasted in is specific to this tool.  I think the following is the failure portion:

2021-11-07T06:11:56.720 INFO:tasks.workunit.client.0.smithi090.stderr:+ '[' -n 0 ']'
2021-11-07T06:11:56.720 INFO:tasks.workunit.client.0.smithi090.stderr:+ /usr/bin/ceph osd pool delete dedup_pool dedup_pool --yes-i-really-really-mean-it
2021-11-07T06:11:57.989 INFO:tasks.workunit.client.0.smithi090.stderr:pool 'dedup_pool' does not exist
2021-11-07T06:11:57.998 INFO:tasks.workunit.client.0.smithi090.stderr:+ /usr/bin/ceph osd pool delete dedup_chunk_pool dedup_chunk_pool --yes-i-really-really-mean-it
2021-11-07T06:11:58.994 INFO:tasks.workunit.client.0.smithi090.stderr:pool 'dedup_chunk_pool' does not exist
2021-11-07T06:11:59.004 INFO:tasks.workunit.client.0.smithi090.stderr:+ die 'Scrub failed expecting bar is removed'
2021-11-07T06:11:59.004 INFO:tasks.workunit.client.0.smithi090.stdout:Scrub failed expecting bar is removed
2021-11-07T06:11:59.005 DEBUG:teuthology.orchestra.run:got remote process result: 1
2021-11-07T06:11:59.005 INFO:tasks.workunit.client.0.smithi090.stderr:+ echo 'Scrub failed expecting bar is removed'
2021-11-07T06:11:59.006 INFO:tasks.workunit.client.0.smithi090.stderr:+ exit 1
2021-11-07T06:11:59.006 INFO:tasks.workunit:Stopping ['rados/test_dedup_tool.sh'] on client.0...

2021-11-10 02:33 UTC, myoungwon commented
@athanatos My bad. I'll take a look.

2021-11-10 16:47 UTC, ljflores commented
jenkins test make check

2021-11-11 15:03 UTC, myoungwon commented
@athanatos I fixed test cases that caused the failure.

2021-11-11 18:05 UTC, ljflores reviewed
After the fixup changes are confirmed to work, I think the commits should then be squashed into one.

2021-11-11 19:35 UTC, athanatos commented on qa/workunits/rados/test_dedup_tool.sh
>      die "Estimate failed expecting 1024 result $RESULT"
1024 wrong here?

2021-11-11 19:35 UTC, athanatos requested changes

2021-11-11 19:35 UTC, athanatos commented on qa/workunits/rados/test_dedup_tool.sh
>      die "Estimate failed expecting 1024 result $RESULT"
Also other messages.

2021-11-12 05:38 UTC, myoungwon commented
Fixed and squashed.

2021-11-15 20:19 UTC, athanatos approved these changes

2021-11-15 20:20 UTC, athanatos commented
Needs to be retested after the above changes.

2021-11-23 18:58 UTC, amathuria commented
http://pulpito.front.sepia.ceph.com/yuriw-2021-11-20_18:01:41-rados-wip-yuri8-testing-2021-11-20-0807-distro-basic-smithi

Failures unrelated tracked in: 
https://tracker.ceph.com/issues/53287
https://tracker.ceph.com/issues/53345
https://tracker.ceph.com/issues/53353
https://tracker.ceph.com/issues/52279
https://tracker.ceph.com/issues/39150
https://tracker.ceph.com/issues/53288

Details:
Bug #53287: test_standby (tasks.mgr.test_prometheus.TestPrometheus) fails
Bug #53345: Test failure: test_daemon_restart (tasks.cephadm_cases.test_cli.TestCephadmCLI)
Bug #53353: mgr/dashboard: orchestrator/03-inventory.e2e-spec.ts failure
Bug #52279: cephadm tests fail due to: error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter
Bug #39150: mon: "FAILED ceph_assert(session_map.sessions.empty())"  
Bug #53288: Failed jobs hanging for 12 hours (Dead jobs)

2021-11-24 08:00 UTC, myoungwon commented
It seems that this PR is unrelated with the failures. Can you double-check? @athanatos

2021-11-24 17:13 UTC, neha-ojha commented
jenkins test api

2021-11-28 22:46 UTC, ljflores commented
jenkins test api

2021-11-29 00:10 UTC, merged