cephadm/box: DiD box documentation
ceph/ceph pull request #43580
Opened 2021-10-18 15:47 UTC by pereman2

Signed-off-by: Pere Diaz Bou <pdiazbou@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-12-01 08:21 UTC, alfonsomthd commented on doc/dev/cephadm/developing-cephadm.rst
> +
It would be great to add a note on how to access the Dashboard once the cluster is up, as the expansion can be done either by CLI or by GUI.

2021-12-01 08:37 UTC, alfonsomthd requested changes
Can we add the command to shutdown the whole cluster?
The equivalent to `docker-compose down`.

2021-12-02 08:41 UTC, alfonsomthd commented
> Can we add the command to shutdown the whole cluster? The equivalent to `docker-compose down`.

@pereman2 is it `sudo box cluster cleanup` ?

2021-12-02 08:51 UTC, pereman2 commented
> > Can we add the command to shutdown the whole cluster? The equivalent to `docker-compose down`.
> 
> @pereman2 is it `sudo box cluster cleanup` ?

@alfonsomthd I forgot about that, just commited it.

2021-12-17 12:10 UTC, avanthakkar approved these changes

2021-12-20 15:45 UTC, alfonsomthd approved these changes

2021-12-20 15:46 UTC, alfonsomthd commented
jenkins test make check arm64

2022-01-04 16:24 UTC, merged