radosgw-admin: supplement help documents with 'mdlog autotrim' and 'mdlog fetch'
ceph/ceph pull request #43768
Opened 2021-11-02 06:12 UTC by Huber-ming

Signed-off-by: Huber-ming <zhangsm01@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-11-02 12:38 UTC, dang approved these changes

2021-11-02 12:38 UTC, dang commented
jenkins test api

2021-11-02 12:39 UTC, dang commented
jenkins test make check

2021-11-02 16:40 UTC, dang requested changes
You'll need to update src/test/cli/radosgw-admin/help.t to match the new update.

2021-11-02 17:15 UTC, cbodley commented on src/rgw/rgw_admin.cc
> +  cout << "  mdlog fetch                fetch metadata log\n";
i'm not sure where `mdlog fetch` came from. i see a command for it, but there's no actual implementation:

```
$ grep MDLOG_FETCH rgw_admin.cc
  MDLOG_FETCH,
  { "mdlog fetch", OPT::MDLOG_FETCH },
```

2021-11-04 01:56 UTC, cbodley approved these changes

2021-11-04 15:14 UTC, cbodley commented
@dang can you please re-review? i think this one can merge if you're satisfied

2021-11-04 17:19 UTC, dang approved these changes

2021-11-04 17:19 UTC, merged