pacific: rgw/sts: adding role name and role session to ops log.
ceph/ceph pull request #43956
Opened 2021-11-16 14:38 UTC by cfsnyder

backport tracker: https://tracker.ceph.com/issues/52782

---

backport of https://github.com/ceph/ceph/pull/41735
parent tracker: https://tracker.ceph.com/issues/51152

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2021-12-03 05:11 UTC, pritha-srivastava commented
@mattbenjamin : the changes here are fine. But the code changes here caused a seg fault bug addressed here: https://github.com/ceph/ceph/pull/43071, tracker here: https://tracker.ceph.com/issues/52530. How should the backport done in this case? separately? should I mark tracker 43071 for backport to pacific?

2022-01-06 14:42 UTC, cbodley requested changes
can you please include the fix from https://github.com/ceph/ceph/pull/43071 here?

2022-01-07 15:11 UTC, cbodley approved these changes
thank you kindly

2022-03-16 13:22 UTC, cfsnyder commented
jenkins test make check

2022-03-22 20:36 UTC, yuriw commented
jenkins test make check

2022-03-22 21:55 UTC, merged