osd: add pg_num_max value
ceph/ceph pull request #44054
Opened 2021-11-22 23:48 UTC by liewegas

- add the property
- some simple tests
- ensure min < pg_num < max
- make pg_autoscaler respect the max

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [ ] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-11-23 01:22 UTC, neha-ojha commented on src/pybind/mgr/dashboard/controllers/pool.py
> +        "pg_num_max": (int, "")
I think this should address https://jenkins.ceph.com/job/ceph-pull-requests/86047/consoleFull#450684626c19247c4-fcb7-4c61-9a5d-7e2b9731c678

```suggestion
        "pg_num_min": (int, ""),
        "pg_num_max": (int, "")
```

2021-11-23 01:25 UTC, neha-ojha commented
https://jenkins.ceph.com/job/ceph-pull-requests/86047/consoleFull#-108728127277933967-90d1-4877-8d60-89cb08ef4eb1 seems to be another occurrence of https://tracker.ceph.com/issues/53000

2021-11-23 18:02 UTC, batrick requested changes
Maybe also update `mgr/volumes` to set a `pg_num_max` on the metadata pool.

2021-11-23 18:29 UTC, liewegas commented on src/pybind/mgr/mgr_module.py
> +        if pg_num_max:
oops, that was left over from an earlier draft.  fixed.

2021-11-30 01:56 UTC, jdurgin commented
> Maybe also update `mgr/volumes` to set a `pg_num_max` on the metadata pool.

Other metadata pools like rgw's smaller ones (not bucket index) would need this too. We keep coming up with metadata-pool-specific settings - maybe we should have some flag for what is a small metadata pool in general, so we could easily apply new settings there.

2021-11-30 02:37 UTC, liewegas commented
> > Maybe also update `mgr/volumes` to set a `pg_num_max` on the metadata pool.
> 
> Other metadata pools like rgw's smaller ones (not bucket index) would need this too. We keep coming up with metadata-pool-specific settings - maybe we should have some flag for what is a small metadata pool in general, so we could easily apply new settings there.

Alternatively, maybe we need something like a "small" flag that indicates that pgs should scale up based on usage (and not down based on capacity)?

2021-11-30 03:22 UTC, jdurgin commented
> > > Maybe also update `mgr/volumes` to set a `pg_num_max` on the metadata pool.
> > 
> > 
> > Other metadata pools like rgw's smaller ones (not bucket index) would need this too. We keep coming up with metadata-pool-specific settings - maybe we should have some flag for what is a small metadata pool in general, so we could easily apply new settings there.
> 
> Alternatively, maybe we need something like a "small" flag that indicates that pgs should scale up based on usage (and not down based on capacity)?

It gets a bit complicated mixing the two modes. scale-down relies on the total number of pools to determine how to diivde the pg budget. I suppose it could treat 'small' pools, or pools in scale-up mode, as being processed first, and subtract those pgs from the budget, before dividing the budget evenly among scale-down pools with little usage. What do you think @kamoltat ?

2021-12-01 19:30 UTC, liewegas commented
jenkins test this please

2021-12-01 19:31 UTC, liewegas commented
Regardless of what we do with pool small or bulk flags, I think we still want a pg_num_max pool property.  I suggest moving forward with this PR.

2021-12-15 00:00 UTC, neha-ojha commented
jenkins retest this please

2021-12-15 00:06 UTC, neha-ojha commented
> Regardless of what we do with pool small or bulk flags, I think we still want a pg_num_max pool property. I suggest moving forward with this PR.

Agreed!

2021-12-16 01:17 UTC, neha-ojha approved these changes

2021-12-19 16:04 UTC, liewegas commented
jenkins test dashboard cephadm

2021-12-19 16:04 UTC, liewegas commented
@batrick ok to proceed without updating mgr/volumes?  I'm not sure a max makes sense there.

2021-12-20 01:46 UTC, batrick commented
> @batrick ok to proceed without updating mgr/volumes? I'm not sure a max makes sense there.

fine with me!

2021-12-22 15:26 UTC, neha-ojha commented
@batrick can you remove your request for changes, if everything looks good to you?
@liewegas have you finished testing this? can we merge it?

2021-12-22 15:56 UTC, liewegas commented
jenkins test dashboard cephadm

2021-12-22 16:01 UTC, liewegas commented
I think this is okay, but there are still some rados failures that I'm not sure about--going to run it through one more time.

@batrick it looks like the mds upgrade tests are still failing?

2021-12-22 18:17 UTC, batrick commented
> I think this is okay, but there are still some rados failures that I'm not sure about--going to run it through one more time.
> 
> @batrick it looks like the mds upgrade tests are still failing?

https://github.com/ceph/ceph/pull/44324

MDS upgrade tests were broken by a recent (RADOS!) PR :)

2021-12-22 18:17 UTC, batrick approved these changes

2021-12-22 18:28 UTC, neha-ojha commented
> > I think this is okay, but there are still some rados failures that I'm not sure about--going to run it through one more time.
> > @batrick it looks like the mds upgrade tests are still failing?
> 
> #44324
> 
> MDS upgrade tests were broken by a recent (RADOS!) PR :)

the rados suite isn't affected by https://tracker.ceph.com/issues/53615, I made a change similar to https://github.com/ceph/ceph/pull/44324 to other upgrade tests in https://github.com/ceph/ceph/pull/44161 before we merged https://github.com/ceph/ceph/commit/bd815bd9d6ecdecaab3d2dd9e0f5a18aa795d749, I missed the fs/upgrade tests. FWIW, these upgrade tests were setting the wrong flags :)

Latest rados/cephadm/mds_upgrade_sequence failures can be found in https://pad.ceph.com/p/teuthology_failures

2022-01-05 15:28 UTC, liewegas commented
jenkins test make check

2022-01-06 13:54 UTC, merged