Bug-Fix for NCB-FSCK
ceph/ceph pull request #44089
Opened 2021-11-24 10:38 UTC by benhanokh

Signed-off-by: Gabriel Benhanokh <gbenhano@redhat.com>

BlueStore:NCB-FSCK
PR-42762 changed the allocator used by NCB-FSCK code from the function private allocator to the global shared-allocator.
This PR returns the allocator to its correct value

      Fixes: https://tracker.ceph.com/issues/53381
      Signed-off-by: gbenhano@redhat.com

2021-11-24 13:45 UTC, aclamk approved these changes

2021-11-24 16:27 UTC, tchaikov commented
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

2021-11-24 16:28 UTC, tchaikov requested changes
the commit message of 

> This time for real :-) 

can be improved.

2021-11-29 15:37 UTC, tchaikov commented
> could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

could you please reconsider this comment?

2021-12-02 13:47 UTC, aclamk approved these changes
Good job!

2021-12-02 13:49 UTC, merged

2021-12-05 03:22 UTC, tchaikov commented
@benhanokh @aclamk it's not done.

the title of the commit reads

> Bug-Fix for PR-42762

this does not summarize the change.

2021-12-08 14:43 UTC, aclamk commented
@tchaikov Thank you.