doc: typo/formating fixes
ceph/ceph pull request #44102
Opened 2021-11-25 05:42 UTC by drunkard

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-12-01 09:28 UTC, sebastian-philipp approved these changes

2021-12-01 09:28 UTC, sebastian-philipp commented
jenkins test api

2021-12-10 12:18 UTC, drunkard commented
I just pushed 2 commits today (2021-12-10), and 4 commits about two weeks ago, when I create PR I saw the previous PR, and can't create a new one, but previous 4 commits has been lost (``git push --force``) from my fork, and they are not in `master` branch yet, so, here's question:

1. have they (4 commits) been merged? (I don't known which branch merged them)
2. do I have to pick them back?

Sorry, I'm not very familiar with workflow on github.

2021-12-13 03:21 UTC, drunkard commented
I reapplied those 4 commits, sorry for bothering you.

2021-12-13 08:46 UTC, sebastian-philipp approved these changes

2021-12-15 14:27 UTC, sebastian-philipp commented
needs rebase

2021-12-16 03:23 UTC, drunkard commented
Rebase done, conflict resolved.

2022-08-07 10:48 UTC, tchaikov commented
rebased against main HEAD.

2022-08-07 10:49 UTC, tchaikov approved these changes

2022-08-20 13:17 UTC, tchaikov commented
jenkins test make check

2022-08-21 05:50 UTC, anthonyeleven requested changes
By and large LGTM.

I did make several request for tweaks.

2022-08-21 05:50 UTC, anthonyeleven commented on doc/rados/troubleshooting/troubleshooting-osd.rst
> +  ``echo 131072 > /sys/module/nf_conntrack/parameters/hashsize``.
Doh! This was probably my goof 😞

2022-08-21 05:50 UTC, anthonyeleven commented on doc/radosgw/rgw-cache.rst
> +the workload from the cluster, using Nginx.
I suggest changing "the workload" to just "workload", i.e. remove the "the".

2022-08-21 05:50 UTC, anthonyeleven commented on doc/radosgw/rgw-cache.rst
> +Currently, this feature will cache only AWSv4 requests (only s3 requests),
s/s3/S3/

2022-08-21 05:50 UTC, anthonyeleven commented on doc/radosgw/rgw-cache.rst
> +The parameters that are most likely to require adjustment according to
Suggest s/according to/to match/

2023-01-27 15:01 UTC, closed without merging