doc: how to change default rbd object size
ceph/ceph pull request #44130
Opened 2021-11-29 14:45 UTC by LittleFox94

This pull request adds a hint to the documentation how to configure the default rbd object size and improves the documentation for the `rbd_default_order` config value (adding it to `rbd-config-ref` and improving it's docs).

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-11-30 08:25 UTC, LittleFox94 commented
Hm some tests are failing, I guess that one change in `rbd.yaml.in` wasn't a doc-only change after all ..

2021-12-22 17:17 UTC, idryomov requested changes
Just a couple a of nits and please squash everything into a single commit.

2021-12-22 17:17 UTC, idryomov commented on doc/man/8/rbd.rst
> +   The default value can be changed with the config ``rbd_default_order``, which
```suggestion
   The default value can be changed with the configuration option ``rbd_default_order``, which
```

2021-12-22 17:17 UTC, idryomov commented on doc/man/8/rbd.rst
> +   takes a power to two (default object size is ``2 ^ rbd_default_order``).
```suggestion
   takes a power of two (default object size is ``2 ^ rbd_default_order``).
```

2021-12-22 17:17 UTC, idryomov commented on src/common/options/rbd.yaml.in
> +  long_desc: This configures the default object size for new rbd images. The value is used as
```suggestion
  long_desc: This configures the default object size for new images. The value is used as
```

2021-12-22 17:17 UTC, idryomov commented on src/common/options/rbd.yaml.in
> +    power to two, meaning ``default_object_size = 2 ^ rbd_default_order`` (alternative
```suggestion
    a power of two, meaning ``default_object_size = 2 ^ rbd_default_order``
```

2021-12-22 17:17 UTC, idryomov commented on src/common/options/rbd.yaml.in
> +    format ``default_object_size = 1 << rbd_default_order``). Configure a value between 12 and 25
The `1 << ` syntax is fairly niche, most people are confused by it.  Let's drop it.
```suggestion
    Configure a value between 12 and 25
```

2021-12-22 17:33 UTC, LittleFox94 commented
Thanks for looking at it @idryomov, changed everything you commented except squashing into a single commit, since I read the [contribution guidelines](https://github.com/ceph/ceph/blob/master/doc/start/documenting-ceph.rst#commit-the-change) as if I should make one commit per file (though the second commit is touching two files already, having multiple commits started from that though)? I will happily squash them, but want to make sure with the docs first :)

2021-12-27 09:28 UTC, idryomov requested changes
Otherwise LGTM.

These commits are tiny and closely related to each other, no need to split per-file or otherwise.

2021-12-27 09:28 UTC, idryomov commented on src/common/options/rbd.yaml.in
> +    power to two, meaning ``default_object_size = 2 ^ rbd_default_order``. Configure a value
```suggestion
    a power of two, meaning ``default_object_size = 2 ^ rbd_default_order``. Configure a value
```

2021-12-27 18:59 UTC, LittleFox94 commented on src/common/options/rbd.yaml.in
> +    power to two, meaning ``default_object_size = 2 ^ rbd_default_order``. Configure a value
whoops, missed that

2021-12-28 07:09 UTC, idryomov approved these changes

2021-12-28 07:09 UTC, idryomov commented
jenkins test api

2021-12-28 10:12 UTC, idryomov commented
jenkins test api

2021-12-29 11:26 UTC, idryomov commented
jenkins test api

2021-12-30 14:55 UTC, idryomov commented
jenkins test api

2021-12-31 11:03 UTC, idryomov commented
jenkins test api

2022-01-03 09:06 UTC, merged