os/bluestore: make pinning logic simpler
ceph/ceph pull request #44349
Opened 2021-12-17 11:52 UTC by aclamk

This is a follow-up of  #44311, sitting on top of it.

Branch with more ceph_assert wip-aclamk-cleanup-onode-pin-test is going to teuthology for testing.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2021-12-20 10:13 UTC, ifed01 commented on src/os/bluestore/BlueStore.cc
> +    pinned = nref >= 1;
Looks like I'm wrong at this line - it still should be nref >= 2
Going to re-test and update the original PR.

2021-12-20 10:23 UTC, ifed01 commented on src/os/bluestore/BlueStore.cc
> +  if (++nref >= 1 && !pinned) {
And this should stay >=2 too.

2021-12-20 12:17 UTC, ifed01 commented
@aclamk - I fixed the condition for 'pinned' state - this should be nref >= 2 not nref > =1 as I proposed initially.

2021-12-23 15:15 UTC, markhpc commented
Adding performance flag just because it touches fairly performance sensitive code (even if we don't expect it to have an impact)

2022-01-13 10:53 UTC, aclamk commented
@ifed01 You mentioned this as preferred solution for onode pinning cleanup.
I am not fully clear at this point - does this PR need any more attention?

2022-01-13 11:52 UTC, ifed01 commented
> @ifed01 You mentioned this as preferred solution for onode pinning cleanup. I am not fully clear at this point - does this PR need any more attention?

yes, it needs rebase (and probably some rework) since my original PR has been updated and merged.

2022-01-14 15:42 UTC, ifed01 requested changes

2022-01-14 15:42 UTC, ifed01 commented on src/os/bluestore/BlueStore.cc
> +  if (++nref >= 1 && !pinned) {
no need any more indeed

2022-01-14 15:42 UTC, ifed01 commented on src/os/bluestore/BlueStore.cc
> +    if (nref >= 2) ceph_assert(pinned);
not a big deal since this goes away in the last commit.

2022-12-29 02:19 UTC, closed without merging