mon/ConfigMonitor: fix config get key with whitespaces
ceph/ceph pull request #44656
Opened 2022-01-19 10:13 UTC by NitzanMordhai

if we run config get command with key that contain whitespaces the command will return with
key not found error, ceph store all keys with whitespaces as underscores.
the config get command need to normalize the key name before it search that key

Fixes: https://tracker.ceph.com/issues/44092
Signed-off-by: Nitzan Mordechai <nmordech@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-01-19 12:59 UTC, ronen-fr commented on src/mon/ConfigMonitor.cc
> +        if (name == "fsid") {
not related

2022-01-19 12:59 UTC, ronen-fr commented on src/mon/ConfigMonitor.cc
> +	      opt = mon.mgrmon()->find_module_option(name);
not related

2022-01-19 12:59 UTC, ronen-fr commented on src/mon/ConfigMonitor.cc
> +        ss << " key: " << name <<" did not found";
not related

2022-01-19 13:01 UTC, ronen-fr commented on src/mon/ConfigMonitor.cc
> +        ss << " key: " << name <<" did not found";
and phrasing

2022-01-19 14:08 UTC, batrick requested changes
Add some tests to `qa/workunits/mon/config.sh` to exercise this.

Also agree with @ronen-fr about removing the unrelated changes (mostly whitespace).

2022-01-20 06:47 UTC, ronen-fr commented
Main change LGTM. Just add the requested test as a 2nd commit in this PR.

2022-01-24 10:17 UTC, ronen-fr commented
jenkins retest this please

2022-01-25 09:22 UTC, ronen-fr approved these changes

2022-01-25 09:23 UTC, NitzanMordhai commented
> Add some tests to `qa/workunits/mon/config.sh` to exercise this.
> 
> Also agree with @ronen-fr about removing the unrelated changes (mostly whitespace).

@batrick done

2022-01-25 13:55 UTC, batrick approved these changes

2022-01-25 13:55 UTC, batrick commented
great work!

2022-03-01 20:17 UTC, ljflores commented
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri6-testing-2022-02-14-1456

Failures, unrelated:
    https://tracker.ceph.com/issues/52124
    https://tracker.ceph.com/issues/51076
    https://tracker.ceph.com/issues/54438

Details:
    1. Invalid read of size 8 in handle_recovery_delete() - Ceph - RADOS
    2. "wait_for_recovery: failed before timeout expired" during thrashosd test with EC backend. - Ceph - RADOS
    3. test/objectstore/store_test.cc: FAILED ceph_assert(bl_eq(state->contents[noid].data, r2)) in function 'virtual void SyntheticWorkloadState::C_SyntheticOnClone::finish(int)' - Ceph - RADOS

2022-03-02 16:02 UTC, merged