qa: fill the test_file before try to read it
ceph/ceph pull request #44679
Opened 2022-01-20 09:09 UTC by lxbsz

When the file is empty the kernel won't trigger the read request
to libcephfs.

Fixes: https://tracker.ceph.com/issues/53859
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-01-20 13:57 UTC, batrick requested changes

2022-01-21 02:15 UTC, lxbsz commented on qa/tasks/cephfs/test_pool_perm.py
> +                os.close(fd)
Done.

2022-01-24 13:17 UTC, vshankar approved these changes

2022-02-07 03:58 UTC, lxbsz commented
jenkins test make check

2022-02-07 05:30 UTC, vshankar commented
@lxbsz This test still fails - https://pulpito.ceph.com/vshankar-2022-02-05_17:27:49-fs-wip-vshankar-testing-20220201-113815-testing-default-smithi/6662928/ (build https://shaman.ceph.com/builds/ceph/wip-vshankar-testing-20220201-113815/)

PTAL.

2022-02-07 05:45 UTC, lxbsz commented
> @lxbsz This test still fails - https://pulpito.ceph.com/vshankar-2022-02-05_17:27:49-fs-wip-vshankar-testing-20220201-113815-testing-default-smithi/6662928/ (build https://shaman.ceph.com/builds/ceph/wip-vshankar-testing-20220201-113815/)
> 
> PTAL.

This time it fails in the test for kclient. I will check how the kclient is handling this case.

2022-02-08 02:05 UTC, lxbsz commented
> > @lxbsz This test still fails - https://pulpito.ceph.com/vshankar-2022-02-05_17:27:49-fs-wip-vshankar-testing-20220201-113815-testing-default-smithi/6662928/ (build https://shaman.ceph.com/builds/ceph/wip-vshankar-testing-20220201-113815/)
> > PTAL.
> 
> This time it fails in the test for kclient. I will check how the kclient is handling this case.

This time it failed when testing the writing to the file and there has no logs, but from the code it should due to buffer writing and just successfully wrote to the buffer.

2022-02-10 06:40 UTC, vshankar commented
> This time it failed when testing the writing to the file and there has no logs, but from the code it should due to buffer writing and just successfully wrote to the buffer.



> This time it failed when testing the writing to the file and there has no logs, but from the code it should due to buffer writing and just successfully wrote to the buffer.

OK -- O_DIRECT should help here.

I'll include this in my next run. Thanks @lxbsz

2022-03-07 04:47 UTC, vshankar commented
@lxbsz - please take a look - https://pulpito.ceph.com/vshankar-2022-03-06_14:47:51-fs-wip-vshankar-testing-20220304-132102-testing-default-smithi/6724272/

(I didn't check why it fails with your latest changes - sorry!)

2022-03-07 05:41 UTC, lxbsz commented
> @lxbsz - please take a look - https://pulpito.ceph.com/vshankar-2022-03-06_14:47:51-fs-wip-vshankar-testing-20220304-132102-testing-default-smithi/6724272/
> 
> (I didn't check why it fails with your latest changes - sorry!)

No worry, I will check it later. Thanks Venky.

2023-02-01 04:27 UTC, lxbsz commented
Reopen it and need to update this PR to find the root cause later.

2023-02-07 12:42 UTC, rishabh-d-dave approved these changes
Looks okay to me.

2023-02-07 12:42 UTC, rishabh-d-dave commented
jenkins test api

2023-02-07 12:43 UTC, rishabh-d-dave commented
jenkins test make windows

2023-02-07 12:43 UTC, rishabh-d-dave commented
jenkins test docs

2023-02-07 12:43 UTC, rishabh-d-dave commented
jenkins test windows

2023-02-07 12:43 UTC, rishabh-d-dave commented
jenkins test make check arm64

2023-02-07 12:44 UTC, rishabh-d-dave commented
@lxbsz @vshankar Shall I pick this for QA?

2023-02-07 14:09 UTC, vshankar commented
> @lxbsz @vshankar Shall I pick this for QA?

Yes.

2023-02-08 01:07 UTC, lxbsz commented
> @rishabh-d-dave sorry, I think we should wait for @lxbsz to push a change update.

Yeah, last time this test failed and I need to spend more time reading the kernel VFS code to found the root cause.

2023-02-08 12:34 UTC, rishabh-d-dave commented
@vshankar @lxbsz Okay, I'll wait. Please feel free me to message me when it's ready.

2024-03-27 05:37 UTC, rishabh-d-dave commented
Hey, @lxbsz. This PR got autoclosed. Just checking if you too want it to remain closed or you want to re-open it. :)

2024-03-27 05:39 UTC, lxbsz commented
> Hey, @lxbsz. This PR was autoclosed. Just checking if you too want it to remain closed or you want to re-open it. :)

Thanks @rishabh-d-dave I just opened it, and this needs to be updated later.

2024-06-27 08:33 UTC, rishabh-d-dave commented
> > Hey, @lxbsz. This PR was autoclosed. Just checking if you too want it to remain closed or you want to re-open it. :)
> 
> Thanks @rishabh-d-dave I just opened it, and this needs to be updated later.

Just FYI: This PR got auto-closed again.

2024-12-25 10:01 UTC, closed without merging