octopus: qa/vstart_runner: align interfaces of different run_python()
ceph/ceph pull request #44731
Opened 2022-01-21 19:25 UTC by rishabh-d-dave

run_python() in qa.tasks.cephfs.mount.py accepts an extra parameter
compared to run_python() in qa.tasks.cephfs.vstart_runner.py. This
inconsistency in interface crashes tests located in qa.tasks.cephfs
when executed using vstart_runner.py.

Fixes: https://tracker.ceph.com/issues/53970

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-02-15 05:50 UTC, rishabh-d-dave commented
@mchangir This patch was written for an issue you were facing with `_run_python()`. Can you please take a look and confirm if it fixes the issue?

2022-02-15 05:50 UTC, rishabh-d-dave commented
jenkins test make check

2022-04-01 17:18 UTC, nmshelke approved these changes
I am not aware of scenario where it is crashing but to have function consistent make sense.

2022-04-18 09:43 UTC, rishabh-d-dave commented
> @mchangir This patch was written for an issue you were facing with `_run_python()`. Can you please take a look and confirm if it fixes the issue?

@mchangir ping.

2022-05-12 19:50 UTC, ljflores commented
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri6-testing-2022-05-09-0734-octopus

A few jobs failed due to problems in infrastructure, but passed in a rerun.

Failures:
    1. https://tracker.ceph.com/issues/49287 --> opened during this run, but unrelated to this PR.
    2. https://tracker.ceph.com/issues/55636

Details:
    1. podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator
    2. octopus: osd-bluefs-volume-ops.sh: TEST_bluestore2 fails with "FAILED ceph_assert(r == 0)" - Ceph - BlueStore

2022-05-17 04:12 UTC, ajarr requested changes
https://github.com/ceph/ceph/blob/octopus/qa/tasks/cephfs/mount.py#L214 , _run_python_ does not have "sudo" param .  But in the commit message you say otherwise. Can you explain the difference?

2022-06-07 18:30 UTC, rishabh-d-dave commented
> https://github.com/ceph/ceph/blob/octopus/qa/tasks/cephfs/mount.py#L214 , _run_python_ does not have "sudo" param . But in the commit message you say otherwise. Can you explain the difference?

Nice catch. Thanks! The comparison was with `run_python()` in `main` branch. I amended the commit message accordingly.

2022-06-07 18:35 UTC, rishabh-d-dave commented
> > https://github.com/ceph/ceph/blob/octopus/qa/tasks/cephfs/mount.py#L214 , _run_python_ does not have "sudo" param . But in the commit message you say otherwise. Can you explain the difference?
> 
> Nice catch. Thanks! The comparison was with `run_python()` in `main` branch. I amended the commit message accordingly.

@ajarr

2022-06-08 08:15 UTC, mchangir approved these changes

2022-07-01 01:05 UTC, vshankar approved these changes

2022-07-01 01:05 UTC, vshankar commented
jenkins test make check

2022-07-02 10:46 UTC, vshankar approved these changes

2022-07-02 15:06 UTC, yuriw commented
@rishabh-d-dave this was approved for merge by @vshankar 
@ajarr pls merged or remove the comment for change

2022-07-04 15:07 UTC, vshankar commented
@yuriw this pr is not critical for octopus and can be left out...

2022-07-05 16:19 UTC, yuriw commented
@vshankar ack

2023-02-27 05:41 UTC, vshankar commented
See https://github.com/ceph/ceph/pull/44732#issuecomment-1445740970

2023-02-27 05:41 UTC, closed without merging