cephadm/box: fix remove image tar error
ceph/ceph pull request #44812
Opened 2022-01-27 17:30 UTC by pereman2

cleanups basically.

Fixes: https://tracker.ceph.com/issues/54045
Signed-off-by: Pere Diaz Bou <pdiazbou@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-01-27 18:40 UTC, epuertat commented
@pereman2 can you please document in Ceph docs how to add the 'shared folders' option?

2022-01-31 16:34 UTC, avanthakkar requested changes

2022-01-31 16:34 UTC, avanthakkar commented on src/cephadm/box/box.py
>      run_shell_command(f'docker save {CEPH_IMAGE} -o {image_tar}')
```suggestion
    run_shell_command(f'docker save {CEPH_IMAGE} -o {CEPH_IMAGE_TAR}')
```

2022-01-31 17:31 UTC, pereman2 commented on src/cephadm/box/box.py
>      run_shell_command(f'docker save {CEPH_IMAGE} -o {image_tar}')
oops thanks!

2022-02-01 07:59 UTC, nizamial09 approved these changes
Tested locally! LGTM

2022-02-01 09:37 UTC, pereman2 commented
jenkins test make check

2022-02-01 13:55 UTC, pereman2 commented
jenkins test api

2022-02-01 13:55 UTC, pereman2 commented
jenkins test dashboard cephadm

2022-02-02 07:23 UTC, nizamial09 commented
jenkins test dashboard cephadm

2022-02-02 18:03 UTC, avanthakkar approved these changes

2022-02-03 06:49 UTC, merged