pybimgr: fix "osd status" command output with format json
ceph/ceph pull request #44836
Opened 2022-01-30 13:53 UTC by NitzanMordhai

currently command "ceph -f json osd status" return table view instead of json view.
the fix will fix that and will also fix the json-pretty format output.

Signed-off-by: Nitzan Mordechai <nmordech@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-01-31 08:16 UTC, NitzanMordhai commented
> 

jenkins test make check

2022-01-31 18:15 UTC, batrick requested changes
Please use `pybind/mgr` or `pybind/mgr/status`.

2022-02-16 06:14 UTC, joscollin requested changes
As you are on it, fix the `xml` and xml-pretty formats too?

2022-02-16 12:48 UTC, NitzanMordhai commented
> As you are on it, fix the `xml` and xml-pretty formats too?

Does it work for any other command output that came from python modules?
anyway, I think we need new tracker for that one

2022-02-16 13:12 UTC, joscollin commented
> > As you are on it, fix the `xml` and xml-pretty formats too?
> 
> Does it work for any other command output that came from python modules? 

Yes, check out other commands.

> anyway, I think we need new tracker for that one

It doesn't need a tracker, as there is no need for a backport afaik.

2022-02-17 05:51 UTC, joscollin commented
> > As you are on it, fix the `xml` and xml-pretty formats too?
> 
> Does it work for any other command output that came from python modules? anyway, I think we need new tracker for that one


Making it similar to `fs status` options is fine.

2022-02-17 05:53 UTC, NitzanMordhai commented
> > > As you are on it, fix the `xml` and xml-pretty formats too?
> > 
> > 
> > Does it work for any other command output that came from python modules?
> 
> Yes, check out other commands.
> 
All the python handled command doesn't have xml\xml-pretty output formatter, the command you tested coming from c++ code.
we will leave the python code for now without xml\xml-pretty formats and if we want to add it later we will need to think of class that will do it like the c++ approach 

> > anyway, I think we need new tracker for that one
> 
> It doesn't need a tracker, as there is no need for a backport afaik.

2022-02-17 05:59 UTC, joscollin approved these changes

2022-02-24 06:18 UTC, NitzanMordhai commented on src/pybind/mgr/status/module.py
> +            if output_format in ('json', 'json-pretty'):
Done

2022-02-24 06:18 UTC, NitzanMordhai commented on src/pybind/mgr/status/module.py
> +
Done

2022-02-24 06:18 UTC, NitzanMordhai commented on src/pybind/mgr/status/module.py
> +        json_output: Dict[str, List[str]] = \
Yes, changed that, thanks

2022-02-24 12:00 UTC, kotreshhr commented on src/pybind/mgr/status/module.py
> +        json_output: Dict[str, List[Any]] = \
need to import `Any`

2022-07-31 12:08 UTC, NitzanMordhai commented
@batrick can you please review the changes?

2022-08-07 03:21 UTC, tchaikov commented
jenkins test make check

2022-08-09 16:10 UTC, tchaikov commented
jenkins test make check

2022-08-09 16:10 UTC, tchaikov commented
@batrick hi Patrick, i believe your comment has been addressed. could you take another look?

2022-08-10 14:05 UTC, tchaikov commented
jenkins test make check

2022-08-12 13:14 UTC, batrick approved these changes

2022-08-12 13:59 UTC, merged