mgr/dashboard: "Please expand your cluster first" shouldn't be shown if cluster is already meaningfully running
ceph/ceph pull request #44951
Opened 2022-02-09 08:39 UTC by votdev

This PR will assume that a cluster is already up and fully running. If this should not be the expected behaviour, deployment tools have to set 'INSTALLED' explicitly. Without this assumption it might happen that upgraded and fully running clusters, e.g. Octopus -> Pacific, will show the 'Expand Cluster' on first log in.

Fixes: https://tracker.ceph.com/issues/54215

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-02-09 10:56 UTC, votdev commented
Is the fix acceptable in that way how it is implemented? I don't think it makes sense to do enhanced tests like checking for OSD's and so on. The only thing is that a deployment tool should explicitly set the `mgr/dashboard/cluster/status` configuration option if it is wanted to show the `Expand cluster` page, otherwise migrations and deployments MUST set `POST_INSTALLED` which is out of scope IMO.

2022-02-09 12:07 UTC, nizamial09 commented
> The only thing is that a deployment tool should explicitly set the `mgr/dashboard/cluster/status` configuration option to `INSTALLED` when it is desired to

I agree! The only thing we need to discuss in the UI is to expose the `expand-cluster` link somewhere in the landing page/navigation sidebar or somewhere so that this is still usable for anyone. (Since this workflow is Expand Cluster, it should be accessible whenever needed). But we can discuss it later on...

Also, we should add something to the cephadm bootstrap to enable this workflow for a new cluster right? @epuertat @votdev

2022-02-09 12:07 UTC, nizamial09 approved these changes

2022-02-09 12:07 UTC, nizamial09 commented
jenkins test dashboard cephadm

2022-02-09 12:07 UTC, nizamial09 commented
jenkins test dashboard

2022-02-09 13:56 UTC, votdev commented
> Also, we should add something to the cephadm bootstrap to enable this workflow for a new cluster right? @epuertat @votdev

I think that's how we should do it.

2022-02-09 16:14 UTC, votdev commented
jenkins test dashboard

2022-02-09 17:10 UTC, votdev commented
Can someone with access to Applitools Eyes please check why the `visualTests/*.vrt-spec.ts` E2E tests fail? I have no access to this service to check the URL which is reported in the error message:
```
1) Dashboard Landing Page
       "after all" hook for "should take screenshot of dashboard landing page":
     Error: [0mEyes-Cypress detected diffs or errors during execution of visual tests.[0m[0m See details at: [38;5;86mhttps://eyes.applitools.com/app/batches/00000251757875846600/00000251757875846287?accountId=hCTedwnSTUWSCZlXPqua0g~~[0m[0m
       [32mPassed - 1 tests[0m
         [32m✓[0m [0mDashboard Component [800x600][0m
       [38;5;214mDiffs detected - 3 tests[0m
         [38;5;214m⚠[0m [0mDashboard Component [1920x1080][0m
         [38;5;214m⚠[0m [0mDashboard Component [1920x1080][0m
         [38;5;214m⚠[0m [0mDashboard Component [800x600][0m

       [0mSee details at:[0m [38;5;86mhttps://eyes.applitools.com/app/batches/00000251757875846600/00000251757875846287?accountId=hCTedwnSTUWSCZlXPqua0g~~[0m
```

2022-02-09 17:28 UTC, nizamial09 commented
> why the `visualTests/*.vrt-spec.ts` E2E tests fail?

@votdev I am hoping this will fix that error. https://github.com/ceph/ceph/pull/44956

2022-02-09 19:41 UTC, votdev commented
> > why the `visualTests/*.vrt-spec.ts` E2E tests fail?
> 
> @votdev I am hoping this will fix that error. #44956. I'll retrigger the job when that PR is merged.

Thx

2022-02-09 19:51 UTC, nizamial09 commented
jenkins test dashboard

2022-02-10 13:19 UTC, epuertat requested changes
Thanks for the fix, @votdev! According to your suggestion of not making any smart guesses based on OSDs, etc., can you please add the changes to set the `INSTALLED` status from the cephadm bootstrap stage?

2022-02-11 08:40 UTC, s0nea commented
Hey @epuertat! Do you think there's an option to merge the PR as it currently is? I can fully understand why you're asking for implementing the "smart guesses" and agree with you! I'm wondering if it's possible to implement this at a later point. It's just because we noticed the wizard will also be shown if a cluster has been upgraded to pacific. Which might be quite a surprise for some users.

2022-02-11 18:46 UTC, epuertat commented
Hi @s0nea , don't worry, I'm not suggesting any fancy/smart guess at all (that might be a nice-to-have, but I agree, not now): just ensuring that when the cluster has just been bootstrapped with cephadm the welcome screen appears as it was happening so far. For fixing an issue (mostly cosmetic, since the wizard can be easily dismissed) this is now causing another one (cosmetic too, since no wizard is ever displayed).

The fix I'm asking for could be as simple as setting this very same option to the previous default in the cephadm bootstrap phase. What do you think @s0nea @votdev ?

2022-02-14 08:29 UTC, s0nea commented
> The fix I'm asking for could be as simple as setting this very same option to the previous default in the cephadm bootstrap phase. What do you think @s0nea @votdev ?

Yes, sounds reasonable to me!

2022-02-14 09:58 UTC, epuertat approved these changes
Thanks a lot @votdev @s0nea! LGTM! Let's wait till the `cephadm dashboard` job passes.

2022-02-14 09:59 UTC, votdev commented
> Thanks a lot @votdev @s0nea! LGTM! Let's wait till the `cephadm dashboard` job passes.

Your welcome.

2022-02-14 11:22 UTC, s0nea commented
> jenkins test docs

Hmpf... I assume `ERROR: sphinx-autodoc-typehints 1.17.0 has requirement Sphinx>=4, but you'll have sphinx 3.5.4 which is incompatible.` won't be resolved by just re-running the job.

2022-02-14 13:52 UTC, votdev commented
jenkins test docs

2022-02-14 13:53 UTC, votdev commented
jenkins retest this please

2022-02-14 14:34 UTC, s0nea commented
I assume https://github.com/ceph/ceph/pull/45018 needs to go in first.

2022-02-15 07:24 UTC, nizamial09 commented
Maybe we can ignore the doc errors (caused by some changes in one of the doc dependencies) and go with this PR

2022-02-15 07:26 UTC, nizamial09 commented
jenkins test docs

2022-02-15 07:56 UTC, s0nea commented
jenkins render docs

2022-02-15 08:00 UTC, s0nea approved these changes

2022-02-15 10:58 UTC, merged