doc/dev: document nested subsets in teuthology
ceph/ceph pull request #44967
Opened 2022-02-10 02:35 UTC by batrick

See also: https://github.com/ceph/teuthology/pull/1704

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-02-10 17:14 UTC, batrick commented
https://ceph--44967.org.readthedocs.build/en/44967/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-intro/#nested-subsets

2022-03-22 21:28 UTC, zmc commented on doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-intro.rst
> +``teuthology-sute``.
typo

2022-03-22 21:29 UTC, zmc requested changes

2022-03-22 21:29 UTC, zmc commented on doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-intro.rst
> +``teuthology-sute``.
```suggestion
``teuthology-suite``.
```

2022-03-23 00:48 UTC, batrick commented on doc/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-intro.rst
> +``teuthology-sute``.
Thanks, fixed!

2022-05-24 16:21 UTC, zmc approved these changes

2022-05-24 16:23 UTC, merged