osd: require osd_pg_max_concurrent_snap_trims > 0
ceph/ceph pull request #45140
Opened 2022-02-24 08:43 UTC by dvanders

If osd_pg_max_concurrent_snap_trims is zero, we mistakenly clear
the snaptrim queue. Require it to be > 0.

Fixes: https://tracker.ceph.com/issues/54396
Signed-off-by: Dan van der Ster <daniel.vanderster@cern.ch>

2022-02-24 18:18 UTC, neha-ojha approved these changes

2022-02-24 18:18 UTC, rzarzynski approved these changes

2022-03-02 23:43 UTC, ljflores commented
There is a SnapMapper failure that looks related to this PR.

http://pulpito.front.sepia.ceph.com/yuriw-2022-03-01_22:42:19-rados-wip-yuri4-testing-2022-03-01-1206-distro-default-smithi/6715606/
http://pulpito.front.sepia.ceph.com/yuriw-2022-03-02_15:47:04-rados-wip-yuri4-testing-2022-03-01-1206-distro-default-smithi/6716189/
```
2022-03-02T04:38:16.044 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:702: TEST_scrub_snaps:  grep 'log_channel[(]cluster[)] log [[]ERR[]] : osd[.][0-9]* found snap mapper error on pg 1.0 oid 1:461f8b5e:::obj16:7 snaps missing in mapper, should be: 1,2,3,4,5,6,7 was  r -2...repaired' td/osd-scrub-snaps/osd.0.log
2022-03-02T04:38:16.045 INFO:tasks.workunit.client.0.smithi133.stdout:Missing log message 'log_channel[(]cluster[)] log [[]ERR[]] : osd[.][0-9]* found snap mapper error on pg 1.0 oid 1:461f8b5e:::obj16:7 snaps missing in mapper, should be: 1,2,3,4,5,6,7 was  r -2...repaired'
2022-03-02T04:38:16.047 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:704: TEST_scrub_snaps:  echo 'Missing log message '\''log_channel[(]cluster[)] log [[]ERR[]] : osd[.][0-9]* found snap mapper error on pg 1.0 oid 1:461f8b5e:::obj16:7 snaps missing in mapper, should be: 1,2,3,4,5,6,7 was  r -2...repaired'\'''
2022-03-02T04:38:16.047 INFO:tasks.workunit.client.0.smithi133.stderr://home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:705: TEST_scrub_snaps:  expr 0 + 1
2022-03-02T04:38:16.048 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:705: TEST_scrub_snaps:  ERRORS=1
2022-03-02T04:38:16.048 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:709: TEST_scrub_snaps:  '[' 1 '!=' 0 ']'
2022-03-02T04:38:16.048 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:711: TEST_scrub_snaps:  echo 'TEST FAILED WITH 1 ERRORS'
2022-03-02T04:38:16.049 INFO:tasks.workunit.client.0.smithi133.stdout:TEST FAILED WITH 1 ERRORS
2022-03-02T04:38:16.052 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:712: TEST_scrub_snaps:  return 1
2022-03-02T04:38:16.052 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:39: run:  return 1
2022-03-02T04:38:16.052 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/ceph-helpers.sh:2261: main:  code=1
```

2022-03-02 23:55 UTC, ljflores requested changes
See comment -- if you think it's unrelated, let me know and I'll investigate further.

2022-03-03 03:37 UTC, neha-ojha commented
> There is a SnapMapper failure that looks related to this PR.
> 
> http://pulpito.front.sepia.ceph.com/yuriw-2022-03-01_22:42:19-rados-wip-yuri4-testing-2022-03-01-1206-distro-default-smithi/6715606/ http://pulpito.front.sepia.ceph.com/yuriw-2022-03-02_15:47:04-rados-wip-yuri4-testing-2022-03-01-1206-distro-default-smithi/6716189/
> 
> ```
> 2022-03-02T04:38:16.044 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:702: TEST_scrub_snaps:  grep 'log_channel[(]cluster[)] log [[]ERR[]] : osd[.][0-9]* found snap mapper error on pg 1.0 oid 1:461f8b5e:::obj16:7 snaps missing in mapper, should be: 1,2,3,4,5,6,7 was  r -2...repaired' td/osd-scrub-snaps/osd.0.log
> 2022-03-02T04:38:16.045 INFO:tasks.workunit.client.0.smithi133.stdout:Missing log message 'log_channel[(]cluster[)] log [[]ERR[]] : osd[.][0-9]* found snap mapper error on pg 1.0 oid 1:461f8b5e:::obj16:7 snaps missing in mapper, should be: 1,2,3,4,5,6,7 was  r -2...repaired'
> 2022-03-02T04:38:16.047 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:704: TEST_scrub_snaps:  echo 'Missing log message '\''log_channel[(]cluster[)] log [[]ERR[]] : osd[.][0-9]* found snap mapper error on pg 1.0 oid 1:461f8b5e:::obj16:7 snaps missing in mapper, should be: 1,2,3,4,5,6,7 was  r -2...repaired'\'''
> 2022-03-02T04:38:16.047 INFO:tasks.workunit.client.0.smithi133.stderr://home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:705: TEST_scrub_snaps:  expr 0 + 1
> 2022-03-02T04:38:16.048 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:705: TEST_scrub_snaps:  ERRORS=1
> 2022-03-02T04:38:16.048 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:709: TEST_scrub_snaps:  '[' 1 '!=' 0 ']'
> 2022-03-02T04:38:16.048 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:711: TEST_scrub_snaps:  echo 'TEST FAILED WITH 1 ERRORS'
> 2022-03-02T04:38:16.049 INFO:tasks.workunit.client.0.smithi133.stdout:TEST FAILED WITH 1 ERRORS
> 2022-03-02T04:38:16.052 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:712: TEST_scrub_snaps:  return 1
> 2022-03-02T04:38:16.052 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/scrub/osd-scrub-snaps.sh:39: run:  return 1
> 2022-03-02T04:38:16.052 INFO:tasks.workunit.client.0.smithi133.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/ceph-helpers.sh:2261: main:  code=1
> ```

@ljflores I don't think this failure is related to this PR, the same test fails in master, https://pulpito.ceph.com/nojha-2022-03-03_01:16:43-rados:standalone-master-distro-basic-smithi/. I think this is related to the logging change made as a part of https://github.com/ceph/ceph/pull/44941.

2022-03-03 16:34 UTC, ljflores approved these changes

2022-03-03 17:48 UTC, ljflores commented
Ok, the SnapMapper failure is unrelated. Here is a summary of the other failures, all unrelated:

http://pulpito.front.sepia.ceph.com/yuriw-2022-03-01_22:42:19-rados-wip-yuri4-testing-2022-03-01-1206-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2022-03-02_15:47:04-rados-wip-yuri4-testing-2022-03-01-1206-distro-default-smithi/

Failures, unrelated:
    https://tracker.ceph.com/issues/52124
    https://tracker.ceph.com/issues/52320
    https://tracker.ceph.com/issues/53680

Details:
    1. Invalid read of size 8 in handle_recovery_delete() - Ceph - RADOS
    2. unable to get monitor info from DNS SRV with service name: ceph-mon - Ceph - Orchestrator
    3. ERROR:tasks.rook:'waiting for service removal' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator

2022-03-03 17:48 UTC, merged

2022-06-25 02:42 UTC, karibertils commented
I have plenty of stuck data over several pools. I tried wiping ALL data from one of the pools and it's still showing ~26% usage.

When I run `rados listsnaps object` on random objects I see for example:
```
1001056373b.00000002:                                                                         
cloneid snaps   size    overlap                                                               
288     288     134217728       []                                                            
```

So there seems to be some accounting that these objects have snaps.

But according to `ceph pg dump` all pg's have SNAPTRIMQ_LEN = 0

Running quincy 17.2.0. I have restarted everything multiple times, repeering all OSD's, deep-scrubbing all, etc.

Is there any way to fill the snaptrim queue again after running into this issue ?