mgr/rbd_support: cast pool_id from int to str when collecting LevelSpec
ceph/ceph pull request #45149
Opened 2022-02-24 16:51 UTC by sunnyku

While collecting LevelSpec using class method from_name make sure to cast
pool_id from int to string. This is necessary to match the internal
representation of LevelSpec where pool_id is maintained as str.

Fixes: https://tracker.ceph.com/issues/53915

Signed-off-by: Sunny Kumar <sunkumar@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-02-24 17:28 UTC, idryomov requested changes
Also please add a reproducer to `qa/workunits/rbd/cli_generic.sh`.

2022-02-24 17:28 UTC, idryomov commented on src/pybind/mgr/rbd_support/schedule.py
> +        return LevelSpec(name, id, str(pool_id), namespace, image_id)
What if it's a global level spec (i.e. if `pool_id` is `None`)?  This would pass `'None'` string and mess up the global level logic in `LevelSpec`.

2022-02-24 17:28 UTC, idryomov commented on src/pybind/mgr/rbd_support/schedule.py
> +        return LevelSpec(name, id, str(pool_id), namespace, image_id)
I'd suggest adding `pool_id = str(pool_id)` before line 128 instead.

2022-02-25 13:02 UTC, sunnyku commented
Working on reproducer will update the patch, thanks.

2022-03-01 16:14 UTC, sunnyku commented
jenkins retest this please

2022-03-05 10:31 UTC, idryomov commented
Updated the branch with more extensive tests, without sleeps.

2022-03-05 11:43 UTC, idryomov commented
jenkins test this please

2022-03-05 12:00 UTC, idryomov commented
jenkins test windows

2022-03-05 12:08 UTC, trociny approved these changes
LGTM

2022-03-05 16:25 UTC, idryomov commented
jenkins test docs

2022-03-06 10:14 UTC, idryomov commented
jenkins test docs

2022-03-07 11:13 UTC, idryomov commented
No related failures:

https://pulpito.ceph.com/dis-2022-03-06_21:44:39-rbd-wip-dis-testing-distro-default-smithi/

2022-03-07 11:13 UTC, idryomov commented
`rbd ls -l` hung, looks like it had to do with messenger failure injection:
```
2022-03-06T22:08:59.666 INFO:tasks.workunit.client.0.smithi116.stderr:+ rbd ls -l
2022-03-06T22:08:59.667 INFO:tasks.workunit.client.0.smithi116.stderr:+ grep image
2022-03-06T22:08:59.667 INFO:tasks.workunit.client.0.smithi116.stderr:+ wc -l
2022-03-06T22:08:59.668 INFO:tasks.workunit.client.0.smithi116.stderr:+ grep 100
2022-03-06T22:08:59.753 INFO:tasks.workunit.client.0.smithi116.stderr:2022-03-06T22:08:59.751+0000 7fa15591c700  0 -- 172.21.15.116:0/1845773366 >> [v2:172.21.15.116:6816/16327,v1:172.21.15.116:6817/16327] conn(0x7fa13001fe50 msgr2=0x7fa130022230 crc :-1 s=STATE_CONNECTION_ESTABLISHED l=1).read_until injecting socket failure
2022-03-07T01:08:20.577 DEBUG:teuthology.orchestra.run:got remote process result: 124
```

2022-03-07 11:13 UTC, idryomov approved these changes

2022-03-07 11:14 UTC, merged

2022-03-21 11:47 UTC, idryomov commented
Note: this is yet another regression introduced by https://github.com/ceph/ceph/pull/39371.