mgr/cephadm: check spec host when adding osd
ceph/ceph pull request #45217
Opened 2022-03-02 11:42 UTC by rkachach

Fixes: https://tracker.ceph.com/issues/47872

Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-03-02 15:47 UTC, rkachach commented on src/pybind/mgr/orchestrator/module.py
> +            filtered_hosts: List[str] = filter_spec.filter_matching_hostspecs(hosts)
I moved the code to the cephadm module (though the error message is more generic)

2022-03-11 15:58 UTC, rkachach commented
jenkins retest this please

2022-03-22 12:42 UTC, rkachach commented
@adk3798 UT has been added to check the new validation

2022-03-22 23:36 UTC, adk3798 approved these changes

2022-03-24 19:06 UTC, adk3798 commented
http://pulpito.front.sepia.ceph.com/adking-2022-03-23_02:54:35-orch:cephadm-wip-adk-testing-2022-03-22-2000-distro-basic-smithi/

2 Failures caused by wrong error code from host add command due to another PR included in the run

2022-03-24 19:07 UTC, adk3798 requested changes

2022-03-24 19:07 UTC, adk3798 commented on src/pybind/mgr/cephadm/tests/test_cephadm.py
> +
```
cephadm/tests/test_cephadm.py:821:5: E303 too many blank lines (2)
1     E303 too many blank lines (2)
```
flake8 error causing make check to fail

2022-03-28 08:30 UTC, rkachach commented on src/pybind/mgr/cephadm/tests/test_cephadm.py
> +
Fixed :+1:

2022-03-30 12:51 UTC, adk3798 commented
http://pulpito.front.sepia.ceph.com/adking-2022-03-29_23:26:23-orch:cephadm-wip-adk-testing-2022-03-29-1402-distro-basic-smithi/

Failures:
https://tracker.ceph.com/issues/44587
https://tracker.ceph.com/issues/49287
1 machine failed to install kernel fast enough

2022-03-30 13:01 UTC, merged