mgr/dashboard: unselect rows in datatables
ceph/ceph pull request #45313
Opened 2022-03-09 12:18 UTC by Sarthak0702

User should be able to unselect a selected row in data-tables.

Fixes: https://tracker.ceph.com/issues/53244
Signed-off-by: Sarthak0702 <sarthak.0702@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-03-10 10:05 UTC, nizamial09 approved these changes
LGTM! Thanks @Sarthak0702

2022-03-10 10:07 UTC, nizamial09 commented
Is it possible to verify this in a small unit test? @Sarthak0702

2022-03-11 15:43 UTC, Sarthak0702 commented
> Is it possible to verify this in a small unit test? @Sarthak0702

Thats a good idea, will try to add that.

2022-03-14 09:46 UTC, Sarthak0702 commented
jenkins test windows

2022-03-16 08:13 UTC, Sarthak0702 commented
jenkins test make check

2022-03-16 08:14 UTC, Sarthak0702 commented
jenkins test make check

2022-03-18 20:27 UTC, Sarthak0702 commented
> This fix breaks the multi select functionality in data-tables (Cluster-> OSDs ). Need to investigate this.

Fixed. As unselect functionality is  natively supported by ngx-datatables for `'multiclick' & 'multi'`, `selectCheck` is only added for `'single' selectionType`.

2022-03-23 09:45 UTC, Sarthak0702 commented
jenkins test dashboard

2022-03-23 09:45 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-03-23 11:10 UTC, votdev commented
Nice idea, but i would like to see that this feature behaves the way a desktop user is used to from operating systems like Windows or Gnome, especially Windows Explorer, Nautilus or other file navigation tools. There you can unselect a row by using STRG + LMB.

2022-03-23 11:14 UTC, votdev submitted a review, later dismissed
Nice idea, but i would like to see that this feature behaves the way a desktop user is used to from operating systems like Windows or Gnome, especially Windows Explorer, Nautilus or other file navigation tools. There you can unselect a row by using CTRL + LMB. It is not good to introduce a different workflow instead of implementing a widely used and accepted standard.

2022-03-23 13:34 UTC, votdev commented
> > Nice idea, but i would like to see that this feature behaves the way a desktop user is used to from operating systems like Windows or Gnome, especially Windows Explorer, Nautilus or other file navigation tools. There you can unselect a row by using CTRL + LMB. It is not good to introduce a different workflow instead of implementing a widely used and accepted standard.
> 
> So are you suggesting to use `LMB` to select a row but `CTRL+LMB` to unselect? Wouldn't that be a bit confusing for the user?

Yes, that is the standard in Windows and Linux UIs.

2022-03-23 13:57 UTC, Sarthak0702 commented
> Yes, that is the standard in Windows and Linux UIs.

Hmm, I see. FYI, for `selectionType:'multiClick'` (check Cluster -> OSDs) in ngx-datable (on which TableComponent is built) `LMB` is used to select and unselect rows natively. So we need to do disable that somehow too.

2022-03-23 21:01 UTC, votdev commented
> > Yes, that is the standard in Windows and Linux UIs.
> 
> Hmm, I see. FYI, for `selectionType:'multiClick'` (check Cluster -> OSDs) in ngx-datable (on which TableComponent is built) `LMB` is used to select and unselect rows natively. So we need to do disable that somehow too.

Yes i know. It's not my decision which style the Dashboard follows, but i think it should go the same way as the most common operating systems and file navigators go. I mean, the LMB approach to select and unselect will work on touch devices, but i don't think someone is using the Dashboard on those devices.

2022-03-28 23:50 UTC, Sarthak0702 commented
> Yes i know, this was IMO also not implemented the right way. But it's not my decision which style the Dashboard follows, but i think it should go the same way as the most common operating systems and file navigators do. I mean, the LMB approach to select and unselect will work on touch devices, but i don't think someone is using the Dashboard on those devices.

Honesty I do find using CTRL+ LMB to unselect rows a bit inorganic in a web based application. Have a look at this: https://www.patternfly.org/v4/components/table#composable-row-click-handler-hoverable--selected-rows
Also, surprisingly there are some folks who do use dashboard on touch devices (like iPads).  Nevertheless, I and @epuertat would agree, feel that the dashboard tables look a bit outdated, and some modern UI changes would surely improve UX. For this I have opened a tracker issue: https://tracker.ceph.com/issues/55095

2022-03-29 19:01 UTC, epuertat approved these changes
LGTM! Thanks @Sarthak0702 !

2022-03-30 09:00 UTC, Sarthak0702 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
> +  }
Ahh, I see. This is a good point, will keep this in mind.

2022-03-30 10:23 UTC, nizamial09 approved these changes

2022-03-30 12:09 UTC, Sarthak0702 commented
jenkins test dashboard

2022-03-30 12:10 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-03-30 18:51 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-03-31 08:07 UTC, nizamial09 requested changes
@Sarthak0702 the dashboard cephadm e2e is failing for real. The below solution will fix it.

```
--- a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
+++ b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
@@ -127,8 +127,8 @@ export class HostsPageHelper extends PageHelper {
   @PageHelper.restrictTo(pages.index.url)
   maintenance(hostname: string, exit = false, force = false) {
     this.clearTableSearchInput();
+    this.getTableCell(this.columnIndex.hostname, hostname).click();
     if (force) {
-      this.getTableCell(this.columnIndex.hostname, hostname).click();
       this.clickActionButton('enter-maintenance');

       cy.get('cd-modal').within(() => {
@@ -145,7 +145,6 @@ export class HostsPageHelper extends PageHelper {
     }
     if (exit) {
       this.getTableCell(this.columnIndex.hostname, hostname)
-        .click()
         .parent()
         .find(`datatable-body-cell:nth-child(${this.columnIndex.status})`)
         .then(($ele) => {
@@ -163,7 +162,6 @@ export class HostsPageHelper extends PageHelper {
           expect(status).to.not.include('maintenance');
         });
     } else {
-      this.getTableCell(this.columnIndex.hostname, hostname).click();
       this.clickActionButton('enter-maintenance');

       this.getTableCell(this.columnIndex.hostname, hostname)
@@ -187,5 +185,9 @@ export class HostsPageHelper extends PageHelper {
       cy.wait(20000);
       this.expectTableCount('total', 0);
     });
+
+    // unselect it to avoid colliding with any other selection
+    // in different steps
+    this.getTableCell(this.columnIndex.hostname, hostname).click();
   }
 }
 ```

2022-03-31 21:23 UTC, Sarthak0702 commented
NA

2022-03-31 21:23 UTC, Sarthak0702 commented
N/A

2022-04-01 06:59 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-04-01 06:59 UTC, Sarthak0702 commented
jenkins test dashboard

2022-04-03 20:25 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-04-04 08:37 UTC, Sarthak0702 commented
jenkins test dashboard

2022-04-06 00:57 UTC, Sarthak0702 commented
jenkins test dashboard

2022-04-06 15:45 UTC, nizamial09 commented
```
diff --git a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/services.po.ts b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/services.po.ts
index cbc900813dc..b90c0ea5f07 100644
--- a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/services.po.ts
+++ b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/services.po.ts
@@ -166,6 +166,10 @@ export class ServicesPageHelper extends PageHelper {
     cy.get('cd-service-daemon-list').within(() => {
       this.getTableRow(daemon).click();
       this.clickActionButton(action);
+
+      // unselect it to avoid colliding with any other selection
+      // in different steps
+      this.getTableRow(daemon).click();
     });
   }
 }
 ```

2022-04-08 06:39 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-04-08 06:39 UTC, Sarthak0702 commented
jenkins test dashboard

2022-04-08 09:33 UTC, nizamial09 commented
jenkins test dashboard cephadm

2022-04-08 19:53 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-04-09 08:30 UTC, Sarthak0702 commented
jenkins test dashboard

2022-04-12 11:30 UTC, epuertat commented
jenkins test dashboard

2022-04-18 09:15 UTC, epuertat commented
jenkins test dashboard

2022-04-22 08:53 UTC, avanthakkar commented
jenkins test dashboard

2022-04-22 08:54 UTC, avanthakkar approved these changes

2022-04-25 07:00 UTC, nizamial09 approved these changes

2022-04-27 12:10 UTC, epuertat commented
jenkins test dashboard

2022-05-05 07:43 UTC, pereman2 commented
jenkins test dashboard

2022-05-05 08:04 UTC, epuertat commented
jenkins test dashboard cephadm

2022-05-05 09:53 UTC, pereman2 commented
jenkins test dashboard cephadm

2022-05-05 09:53 UTC, pereman2 commented
jenkins test dashboard

2022-05-05 15:58 UTC, Sarthak0702 commented
jenkins test dashboard

2022-05-05 21:50 UTC, Sarthak0702 commented
jenkins test make check

2022-05-06 05:56 UTC, Sarthak0702 commented
jenkins test make check

2022-05-10 18:59 UTC, Sarthak0702 commented
jenkins test dashboard

2022-05-10 19:00 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-05-10 19:22 UTC, Sarthak0702 commented
jenkins test dashboard cephadm

2022-05-13 09:10 UTC, epuertat commented
jenkins test api

2022-05-13 09:11 UTC, epuertat commented
jenkins test dashboard cephadm

2022-05-17 09:48 UTC, merged