nautilus: mgr/dashboard: fix Grafana OSD/host panels
ceph/ceph pull request #45332
Opened 2022-03-10 10:28 UTC by p-se

backport tracker: https://tracker.ceph.com/issues/53990

---

backport of https://github.com/ceph/ceph/pull/43685
parent tracker: https://tracker.ceph.com/issues/52974

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2022-03-10 14:41 UTC, p-se commented
jenkins test make check

2022-05-13 10:50 UTC, avanthakkar commented
jenkins test make check

2022-05-13 11:21 UTC, avanthakkar approved these changes

2022-05-13 13:04 UTC, avanthakkar commented
jenkins test windows

2022-05-13 14:32 UTC, epuertat commented
jenkins test windows

2022-05-19 17:58 UTC, epuertat commented
jenkins test windows

2022-05-19 18:10 UTC, anthonyeleven requested changes

2022-05-19 18:10 UTC, anthonyeleven commented on doc/mgr/prometheus.rst
>  the ``*`` operator in your prometheus query. All metadata metrics (like ``
While you're here, please capitalize Prometheus

2022-05-19 18:10 UTC, anthonyeleven commented on doc/mgr/prometheus.rst
> +The following two section outline two approaches to remedy this.
The following two sections outline ways to work around this.

2022-07-13 12:33 UTC, pereman2 commented
Hey @p-se are you planning on fixing the errors?

2022-07-13 13:26 UTC, cbodley commented
this PR targets the nautilus release, which is no longer supported. can we close this?

2022-07-13 22:51 UTC, anthonyeleven commented
I would think so

2022-12-06 11:14 UTC, avanthakkar commented
jenkins retest this please

2023-07-14 12:25 UTC, closed without merging