pacific: radosgw-admin: 'reshard list' doesn't log ENOENT errors
ceph/ceph pull request #45451
Opened 2022-03-16 18:01 UTC by cfsnyder

backport tracker: https://tracker.ceph.com/issues/52958

---

backport of https://github.com/ceph/ceph/pull/43488
parent tracker: https://tracker.ceph.com/issues/52873

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2022-05-16 08:44 UTC, cfsnyder commented
jenkins test make check

2022-10-05 17:10 UTC, cbodley requested changes

2022-10-05 17:10 UTC, cbodley commented on src/rgw/rgw_reshard.cc
> +        << logshard_oid << " marker=" << marker << " " << cpp_strerror(ret) << dendl;
`ctx` is a member function, so this should be `store->ctx()` like the code it replaces

build log:
```
src/rgw/rgw_reshard.cc: In member function ‘int RGWReshard::list(int, std::__cxx11::string&, uint32_t, std::__cxx11::list<cls_rgw_reshard_entry>&, bool*)’:
src/common/dout.h:159:8: error: invalid use of non-static member function ‘virtual ceph::common::CephContext* rgw::sal::RGWRadosStore::ctx()’
   }(cct);        \
        ^
src/common/dout.h:177:20: note: in expansion of macro ‘dout_impl’
 #define lderr(cct) dout_impl(cct, ceph_subsys_, -1) dout_prefix
                    ^~~~~~~~~
src/rgw/rgw_reshard.cc:904:5: note: in expansion of macro ‘lderr’
     lderr(store->ctx) << "ERROR: access denied to pool " << store->svc()->zone->get_zone_params().reshard_pool
     ^~~~~
In file included from src/rgw/rgw_reshard.cc:11:
src/rgw/rgw_sal_rados.h:328:26: note: declared here
     virtual CephContext *ctx(void) { return rados->ctx(); }
                          ^~~
```

2022-12-05 18:11 UTC, cbodley approved these changes

2022-12-05 18:11 UTC, cbodley commented
jenkins test make check

2022-12-05 18:11 UTC, cbodley commented
jenkins test api

2022-12-05 18:29 UTC, yuriw commented
jenkins test api

2022-12-05 19:39 UTC, yuriw commented
jenkins test make check

2022-12-05 23:48 UTC, yuriw commented
jenkins test make check

2022-12-06 15:03 UTC, merged