ceph/admin: s/master/main
ceph/ceph pull request #45512
Opened 2022-03-17 23:07 UTC by zdover23

This PR changes the name "master" to "main" so
that builds (and, I assume, a great many other
things) will not fail.

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-03-17 23:21 UTC, jdurgin approved these changes

2022-03-18 03:49 UTC, tchaikov commented
jenkins test make check

2022-03-18 03:51 UTC, tchaikov requested changes

2022-03-18 03:51 UTC, tchaikov commented on admin/doc-read-the-docs.txt
> +git+https://github.com/readthedocs/readthedocs-sphinx-search@main
```suggestion
git+https://github.com/readthedocs/readthedocs-sphinx-search@0.1.1
```

2022-03-21 15:46 UTC, tchaikov commented
@zdover23 ping? it's still an improvement without incorporating my suggestion. if you are fine with it but don't have the bandwidth working on it. i can help on the squash things.

2022-03-22 23:38 UTC, merged

2022-03-23 10:53 UTC, zdover23 commented
> @zdover23 ping? it's still an improvement without incorporating my suggestion. if you are fine with it but don't have the bandwidth working on it. i can help on the squash things.

@tchaikov -- sorry about the radio silence on my part. I've been at capacity for the last four days, and only now got back to this. It might look me-too-ish of me to say this, but I agree with Josh about making changes like this as incrementally as possible. (Sorry inb4 Josh, if I'm putting words into your mouth.)