mgr/snap_schedule: validate fs name argument
ceph/ceph pull request #45732
Opened 2022-03-31 11:12 UTC by mchangir

Validate fs name argument for all commands.

Fixes: https://tracker.ceph.com/issues/54560
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-04-19 04:28 UTC, vshankar commented on src/pybind/mgr/snap_schedule/module.py
> +    def has_fs(self, fs_name: str) -> bool:
nit: use the following helper?

```
src/pybind/mgr/mgr_util.py:    def get_all_filesystems(self) -> List[str]:
```

2022-04-19 04:28 UTC, vshankar requested changes
minor nit, otherwise looks fine,

2022-04-26 01:03 UTC, mchangir commented on src/pybind/mgr/snap_schedule/module.py
> +    def has_fs(self, fs_name: str) -> bool:
done ... used the suggested helper

2022-04-26 06:42 UTC, nmshelke commented on src/pybind/mgr/snap_schedule/module.py
> +        if not self.has_fs(use_fs):
Can we save call for `has_fs(use_fs)` in case of `default_fs` (because I feel no need to validate `default_fs`) ?

2022-04-26 12:29 UTC, vshankar commented
> `snap-schedule` teuthology run with `PG_AVAILABILITY` Warnings

Could you help me recall why are we getting these warnings in snap_schedule tests?

2022-05-02 09:38 UTC, vshankar approved these changes

2022-05-03 13:47 UTC, ajarr approved these changes

2022-05-03 19:56 UTC, mchangir commented
> > `snap-schedule` teuthology run with `PG_AVAILABILITY` Warnings
> 
> Could you help me recall why are we getting these warnings in snap_schedule tests?

I'm not sure if these warnings are specific to snap-schedule runs.
I still won't be able to answer the  **why** part, but these warnings are seen when the cluster is being torn down.

2022-05-04 13:30 UTC, mchangir commented
[teuthoogy run with both PRs](https://pulpito.ceph.com/mchangir-2022-05-04_09:22:05-fs-wip-mchangir-TESTING-mgr-snap_schedule-distro-default-smithi/)

This run has also thrown PG_AVAILABILITY warnings.

2022-05-09 14:00 UTC, vshankar approved these changes

2022-05-09 14:00 UTC, vshankar approved these changes

2022-05-09 14:00 UTC, merged