octopus:rgw: fix lock scope in ObjectCache::get()
ceph/ceph pull request #45838
Opened 2022-04-10 09:08 UTC by RaminNietzsche

Based on @cupnes's changes on #44747
Date:      Sun Apr 10 13:12:19 2022 +0430

On branch fix_bug_51927
Changes to be committed:
	modified:   src/rgw/rgw_cache.cc

> in the touch_lru() case, we promote the shared_lock to a unique_lock.
but because the unique_lock is in a nested scope, the lock drops with
its scope and we continue accessing the map without any protection

> this moves the unique_lock up to function scope, where it's
constructed as unlocked with std::defer_lock. after promotion, this
lock will be held until the function returns

Fixes: https://tracker.ceph.com/issues/51927
Signed-off-by: Ramin Najarbashi <ramin.najarbashi@gmail.com>

## Checklist
- Tracker 
  - [x] References tracker ticket [#51927](https://tracker.ceph.com/issues/51927)
- Component impact
  - [x] No impact that needs to be tracked
- Documentation 
  - [x] No doc update is appropriate
- Tests
  - [x] No tests

2022-04-10 21:28 UTC, RaminNietzsche commented
@ideepika 
@tchaikov

2022-04-11 06:46 UTC, ideepika requested changes
@RaminNietzsche please chery pick commit 1aee987ec8f817541aab9cd21480b5351df38f69 from master or amend cherry pick ref to commiit msg. 
https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst

Please, also please consider opening seperate PR for main/master change, thanks!

2022-04-11 07:17 UTC, RaminNietzsche commented
> @RaminNietzsche please chery pick commit [1aee987](https://github.com/ceph/ceph/commit/1aee987ec8f817541aab9cd21480b5351df38f69) from master or amend cherry pick ref to commiit msg. https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst
> 
> Please, also please consider opening seperate PR for main/master change, thanks!

I have already sent two separated MR but the automatic tests did’t pass successfully. So, the two MR were merged and I closed Main-Master.

I will edit this request and will resend you previous one again.

2022-04-12 21:21 UTC, RaminNietzsche commented
@ideepika it  should be okay now?

2022-04-15 17:31 UTC, RaminNietzsche commented
> @ideepika it should be okay now?

@dang

2022-05-18 11:17 UTC, RaminNietzsche commented
@ideepika Could you check that again, please?

2022-07-15 15:23 UTC, closed without merging