pacific: ceph-fuse: ignore fuse mount failure if path is already mounted
ceph/ceph pull request #45925
Opened 2022-04-18 05:52 UTC by nmshelke

backport tracker: https://tracker.ceph.com/issues/55040

---

backport of https://github.com/ceph/ceph/pull/44491
parent tracker: https://tracker.ceph.com/issues/46075

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2022-04-18 06:02 UTC, kotreshhr requested changes
The PR has added unintended files.

2022-04-18 06:16 UTC, nmshelke commented
> The PR has added unintended files.

@kotreshhr Updated code and commits.

2022-04-18 07:49 UTC, nmshelke commented
jenkins test make check

2022-04-18 08:01 UTC, kotreshhr approved these changes

2022-04-18 08:04 UTC, vshankar commented
Not urgent for 16.2.8.

2022-05-12 18:05 UTC, nmshelke commented
> Not urgent for 16.2.8.

Ok

2022-06-08 04:10 UTC, vshankar requested changes
@nmshelke PTAL at the build failure - https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=bionic,DIST=bionic,MACHINE_SIZE=gigantic/63092//consoleFull

```
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc: In function 'int already_fuse_mounted(const char*, bool&)':
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:182:16: error: aggregate 'already_fuse_mounted(const char*, bool&)::statx path_statx' has incomplete type and cannot be defined
   struct statx path_statx;
                ^~~~~~~~~~
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:183:16: error: aggregate 'already_fuse_mounted(const char*, bool&)::statx parent_statx' has incomplete type and cannot be defined
   struct statx parent_statx;
                ^~~~~~~~~~~~
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:194:35: error: 'AT_STATX_DONT_SYNC' was not declared in this scope
   if (-1 == statx(AT_FDCWD, path, AT_STATX_DONT_SYNC, STATX_INO, &path_statx)) {
                                   ^~~~~~~~~~~~~~~~~~
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:194:35: note: suggested alternative: 'AT_NO_ATTR_SYNC'
   if (-1 == statx(AT_FDCWD, path, AT_STATX_DONT_SYNC, STATX_INO, &path_statx)) {
                                   ^~~~~~~~~~~~~~~~~~
                                   AT_NO_ATTR_SYNC
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:194:55: error: 'STATX_INO' was not declared in this scope
   if (-1 == statx(AT_FDCWD, path, AT_STATX_DONT_SYNC, STATX_INO, &path_statx)) {
                                                       ^~~~~~~~~
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:194:55: note: suggested alternative: 'STA_INS'
   if (-1 == statx(AT_FDCWD, path, AT_STATX_DONT_SYNC, STATX_INO, &path_statx)) {
                                                       ^~~~~~~~~
                                                       STA_INS
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:194:77: error: invalid use of incomplete type 'struct already_fuse_mounted(const char*, bool&)::statx'
   if (-1 == statx(AT_FDCWD, path, AT_STATX_DONT_SYNC, STATX_INO, &path_statx)) {
                                                                             ^
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:182:10: note: forward declaration of 'struct already_fuse_mounted(const char*, bool&)::statx'
   struct statx path_statx;
          ^~~~~
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:210:42: error: 'AT_STATX_DONT_SYNC' was not declared in this scope
   if (-1 == statx(AT_FDCWD, parent_path, AT_STATX_DONT_SYNC, STATX_INO, &parent_statx)) {
                                          ^~~~~~~~~~~~~~~~~~
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:210:42: note: suggested alternative: 'AT_NO_ATTR_SYNC'
   if (-1 == statx(AT_FDCWD, parent_path, AT_STATX_DONT_SYNC, STATX_INO, &parent_statx)) {
                                          ^~~~~~~~~~~~~~~~~~
                                          AT_NO_ATTR_SYNC
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:210:62: error: 'STATX_INO' was not declared in this scope
   if (-1 == statx(AT_FDCWD, parent_path, AT_STATX_DONT_SYNC, STATX_INO, &parent_statx)) {
                                                              ^~~~~~~~~
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:210:62: note: suggested alternative: 'STA_INS'
   if (-1 == statx(AT_FDCWD, parent_path, AT_STATX_DONT_SYNC, STATX_INO, &parent_statx)) {
                                                              ^~~~~~~~~
                                                              STA_INS
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:210:86: error: invalid use of incomplete type 'struct already_fuse_mounted(const char*, bool&)::statx'
   if (-1 == statx(AT_FDCWD, parent_path, AT_STATX_DONT_SYNC, STATX_INO, &parent_statx)) {
                                                                                      ^
/build/ceph-16.2.9-144-gd8d210f8/src/client/fuse_ll.cc:182:10: note: forward declaration of 'struct already_fuse_mounted(const char*, bool&)::statx'
   struct statx path_statx;
          ^~~~~
src/CMakeFiles/ceph-fuse.dir/build.make:89: recipe for target 'src/CMakeFiles/ceph-fuse.dir/client/fuse_ll.cc.o' failed```

2022-06-09 10:24 UTC, vshankar commented
@nmshelke Could you put this through a shaman build.

2022-06-09 10:28 UTC, joscollin commented
Looks like this needs 
```
#ifndef __USE_GNU
#define __USE_GNU 1
#endif
```
just before fcntl.h to include the definition of `AT_` constants.

2022-06-10 03:23 UTC, gregsfortytwo commented
> Looks like this needs
> 
> ```
> #ifndef __USE_GNU
> #define __USE_GNU 1
> #endif
> ```
> 
> just before fcntl.h to include the definition of `AT_` constants.

Hmm it looks to me like we *just* started using these constants: 4654f9350cb1285859f58e1bc0abdcc9e141f879

So I think we just want to stick with the original AT_NO_ATTR_SYNC that Pacific was using.

2022-06-10 03:25 UTC, gregsfortytwo requested changes
As I commented above

2022-06-10 04:02 UTC, joscollin commented
> Looks like this needs
> 
> ```
> #ifndef __USE_GNU
> #define __USE_GNU 1
> #endif
> ```
> 
> just before fcntl.h to include the definition of `AT_` constants.

@vshankar [This](https://tracker.ceph.com/issues/55253) needs backport decision instead.

2022-06-13 08:37 UTC, nmshelke commented
> > Looks like this needs
> > ```
> > #ifndef __USE_GNU
> > #define __USE_GNU 1
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > just before fcntl.h to include the definition of `AT_` constants.
> 
> Hmm it looks to me like we _just_ started using these constants: [4654f93](https://github.com/ceph/ceph/commit/4654f9350cb1285859f58e1bc0abdcc9e141f879)
> 
> So I think we just want to stick with the original AT_NO_ATTR_SYNC that Pacific was using.

@vshankar @joscollin @gregsfortytwo Please find link for similar issue: https://stackoverflow.com/questions/53810990/how-to-use-statx-syscall
I think we should also need similar implementation.

2022-06-14 05:48 UTC, joscollin commented
> 
> Please find link for similar issue: https://stackoverflow.com/questions/53810990/how-to-use-statx-syscall I think we should also need similar implementation. @vshankar @joscollin @gregsfortytwo Your thoughts?

There are two issues here. So it needs a backport first [1] and then resolve stat.h path.
[1] https://tracker.ceph.com/issues/55253

2022-06-15 04:42 UTC, nmshelke commented
@yuriw the pacific build failure due to these changes still not fixed. Hence removing tag ```wip-yuri3-testing```

2022-06-27 07:41 UTC, vshankar commented
I guess its fine to drop this change since its really not a critical backport. What do others think?

2022-06-29 05:48 UTC, nmshelke commented
> I guess its fine to drop this change since its really not a critical backport. What do others think?

I am okay to drop this (backport) for pacific.

2022-07-12 09:39 UTC, nmshelke commented
Closing PR since its really not a critical backport.

2022-07-12 09:39 UTC, closed without merging