Docs: Disable double dashes "--" smartquotes convertion to en-dashs "–"
ceph/ceph pull request #46195
Opened 2022-05-08 07:22 UTC by snosratiershad

Double dashes ("--") are converted to [en]dash ("–") which is looks like a single dash.
It's because of docutils smartquotes which is enabled by default by sphinx.
I think it's better to display commands like ```radosgw bucket radoslist --bucket=<bucket>``` instead of ```radosgw bucket radoslist –bucket=<bucket>```.
I just changed the smartquotes_action (added in 1.6.6 version) configuration from default value ("qDe") to "qe" to disable only em- and en-Dashes transformation.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

2022-05-08 07:31 UTC, snosratiershad commented
FYI: I just signed the commits with a key which includes my company email in it's information and for a unknown reasons Github doesn't send any verification email to my company email: salar.nosratiershad@sotoon.ir. it's the reason why signatures labeled "Unverified". Sorry about it.

2022-05-09 15:26 UTC, snosratiershad commented
jenkins test signed

2022-05-10 06:24 UTC, snosratiershad commented
jenkins test signed

2022-06-11 11:48 UTC, snosratiershad commented
@djgalloway, Is there anything I can help about this PR?

2022-06-11 17:12 UTC, anthonyeleven commented
Hi.  Please update the PR and commit messages to something like the below and I’ll approve.  Conversions like this confound cut/paste and I’ve seen them cause an outage.  

doc: Disable double dashes "--" smartquotes conversion to en-dashes

doc not docs, spelling of conversion.

2022-06-11 17:13 UTC, anthonyeleven requested changes
Please make the requested changes

2022-06-11 19:08 UTC, snosratiershad commented
@anthonyeleven , I fixed the typo, the branch name is still wrong, but I think it would not effect commit message, If it is, tell me to creating another PR with true branch.
Thank you

2022-06-11 19:16 UTC, anthonyeleven commented
? I see this as merging to `main` ; David updated that.  He renamed `master` to `main` recently, as the term `master` has certain connotations that are best avoided.  So this looks good to go to me, am I missing something?

2022-06-11 19:27 UTC, snosratiershad commented
@anthonyeleven, you are right, I didn't mean that. actually I told this about my PR forks branch name ` fix-docs-double-dash-convertion-to-em-dash`, which has the same issue with conversion spell. I'm sorry about that, I can't change it's name in a open PR.

2022-06-11 20:31 UTC, anthonyeleven commented
Ah. The name of your branch isn't important, nobody sees that.

2022-06-11 20:32 UTC, anthonyeleven approved these changes

2022-06-11 20:32 UTC, merged