doc/man/8: Add enable_stretch_mode docs
ceph/ceph pull request #46200
Opened 2022-05-09 08:28 UTC by elacunza

Explanation taken from ceph mon -h, plus additional sentence for explaining
new_crush_rule arg.

Signed-off-by: Eneko Lacunza <elacunza@binovo.es>

2022-05-09 09:09 UTC, anthonyeleven requested changes
Nice.  A couple of requests:

1) When I first read

>Subcommand ``enable_stretch_mode`` enables stretch mode, changing the peering
rules and failure handling on all pools with <tiebreaker_mon> as the tiebreaker

I interpreted this to mean that enabling strech mode changes the peering rules and failure handling on only those pools that have <tiebreaker_mon> set as the <tiebreaker>.  But I don't *think* that's the intent, maybe add a comma after `pools`?

2)
>and setting <dividing_bucket> locations as the units for stretching across.

FWIW I had to go to https://docs.ceph.com/en/latest/rados/operations/stretch-mode/ to discern what this means, so I get it, but I humbly suggest that this may be unclear for some readers, especially `units`.  I've talked to experienced Ceph folks who were surprised that there are CRUSH bucket types other than `rack`, `host`, and `osd`, and even more so that one can create new ones.  Might I suggest something like a period after `tiebreaker`, then a new sentence something like the below, which is very off-the-cuff:

>For a given PG to successfully peer and be marked ``active``, ``min_size`` replicas will now need to be active under all (currently two) CRUSH buckets of type ``dividing_bucket``.  This will typically be ``datacenter`` or other CRUSH hierarchy bucket type that denotes physically or logically distant subdivisions.

2022-05-09 09:20 UTC, elacunza commented
> Nice. A couple of requests:
> 
>     1. When I first read
> 
> > Subcommand `enable_stretch_mode` enables stretch mode, changing the peering
> > rules and failure handling on all pools with <tiebreaker_mon> as the tiebreaker
> 
> I interpreted this to mean that enabling strech mode changes the peering rules and failure handling on only those pools that have <tiebreaker_mon> set as the . But I don't _think_ that's the intent, maybe add a comma after `pools`?

Of course not, tiebreaker mon isn't linked to a pool :)
Shall I PR that very change to "ceph mon -h" as well?

> 
> 
> > and setting <dividing_bucket> locations as the units for stretching across.
> 
> FWIW I had to go to https://docs.ceph.com/en/latest/rados/operations/stretch-mode/ to discern what this means, so I get it, but I humbly suggest that this may be unclear for some readers, especially `units`. I've talked to experienced Ceph folks who were surprised that there are CRUSH bucket types other than `rack`, `host`, and `osd`, and even more so that one can create new ones. Might I suggest something like a period after `tiebreaker`, then a new sentence something like the below, which is very off-the-cuff:
> 
> > For a given PG to successfully peer and be marked `active`, `min_size` replicas will now need to be active under all (currently two) CRUSH buckets of type `dividing_bucket`.  This will typically be `datacenter` or other CRUSH hierarchy bucket type that denotes physically or logically distant subdivisions.

As the rest of commands are very briefly explained, I tried to keep short, just explaining the missing arg. But your explanation is  good. I thought about linking to the full Stretch cluster docs, but I'm not very sure how to do so from a manpage (that also is published online). Any example I could use as a base?

Thanks

2022-05-09 17:05 UTC, elacunza commented
Ok so let's concentrate in this manpage. I don't think we can explain in enough detail stretch mode in ceph manpage, that would take a manpage on its own. I wanted to add this detail because those manpages are published along the docs online, and it is shocking to only find stretch related commands only in the stretch docs but not in CLI reference docs :)

2022-06-11 21:02 UTC, anthonyeleven approved these changes

2022-06-11 21:02 UTC, merged