doc: add note about checking pending stray directory entries before initiating upgrade
ceph/ceph pull request #46237
Opened 2022-05-12 06:56 UTC by vshankar

Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-05-12 06:57 UTC, vshankar commented
@huww98 FYI

2022-05-12 07:11 UTC, huww98 commented
Stray files should be OK. Only stray directories would crash MDS. Getting rid of all stray files may be very hard, we always have thousands of them.

We use the following script to identify stray directories:

Dump the content of all strays (sleep to avoid overloading the MDS if we have a lot of strays):
```bash
for i in {0..9}; do ceph tell mds.<rank> dump tree "~mdsdir/stray${i}" > mds<rank>/stray${i}.json; sleep 2; done
```

Then run the following python script:
```Python
import json

for i_mds in range(2):
    for i_stray in range(10):
        l = json.load(open(f'mds{i_mds}/stray{i_stray}.json'))
        for inode in l:
            if inode['nlink'] > 0:
                continue
            if inode['dir_layout']['dir_hash'] == 0:
                continue
            print(f'mds{i_mds} ino:{inode["ino"]:x}', inode['stray_prior_path'], [c['client_id'] for c in inode['client_caps']])
```

2022-05-12 08:08 UTC, vshankar commented
> Stray files should be OK. Only stray directories would crash MDS. Getting rid of all stray files may be very hard, we always have thousands of them.

Right. Ideally we would want the admins to check this via a single command (w/ jq magic) rather than running custom script. I'll see what I can come up with.

> 
> We use the following script to identify stray directories:
> 
> Dump the content of all strays (sleep to avoid overloading the MDS if we have a lot of strays):
> 
> ```shell
> for i in {0..9}; do ceph tell mds.<rank> dump tree "~mdsdir/stray${i}" > mds<rank>/stray${i}.json; sleep 2; done
> ```
> 
> Then run the following python script:
> 
> ```python
> import json
> 
> for i_mds in range(2):
>     for i_stray in range(10):
>         l = json.load(open(f'mds{i_mds}/stray{i_stray}.json'))
>         for inode in l:
>             if inode['nlink'] > 0:
>                 continue
>             if inode['dir_layout']['dir_hash'] == 0:
>                 continue
>             print(f'mds{i_mds} ino:{inode["ino"]:x}', inode['stray_prior_path'], [c['client_id'] for c in inode['client_caps']])
> ```

2022-05-12 09:22 UTC, vshankar commented
@huww98 How about something like (e.g., for rank1, stray0):

```
ceph tell mds.1 dump tree ~mdsdir/stray0 2>/dev/null |  jq '.[] | select ((.nlink == 0 or .dir_layout.dir_hash > 0) and .stray_prior_path != "") | .stray_prior_path' | wc -l
```

2022-05-12 14:11 UTC, huww98 commented
> @huww98 How about something like (e.g., for rank1, stray0):
> 
> ```
> ceph tell mds.1 dump tree ~mdsdir/stray0 2>/dev/null |  jq '.[] | select ((.nlink == 0 or .dir_layout.dir_hash > 0) and .stray_prior_path != "") | .stray_prior_path' | wc -l
> ```

@vshankar should be `.nlink == 0 and .dir_layout.dir_hash > 0` (`and` instead of `or`)

Besides, why `.stray_prior_path != ""`? if it is really empty for some reason, we may need to identify the stray dir by other means, instead of ignoring it.

2022-05-12 14:34 UTC, vshankar commented
> > @huww98 How about something like (e.g., for rank1, stray0):
> > ```
> > ceph tell mds.1 dump tree ~mdsdir/stray0 2>/dev/null |  jq '.[] | select ((.nlink == 0 or .dir_layout.dir_hash > 0) and .stray_prior_path != "") | .stray_prior_path' | wc -l
> > ```
> 
> @vshankar should be `.nlink == 0 and .dir_layout.dir_hash > 0` (`and` instead of `or`)
> 
> Besides, why `.stray_prior_path != ""`? if it is really empty for some reason, we may need to identify the stray dir by other means, instead of ignoring it.

ah yes! thx for noticing that.

regarding empty stray_prior_path, that's in the inode dump of the stray directory itself

```
    {
        "ino": 1541,
        ....
        ....
        "stray_prior_path": "",
        ....
        ....
    }
```

2022-05-13 02:46 UTC, huww98 commented
> regarding empty stray_prior_path, that's in the inode dump of the stray directory itself

That's why I use `.nlink == 0` in the filter. The stray directory itself should have nlink == 1

2022-05-13 02:51 UTC, vshankar commented
> > regarding empty stray_prior_path, that's in the inode dump of the stray directory itself
> 
> That's why I use `.nlink == 0` in the filter. The stray directory itself should have nlink == 1

In that case, I think the inode dump is a bit incorrect for some of the dirs. Let me check.

2022-05-13 02:54 UTC, vshankar commented
@huww98 OK -- this is what we need:

```
 jq '.[] | select (.nlink == 0 and .dir_layout.dir_hash > 0) | .stray_prior_path' | wc -l
```

jq was throwing an extra "\n" at the end that bumped up the count.

2022-05-13 09:59 UTC, vshankar commented
updated and pushed - please take a look.

2022-05-13 10:48 UTC, huww98 commented on doc/releases/pacific.rst
> +     # for idx in {0..9}; do ceph tell mds.<rank> dump tree ~mdsdir/stray$idx| jq '.[] | select (.nlink == 0and .dir_layout.dir_hash > 0) | .stray_prior_path' | wc -l; done
Missing a space before `and`.

2022-05-13 10:49 UTC, huww98 requested changes
Missing a space before `and`.

2022-05-13 10:54 UTC, vshankar commented
> Missing a space before `and`.

fixed.

2022-05-13 11:01 UTC, huww98 approved these changes

2022-05-13 11:02 UTC, kotreshhr approved these changes

2022-05-13 11:03 UTC, lxbsz approved these changes
LGTM.

2022-05-13 12:40 UTC, merged