quincy: mgr, mon: Keep upto date metadata with mgr for MONs
ceph/ceph pull request #46559
Opened 2022-06-08 02:24 UTC by pdvian

backport tracker: https://tracker.ceph.com/issues/55305

---

backport of https://github.com/ceph/ceph/pull/45670
parent tracker: https://tracker.ceph.com/issues/55088

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2022-06-10 21:52 UTC, ljflores requested changes
@pdvian see this tracker, which I believe is related to this PR:
https://tracker.ceph.com/issues/55322

This failure does not occur every time (it fails 10/25 times on main; 15/25 times on pacific), which is why it was not caught initially.

The Pacific backport was already merged, but we should investigate whether this Tracker is related before the Quincy backport is merged.

Let me know if you have any questions! I am trying to debug on my end as well since I was involved in reviewing the main and pacific PRs.

2022-08-25 03:13 UTC, pdvian commented
jenkins test windows

2022-09-04 10:06 UTC, Matan-B commented
LGTM, 11/19 failures failed to fetch packages since we don't build quincy for jammy.

0 Related Failures.
19 Tracked unrelated Failures.
0 Newly Tracked Failures.
0 Tracked dead Jobs.

https://pulpito.ceph.com/yuriw-2022-09-01_15:09:54-rados-wip-yuri2-testing-2022-08-29-0846-quincy-distro-default-smithi/

Rerun of:
https://pulpito.ceph.com/yuriw-2022-08-30_17:06:35-rados-wip-yuri2-testing-2022-08-29-0846-quincy-distro-default-smithi/

Failures, unrelated:
7005337, 7005340, 7005341, 7005344, 7005345, 7005346
7005347, 7005350 , 7005352, 7005354, 7005355: https://tracker.ceph.com/issues/57314
7005338, 7005348, 7005353: https://tracker.ceph.com/issues/57368
7005339, 7005351: https://tracker.ceph.com/issues/57346
7005342, 7005349: https://tracker.ceph.com/issues/57297
7005343: https://tracker.ceph.com/issues/56951

Details:

7005337, 7005340, 7005341, 7005344, 7005345, 7005346
7005347, 7005350 , 7005352, 7005354, 7005355: quincy: rados/cephadm: Failed to fetch package version from https://shaman.ceph.com...
7005338, 7005348, 7005353: The CustomResourceDefinition "installations.operator.tigera.io" is
7005339, 7005351: quincy: expected valgrind issues and found none
7005342, 7005349: quincy: cephadm: RuntimeError: Failed command: apt-get update: E: The repository 'https://download.ceph.com/debian-octopus jammy Release' does not have a Release file.
7005343: rook/smoke: Updating cephclusters/rook-ceph is forbidden

2022-09-05 14:05 UTC, yuriw commented
@pdvian @ljflores this is ready for merge https://trello.com/c/0opnlWjz

pls merge

2022-09-06 16:15 UTC, yuriw commented
jenkins test api

2022-09-06 16:16 UTC, ljflores approved these changes

2022-09-06 20:41 UTC, merged