quincy: client: Inode::hold_caps_until is time from monotonic clock now.
ceph/ceph pull request #46563
Opened 2022-06-08 07:28 UTC by neesingh-rh

backport tracker: https://tracker.ceph.com/issues/55936

---

backport of https://github.com/ceph/ceph/pull/44247
parent tracker: https://tracker.ceph.com/issues/52982

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2022-06-08 22:11 UTC, ljflores requested changes
See https://github.com/ceph/ceph/pull/44247#issuecomment-1150462645.

2022-06-10 17:05 UTC, ljflores commented
The commit from https://github.com/ceph/ceph/pull/46604 should be included in this backport.

2022-06-10 21:56 UTC, ljflores approved these changes
@yuriw this should go through the rados and cephfs suite

2022-06-10 21:57 UTC, ljflores commented
jenkins test api

2022-07-22 10:29 UTC, rishabh-d-dave commented
@neesingh-rh @ljflores This PR is backport of 2 PRs: https://github.com/ceph/ceph/pull/44247and https://github.com/ceph/ceph/pull/46604. The latter PR and it's tracker are not linked to this backport. IMO, this should be done for future reference.

2022-07-22 10:44 UTC, neesingh-rh commented
> @neesingh-rh @ljflores This PR is backport of 2 PRs: https://github.com/ceph/ceph/pull/44247and #46604. The latter PR and it's tracker are not linked to this backport. IMO, this should be done for future reference.

@rishabh-d-dave Done!! Thanks:)

2022-07-22 11:09 UTC, rishabh-d-dave commented
> > @neesingh-rh @ljflores This PR is backport of 2 PRs: https://github.com/ceph/ceph/pull/44247and #46604. The latter PR and it's tracker are not linked to this backport. IMO, this should be done for future reference.
> 
> @rishabh-d-dave Done!! Thanks:)

Thank you for the quick response!

2022-07-22 11:11 UTC, rishabh-d-dave approved these changes
fs approved

2022-07-22 12:07 UTC, merged