doc: adding ceph post-upgrade section
ceph/ceph pull request #46716
Opened 2022-06-16 14:32 UTC by rkachach

Fixes: https://tracker.ceph.com/issues/54474

Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-06-16 14:48 UTC, guits commented on doc/cephadm/upgrade.rst
> +doesn't use ``cephm shell``) to a version compatible with the new version.
```suggestion
doesn't use ``cephadm shell``) to a version compatible with the new version.
```

2022-06-16 17:41 UTC, anthonyeleven requested changes
Please change the commit/PR messages to

doc/cephadm: Add post-upgrade section

2022-06-17 09:30 UTC, rkachach commented
> Please change the commit/PR messages to
> 
> doc/cephadm: Add post-upgrade section

Fixed

2022-06-17 13:40 UTC, rkachach commented
jenkins test dashboard cephadm

2022-06-18 05:24 UTC, anthonyeleven approved these changes

2022-06-21 22:07 UTC, merged