AdminSocket for alien_store
ceph/ceph pull request #46768
Opened 2022-06-21 12:42 UTC by aclamk

Introduced gluer that exposed classic admin socket commands through crimson admin socket.
This works only for alien_store.

It is based on #46618

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-06-22 22:43 UTC, athanatos requested changes
I think this approach is perfect -- it should pass through all of the BlueStore admin socket commands appropriately.

2022-06-22 22:43 UTC, athanatos commented on src/crimson/os/alienstore/alien_admin_socket.cc
> +    :string_prefix(prefix_str)
Space after : and after ,

2022-06-22 22:43 UTC, athanatos commented on src/crimson/os/alienstore/alien_admin_socket.cc
> + public:
public/private should not be indented

2022-06-22 22:43 UTC, athanatos commented on src/crimson/os/alienstore/alien_admin_socket.cc
> +:AdminSocket(cct)
Indent to level of unsigned and add spaces after : and ,

2022-06-22 22:43 UTC, athanatos commented on src/crimson/os/alienstore/alien_admin_socket.cc
> +static const std::string alien_prefix = "alien ";
Not adding the additional alien prefix would also I think avoid needing to store a string in CnAdminSocketHook?

2022-06-23 12:19 UTC, aclamk commented
jenkins test make check

2022-07-19 03:53 UTC, athanatos commented
@aclamk I made some comments above, let me know if they make sense.  Also needs to be rebased.

2023-05-16 13:04 UTC, closed without merging