doc: add steps to the adoption process
ceph/ceph pull request #46847
Opened 2022-06-25 20:09 UTC by gurubert

There are a few steps missing the get the full orchestrator experience.

Signed-off-by: Robert Sander <gurubert@gurubert.de>

2022-06-25 20:59 UTC, anthonyeleven requested changes

2022-06-25 20:59 UTC, anthonyeleven commented on doc/cephadm/adoption.rst
> +
Double backquotes around `container_image`

2022-06-25 20:59 UTC, anthonyeleven commented on doc/cephadm/adoption.rst
> +#. Remove ceph packages from the host except for ceph-common to keep ceph commandline tools.
Ceph capital

2022-06-27 13:12 UTC, adk3798 approved these changes

2022-06-27 15:22 UTC, gurubert commented on doc/cephadm/adoption.rst
> +
commit 10dd35e1018e8456ff71efabcab1ce66e5f214ed

2022-06-27 15:23 UTC, gurubert commented on doc/cephadm/adoption.rst
> +#. Remove ceph packages from the host except for ceph-common to keep ceph commandline tools.
commit dc20a0dea47448aeb8d66b0dd37e541298200377

2022-06-27 23:43 UTC, anthonyeleven commented
LGTM, but PR and commit message should be like "doc/cephadm: Add steps to the adoption process"

2022-06-27 23:43 UTC, anthonyeleven approved these changes

2022-06-29 00:26 UTC, adk3798 commented
@gurubert FYI, there's a required check in our github CI that all commits have a signed-off-by line in them. Before merging we have to either add signatures to the unsigned commits or squash the commits (preferable in this case I think) then make sure the remaining commit is signed.

Thanks

2022-07-04 08:05 UTC, gurubert commented
OK, I will create a new pull request that is properly signed off.

2022-07-04 08:05 UTC, closed without merging