Packet drop alert overly sensitive
ceph/ceph pull request #46842
Opened 2022-06-24 19:43 UTC by mmgaggle

The alert description states > 10 packets/s, but the actual alert
logic is looking at whether there have been >= 10 packets dropped
over a minute sized window. If the intent is to only alert if there
are more than 10 packets/s dropped, the check should be >= 600.

Signed-off-by: kbader <kbader@redhat.com>

2022-06-26 22:38 UTC, pcuzner commented
@mmgaggle agree the alert description doesn't reflect the expression :) Do you think we need both a % drop rate AND a specific packet drop count to indicate a problem?

2022-06-29 17:52 UTC, mmgaggle commented
Well I don't think we should alert if the counter on the host is higher than some threshold, since the counter would be total drops since the machine was booted. The prometheus `rate` function should only be used with gauges iiuc, and so increase is the right thing to use here since it's a counter.

2022-07-08 00:14 UTC, pcuzner commented
rate and increase functions, both work on counters only. 

As far as this change is concerned, I think it makes sense to just merge it. I'm surprised it hasn't been pick up on before now.
@aaSharma14 thoughts?

2022-07-08 05:24 UTC, aaSharma14 commented
jenkins test make check

2022-07-08 05:46 UTC, aaSharma14 requested changes
Thank you @mmgaggle for the contribution

2022-07-08 05:46 UTC, aaSharma14 commented on monitoring/ceph-mixin/prometheus_alerts.yml
> +          ) >= 600
You need to change the value in the alert description as well - 

`Node {{ $labels.instance }} experiences packet drop > 0.01% or >
            600 packets/s on interface {{ $labels.device }}.`

2022-07-08 05:55 UTC, aaSharma14 commented
Also, the test_alerts.yml needs to be updated according to the new value. You can make the following changes the test_alerts.yml file -

`# network packets dropped
 - interval: 1s
   input_series:
    - series: 'node_network_receive_drop_total{device="eth0",
      instance="node-exporter",job="node-exporter"}'
      values: '10+10x700'
    - series: 'node_network_transmit_drop_total{device="eth0",
      instance="node-exporter",job="node-exporter"}'
      values: '10+10x700'
   promql_expr_test:
     - expr: |
         (
           increase(node_network_receive_drop_total{device!="lo"}[1m]) +
           increase(node_network_transmit_drop_total{device!="lo"}[1m])
         ) / (
           increase(node_network_receive_packets_total{device!="lo"}[1m]) +
           increase(node_network_transmit_packets_total{device!="lo"}[1m])
         ) >= 0.0001 or (
           increase(node_network_receive_drop_total{device!="lo"}[1m]) +
           increase(node_network_transmit_drop_total{device!="lo"}[1m])
         ) >= 600

       eval_time: 5m
       exp_samples:
         - labels: '{device="eth0", instance="node-exporter",
           job="node-exporter"}'
           value: 1.2E+03
   alert_rule_test:
     - eval_time: 5m
       alertname: CephNodeNetworkPacketDrops
       exp_alerts:
       - exp_labels:
           device: eth0
           instance: node-exporter
           job: node-exporter
           oid: 1.3.6.1.4.1.50495.1.2.1.8.2
           severity: warning
           type: ceph_default
         exp_annotations:
           summary: One or more Nics is seeing packet drops
           description: >
             Node node-exporter experiences packet drop > 0.01% or >
             600 packets/s on interface eth0.`

2022-07-08 18:07 UTC, epuertat approved these changes
@mmgaggle we had a discussion about [these thresholds here](https://github.com/ceph/ceph/pull/38030#discussion_r572340971). Basically @p-se started with a looser threshold and @wido and I asked for a stricter one. In any case, after checking the meaning of `increase`, yes, 600 is obviously 10 p/s for 1 minute (@aaSharma14).

BTW this also needs to be fixes in the `CephNodeNetworkPacketErrors` alert.

2022-08-24 11:51 UTC, epuertat commented
This PR would be superseded by https://github.com/ceph/ceph/pull/47707 (which makes the packet drop rate/count build-time configurable).

Let's close this one and continue the discussion there.

Thanks @mmgaggle for bringing this up and your work here!

2022-08-24 11:51 UTC, closed without merging