osd/scrub: modify scrub behaviour under no-scrub
ceph/ceph pull request #46891
Opened 2022-06-29 09:28 UTC by ronen-fr

Fix no-scrub & nodeep-scrub related code to match requirements:
- deep scrubs should be allowed to execute when no-scrub is set;
- some initiated scrubs (i.e. not periodic ones) might be changed
  from the requested 'deep' to 'shallow'.

Signed-off-by: Ronen Friedman <rfriedma@redhat.com>

2022-07-15 07:50 UTC, amathuria commented on qa/standalone/scrub/osd-scrub-test.sh
> +    # set both 'no scrub' & 'no deep', then request a deep-scrub.
'no deep-scrub'

2022-07-15 09:47 UTC, amathuria requested changes

2022-07-17 08:27 UTC, ronen-fr commented on qa/standalone/scrub/osd-scrub-test.sh
> +    # set both 'no scrub' & 'no deep', then request a deep-scrub.
fixed

2022-08-01 13:38 UTC, amathuria requested changes

2022-08-01 16:24 UTC, ronen-fr commented on src/osd/PG.h
> +  std::optional<requested_scrub_t> validate_periodic_mode(
The name got too long... I'd rather stay with this form.

2022-08-08 07:58 UTC, amathuria approved these changes

2022-08-08 07:58 UTC, amathuria commented
jenkins test make check

2022-08-08 07:59 UTC, amathuria commented
jenkins test api

2022-08-08 08:57 UTC, neha-ojha commented
jenkins retest this please

2022-08-08 09:14 UTC, ronen-fr commented
needs rebasing to compile. Working on it.

2022-08-08 10:09 UTC, ronen-fr commented
API tests failing with 'AttributeError: module 'collections' has no attribute 'MutableMapping''.
Retrying.

2022-08-08 14:26 UTC, ronen-fr commented
jenkins retest this please

2022-08-09 07:11 UTC, ronen-fr commented
jenkins retest this please

2022-08-13 18:47 UTC, ronen-fr commented
jenkins test make check

2022-08-13 18:47 UTC, ronen-fr commented
jenkins retest this please

2022-08-14 09:06 UTC, ronen-fr commented
None of the failures is caused by the PRs changes:
6965704 & 6965741: rados/dashboard e2e: fails in ‘main’, too (also, for example, in yuriw-2022-06-01_23:21:01-rados-wip-yuri3-testing-2022-06-01-1035-quincy-distro-default-smithi).
6965705 & 6965736: rados/rook/smoke: fails in ‘main’, too.
6965738 & 6965746: rados/upgrade: not related. Probably https://tracker.ceph.com/issues/55853.
6965739 & 6965750: rados/valgrind-leaks: MGR or test issue. Not related.
6965742 & 6965744: rados/rook/smoke: unrelated, as no OSDs were involved. 
6965737, 6965745: rados/singleton-nomsgr/admin_socket_output - ubuntu: fixed in main
‘main’ + rhel: OK (rfriedma-2022-08-13_07:39:27-rados:singleton-nomsgr-wip-rf-like-main-distro-default-smithi)
with the ‘redo-noscrub’ PR + centos: OK (rfriedma-2022-08-13_07:41:33-rados:singleton-nomsgr-wip-rf-like-redo-distro-default-smithi)

The other two seem to exist in ‘main’ too, to be dist related, and might be a regression from the last month. 
6965710, 6965743: rados/singleton-nomsgr/librados_hello_world + mon_election/connectivity - centos-8
‘main’ - fails ( ’mon_election/classic’ + rhel_8) see rfriedma-2022-08-13_08:48:40-rados:singleton-nomsgr-wip-rf-like-main-distro-default-smithi.
with the PR: fails on ’mon_election/classic’ + ubuntu (rfriedma-2022-08-13_14:00:13-rados:singleton-nomsgr-wip-rf-like-redo-distro-default-smithi)
https://tracker.ceph.com/issues/57122 created.

2022-08-14 09:09 UTC, merged