crimson, doc: document installing crimson with cephadm
ceph/ceph pull request #47082
Opened 2022-07-13 14:43 UTC by rzarzynski

Signed-off-by: Radosław Zarzyński <rzarzyns@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-07-13 16:48 UTC, anthonyeleven requested changes

2022-07-13 16:48 UTC, anthonyeleven commented on doc/dev/crimson/crimson.rst
> +An alternative to building Crimson from sources is to use container images built
s/sources/source/

2022-07-13 16:48 UTC, anthonyeleven commented on doc/dev/crimson/crimson.rst
> +In the opened file change ``DEFAULT_IMAGE = 'quay.ceph.io/ceph-ci/ceph:master'``
s/opened//

2022-07-26 07:43 UTC, ljx023 commented
I tried to deploy crimson using cephadm according to this document and it worked. 

It would be better if adding some description about image build in the future.

2022-07-26 13:14 UTC, zdover23 commented
jenkins retest this please

2022-07-26 13:19 UTC, zdover23 commented
@rzarzynski, you're missing the "Signed-off by:" line in your commit.

Here's a link to the instructions for configuring your Ceph environment to append the "Signed-off by:" line:

https://docs.ceph.com/en/quincy/dev/developer_guide/basic-workflow/#configuring-your-local-environment

And here's the section on amending an existing PR:

https://docs.ceph.com/en/quincy/dev/developer_guide/basic-workflow/#amending-your-pr

Note to future me (not to Radosław): It might not be a bad idea to write a step-by-step guide to squashing.

2022-07-26 13:20 UTC, rzarzynski commented
@anthonyeleven: Thanks for the review! I addressed the comments. Would you mind to retake a look?

2022-07-26 13:22 UTC, zdover23 commented
> @anthonyeleven: Thanks for the review! I addressed the comments. Would you mind to retake a look?


@rzarzynski: see https://github.com/ceph/ceph/pull/47082#issuecomment-1195475442

We won't be able to merge this PR until the "Signed-off by:" line is present in the commit message.

2022-07-26 13:26 UTC, rzarzynski commented
@zdover23: I think even the original commit has the tag already:

```
commit 2ca9669e96b9e140cd66a522a151bcb0e47b5215
Author: Radoslaw Zarzynski <rzarzynski@redhat.com>
Date:   Wed Jul 13 14:33:06 2022 +0200

    crimson, doc: document installing crimson with cephadm
    
    Signed-off-by: Rados<C5><82>aw Zarzy<C5><84>ski <rzarzyns@redhat.com>
```

However, somehow (hmm, developing on desktop to look on the HTMLized doc?) UTF-8 sneaked into my name and – perhaps – makes the bot angry. Fixing!

2022-07-26 13:28 UTC, zdover23 commented
> @zdover23: I think even the original commit has the tag already:
> 
> ```
> commit 2ca9669e96b9e140cd66a522a151bcb0e47b5215
> Author: Radoslaw Zarzynski <rzarzynski@redhat.com>
> Date:   Wed Jul 13 14:33:06 2022 +0200
> 
>     crimson, doc: document installing crimson with cephadm
>     
>     Signed-off-by: Rados<C5><82>aw Zarzy<C5><84>ski <rzarzyns@redhat.com>
> ```
> 
> However, somehow (hmm, developing on desktop to look on the HTMLized doc?) UTF-8 sneaked into my name and – perhaps – makes the bot angry. Fixing!

I haven't tested this on this PR myself, but I suspect that the indentation is what's causing the "Signed-off by:" check to fail. Move that line to the left margin and let's run it again.

2022-07-26 13:32 UTC, rzarzynski commented
Huh!

```
=================================== FAILURES ===================================
__________________________ TestCommits.test_doc_title __________________________

self = <test_commits.TestCommits object at 0x7f8460fd66a0>

    @pytest.mark.doc_test
    def test_doc_title(self):
        doc_regex = '\nDate:[^\n]+\n\n    doc'
        all_commits = 'git log -z --no-merges origin/%s..%s' % (
            self.target_branch, self.source_branch)
        wrong_commits = list(filterfalse(
            re.compile(doc_regex).search,
            self.command(all_commits).split('\0')))
        if wrong_commits:
            raise AssertionError("\n".join([
                "The title/s of following commit/s is/are not started with 'doc', but they only touch files under 'doc/'. Please make sure the commit titles",
                "are started with 'doc'. See the 'Submitting Patches' guide:",
                "https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title",
                ""] +
>               wrong_commits
            ))
E           AssertionError: The title/s of following commit/s is/are not started with 'doc', but they only touch files under 'doc/'. Please make sure the commit titles
E           are started with 'doc'. See the 'Submitting Patches' guide:
E           https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title
E           
E           commit f27b1741a40ff0bb056a0df4a8d96b4f472d688a
E           Author: Radosław Zarzyński <rzarzyns@redhat.com>
E           Date:   Wed Jul 13 14:33:06 2022 +0200
E           
E               crimson, doc: document installing crimson with cephadm
E               
E               Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>
```

2022-07-26 13:38 UTC, zdover23 approved these changes

2022-07-26 14:37 UTC, anthonyeleven approved these changes

2022-07-26 14:45 UTC, merged

2022-07-26 14:48 UTC, zdover23 commented
https://github.com/ceph/ceph/pull/47283 - Quincy backport