monitoring/ceph-mixin: fix typos
ceph/ceph pull request #47130
Opened 2022-07-16 10:52 UTC by lonniebe

fixing minor typos.

Signed-off-by: Lonnie Berry <lonchbe@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-07-16 11:11 UTC, tchaikov approved these changes

2022-07-16 17:38 UTC, anthonyeleven requested changes

2022-07-16 17:38 UTC, anthonyeleven commented on monitoring/ceph-mixin/README.md
> +prometheus mixin. You can find more resources about mixins in general on
Prometheus

2022-07-16 19:11 UTC, anthonyeleven approved these changes

2022-07-16 19:11 UTC, lonniebe commented on monitoring/ceph-mixin/README.md
> +prometheus mixin. You can find more resources about mixins in general on
fixed it, thank you.

2022-07-16 19:48 UTC, anthonyeleven approved these changes

2022-07-17 03:28 UTC, anthonyeleven commented
Jenkins retest this please

2022-07-17 19:21 UTC, lonniebe commented
@anthonyeleven I had some extra commits pushed accidently, fixed now.
Thank you for the quick review! 👍

2022-07-17 19:22 UTC, lonniebe commented
jenkins test dashboard cephadm

2022-07-17 21:17 UTC, anthonyeleven commented
I suspect that the Jenkins / check rig is broken, hence the errors.  I don’t think they’re related to your changes but we can’t merge until we resolve them

2022-07-18 07:16 UTC, anthonyeleven commented
jenkins please retest this

2022-07-18 07:16 UTC, anthonyeleven commented
jenkins retest this please

2022-07-18 17:03 UTC, avanthakkar approved these changes
LGTM!

2022-07-18 17:04 UTC, avanthakkar commented
jenkins test dashboard

2022-07-18 17:06 UTC, avanthakkar commented
@lonniebe  I think you need to fix unit tests 
`Unit Testing:  /home/jenkins-build/build/workspace/ceph-pull-requests/monitoring/ceph-mixin/tests_alerts/test_alerts.yml`
https://jenkins.ceph.com/job/ceph-pull-requests/99615/testReport/junit/projectroot.monitoring/ceph-mixin/run_promtool_unittests/

2022-07-18 17:07 UTC, avanthakkar commented
jenkins test windows

2022-07-27 08:42 UTC, lonniebe commented
jenkins retest this please

2022-08-22 15:14 UTC, nizamial09 commented
@lonniebe can you rebase this once more and then it'll be good to go!

2022-10-09 06:25 UTC, nizamial09 commented
jenkins test make check

2023-05-27 21:01 UTC, closed without merging