doc: 15.2.17 Release Notes
ceph/ceph pull request #47198
Opened 2022-07-20 21:27 UTC by yuriw

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-07-22 07:28 UTC, idryomov requested changes

2022-07-22 07:28 UTC, idryomov commented on doc/releases/octopus.rst
> +Octopus is the 17th stable release of Ceph.  It is named after an
This is wrong -- Octopus *is* v15.

2022-07-29 16:01 UTC, idryomov commented
Squashed the changelog regeneration commit and added an RBD note.

2022-07-29 16:02 UTC, idryomov approved these changes

2022-07-29 16:06 UTC, idryomov commented
@yuriw I think you would need to regenerate the changelog again though, once https://github.com/ceph/ceph/pull/47236 merges.  And we are going to need a release note for it, probably just copied from v17.2.2 or v16.2.10.

2022-08-02 17:31 UTC, idryomov commented
> [doc: added fs PR to the list](https://github.com/ceph/ceph/pull/47198/commits/c76031606ce7d9b9aab29f473101a6a441681ba6)

@yuriw Please add a release note in the same commit as well:

> And we are going to need a release note for it, probably just copied from v17.2.2 or v16.2.10.

2022-08-09 18:15 UTC, djgalloway commented on doc/releases/octopus.rst
> +This is the 17th backport release in the Octopus series. We recommend all
```suggestion
This is the 17th and final backport release in the Octopus series. We recommend all
```

2022-08-10 10:36 UTC, idryomov commented
Added a note for the Manila security fix and updated the release date.

2022-08-10 10:39 UTC, merged