os/bluestore: fix no deferred writing for legacy OSDs
ceph/ceph pull request #47241
Opened 2022-07-22 11:43 UTC by ifed01

Fixes: https://tracker.ceph.com/issues/56488

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-08-01 13:00 UTC, aclamk requested changes
I think "<=" commit should be dropped, and refactor commit amended to reflect logic change.

2022-08-18 17:38 UTC, aclamk commented on src/os/bluestore/BlueStore.cc
> +      has_chunk2defer |= (l < prefer_deferred_size_snapshot);
@ifed01 ping... ?

2022-08-25 08:42 UTC, cfsnyder commented
I agree with Adam's comments. This seems like a high priority fix since deferred writes are otherwise not happening at all for many clusters with default settings, right? It would be great to get this merged and backported to Pacific before the next Pacific release!

2022-08-25 13:56 UTC, ifed01 commented
> I agree with Adam's comments. This seems like a high priority fix since deferred writes are otherwise not happening at all for many clusters with default settings, right?
That's true. And I agree that Adam's comments are valid. Working on a better approach for now...

> It would be great to get this merged and backported to Pacific before the next Pacific release!

2022-08-25 14:29 UTC, cfsnyder commented
@ifed01 would you mind sharing brief details about the better approach that you're working on? Do you think that this will be ready in time for the next Pacific release?

2022-08-26 23:12 UTC, ifed01 commented
> @ifed01 would you mind sharing brief details about the better approach that you're working on? Do you think that this will be ready in time for the next Pacific release?

I've just updated the PR with a modified implementation. This also adds some comments (and new test cases) to represent the ideas behind the patch. Please let me know if you have more questions

2022-08-26 23:12 UTC, ifed01 commented
@aclamk - ready for another review round

2022-10-14 12:09 UTC, aclamk commented
@ifed01
Last week, I reviewed your solution and tested that it works.
From that point of view I think it can be merged.

However, I did not like a multitude of conditions that were needed and the fact that many unittest had to be adjusted to new revised `deferred count` changes.

I allowed myself to attempt different solution : #48490.
In any case, we need to decide on one, as they are incompatible.

More over - I believe we need a revamp of deferred write selection algorithm. 
The current one (unrelated decisions in _do_write_small, do_write_big, _do_allocate_write) make a fine-tuning impossible.

2022-11-30 11:42 UTC, ifed01 commented
Closing in favor of #48490

2022-11-30 11:42 UTC, closed without merging