mgr/dashboard: add option to resolve ip addr
ceph/ceph pull request #47265
Opened 2022-07-25 16:06 UTC by s0nea

Add the option `redirect_resolve_ip_addr` to the dashboard module.
If the option is set to `True`, try to resolve the IP address before redirecting from the passive to the active mgr instance.
If the option is set to `False`, follow the already known behavior.

Fixes: https://tracker.ceph.com/issues/56699
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-07-26 16:55 UTC, anthonyeleven requested changes

2022-07-26 16:55 UTC, anthonyeleven commented on doc/mgr/dashboard.rst
> +The redirect from the passive to the active dashboard is done via the IP
I think "from a standby to the active dashboard" might be better.

2022-07-26 16:55 UTC, anthonyeleven commented on doc/mgr/dashboard.rst
> +However, in some situation it might be helpful to redirect via the hostname.
situations

2022-07-26 16:55 UTC, anthonyeleven commented on doc/mgr/dashboard.rst
> +For example if the configured TLS certificate matches the hostnames, only. To
only the hostnames

2022-07-28 10:21 UTC, s0nea commented
@anthonyeleven updated. Thank you for your suggestions! :+1:

2022-07-28 13:46 UTC, s0nea commented
jenkins test dashboard cephadm

2022-07-28 14:20 UTC, anthonyeleven approved these changes
Docs lgtm, code should be approved by someone else

2022-08-24 12:29 UTC, epuertat approved these changes
LGTM. Just a few suggestions.

2022-08-24 12:29 UTC, epuertat commented on doc/mgr/dashboard.rst
> +You can disabled it again by::
```suggestion
You can disable it again by::
```

2022-08-24 12:29 UTC, epuertat commented on src/pybind/mgr/dashboard/module.py
> +                        if module.get_module_option('redirect_resolve_ip_addr', False):
No need to repeat the default, it's taken from the definition above:
```suggestion
                        if module.get_module_option('redirect_resolve_ip_addr'):
```

2022-08-24 12:29 UTC, epuertat commented on src/pybind/mgr/dashboard/module.py
> +                                    pass
What's this dealing with? Maybe a short comment explaining why is needed.

2022-09-06 13:42 UTC, s0nea commented
> LGTM. Just a few suggestions.

I updated the PR. @epuertat would you mind doing another review? - Thank you! :slightly_smiling_face:

2022-09-06 16:20 UTC, epuertat approved these changes
LGTM, just a small suggestion on a more concrete syntax.

2022-09-08 11:06 UTC, s0nea commented
jenkins test make check

2022-09-08 14:21 UTC, s0nea commented
jenkins test make check

2022-09-09 06:18 UTC, s0nea commented
jenkins test dashboard

2022-09-16 11:54 UTC, s0nea commented
jenkins test dashboard

2022-09-21 12:04 UTC, Pegonzal commented
jenkins test dashboard

2022-09-23 05:29 UTC, merged

2022-09-23 05:29 UTC, nizamial09 commented
@s0nea does this needs to be backported?

2022-09-23 06:26 UTC, s0nea commented
> @s0nea does this needs to be backported?

Yes, I think so. I'll take a look. Thank you!