debian: add libsqlite3-mod-ceph dependency for ceph-mgr
ceph/ceph pull request #47288
Opened 2022-07-26 21:24 UTC by batrick

with appropriate version! Without this, upgrades will keep older
versions of the module.

Fixes: https://tracker.ceph.com/issues/56274
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-07-26 21:28 UTC, batrick commented
@tchaikov seems you reverted this (almost) exact patch in 45b9da3c92a20e8bb4e6dbf6f731ccc7faf572ad. I'm not sure I understand why `shlibs:Depends` does not handle this correctly. Do you?

2022-07-27 14:46 UTC, tchaikov commented
> @tchaikov seems you reverted this (almost) exact patch in [45b9da3](https://github.com/ceph/ceph/commit/45b9da3c92a20e8bb4e6dbf6f731ccc7faf572ad). I'm not sure I understand why `shlibs:Depends` does not handle this correctly. Do you?

@batrick no sure.. i need to check the symbol tables and unpack the deb and check the dependencies first. will take a look this weekend.

2022-07-30 01:12 UTC, tchaikov commented
i downloaded the [deb packages](https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/) from a recent build. and uncompressed them to understand the dependencies and symbols, here's my findings:

```console
$ wget https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
$ tar x libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
$ tar xJvf data.tar.xz
$ nm -D ./usr/lib/libcephsqlite.so | grep cephsqlite > libcephsqlite.symbols
$ nm -D ./usr/lib/libcephsqlite.so | grep SimpleRADOSStriper >> libcephsqlite.symbols
$ cut -d' ' -f2,3 libcephsqlite.symbols | sort
T cephsqlite_setcct
T sqlite3_cephsqlite_init
T _ZN18SimpleRADOSStriper12recover_lockEv
T _ZN18SimpleRADOSStriper12set_metadataEmb
T _ZN18SimpleRADOSStriper12shrink_allocEm
T _ZN18SimpleRADOSStriper13config_loggerEPN4ceph6common11CephContextESt17basic_string_viewIcSt11char_traitsIcEEPSt10shared_ptrINS1_12PerfCountersEE
T _ZN18SimpleRADOSStriper13print_lockersERSo
T _ZN18SimpleRADOSStriper13wait_for_aiosEb
T _ZN18SimpleRADOSStriper16lock_keeper_mainEv
T _ZN18SimpleRADOSStriper18maybe_shrink_allocEv
T _ZN18SimpleRADOSStriper4lockEm
T _ZN18SimpleRADOSStriper4openEv
T _ZN18SimpleRADOSStriper4readEPvmm
T _ZN18SimpleRADOSStriper4statEPm
T _ZN18SimpleRADOSStriper5flushEv
T _ZN18SimpleRADOSStriper5writeEPKvmm
T _ZN18SimpleRADOSStriper6createEv
T _ZN18SimpleRADOSStriper6removeEv
T _ZN18SimpleRADOSStriper6str2blESt17basic_string_viewIcSt11char_traitsIcEE
T _ZN18SimpleRADOSStriper6unlockEv
T _ZN18SimpleRADOSStriper7uint2blEm
T _ZN18SimpleRADOSStriper8truncateEm
T _ZN18SimpleRADOSStriperD1Ev
T _ZN18SimpleRADOSStriperD2Ev
T _ZNK18SimpleRADOSStriper15get_next_extentEmm
u _ZGVN18SimpleRADOSStriper7biglockB5cxx11E
u _ZGVN18SimpleRADOSStriper8lockdescB5cxx11E
u _ZN18SimpleRADOSStriper10XATTR_EXCLE
u _ZN18SimpleRADOSStriper10XATTR_SIZEE
u _ZN18SimpleRADOSStriper13XATTR_VERSIONE
u _ZN18SimpleRADOSStriper15XATTR_ALLOCATEDE
u _ZN18SimpleRADOSStriper24XATTR_LAYOUT_OBJECT_SIZEE
u _ZN18SimpleRADOSStriper24XATTR_LAYOUT_STRIPE_UNITE
u _ZN18SimpleRADOSStriper25XATTR_LAYOUT_STRIPE_COUNTE
u _ZN18SimpleRADOSStriper7biglockB5cxx11E
u _ZN18SimpleRADOSStriper8lockdescB5cxx11E
V _ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEEE
V _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEEE
V _ZTVNSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEEE
W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEE6_M_runEv
```

so all they "T" symbols are also listed in https://github.com/ceph/ceph/blob/main/debian/libsqlite3-mod-ceph.symbols, also expected.


```console
$ wget https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/ceph-mgr_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
$ ar x ceph-mgr_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
$ tar xJvf control.tar.xz
$ $ grep Depends control
Depends: ceph-base (= 17.0.0-13884-g9a8f20f4-1focal), ceph-mgr-modules-core (= 17.0.0-13884-g9a8f20f4-1focal), python3-ceph-argparse, python3-cephfs, python3-distutils, python3-openssl, python3-yaml, libc6 (>= 2.28), libgcc-s1 (>= 3.0), libgoogle-perftools4, libpython3.8 (>= 3.8.2), librados2, libsqlite3-0 (>= 3.5.9), libsqlite3-mod-ceph (>= 15.2.0-1), libstdc++6 (>= 9)
```
so, as expected, the ceph-mgr depends on `libsqlite3-mod-ceph (>= 15.2.0-1)` . and the symbols can be provided by `libsqlite3-mod-ceph (>= 15.2.0-1)`

i am quoting https://tracker.ceph.com/issues/56274#note-5 , 

> symbol locations will differ, causing the segtfault

i don't quite follow this. yes, the symbols can be relocated in the text section by the linker across different versions when building the shared object. but i believe the linker should also be able to resolve to the right symbols when loading ceph-mgr executable image, this is how the linker and loader work, i believe.

i am quoting the backtrace at `/a/mchangir-2022-07-26_10:40:37-upgrade-wip-mchangir-test-pacific-to-quincy-upgrade-with-snap_schedule-test-pacific-distro-default-smithi/6947433/remote/*/log/ceph-mgr.x.log.gz` also:

```
 ceph version 17.0.0-13700-g44739573 (447395734d5de358016cdb44830f44fe6ad6a124) quincy (dev)
 1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7ffff6a72420]
 2: pthread_mutex_lock()
 3: (ceph::logging::Log::submit_entry(ceph::logging::Entry&&)+0x45) [0x7ffff714c075]
 4: cephsqlite_setcct()
 5: (Mgr::init()+0x19c5) [0x5555557cd7e5]
 6: /usr/bin/ceph-mgr(+0x27a711) [0x5555557ce711]
 7: (Context::complete(int)+0xd) [0x55555571941d]
 8: (Finisher::finisher_thread_entry()+0x19d) [0x7ffff6df110d]
 9: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7ffff6a66609]
 10: clone()
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

so probably it is because `cephsqlite_setcct` is not backward compatible? and it is not versioned yet. so `dh_makeshlibs` and `dpkg-gensymbols` think that the older libsqlite3-mod-ceph can also satisfy the requirement.

i am not against the change. just wanted to explain my guess on the root cause. but a bigger question is, why `cephsqlite_setcct` fails ? it is supposed to be a public API and exposed by `libcephsqlite`.

2022-07-30 20:54 UTC, batrick commented
> i downloaded the [deb packages](https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/) from a recent build. and uncompressed them to understand the dependencies and symbols, here's my findings:
> 
> ```
> $ wget https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
> $ tar x libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
> $ tar xJvf data.tar.xz
> $ nm -D ./usr/lib/libcephsqlite.so | grep cephsqlite > libcephsqlite.symbols
> $ nm -D ./usr/lib/libcephsqlite.so | grep SimpleRADOSStriper >> libcephsqlite.symbols
> $ cut -d' ' -f2,3 libcephsqlite.symbols | sort
> T cephsqlite_setcct
> T sqlite3_cephsqlite_init
> T _ZN18SimpleRADOSStriper12recover_lockEv
> T _ZN18SimpleRADOSStriper12set_metadataEmb
> T _ZN18SimpleRADOSStriper12shrink_allocEm
> T _ZN18SimpleRADOSStriper13config_loggerEPN4ceph6common11CephContextESt17basic_string_viewIcSt11char_traitsIcEEPSt10shared_ptrINS1_12PerfCountersEE
> T _ZN18SimpleRADOSStriper13print_lockersERSo
> T _ZN18SimpleRADOSStriper13wait_for_aiosEb
> T _ZN18SimpleRADOSStriper16lock_keeper_mainEv
> T _ZN18SimpleRADOSStriper18maybe_shrink_allocEv
> T _ZN18SimpleRADOSStriper4lockEm
> T _ZN18SimpleRADOSStriper4openEv
> T _ZN18SimpleRADOSStriper4readEPvmm
> T _ZN18SimpleRADOSStriper4statEPm
> T _ZN18SimpleRADOSStriper5flushEv
> T _ZN18SimpleRADOSStriper5writeEPKvmm
> T _ZN18SimpleRADOSStriper6createEv
> T _ZN18SimpleRADOSStriper6removeEv
> T _ZN18SimpleRADOSStriper6str2blESt17basic_string_viewIcSt11char_traitsIcEE
> T _ZN18SimpleRADOSStriper6unlockEv
> T _ZN18SimpleRADOSStriper7uint2blEm
> T _ZN18SimpleRADOSStriper8truncateEm
> T _ZN18SimpleRADOSStriperD1Ev
> T _ZN18SimpleRADOSStriperD2Ev
> T _ZNK18SimpleRADOSStriper15get_next_extentEmm
> u _ZGVN18SimpleRADOSStriper7biglockB5cxx11E
> u _ZGVN18SimpleRADOSStriper8lockdescB5cxx11E
> u _ZN18SimpleRADOSStriper10XATTR_EXCLE
> u _ZN18SimpleRADOSStriper10XATTR_SIZEE
> u _ZN18SimpleRADOSStriper13XATTR_VERSIONE
> u _ZN18SimpleRADOSStriper15XATTR_ALLOCATEDE
> u _ZN18SimpleRADOSStriper24XATTR_LAYOUT_OBJECT_SIZEE
> u _ZN18SimpleRADOSStriper24XATTR_LAYOUT_STRIPE_UNITE
> u _ZN18SimpleRADOSStriper25XATTR_LAYOUT_STRIPE_COUNTE
> u _ZN18SimpleRADOSStriper7biglockB5cxx11E
> u _ZN18SimpleRADOSStriper8lockdescB5cxx11E
> V _ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEEE
> V _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEEE
> V _ZTVNSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEEE
> W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJM18SimpleRADOSStriperFvvEPS3_EEEEE6_M_runEv
> ```
> 
> so all the "T" (i.e., text section) symbols are also listed in https://github.com/ceph/ceph/blob/main/debian/libsqlite3-mod-ceph.symbols, also expected.
> 
> ```
> $ wget https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/ceph-mgr_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
> $ ar x ceph-mgr_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
> $ tar xJvf control.tar.xz
> $ $ grep Depends control
> Depends: ceph-base (= 17.0.0-13884-g9a8f20f4-1focal), ceph-mgr-modules-core (= 17.0.0-13884-g9a8f20f4-1focal), python3-ceph-argparse, python3-cephfs, python3-distutils, python3-openssl, python3-yaml, libc6 (>= 2.28), libgcc-s1 (>= 3.0), libgoogle-perftools4, libpython3.8 (>= 3.8.2), librados2, libsqlite3-0 (>= 3.5.9), libsqlite3-mod-ceph (>= 15.2.0-1), libstdc++6 (>= 9)
> ```
> 
> so, as expected, the ceph-mgr depends on `libsqlite3-mod-ceph (>= 15.2.0-1)` . and the symbols can be provided by `libsqlite3-mod-ceph (>= 15.2.0-1)`
> 
> i am quoting https://tracker.ceph.com/issues/56274#note-5 ,
> 
> > symbol locations will differ, causing the segtfault
> 
> i don't quite follow this. yes, the symbols can be relocated in the text section by the linker across different versions when building the shared object. but i believe the linker should also be able to resolve to the right symbols when loading ceph-mgr executable image, this is how the linker and loader work, i believe.
> 
> i am quoting the backtrace at `/a/mchangir-2022-07-26_10:40:37-upgrade-wip-mchangir-test-pacific-to-quincy-upgrade-with-snap_schedule-test-pacific-distro-default-smithi/6947433/remote/*/log/ceph-mgr.x.log.gz` also:
> 
> ```
>  ceph version 17.0.0-13700-g44739573 (447395734d5de358016cdb44830f44fe6ad6a124) quincy (dev)
>  1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7ffff6a72420]
>  2: pthread_mutex_lock()
>  3: (ceph::logging::Log::submit_entry(ceph::logging::Entry&&)+0x45) [0x7ffff714c075]
>  4: cephsqlite_setcct()
>  5: (Mgr::init()+0x19c5) [0x5555557cd7e5]
>  6: /usr/bin/ceph-mgr(+0x27a711) [0x5555557ce711]
>  7: (Context::complete(int)+0xd) [0x55555571941d]
>  8: (Finisher::finisher_thread_entry()+0x19d) [0x7ffff6df110d]
>  9: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7ffff6a66609]
>  10: clone()
>  NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
> ```
> 
> so probably it is because `cephsqlite_setcct` is not backward compatible? and it is not versioned yet. so `dh_makeshlibs` and `dpkg-gensymbols` think that the older libsqlite3-mod-ceph can also satisfy the requirement.
> 
> i am not against the change. just wanted to explain my guess on the root cause. but a bigger question is, why `cephsqlite_setcct` fails ? it is supposed to be a public API and exposed by `libcephsqlite`.



> i downloaded the [deb packages](https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/) from a recent build. and uncompressed them to understand the dependencies and symbols, here's my findings:
> 
> ```
> $ wget https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
> $ tar x libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
> $ tar xJvf data.tar.xz
> $ nm -D ./usr/lib/libcephsqlite.so | grep cephsqlite > libcephsqlite.symbols
> $ nm -D ./usr/lib/libcephsqlite.so | grep SimpleRADOSStriper >> libcephsqlite.symbols
> $ cut -d' ' -f2,3 libcephsqlite.symbols | sort
> T cephsqlite_setcct
> T sqlite3_cephsqlite_init
> T _ZN18SimpleRADOSStriper12recover_lockEv
> T _ZN18SimpleRADOSStriper12set_metadataEmb
> T _ZN18SimpleRADOSStriper12shrink_allocEm
> T _ZN18SimpleRADOSStriper13config_loggerEPN4ceph6common11CephContextESt17basic_string_viewIcSt11char_traitsIcEEPSt10shared_ptrINS1_12PerfCountersEE
> T _ZN18SimpleRADOSStriper13print_lockersERSo
> T _ZN18SimpleRADOSStriper13wait_for_aiosEb
> T _ZN18SimpleRADOSStriper16lock_keeper_mainEv
> T _ZN18SimpleRADOSStriper18maybe_shrink_allocEv
> T _ZN18SimpleRADOSStriper4lockEm
> T _ZN18SimpleRADOSStriper4openEv
> T _ZN18SimpleRADOSStriper4readEPvmm
> T _ZN18SimpleRADOSStriper4statEPm
> T _ZN18SimpleRADOSStriper5flushEv
> T _ZN18SimpleRADOSStriper5writeEPKvmm
> T _ZN18SimpleRADOSStriper6createEv
> T _ZN18SimpleRADOSStriper6removeEv
> T _ZN18SimpleRADOSStriper6str2blESt17basic_string_viewIcSt11char_traitsIcEE
> T _ZN18SimpleRADOSStriper6unlockEv
> T _ZN18SimpleRADOSStriper7uint2blEm
> T _ZN18SimpleRADOSStriper8truncateEm
> T _ZN18SimpleRADOSStriperD1Ev
> T _ZN18SimpleRADOSStriperD2Ev
> T _ZNK18SimpleRADOSStriper15get_next_extentEmm
> u _ZGVN18SimpleRADOSStriper7biglockB5cxx11E
> u _ZGVN18SimpleRADOSStriper8lockdescB5cxx11E
> u _ZN18SimpleRADOSStriper10XATTR_EXCLE
> u _ZN18SimpleRADOSStriper10XATTR_SIZEE
> u _ZN18SimpleRADOSStriper13XATTR_VERSIONE
> u _ZN18SimpleRADOSStriper15XATTR_ALLOCATEDE
> u _ZN18SimpleRADOSStriper24XATTR_LAYOUT_OBJECT_SIZEE
> u _ZN18SimpleRADOSStriper24XATTR_LAYOUT_STRIPE_UNITE
> u _ZN18SimpleRADOSStriper25XATTR_LAYOUT_STRIPE_COUNTE
> u _ZN18SimpleRADOSStriper7biglockB5cxx11E
> [...]

2022-07-31 04:00 UTC, mchangir commented
is the code in pacific and mainline/Quincy built with different stack frame generation options ?

2022-07-31 08:57 UTC, tchaikov commented
> > i don't quite follow this. yes, the symbols can be relocated in the text section by the linker across different versions when building the shared object. but i believe the linker should also be able to resolve to the right symbols when loading ceph-mgr executable image, this is how the linker and loader work, i believe.
> 
> My guess is that a symbol is not available from the common libraries. I checked and the `Log::submit_entry` is the same signature. There must be something else. (`cephsqlite_setcct` crashes on the first line trying to log a message.)
> 

i agree that it is not caused by "missing symbols". it should have something to do with `libceph-common.so.2`. it is the loophole of `libcephsqlite.so`. i will expand on this at the end of this comment.

> > so probably it is because `cephsqlite_setcct` is not backward compatible? and it is not versioned yet. so `dh_makeshlibs` and `dpkg-gensymbols` think that the older libsqlite3-mod-ceph can also satisfy the requirement.
> 
> I can't see a good reason to let `dh_makeshlibs` keep back an older version of a ceph library during a ceph upgrade.

at first glance, yeah.

but based on my findings of two "expected", `dh_makeshlibs` does its job well.  and i'd prefer finding out the root cause before advancing.

> 
> > i am not against the change. just wanted to explain my guess on the root cause. but a bigger question is, why `cephsqlite_setcct` fails ? it is supposed to be a public API and exposed by `libcephsqlite`.
> 
> From the stacktrace, the logical explanation is that the mutex passed to `pthread_mutex_lock` is invalid due to incompatible offsets. I can't find a likely cause in changes to `CephContext` or anything else.

yeah, should be. after compiling pacific and main branches, and looking into the output of `ldd lib/libcephsqlite.so`, i confirmed this:
```console
$ ldd lib/libcephsqlite.so
        linux-vdso.so.1 (0x00007ffdf937a000)
        librados.so.2 => /home/kefu/dev/ceph/build/lib/librados.so.2 (0x00007f2ac9f0d000)
>>      libceph-common.so.2 => /home/kefu/dev/ceph/build/lib/libceph-common.so.2 (0x00007f2ac11ff000)
        libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007f2ac10bc000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f2ac10a8000)
        libfmt.so.8 => /lib64/libfmt.so.8 (0x00007f2ac1087000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f2ac104e000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f2ac0c22000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00007f2ac0bf5000)
        libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00007f2ac0bd3000)
        librdmacm.so.1 => /lib64/librdmacm.so.1 (0x00007f2ac0bb6000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f2ac0b9c000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f2ac0973000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2ac0958000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2ac074e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2aca117000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2ac0673000)
        libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00007f2ac05ed000)
        libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00007f2ac05c7000)
```
so `libcephsqlite.so` references symbols exposed by `libceph-common.so.2`. i just checked `libsqlite3-mod-ceph` deb package's dependencies using
```console
$ wget https://4.chacra.ceph.com/r/ceph/main/9a8f20f42e0fd5753811fefea644d059befb458d/ubuntu/focal/flavors/default/pool/main/c/ceph/libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
$ ar x  libsqlite3-mod-ceph_17.0.0-13884-g9a8f20f4-1focal_amd64.deb
$ tar xJvf control.tar.xz
$ grep Depends control
Depends: libc6 (>= 2.17), libgcc-s1 (>= 3.0), librados2, libstdc++6 (>= 6)
```
this echos with what we have in the CMake script, see https://github.com/ceph/ceph/blob/56ac13ebd5ba2596c41ae15e224737ded8b510de/src/CMakeLists.txt#L808 .

but the problem is, `libsqlite3-mod-ceph` depends on `librados2` without specifying `librados2`'s version. but it is `librados2` which provides `libceph-common.so.*`, see https://github.com/ceph/ceph/blob/56ac13ebd5ba2596c41ae15e224737ded8b510de/debian/librados2.install#L1 .

so, unless we properly version `libceph-common.so.*`, and keep its backward compatibility . but we probably will never do so, as `ceph-common` is an internal library. it would be a huge pain if we were going to version it or try to keep it backward compatible.

in other words, we should always have an explicit versioned dependency from `libsqlite3-mod-ceph` to `librados2`. hence i think following patch is a better fix:
```diff
diff --git a/debian/control b/debian/control
index ea3a0161d30..11c76e5e658 100644
--- a/debian/control
+++ b/debian/control
@@ -734,7 +734,8 @@ Description: RADOS distributed object store client C++ library (development file
 Package: libsqlite3-mod-ceph
 Architecture: any
 Section: libs
-Depends: ${misc:Depends},
+Depends: librados2 (= ${binary:Version}),
+         ${misc:Depends},
          ${shlibs:Depends},
 Description: SQLite3 VFS for Ceph
  A SQLite3 VFS for storing and manipulating databases stored on Ceph's RADOS
```

2022-07-31 08:58 UTC, tchaikov requested changes
see my analysis and proposal.

2022-07-31 09:17 UTC, tchaikov commented
> is the code in pacific and mainline/Quincy built with different stack frame generation options ?

not likely, we are using libcephsqlite in the normal way how other applications are using shared libraries. all of us are following the amd64 ABI call conventions.

2022-07-31 13:21 UTC, batrick commented
> in other words, we should always have an explicit versioned dependency from libsqlite3-mod-ceph to librados2. hence i think following patch is a better fix:

I'm okay with this change but I'm a little confused: why would upgrading `ceph-mgr` also force an upgrade of `libsqlite3-mod-ceph`? Is it because other upgraded packages depend on `librados2 (= ${binary:Version})` which forces an upgrade of `librados2` thereby indirectly forcing an upgrade of `libsqlite3-mod-ceph`?

Also, there are other instances in `debian/control` of this, like `python3-rados`. Shall they be fixed too?

2022-07-31 13:44 UTC, tchaikov commented
> I'm okay with this change but I'm a little confused: why would upgrading `ceph-mgr` also force an upgrade of `libsqlite3-mod-ceph`? 

sorry, i missed an important dependency: ceph-mgr depends on ceph-common, which is not versioned. so we have to add another dependency from `ceph-mgr` to `librados2 (= ${binary:Version})`.

> Also, there are other instances in `debian/control` of this, like `python3-rados`. Shall they be fixed too?

i don't think so, as `python3-rados` only uses the public interfaces of librados. so it (and its friends) should be safe.

2022-08-01 13:04 UTC, batrick commented
> > I'm okay with this change but I'm a little confused: why would upgrading `ceph-mgr` also force an upgrade of `libsqlite3-mod-ceph`?
> 
> sorry, i missed an important dependency: ceph-mgr depends on libceph-common, which is not versioned. so we have to add another dependency from `ceph-mgr` to `librados2 (= ${binary:Version})`.
> 
> > Also, there are other instances in `debian/control` of this, like `python3-rados`. Shall they be fixed too?
> 
> i don't think so, as `python3-rados` only uses the public interfaces of librados. so it (and its friends) should be safe.

ACK, PTAL.

2022-08-01 14:07 UTC, tchaikov approved these changes

2022-08-01 14:26 UTC, batrick commented
@mchangir please give this patch another try.

2022-08-02 07:48 UTC, mchangir commented
> @mchangir please give this patch another try.

HEAD of the ceph-ci branch with the cherry-picked patch:
<pre>
commit 4b6ff40a282c57633f7c6b829ef227a4ba1a06d0 (HEAD -> wip-mchangir-mgr-ensure-background_init-completion-before-starting-python-modules, origin/wip-mchangir-mgr-ensure-background_init-completion-before-starting-python-modules)
Author: Patrick Donnelly <pdonnell@redhat.com>
Date:   Tue Jul 26 17:23:09 2022 -0400

    debian: add librados2 versioned dep for ceph-mgr/libsqlite3-mod-ceph
    
    Without this, upgrades will keep older versions of the libcephsqlite3
    module.
    
    Fixes: https://tracker.ceph.com/issues/56274
    Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>
</pre>

and the result on [ubuntu](https://pulpito.ceph.com/mchangir-2022-08-02_06:34:40-upgrade-wip-mchangir-test-pacific-to-quincy-upgrade-with-snap_schedule-test-pacific-distro-default-smithi/) ...

<pre>
2022-08-02T06:55:39.230 INFO:tasks.ceph.mgr.x.smithi135.stderr:*** Caught signal (Segmentation fault) **
2022-08-02T06:55:39.231 INFO:tasks.ceph.mgr.x.smithi135.stderr: in thread 7f9bb9163700 thread_name:mgr-fin
2022-08-02T06:55:39.231 INFO:tasks.ceph.mgr.x.smithi135.stderr: ceph version 17.0.0-13908-g4b6ff40a (4b6ff40a282c57633f7c6b829ef227a4ba1a06d0) quincy (dev)
2022-08-02T06:55:39.232 INFO:tasks.ceph.mgr.x.smithi135.stderr: 1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f9bd1172420]
2022-08-02T06:55:39.232 INFO:tasks.ceph.mgr.x.smithi135.stderr: 2: pthread_mutex_lock()
2022-08-02T06:55:39.232 INFO:tasks.ceph.mgr.x.smithi135.stderr: 3: (ceph::logging::Log::submit_entry(ceph::logging::Entry&&)+0x42) [0x7f9bd185ec92]
2022-08-02T06:55:39.232 INFO:tasks.ceph.mgr.x.smithi135.stderr: 4: cephsqlite_setcct()
2022-08-02T06:55:39.233 INFO:tasks.ceph.mgr.x.smithi135.stderr: 5: (Mgr::init()+0x13dc) [0x56464ee8eb9c]
2022-08-02T06:55:39.233 INFO:tasks.ceph.mgr.x.smithi135.stderr: 6: ceph-mgr(+0x242911) [0x56464ee8f911]
2022-08-02T06:55:39.233 INFO:tasks.ceph.mgr.x.smithi135.stderr: 7: (Context::complete(int)+0xd) [0x56464edf390d]
2022-08-02T06:55:39.233 INFO:tasks.ceph.mgr.x.smithi135.stderr: 8: (Finisher::finisher_thread_entry()+0x18d) [0x7f9bd153ebcd]
2022-08-02T06:55:39.233 INFO:tasks.ceph.mgr.x.smithi135.stderr: 9: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f9bd1166609]
2022-08-02T06:55:39.234 INFO:tasks.ceph.mgr.x.smithi135.stderr: 10: clone()
</pre>

For ubuntu, please note the branch HEAD commit ID and the commit ID in crash logs mentioned above for sanity verification.

tests pass on [centos](https://pulpito.ceph.com/mchangir-2022-08-02_06:35:58-upgrade-wip-mchangir-test-pacific-to-quincy-upgrade-with-snap_schedule-test-pacific-distro-default-smithi/) with the `PG_AVAILABILITY` log
<pre>
"2022-08-02T06:54:26.108858+0000 mon.a (mon.0) 178 : cluster [WRN] Health check failed: Reduced data availability: 2 pgs peering (PG_AVAILABILITY)" in cluster log
</pre>

2022-08-02 13:04 UTC, batrick commented
Damn, well I've restored the libsqlite3-mod-ceph versioned dependency. Should work now, again.

2022-08-02 20:07 UTC, batrick commented
jenkins test windows

2022-08-04 17:28 UTC, batrick commented
@ljflores can you confirm teh latest version of this fixes the issue for your tests too?

2022-08-09 16:04 UTC, tchaikov commented
- https://pulpito.ceph.com/kchai-2022-08-07_05:39:26-rados-wip-kefu-testing-2022-08-07-1123-distro-default-smithi/
- https://pulpito.ceph.com/kchai-2022-08-07_07:44:14-rados-wip-kefu-testing-2022-08-07-1123-distro-default-smithi/

the `sudo yum -y install ceph-radosgw` failures are tracked by https://tracker.ceph.com/issues/57051

2022-08-11 17:33 UTC, batrick commented
@tchaikov are you okay with adding the libsqlite3-mod-ceph versioned dependency back in?

2022-08-11 18:06 UTC, ljflores commented
> @ljflores can you confirm teh latest version of this fixes the issue for your tests too?

Sure @batrick. I ran into this bug on quincy p2p upgrade tests though (https://github.com/ceph/ceph/pull/46896), so I'll have to test this on a Quincy backport.

2022-08-16 20:41 UTC, batrick commented
before (with small qa adjustment to run `fs:upgrade:nofs` on ubuntu):

https://pulpito.ceph.com/pdonnell-2022-08-16_12:50:28-fs:upgrade:nofs-main-distro-default-smithi/

after:

https://pulpito.ceph.com/pdonnell-2022-08-16_20:13:59-fs:upgrade:nofs-wip-pdonnell-testing-20220816.143528-distro-default-smithi/

this is ready to merge imo

2022-08-18 16:25 UTC, jdurgin approved these changes

2022-08-18 16:29 UTC, merged