Ceph-mixin: Fix CephNodeNetworkPacketDrops alert
ceph/ceph pull request #47707
Opened 2022-08-19 16:13 UTC by bosc0

Currently the `CephNodeNetworkPacketDrops` and `CephNodeNetworkPacketErrors` alert queries count the amount of packet drops/errors per minute instead of per second as mentioned in the description. This commit fixes that and makes the threshold values customizable with slightly higher defaults

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-08-22 07:34 UTC, MrFreezeex requested changes
Could you regenerate the yaml file with the alerts?

2022-08-23 07:10 UTC, MrFreezeex approved these changes

2022-08-23 07:44 UTC, MrFreezeex commented on monitoring/ceph-mixin/prometheus_alerts.libsonnet
> -          expr: '(  increase(node_network_receive_drop_total{device!="lo"}[1m]) +  increase(node_network_transmit_drop_total{device!="lo"}[1m])) / (  increase(node_network_receive_packets_total{devic
Actually could we have multiline jsonnet for these networks alerts?

2022-08-23 17:46 UTC, MrFreezeex commented
jenkins test make check

2022-08-24 12:03 UTC, epuertat approved these changes
LGTM! Thanks @bosc0 !

@mmgaggle could you please review this and check if this would be consistent with your fix in https://github.com/ceph/ceph/pull/46842?

2022-08-30 06:53 UTC, aaSharma14 approved these changes

2022-08-30 06:54 UTC, aaSharma14 commented
jenkins test dashboard cephadm

2022-08-30 06:54 UTC, aaSharma14 commented
jenkins test dashboard

2022-08-30 06:54 UTC, aaSharma14 commented
jenkins test windows

2022-08-30 10:49 UTC, MrFreezeex commented
I'm merging this as I want to be able to backport the recent changes of ceph-mixin up to pacific (and there are a couple not tracked in the trackers oups). I'm leaving CERN rather soon and I probably won't have access to a dev environment for a few weeks to do that but if @mmgaggle or someone else has a follow up suggestion/PR would be happy to help.

2022-08-30 10:49 UTC, merged