doc: Update release process doc to accurately reflect current process
ceph/ceph pull request #47736
Opened 2022-08-22 20:13 UTC by djgalloway

Signed-off-by: David Galloway <dgallowa@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-08-24 14:07 UTC, zdover23 requested changes

2022-08-24 14:07 UTC, zdover23 commented on doc/dev/release-process.rst
> +Prequisites
s/Prequisites/Prerequisites/

2022-08-24 15:11 UTC, anthonyeleven requested changes

2022-08-24 15:11 UTC, anthonyeleven commented on doc/dev/release-process.rst
> +The signing machine is a virtual machine in the `Sepia lab<https://wiki.sepia.ceph.com/doku.php?id=start>`_.  SSH access is limited to the usual Infrastructure Admins along with a few other component
Suggest s/virtual machine/VM/ to be less stilted.

2022-08-24 18:07 UTC, djgalloway commented on doc/dev/release-process.rst
> +The ``ubuntu`` user on the machine has a few `build scripts` <https://github.com/ceph/ceph-build/tree/main/scripts>`_ to ease the pulling, pushing, and signing of packages.
```suggestion
The ``ubuntu`` user on the machine has a few `build scripts <https://github.com/ceph/ceph-build/tree/main/scripts>`_ to ease the pulling, pushing, and signing of packages.
```

2022-08-24 18:08 UTC, djgalloway commented on doc/dev/release-process.rst
> +3. Build Lead starts [Jenkins multijob](https://jenkins.ceph.com/view/all/job/ceph) which triggers all builds.
```suggestion
3. Build Lead starts `Jenkins multijob <https://jenkins.ceph.com/view/all/job/ceph>`_ which triggers all builds.
```

2022-08-24 19:06 UTC, zdover23 approved these changes

2022-08-24 19:07 UTC, djgalloway commented on doc/dev/release-process.rst
> +For new major (alphabetical) releases, RPM repos need a `ceph-release` RPM created.  The chacra repos are configured to include this RPM but it must be built separately. You must make sure that chacr
Correct!

2022-08-24 19:16 UTC, zdover23 commented on doc/dev/release-process.rst
> +For new major (alphabetical) releases, RPM repos need a `ceph-release` RPM created.  The chacra repos are configured to include this RPM but it must be built separately. You must make sure that chacr
Alright. I'm going to tidy up the syntax here (I expect this to take about another half hour). After that, I think that we can merge this PR.

2022-08-24 19:42 UTC, zdover23 commented on doc/dev/release-process.rst
> +For new major (alphabetical) releases, RPM repos need a `ceph-release` RPM created.  The chacra repos are configured to include this RPM but it must be built separately. You must make sure that chacr
I think that the relationship between 1) chacra and 2) the RPM that must be built before chacra is run should be made clearer. 

We could improve this by merely including a sentence explaining what chacra is, and what it does.

2022-08-24 19:43 UTC, zdover23 commented on doc/dev/release-process.rst
> +For new major (alphabetical) releases, RPM repos need a `ceph-release` RPM created.  The chacra repos are configured to include this RPM but it must be built separately. You must make sure that chacr
@djgalloway ^^^ (see above)

2022-08-24 21:13 UTC, anthonyeleven commented on doc/dev/release-process.rst
> +The signing machine is a virtual machine in the `Sepia lab<https://wiki.sepia.ceph.com/doku.php?id=start>`_.  SSH access is limited to the usual Infrastructure Admins along with a few other component
If someone doesn't know what a triode is I don't want them using my software in the first place, but ok.  Maybe instead replace "signing machine" with "signing host"?

2022-08-24 21:13 UTC, anthonyeleven approved these changes

2022-08-26 12:01 UTC, zdover23 commented
jenkins test docs

2022-08-26 14:46 UTC, djgalloway commented
DNM yet.

To-do:

1. Make step 1 pushing to `quincy-release`
2. I'd like to make a table with the distro map (e.g., | quincy | `centos8 centos9 focal bullseye`)

2022-08-26 19:08 UTC, zdover23 commented
> DNM yet.
> 
> To-do:
> 
>     1. Make step 1 pushing to `quincy-release`
> 
>     2. I'd like to make a table with the distro map (e.g., | quincy | `centos8 centos9 focal bullseye`)
> 
>     3. Edit `sync-pull` command so release name is in < >
> 
>     4. Add note about where packages go under `3. Signing and Publishing the Build`
> 
>     5. Add merfi and sign-rpms output
> 
>     6. Mention the ceph.git release notes pull request under `5. Announce the Release`

@djgalloway Would you like me to take care of these items and push this back to you for review?

Also, there's some kind of error that I've never seen before that is making the docs build check and the ceph-pr-docs check fail. Do you have any insight into that?

2022-08-26 20:18 UTC, djgalloway commented
> @djgalloway Would you like me to take care of these items and push this back to you for review?

I appreciate the offer it's all knowledge in my head that needs to get out of my head :rofl:.

> Also, there's some kind of error that I've never seen before that is making the "docs build check" and the "ceph-pr-docs check" fail. Do you have any insight into that?

I haven't looked yet but I'll fix it.

2022-08-27 01:42 UTC, djgalloway commented
@zdover23 I think I'm done.  Please take a look at and let me know if

1. You think you could follow these steps and create a Ceph release (if you had proper access to all the systems)
2. Formatting, syntax, grammar, etc. is up to your standards

https://ceph--47736.org.readthedocs.build/en/47736/dev/release-process/

2022-08-27 20:26 UTC, zdover23 commented
> 

1. I think so. I think that I could use this procedure to create a Ceph release if I had the necessary permissions.
2. I've made an alteration to the formatting of one of the procedures. There are minor usage and syntactical alterations that I might make in the future, but I don't see anything here that is a showstopper--nothing here should stop this merge. This is excellent internal procedural documentation, and if international conventions open again I might use it as the example of how to create such internal documentation.

2022-08-27 20:27 UTC, zdover23 commented
> @zdover23 I think I'm done. Please take a look at and let me know if
> 
>     1. You think you could follow these steps and create a Ceph release (if you had proper access to all the systems)
> 
>     2. Formatting, syntax, grammar, etc. is up to your standards
> 
> 
> https://ceph--47736.org.readthedocs.build/en/47736/dev/release-process/

1. I think so. I think that I could use this procedure to create a Ceph release if I had the necessary permissions.
2. I've made an alteration to the formatting of one of the procedures. There are minor usage and syntactical alterations that I might make in the future, but I don't see anything here that is a showstopper--nothing here should stop this merge. This is excellent internal procedural documentation, and if international conventions open again I might use it as the example of how to create such internal documentation.

2022-08-27 21:13 UTC, zdover23 commented
https://github.com/ceph/ceph/pull/47837 - Quincy backport
https://github.com/ceph/ceph/pull/47838 - Pacific backport

2022-08-27 21:13 UTC, merged