cephadm/mgr: adding logic to handle -no-overwrite for tuned profiles
ceph/ceph pull request #47815
Opened 2022-08-26 10:33 UTC by rkachach

Fixes: https://tracker.ceph.com/issues/57032

Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-08-29 08:14 UTC, rkachach commented
jenkins retest this please

2022-08-29 20:09 UTC, adk3798 approved these changes

2022-08-29 20:09 UTC, adk3798 commented on src/pybind/mgr/cephadm/module.py
> +                outs.append(f"Tuned profile '{spec.profile_name}' already exists (--no-overwrite is enabled)")
```suggestion
                outs.append(f"Tuned profile '{spec.profile_name}' already exists (--no-overwrite flag was passed")
```
NIT, I think it's a bit clearer

2022-08-29 20:10 UTC, adk3798 commented
jenkins test make check

2022-08-29 20:10 UTC, adk3798 commented
jenkins test api

2022-08-29 20:10 UTC, adk3798 commented
jenkins test dashboard cephadm

2022-08-29 20:12 UTC, adk3798 commented
we probably ought to document this functionality now that it's there, right @rkachach? It could be useful to people as the flag sort of make the command idempotent

2022-08-30 11:49 UTC, rkachach commented
> we probably ought to document this functionality now that it's there, right @rkachach? It could be useful to people as the flag sort of make the command idempotent

Yep, it's a good idea to reflect it in the docs as well :+1:

2022-08-30 13:42 UTC, anthonyeleven approved these changes

2022-08-30 13:42 UTC, anthonyeleven commented on doc/cephadm/host-management.rst
> +  Applying tuned profiles is idempotent when ``--no-overwrite`` option is passed.
When the

2022-08-30 13:42 UTC, anthonyeleven requested changes
Change requested in comment

2022-08-30 14:25 UTC, rkachach commented on doc/cephadm/host-management.rst
> +  Applying tuned profiles is idempotent when ``--no-overwrite`` option is passed.
fixed

2022-08-30 14:54 UTC, anthonyeleven approved these changes

2022-08-31 09:11 UTC, rkachach commented
jenkins test make check

2022-08-31 09:12 UTC, rkachach commented
jenkins retest this please

2022-09-02 00:22 UTC, adk3798 approved these changes

2022-09-03 15:32 UTC, adk3798 commented
https://pulpito.ceph.com/adking-2022-09-02_11:54:06-orch:cephadm-wip-adk-testing-2022-09-01-2029-distro-default-smithi/

Failures tracked by

- https://tracker.ceph.com/issues/57371
- https://tracker.ceph.com/issues/55986
- https://tracker.ceph.com/issues/57287
- https://tracker.ceph.com/issues/57374

All failures are also present on main branch and not caused by PRs in the run

2022-09-03 15:58 UTC, merged