pacific: mgr/stats: change in structure of perf_stats o/p
ceph/ceph pull request #47821
Opened 2022-08-26 17:30 UTC by neesingh-rh

backport tracker: https://tracker.ceph.com/issues/57279

---

backport of https://github.com/ceph/ceph/pull/46068
parent tracker: https://tracker.ceph.com/issues/56162

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2022-08-26 17:38 UTC, anthonyeleven approved these changes
Docs Lgtm

2022-08-29 09:05 UTC, joscollin requested changes

2022-08-29 09:30 UTC, neesingh-rh commented on qa/tasks/cephfs/test_mds_metrics.py
> +                raise RuntimeError("valid_metrics of fs2 not found!")
Fixed!! I guess it came during resolving conflict.My bad.

2022-08-29 10:05 UTC, joscollin commented on qa/tasks/cephfs/test_mds_metrics.py
> +                raise RuntimeError("valid_metrics of fs2 not found!")
You should add a `Conflicts:` section.  

Please see:
https://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits_old
https://github.com/ceph/ceph/blob/main/SubmittingPatches-backports.rst#cherry-picking-rules

I guess the doc commit also had conflicts?

2022-08-29 10:24 UTC, neesingh-rh commented on qa/tasks/cephfs/test_mds_metrics.py
> +                raise RuntimeError("valid_metrics of fs2 not found!")
Updated the commits!

2022-08-29 11:13 UTC, joscollin commented
I'm closing this one. A new backport is created which doesn't have commit edits: https://github.com/ceph/ceph/pull/47851

2022-08-29 11:13 UTC, closed without merging