mgr/dashboard: Add details to the modal which displays the `safe-to-d…
ceph/ceph pull request #47849
Opened 2022-08-29 10:42 UTC by torchiaf

…estroy` result

- Add warnings type information in the case of the OSDs are not safe to destroy
- Add info type information in the case of the OSDs are safe to destroy

Fixes: https://tracker.ceph.com/issues/37327
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-08-31 14:38 UTC, torchiaf commented
Below, a demo showing all the possible warnings messages for different OSDs:

![image](https://user-images.githubusercontent.com/26394656/187705819-c98aba8c-0bc2-49ca-839f-4d9b95302561.png)

2022-08-31 14:49 UTC, torchiaf commented
Below, the info message in case of the destroy action is safe:

![image](https://user-images.githubusercontent.com/26394656/187708622-166f025f-7ae9-4ace-af98-0f664002a95a.png)

2022-08-31 14:49 UTC, torchiaf commented
The CI steps which are failed are not apparently related to the changes included in this PR.

2022-09-01 08:20 UTC, votdev requested changes

2022-09-01 08:20 UTC, votdev commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.scss
> +  margin-bottom: 1rem;
Wouldn't it be better to use `class="danger mb-X"` instead?

2022-09-01 08:20 UTC, votdev commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.scss
> +.warnings-list {
Wouldn't it be better to use `class="warnings-list mb-0 pl-X"` instead?

2022-09-08 14:11 UTC, votdev commented
jenkins retest this please

2022-09-08 14:14 UTC, votdev approved these changes

2022-09-12 13:29 UTC, votdev commented
jenkins retest this please

2022-09-16 08:12 UTC, nizamial09 approved these changes
Thank you! @torchiaf LGTM! just a minor ask.

2022-09-16 08:12 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.html
> +      <ng-container i18n>
[ng-container](https://angular.io/api/core/ng-container) is mostly used to hold the structural directives, but here a simple span will suffice, right?

2022-09-16 15:19 UTC, merged

2022-09-16 15:21 UTC, nizamial09 commented
Thanks @torchiaf ! I added the backport for pacific and quincy