pacific: osd/PeeringState: fix missed recheck_readable from laggy
ceph/ceph pull request #47899
Opened 2022-09-01 13:24 UTC by amathuria

backport tracker: https://tracker.ceph.com/issues/56734

---

backport of https://github.com/ceph/ceph/pull/44499
parent tracker: https://tracker.ceph.com/issues/53806

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2022-09-01 16:07 UTC, neha-ojha approved these changes

2022-09-06 06:13 UTC, amathuria commented
jenkins test make check

2022-09-06 10:54 UTC, amathuria commented
jenkins test api

2022-09-14 21:22 UTC, ljflores requested changes
We found that this PR has caused a regression. We are reverting the Quincy backport so we can release 17.2.4: https://github.com/ceph/ceph/pull/48104

See https://tracker.ceph.com/issues/57546 for more details.

2024-01-09 23:25 UTC, ljflores commented
jenkins retest this please

2024-01-09 23:32 UTC, ljflores commented
Let's close this, as there doesn't seem to be a fix to help with the teuthology regression.

2024-01-09 23:32 UTC, closed without merging