[DNM] iteration 1 of workload balancer
ceph/ceph pull request #48010
Opened 2022-09-08 03:15 UTC by ljflores

Signed-off-by: Laura Flores <lflores@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-09-26 23:47 UTC, ljflores commented
Note to self: this will be the change needed in the osdmaptool code to print the score when combined with Josh's PR:

```diff
[lflores@folio01 build]$ git diff
diff --git a/src/tools/osdmaptool.cc b/src/tools/osdmaptool.cc
index ccafde9b11a..0dcfb87bee0 100644
--- a/src/tools/osdmaptool.cc
+++ b/src/tools/osdmaptool.cc
@@ -472,10 +472,15 @@ int main(int argc, const char **argv)
     cout << " \n";
     cout << "---------- BEFORE ------------ \n";
     for (auto [osd, pgs] : acting_prims_by_osd) {
-      cout << " osd." << osd << " ~ number of prims: " << pgs.size() << " ~ score: " << "<insert score here>\n";
+      cout << " osd." << osd << " ~ number of prims: " << pgs.size() << "\n";
     }
     cout << " \n";
 
+    OSDMap::read_balance_info_t rb_info;
+    tmp_osd_map.calc_read_balance_score(g_ceph_context, pid, &rb_info);
+    cout << "read_balance_score of " << workload_pool << " : " << rb_info.acting_adj_score << "\n";
+    cout << " \n";
+
     OSDMap::Incremental pending_inc(osdmap.get_epoch()+1);
     int num_changes = osdmap.calc_workload_balancer(g_ceph_context, pid, &pending_inc, tmp_osd_map);
 
@@ -486,9 +491,13 @@ int main(int argc, const char **argv)
     cout << " \n";
     cout << "---------- AFTER ------------ \n";
     for (auto [osd, pgs] : acting_prims_by_osd_2) {
-      cout << " osd." << osd << " ~ number of prims: " << pgs.size() << " ~ score: " << "<insert score here>\n";
+      cout << " osd." << osd << " ~ number of prims: " << pgs.size() << "\n";
     }
     cout << " \n";
+    tmp_osd_map.calc_read_balance_score(g_ceph_context, pid, &rb_info);
+    cout << "read_balance_score of " << workload_pool << " : " << rb_info.acting_adj_score << "\n";
+    cout << " \n";
+
     cout << "num changes: " << num_changes << "\n";
     cout << " \n";

```

2022-10-04 16:16 UTC, ljflores commented
![](https://github.trello.services/images/mini-trello-icon.png) [balancer: balance reads](https://trello.com/c/is7l6BIb/812-balancer-balance-reads)

2022-10-05 21:14 UTC, ljflores commented
Commits that need to be added after #47555 is merged:

https://github.com/ceph/ceph/commit/05d811670e10ccc916f52305359ec6565694a5d6
https://github.com/ceph/ceph/commit/645e5628c433e8017c9015e91e7e0ecf07e38f3b

2023-02-02 00:49 UTC, ljflores commented
I cleaned up the commits. This PR depends on https://github.com/ceph/ceph/pull/47555 to be merged first, which is in testing right now.

After #47555 is merged, I will drop https://github.com/ceph/ceph/pull/48010/commits/3c7ebc2bc485eced28d95f9c7c38b6fc7c458102. It is there for now as a placeholder.

2023-02-20 09:02 UTC, JoshSalomon requested changes

2023-02-21 00:37 UTC, ljflores commented
Will squash commits after I'm certain make check is passing

2023-02-21 10:06 UTC, JoshSalomon approved these changes

2023-02-21 10:06 UTC, JoshSalomon commented on src/tools/osdmaptool.cc
> +    if (vstart)
You did not implement this one... The idea was to have only one place in which you ask `if (vstart)`

2023-02-21 10:06 UTC, JoshSalomon commented on src/test/osd/TestOSDMap.cc
> +    osdmap.calc_read_balance_score(g_ceph_context, my_rep_pool, &rb_info);
I see that you still do not check for the return code of `calc_read_balance_score` in any place.

2023-02-22 07:51 UTC, JoshSalomon approved these changes

2023-02-22 20:49 UTC, ljflores commented
jenkins test make check

2023-02-27 23:55 UTC, ljflores commented
Rados suite review:
http://pulpito.front.sepia.ceph.com:80/yuriw-2023-02-22_21:31:50-rados-wip-yuri10-testing-2023-02-22-0848-distro-default-smithi
http://pulpito.front.sepia.ceph.com:80/yuriw-2023-02-23_16:14:52-rados-wip-yuri10-testing-2023-02-22-0848-distro-default-smithi

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57754
    2. https://tracker.ceph.com/issues/58475
    3. https://tracker.ceph.com/issues/58585
    4. https://tracker.ceph.com/issues/58797

Details:
    1. test_envlibrados_for_rocksdb.sh: update-alternatives: error: alternative path /usr/bin/gcc-11 doesn't exist - Ceph - RADOS
    2. test_dashboard_e2e.sh: Conflicting peer dependency: postcss@8.4.21 - Ceph - Mgr - Dashboard
    3. rook: failed to pull kubelet image - Ceph - Orchestrator
    4. scrub/osd-scrub-dump.sh: TEST_recover_unexpected fails from "ERROR: Unexpectedly low amount of scrub reservations seen during test"

Some failures in the runs were directly related to https://github.com/ceph/ceph/pull/49837.

2023-02-27 23:55 UTC, merged

2023-07-28 00:57 UTC, batrick commented
Linking to #52547 for posterity.