mgr/dashboard: pin python tox version to 3.8
ceph/ceph pull request #48032
Opened 2022-09-09 09:41 UTC by pereman2

With python 3.10 openapi-check fails, so we pin the version to 3.8 for now.

Signed-off-by: Pere Diaz Bou <pdiazbou@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-09-09 10:11 UTC, epuertat requested changes
LGTM! Thanks for the

2022-09-09 10:11 UTC, epuertat commented on src/pybind/mgr/dashboard/tox.ini
> +basepython=python3.8
Shouldn't this be fixed in line 158 instead?
```ini
[testenv:openapi-{check,fix}]
basepython = python3
```
Or even better, fixed for all text environments: by changing that in the `[testenv]` section, which [will be inherited by the remaining](https://tox.wiki/en/latest/config.html#tox-environments) `[testenv:xxx]` sections once the current override `basepython = python3` is removed from each one:
```ini
[testenv]
basepython = py3.8
```
```diff
[testenv:openapi-{check,fix}]
-basepython = python3
```

2022-09-09 10:30 UTC, epuertat approved these changes
Thanks for the quick fix @pereman2 !

2022-09-09 10:48 UTC, pereman2 commented
jenkins test dashboard cephadm

2022-09-09 10:48 UTC, pereman2 commented
jenkins test dashboard

2022-09-09 11:21 UTC, nizamial09 approved these changes

2022-09-09 11:22 UTC, nizamial09 requested changes
well looks like the openapi-checks failed again
```
openapi-check run-test: commands[1] | diff openapi.yaml /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/.tox/openapi-check/tmp/openapi.yaml
10483c10483
< - description: Get Ceph Users
---
> - description: Get Cluster Details
ERROR: InvocationError for command /usr/bin/diff openapi.yaml .tox/openapi-check/tmp/openapi.yaml (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   openapi-check: commands failed
```

2022-09-09 11:24 UTC, nizamial09 commented
@epuertat what kind of machine would be this? is this jammy?
```
Building remotely on [172.21.2.13+braggi13](https://jenkins.ceph.com/computer/172.21.2.13+braggi13) (buster small jammy gigantic windows bullseye trusty libvirt sepia x86_64 focal bionic braggi vagrant huge xenial amd64)
```

2022-09-09 14:27 UTC, epuertat commented
@nizamial09 @pereman2 it failed again 'cause it still run with `python3`:

https://github.com/rhcs-dashboard/ceph/blob/c04dd9c679bccc3dbc6e20c8f38ae8510046d6da/src/pybind/mgr/dashboard/tox.ini#L140-L156

In any case, it seems that it doesn's support python3.8:

> check create: /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/.tox/check
> ERROR: InterpreterNotFound: python3.8
> ___________________________________ summary ____________________________________
> ERROR:  check: InterpreterNotFound: python3.8

2022-09-09 15:08 UTC, ljflores commented
@epuertat @pereman2 yeah, I think Jammy runs with python 3.10.

2022-09-09 16:15 UTC, epuertat approved these changes
LGTM! Good work @pereman2 !

2022-09-09 16:21 UTC, ljflores approved these changes

2022-09-09 19:05 UTC, ljflores commented
make check arm64 failure: https://tracker.ceph.com/issues/57490

make check is still failing:
```
DEBUG:dashboard.controllers._router:list of parent paths: {'/api/api', '/api/ui-api', '/api', '/api/auth', '/api/docs'}
DEBUG:controllers.docs:Host: example.com
openapi-check run-test: commands[1] | diff openapi.yaml /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/.tox/openapi-check/tmp/openapi.yaml
10483c10483
< - description: Get Cluster Details
---
> - description: Get Ceph Users
ERROR: InvocationError for command /usr/bin/diff openapi.yaml .tox/openapi-check/tmp/openapi.yaml (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   openapi-check: commands failed

        Start  15: teardown-venv-for-mgr-dashboard-openapi
128/282 Test  #15: teardown-venv-for-mgr-dashboard-openapi ...   Passed    0.34 sec
```

2022-09-09 19:05 UTC, ljflores commented
jenkins test make check

2022-09-09 20:44 UTC, pereman2 commented
my bad, I forgot to stage stage openapi.yaml

2022-09-09 22:51 UTC, ljflores commented
@nizamial09 this PR is okay to merge. Can you approve or dismiss the changes requested?

2022-09-10 04:56 UTC, nizamial09 approved these changes

2022-09-10 07:19 UTC, merged