rados:ceph versions : mds : remove empty list entries from ceph versions
ceph/ceph pull request #48136
Opened 2022-09-16 09:22 UTC by shreyanshjain7174

rados:ceph versions : mds : remove empty list entries from ceph versions
- Tracker
   - [Bug #2110933](https://bugzilla.redhat.com/show_bug.cgi?id=2110933)
   - In out put of ceph versions, empty list gets printed for mds but not for other daemons.
if there are no rgw/rbd-mirror daemon, ceph-version doesn't display any information (empty list) for those daemons.
only for mds, empty list gets printed if there are no mds.

Signed-off-by: [Shreyansh Sancheti] <[ssanchet@redhat.com]>

2022-09-16 11:43 UTC, pdvian requested changes
The commit message should start with component name before ':'. Also there should not be multiple ':' to separate additional description. e.g for this PR it should be "mon: remove empty list entries from ceph versions"

2022-09-16 11:43 UTC, pdvian commented on src/mon/Monitor.cc
>      mgrmon()->count_metadata("ceph_version", &mgr);
- The code inside if blocks needs indentation. 
- Add space between if condition and round bracket also before curly brace.

2022-09-16 11:43 UTC, pdvian commented on src/mon/Monitor.cc
> +    }
Add new line after this curly braces.

2022-09-16 11:43 UTC, pdvian commented on src/mon/Monitor.cc
> +    if(!osd.empty()){
Similar changes required as mention for mgr block.

2022-09-16 11:43 UTC, pdvian commented on src/mon/Monitor.cc
> +    if(!mds.empty()){
Similar changes required as mention for mgr block.

2022-09-16 11:47 UTC, pdvian commented
@shreyanshjain7174 You have missed the check for mon versions but it's never going to be empty as to get ceph versions output you will need at least single mon.

2022-09-16 11:55 UTC, pdvian commented
> rados:ceph versions : mds : remove empty list entries from ceph versions
> 
>     * Tracker
>       
>       * [Bug #2110933](https://bugzilla.redhat.com/show_bug.cgi?id=2110933)
Open upstream tracker for this BZ and copy the details to tracker. Add link to tracker in the commit.

>       * In out put of ceph versions, empty list gets printed for mds but not for other daemons.
>         if there are no rgw/rbd-mirror daemon, ceph-version doesn't display any information (empty list) for those daemons.
>         only for mds, empty list gets printed if there are no mds.
> 
> 
> Signed-off-by: [Shreyansh Sancheti] <[[ssanchet@redhat.com](mailto:ssanchet@redhat.com)]>

Refer below links for best practices and coding styles:
[1] https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst
[2] https://github.com/ceph/ceph/blob/main/CodingStyle

2022-09-16 17:38 UTC, shreyanshjain7174 commented
I have done the suggested changes.

2022-09-16 21:06 UTC, vumrao commented
@shreyanshjain7174 I think you need to modify the commit message of the first commit in this PR as looks like somehow the title of that commit got dropped!

2022-09-16 21:57 UTC, vumrao commented
and I forgot to mention congratulations on your first Ceph PR, it is always special :)

2022-09-16 22:51 UTC, ljflores commented
Congrats @shreyanshjain7174!

2022-09-19 12:32 UTC, pdvian requested changes
The changes are in mon component so commit message should contain "mon:" not "mds:". Also there should not be a space between component and ':' char in commit message.

2022-09-19 12:32 UTC, pdvian commented on src/mon/Monitor.cc
> +    if(!mgr.empty()){
There should be space between if keyword and starting parentheses here. Also there should be space between ending parentheses and  curly bracket.

2022-09-19 12:32 UTC, pdvian commented on src/mon/Monitor.cc
> +    if(!osd.empty()){
There should be space between if keyword and starting parentheses here. Also there should be space between ending parentheses and curly bracket.

2022-09-19 12:32 UTC, pdvian commented on src/mon/Monitor.cc
> +    if(!mds.empty()){
There should be space between if keyword and starting parentheses here. Also there should be space between ending parentheses and curly bracket.

2022-09-19 12:42 UTC, pdvian commented
> rados:ceph versions : mds : remove empty list entries from ceph versions
> 
>     * Tracker
>       
>       * [Bug #2110933](https://bugzilla.redhat.com/show_bug.cgi?id=2110933)
>       * In out put of ceph versions, empty list gets printed for mds but not for other daemons.
>         if there are no rgw/rbd-mirror daemon, ceph-version doesn't display any information (empty list) for those daemons.
>         only for mds, empty list gets printed if there are no mds.
> 
> 
> Signed-off-by: [Shreyansh Sancheti] <[[ssanchet@redhat.com](mailto:ssanchet@redhat.com)]>

Edit this commit message to something like: 
In ceph versions command output, empty list gets printed for
mds. If there are no rgw/rbd-mirror daemon deployed, the
ceph versions command doesn't display version information
(empty list) for those daemons. Similar issue has been observed
for mgr and osd daemons. The ceph versions should only show
version information for daemons which are deployed in the cluster.

Fixes : https://tracker.ceph.com/issues/57585

Signed-off-by: Shreyansh Sancheti <ssanchet@redhat.com>

2022-09-19 13:07 UTC, pdvian commented
@shreyanshjain7174 There are 2 commits in this PR. You need to merge both commits to single commit. Let's catch up to fix this PR.

2022-09-28 12:59 UTC, pdvian approved these changes
LGTM. Thanks!

2022-12-06 00:11 UTC, ljflores commented
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2022-11-23-1348

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58098
    2. https://tracker.ceph.com/issues/58096
    3. https://tracker.ceph.com/issues/57311
    4. https://tracker.ceph.com/issues/58097
    5. https://tracker.ceph.com/issues/57731
    6. https://tracker.ceph.com/issues/57311
    7. https://tracker.ceph.com/issues/51945

Details:
    1. qa/workunits/rados/test_crash.sh: crashes are never posted - Ceph - RADOS
    2. test_cluster_set_reset_user_config: NFS mount fails due to missing ceph directory - Ceph - Orchestrator
    3. rook: ensure CRDs are installed first - Ceph - Orchestrator
    4. qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer - Infrastructure
    5. Problem: package container-selinux conflicts with udica < 0.2.6-1 provided by udica-0.2.4-1 - Infrastructure
    6. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    7. qa/workunits/mon/caps.sh: Error: Expected return 13, got 0 - Ceph - RADOS

2022-12-07 18:49 UTC, merged