mgr/dashboard: cluster utilization card
ceph/ceph pull request #48173
Opened 2022-09-19 13:26 UTC by Pegonzal

Signed-off-by: Pedro Gonzalez Gomez <pegonzal@redhat.com>

Cluster utilization card

Displays graphs for the:

- Used capacity 
- IOPS
- Latency
- Client Throughput - (Not sure which promql is needed)
- Recovery Troughput - (Not sure which promql is needed)

Everything is done but a couple promqls to fetch the proper data from prometheus.
And some minor styling adjustments for aligning the graphs labels. 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-09-20 09:47 UTC, pereman2 requested changes

2022-09-20 09:47 UTC, pereman2 commented on src/pybind/mgr/dashboard/controllers/prometheus.py
> +        return self.alert_proxy('GET', '/silences', payload=params)
```suggestion
        return self.alert_proxy('GET', '/silences', params)
```

2022-09-20 09:47 UTC, pereman2 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/new-dashboard/dashboard/dashboard.component.ts
> +  readonly source = timer(0, 10000);
Let's change this name to something more meaningful and we will need to change the value on the fly.

2022-09-20 09:47 UTC, pereman2 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/new-dashboard/dashboard/dashboard.component.ts
> +    'sum(ceph_osd_recovery_bytes)'
```suggestion
  enum PrometheusQuery {
    CAPACITY = 'sum(ceph_osd_stat_bytes_used)/sum(ceph_osd_stat_bytes)',
    IOPS = 'sum(ceph_osd_op_rw)',
```

2022-09-20 09:47 UTC, pereman2 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/new-dashboard/dashboard/dashboard.component.ts
> +          end: selectedTime['end'],
Why not having only one timer for all prometheus calls?
```suggestion
    timer(0, this.interval).subscribe(() => {
      this.prometheusService
        .getPrometheusData({
          params: this.promqls[0],
          start: selectedTime['start'],
          end: selectedTime['end'],
          step: selectedTime['step']
        })
        .subscribe((data: any) => {
          if (data.result.length) {
            this.usedCapacity$ = data.result[0].values;
          }
        });
         this.prometheusService
        .getPrometheusData({
          params: this.promqls[1],
          start: selectedTime['start'],
          end: selectedTime['end'],
    });
  
    
```

2022-09-21 09:16 UTC, pereman2 requested changes

2022-09-21 09:36 UTC, Pegonzal commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/new-dashboard/dashboard/dashboard.component.ts
> +    this.timerGetPrometheusDataSub = this.timer.subscribe(() => {
Wooops, you are right.

2022-09-27 08:41 UTC, nizamial09 reviewed
@Pegonzal we can use the `dimlessBinaryPipe` to achieve something like this. I havent verified the data's coming but you can give it a go.
![Screenshot from 2022-09-27 14-10-03](https://user-images.githubusercontent.com/71764184/192477617-9cfed3ac-c799-4e5b-8569-8ae55e3332e0.png)

2022-10-19 18:55 UTC, epuertat commented
Hey @Pegonzal, I finally found time to test this PR, and I'm seeing some issues, like (storage capacity indicates 50% of 6 GB, but the cluster utilization says 8 GB 🤔 :

![image](https://user-images.githubusercontent.com/37327689/196779187-5a4b3627-9225-4b0c-95eb-035826b963f1.png)

So what about having a hands-on meeting and having a thorough/interactive demo & review?

2022-10-20 08:43 UTC, Pegonzal commented
> Hey @Pegonzal, I finally found time to test this PR (the Prometheus integration looks great BTW partying_face), but I'm facing some issues and not sure if there's something wrong with my testbed (like "storage capacity" charts indicating 50% of 6 GB, but "cluster utilization" saying 8 GB thinking ):
> 
> ![image](https://user-images.githubusercontent.com/37327689/196779187-5a4b3627-9225-4b0c-95eb-035826b963f1.png)
> 
> So what about having a hands-on meeting and having a thorough/interactive demo & review?

For sure @epuertat , we can have a meeting and I'll explain what's going on

2022-11-18 16:18 UTC, pereman2 requested changes
Needs rebase. Was the alignment fixed?

2022-11-24 11:57 UTC, Pegonzal commented
> Needs rebase. Was the alignment fixed?

It is at the moment, not the best fix but works

2022-11-24 17:51 UTC, pereman2 requested changes

2022-11-24 17:51 UTC, pereman2 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/new-dashboard/dashboard-area-chart/dashboard-area-chart.component.ts
> +    );
Instead of having 2 data variables, could we have the input as an array of datas so it is more flexible.

2022-11-24 17:51 UTC, pereman2 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/new-dashboard/dashboard/dashboard.component.ts
> +          params: Promqls.OPS,
I see a lot of repetition
```suggestion
  for (const [query_name, query] of queries) {
      this.prometheusService
        .getPrometheusData({
          params: query,
          start: selectedTime['start'],
          end: selectedTime['end'],
          step: selectedTime['step']
        })
        .subscribe((data: any) => {
          if (data.result.length) {
            this.queryResults[query_name] = data.result[0].values;
          }
        });

```

2023-01-10 15:01 UTC, pereman2 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/new-dashboard/dashboard/dashboard.component.ts
> +  recoveryThroughput: any;
There are too many any types here. Output of prometheus queries has a clear format we can classify:
```
{"resultType": "matrix", "result": [{"metric": {}, "values": [[1673362508, "0"], [1673362538, "0"], [1673362568, "0"], [1673362598, "0"], [1673362628, "0"], [1673362658, "0"]]}]}
values == Array<DataPoint>
Datapoint {
  timestamps: number;
  value: string
}

2023-01-10 15:28 UTC, anthonyeleven reviewed
Docs lgtm

2023-01-11 06:23 UTC, nizamial09 approved these changes

2023-01-16 14:02 UTC, Pegonzal commented
jenkins test make check

2023-01-16 14:03 UTC, Pegonzal commented
jenkins test dashboard cephadm

2023-01-16 18:50 UTC, merged