pacific: log: Make log_max_recent have an effect again.
ceph/ceph pull request #48311
Opened 2022-09-30 10:24 UTC by k0ste

backport tracker: https://tracker.ceph.com/issues/56635

---

backport of https://github.com/ceph/ceph/pull/46736
parent tracker: https://tracker.ceph.com/issues/56093

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2023-01-24 03:26 UTC, k0ste commented
needs-qa

2023-11-17 20:27 UTC, k0ste commented
@tchaikov only docs failed, please take a look

2024-01-10 00:14 UTC, ljflores commented
@cbodley @k0ste @idryomov is this a blocker for 16.2.15? If so, add it to https://github.com/ceph/ceph/milestone/17

2024-01-10 05:40 UTC, k0ste commented
> @cbodley @k0ste @idryomov is this a blocker for 16.2.15? If so, add it to https://github.com/ceph/ceph/milestone/17 since Pacific is going EOL.

Only developers can edit labels and milestones, I'm not

2024-01-11 21:42 UTC, idryomov requested changes
> Conflicts:
>  - file: src/common/options/global.yaml.in
>    desc: not exists in pacific?

This file indeed doesn't exist in pacific, but simply dropping the hunk isn't right.  Please tack on `.set_min(1)` on `log_max_recent` entry in `src/common/options.cc`:
```
    Option("log_max_recent", Option::TYPE_INT, Option::LEVEL_ADVANCED)
    .set_default(500)
    .set_daemon_default(10000)
    .set_min(1)
    .set_description("recent log entries to keep in memory to dump in the event of a crash")
```

2024-01-12 12:18 UTC, k0ste commented
Ilya, done

2024-01-12 20:49 UTC, idryomov approved these changes

2024-01-22 22:38 UTC, ljflores commented
Rados-approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomc5smPyFbb1933-wip-yuri4-testing-2024-01-18-1257-pacific-no-needs-qa

2024-01-24 07:30 UTC, mchangir approved these changes
LGTM

https://pulpito.ceph.com/yuriw-2024-01-19_23:24:27-fs-wip-yuri4-testing-2024-01-18-1257-pacific-distro-default-smithi/
https://pulpito.ceph.com/yuriw-2024-01-21_16:37:18-fs-wip-yuri4-testing-2024-01-18-1257-pacific-distro-default-smithi/

2024-01-24 15:22 UTC, merged