rgw: add bucket chown entrypoint
ceph/ceph pull request #48420
Opened 2022-10-10 13:52 UTC by giubacc

@dang, @cbodley I would like to have your opinion regarding the direction taken for this PR.
Given that link/unlink operations are more close with Ceph world, we are proposing an entrypoint for `chown`. 
For the time being I tested this manually on my machine; if it's worth continuing with this, can we discuss also how to properly handle tests.
----

Added an admin rest entrypoint for changing the owner of a bucket. The call is mapped over the existing: RGWHandler_Bucket::op_put(). The query string must contain the parameter: owner in order to trigger a chown.

Example:

admin/bucket?owner&uid=jack&bucket=foo

This invocation changes the bucket foo's owner with the user jack.

The user calling chown entrypoint must have users capability set with write permission. The call returns a 200 HTTP code on success with an empty body.

Fixes: https://tracker.ceph.com/issues/57569
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-10-17 13:03 UTC, giubacc commented
@cbodley @dang, have you had a chance to take a look to this?
We'd need to understand if this direction is correct from an upstream point of view.

2022-10-17 16:15 UTC, dang approved these changes

2022-10-17 20:23 UTC, cbodley commented
i thought the goal was to make 'bucket link/unlink' backend-agnostic, so we could use the `radosgw-admin bucket link/unlink` commands and `RGWOp_Bucket_Link/Unlink` APIs with any store. it sounds like we've decided to expose 'bucket chown' instead, but what's the plan for the existing link/unlink stuff?

2022-10-18 07:32 UTC, giubacc commented
> i thought the goal was to make 'bucket link/unlink' backend-agnostic, so we could use the `radosgw-admin bucket link/unlink` commands and `RGWOp_Bucket_Link/Unlink` APIs with any store. it sounds like we've decided to expose 'bucket chown' instead, but what's the plan for the existing link/unlink stuff?

After a chat with @dang, we concluded that addressing the `link/unlink` issue is a far more complex task than expose `chown`.
Given that `chown` can fulfill pretty well our needs, we can avoid to embark ourselves on a business potentially much more complex involving non trivial design choices that could be controversial upstream.
Because of this we decided to propose instead a `chown` entrypoint.

2022-10-20 14:51 UTC, cbodley approved these changes
this admin API looks fine, i'm just trying to understand what the next steps are for bucket link/unlink. don't we still need to expose them in sal, even if RadosStore is the only one that implements them?

2022-10-20 15:16 UTC, giubacc commented
> this admin API looks fine, i'm just trying to understand what the next steps are for bucket link/unlink. don't we still need to expose them in sal, even if RadosStore is the only one that implements them?

Very appropriate question.
If you want my opinion, everything that is exposed to the world (with a rest entrypoint) should be modeled inside with an abstract representation.

2022-10-20 15:25 UTC, dang commented
> this admin API looks fine, i'm just trying to understand what the next steps are for bucket link/unlink. don't we still need to expose them in sal, even if RadosStore is the only one that implements them?

Probably.

2022-10-21 08:45 UTC, giubacc commented
I force pushed an identical commit to trigger again the CI because there was the `make check` failed.
But now there is also the `API tests` in failed status.
I have looked at the jenkins logs but the cause of these failing is not clear to me; can you help me with this?

2022-10-21 13:34 UTC, cbodley commented
jenkins test api

2022-10-21 13:34 UTC, cbodley commented
jenkins test make check

2022-10-21 13:35 UTC, cbodley commented
API tests have been hitting https://tracker.ceph.com/issues/57834 lately, so sometimes take several tries :(

2022-10-21 14:15 UTC, giubacc commented
jenkins test api

2022-10-21 14:15 UTC, giubacc commented
jenkins test make check

2022-10-21 16:24 UTC, giubacc commented
@cbodley @dang I think we are done here; feel free to merge.

2022-10-24 14:08 UTC, cbodley requested changes
@giubacc @dang sorry, i just remembered that `radosgw-admin bucket chown` has to iterate through all of the bucket's objects to rewrite their ACLs. for large buckets, this can take a long time, and HTTP requests will almost always time out before this completes

long-lived requests make for bad REST APIs, because the client will time out never knowing whether their operation actually completed. normal clients will time out and send retries, which would cause us to run several iterations of the same operation at the time

i'm guessing this is why we didn't add a REST API for it in the first place, and probably shouldn't now. what do you guys think?

2022-10-24 14:30 UTC, giubacc commented
@cbodley, I haven't thought about that.
What do you think about a mixed approach: an http client is allowed to do a `chown` operation but it will only receive an `ack/nack` if he can actually perform that operation or not.
Once he has received an `ack/nack` the operation will eventually take place async on another thread.
Currently what happens if a `chown` operation with the admin tool fails in the middle? is the entire operation rolled back?

2022-10-24 14:43 UTC, dang commented
If chown isn't viable, then we probably need to do the work to expose link/unlink.

2022-10-24 15:30 UTC, dang commented
The original context of this work was to expose link/unlink as REST APIs.  Since they aren't in Zipper, I suggested that it was much less work to expose chown, which is this PR.  If chown can't be a REST API, then we probably need to go back to exposing link/unlink, including adding them to Zipper.

2022-10-24 15:33 UTC, cbodley commented
we already have APIs for `RGWOp_Bucket_Link`/`Unlink` in rgw_rest_bucket.cc, i think it's just the Zipper part that's missing

2022-10-24 16:01 UTC, giubacc commented
Let me explain our problem here, a downstream problem, I'm conscious of this; In our context, we cannot simply use the `rados-admin` tool because the `rgw` is using a custom backend that can be used in an exclusive manner by a single process.
We cannot allow another process to change data meanwhile rgw is also working on that.
`chown` is an important feature we would like to support; we are conscious that this is a slow operation in certain cases, but we would like not to loose this function.
Just to reason a bit on the problem, a solution (ok complicated) for this could be to make `chown` entrypoint to return a ` request id` that the client could then use to query the status of the call.
what do you guys think about this, would be reasonable to try to implement this?

2022-10-24 16:31 UTC, cbodley commented
(cc @mattbenjamin)

@giubacc i'd recommend that you try to support local radosgw-admin commands like we are with dbstore. what is it that makes this shared access so hard in your case? just that you can't make mutations atomic?

for this standalone-rgw use case, i still think it's ideal to have a hybrid backend that uses a database for metadata and files for object data, so i'd love to find a way for your work to converge in some form with dbstore

2022-10-25 07:05 UTC, giubacc commented
@cbodley we have to internally discuss about this. Given the nature of s3gw, that is a kubernetes pod exposing an s3 endpoint, the natural way to operate with an external client (such as the UI) is via rest calls.
A text based client, in this context, is most likely not suitable for this purpose.

2022-10-28 14:12 UTC, giubacc commented
Well guys, we made a discussion on this our side and we concluded that there is no a simple solution to this issue :wink:.
In my opinion the best approach here could be if we try to develop an async rest approach to this call.
I can try to develop this, but because we'd like in the end try to merge this upstream and not to diverge; I'm asking you if you think this will ever have chances to be merged.

2022-10-28 16:58 UTC, dang commented
Are the link/unlink REST APIs not sufficient?

2022-10-28 17:26 UTC, cbodley commented
thanks @giubacc. radosgw-admin does far too much to expose *everything* as REST APIs, but we can certainly find a better way to expose chown. i don't think an async API is necessarily the way to go though

if the main problem is client timeouts/retries, we can avoid the timeouts by sending regular progress updates in the response body. `radosgw-admin bucket chown` is already doing something like this in https://github.com/ceph/ceph/blob/e7b9cd3/src/rgw/rgw_bucket.cc#L2967-L2968, by logging to stderr every 1000 objects. 1000 is probably too high for the REST API, so i'd lower that to 100 or so

we can turn that output into json by taking a `RGWFormatterFlusher` argument like other admin APIs do (ex [`RGWBucketAdminOp::info()`](https://github.com/ceph/ceph/blob/e7b9cd3/src/rgw/rgw_bucket.cc#L1194-L1198)). how about a response body like this?
```json
{
  "OldOwner": "tom",
  "NewOwner": "jerry",
  "ObjectProgress": [
    {
      "Count": 100,
      "Position": "aaaa"
    },
    {
      "Count": 200,
      "Position": "bbbb"
    },
    {
      "Count": 300,
      "Position": "cccc"
    }
  ]
}
```

2022-10-31 10:03 UTC, giubacc commented
> Are the link/unlink REST APIs not sufficient?

Unfortunately I don't think so. We need an API to change the owner of a bucket.
Link/Unlink do not implement this semantics, they are just defining a group of users that can operate on a bucket, but the original owner is untouched.
Unless I have misunderstood something here.

2022-10-31 10:05 UTC, giubacc commented
> thanks @giubacc. radosgw-admin does far too much to expose _everything_ as REST APIs, but we can certainly find a better way to expose chown. i don't think an async API is necessarily the way to go though
> 
> if the main problem is client timeouts/retries, we can avoid the timeouts by sending regular progress updates in the response body. `radosgw-admin bucket chown` is already doing something like this in https://github.com/ceph/ceph/blob/e7b9cd3/src/rgw/rgw_bucket.cc#L2967-L2968, by logging to stderr every 1000 objects. 1000 is probably too high for the REST API, so i'd lower that to 100 or so
> 
> we can turn that output into json by taking a `RGWFormatterFlusher` argument like other admin APIs do (ex [`RGWBucketAdminOp::info()`](https://github.com/ceph/ceph/blob/e7b9cd3/src/rgw/rgw_bucket.cc#L1194-L1198)). how about a response body like this?
> 
> ```json
> {
>   "OldOwner": "tom",
>   "NewOwner": "jerry",
>   "ObjectProgress": [
>     {
>       "Count": 100,
>       "Position": "aaaa"
>     },
>     {
>       "Count": 200,
>       "Position": "bbbb"
>     },
>     {
>       "Count": 300,
>       "Position": "cccc"
>     }
>   ]
> }
> ```

This is an interesting approach, I will sure investigate this.
Thanks!

2022-11-08 08:44 UTC, giubacc commented
@cbodley, @dang, Hi guys,
Yesterday I had a chance to work on this and I updated the implementation using the approach suggested by Casey to use a `RGWFormatterFlusher`.
Let me know if this is reasonably good; for the time being, I have tested the API with our downstream backend; so probably we will need to address proper testing for rados.

2022-11-09 15:14 UTC, cbodley reviewed
> I have tested the API with our downstream backend; so probably we will need to address proper testing for rados.

you can add a test case to qa/tasks/radosgw_admin_rest.py

2022-11-09 16:48 UTC, giubacc commented on src/rgw/rgw_bucket.cc
> +  if(formatter){
The choice to make this a pointer and not a ref comes from the call in `src/rgw/rgw_bucket.cc`: 

```
void check_bad_user_bucket_mapping(...)
{
...
r = actual_bucket->chown(dpp, user, nullptr, null_yield);
...
}
```

I'd prefer to make this a reference, but I don't know if we can adjust the call above.

2022-11-11 13:39 UTC, giubacc commented
jenkins test api

2022-11-11 17:27 UTC, cbodley commented on src/rgw/rgw_bucket.cc
> +  if(formatter){
i see, thanks. it's fine to leave flusher as a pointer for now

2022-11-11 17:44 UTC, cbodley commented on qa/tasks/radosgw_admin_rest.py
> +        key = boto.s3.key.Key(foo_bucket)
this just creates an in-memory key to represent an object name. see https://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.key.Key

you'll need to name these objects, like `key = boto.s3.key.Key(foo_bucket, 'obj%s' % i)`, then call something like `key.set_contents_from_string('')` to actually upload then

2022-11-11 18:38 UTC, cbodley commented
we document these admin APIs in https://docs.ceph.com/en/latest/radosgw/adminops/. can you please add a section about this chown API to doc/radosgw/adminops.rst, like after Link Bucket?

2022-11-14 16:13 UTC, anthonyeleven commented on doc/radosgw/adminops.rst
> +Change Bucket's Owner
Suggest `Change the Owner of a Bucket`
In part because the apostrophe might complicate future linking.  Yes this is minor.

2022-11-14 16:16 UTC, anthonyeleven commented on doc/radosgw/adminops.rst
> +:Description: On going operation's progression information.
Suggest `Progress of the on-going operation.`

2022-12-05 08:33 UTC, giubacc commented
jenkins make check

2022-12-12 15:19 UTC, giubacc commented
@cbodley, I've rebased this on latest changes; it seems in a good shape; let me know if you need us to do something.

2022-12-23 08:09 UTC, giubacc commented
> @cbodley, I've rebased this on latest changes; it seems in a good shape; let me know if you need us to do something.

bump

2023-01-11 15:35 UTC, giubacc commented
There have been too much changes to `chown` after this PR and we cannot devote enough time to this now.
I'm closing this; eventually we will retry a new proposal in the future.

2023-01-11 15:35 UTC, closed without merging