mds/PurgeQueue: don't consider filer_max_purge_ops when _calculate_ops
ceph/ceph pull request #48786
Opened 2022-11-08 08:27 UTC by Rethan

_calculate_ops relying on a config which can be modified on the fly will cause a bug. e.g.
1. A file has 20 objects and filer_max_purge_ops config was 10.
2. calling PurgeQueue::_execute_item and _calculate_ops returns 10, so ops_in_flight add 10.
3. adjust filer_max_purge_ops to 20 on the fly
4. calling PurgeQueue::_execute_item_complete and _calculate_ops returns 20, so ops_in_flight dec 10.
5. since ops_in_flight is uint64, this cause an overflow which makes ops_in_flight far more greater than max_purge_ops, so _can_consume will always return false, then PurgeQueue will stuck.

filer_max_purge_ops will still work when _do_purge_range, so it's ok to ignore it here.

Signed-off-by: haoyixing <haoyixing@kuaishou.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-11-08 08:35 UTC, Rethan commented
When increasing filer_max_purge_ops on a pacific mds, the purge_queue becomes abnormal immediately, but I think it also applies to the main branch.

2022-11-08 15:36 UTC, Rethan commented
jenkins test make check arm64

2022-11-09 01:28 UTC, Rethan commented
jenkins test make check arm64

2022-11-11 08:59 UTC, vshankar commented
Requires a tracker - please create one @Rethan.

2022-11-11 09:16 UTC, Rethan commented
> Requires a tracker - please create one @Rethan.

created #58008.

2022-11-14 11:17 UTC, kotreshhr approved these changes
lgtm

2022-11-15 10:43 UTC, vshankar commented
@Rethan Nice catch. Is the `std::min` ensuring that PurgeQueue doesn't overload object trimming?

2022-11-15 11:36 UTC, Rethan commented
> @Rethan Nice catch. Is the `std::min` ensuring that PurgeQueue doesn't overload object trimming?

I believed it was intended to do so by adding ops to ops_in_flight and comparing with max_purge_ops.The dynamic config value makes it wrong. Besides,

2022-11-15 15:21 UTC, vshankar commented
> > @Rethan Nice catch. Is the `std::min` ensuring that PurgeQueue doesn't overload object trimming?
> 
> I believed it was intended to do throttling by adding ops to ops_in_flight and comparing with max_purge_ops, while it was broken due to the dynamic config. We now separate PurgeQueue throttle (which is overall throttle for files and ops) and Filer throttle (throttling objecter ops for one file) and let them throttle independently. This still limit the global object trimming since inflight_ops would not be larger than max_purge_files * filer_max_purge_ops.

True. I'm a tiny bit worried if this _could_ result in some resource starvation since PurgeQueue would be sending more ops than before. I will check on this and get back to you tomorrow.

2022-11-18 09:25 UTC, Rethan commented
> > > @Rethan Nice catch. Is the `std::min` ensuring that PurgeQueue doesn't overload object trimming?
> > 
> > 
> > I believed it was intended to do throttling by adding ops to ops_in_flight and comparing with max_purge_ops, while it was broken due to the dynamic config. We now separate PurgeQueue throttle (which is overall throttle for files and ops) and Filer throttle (throttling objecter ops for one file) and let them throttle independently. This still limit the global object trimming since inflight_ops would not be larger than max_purge_files * filer_max_purge_ops.
> 
> True. I'm a tiny bit worried if this _could_ result in some resource starvation since PurgeQueue would be sending more ops than before. I will check on this and get back to you tomorrow.

If mds_max_purge_ops doest not change, I think it will send less ops, not more. For example, one big file (1k objects) was considered 10 inflight ops (filer_max_purge_ops) before, since filer will do 10 concurrent ops for the file, now it need to take 1k ops tokens before purge_queue consume the item.

2022-11-18 16:59 UTC, vshankar commented
> > > > @Rethan Nice catch. Is the `std::min` ensuring that PurgeQueue doesn't overload object trimming?
> > > 
> > > 
> > > I believed it was intended to do throttling by adding ops to ops_in_flight and comparing with max_purge_ops, while it was broken due to the dynamic config. We now separate PurgeQueue throttle (which is overall throttle for files and ops) and Filer throttle (throttling objecter ops for one file) and let them throttle independently. This still limit the global object trimming since inflight_ops would not be larger than max_purge_files * filer_max_purge_ops.
> > 
> > 
> > True. I'm a tiny bit worried if this _could_ result in some resource starvation since PurgeQueue would be sending more ops than before. I will check on this and get back to you tomorrow.
> 
> If mds_max_purge_ops doest not change, I think it will send less ops, not more. For example, one big file (1k objects) was considered 10 inflight ops (filer_max_purge_ops) before, since filer will do 10 concurrent ops for the file. Now it needs to take 1k ops tokens before purge_queue consume the item.

Fair enough. The changes look fine.

Note that our testing infra is a bit broken at the moment, so this will have to wait for sometime (possibly early next week).

2022-11-19 08:26 UTC, dparmar18 commented
If this issue can be reproduced using the steps mentioned in the commit description, shouldn't we be having a testcase to verify too? What do you think @vshankar @kotreshhr ?

2022-11-20 16:54 UTC, ajarr requested changes
@Rethan 
nit:  Please add tag 'Fixes: <ceph tracker link'> in the commit message.

I see it in the PR description but not in the commit message.

otherwise the code looks good.

2022-11-21 01:37 UTC, Rethan commented
> @Rethan nit: Please add tag 'Fixes: <ceph tracker link'> in the commit message.
> 
> I see it in the PR description but not in the commit message.
> 
> otherwise the code looks good.

Updated.

2022-11-21 03:15 UTC, Rethan commented
jenkins test make check arm64

2022-11-21 03:15 UTC, Rethan commented
jenkins test windows

2022-11-21 09:25 UTC, vshankar commented
> If this issue can be reproduced using the steps mentioned in the commit description, shouldn't we be having a testcase to verify too? What do you think @vshankar @kotreshhr ?

That requires the config to be changed at the right time which can be a _bit_ hard to get right.

2022-11-21 13:25 UTC, ajarr approved these changes
@Rethan thanks!

2022-12-08 13:28 UTC, vshankar commented
https://tracker.ceph.com/projects/cephfs/wiki/Main#08-Dec-2022

2022-12-12 14:08 UTC, merged