pacific: ceph-crash: drop privleges to run as "ceph" user, rather than root (CVE-2022-3650)
ceph/ceph pull request #48804
Opened 2022-11-09 02:58 UTC by tserong

backport tracker: https://tracker.ceph.com/issues/57996

---

backport of https://github.com/ceph/ceph/pull/48713
parent tracker: https://tracker.ceph.com/issues/57967

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2022-11-09 03:21 UTC, tserong commented
Additional trivial cleanup commits avoid cherry-pick conflicts

2022-11-09 04:56 UTC, tserong commented
jenkins test api

2022-12-05 23:49 UTC, ljflores requested changes
See https://github.com/ceph/ceph/pull/48713#issuecomment-1338375615

2023-01-27 16:23 UTC, ljflores approved these changes

2023-02-15 16:30 UTC, ktdreyer approved these changes

2023-02-16 16:32 UTC, merged