quincy: ceph-crash: drop privleges to run as "ceph" user, rather than root (CVE-2022-3650)
ceph/ceph pull request #48805
Opened 2022-11-09 03:00 UTC by tserong

backport tracker: https://tracker.ceph.com/issues/57997

---

backport of https://github.com/ceph/ceph/pull/48713
parent tracker: https://tracker.ceph.com/issues/57967

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2022-11-09 03:21 UTC, tserong commented
Additional trivial cleanup commits avoid cherry-pick conflicts

2022-12-05 23:49 UTC, ljflores requested changes
See https://github.com/ceph/ceph/pull/48713#issuecomment-1338375615

2023-01-27 16:22 UTC, ljflores approved these changes

2023-01-27 16:23 UTC, ljflores commented
jenkins test make check

2023-01-30 10:18 UTC, tserong commented
jenkins test make check

2023-02-17 17:27 UTC, ljflores commented
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri3-testing-2023-02-16-0752-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58146
    2. https://tracker.ceph.com/issues/58585

Details:
    1. test_cephadm.sh: Error: Error initializing source docker://quay.ceph.io/ceph-ci/ceph:master - Ceph - Orchestrator
    2. rook: failed to pull kubelet image - Ceph - Orchestrator

2023-02-17 17:27 UTC, merged