doc/cephfs: simplify ceph fs volume create command
ceph/ceph pull request #49203
Opened 2022-12-02 18:13 UTC by ktdreyer

Make it easy for new users to choose a sensible default "cephfs" filesystem name.

2022-12-02 18:16 UTC, anthonyeleven commented
IMHO it then becomes unclear that one _can_ specify a different name.  This sort of convention is common in CLI documentation.

2022-12-05 17:36 UTC, ktdreyer commented
The purpose of this change is to make it easier for new users. Every choice we present to new users is an additional hurdle that contributes to the feeling that Ceph is hard.

I've updated the PR to add a link to the full [fs-volumes](https://docs.ceph.com/en/latest/cephfs/fs-volumes/) page. This should read as "advanced" information, not something we put on the CephFS index page.

2022-12-05 21:04 UTC, anthonyeleven commented
Thanks, that helps.  @zdover23 Do you have any thoughts?

2022-12-08 15:27 UTC, dparmar18 commented
I think the existing one is still understandable. If we want to make it more easy, this can also be done:

```
ceph fs volume create <fs name>    #where <fs name > can be any name
```

Rationale being: let's say im a complete beginner, if i see `ceph fs volume create cephfs`, I would think okay so `cephfs` is what I need to have. Yeah the inclusion of ceph-volume link might help here, but if there's someone like who just jumps to things, i might skip reading it. Just an opinion here.

2022-12-08 16:31 UTC, ktdreyer commented
I jump to things as well. I want to quickly copy and paste. I don't want to paste `<` or `>` characters into my terminal accidentally.

I've updated the PR again to include a comment above the command to explain what it's doing.

2022-12-09 00:02 UTC, zdover23 commented
> Thanks, that helps. @zdover23 Do you have any thoughts?

My first thought is that I should probably do a better job promulgating the conventions that govern the upstream Ceph documentation.

I also think that I can lay claim to more recently having been a complete beginner than can anyone else in this discussion, and I have precious little sympathy for complete beginners who "jump" to commands and cut and paste them without having understood those commands in context.

2022-12-09 00:02 UTC, zdover23 requested changes

2022-12-09 00:13 UTC, zdover23 commented
> IMHO it then becomes unclear that one _can_ specify a different name. This sort of convention is common in CLI documentation.

I agree with @anthonyeleven that (as I read it, and as I try to put myself in the mind of a first-time reader) the new formulation suggests that the only possible filesystem name is "cephfs".

I suggest that this model be used instead: https://docs.ceph.com/en/quincy/rbd/rados-rbd-cmds/#create-a-block-device-user

In this model, we give the general formula first and then a specific example command second.

(I know that this RBD-related example involves a rather long command with an impressive train of specifications that stretch across the horizon of the website, but it's an example that I have recently touched that seems apropos.)

2022-12-15 15:07 UTC, ktdreyer commented
I've updated the PR again to use the sphinx-prompt module and make it clearer that `cephfs` is an example name, not the only possible name.

2022-12-15 15:08 UTC, ktdreyer commented on doc/cephfs/index.rst
>  .. code:: bash
Thanks, I've switched to this one.

2022-12-19 06:07 UTC, vshankar commented
@zdover23 If the changes look fine, feel free to merge.

2022-12-19 06:44 UTC, anthonyeleven commented
LGTM, thanks!

2022-12-19 06:45 UTC, anthonyeleven approved these changes

2022-12-19 06:46 UTC, merged