rados:stengthen daemons from crashing in case of mal-formatted cmd input
ceph/ceph pull request #49279
Opened 2022-12-06 09:55 UTC by gaord

this is one of couple commits of the fix effort. code under src/common gets reviewed to make sure all cmd_getval stuff are running safe with this commit.
bug to fix:https://tracker.ceph.com/issues/57890
related bug: https://tracker.ceph.com/issues/54558

Signed-off-by: Ben Gao <bengao168@msn.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2022-12-07 13:14 UTC, gaord commented
@pjjw Hi, the commit should be clean-handed with ceph windows tests failure? What do you think? Thank you.

2022-12-13 11:41 UTC, idryomov reviewed
This is up to @ceph/core but if it was me, I'd look into changing `cmd_getval` interface to get rid of exceptions instead of trying to sprinkle more try/catch around.  The current interface (bool return value + potential exception) is clearly too confusing, just judging by the number of places where it appears to be misused.

2022-12-13 12:53 UTC, gaord commented
@idryomov @

> This is up to @ceph/core but if it was me, I'd look into changing `cmd_getval` interface to get rid of exceptions instead of trying to sprinkle more try/catch around. The current interface (bool return value + potential exception) is clearly too confusing, just judging by the number of places where it appears to be misused.

reviewing code could tell that tons of cases were already consolidated good by try/catch. This pr just included cases slipped through the net. thinking about "ceph tell" command may send Mal-formatted string to any daemons, eventually get them crashed, it's appealing to fix it soon with less impact one way or another.

2023-09-22 09:43 UTC, rzarzynski approved these changes

2023-09-22 09:43 UTC, rzarzynski commented on src/messages/MMonCommand.h
> +    } catch (bad_cmd_get& e) {
OK, so most of the changes in this commit is about reindenting `cmd_getval()`-related blocks due to catching `bad_cmd_get`.

2023-09-22 09:43 UTC, rzarzynski commented on src/mon/Monitor.cc
> +        reply_command(op, -EINVAL, e.what(), 0);
`MMonCommandAck` the `reply_command()` generates is finally handled by `MonClient` which, as far as I see, doesn't use the version (`0` here) field.

2023-10-11 14:58 UTC, ljflores requested changes
Hey @gaord can you fix the commit titles so they align with https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title?

2023-10-31 08:56 UTC, NitzanMordhai commented
Rados review : https://tracker.ceph.com/projects/rados/wiki/MAIN#httpspulpitocephcomyuriw-2023-10-30_153436-rados-wip-yuri10-testing-2023-10-27-0804-distro-default-smithi

2023-10-31 15:31 UTC, yuriw commented
jenkins test windows

2023-10-31 15:31 UTC, yuriw commented
jenkins test make check

2023-10-31 15:33 UTC, yuriw commented
@gaord this was tested and ready for merge after checks passed and comments resolved
ref: https://trello.com/c/IdHRIj6u

2023-10-31 15:33 UTC, ljflores commented
> Hey @gaord can you fix the commit titles so they align with https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title?

@gaord this is the only thing missing; when this is fixed, the PR can be merged.

2023-12-04 09:28 UTC, gaord commented
> > Hey @gaord can you fix the commit titles so they align with https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title?
> 
> @gaord this is the only thing missing; when this is fixed, the PR can be merged.

missed this message among lots of others.  What shall the title look like? would like to make a push, not clear what to change, however. Thanks.
@ljflores

2024-03-04 18:01 UTC, closed without merging