osd/scrub: fix the handling of interval changes
ceph/ceph pull request #49959
Opened 2023-02-01 11:21 UTC by ronen-fr

Separating and clarifying the handling of interval termination, new interval starting, and configuration changes:

A primary PG now registers with its OSD for scrubbing only when fully activated: on_pg_activate() called from PG::on_activate();

When the interval ends, the PG is removed from the OSD queue by stop_active_scrubs(), called from start_peering_interval().

Configuration changes are still handled by update_scrub_job().

Some calls to publish_stats were removed, as publish_stats expects a stable PG state, and that state is not synchronized with the scrubber operation.

Signed-off-by: Ronen Friedman <rfriedma@redhat.com>

2023-02-02 06:01 UTC, athanatos requested changes
Seems reasonable structurally, see my comments.

This PR's single commit seems to contain several orthogonal changes.  In order to review it, I needed to split it into smaller atomic commits.  https://github.com/athanatos/ceph/tree/sjust/wip-scrub-interval-pr-49959 has those commits -- please split up this PR in a similar way.  In the future, it would really expedite review if you'd split up your PRs in a similar manner.

2023-02-02 07:39 UTC, ronen-fr commented on src/osd/PeeringState.h
> +    virtual void stop_active_scrubs() = 0;
I fully accept your 1'st comment. Moved stop_active_scrubs() call to PG::on_new_interval().
Re both comments: the intention here is to separate the handling of a change of interval into two parts: stopping what the scrubber was doing in the prev interval as one step, executed early on the interval transition, and a separate handling of "we have a new primary with its updated actset, which should be queued for scrubbing" - which should only be called when the PG is really ready.

The old code handled both at the same time (and the same function), which:
- caused multiple aborted attempts to "let's start scrubb'in" during new interval peering (had to be restarted, for example, each time a replica was acked and joined), and
- was confusing, and
- was even more confusing when I mixed it with 'history/conf' changes, that should only affect the scheduling of the next scrub.

That is why I maintain the separate names for the separate stages.
(and why I originally placed a direct call to stop_active_scrubs() in the peering-state code: I wanted to guarantee that that code is always executed early in the process.)

2023-02-02 07:42 UTC, ronen-fr commented on src/osd/scrubber/pg_scrubber.cc
> -  m_no_reply.reset();
Not really - it was copied from a separate PR. But it's hard to test this PR without it, as the OSDs crash.
Will move it to a separate commit, to be rmed once that other PR is merged.

2023-02-02 09:44 UTC, ronen-fr commented on src/osd/scrubber/pg_scrubber.cc
> +  if (m_fsm->is_active_replica()) {
the full_reset event is always effective, regardless of the FSM state (as it was meant
as a way to guarantee reset). Note the next line, which I do not want to call unless
active as replica. I could have used a new event, and moved the replica_handling_done()
to the FSM reactions, but (for me at least) the added code would have just made the logic
less clear.

2023-02-02 19:59 UTC, athanatos commented on src/osd/PeeringState.h
> +    virtual void stop_active_scrubs() = 0;
Ah, I was unclear.   I'd expect to see two scrubber side methods: one for when an interval ends and another for when the pg goes active.  I think you've already got the one for when the pg goes active, though.

2023-02-02 20:37 UTC, ronen-fr commented on src/osd/scrubber/pg_scrubber.cc
> -  m_no_reply.reset();
Not directly - but I was unable to test the PR without this fix.
Moved into a separate commit.

2023-02-02 20:37 UTC, ronen-fr commented on src/osd/scrubber/pg_scrubber.cc
> +    dout(10) << __func__ << " !!! primary but not scheduled! " << dendl;
For now - left this change out of the PR

2023-02-02 20:38 UTC, ronen-fr commented
@athanatos thanks for the work invested, especially re the commit splits

2023-02-08 09:53 UTC, ronen-fr commented on src/osd/scrubber/pg_scrubber.cc
> -  m_no_reply.reset();
@athanatos : yes - that was the failed scenario. Checking what you said in the last sentence.

2023-02-09 21:31 UTC, athanatos commented on src/osd/scrubber/pg_scrubber.cc
> -      scrub_clear_state();
By "a message carrying the request to be reserved by a primary was queued", do you mean the time the message spends between being queued via the messenger Dispatcher interface and when it gets processed by the PG and and scrubber?  Why is that important?

2023-02-14 02:03 UTC, athanatos commented on src/osd/scrubber/pg_scrubber.cc
> -  m_no_reply.reset();
I'm now less sure about this diagnosis.  SafeTimer can optionally either hold the lock while calling callbacks or not.  There's a boolean param passed to the constructor which governs this behavior -- safe_callbacks.  sleep_timer specifically seems to be constructed with safe_callbacks set to false, so locking OSDService::sleep_lock shouldn't be a problem.

Can you link to the tracker id?

2023-02-14 06:47 UTC, athanatos commented on src/osd/scrubber/pg_scrubber.cc
> -      scrub_clear_state();
@ronen-fr I think it's worth mapping these resources onto the state machine.  I've started working on a branch https://github.com/athanatos/ceph/tree/sjust/wip-scrub-interval-pr-49959-2 which does that.  I'm still working on it, so it's likely got errors.

2023-09-17 17:01 UTC, closed without merging