quincy: cephfs-top: Handle `METRIC_TYPE_NONE` fields for sorting
ceph/ceph pull request #50595
Opened 2023-03-20 11:19 UTC by neesingh-rh

backport tracker: https://tracker.ceph.com/issues/58985

---

backport of https://github.com/ceph/ceph/pull/50195
parent tracker: https://tracker.ceph.com/issues/58814

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2023-05-24 11:44 UTC, joscollin requested changes
This should be rebased after we merge https://github.com/ceph/ceph/pull/50717. So there won't be conflicts.

EDIT: r/rebased/backported only

2023-06-08 23:45 UTC, joscollin commented
@neesingh-rh Reset your branch `wip-58985-quincy` and cherry-pick `4626cb5fb1141c38acd4b114ad4562bd14fa7aad` once again. There shouldn't be any conflicts now.

2023-06-14 12:15 UTC, neesingh-rh commented
Rebased!!

2023-06-15 05:43 UTC, joscollin approved these changes

2023-07-25 10:17 UTC, vshankar approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#25-July-2023

2023-07-25 15:08 UTC, merged