cephfs-top: fix version check
ceph/ceph pull request #51224
Opened 2023-04-26 06:04 UTC by joscollin

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-04-26 08:21 UTC, joscollin commented
jenkins test windows

2023-04-26 09:29 UTC, joscollin commented
jenkins test windows

2023-04-26 12:22 UTC, joscollin commented
jenkins build docs

2023-04-26 12:22 UTC, joscollin commented
jenkins test api

2023-04-26 12:23 UTC, joscollin commented
jenkins test docs

2023-04-26 12:24 UTC, joscollin commented
jenkins test make check arm64

2023-04-26 12:40 UTC, joscollin commented
jenkins test make check arm64

2023-04-26 14:17 UTC, vshankar requested changes

2023-04-27 04:46 UTC, joscollin commented on src/tools/cephfs/top/CMakeLists.txt
> +find_package(Python3 ${MINIMUM_COMPATIBLE_VERSION} REQUIRED
Is that a stricter version check? As I checked, anything above `3.6.0` should pass this check. I'm not using `EXACT` here.

2023-04-27 05:53 UTC, vshankar commented on src/tools/cephfs/top/CMakeLists.txt
> +find_package(Python3 ${MINIMUM_COMPATIBLE_VERSION} REQUIRED
Stricter as compared to the top-level CMake check for Python >3

2023-04-27 08:43 UTC, joscollin commented on src/tools/cephfs/top/CMakeLists.txt
> +find_package(Python3 ${MINIMUM_COMPATIBLE_VERSION} REQUIRED
updated

2023-04-28 04:43 UTC, vshankar commented
jenkins retest this please

2023-04-28 07:21 UTC, vshankar commented
make check failure is

> ERROR: Cannot install -r requirements.txt (line 3) and kubernetes because these package versions have conflicting dependencies.

what broke that now? :/

2023-04-28 07:27 UTC, joscollin commented
> make check failure is
> 
> > ERROR: Cannot install -r requirements.txt (line 3) and kubernetes because these package versions have conflicting dependencies.
> 
> what broke that now? :/

The same error comes for other PRs also, not specific to this one.

2023-04-28 23:35 UTC, joscollin commented
jenkins test make check

2023-05-02 04:11 UTC, joscollin commented
jenkins test make check

2023-05-03 12:02 UTC, vshankar commented
Builds are fine in shaman: https://shaman.ceph.com/builds/ceph/wip-vshankar-testing-20230503.090416/

@petrutlucian94 @dmick PTAL at the changes.

2023-05-03 12:05 UTC, petrutlucian94 commented
looks good to me

2023-05-04 12:55 UTC, merged