mgr/dashboard: add 'omit_usage' query param to dashboard api 'get rbd' endpoint
ceph/ceph pull request #51294
Opened 2023-04-30 10:57 UTC by cfsnyder

Allows RBD info to be retrieved without getting associated usage info. This can be useful for large RBDs where the process of gathering such usage info is sometimes very slow.

Fixes: https://tracker.ceph.com/issues/59588

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-05-02 05:33 UTC, nizamial09 commented
thanks @cfsnyder the [make check](https://jenkins.ceph.com/job/ceph-pull-requests/114504/testReport/junit/projectroot.src.pybind.mgr/dashboard/run_tox_mgr_dashboard_openapi/) and [api tests](https://jenkins.ceph.com/job/ceph-api/54660/) are failing. seems to be related to the PR.

probably the make check can be fixed by [regenerating](https://docs.ceph.com/en/latest/dev/developer_guide/dash-devel/#rest-api-documentation) the openapi doc.
`tox -e openapi-fix` inside the dashboard folder.
but the api tests needs to be looked into.

2023-05-08 09:35 UTC, cfsnyder commented
jenkins retest this please

2023-05-08 12:23 UTC, cfsnyder commented
@nizamial09 when I run 'tox -e openapi-fix' on my machine, everything is green and there don't seem to be any changes to files tracked in git. Am I missing something?

2023-05-08 12:45 UTC, nizamial09 commented
> @nizamial09 when I run 'tox -e openapi-fix' on my machine, everything is green and there don't seem to be any changes to files tracked in git. Am I missing something?

@cfsnyder I hope you are running the command from `src/pybind/mgr/dashboard` folder. Because it should generate a new `openapi.yml` spec. I have to run it with a sudo command, but I think its just my local issue.

2023-05-26 18:42 UTC, cfsnyder commented
Updated @nizamial09. I'm not sure what was going on but after running on a fresh clone of the project and in a fresh venv, it worked.

2023-05-29 11:04 UTC, pereman2 requested changes
```
dashboard/controllers/rbd.py:181: error: Missing positional argument "omit_usage" in call to "get_image" of "RbdService"
```

2023-05-30 20:04 UTC, cfsnyder commented
jenkins test make check

2023-05-31 05:28 UTC, nizamial09 approved these changes

2023-06-05 20:15 UTC, merged