doc: update multisite doc
ceph/ceph pull request #51392
Opened 2023-05-08 13:57 UTC by parth-gr

cmd for getting zone group was spelled incorrectly Updated to rdosgw-admin

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-05-08 14:00 UTC, cbodley requested changes

2023-05-08 14:00 UTC, cbodley commented on doc/radosgw/multisite.rst
> +   rdosgw-admin zonegroup get [--rgw-zonegroup=<zonegroup>]
radosgw-admin

2023-05-08 14:05 UTC, cbodley approved these changes

2023-05-08 14:06 UTC, thotz approved these changes

2023-05-09 02:37 UTC, zdover23 commented
Reviewed-by:  Jiffin Tony Thottan <jthottan@redhat.com>
Reviewed-by:  Casey Bodley <cbodley@redhat.com>
Reviewed-by:  Zac Dover <zac.dover@proton.me>

2023-05-09 02:37 UTC, merged

2023-05-09 02:40 UTC, zdover23 commented
https://github.com/ceph/ceph/pull/51400 - Reef backport
https://github.com/ceph/ceph/pull/51401 - Quincy backport
https://github.com/ceph/ceph/pull/51402 - Pacific backport