osd/scrub: use one single queue priority for all transactions
ceph/ceph pull request #51426
Opened 2023-05-10 14:24 UTC by ronen-fr

initiated by scrub_compare_maps()

* using a single queue priority hint for all transactions initiated within scrub_compare_maps();
* low priority for queue_scrub_after_repair()

A follow-up PR will introduce more changes to scrub events queue priorities. This change is a minimal & back-portable bug fix.

Fixes: https://tracker.ceph.com/issues/59049

2023-05-11 00:07 UTC, athanatos commented
@ronen-fr It's not obvious to me why this bug started popping up in the last few weeks.  Have you worked out which commit caused it?

2023-05-11 04:36 UTC, athanatos commented
How about we do something like https://github.com/athanatos/ceph/tree/sjust/wip-scrub-59049 and just make MapsCompared synchronous?  Relying on event ordering through the scheduler for concurrent events is pretty brittle -- are there any other cases where scrub can have more than one asynchronous event outstanding where we rely on ordering?

2023-05-11 04:37 UTC, NitzanMordhai approved these changes
LGTM

2023-05-11 05:07 UTC, athanatos requested changes
(See question above)

2023-05-11 05:39 UTC, ronen-fr commented
@athanatos, 
> How about we do something like https://github.com/athanatos/ceph/tree/sjust/wip-scrub-59049 and just make MapsCompared synchronous? Relying on event ordering through the scheduler for concurrent events is pretty brittle -- are there any other cases where scrub can have more than one asynchronous event outstanding where we rely on ordering?

That's indeed easier and clearer, and was how I did things at some point in the past. I have modified it
to be async when I was working on Crimson adjustments. To tell the truth - I still do not see how the original
flow can be made compatible with Crimson (apart from by using a separate Seastar thread, which I assume
is not what we want).

2023-05-11 12:14 UTC, ronen-fr commented
> @athanatos,
...
see https://github.com/ceph/ceph/commit/c257c2e108decb21f479d005e792fccc58a778fa
as to where I changed to asynch

2023-05-11 12:19 UTC, ronen-fr commented
> @ronen-fr It's not obvious to me why this bug started popping up in the last few weeks. Have you worked out which commit caused it?

Turned out there was no such change lately (the low priority for the 'maps compared' event is 2 years old).
Aishwarya suggests that the problem was there for long (and, I might add, was hidden under the other old bug that
caused bogus update messages to be sent), and the recent introduction of the mclock testing value for the
cutoff - which created a major time separation between low & high priority scrub messages - made it frequent.

2023-05-11 18:58 UTC, athanatos commented
@ronen-fr Agreed, I'm running the branch I mentioned above through tests.  As for crimson, making this event synchronous doesn't really matter.  I mostly know what refactors I'll need to do to make it work.

2023-05-17 14:01 UTC, ronen-fr commented
Will probably be closed soon, as the original bug is solved by Sam's PR#51498

2023-10-27 10:01 UTC, closed without merging