pacific: qa: add subvolume option flavors
ceph/ceph pull request #51509
Opened 2023-05-16 07:28 UTC by mchangir

backport tracker: https://tracker.ceph.com/issues/59202

---

backport of https://github.com/ceph/ceph/pull/45556
parent tracker: https://tracker.ceph.com/issues/54317

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2023-07-25 10:08 UTC, vshankar commented
jenkins test dashboard cephadm

2023-07-25 10:09 UTC, vshankar commented
jenkins test dashboard cephadm

2023-08-01 05:16 UTC, vshankar commented on qa/tasks/cephfs/fuse_mount.py
> +        fuse_cmd = [self._mount_bin, self.hostfs_mntpt]
@mchangir This is causing failures such as - https://pulpito.ceph.com/yuriw-2023-07-27_03:42:08-fs-wip-yuri10-testing-2023-07-26-0858-pacific-distro-default-smithi/7354247

PTAL

2023-08-01 05:16 UTC, vshankar requested changes
This change is causing failures such as

```
'FuseMount' object has no attribute '_mount_bin'
```

https://pulpito.ceph.com/yuriw-2023-07-27_03:42:08-fs-wip-yuri10-testing-2023-07-26-0858-pacific-distro-default-smithi/


<br class="Apple-interchange-newline">

2023-08-02 06:13 UTC, mchangir commented
> This change is causing failures such as
> 
> ```
> 'FuseMount' object has no attribute '_mount_bin'
> ```
> 
> https://pulpito.ceph.com/yuriw-2023-07-27_03:42:08-fs-wip-yuri10-testing-2023-07-26-0858-pacific-distro-default-smithi/

removed offending line;
host_mntpt was appended to the mount command later in the code;
this issue was created due to manual conflict resolution during backporting process;

2023-08-09 04:23 UTC, vshankar commented
jenkins retest this please

2023-08-09 04:25 UTC, vshankar commented
> > This change is causing failures such as
> > ```
> > 'FuseMount' object has no attribute '_mount_bin'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://pulpito.ceph.com/yuriw-2023-07-27_03:42:08-fs-wip-yuri10-testing-2023-07-26-0858-pacific-distro-default-smithi/
> 
> removed offending line; host_mntpt was appended to the mount command later in the code; this issue was created due to manual conflict resolution during backporting process;

I guess this is commit b9179f23db66f40f8bf90fea049c0a219a798bd3 that you mention. Could you explain the conflict itself in the commit message? That helps with reviewing.

2023-08-09 05:48 UTC, mchangir commented
> > > This change is causing failures such as
> > > ```
> > > 'FuseMount' object has no attribute '_mount_bin'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > https://pulpito.ceph.com/yuriw-2023-07-27_03:42:08-fs-wip-yuri10-testing-2023-07-26-0858-pacific-distro-default-smithi/
> > 
> > 
> > removed offending line; host_mntpt was appended to the mount command later in the code; this issue was created due to manual conflict resolution during backporting process;
> 
> I guess this is commit [b9179f2](https://github.com/ceph/ceph/commit/b9179f23db66f40f8bf90fea049c0a219a798bd3) that you mention. Could you explain the conflict itself in the commit message? That helps with reviewing.

added reason to the Conflicts section in the commit message

2023-08-17 22:03 UTC, ljflores commented
Rados approved: https://trello.com/c/qRJogcXu/1827-wip-yuri2-testing-2023-08-16-1142-pacific

2023-08-21 15:57 UTC, batrick approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/Pacific#2023-August-16-2

2023-08-21 16:03 UTC, mchangir commented
> @mchangir The PR description should have an explanation for where [qa: avoid explicit set to client mountpoint as "/"](https://github.com/ceph/ceph/pull/51509/commits/cf6f49b7a36795db7ec83a3c3baa99d613c1eb55) comes from. I see that now but I shouldn't need to trawl through the PR links to learn why.

ack

2023-08-21 16:05 UTC, yuriw commented
@mchangir pls fix and it's ready for merge
ref: https://trello.com/c/qRJogcXu

2023-08-22 04:18 UTC, vshankar approved these changes

2023-08-22 04:20 UTC, merged