rgw: fix http client relevant headers behavior
ceph/ceph pull request #51583
Opened 2023-05-19 06:02 UTC by mdw-at-linuxbox

In a containerized install with keystone; radosgw was caught redhanded in the act of attempting to validate a uesr supplied token with an empty admin token.  The problem turned out to be a bug that was never present upstream - but the problem was masked by debug behavior which considered all headers to be relevant causing the bug to go away.  This is classic noxious heisenbug behavior.

This fix:
/1/ debug behavior does not alter what are "relevant headers". /2/ debug behavior produces useful diagnostics for uninteresting headers. /3/ refactor some of the other logic in receive_headers, which was
    previously recalculating val_loc_s and val_loc_e twice.

Fixes: https://tracker.ceph.com/issues/61259

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-05-19 06:19 UTC, mdw-at-linuxbox commented
I've pushed a copy of this to ceph-ci
https://shaman.ceph.com/builds/ceph/mdw-main-http-header-2/
I expect this to build. but it should be run thru teuthology et al.

Testing the actual intent of this fix would be tricky.  One would almost have to introduce a bug elsewhere in the source to induce the heisenbug behavior...

2023-05-22 13:49 UTC, cbodley reviewed
what's the purpose of logging the uninteresting headers, if they're hidden from `RGWHTTPHeadersCollector`'s caller?

2023-05-22 13:49 UTC, cbodley commented on src/rgw/rgw_http_client.cc
> +    }
the `interesting` case below uses completely different logic to parse the header value. can you not reuse `val_loc_s` and `val_loc_e` here?

2023-05-25 15:13 UTC, ivancich requested changes
I didn't do an in-depth review, but since this PR came up during bug scrub I did take a peak and a few portions piqued my interest.

2023-05-25 15:13 UTC, ivancich commented on src/rgw/rgw_http_client.cc
> +      --hdl;
This logic seems unnecessarily convoluted. It also fails if header_line simply contains one newline character, as hdl, being an unsigned type, will contain a very large value (wrapping around from -1).

I think something along the lines of:
```
    auto hdl { header_line.length() };
    if (hdl > 0 && header_line[hdl-1] == '\n') {
        --hdl;
        if (hdl > 0 && header_line[hdl-1] == '\r') {
            --hdl;
        }
    }
```
would be much clearer to those following, even if you shift the first decrement into the second conditional.

2023-05-25 15:13 UTC, ivancich commented on src/rgw/rgw_http_client.cc
> +  bool interesting = relevant_headers.find(name) != relevant_headers.end();
So the next person coming through this code doesn't have to figure out what "interesting" means, would you consider a juicy comment explaining what's happening here and below?

2023-11-04 23:01 UTC, closed without merging