osd/OSD: cleanup OSDService::maybe_share_map()
ceph/ceph pull request #51667
Opened 2023-05-22 13:02 UTC by Matan-B

```
* avoid locking sent_epoch_lock twice

* add log message when osdmap is not newer than session's projected_epoch

* edit log messages

* rename last_sent_epoch to projected_epoch
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-05-24 15:02 UTC, ronen-fr commented on src/osd/OSD.cc
> +       __func__, con->get_peer_addr(),
"from to" ??

2023-05-24 15:05 UTC, ronen-fr commented on src/osd/OSD.cc
> +       __func__, con->get_peer_addr(),
apart from that: LGTM

2023-05-24 15:27 UTC, Matan-B commented on src/osd/OSD.cc
> +       __func__, con->get_peer_addr(),
Thanks!

2023-05-24 20:48 UTC, rzarzynski commented on src/osd/OSD.cc
> +  if (osdmap->get_epoch() <= session->last_sent_epoch) {
For the sake of explicitness: I'm assuming no locking in `get_epoch()`.

2023-05-24 20:48 UTC, rzarzynski commented on src/osd/OSD.cc
> +  const epoch_t send_from = session->last_sent_epoch;
:+1:

2023-05-24 20:48 UTC, rzarzynski commented on src/osd/OSD.cc
> +    session->sent_epoch_lock.unlock();
Would love to handle the unlocking with a scope guard.

2023-05-26 23:01 UTC, athanatos commented
Since we're touching this code, let's use a scope guard rather than explicitly locking and unlocking.

2023-05-26 23:03 UTC, athanatos requested changes
Looks reasonable to me otherwise.

2023-05-26 23:03 UTC, athanatos commented on src/osd/OSD.cc
> -  epoch_t last_sent_epoch = session->last_sent_epoch;
The commit message in this commit needs to be explicit about why this is allowed.  Invoking send_incremental_map doesn't wait until the replica actually receives the map, so marking last_epoch_sent prior to invoking it is just as correct.

2023-05-30 23:02 UTC, athanatos approved these changes
LGTM otherwise

2023-05-30 23:02 UTC, athanatos commented on src/osd/OSD.cc
> +  epoch_t send_from;
Initialize this to something.  If there's a constand for an invalid epoch use that.  Otherwise, 0.

2023-05-30 23:03 UTC, athanatos commented
Add needs-qa once the nit above is addressed.

2023-06-12 15:18 UTC, ljflores commented
Marking this as TESTED for now, but go ahead and re-add the "needs-qa" label as needed.

2023-06-21 20:48 UTC, ljflores commented
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcCcKXkHLe1789-wip-yuri3-testing-2023-06-19-1518

2023-06-21 21:12 UTC, merged