MOSDMap: osdmap bufferlist page aligned when MOSDMap::decode_payload
ceph/ceph pull request #51888
Opened 2023-06-02 07:41 UTC by jianwei1216

```
- unified osdmap blufferlist page alignment at the MOSDMap::decode_payload position can avoid modification omissions.
```

see also,
https://github.com/ceph/ceph/pull/51444

2023-06-06 00:54 UTC, jianwei1216 commented
@athanatos  please review, thank you!

2023-06-07 00:25 UTC, athanatos requested changes

2023-06-07 00:25 UTC, athanatos commented on src/messages/MOSDMap.h
> +      if (!bl.is_page_aligned()) {
Calling rebuild_page_aligned() on an aligned bufferlist appears to be a noop and about as expensive as calling is_page_aligned().  For an unaligned bufferlist, calling is_page_aligned() first is simply extra cost.  I think removing the is_page_aligned() guards will be both more performant and clearer.

2023-06-21 02:32 UTC, closed without merging

2023-06-21 06:29 UTC, jianwei1216 commented
Since the branch of jianwei1216/ceph switched from master to main, github has been generating pr and sending me emails of pr failure, so I recreated the repo of jianwei1216/ceph