mds: optionally forbid to use standby for another fs as last resort
ceph/ceph pull request #51942
Opened 2023-06-06 13:52 UTC by trociny

Fixes: https://tracker.ceph.com/issues/61599

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-06-06 14:01 UTC, trociny commented
Alternatively, instead of a config option we could use a fs option, something like `ceph fs set <fs_name> allow_another_fs_standby false`. @batrick @vshankar what do you think?

If we still want a config option then I am also not sure if `mds_allow_another_fs_standby` is a good name. The option should be set for mon while the `mds_` prefix suggests it is for mds. Then may be `mon_mds_allow_another_fs_standby`?

2023-06-06 15:21 UTC, batrick commented
> Alternatively, instead of a config option we could use a fs option, something like `ceph fs set <fs_name> allow_another_fs_standby false`. @batrick @vshankar what do you think?

This would be more appropriate as you may want different behavior for different FS.

2023-06-07 05:52 UTC, trociny commented
> This would be more appropriate as you may want different behavior for different FS.

That is what I would like more too. Thanks.

Then the next question is about naming and the default behaviour. Ideally I would like we don't allow standby for another fs by default and if one wants it they should set the fs flag with the command:
```
ceph fs set <fs> allow_another_fs_standby true
```
(an alternative flag name could be `allow_standby_for_another_fs` or may be you have some other idea for the name?)

But this would mean the previous behaviour would change after upgrade (and I would like to backport this to all supported branches) and users may not be happy. So a safer approach would be to add `refuse_another_fs_standby` (`refuse_standby_for_another_fs`) flag instead, which users are supposed to set if they want the new behaviour:
```
ceph fs set <fs> refuse_another_fs_standby true
```
I am using `allow_` and `refuse_` prefixes because I see we already have flags with these prefixes, still if you have a better idea about the flag name I would be glad to know.

So, what do you think? I would be fine with any solution that allowed to enable this somehow.

2023-06-07 15:51 UTC, batrick commented
I don't think we can change the default behavior. It's too surprising to users why standbys are not being promoted.

Name is good to me.

2023-06-23 05:16 UTC, vshankar commented
jenkins test api

2023-06-23 05:21 UTC, vshankar commented
@trociny Needs update to doc in doc/cephfs/standby.rst

... and just to clarify, the default behaviour is still what it is right now (monitor can choose any standby MDS)?

2023-06-24 07:38 UTC, trociny commented
updated to include the test and documentation change.

2023-06-25 07:44 UTC, trociny commented
Running on teuthology the fs suite with `--filter failover`, just to check that the modified `join_fs_last_resort` test works:

https://pulpito.ceph.com/trociny-2023-06-25_06:00:43-fs-wip-mgolub-testing-distro-default-smithi/

 All tests passed.

2023-06-27 12:11 UTC, vshankar commented
jenkins test api

2023-06-27 12:20 UTC, dparmar18 commented on doc/cephfs/standby.rst
> +``standby-replay`` daemons are always selected before other standbys.
```suggestion
.. note::
   Configuring MDS file system affinity does not guarantee that
   ``standby-replay`` daemons are always selected before other standbys.
```

2023-06-28 00:33 UTC, batrick requested changes
otherwise LGTM

2023-06-28 00:33 UTC, batrick commented on PendingReleaseNotes
> +Relevant tracker: https://tracker.ceph.com/issues/61599
```suggestion
* Introduced a new file system flag `refuse_standby_for_another_fs` that can be
set using the `fs set` command. This flag prevents using a standby for another
file system (join_fs = X) when standby for the current filesystem is not available.
Relevant tracker: https://tracker.ceph.com/issues/61599
```

2023-06-28 00:33 UTC, batrick commented on qa/tasks/cephfs/test_failover.py
> +        # Wait for the former active to reclaim its spot
Please make a separate, focused test.

2023-06-28 00:33 UTC, batrick commented on src/mon/FSCommands.cc
> +          ss << "forbade to use standby for another fs";
```suggestion
          ss << "set to refuse standby for another fs";
```

2023-06-28 00:33 UTC, batrick commented on src/mon/FSCommands.cc
> +          ss << "to use standby for another fs is already forbidden";
ditto

2023-07-03 10:54 UTC, vshankar commented
> otherwise LGTM

@trociny I'll include this in my integration run this week. Could you finish up the comments?

2023-07-03 17:23 UTC, trociny commented
> @trociny I'll include this in my integration run this week. Could you finish up the comments?

@vshankar I am on vacation right now. Actually, I think I addressed @batrick's comments but I have not had a chance to try the updated test so I was reluctant to push it. Anyway I pushed it right now though it is still not tested.

2023-07-04 05:58 UTC, trociny commented
The updated tests seem to work:

https://pulpito.ceph.com/trociny-2023-07-04_04:45:48-fs-wip-mgolub-testing-distro-default-smithi/

Note, wip-mgolub-tesing branch has different sha than wip-61599 just because I had to rebase it to force shaman build (the previous build failed for some reason).

2023-07-04 06:12 UTC, vshankar commented
> > @trociny I'll include this in my integration run this week. Could you finish up the comments?
> 
> @vshankar I am on vacation right now. Actually, I think I addressed @batrick's comments but I have not had a chance to try the updated test so I was reluctant to push it. Anyway I pushed it right now though it is still not tested.

Sure, no problem. I'll have a look. Thx!

2023-07-12 11:42 UTC, vshankar commented
jenkins retest this please

2023-07-12 12:50 UTC, batrick approved these changes

2023-07-12 14:00 UTC, rishabh-d-dave commented
https://jenkins.ceph.com/job/ceph-api/58129/

2023-07-12 14:00 UTC, rishabh-d-dave commented
jenkins test api

2023-07-12 14:01 UTC, rishabh-d-dave commented
I'll pick this PR for integration testing in few days.

2023-07-12 15:15 UTC, dparmar18 commented on qa/tasks/cephfs/test_failover.py
> +            return len(ranks) > 0 and ranks[0]['name'] not in standbys
this is same as in `test_join_fs_last_resort`. This helper can be moved before the test cases start; thus removing redundancy.

2023-07-13 13:29 UTC, dparmar18 commented on src/mds/FSMap.cc
> +	       !fs.mds_map.test_flag(CEPH_MDSMAP_REFUSE_STANDBY_FOR_ANOTHER_FS)) {
usage of dot operator looks correct

2023-07-24 16:16 UTC, rishabh-d-dave approved these changes
Testing was successful - https://tracker.ceph.com/projects/cephfs/wiki/Main#24-Jul-2024

2023-07-24 16:18 UTC, rishabh-d-dave commented
The PR is ready for merge but not until Ceph API tests also passes. I'll merge after as soon as it passes.

2023-07-24 16:18 UTC, rishabh-d-dave commented
jenkins test api

2023-07-24 16:18 UTC, rishabh-d-dave commented
https://jenkins.ceph.com/job/ceph-windows-pull-requests/25605/

2023-07-24 16:19 UTC, rishabh-d-dave commented
jenkins test windows

2023-07-24 16:20 UTC, rishabh-d-dave commented
https://jenkins.ceph.com/job/ceph-pull-requests-arm64/43130/

2023-07-25 08:21 UTC, rishabh-d-dave commented
https://jenkins.ceph.com/job/ceph-api/58731/

2023-07-25 08:21 UTC, rishabh-d-dave commented
jenkins test api

2023-07-25 12:01 UTC, rishabh-d-dave commented
https://jenkins.ceph.com/job/ceph-api/58774/

2023-07-25 12:01 UTC, rishabh-d-dave commented
jenkins test api

2023-07-26 09:37 UTC, rishabh-d-dave commented
https://jenkins.ceph.com/job/ceph-api/58801/

2023-07-26 09:39 UTC, vshankar commented
@rishabh-d-dave 

```
2023-07-25 17:41:25,714.714 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 712, in 
2023-07-25 17:41:25,714.714 INFO:__main__:    _validate_json(val[key], sub_schema, path + [key])
2023-07-25 17:41:25,714.714 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 710, in _validate_json
2023-07-25 17:41:25,714.714 INFO:__main__:    raise _ValError('unknown keys: {}'.format(unknown_keys), path)
2023-07-25 17:41:25,714.714 INFO:__main__:tasks.mgr.dashboard.helper._ValError: In `input['fs_map']['filesystems'][0]['mdsmap']['flags_state']`: unknown keys: {'refuse_standby_for_another_fs'}
2023-07-25 17:41:25,714.714 INFO:__main__:
2023-07-25 17:41:25,714.714 INFO:__main__:During handling of the above exception, another exception occurred:
```

The new option `refuse_standby_for_another_fs` needs to be updated in some dashboard test.

2023-07-26 10:18 UTC, trociny commented
> The new option refuse_standby_for_another_fs needs to be updated in some dashboard test.

@vshankar thanks, I will update it and add the commit here.

2023-07-27 05:53 UTC, trociny commented
@rishabh-d-dave @vshankar I believe the dashboard tests are fixed now (the ceph API tests passed).

2023-07-27 11:26 UTC, rishabh-d-dave commented
> @rishabh-d-dave
> 
> ```
> 2023-07-25 17:41:25,714.714 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 712, in 
> 2023-07-25 17:41:25,714.714 INFO:__main__:    _validate_json(val[key], sub_schema, path + [key])
> 2023-07-25 17:41:25,714.714 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 710, in _validate_json
> 2023-07-25 17:41:25,714.714 INFO:__main__:    raise _ValError('unknown keys: {}'.format(unknown_keys), path)
> 2023-07-25 17:41:25,714.714 INFO:__main__:tasks.mgr.dashboard.helper._ValError: In `input['fs_map']['filesystems'][0]['mdsmap']['flags_state']`: unknown keys: {'refuse_standby_for_another_fs'}
> 2023-07-25 17:41:25,714.714 INFO:__main__:
> 2023-07-25 17:41:25,714.714 INFO:__main__:During handling of the above exception, another exception occurred:
> ```
> 
> The new option `refuse_standby_for_another_fs` needs to be updated in some dashboard test.

@trociny The CephFS integration tests ran fine but the CI job "Ceph API tests" fails consistently. Please fix this issue so that this PR can a move step towards getting merged.

2023-07-27 12:05 UTC, rishabh-d-dave commented
> @rishabh-d-dave @vshankar I believe the dashboard tests are fixed now (the ceph API tests passed).

Yes, dashboard tests are fixed. We can merge this PR but I guess its better to get an approval from Dashboard team as well. I've messaged Ernesto on Slack requesting review for this PR.

2023-07-27 16:46 UTC, epuertat approved these changes
LGT @ceph/dashboard!

2023-08-24 16:20 UTC, rishabh-d-dave commented
@vshankar 
> @rishabh-d-dave good to merge?

I am waiting to discuss some failures with you before merging this PR.

2023-08-24 16:46 UTC, vshankar commented
> @vshankar 
> > @rishabh-d-dave good to merge?
> 
> I am waiting to discuss some failures with you before merging this PR.

According to https://github.com/ceph/ceph/pull/51942#issuecomment-1653481476 this is ready to merge, isn't it?

2023-08-24 19:45 UTC, rishabh-d-dave commented
> > @vshankar
> > > @rishabh-d-dave good to merge?
> > 
> > 
> > I am waiting to discuss some failures with you before merging this PR.
> 
> According to [#51942 (comment)](https://github.com/ceph/ceph/pull/51942#issuecomment-1653481476) this is ready to merge, isn't it?

Right but since there were too many re-runs, I included it in one of batches for testing again.

2023-08-25 12:01 UTC, vshankar commented
> Right but since there were too many re-runs, I included it in one of batches for testing again.

As discussed - pending RCA for two test failures before merging.

2023-09-06 14:51 UTC, rishabh-d-dave approved these changes
CephFS integration tests ran fine - https://tracker.ceph.com/projects/cephfs/wiki/Main#6-Sep-2023.

2023-09-06 14:56 UTC, merged

2023-09-06 19:50 UTC, ljflores commented
Hey @rishabh-d-dave, I think this caused a compilation failure. See https://tracker.ceph.com/issues/62729 for details

2023-09-06 19:54 UTC, ljflores commented
@trociny FYI