osd/TrackedOp: Redefine TrackedOp perfcounter
ceph/ceph pull request #52068
Opened 2023-06-15 04:33 UTC by YiteGu

1. TrackedOp is a common class, mon and mds alse use it.
2. Set prio level of l_trackedop_slow_op_count to PRIO_USEFUL, we can get change of slow op of daemon from prometheus metrics, it's very interesting

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-06-15 04:36 UTC, YiteGu commented
```
# ceph -c ceph.conf daemon asok/osd.0.asok perf dump | grep -A 5 trackedop
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
    "trackedop": {
        "slow_ops_count": 0
    }
}
# ceph -c ceph.conf daemon asok/mon.a.asok perf dump | grep -A 5 trackedop
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
    "trackedop": {
        "slow_ops_count": 0
    }
}
# ./ceph -c ceph.conf daemon asok/mds.c.asok perf dump | grep -A 5 trackedop
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
    "trackedop": {
        "slow_ops_count": 0
    }
}
```

2023-06-15 04:38 UTC, YiteGu commented
from metrics:
```
# HELP ceph_trackedop_slow_ops_count Number of operations taking over ten second
# TYPE ceph_trackedop_slow_ops_count counter
ceph_trackedop_slow_ops_count{ceph_daemon="mds.c"} 0.0
ceph_trackedop_slow_ops_count{ceph_daemon="mon.a"} 0.0
ceph_trackedop_slow_ops_count{ceph_daemon="mon.b"} 0.0
ceph_trackedop_slow_ops_count{ceph_daemon="mon.c"} 0.0
ceph_trackedop_slow_ops_count{ceph_daemon="osd.0"} 0.0
ceph_trackedop_slow_ops_count{ceph_daemon="osd.1"} 0.0
ceph_trackedop_slow_ops_count{ceph_daemon="osd.2"} 0.0
```

2023-06-15 04:41 UTC, YiteGu commented
@rzarzynski @athanatos have a code review, urgent

2023-06-20 18:27 UTC, athanatos commented
So, the main change here is to set the priority for l_osd_slow_op_count to PRIO_USEFUL.  Seems reasonable to me. @rzarzynski @batrick Does this seem reasonable to you?

2023-06-20 18:28 UTC, athanatos approved these changes

2023-06-20 19:44 UTC, batrick requested changes
Please rewrite commit title as: `common/TrackedOp: rename and raise prio of slow op perfcounter`

2023-06-20 19:44 UTC, batrick commented
> So, the main change here is to set the priority for l_osd_slow_op_count to PRIO_USEFUL. Seems reasonable to me. @rzarzynski @batrick Does this seem reasonable to you?

Yup!

2023-06-20 20:04 UTC, rzarzynski approved these changes
LGTM assuming the Patrick's review gets addressed.

2023-06-20 20:04 UTC, rzarzynski commented on src/common/TrackedOp.h
> +    b.set_prio_default(PerfCountersBuilder::PRIO_USEFUL);
Yeah, I think there shouldn't be too much of worries about the renaming as this counter was `PRIO_DEBUGONLY` only.

```cpp
class PerfCountersBuilder
{
public:
  PerfCountersBuilder(CephContext *cct, const std::string &name,
                    int first, int last);
...
  // prio values: higher is better, and higher values get included in
  // 'ceph daemonperf' (and similar) results.
  // Use of priorities enables us to add large numbers of counters
  // internally without necessarily overwhelming consumers.
  enum {
    PRIO_CRITICAL = 10,
    // 'interesting' is the default threshold for `daemonperf` output
    PRIO_INTERESTING = 8,
    // `useful` is the default threshold for transmission to ceph-mgr
    // and inclusion in prometheus/influxdb plugin output
    PRIO_USEFUL = 5,
    PRIO_UNINTERESTING = 2,
    PRIO_DEBUGONLY = 0,
  };
...
  void set_prio_default(int prio_)
  {
    prio_default = prio_;
  }
...
  int prio_default = 0;
};

2023-06-21 01:23 UTC, YiteGu commented
@batrick Rewrite commit title done

2023-06-21 01:53 UTC, batrick approved these changes

2023-08-01 07:11 UTC, YiteGu commented
results show
<img width="910" alt="截屏2023-08-01 下午1 56 15" src="https://github.com/ceph/ceph/assets/33341035/c98d5723-9bb0-4785-8b03-8ed1877fe410">

2023-10-31 02:19 UTC, YiteGu commented
Hi @ljflores this pr need testing

2024-07-01 03:30 UTC, YiteGu commented
@rzarzynski I think we need to fix this problem, otherwise, the slow op of mon and mds will be represented by the keyword osd, this will cause ambiguity

2024-07-22 16:41 UTC, batrick commented
ping @ljflores @rzarzynski @yuriw please QA.

2024-07-23 07:02 UTC, rzarzynski commented
jenkins test make check

2024-07-23 07:03 UTC, rzarzynski commented
`needs-qa` is already assigned.

@yuriw, @ljflores: let's take this into the very next QA batch. Pinging also in Slack.

2024-07-23 10:59 UTC, rzarzynski commented
Looks unrelated at first glance:

```
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/bin/nodeenv", line 8, in 
    sys.exit(main())
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/lib/python3.10/site-packages/nodeenv.py", line 1130, in main
    create_environment(env_dir, args)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/lib/python3.10/site-packages/nodeenv.py", line 1006, in create_environment
    install_node(env_dir, src_dir, args)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/lib/python3.10/site-packages/nodeenv.py", line 763, in install_node
    install_node_wrapped(env_dir, src_dir, args)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/lib/python3.10/site-packages/nodeenv.py", line 786, in install_node_wrapped
    download_node_src(node_url, src_dir, args)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/lib/python3.10/site-packages/nodeenv.py", line 618, in download_node_src
    dl_contents = _download_node_file(node_url)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/lib/python3.10/site-packages/nodeenv.py", line 610, in _download_node_file
    raise e
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/lib/python3.10/site-packages/nodeenv.py", line 602, in _download_node_file
    return io.BytesIO(urlopen(node_url).read())
  File "/usr/lib/python3.10/http/client.py", line 482, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.10/http/client.py", line 633, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(12623872 bytes read, 34097368 more expected)
```

2024-07-23 10:59 UTC, rzarzynski commented
jenkins test make check

2024-07-31 05:31 UTC, ljflores commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues67090

2024-07-31 14:30 UTC, merged