mgr/dashboard: cluster upgrade start UI
ceph/ceph pull request #52493
Opened 2023-07-17 18:15 UTC by avanthakkar

Fixes: https://tracker.ceph.com/issues/61928
Signed-off-by: avanthakkar <avanjohn@gmail.com>

[Screencast from 2023-07-17 23-17-50.webm](https://github.com/ceph/ceph/assets/23611106/f776fcaf-a02f-433a-8f86-59df5f568bdb)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-07-18 08:11 UTC, cloudbehl commented
Some Nits:

Are we checking two times if the update is available? once when we load the upgrade page and once we are opening the modal for upgrade, can't we just pass data from parent component to child and use it?

Also set the default height and width of modal to size you think it will require.

2023-07-18 10:59 UTC, avanthakkar commented
> Some Nits:
> 
> Are we checking two times if the update is available? once when we load the upgrade page and once we are opening the modal for upgrade, can't we just pass data from parent component to child and use it?
> 
> Also set the default height and width of modal to size you think it will require.

We need to subscribe again to see which versions are available. So probably I can update the message as 
`Fetching the available versions`? Not sure if I can @Input these versions. wdyt? @nizamial09 
Sure will do some resizing for text and modal.

2023-07-19 07:54 UTC, nizamial09 requested changes
I've made some modifications in the review. If you follow that, you can avoid the duplicated api call. 

Also the `upgrade-start` component you created should really be `upgrade-form` component and it should be inside `upgrade/upgrade-form` folder rather than existing in the same folder as `upgrade`.

Also it is missing the unit-test file. You should also create that and push it.

2023-07-19 07:54 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-start-modal-component.ts
> +    private fb: CdFormBuilder,
don't need this
```suggestion
```

2023-07-19 07:54 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-start-modal-component.ts
> +    this.upgradeInfoError$ = this.upgradeInfo$?.pipe(
we don't need to do this again. We can pass the versions from the upgrade.component where we are actually doing the subscription. so on this file you can introduce a variable called `versions` to catch the params that are send from upgrade component.

2023-07-19 07:54 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-start-modal-component.ts
> +  }
```suggestion
    this.upgradeForm = new CdFormGroup({
      availableVersions: new FormControl(null, [Validators.required])
    });
  }
```

2023-07-19 07:54 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade.component.ts
> +    this.modalRef = this.modalService.show(UpgradeStartModalComponent);
```suggestion
    this.modalRef = this.modalService.show(UpgradeStartModalComponent, {
        versions: this.upgradableVersions
    });
```

you have to get the `upgradableVersions` using a `pipe` from above where the `upgradeInfo$` is instanitated.

```
this.upgradeInfo$ = this.upgradeService.list().pipe(
      tap((upgradeInfo: UpgradeInfoInterface) => this.upgradableVersions = upgradeInfo.versions));
 
 ```

2023-07-19 07:54 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts
> +    this.UPGRADE = $localize`Start Upgrade`;
```suggestion
    this.START_UPGRADE = $localize`Start Upgrade`;
```

2023-07-19 07:54 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-start-modal-component.html
> +                *ngIf="upgradeInfo$ | async as upgradeInfo; else checkUpgrade">
```suggestion
```

2023-07-19 07:54 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/upgrade/upgrade-start-modal-component.html
> +                  *ngIf="upgradeForm.showError('availableVersions', upgradeForm, 'required')"
```suggestion
                  *ngIf="upgradeForm.showError('availableVersions', formDir, 'required')"
```

2023-07-20 11:30 UTC, cloudbehl commented
The version IMO needs to be in ascending order. 

![image](https://github.com/ceph/ceph/assets/6695156/a74cd663-1143-4904-b774-04ddddbb464d)

2023-07-24 10:10 UTC, avanthakkar commented
> The version IMO needs to be in ascending order.
> 
> ![image](https://user-images.githubusercontent.com/6695156/254869286-a74cd663-1143-4904-b774-04ddddbb464d.png)

Done!

2023-07-24 12:51 UTC, avanthakkar commented
jenkins test make check

2023-07-25 07:21 UTC, cloudbehl commented
Nit: `New versions` -> `New version`

2023-07-25 10:57 UTC, nizamial09 commented
jenkins test dashboard cephadm

2023-07-25 10:58 UTC, nizamial09 approved these changes

2023-07-27 07:23 UTC, Pegonzal approved these changes
Hey @avanthakkar , overall looks good to me and is working so I'll approve it!

But I agree with Nizam's comment which hasn't been taking into account yet, I think this should be done:

>
>Also the upgrade-start component you created should really be upgrade-form component and it should be inside upgrade/upgrade-form folder rather than existing in the same folder as upgrade.
>
>Also it is missing the unit-test file. You should also create that and push it.

2023-07-27 09:58 UTC, avanthakkar commented
> Hey @avanthakkar , overall looks good to me and is working so I'll approve it!
> 
> But I agree with Nizam's comment which hasn't been taking into account yet, I think this should be done:
> 
> > Also the upgrade-start component you created should really be upgrade-form component and it should be inside upgrade/upgrade-form folder rather than existing in the same folder as upgrade.
> > Also it is missing the unit-test file. You should also create that and push it.

yeah missed that, will do unit test and move start modal component under `upgrade-form`

2023-07-31 09:33 UTC, avanthakkar commented
> Nit: `New versions` -> `New version`

Done!

2023-07-31 09:33 UTC, avanthakkar commented
> Hey @avanthakkar , overall looks good to me and is working so I'll approve it!
> 
> But I agree with Nizam's comment which hasn't been taking into account yet, I think this should be done:
> 
> > Also the upgrade-start component you created should really be upgrade-form component and it should be inside upgrade/upgrade-form folder rather than existing in the same folder as upgrade.
> > Also it is missing the unit-test file. You should also create that and push it.

Done!

2023-08-01 07:05 UTC, avanthakkar commented
jenkins test make check

2023-08-01 08:46 UTC, merged