pacific: qa/cephfs: add 'rhel' to family of RH OS in xfstest_dev.py
ceph/ceph pull request #52584
Opened 2023-07-21 19:37 UTC by rishabh-d-dave

backport tracker: https://tracker.ceph.com/issues/58992

---

backport of https://github.com/ceph/ceph/pull/50142
parent tracker: https://tracker.ceph.com/issues/58726

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2023-07-26 04:04 UTC, vshankar commented
jenkins test make check

2023-08-08 12:10 UTC, vshankar requested changes

2023-08-08 12:10 UTC, vshankar commented on qa/tasks/cephfs/xfstests_dev.py
> +        log.info(f'distro and version detected is "{distro}" and "{version}".')
https://pulpito.ceph.com/yuriw-2023-08-07_23:35:53-fs-wip-yuri10-testing-2023-08-01-0753-pacific-distro-default-smithi/7362364/

```
2023-08-08T00:25:39.609 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_569a240beeab1f0e3097de970ef4b8c68c2b492a/qa/tasks/cephfs/xfstests_dev.py", line 91, in install_deps
2023-08-08T00:25:39.609 INFO:tasks.cephfs_test_runner:    log.info(f'distro and version detected is "{distro}" and "{version}".')
2023-08-08T00:25:39.609 INFO:tasks.cephfs_test_runner:NameError: name 'log' is not defined
```

2023-08-11 01:05 UTC, vshankar commented on qa/tasks/cephfs/xfstests_dev.py
> +        log.info(f'distro and version detected is "{distro}" and "{version}".')
@rishabh-d-dave ping?

2023-08-21 04:39 UTC, vshankar commented on qa/tasks/cephfs/xfstests_dev.py
> +        log.info(f'distro and version detected is "{distro}" and "{version}".')
@rishabh-d-dave ping?

2023-08-22 09:43 UTC, rishabh-d-dave commented on qa/tasks/cephfs/xfstests_dev.py
> +        log.info(f'distro and version detected is "{distro}" and "{version}".')
Fixed.

2023-08-22 09:43 UTC, rishabh-d-dave commented
Checking if there are no failures due to this patch - http://pulpito.front.sepia.ceph.com/rishabh-2023-08-22_09:41:50-fs-pacific-testing-default-smithi/

2023-08-22 10:49 UTC, rishabh-d-dave commented
> Checking if there are no failures due to this patch - http://pulpito.front.sepia.ceph.com/rishabh-2023-08-22_09:41:50-fs-pacific-testing-default-smithi/

The test passed but this PR branch wasn't picked during the run. Re-initiating the test, this time with this PR branch -

http://pulpito.front.sepia.ceph.com/rishabh-2023-08-22_10:48:24-fs-pacific-testing-default-smithi/

2023-08-22 11:30 UTC, rishabh-d-dave commented
Needed one more commit to be backported. Re-testing again: http://pulpito.front.sepia.ceph.com/rishabh-2023-08-22_11:24:40-fs-pacific-testing-default-smithi/

2023-08-22 12:01 UTC, rishabh-d-dave commented
> Needed one more commit to be backported. Re-testing again: http://pulpito.front.sepia.ceph.com/rishabh-2023-08-22_11:24:40-fs-pacific-testing-default-smithi/

Tests passed. @yuriw This is ready for integration testing.
cc @vshankar

2023-08-23 04:36 UTC, vshankar requested changes
@rishabh-d-dave I think the commit order needs to be reversed.

2023-08-24 10:24 UTC, rishabh-d-dave commented
> @rishabh-d-dave I think the commit order needs to be reversed.

Yes, that would be better for anyone who reads this commit series. Although, exact reverse is not a good idea, bit of it is.

2023-11-29 14:12 UTC, vshankar commented
Not critical for pacific - failure not seen in pacific.

2023-11-29 14:12 UTC, closed without merging