quincy: qa/cephfs: add 'rhel' to family of RH OS in xfstest_dev.py
ceph/ceph pull request #52585
Opened 2023-07-21 19:38 UTC by rishabh-d-dave

backport tracker: https://tracker.ceph.com/issues/58991

---

backport of https://github.com/ceph/ceph/pull/50142
parent tracker: https://tracker.ceph.com/issues/58726

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2023-07-25 07:48 UTC, vshankar commented
jenkins retest this please

2023-08-17 19:23 UTC, batrick approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-August-08

2023-08-17 21:37 UTC, yuriw commented
jenkins test make check

2023-08-17 21:38 UTC, yuriw commented
@rishabh-d-dave feel free to merge after all checks passed
ref: https://trello.com/c/ZjPC9CcN

2023-08-21 05:06 UTC, vshankar commented
> @rishabh-d-dave feel free to merge after all checks passed ref: https://trello.com/c/ZjPC9CcN

Not really:

```
2023-08-09T04:56:58.148 INFO:tasks.cephfs_test_runner:test_acls (tasks.cephfs.test_acls.TestACLs) ... ERROR
2023-08-09T04:56:58.149 INFO:tasks.cephfs_test_runner:
2023-08-09T04:56:58.149 INFO:tasks.cephfs_test_runner:======================================================================
2023-08-09T04:56:58.149 INFO:tasks.cephfs_test_runner:ERROR: test_acls (tasks.cephfs.test_acls.TestACLs)
2023-08-09T04:56:58.150 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2023-08-09T04:56:58.150 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2023-08-09T04:56:58.150 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_c99915ec04212fb433eef93cd14cd65cd72d46b4/qa/tasks/cephfs/xfstests_dev.py", line 18, in setUp
2023-08-09T04:56:58.150 INFO:tasks.cephfs_test_runner:    self.prepare_xfstests_dev()
2023-08-09T04:56:58.150 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_c99915ec04212fb433eef93cd14cd65cd72d46b4/qa/tasks/cephfs/xfstests_dev.py", line 23, in prepare_xfstests_dev
2023-08-09T04:56:58.151 INFO:tasks.cephfs_test_runner:    self.install_deps()
2023-08-09T04:56:58.151 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_c99915ec04212fb433eef93cd14cd65cd72d46b4/qa/tasks/cephfs/xfstests_dev.py", line 91, in install_deps
2023-08-09T04:56:58.151 INFO:tasks.cephfs_test_runner:    log.info(f'distro and version detected is "{distro}" and "{version}".')
2023-08-09T04:56:58.151 INFO:tasks.cephfs_test_runner:NameError: name 'log' is not defined
```

This change needs fix.

2023-08-22 12:06 UTC, rishabh-d-dave commented
The issue with this backport is same as https://github.com/ceph/ceph/pull/52584. Adding same fix to this PR.

2023-08-22 12:16 UTC, rishabh-d-dave commented
Testing this change - http://pulpito.front.sepia.ceph.com/rishabh-2023-08-22_12:15:55-fs-wip-yuri5-testing-2023-08-08-0807-quincy-testing-default-smithi/

2023-08-22 14:33 UTC, rishabh-d-dave commented
jenkins test api

2023-08-23 04:33 UTC, vshankar requested changes
@rishabh-d-dave commit 808279cc0ecabfed317683c6edc679a5c0e3163d and 24ddcfb14cacdb788e9beef2373ca2fcb21f5349 are cherry-picked from the pacific backport and not from main branch. IMO, that needs to be changes unless there is a good reason to do so (and that needs to be mentioned in the commit message).

2023-08-24 10:25 UTC, rishabh-d-dave commented
> @rishabh-d-dave commit [808279c](https://github.com/ceph/ceph/commit/808279cc0ecabfed317683c6edc679a5c0e3163d) and [24ddcfb](https://github.com/ceph/ceph/commit/24ddcfb14cacdb788e9beef2373ca2fcb21f5349) are cherry-picked from the pacific backport and not from main branch. IMO, that needs to be changes unless there is a good reason to do so (and that needs to be mentioned in the commit message).

Yes, I noticed this mistake while changing order of commits and have fixed it now.

2023-08-25 02:17 UTC, vshankar commented
@rishabh-d-dave The two commits (related to logger) have more than one `cherry picked from ...` in the commit message:

```
Signed-off-by: Rishabh Dave <ridave@redhat.com>
(cherry picked from commit https://github.com/rishabh-d-dave/ceph/commit/b60b73c0feb76ea86fc8c9a6f4db796ea600f8a7)
(cherry picked from commit https://github.com/rishabh-d-dave/ceph/commit/03e6f7c77776ccd3079a8ba8a534cf6da42e5b2f)
@rishabh-d-dave
```

I though you fixed that.

2023-08-25 06:42 UTC, rishabh-d-dave commented
> @rishabh-d-dave The two commits (related to logger) have more than one `cherry picked from ...` in the commit message:
> 
> ```
> Signed-off-by: Rishabh Dave <ridave@redhat.com>
> (cherry picked from commit https://github.com/rishabh-d-dave/ceph/commit/b60b73c0feb76ea86fc8c9a6f4db796ea600f8a7)
> (cherry picked from commit https://github.com/rishabh-d-dave/ceph/commit/03e6f7c77776ccd3079a8ba8a534cf6da42e5b2f)
> @rishabh-d-dave
> ```
> 
> I though you fixed that.

Same here. 

Fixed again. This time I've double checked too.

2023-10-03 17:42 UTC, mchangir approved these changes
https://pulpito.ceph.com/vshankar-2023-09-29_10:09:00-fs-wip-vshankar-testing-quincy-20230929.071619-testing-default-smithi/

2023-10-04 12:12 UTC, mchangir commented
Reviewed-by: Milind Changire <mchangir@redhat.com>

2023-10-04 16:16 UTC, vshankar approved these changes

2023-10-04 16:18 UTC, merged