pacific: mgr/snap_schedule: allow retention spec 'n' to be user defined
ceph/ceph pull request #52750
Opened 2023-08-02 06:32 UTC by mchangir

backport tracker: https://tracker.ceph.com/issues/61989

---

backport of https://github.com/ceph/ceph/pull/51278
parent tracker: https://tracker.ceph.com/issues/59582

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2023-08-03 05:37 UTC, mchangir commented
jenkins test api

2023-08-03 05:37 UTC, mchangir commented
jenkins test make check

2023-08-04 04:08 UTC, mchangir commented
jenkins test make check

2023-08-17 21:58 UTC, ljflores commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcqRJogcXu1827-wip-yuri2-testing-2023-08-16-1142-pacific

2023-08-17 22:23 UTC, ljflores commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomc4TiiTR0k1821-wip-yuri7-testing-2023-08-16-1309-pacific-old-wip-yuri7-testing-2023-08-16-0933-pacific-old-wip-yuri7-testing-2023-08-15-0741-pa

2023-08-21 15:33 UTC, batrick requested changes
Otherwise good to merge after that doc fix.

https://tracker.ceph.com/projects/cephfs/wiki/Pacific#2023-August-16

2023-08-21 16:01 UTC, mchangir commented on PendingReleaseNotes
> +* mClock Scheduler: The mClock scheduler (default scheduler in Quincy) has
fixed the `PendingReleaseNotes`

2023-09-25 06:03 UTC, mchangir commented
@vshankar please merge this PR

2023-09-25 07:48 UTC, vshankar approved these changes

2023-09-25 07:49 UTC, merged