Revert "qa/cephfs: fix ior build failure"
ceph/ceph pull request #53036
Opened 2023-08-17 13:01 UTC by vshankar

Reverts ceph/ceph#52416

2023-08-17 13:02 UTC, rishabh-d-dave approved these changes

2023-08-17 13:03 UTC, rishabh-d-dave requested changes
@vshankar Commit is unsigned.

2023-08-17 13:05 UTC, vshankar commented
> @vshankar Commit is unsigned.

Github UI doesn't add that -- done now.

2023-08-22 07:58 UTC, vshankar commented
jenkins test make check

2023-08-22 09:46 UTC, rishabh-d-dave approved these changes

2023-08-22 09:46 UTC, merged