reef: cephfs: implement snapdiff
ceph/ceph pull request #53229
Opened 2023-08-30 20:30 UTC by ifed01

Backport of https://github.com/ceph/ceph/pull/43546
Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-09-08 05:47 UTC, joscollin approved these changes

2023-10-04 14:03 UTC, vshankar requested changes
@ifed01 PTAL

2023-10-05 10:25 UTC, vshankar commented on src/mds/Server.cc
> +    max_bytes = (512 << 10) + g_conf()->mds_max_xattr_pairs_size;
false alarm -- probably build script bug. rebuilding.

2023-10-17 00:30 UTC, lxbsz approved these changes
Checked all the 15 test failures and all are not related to this PR:

https://pulpito.ceph.com/vshankar-2023-10-09_16:48:27-fs-wip-vshankar-testing-reef-20231009.131610-testing-default-smithi/

LGTM.

2023-10-17 15:02 UTC, vshankar commented
> @vshankar - can we go ahead with merging?

@yuriw merges backport normally - I'm sure he is on it since @lxbsz approved the change.

2023-10-18 04:29 UTC, vshankar commented
> > @vshankar - can we go ahead with merging?
> 
> @yuriw merges backport normally - I'm sure he is on it since @lxbsz approved the change.

Spoke to @yuriw - this change (along with others in the test batch) will be merged today.

2023-10-18 14:53 UTC, yuriw commented
@vshankar you need to remove your block here

2023-10-18 15:29 UTC, vshankar commented
> @vshankar you need to remove your block here

Done.

2023-10-18 16:22 UTC, merged