docs: add warning about potential package conflict
ceph/ceph pull request #53341
Opened 2023-09-08 16:31 UTC by alvinowyong

The command `ceph orch daemon add osd *<host>*:*<device-path>*` will fail on target host if ceph-osd package is installed on target host. This commit adds warning for "creating new osds" section under cephadm services.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-09-08 17:17 UTC, anthonyeleven requested changes

2023-09-08 17:17 UTC, anthonyeleven commented on doc/cephadm/services/osd.rst
> +
When deploying new OSDs with `cephadm`, ensure that the `ceph-osd` package is not already installed on the target host.  If it is installed, conflicts may arise in the management and control of the OSD that may lead to errors or unexpected behavior.

2023-09-08 17:18 UTC, anthonyeleven commented
Also `doc/cephadm/services: Add package conflict warning to osd.rst`

2023-09-08 17:48 UTC, alvinowyong commented
Thanks for the inputs, changes made accordingly.

2023-09-09 20:08 UTC, anthonyeleven approved these changes

2023-09-09 20:08 UTC, anthonyeleven commented
The failed test looks unrelated, so I'm merging.  Thanks for contributing!

2023-09-09 20:09 UTC, merged