mgr/dashboard: fix bootstrap script for cephadm installation
ceph/ceph pull request #53436
Opened 2023-09-13 11:19 UTC by avanthakkar

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-09-14 09:26 UTC, avanthakkar commented on src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
> +ln -s $CEPHADM_SRC $CEPHADM
Makes sense, thanks! Pushed the changes, PTAL

2023-09-14 09:28 UTC, nizamial09 commented on src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
> +ln -s $CEPHADM_SRC $CEPHADM
don't see the changes though?

2023-09-14 10:01 UTC, nizamial09 commented on src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
>  mkdir -p /etc/ceph
i don't think changes in this file is necessary. we can probably keep it as it is and it should work

2023-09-14 15:23 UTC, nizamial09 requested changes

2023-09-14 15:23 UTC, nizamial09 commented on src/pybind/mgr/dashboard/ci/cephadm/start-cluster.sh
> +${CEPH_DEV_FOLDER}/src/cephadm/build.by ${CEPH_DEV_FOLDER}/src/cephadm/cephadm
we are trying to execute a python file here
```suggestion
exec python3 ${CEPH_DEV_FOLDER}/src/cephadm/build.by ${CEPH_DEV_FOLDER}/src/cephadm/cephadm
```

2023-09-14 15:23 UTC, nizamial09 commented on src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
> +ln -s $CEPHADM_SRC $CEPHADM
```suggestion
cp /mnt/{{ ceph_dev_folder }}/src/cephadm/cephadm $CEPHADM
```

2023-09-14 15:24 UTC, nizamial09 commented on src/pybind/mgr/dashboard/ci/cephadm/bootstrap-cluster.sh
> +ln -s $CEPHADM_SRC $CEPHADM
not sure if a copy would ask for sudo permission in jenkins!

2023-09-15 08:50 UTC, avanthakkar commented
jenkins test dashboard cephadm

2023-09-22 16:12 UTC, adk3798 commented on src/cephadm/cephadm.py
> +                mounts[cephadm_binary] = '/usr/sbin/cephadm'
FYI, Redouane's PR got merged so you should be able to rebase and remove this commit

2023-10-04 06:24 UTC, avanthakkar commented
jenkins test dashboard cephadm

2023-10-04 08:36 UTC, nizamial09 approved these changes

2023-10-04 08:36 UTC, nizamial09 commented
jenkins test api

2023-10-04 13:13 UTC, merged

2023-10-04 13:17 UTC, nizamial09 commented
Thanks @avanthakkar