test: corrected control reaches end by adding a default return
ceph/ceph pull request #53606
Opened 2023-09-22 21:14 UTC by Patty8122

Default return was needed if no check fails. So I added a "return 0". Failed checks return -1.
Fixes: https://tracker.ceph.com/issues/62855
Signed-off-by: Patty8122 <divyapattisapu@uchicago.edu>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

Tried reproducing the error after fix using "ninja ceph_test_timers" and found that there is no issue.

<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-09-23 18:30 UTC, ronen-fr requested changes
the relevant commit looks good.
Please remove the unrelated one.

2023-09-23 18:30 UTC, ronen-fr commented on src/osd/OSD.cc
> +  for (uint32_t shard_index = 0; shard_index < osd->num_shards; shard_index++) {
not related to this PR

2023-09-23 18:32 UTC, ronen-fr commented
I'd also suggest removing the word 'default',  as it hints at a missing switch-case label

2023-09-26 00:38 UTC, ljflores commented
Hey @Patty8122, let us know if you need any help removing this commit: https://github.com/ceph/ceph/pull/53606/commits/a067da24d81c9f716cbac2769fbda559a5038e3a

I think it was from a different PR.

2023-09-29 22:40 UTC, ljflores commented
@Patty8122 I dropped the irrelevant commit. Here are the steps I took:

```
git checkout control-reaches-end-fix
git rebase -i 9fedc1e062027dbce66747e5d0dc11319615ab8a
Write "drop" next to commit a067da24d81c9f716cbac2769fbda559a5038e3a instead of "pick"
Save the file (:wq)
git push -f Patty8122 control-reaches-end-fix
```

2023-09-29 22:43 UTC, ljflores commented
> I'd also suggest removing the word 'default', as it hints at a missing switch-case label

If you need help addressing @ronen-fr's comment, let me know!

Since I updated your remote branch, you'd need to pull these new changes to your local branch before committing, like this, assuming you named your fork of the repository "Patty8122":

```
git pull Patty8122
git checkout control-reaches-end-fix
git reset --hard Patty8122/control-reaches-end-fix
```

Then you can make more changes and follow the same commit workflow you used before to originally create the PR.

2023-10-01 23:12 UTC, Patty8122 commented
Thank you for the suggestions @ronen-fr !

Thank you so much for the hints, @ljflores ! They were helpful. I hope things are correct now.

2023-10-02 05:33 UTC, ronen-fr approved these changes

2023-10-02 05:36 UTC, ronen-fr commented
@Patty8122 , @ljflores : as this PR only changes test code (a very minor change at that), I will be merging it based on
the CI tests, not waiting for Teuthology

2023-10-02 05:37 UTC, merged

2023-10-02 14:39 UTC, ljflores commented
Congrats on merging a PR @Patty8122 !