[OSD.cc in src/osd]: Mismatch in variable type during for loop iteration
ceph/ceph pull request #53603
Opened 2023-09-22 20:14 UTC by Patty8122

Changed the variable shard_index from int to uint32_t due to mismatch.

Signed-off-by: Patty8122 <divyapattisapu@uchicago.edu>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ x ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ x ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ x ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ x ] No tests

Tested it 
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-09-22 20:33 UTC, ljflores reviewed
Hey @Patty8122, I updated your PR title to match Ceph guidelines.

You can find more here: https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst

Please edit your commit to match that new title.

You can do it with `git commit --amend` on your local branch. Let me know if you have questions!

2023-09-22 20:35 UTC, ljflores commented
Also @Patty8122, add a "Fixes: <tracker link>" above where you signed off your name and email in the commit!

2023-09-22 23:53 UTC, yaarith commented
@Patty8122 thanks! 
The `Fixes` section should include the tracker link: https://tracker.ceph.com/issues/62851

2023-09-23 15:52 UTC, ronen-fr commented
This issue was already fixed in approved PR
https://github.com/ceph/ceph/pull/53530
(and - that fix is better).

I'd suggest closing this PR.

2023-09-23 15:54 UTC, ronen-fr requested changes
A better fix was already approved in https://github.com/ceph/ceph/pull/53530

2023-09-29 22:45 UTC, ljflores commented
> A better fix was already approved in #53530

@Patty8122 looks like there was a fix for this in a different PR. Let's close this one.

2023-09-29 22:45 UTC, closed without merging