cephfs-shell: use pkg_resources rather than packaging module
ceph/ceph pull request #53710
Opened 2023-09-28 07:57 UTC by vshankar

Fixes: https://tracker.ceph.com/issues/62739

Follow up on #53529 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-10-03 05:45 UTC, joscollin requested changes
There are other instances:

`
$ source vstart_environment.sh && source venv/bin/activate && python3 ../src/tools/cephfs/shell/cephfs-shell
Traceback (most recent call last):
  File "/home/jcollin/workspace/ceph/build/../src/tools/cephfs/shell/cephfs-shell", line 1848, in <module>
    read_shell_conf(shell, get_shell_conffile_path(args.config))
  File "/home/jcollin/workspace/ceph/build/../src/tools/cephfs/shell/cephfs-shell", line 1704, in read_shell_conf
    if version.parse(cmd2_version) >= version.parse("0.10.0"):
       ^^^^^^^
NameError: name 'version' is not defined. Did you mean: 'Version'?

`

2023-10-03 05:46 UTC, vshankar commented
> There are other instances:
> 
> > $ source vstart_environment.sh && source venv/bin/activate && python3 ../src/tools/cephfs/shell/cephfs-shell
> > Traceback (most recent call last):
> > File "/home/jcollin/workspace/ceph/build/../src/tools/cephfs/shell/cephfs-shell", line 1848, in 
> > read_shell_conf(shell, get_shell_conffile_path(args.config))
> > File "/home/jcollin/workspace/ceph/build/../src/tools/cephfs/shell/cephfs-shell", line 1704, in read_shell_conf
> > if version.parse(cmd2_version) >= version.parse("0.10.0"):
> > ^^^^^^^
> > NameError: name 'version' is not defined. Did you mean: 'Version'?

oh, bother :/

sending a fix...

2023-10-10 04:42 UTC, vshankar commented
jenkins test api

2023-10-10 05:19 UTC, joscollin approved these changes
Looks good to me, though it's better move the doc changes to separate commit.

2023-10-10 05:34 UTC, vshankar commented
> Looks good to me, though it's better move the doc changes to separate commit.

The doc change *is* a separate commit :)

2023-10-20 05:06 UTC, vshankar commented
jenkins test api

2023-10-20 05:06 UTC, vshankar commented
https://tracker.ceph.com/projects/cephfs/wiki/Main#13-Oct-2023

2023-10-20 09:57 UTC, merged