os/bluestore: Nice debug prints for Extent and Blob
ceph/ceph pull request #54075
Opened 2023-10-18 14:28 UTC by aclamk

Introduce printer class that allows to select parts of Blob that are to be printed.
It severly reduced amount of clutter in output.
Usage:
using P = Bluestore::Blob::printer;
dout << blob->printer(P::nick + P::sdisk + P::schk);

Now the Blob printout can look like this:
`Blob(rtrvlad disk=0x[45~1,46~f]000 track=16*4K{4K}[] )`
or
`Blob(eflahoj disk=0x[55~1]000 track=1*4K[210] )`

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-10-19 12:46 UTC, ifed01 approved these changes
Nice!

2024-01-04 11:58 UTC, pereman2 requested changes

2024-01-04 11:58 UTC, pereman2 commented on src/os/bluestore/BlueStore.h
> +    }
shouldn't the printer be a singleton? If we add to many prints it will instantiate a printer every time we print something.

2024-01-04 11:58 UTC, pereman2 commented
unstale

2024-03-06 14:59 UTC, ifed01 commented
jenkins test make check

2024-03-06 14:59 UTC, ifed01 commented
jenkins test api

2024-03-06 15:08 UTC, ifed01 commented on src/os/bluestore/BlueStore_debug.cc
> +// cheap, not very reliable but portable detector where heap starts
misplaces or totally unrelated?

2024-03-06 16:15 UTC, ifed01 approved these changes

2024-03-26 13:43 UTC, aclamk commented on src/os/bluestore/BlueStore_debug.cc
> +      out << (k.x / 0x400);
`x / 0x400` compiles to `shl x, 10`, but retains relation to above condition.

2024-05-15 08:04 UTC, pereman2 approved these changes

2024-06-28 15:27 UTC, aclamk commented
jenkins test make check

2024-06-28 15:28 UTC, aclamk commented
jenkins test windows

2024-06-28 15:28 UTC, aclamk commented
jenkins test api

2024-07-02 09:22 UTC, aclamk commented
jenkins test api

2024-07-24 13:03 UTC, aclamk commented
jenkins test api

2024-08-08 07:22 UTC, aclamk commented
jenkins test make check

2024-08-08 07:22 UTC, aclamk commented
jenkins test api

2024-08-08 08:56 UTC, aclamk commented
jenkins test make check

2024-08-08 08:56 UTC, aclamk commented
jenkins test api

2024-08-08 13:53 UTC, aclamk commented
jenkins test make check

2024-08-12 13:47 UTC, merged