quincy: prevent anonymous topic operations
ceph/ceph pull request #54172
Opened 2023-10-24 16:32 UTC by yuvalif

backport tracker: https://tracker.ceph.com/issues/58906

---

backport of https://github.com/ceph/ceph/pull/49335
parent tracker: https://tracker.ceph.com/issues/58167

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2023-10-24 16:42 UTC, yuvalif commented
note that due to conflicts, the fix here is different than the one done in reef: https://github.com/ceph/ceph/pull/49335

2024-03-26 12:04 UTC, BioWilko commented
Any updates on this? I'm very keen for this to be pulled in, due to the security implications I'm having to run a rubbish notifications workaround for new s3 objects currently...

2024-03-28 17:08 UTC, yuvalif commented
> Any updates on this? I'm very keen for this to be pulled in, due to the security implications I'm having to run a rubbish notifications workaround for new s3 objects currently...

added "needs-review" and "needs-qa" flags. hope that this is be reviewed, tested and merged soon...

2024-04-17 20:47 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65558](https://tracker.ceph.com/issues/65558).

2024-04-17 22:22 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65561](https://tracker.ceph.com/issues/65561).

2024-04-22 19:51 UTC, cbodley commented
@yuvalif qa on this had a crash in rgw/notifications. i reopened https://tracker.ceph.com/issues/62063 with stack traces. are we missing other important backports here?

2024-04-22 21:06 UTC, yuriw commented
ref: https://tracker.ceph.com/issues/65558

2024-04-23 15:13 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65638](https://tracker.ceph.com/issues/65638).

2024-07-02 20:37 UTC, adamemerson approved these changes

2024-07-02 20:41 UTC, adamemerson commented
Was there anything merged to quincy since April that might make this worth another QA run, or does it still need to be investigated?

2024-07-02 20:42 UTC, adamemerson requested changes
Pending resolution of regression

2024-07-02 20:54 UTC, cbodley commented
> Was there anything merged to quincy since April that might make this worth another QA run, or does it still need to be investigated?

i looked through https://pulpito.ceph.com/?suite=rgw and didn't see any quincy runs since [the one containing this failure](https://pulpito.ceph.com/yuriw-2024-04-20_15:31:09-rgw-wip-yuri4-testing-2024-04-19-0708-quincy-distro-default-smithi/) in april, so we shouldn't have merged any other backports in the meantime

2024-08-06 21:40 UTC, closed without merging