quincy: rgw: add versioning info to radosgw-admin bucket stats output
ceph/ceph pull request #54190
Opened 2023-10-25 13:57 UTC by cfsnyder

backport tracker: https://tracker.ceph.com/issues/63253

---

backport of https://github.com/ceph/ceph/pull/53813
parent tracker: https://tracker.ceph.com/issues/63092

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-01-11 15:44 UTC, cbodley commented
jenkins test make check

2024-01-11 15:44 UTC, cbodley commented
jenkins test api

2024-01-11 15:46 UTC, cbodley requested changes
we ended up changing this output - i believe https://github.com/ceph/ceph/pull/54197 is where that happened. could you please cherry-pick those changes too? cc @ivancich

2024-01-11 19:23 UTC, dang approved these changes

2024-01-11 21:28 UTC, yuriw commented
jenkins test api

2024-01-11 21:36 UTC, yuriw commented
@cfsnyder This was tested and can be merged after @cbodley 's change addressed 
ref: https://trello.com/c/lspPyG27

2024-01-23 18:25 UTC, cbodley approved these changes

2024-04-17 20:47 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65558](https://tracker.ceph.com/issues/65558).

2024-04-17 22:22 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65561](https://tracker.ceph.com/issues/65561).

2024-04-22 21:07 UTC, merged