mds: fix `dump dir` indicate dir is not cached
ceph/ceph pull request #54202
Opened 2023-10-26 06:26 UTC by joscollin

Fixes: https://tracker.ceph.com/issues/63093

2023-10-31 01:17 UTC, batrick requested changes
Please include an example output in the commit message.

2023-10-31 01:17 UTC, batrick commented on src/mds/MDSRank.cc
> +    else {
```suggestion
    } else {
```

style

2023-10-31 01:17 UTC, batrick commented on src/mds/MDSRank.cc
> +      f->dump_string("status", "dirfrag not in cache");
How do you know which dirfrag is not in cache?

2023-12-05 15:54 UTC, batrick requested changes

2023-12-05 15:54 UTC, batrick commented on src/mds/MDSRank.cc
> +      f->dump_string("value/bits", css->strv());
```suggestion
      f->dump_stream("frag") << leaf;
```

2023-12-07 11:38 UTC, joscollin commented
jenkins test make check

2024-01-25 11:12 UTC, vshankar approved these changes
LGTM.

2024-01-25 11:56 UTC, dparmar18 approved these changes

2024-02-27 04:36 UTC, vshankar commented
https://pulpito.ceph.com/?branch=wip-vshankar-testing-20240226.124304

2024-02-27 05:59 UTC, vshankar commented
https://pulpito.ceph.com/vshankar-2024-02-27_04:05:06-fs-wip-vshankar-testing-20240226.124304-testing-default-smithi/

2024-03-04 10:15 UTC, vshankar commented
Reruning tests with https://github.com/ceph/ceph/pull/55909 and https://github.com/ceph/ceph/pull/55908 included. See - https://pulpito.ceph.com/vshankar-2024-03-04_08:26:39-fs-wip-vshankar-testing-20240304.042522-testing-default-smithi/

2024-03-06 08:37 UTC, vshankar approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/Main#5th-March-2024

2024-03-06 08:44 UTC, merged