Wip ksirivad pool availability feature
ceph/ceph pull request #54249
Opened 2023-10-30 14:47 UTC by kamoltat

Draft PR for availability feature

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-12-21 15:24 UTC, yaarith commented
Hey @kamoltat, 

We had a discussion about a few design aspects of the availability score feature:

1. It’s probably better to have this feature off by default, and have the user explicitly turn it on. That is, if the feature is turned off, no metadata is being stored in the mon db.
2. The frequency of the metadata capturing should be configurable (capture pg availability every X minutes).
3. The availability score should also be configurable (maybe by number of days, up to a certain threshold).
4. We should prune the metadata after X days (can also be configurable). When we do so, it would be nice to calculate availability score for the data that will be pruned. Neha suggested to add an epoch / timestamp for the score.
5. Take into consideration possible issues with mob db - we need to be able to estimate how much space will be dedicated for this feature - if we know how the records look like in the mon db (key, value), how many PGs, and retention time (how long we keep the metadata for) it will be easy to calculate the required space.
6. Since the feature should be enabled, we should think of what disabling it does - maybe when the user disables it we should display a warning that “all of the availability metadata will be removed” or something like it.
7. Neha suggested to have a script that injects failures in random times (something like: failure 1 at t0, failure 2 at t1 = t0 + 3 days, failure 3 at t2 = t1 + 5 minutes, failure 4 at t3 = t2 + 1 minute, etc.) and measure the availability score along the way. The tests should also include changing the total number of PGs, to see how much we can scale out. The gibba cluster can be a good candidate for testings.

2024-01-18 18:59 UTC, NitzanMordhai requested changes
@kamoltat please see my comments

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/PGMap.cc
> +  if (v >= 5) {
You don't need to check for v in encode, the encode is always the current version of the mon, so it must be 5 in that case, if it's earlier, you won't have the code on.

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/PGMap.cc
> +  f->open_array_section("pool_pg_unavailable_map");
do you think we can leave only one array section instead of opening a new section for each iterator?

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/PGMap.cc
> +    pool_pg_unavailable_map[poolid];
Can you explain that line? maybe left over?

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/PGMap.cc
> +void PGMap::calc_pool_stuck_unavailable_pg_map(const OSDMap& osdmap)
Maybe i'm missing something, are we using osdmap over here?

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/OSDMonitor.cc
> +  else if (prefix == "osd force-create-pg") {
keeping the style, please move else if after {

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/MgrStatMonitor.cc
> +          digest.pool_pg_unavailable_map.end()) {
since we just constructed pool_available out from digest.pool_pg_unavailable_map, is there any reason why it won't find it?

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/MgrStatMonitor.cc
> +        now - pool_availability[poolid].last_uptime;
indent ..

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/MgrStatMonitor.cc
> +      pool_availability[poolid].uptime +=
isn't it supposed to be downtime?

2024-01-18 18:59 UTC, NitzanMordhai commented on src/mon/mon_types.h
> +WRITE_CLASS_ENCODER(PoolAvailability)
i think it will be better to start using DENC instead of classic encoding and using DENC macro. it will be easier to read and maintain

2024-04-10 15:27 UTC, neha-ojha commented
@kamoltat let's resurrect this PR for Tentacle

2024-04-10 23:20 UTC, athanatos commented
@kamoltat Ping me when you've addressed the comments from @NitzanMordhai and @yaarith and I'll take a look.

2024-08-28 14:43 UTC, yaarith commented
Trello card: https://trello.com/c/MNmj6CgJ/764-mon-mgr-track-availability-over-time

2024-08-28 15:24 UTC, shraddhaag commented
Tracker: https://tracker.ceph.com/issues/67777

2024-09-09 13:26 UTC, NitzanMordhai commented on src/mon/PGMap.cc
> +  if (v >= 5) {
v should be changed to struct_v

2024-09-10 04:38 UTC, NitzanMordhai commented on src/mon/PGMap.cc
> +  if (v >= 5) {
@shraddhaag we are using struct_v that added and set by DECODE_START macro. when we encoding into a byte stream and send it to other daemons we need to tell them first the version and the length of the byte stream so they can decode it correctly, we are encoding the byte stream with our current version (class version) so we don't need to check it during the encode. but during decode, it means that we got it from another daemon, we want to decode the byte stream correctly so we check if it contains values of members by the version of the byte stream.

2024-12-09 05:01 UTC, closed without merging