cli/ceph: show the most used OSD by a pool through 'ceph df' command
ceph/ceph pull request #54426
Opened 2023-11-08 20:32 UTC by ifed01

ceph df output gets MAX RAW USED column, corresponding fields added to json output as well.

![ceph_df_max_used](https://github.com/ceph/ceph/assets/7138176/ad4f3388-26b5-45ac-a2ef-4f2dfad2400e)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-01-16 11:54 UTC, ifed01 commented
jenkins test dashboard cephadm

2024-02-26 19:34 UTC, ifed01 commented
jenkins test make check

2024-04-26 22:41 UTC, ifed01 commented
unstale

2024-07-13 12:19 UTC, rzarzynski commented
jenkins retest this please

2024-07-13 12:45 UTC, rzarzynski requested changes
There is a slight problem with the dencoding change.

Note to QA: **THIS PR HAS A DENCODING CHANGE**, so it requires extra caution.
@ifed01, does it have coverage also in upgrade testing?

2024-07-13 12:45 UTC, rzarzynski commented on src/mon/PGMap.cc
> -    if (avail_by_rule.count(ruleno) == 0) {
Ouch, I see – `avail_by_rule` is guaranteed to be empty at this stage.

2024-07-13 12:45 UTC, rzarzynski commented on src/mon/PGMap.cc
> +  if (struct_v > 4) {
The version in `DECODE_START()`  hasn't been updated. Please bump it up to `5`.

2024-07-13 12:45 UTC, rzarzynski commented on src/mon/PGMap.cc
> +  encode(max_raw_used_by_rule, bl);
OK, the schema change at the encoder side looks sane – it's the classical extension-at-the-end.

2024-07-13 12:45 UTC, rzarzynski commented on src/mon/PGMap.cc
> +    if (it != max_raw_used_by_rule.end()) {
nit: how about limiting the `it` scope and define within the `if (...; ...)`?

2024-07-13 12:45 UTC, rzarzynski commented on src/mon/PGMap.cc
> +      max_used_rate = it->second.second;;
nit: `std::tie()`? Anyway, not going to argue about saving one line.

2024-07-13 12:45 UTC, rzarzynski commented on src/test/mon/PGMap.cc
> +      for (int i = 0; i < 6; i++) {
:+1: I'm glad it has the test coverage!

2024-07-13 12:46 UTC, rzarzynski commented
BTW: I wonder we should introduce a label like `needs-qa-dencoding` to not forget the _"Note to QA"_ from the review's opening comment.

2024-11-08 05:01 UTC, closed without merging