quincy: Fixing example of BlueStore resharding.
ceph/ceph pull request #54476
Opened 2023-11-13 13:42 UTC by k0ste

backport tracker: https://tracker.ceph.com/issues/63440

---

backport of https://github.com/ceph/ceph/pull/54331
parent tracker: https://tracker.ceph.com/issues/63353

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2023-11-28 14:48 UTC, aclamk requested changes
The O must also be upcase ```O(3,0-13)```. I missed it initially, lets fix it comprehensively.

2024-08-19 16:31 UTC, ljflores commented
@k0ste PTAL and address the review changes.

2024-08-21 19:57 UTC, rzarzynski approved these changes

2024-08-21 19:58 UTC, rzarzynski commented
Leaving the final decision to @aclamk and @pereman2.

2024-08-22 20:30 UTC, pereman2 approved these changes

2024-12-26 12:02 UTC, closed without merging