osd/scrub: separate counters for primary vs. replica scrubs
ceph/ceph pull request #54570
Opened 2023-11-20 13:35 UTC by ronen-fr

The OSD limits the number of concurrent scrubs performed on its PGs.
This limit is now enforced separately for primary and replica scrubs.

TEMPORARY NOTE: only the last commit is relevant to the PR. All other
commits are part of https://github.com/ceph/ceph/pull/54482, and
are pending approval there.

2023-11-21 15:30 UTC, athanatos requested changes

2023-11-21 15:30 UTC, athanatos commented on src/osd/scrubber/scrub_resources.h
> +  /// an aux used to check available local scrubs. Called under the
Must be called with the resource lock held.

2023-11-21 15:30 UTC, athanatos commented on src/osd/scrubber/scrub_resources.h
> +  bool can_inc_local_scrubs_aux() const;
can_inc_local_scrubs_unlocked

2023-12-04 11:46 UTC, ronen-fr commented
closed, as already merged (fixed) as part of #54482

2023-12-04 11:46 UTC, closed without merging