tools/ceph_objectstore_tool: add op "expand-log"
ceph/ceph pull request #54586
Opened 2023-11-21 02:22 UTC by xxhdx1985126

There are circumstances in which, although we can't find enough OSDs to form a valid ec acting set, we can enough OSDs that are fully backfilled and it's only because their PGLog are lagged behind that they can't be added the acting set. In this case, right now, we can only drop the entire pg's data by recreating it.

This commit add the ability to fill in the pg log gap between the backfilled OSDs and the auth log shard, so the pg can be brought to active losing only part of its data and those uncorruped data can be recovered.

Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2023-11-21 02:23 UTC, xxhdx1985126 commented
@athanatos This really worked:-) Please take a look, thanks:-)

2023-11-28 22:11 UTC, athanatos requested changes
Looks mostly good.  My only note is that I'd like the name of the operation to seem more obviously dangerous.  How about pad-log-with-fake-entries?

2023-12-19 14:38 UTC, xxhdx1985126 commented
> Looks mostly good. My only note is that I'd like the name of the operation to seem more obviously dangerous. How about extend-log-with-fake-entries?

Done:-)

2024-02-18 01:49 UTC, xxhdx1985126 commented
Can this PR be merged?

2024-02-18 02:31 UTC, tchaikov commented
i just audited the code. it does not interferer with existing workflow, neither is it exercised by any existing / new tests. so in theory, it won't introduce regressions. i am merging it as it has been approved.

2024-02-18 02:31 UTC, merged

2024-02-18 04:50 UTC, xxhdx1985126 commented
> i just audited the code. it does not interferer with existing workflow, neither is it exercised by any existing / new tests. so in theory, it won't introduce regressions. i am merging it as it has been approved.

Thanks:-)