crimson/osd: Support incremental maps
ceph/ceph pull request #54613
Opened 2023-11-22 09:49 UTC by Matan-B

Blocked by: #54437

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2023-12-03 08:11 UTC, Matan-B commented
https://github.com/ceph/ceph/pull/54437 was merged, this PR is rebased and ready for review. Thanks!
@athanatos

2023-12-03 08:20 UTC, Matan-B commented on src/crimson/osd/shard_services.cc
> +        for (auto const& [e, val] : bls) {
The extra iteration over `bls` here could have been avoided when it was constructed in `load_map_bls()`. However, in order to keep `seastar::map_reduce` usage, I preferred differentiating between full/inc maps here.

2023-12-11 03:54 UTC, athanatos requested changes

2023-12-11 03:54 UTC, athanatos commented on src/crimson/osd/shard_services.cc
> +        return conn.send(std::move(m));
If you want to split building from sending, this should probably return the map for send_incremental_map below to send.

2024-01-02 17:08 UTC, athanatos approved these changes

2024-01-07 12:38 UTC, merged