cmake/rocksdb: make sure dependencies build before rocksdb
ceph/ceph pull request #54626
Opened 2023-11-23 05:22 UTC by cbodley

some of rocksdb's dependencies may not have built by the time its ExternalProject starts, so it can fail with missing headers or libraries. for example, `uring::uring` may itself be an ExternalProject, and its include directory won't exist until it starts building:

```
[89/1345] Performing configure step for 'rocksdb_ext'
FAILED: src/rocksdb_ext-prefix/src/rocksdb_ext-stamp/rocksdb_ext-configure build/src/rocksdb_ext-prefix/src/rocksdb_ext-stamp/rocksdb_ext-configure
...
CMake Error in CMakeLists.txt:
  Imported target "uring::uring" includes non-existent path

    "build/src/liburing/src/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
...
[91/1345] Performing download step (git clone) for 'liburing_ext'
Cloning into 'liburing'...
```

use `add_dependencies(rocksdb_ext)` to make sure all of its dependencies are available before starting the build

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2023-11-23 05:51 UTC, cyx1231st approved these changes
The issue looks disappeared, thank you!

It also makes sense to me that originally, the build will be successful after a retry.

2023-11-23 05:51 UTC, cyx1231st commented
cc @liu-chunmei

2023-11-24 18:28 UTC, cbodley commented
builds are green https://shaman.ceph.com/builds/ceph/wip-cmake-rocksdb-uring/353360581a0b802435ecf4273ba79f53deb710e6/

2023-11-24 18:28 UTC, cbodley commented
> The following tests FAILED:
	 10 - run-tox-mgr-dashboard-lint (Failed)
	 19 - run-tox-python-common (Failed)

2023-11-24 18:28 UTC, cbodley commented
jenkins test make check

2023-11-24 19:36 UTC, cbodley commented
> The following tests FAILED:
	 31 - run-rbd-unit-tests-1.sh (Failed)

2023-11-24 19:36 UTC, cbodley commented
jenkins test make check

2023-11-27 13:45 UTC, batrick requested changes
Thanks for the fix Casey. This will need a tracker ticket though as

https://tracker.ceph.com/issues/63218

is being backported.

2023-11-27 13:54 UTC, batrick commented
> > Thanks for the fix Casey. This will need a tracker ticket though as
> > https://tracker.ceph.com/issues/63218
> > is being backported.
> 
> @batrick since you did those backports, could i ask you to include this commit? if we try to track them separately, we'll get conflicts because this depends on yours

Sure

2023-11-27 13:54 UTC, batrick approved these changes

2023-11-27 14:20 UTC, merged

2023-11-27 14:20 UTC, cbodley commented
@batrick i'd be happy to push the commit to your backport branches if you prefer

2023-11-27 14:35 UTC, batrick commented
> @batrick i'd be happy to push the commit to your backport branches if you prefer

That'd be great, thanks.