qa: add centos_latest (9.stream) and ubuntu_20.04 yamls to supported-all-distro
ceph/ceph pull request #54677
Opened 2023-11-27 14:32 UTC by vshankar

A bug in Ceph MDS (MDS crash!) is seen with distos using a not-so-recent kernel
    (5.4ish). This crash was first seen in quincy smoke run and the problematic
    backport change was reverted. The smoke suite chooses a random distro for each
    job, so to hit this bug, the appropriate distro needs to be (randomly) get chosen.

    This change point the smoke suite to run against all supported distros.

    This effects suites that point to supported-all-distro (powercycle) since it
    bloats up the nuymber of jobs. E.g., currently, without --subset, powercycle:osd

              INFO:teuthology.suite.run:0/336 jobs were filtered out.

    vs

    (with this change)

              Unable to schedule 560 jobs, too many jobs, when maximum 500 jobs allowed.

    For smoke suite

              INFO:teuthology.suite.run:Scheduled 24 jobs in total.

    vs

    (with this change)

               INFO:teuthology.suite.run:Scheduled 120 jobs in total.

    Eventually, with PR #46882, then testing kernel will no longer override the
    distro kernel in fs suite, so we should get good coverage then.

--

This isn't really reef only change BTW.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2023-11-27 18:13 UTC, batrick requested changes
I'm confused by `qa/distros/supported-all-distros`. That's new right? Why would that affect powercycle?

I would think it should be `qa/distros/supported` which does already exist.

2023-11-27 19:04 UTC, yuriw commented
@vshankar why is it part of the smoke instead of the fs suite?

2023-11-28 00:18 UTC, vshankar commented
> I'm confused by `qa/distros/supported-all-distros`. That's new right? Why would that affect powercycle?

No, it isn't. It already existed and powercycle suite was pointing to it for the list of distros to use. Note that this is in the reef branch.

I'll check again though.


> 
> I would think it should be `qa/distros/supported` which does already exist.

There are a host of directories under qa/distros: 

- all: has yamls for all distros
- supported
- supported-all-distro
- supported-random-distros$

2023-11-28 00:25 UTC, vshankar commented
Fyi - https://pulpito.ceph.com/vshankar-2023-11-27_13:25:48-smoke-reef-release-testing-default-smithi/

Used the qa changes here with reef-release branch and a custom --filter to run some test - I think the failed test is the mds crash.

2023-11-28 04:09 UTC, vshankar commented
> Fyi - https://pulpito.ceph.com/vshankar-2023-11-27_13:25:48-smoke-reef-release-testing-default-smithi/
> 
> Used the qa changes here with reef-release branch and a custom --filter to run some test - I think the failed test is the mds crash.

False alarm - the test failed due to infra issue.

2023-11-28 05:13 UTC, vshankar commented
cc @badone for powercycle:osd (maybe?)

2023-11-28 06:08 UTC, lxbsz commented on qa/suites/smoke/basic/supported-all-distro
> +./.qa/distros/supported-all-distro
`./.qa/distros/supported-all-distro` --> `.qa/distros/supported-all-distro`

2023-11-28 06:13 UTC, lxbsz commented
> This effects suites that point to supported-all-distro (powercycle) since it
> bloats up the nuymber of jobs. E.g., currently, without --subset, powercycle:osd
> 

`s/nuymber/number/` in the commit comment of https://github.com/ceph/ceph/pull/54677/commits/4feb8c30c6b9c6ad50f66195cea600f892e3b9f4.

2023-11-28 06:46 UTC, vshankar commented
Thanks for the review @lxbsz. BTW, after working around the issue with missing debugfs kclient patches in 20.04, I've been able to hit the mds assert here - https://pulpito.ceph.com/vshankar-2023-11-28_05:49:38-smoke-reef-release-distro-default-smithi/7469311/

(note - the test is still running atm - MDS crashed, but the job is continuously doing `sudo logrotate /etc/logrotate.d/ceph-test.conf`)

MDS assert:

```
2023-11-28T06:14:25.604 INFO:tasks.ceph.mds.a.smithi005.stderr:/build/ceph-18.2.0-1242-g6c86da32/src/mds/Server.cc: 3441: FAILED ceph_assert(_inode->gid != (unsigned)-1)
2023-11-28T06:14:25.608 INFO:tasks.ceph.mds.a.smithi005.stderr: ceph version 18.2.0-1242-g6c86da32 (6c86da324d5733ef2768551db91b670156088da7) reef (stable)
2023-11-28T06:14:25.608 INFO:tasks.ceph.mds.a.smithi005.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x128) [0x7efdb02602c5]
2023-11-28T06:14:25.608 INFO:tasks.ceph.mds.a.smithi005.stderr: 2: /usr/lib/ceph/libceph-common.so.2(+0x320481) [0x7efdb0260481]
2023-11-28T06:14:25.608 INFO:tasks.ceph.mds.a.smithi005.stderr: 3: (Server::prepare_new_inode(boost::intrusive_ptr<MDRequestImpl>&, CDir*, inodeno_t, unsigned int, file_layout_t const*)+0x1ae9) [0x55bfca3aa039]
2023-11-28T06:14:25.608 INFO:tasks.ceph.mds.a.smithi005.stderr: 4: (Server::handle_client_mkdir(boost::intrusive_ptr<MDRequestImpl>&)+0x1cd) [0x55bfca3abfed]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 5: (Server::handle_client_request(boost::intrusive_ptr<MClientRequest const> const&)+0x614) [0x55bfca3c7d94]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 6: (Server::dispatch(boost::intrusive_ptr<Message const> const&)+0xf4) [0x55bfca3cc964]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 7: (MDSRank::_dispatch(boost::intrusive_ptr<Message const> const&, bool)+0x5a6) [0x55bfca317246]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 8: (MDSRankDispatcher::ms_dispatch(boost::intrusive_ptr<Message const> const&)+0x5c) [0x55bfca31783c]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 9: (MDSDaemon::ms_dispatch2(boost::intrusive_ptr<Message> const&)+0x1bf) [0x55bfca30135f]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 10: (Messenger::ms_deliver_dispatch(boost::intrusive_ptr<Message> const&)+0x468) [0x7efdb04da4f8]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 11: (DispatchQueue::entry()+0x657) [0x7efdb04d7a97]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 12: (DispatchQueue::DispatchThread::entry()+0x11) [0x7efdb059d3a1]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 13: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7efdafeea609]
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr: 14: clone()
2023-11-28T06:14:25.609 INFO:tasks.ceph.mds.a.smithi005.stderr:*** Caught signal (Aborted) **
```

I'll send a main branch PR with the additional fixes.

2023-11-28 07:27 UTC, vshankar commented
OK, so main branch has 20.04/centos8/rhel8 removed from the supported distro. See: #53517 - which means this change needs to be reef only IMO.

2023-11-28 09:43 UTC, vshankar commented
Addressed @lxbsz comment. Also added a commit to ignore failures when fetching mount information which happens with 20.04 due to missing kernel patches.

2023-11-28 09:44 UTC, vshankar commented
I'm marking this ready for review.

2023-11-28 11:39 UTC, idryomov reviewed
FWIW I don't think expanding the distro matrix like that is the right way to approach this.  What is missing is a backwards compatibility test suite.  The kernel client happens to be a client with a custom set of supported feature flags/encoding versions on a release schedule that doesn't match Ceph release schedule and you are trying to exploit that in an ad hoc manner.  This is tying everything to the set distros supported by a particular release of Ceph, but note that:

- We need to be able to detect backwards compatibility issues even when we stop building Ceph for one of these distros.

- (Any) distro kernel is a moving target.  If a patch that masks a backwards compatibility issue lands in the kernel client, the failure would disappear without necessarily getting addressed in Ceph.  If such a patch gets backported by the distro kernel team quickly enough, you may never even see the failure in the first place.

2023-11-28 11:45 UTC, idryomov commented
> OK, so main branch has 20.04/centos8/rhel8 removed from the supported distro. See: #53517 - which means this change needs to be reef only IMO.

... and this just proves my point.  Let's say this change is in place and there is an open PR against main which introduces a backwards compatibility issue in the MDS.  It would pass the fs suite even when it's improved with @batrick's https://github.com/ceph/ceph/pull/46882 because we are no longer building Ceph for 20.04 (not the case today but those builds are bound to be dropped at some point).  The PR would get merged to main.  If it's something that is getting backported to reef, the bug would be discovered then, potentially weeks later requiring folks to scramble for a follow-up or a revert.  If it's a new feature, it probably isn't getting backported, meaning that the bug is there to stay...

2023-11-28 13:38 UTC, batrick commented
`qa: don't fail on gather_mount_info() failure ` should go in `main` too if we plan to regularly test LTS kernels in upstream QA (I agree we should do that).

2023-11-28 13:42 UTC, batrick commented
> FWIW I don't think expanding the distro matrix like that is the right way to approach this.

I agree, Ilya. However, when we adjust `main` to actually test LTS kernels rather than "old" distro kernels, that change is very unlikely to be backported (due to complexity). I would support this change as a band-aid fix for `reef` in the mean-time.

2023-11-28 23:16 UTC, badone commented
I'd suggest backporting https://github.com/ceph/ceph/commits/0e5746d44ef44ba1c7e7c0c3c3828fdfc8b14fc2

2023-11-29 05:56 UTC, vshankar commented
> `qa: don't fail on gather_mount_info() failure ` should go in `main` too if we plan to regularly test LTS kernels in upstream QA (I agree we should do that).

ACK. I'll send a change.

2023-11-29 06:05 UTC, vshankar commented
> I'd suggest backporting https://github.com/ceph/ceph/commits/0e5746d44ef44ba1c7e7c0c3c3828fdfc8b14fc2

So, that change does away with centos8/rhel8 and ubuntu 20.04, which this change adds to supported-all-distro. So, I'm not 100% clear if I understand the need for backport.

2023-11-29 15:36 UTC, cbodley commented on qa/distros/supported-all-distro/ubuntu_20.04.yaml
> +../all/ubuntu_20.04.yaml
https://github.com/ceph/ceph/pull/53517 removed 20.04 as a supported distro for the squid release, so it shouldn't be added back. if this piece is needed on reef, it shouldn't go through main first

2023-11-29 15:39 UTC, cbodley commented
> I'd suggest backporting https://github.com/ceph/ceph/commits/0e5746d44ef44ba1c7e7c0c3c3828fdfc8b14fc2

@badone it's not clear from that link whether you mean backporting all of https://github.com/ceph/ceph/pull/53517? that concerns dropping distro support for the squid release, but for reef we need to continue testing all of the distros that reef supports

2023-11-29 15:47 UTC, cbodley commented on qa/distros/supported-all-distro/ubuntu_20.04.yaml
> +../all/ubuntu_20.04.yaml
oops, this is a pr against reef :)

2023-11-29 22:25 UTC, badone commented
> > I'd suggest backporting https://github.com/ceph/ceph/commits/0e5746d44ef44ba1c7e7c0c3c3828fdfc8b14fc2
> 
> @badone it's not clear from that link whether you mean backporting all of #53517? that concerns dropping distro support for the squid release, but for reef we need to continue testing all of the distros that reef supports

I was thinking of specifically this commit, https://github.com/ceph/ceph/commit/0e5746d44ef44ba1c7e7c0c3c3828fdfc8b14fc2 and any related changes. Seems I added an extra 's' sorry.

2023-11-30 08:55 UTC, vshankar commented
This change required one final tweaking to get the tests running to completion. Commit 3d0a927ecf530ba7ef1d2636afc282af7c44435c.

Ran Yuri's branch which has the backport fix - wip-yuri11-testing-2023-11-21-0932-reef with --filter kclient,ubuntu_20.04. Test results here: https://pulpito.ceph.com/vshankar-2023-11-30_06:13:59-smoke-wip-yuri11-testing-2023-11-21-0932-reef-distro-default-smithi/

With reef-release branch the tests fail - https://pulpito.ceph.com/vshankar-2023-11-30_06:09:58-smoke-reef-release-distro-default-smithi/

... with the MDS crash:

```
2023-11-30T06:32:36.969 INFO:tasks.ceph.mds.a.smithi132.stderr:/build/ceph-18.2.0-1242-g6c86da32/src/mds/Server.cc: In function 'CInode* Server::prepare_new_inode(MDRequestRef&, CDir*, inodeno_t, unsigned int, const file_layout_t*)' thread 7f28793e1700 time 2023-11-30T06:
32:36.969022+0000
2023-11-30T06:32:36.969 INFO:tasks.ceph.mds.a.smithi132.stderr:/build/ceph-18.2.0-1242-g6c86da32/src/mds/Server.cc: 3441: FAILED ceph_assert(_inode->gid != (unsigned)-1)
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: ceph version 18.2.0-1242-g6c86da32 (6c86da324d5733ef2768551db91b670156088da7) reef (stable)
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x128) [0x7f287f81f2c5]
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 2: /usr/lib/ceph/libceph-common.so.2(+0x320481) [0x7f287f81f481]
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 3: (Server::prepare_new_inode(boost::intrusive_ptr<MDRequestImpl>&, CDir*, inodeno_t, unsigned int, file_layout_t const*)+0x1ae9) [0x55759ccd8039]
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 4: (Server::handle_client_mkdir(boost::intrusive_ptr<MDRequestImpl>&)+0x1cd) [0x55759ccd9fed]
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 5: (Server::handle_client_request(boost::intrusive_ptr<MClientRequest const> const&)+0x614) [0x55759ccf5d94]
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 6: (Server::dispatch(boost::intrusive_ptr<Message const> const&)+0xf4) [0x55759ccfa964]
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 7: (MDSRank::_dispatch(boost::intrusive_ptr<Message const> const&, bool)+0x5a6) [0x55759cc45246]
2023-11-30T06:32:36.974 INFO:tasks.ceph.mds.a.smithi132.stderr: 8: (MDSRankDispatcher::ms_dispatch(boost::intrusive_ptr<Message const> const&)+0x5c) [0x55759cc4583c]
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr: 9: (MDSDaemon::ms_dispatch2(boost::intrusive_ptr<Message> const&)+0x1bf) [0x55759cc2f35f]
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr: 10: (Messenger::ms_deliver_dispatch(boost::intrusive_ptr<Message> const&)+0x468) [0x7f287fa994f8]
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr: 11: (DispatchQueue::entry()+0x657) [0x7f287fa96a97]
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr: 12: (DispatchQueue::DispatchThread::entry()+0x11) [0x7f287fb5c3a1]
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr: 13: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f287f4a9609]
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr: 14: clone()
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr:*** Caught signal (Aborted) **
2023-11-30T06:32:36.975 INFO:tasks.ceph.mds.a.smithi132.stderr: in thread 7f28793e1700 thread_name:ms_dispatch
```

2023-11-30 09:21 UTC, vshankar commented
@yuriw - since an additional commit was added, I've requested review from @batrick. Once this change gets an ACK, its good to merge along with #54407

2023-11-30 16:04 UTC, batrick approved these changes

2023-11-30 16:43 UTC, merged

2023-12-01 00:01 UTC, badone commented
I'll create a follow-up backport of https://github.com/ceph/ceph/pull/53517/commits/0e5746d44ef44ba1c7e7c0c3c3828fdfc8b14fc2 to reef.

2024-03-24 20:10 UTC, batrick commented
@vshankar why was `qa/smoke: run smoke suite with all supported distros` not also submitted to `main`?

The reef smoke suite is now 5x larger than the other branches.

2024-03-24 20:10 UTC, batrick commented
https://pulpito.ceph.com/?suite=smoke

2024-03-25 04:24 UTC, vshankar commented
> @vshankar why was `qa/smoke: run smoke suite with all supported distros` not also submitted to `main`?

OK. I think we missed that partly due to https://github.com/ceph/ceph/pull/46882 eventually be able to allow distro kernel testing in fs suite. I'll submit this change to q/s releases.

> The reef smoke suite is now 5x larger than the other branches.

That was intentional as mentioned in the commit message - not ideal, but unless we get distro kernel testing coverage in fs suite, we'll have to live with a bloated smoke suite.

2024-03-25 07:22 UTC, vshankar commented
> > @vshankar why was `qa/smoke: run smoke suite with all supported distros` not also submitted to `main`?
> 
> OK. I think we missed that partly due to #46882 eventually be able to allow distro kernel testing in fs suite. I'll submit this change to q/s releases.

I checked back on this. So, main branch does not have `supported-all-distro`:

```
/work/ceph on wip-smoke-all-distro *1 !4 ?2 ❯ ls -l qa/distros/supported                                                                                                                                             with cephalopod@cephalopod-octo
total 0
lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04 centos_latest.yaml -> ../all/centos_latest.yaml
lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04 ubuntu_latest.yaml -> ../all/ubuntu_latest.yaml
/work/ceph on wip-smoke-all-distro *1 !4 ?2 ❯ ls -l qa/distros/supported-random-distro\$                                                                                                                             with cephalopod@cephalopod-octo
total 0
-rw-r--r--. 1 cephalopod cephalopod  0 Jan  7  2022 '$'
lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04  centos_latest.yaml -> ../all/centos_latest.yaml
lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04  ubuntu_latest.yaml -> ../all/ubuntu_latest.yaml
```

and smoke/basic points to:

```
ls -l qa/suites/smoke/basic/supported-random-distro\$                                                                                                                  with cephalopod@cephalopod-octo
lrwxrwxrwx. 1 cephalopod cephalopod 42 Mar 25 03:14 'qa/suites/smoke/basic/supported-random-distro$' -> '../../../distros/supported-random-distro$/'
```

So, there is merit in pointing that to supported and not having to randomly choose a distro (for some/basic) and have the suite run with _all_ (supported) distress, but the real value of this was to run smoke with oldi'sh kernels...

2024-03-26 00:13 UTC, batrick commented
> > > @vshankar why was `qa/smoke: run smoke suite with all supported distros` not also submitted to `main`?
> > 
> > 
> > OK. I think we missed that partly due to #46882 eventually be able to allow distro kernel testing in fs suite. I'll submit this change to q/s releases.
> 
> I checked back on this. So, main branch does not have `supported-all-distro`:
> 
> ```
> /work/ceph on wip-smoke-all-distro *1 !4 ?2 ❯ ls -l qa/distros/supported                                                                                                                                             with cephalopod@cephalopod-octo
> total 0
> lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04 centos_latest.yaml -> ../all/centos_latest.yaml
> lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04 ubuntu_latest.yaml -> ../all/ubuntu_latest.yaml
> /work/ceph on wip-smoke-all-distro *1 !4 ?2 ❯ ls -l qa/distros/supported-random-distro\$                                                                                                                             with cephalopod@cephalopod-octo
> total 0
> -rw-r--r--. 1 cephalopod cephalopod  0 Jan  7  2022 '$'
> lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04  centos_latest.yaml -> ../all/centos_latest.yaml
> lrwxrwxrwx. 1 cephalopod cephalopod 25 Feb 28 09:04  ubuntu_latest.yaml -> ../all/ubuntu_latest.yaml
> ```
> 
> and smoke/basic points to:
> 
> ```
> ls -l qa/suites/smoke/basic/supported-random-distro\$                                                                                                                  with cephalopod@cephalopod-octo
> lrwxrwxrwx. 1 cephalopod cephalopod 42 Mar 25 03:14 'qa/suites/smoke/basic/supported-random-distro$' -> '../../../distros/supported-random-distro$/'
> ```
> 
> So, there is merit in pointing that to supported and not having to randomly choose a distro (for some/basic) and have the suite run with _all_ (supported) distress, but the real value of this was to run smoke with oldi'sh kernels...

Honestly, `$` is not necessary with subsets. I'd rather just convert to using `distro/supported`.

I will revive work on the kernel PR soon I think. My time is beginning to free up.