quincy: qa/cephfs: improvements for name generators in test_volumes.py
ceph/ceph pull request #54727
Opened 2023-11-30 06:27 UTC by rishabh-d-dave

backport tracker: https://tracker.ceph.com/issues/63687

---

backport of https://github.com/ceph/ceph/pull/54631
parent tracker: https://tracker.ceph.com/issues/63680

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2023-12-13 06:07 UTC, vshankar commented
jenkins retest this please

2024-01-23 05:11 UTC, vshankar commented
@rishabh-d-dave This change needs additional commits from @neesingh-rh PR. @neesingh-rh please link the respective PR please?

2024-01-23 06:20 UTC, neesingh-rh commented
> @rishabh-d-dave This change needs additional commits from @neesingh-rh PR. @neesingh-rh please link the respective PR please?

Yup, its this PR: https://github.com/ceph/ceph/pull/54206

2024-01-23 09:41 UTC, vshankar requested changes
NACK to prevent accidental merge.

2025-02-11 06:57 UTC, vshankar commented
Quincy is EOL.

2025-02-11 06:57 UTC, closed without merging