reef: qa/cephfs: improvements for name generators in test_volumes.py
ceph/ceph pull request #54729
Opened 2023-11-30 07:10 UTC by rishabh-d-dave

backport tracker: https://tracker.ceph.com/issues/63688

---

backport of https://github.com/ceph/ceph/pull/54631
parent tracker: https://tracker.ceph.com/issues/63680

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-03-14 21:12 UTC, batrick requested changes
Missing a invocation of `_generate_random_...` introduced by #54207. (Please rebase.)

2024-03-19 12:11 UTC, vshankar requested changes
Failure here - https://pulpito.ceph.com/yuriw-2024-03-16_15:03:17-fs-wip-yuri10-testing-2024-03-15-1653-reef-distro-default-smithi/7606241/

@rishabh-d-dave please rebase this with changes to tests to use the new helper name.

2024-03-22 17:16 UTC, rishabh-d-dave commented
> Failure here - https://pulpito.ceph.com/yuriw-2024-03-16_15:03:17-fs-wip-yuri10-testing-2024-03-15-1653-reef-distro-default-smithi/7606241/
> 
> @rishabh-d-dave please rebase this with changes to tests to use the new helper name.

Fixed.

2024-03-25 21:19 UTC, ljflores commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrackercephcomissues65048

2024-03-26 05:34 UTC, vshankar commented
jenkins test make check

2024-04-01 22:43 UTC, ljflores commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrackercephcomissues65202

2024-04-02 05:56 UTC, vshankar approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/Reef#2024-03-28

2024-04-02 06:47 UTC, merged