common: LogClient do not output meaningless logs by default
ceph/ceph pull request #54780
Opened 2023-12-05 08:34 UTC by jianwei1216

common: LogClient do not output meaningless logs by default

    the default output log to syslog/graylog is meaningless
    it will consume a lot of log resources

    Fixes: https://tracker.ceph.com/issues/63727
    Signed-off-by: zhangjianwei <zhangjianwei2@cmss.chinamobile.com>

2023-12-05 08:39 UTC, jianwei1216 commented
@batrick 
Can you also give me another look at this commit?

Although it only changes one log level, its effect on controlling invalid logs is obvious!

2023-12-05 08:47 UTC, jianwei1216 commented
@batrick 
You don’t want to add a log to syslog in front of every log, right?

such as

```
log to syslog
log item 1


log to syslog
log item 2


log to syslog
log item 3

... ...
```

2023-12-05 13:36 UTC, batrick requested changes

2023-12-05 13:36 UTC, batrick commented on src/common/LogClient.cc
> +    ldout(cct,30) << __func__ << " log to syslog"  << dendl;
I'd rather see these messages completely removed.

2023-12-06 02:56 UTC, jianwei1216 commented on src/common/LogClient.cc
> +    ldout(cct,30) << __func__ << " log to syslog"  << dendl;
done

2023-12-11 20:40 UTC, batrick approved these changes

2024-01-18 06:41 UTC, kamoltat commented
RADOS APPROVED
https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcD0n65np11923-wip-yuri-testing-2024-01-09-1331

2024-01-18 15:38 UTC, merged