mon/AuthMonitor: fix potential repeated global id
ceph/ceph pull request #55006
Opened 2023-12-26 11:34 UTC by shminjs

When we expand or shrink monitors, there is the possibility of repeatedly allocating global ids. Because the calculation of last_allocated_id depends on mon_num and mon_rank, and expand or shrink monitors changes mon_num and mon_rank. A simple fix is to reset last_allocated_id when the election is complete.

Fixs: to be continue
Signed-off-by: shimin shimin@kuaishou.com

2023-12-26 11:44 UTC, shminjs commented
Use the following code to check correctness

```
def assign_global_id(last_allocated_id, mon_num, mon_rank, max_global_id, total_allocations):
    allocated_ids = []
    for _ in range(total_allocations):
        id = last_allocated_id + 1
        remainder = id % mon_num
        if remainder:
            remainder = mon_num - remainder
        id += remainder + mon_rank

        if id >= max_global_id:
            break

        last_allocated_id = id
        allocated_ids.append(id)

    return allocated_ids

last_allocated_id = 10000
max_global_id = 100000000
total_allocations = 100


mon_a_list_3 = assign_global_id(last_allocated_id, 3, 0, max_global_id, total_allocations)
mon_b_list_3 = assign_global_id(last_allocated_id, 3, 1, max_global_id, total_allocations)
mon_c_list_3 = assign_global_id(last_allocated_id, 3, 2, max_global_id, total_allocations)


mon_a_list_5 = assign_global_id(last_allocated_id, 5, 0, max_global_id, total_allocations)
mon_b_list_5 = assign_global_id(last_allocated_id, 5, 1, max_global_id, total_allocations)
mon_c_list_5 = assign_global_id(last_allocated_id, 5, 2, max_global_id, total_allocations)
mon_d_list_5 = assign_global_id(last_allocated_id, 5, 3, max_global_id, total_allocations)
mon_e_list_5 = assign_global_id(last_allocated_id, 5, 4, max_global_id, total_allocations)


intersection_a = set(mon_a_list_5).intersection(set(mon_b_list_3 + mon_c_list_3))
intersection_b = set(mon_b_list_5).intersection(set(mon_a_list_3 + mon_c_list_3))
intersection_c = set(mon_c_list_5).intersection(set(mon_a_list_3 + mon_b_list_3))

print(intersection_a)
print(intersection_b)
print(intersection_c)
```

2023-12-26 12:10 UTC, shminjs commented
jenkins test make check

2023-12-26 16:17 UTC, shminjs commented
jenkins test make check arm64

2024-01-03 06:45 UTC, shminjs commented
jenkins test make check arm64

2024-01-11 06:35 UTC, shminjs commented
jenkins test make check arm64

2024-01-16 12:30 UTC, shminjs commented
jenkins test make check arm64

2024-01-17 06:34 UTC, shminjs commented
jenkins test make check arm64

2024-01-30 03:01 UTC, shminjs commented
jenkins test make check arm64

2024-03-30 08:13 UTC, shminjs commented
does anyone handle this issue?

2024-03-30 08:19 UTC, shminjs commented
cephfs client depend on global_id, and repeated global_id would result some inconsistent problem.

2024-06-11 01:22 UTC, shminjs commented
This is a bug, need to fix

2024-08-16 07:20 UTC, rzarzynski approved these changes

2024-08-29 20:55 UTC, batrick approved these changes

2024-09-16 20:06 UTC, batrick commented
This PR is under test in [https://tracker.ceph.com/issues/68089](https://tracker.ceph.com/issues/68089).

2024-09-17 15:39 UTC, batrick requested changes
This failed QA, see for example:

https://pulpito.ceph.com/pdonnell-2024-09-17_02:09:51-fs-wip-pdonnell-testing-20240916.200549-debug-distro-default-smithi/7908340/

and the leader mon log:

[ceph-mon.a.log.gz](https://github.com/user-attachments/files/17030904/ceph-mon.a.log.gz)

2024-09-18 12:13 UTC, shminjs commented
> This failed QA, see for example:
> 
> https://pulpito.ceph.com/pdonnell-2024-09-17_02:09:51-fs-wip-pdonnell-testing-20240916.200549-debug-distro-default-smithi/7908340/
> 
> and the leader mon log:
> 
> [ceph-mon.a.log.gz](https://github.com/user-attachments/files/17030904/ceph-mon.a.log.gz)

ok, I check the log and reply soon as possible

2024-12-23 09:01 UTC, closed without merging