pacific: mgr/BaseMgrModule: Optimize CPython Call in Finish Function
ceph/ceph pull request #55109
Opened 2024-01-09 16:28 UTC by k0ste

backport tracker: https://tracker.ceph.com/issues/63978

---

backport of https://github.com/ceph/ceph/pull/54634
parent tracker: https://tracker.ceph.com/issues/59580

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-01-10 00:18 UTC, ljflores commented
If this is a must for 16.2.15, please add it to https://github.com/ceph/ceph/milestone/17.

2024-01-10 05:40 UTC, k0ste commented
> If this is a must for 16.2.15, please add it to https://github.com/ceph/ceph/milestone/17 since Pacific is going EOL.

Only developers can edit labels and milestones, I'm not

2024-01-17 16:15 UTC, ljflores commented
This changeset wasn't staging in the main branch enough to observe long-term behavior. As the .15 is the last minor release of the series (pacific goes EOL), there won't be more time. Let's close it.

2024-01-17 16:15 UTC, ljflores commented
Thanks for your contribution!

2024-02-01 17:17 UTC, ljflores commented
Will see how this goes in testing since there is a little more time for 16.2.15.

2024-02-03 15:10 UTC, tchaikov approved these changes
lgtm

2024-02-05 17:57 UTC, ljflores requested changes
Blocking merging until @rzarzynski and @NitzanMordhai can take a final look.

The rados suite passed though: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcN8lquGmt1946-wip-yuri2-testing-2024-02-01-0939-pacific

2024-02-06 06:46 UTC, NitzanMordhai commented
> Blocking merging until @rzarzynski and @NitzanMordhai can take a final look.
> 
> The rados suite passed though: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcN8lquGmt1946-wip-yuri2-testing-2024-02-01-0939-pacific

looks good to me, although only 1 test was for the rest module, but it cover all options. @rzarzynski any thoughts?

2024-02-06 17:54 UTC, ljflores approved these changes
We discussed it; this can be included.

2024-02-06 17:54 UTC, merged