feat: add mclock queue perfcounter
ceph/ceph pull request #55295
Opened 2024-01-24 09:28 UTC by jianwei1216

```
Easy to visualize the number of ops
in each subqueue of mclock.

Add request statistics for each
op_scheduler_class

ceph daemon osd.0 perf dump osd
{
    "osd": {
        "mclock_immdiate_op": 640,
        "mclock_client_op": 1229,
        "mclock_store_db_op": 129,
        "mclock_recovery_op": 887,
        "mclock_best_effort_op": 925
    }
}
```

2024-01-24 09:30 UTC, jianwei1216 commented
I will create an issue later

2024-01-24 14:16 UTC, tchaikov commented
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

2024-01-25 02:38 UTC, jianwei1216 commented
@sseshasa @athanatos @rzarzynski What do you think？Thank you.

2024-01-25 06:01 UTC, sseshasa requested changes

2024-01-25 06:06 UTC, sseshasa requested changes

2024-01-25 06:06 UTC, sseshasa commented on src/osd/osd_perf_counters.cc
> +  // mclock QoS queue op counter
General comment about counter descriptions:

The counter description could just read "osd op_scheduler_class::immediate type op count" for example. The same applies to other counter descriptions. Remove the word "handle" from the descriptions.

2024-01-25 06:06 UTC, sseshasa commented on src/osd/osd_perf_counters.cc
> +  osd_plb.add_u64_counter(l_osd_mclock_immdiate_op, "mclock_immdiate_op",
s/mclock_immdiate_op/mclock_immediate_op

2024-01-29 10:35 UTC, jianwei1216 commented on src/osd/osd_perf_counters.h
> +  // mclock queue
did you mean? 
- When each shard-mclock-queue is initialized, initialize its own PerfCounters separately?
- Record the count of immediate/client/recovery/best_effort requests in each PerfCounters
- For example,
  - if an osd has 5 shard-mclock queues, 
  - there will be 5 shard-mclock PerfCounters.

Is my understanding correct? @sseshasa 

such as
```
ceph daemon osd.0 perf dump osd
{
    "osd": {
        "mclock_immediate_op": 3200, //sum
        "mclock_client_op": 6145,  //sum
        "mclock_recovery_op": 4435, //sum
        "mclock_best_effort_op": 4625  //sum
    }
    "shard-0-mclock-queue" : {
        "mclock_immediate_op": 640,
        "mclock_client_op": 1229,
        "mclock_recovery_op": 887,
        "mclock_best_effort_op": 925
    }
    "shard-1-mclock-queue" : {
        "mclock_immediate_op": 640,
        "mclock_client_op": 1229,
        "mclock_recovery_op": 887,
        "mclock_best_effort_op": 925
    }
    "shard-2-mclock-queue" : {
        "mclock_immediate_op": 640,
        "mclock_client_op": 1229,
        "mclock_recovery_op": 887,
        "mclock_best_effort_op": 925
    }
    "shard-3-mclock-queue" : {
        "mclock_immediate_op": 640,
        "mclock_client_op": 1229,
        "mclock_recovery_op": 887,
        "mclock_best_effort_op": 925
    }
    "shard-4-mclock-queue" : {
        "mclock_immediate_op": 640,
        "mclock_client_op": 1229,
        "mclock_recovery_op": 887,
        "mclock_best_effort_op": 925
    }
}
```

2024-01-29 12:04 UTC, sseshasa commented on src/osd/osd_perf_counters.h
> +  // mclock queue
@jianwei1216 Yes, this is what I am proposing.

2024-01-29 13:35 UTC, jianwei1216 commented
jenkins test make check

2024-01-29 13:35 UTC, jianwei1216 commented
jenkins test make check (arm64)

2024-01-30 05:38 UTC, jianwei1216 commented
jenkins test make check

2024-04-29 06:01 UTC, closed without merging

2024-06-27 08:27 UTC, jianwei1216 commented
@sseshasa @athanatos  Could you please reopen this PR for me?

2024-06-27 08:28 UTC, jianwei1216 commented
> @sseshasa @athanatos Could you please reopen this PR for me?

I'll open a new PR.

Ignore

2024-06-27 08:37 UTC, jianwei1216 commented
NEW PR: https://github.com/ceph/ceph/pull/58302