quincy: qa: fix rank_asok() to handle errors from asok commands
ceph/ceph pull request #55301
Opened 2024-01-24 14:20 UTC by neesingh-rh

backport tracker: https://tracker.ceph.com/issues/64143

---

backport of https://github.com/ceph/ceph/pull/54208
parent tracker: https://tracker.ceph.com/issues/63176

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2024-02-07 15:52 UTC, vshankar commented
jenkins test api

2024-02-07 15:52 UTC, vshankar commented
jenkins retest this please

2024-06-20 10:14 UTC, joscollin requested changes
@neesingh-rh Please resolve the conflicts. I'm moving the tracker to `In Progress` for now. Please update when the PR is ready.

2024-07-24 02:30 UTC, lxbsz commented
jenkins test api

2024-08-02 05:30 UTC, lxbsz commented
This PR is under test in [https://tracker.ceph.com/issues/67315](https://tracker.ceph.com/issues/67315).

2024-08-19 10:34 UTC, rishabh-d-dave approved these changes
QA run was successful - https://tracker.ceph.com/projects/cephfs/wiki/Quincy#19-Aug-2024

2024-08-19 10:54 UTC, merged