reef: qa/tasks/cephadm: enable mon_cluster_log_to_file
ceph/ceph pull request #55431
Opened 2024-02-02 19:52 UTC by adk3798

Backport of https://github.com/ceph/ceph/pull/54312

Without cluster_log_to_file we have nothing to grep for errors:

2023-10-27T16:06:59.111 DEBUG:teuthology.orchestra.run.smithi150:> sudo egrep '\[ERR\]|\[WRN\]|\[SEC\]' /var/log/ceph/38cc7fce-74d9-11ee-8db9-212e2dc638e7/ceph.log | egrep -v '\(MDS_ALL_DOWN\)' | egrep -v '\(MDS_UP_LESS_THAN_MAX\)' | head -n 1 2023-10-27T16:06:59.141 INFO:teuthology.orchestra.run.smithi150.stderr:grep: /var/log/ceph/38cc7fce-74d9-11ee-8db9-212e2dc638e7/ceph.log: No such file or directory

Set mon_cluster_log_to_file = true.

Fixes: https://tracker.ceph.com/issues/63425
Signed-off-by: Dan van der Ster <dan.vanderster@clyso.com>
(cherry picked from commit 822e6b01f909dff79b336bb2fc029de4663b428a) (cherry picked from commit df79c84fbfc831dc9098b0b20638d18b0f46aa1e)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-02-08 15:51 UTC, idryomov approved these changes

2024-02-08 16:05 UTC, idryomov commented
Not assigning to 18.2.x milestone until there is clarity on https://tracker.ceph.com/issues/64343.

2024-02-15 19:54 UTC, ljflores commented
> Not assigning to 18.2.x milestone until there is clarity on https://tracker.ceph.com/issues/64343.

Thanks Ilya, my take on this is that we should run this through the rados/orch suite, get results, and then create a commit to address whitelisting as was done in this PR: https://github.com/ceph/ceph/pull/55523

Although, for reef (and quincy), I would prefer to have these pieces merge together.

2024-02-15 19:55 UTC, ljflores requested changes
Blocking this until we have a commit to whitelist appropriate warnings in the rados/orch suite (I can help with this). We can put this PR through the rados suite, and then use the results to create the whitelist commit.

2025-02-01 15:31 UTC, idryomov commented
Reopening for this to go with https://github.com/ceph/ceph/pull/61434.

2025-02-13 18:37 UTC, adamemerson commented
jenkins test windows

2025-03-05 08:05 UTC, NitzanMordhai commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrackercephcomissues69634

2025-03-05 18:42 UTC, ljflores approved these changes

2025-03-05 18:43 UTC, merged