quincy: qa: bump up scrub status command timeout
ceph/ceph pull request #55916
Opened 2024-03-04 09:58 UTC by mchangir

backport tracker: https://tracker.ceph.com/issues/64224

---

backport of https://github.com/ceph/ceph/pull/54446
parent tracker: https://tracker.ceph.com/issues/63411

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2024-04-12 09:46 UTC, mchangir commented
manually rebased and fixed conflict between `get_ceph_cmd_stdout()` and explicit call to `self.ceph_cluster.mon_manager.raw_cluster_cmd()`

2024-06-20 10:11 UTC, joscollin commented
jenkins retest this please

2024-06-21 05:58 UTC, joscollin requested changes
@mchangir Please resolve the make check failure:
./tasks/vstart_runner.py:814:27: F821 undefined name 'RADOS_CMD'

2024-06-21 12:54 UTC, mchangir commented
> @mchangir Please resolve the make check failure: ./tasks/vstart_runner.py:814:27: F821 undefined name 'RADOS_CMD'

@joscollin fixed the issue

2024-06-24 08:11 UTC, joscollin commented
jenkins test make check

2024-08-02 05:30 UTC, lxbsz commented
This PR is under test in [https://tracker.ceph.com/issues/67315](https://tracker.ceph.com/issues/67315).

2024-08-19 10:34 UTC, rishabh-d-dave approved these changes
QA run was successful - https://tracker.ceph.com/projects/cephfs/wiki/Quincy#19-Aug-2024

2024-08-19 10:54 UTC, merged