quincy: rgw/beast: Enable SSL session-id reuse speedup mechanism
ceph/ceph pull request #56119
Opened 2024-03-11 11:07 UTC by mkogan1

backport tracker: https://tracker.ceph.com/issues/64767

---

backport of https://github.com/ceph/ceph/pull/55967
parent tracker: https://tracker.ceph.com/issues/64719

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

2024-03-11 15:02 UTC, cbodley commented
> The following tests FAILED:
	  7 - run-tox-mgr-dashboard-py3 (Failed)

2024-03-11 15:02 UTC, cbodley commented
jenkins test make check

2024-03-11 15:03 UTC, cbodley commented
jenkins test api

2024-03-11 15:07 UTC, mattbenjamin commented
> > The following tests FAILED:
> > 7 - run-tox-mgr-dashboard-py3 (Failed)

this failure doesn't seem to be unique to this PR

2024-03-12 10:36 UTC, mkogan1 commented
jenkins test make check

2024-03-20 10:48 UTC, mkogan1 commented
jenkins test make check

2024-04-17 20:47 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65558](https://tracker.ceph.com/issues/65558).

2024-04-17 22:22 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65561](https://tracker.ceph.com/issues/65561).

2024-04-22 20:18 UTC, cbodley requested changes
possible regression here, want to investigate further

2024-04-22 21:06 UTC, yuriw commented
ref: https://tracker.ceph.com/issues/65558

2024-04-23 15:13 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65638](https://tracker.ceph.com/issues/65638).

2024-05-09 15:02 UTC, cbodley commented
@mkogan1 can you please include the fix from https://tracker.ceph.com/issues/65887?

2024-05-13 15:04 UTC, mkogan1 commented
jenkins test api

2024-05-13 15:23 UTC, cbodley approved these changes

2024-08-06 15:20 UTC, merged