RGW: realm get default command should show the realm name along with id
ceph/ceph pull request #56159
Opened 2024-03-13 11:52 UTC by shreyanshjain7174

`radosgw-admin realm get default` command should show the realm name along with id of the default realm. 

Fixes: https://tracker.ceph.com/issues/64888

Signed-off-by: Shreyansh Sancheti <ssanchet@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-03-22 05:27 UTC, thotz requested changes
Some minor nits, have check realm rename scenarios for this PR??

2024-03-22 05:27 UTC, thotz commented on src/rgw/rgw_admin.cc
> +  cout << "default realm name: " << default_name << std::endl;
Both log messages can be combined

2024-03-22 05:27 UTC, thotz commented on src/rgw/rgw_admin.cc
> +  string default_name;
indentation issue??

2024-03-25 05:35 UTC, shreyanshjain7174 commented
jenkins test api
jenkins test make check

2024-06-23 10:01 UTC, closed without merging

2025-04-11 13:29 UTC, mattbenjamin commented on src/rgw/rgw_zone_types.h
>      ENCODE_START(1, 1, bl);
doesn't this need a version increment?