Fixes the error prompted by the check bugprone-branch-clone in clang-…
ceph/ceph pull request #56232
Opened 2024-03-15 20:47 UTC by Suyashd999

When executing the command: `clang-tidy -checks='bugprone-branch-clone' OSD.cc` 

clang-tidy gave the warning: `warning: repeated branch in conditional chain [bugprone-branch-clone]`

This PR aims to fix it.   

Signed-off-by: Suyash Dongre suyashd999@gmail.com

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-03-15 20:48 UTC, Suyashd999 commented
@yuvalif Can you take a look at this?

2024-03-16 06:11 UTC, Suyashd999 commented
jenkins test api

2024-03-16 06:12 UTC, Suyashd999 commented
jenkins test make check

2024-04-03 15:03 UTC, ronen-fr commented on src/osd/OSD.cc
> +                << start << dendl;
it does not seem like you are keeping the existing logic ??

2024-04-03 15:08 UTC, ronen-fr requested changes
pls show that sub_want_increment() and sub_want() are called under the same conditions after the change.
Also - what exactly was improved by the change?

2024-04-03 15:30 UTC, ljflores commented
Hey @Suyashd999, can you fix the commit title based on the guidelines here? https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst

Also, I think you should open a Tracker issue (from tracker.ceph.com) to report the issue with the original clang-tidy report.

2024-04-03 16:00 UTC, ljflores commented
Sure @Suyashd999, that will work fine.

2024-04-03 16:01 UTC, ronen-fr commented
@Suyashd999 - you may want to close this PR, and issue a new one. There is too little in common between the "old" PR and the future one.

2024-04-03 16:32 UTC, Suyashd999 commented
> @Suyashd999 - you may want to close this PR, and issue a new one. There is too little in common between the "old" PR and the future one.

@ronen-fr Yes will do, Thanks!

2024-04-22 13:30 UTC, closed without merging