src : correction in the description of mds_log_max_segments config
ceph/ceph pull request #56634
Opened 2024-04-02 12:01 UTC by neesingh-rh

Fixes: https://tracker.ceph.com/issues/64064
Signed-off-by: Neeraj Pratap Singh <neesingh@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-04-02 13:26 UTC, leonid-s-usov requested changes, later dismissed
There are more places to be addressed post #48732. The new minimum of `8` also invalidates some tests that try to set the property to `1`. I found two such cases:

* `qa/tasks/cephfs/test_meta_injection.py:TestMetaInjection.test_meta_injection`
* `qa/workunits/restart/test-backtraces.py:flush()`

I'm not ready to say whether those tests will need a more significant refactoring or just set the value to the new minimum (8)

2024-04-04 01:17 UTC, batrick requested changes, later dismissed
Use `mds: ` for the component please.

And I echo @leonid-s-usov 's comment.

2024-04-04 09:45 UTC, leonid-s-usov commented
I find it suspicious that the updated tests weren't failing before this change. @neesingh-rh, could you please verify that the tests are being run by teuthology?

2024-06-12 10:10 UTC, neesingh-rh commented
> There are more places to be addressed post #48732. The new minimum of `8` also invalidates some tests that try to set the property to `1`. I found two such cases:
> 
>     * `qa/tasks/cephfs/test_meta_injection.py:TestMetaInjection.test_meta_injection`
> 
>     * `qa/workunits/restart/test-backtraces.py:flush()`
> 
> 
> I'm not ready to say whether those tests will need a more significant refactoring or just set the value to the new minimum (8)

As asked by @leonid-s-usov , I did check some of the runs to check why the tests weren't failing before. I did check the code and we should be getting the error caught here: https://github.com/ceph/ceph/blob/main/src/common/ceph_context.cc#L613 . I didn't find this test being run in teuthology. @vshankar Any reason? Or Am I wrong somewhere.

2024-09-06 14:12 UTC, vshankar commented
@neesingh-rh Do you plan to refurbish this change? As far as https://github.com/ceph/ceph/pull/56634#issuecomment-2162627400 is concerned, please look into one of the latest fs suite runs to assess if the tests are being run and the relevant config (set to 1) is indeed getting exercised.

2024-09-12 12:10 UTC, vshankar commented
@neesingh-rh ping

2024-09-12 12:15 UTC, neesingh-rh commented
> @neesingh-rh ping

The PR addresses the requirements of the respective tracker. Need to look one of the latest runs for this comment:https://github.com/ceph/ceph/pull/56634#issuecomment-2036707767

2024-10-24 10:04 UTC, vshankar commented
@neesingh-rh Looks like test_meta_injection isn't run from anywhere

```
git grep test_meta_injection
qa/tasks/cephfs/test_meta_injection.py:    def test_meta_injection(self):
```

color me surprised o_O

2024-10-24 11:21 UTC, neesingh-rh commented
> @neesingh-rh Looks like test_meta_injection isn't run from anywhere
> 
> ```
> git grep test_meta_injection
> qa/tasks/cephfs/test_meta_injection.py:    def test_meta_injection(self):
> ```
> 
> color me surprised o_O

yes, May be it was added to test it locally. I am not sure about the reason. But yeah, the PR updates the config option with its new min value. So, we can go ahead with this. What say?

2024-10-24 16:35 UTC, vshankar commented
> > @neesingh-rh Looks like test_meta_injection isn't run from anywhere
> > ```
> > git grep test_meta_injection
> > qa/tasks/cephfs/test_meta_injection.py:    def test_meta_injection(self):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > color me surprised o_O
> 
> yes, May be it was added to test it locally. I am not sure about the reason. But yeah, the PR updates the config option with its new min value. So, we can go ahead with this. What say?

Then let's add changes to start running the test. The type of the config is unsigned int, so setting to -1 should fail.

2024-11-05 06:22 UTC, neesingh-rh commented
> > > @neesingh-rh Looks like test_meta_injection isn't run from anywhere
> > > ```
> > > git grep test_meta_injection
> > > qa/tasks/cephfs/test_meta_injection.py:    def test_meta_injection(self):
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > color me surprised o_O
> > 
> > 
> > yes, May be it was added to test it locally. I am not sure about the reason. But yeah, the PR updates the config option with its new min value. So, we can go ahead with this. What say?
> 
> Then let's add changes to start running the test. The type of the config is unsigned int, so setting to -1 should fail.

@vshankar I have created a yaml file in `suites/fs/functional/tasks` to include it in test

2024-11-05 09:49 UTC, vshankar commented
@neesingh-rh Do you know where `qa/workunits/restart/test-backtraces.py` is run from?

2024-11-05 10:25 UTC, neesingh-rh commented
> @neesingh-rh Do you know where `qa/workunits/restart/test-backtraces.py` is run from?

Oh, this also needs to be taken care of!! I have no idea where should it be added.

2024-11-05 10:33 UTC, vshankar commented
> > @neesingh-rh Do you know where `qa/workunits/restart/test-backtraces.py` is run from?
> 
> Oh, this also needs to be taken care of!! I have no idea where should it be added.

Have you checked the commit history for this file? It may give some insights as where it was intended to be used.

2024-11-05 11:06 UTC, neesingh-rh commented
> > > @neesingh-rh Do you know where `qa/workunits/restart/test-backtraces.py` is run from?
> > 
> > 
> > Oh, this also needs to be taken care of!! I have no idea where should it be added.
> 
> Have you checked the commit history for this file? It may give some insights as where it was intended to be used.

There's only this commit which introduces this patch: https://github.com/ceph/ceph/commit/2678db532a3c68ce636323a2afa11d74b2903f32#diff-b9348581bc6cbe026330924f32da04c17755e28dcaa8a7459056b902a5bf1393R97 . The commit message mentions that `The script includes test cases
that kill the mds at specific kill points and restart it through
teuthology using the teuthology restart task.`

2024-11-07 10:28 UTC, vshankar commented
> > > > @neesingh-rh Do you know where `qa/workunits/restart/test-backtraces.py` is run from?
> > > 
> > > 
> > > Oh, this also needs to be taken care of!! I have no idea where should it be added.
> > 
> > 
> > Have you checked the commit history for this file? It may give some insights as where it was intended to be used.
> 
> There's only this commit which introduces this patch: [2678db5#diff-b9348581bc6cbe026330924f32da04c17755e28dcaa8a7459056b902a5bf1393R97](https://github.com/ceph/ceph/commit/2678db532a3c68ce636323a2afa11d74b2903f32#diff-b9348581bc6cbe026330924f32da04c17755e28dcaa8a7459056b902a5bf1393R97) . The commit message mentions that `The script includes test cases that kill the mds at specific kill points and restart it through teuthology using the teuthology restart task.`

That's from 2013ish, so I think we should not worry about it. This change fixes up in that source, but there isn't anything that's running that test file.

2024-11-07 10:28 UTC, vshankar approved these changes

2024-11-07 10:28 UTC, vshankar commented
jenkins test api

2024-11-11 13:14 UTC, dparmar18 commented on qa/suites/fs/functional/tasks/meta-injection.yaml
> +      - tasks.cephfs.test_meta_injection
the testcase in focus flushes journal and exports the metadata. I hope this isn't prone to some warnings like "slow mds" or "mds behind in trimming"?

2024-11-11 13:21 UTC, dparmar18 commented
Should there be a measure to check for non-negative values? Are we fine to trust the user for setting this and hope they don't get it wrong?

2025-02-04 12:41 UTC, vshankar commented
@mchangir Anything on the test?

2025-02-04 13:15 UTC, dparmar18 commented on qa/suites/fs/functional/tasks/meta-injection.yaml
> +      - tasks.cephfs.test_meta_injection
it's been a while let me go through the PR again

2025-02-13 19:02 UTC, dparmar18 commented on qa/suites/fs/functional/tasks/meta-injection.yaml
> +      - tasks.cephfs.test_meta_injection
i can't really recall what went through my mind when i made this comment. resolving this.

2025-05-29 11:12 UTC, neesingh-rh commented
@mchangir Your testing label has been added, any updates?

2025-06-02 10:28 UTC, mchangir commented
> @mchangir Your testing label has been added, any updates?

probably this wasn't put to test
I'll remove the testing label, somebody else can pick it up

2025-06-11 08:53 UTC, neesingh-rh commented
@rishabh-d-dave Can this be added in any of your runs?

2025-06-13 10:47 UTC, rishabh-d-dave commented
jenkins test windows

2025-06-13 10:53 UTC, rishabh-d-dave commented
This PR is under test in [https://tracker.ceph.com/issues/71663](https://tracker.ceph.com/issues/71663).

2025-06-16 18:27 UTC, rishabh-d-dave commented
> This PR is under test in https://tracker.ceph.com/issues/71663.

A large number of jobs failed to an unrelated error, deferring QA run until it is fixed.

2025-06-17 17:40 UTC, rishabh-d-dave commented
This PR is under test in [https://tracker.ceph.com/issues/71703](https://tracker.ceph.com/issues/71703).

2025-06-25 11:01 UTC, rishabh-d-dave submitted a review, later dismissed
QA run was unsuccessful - https://pulpito.ceph.com/rishabh-2025-06-20_10:40:51-fs-wip-rishabh-testing-20250617.173904-testing-default-smithi/8338511

2025-06-25 11:01 UTC, rishabh-d-dave commented on qa/suites/fs/functional/tasks/meta-injection.yaml
> +      - tasks.cephfs.test_meta_injection
This patch doesn't align with the commit title (`qa: setting the mds_log_max_segments value to new minimum`). Therefore it's better to move it to a different commit, IMO.

Also, IIUC, `test_meta_injection` wasn't run until now. Therefore, It would nice to add an explanation in this commit regarding why it was disabled and why is it being enabled now.

2025-06-26 13:04 UTC, neesingh-rh commented on qa/suites/fs/functional/tasks/meta-injection.yaml
> +      - tasks.cephfs.test_meta_injection
We didn't find any proper reason of not adding it. see the discussion here: https://github.com/ceph/ceph/pull/56634#issuecomment-2435754760 and https://github.com/ceph/ceph/pull/56634#issuecomment-2461865561

2025-07-23 09:18 UTC, neesingh-rh commented
@rishabh-d-dave ping?

2025-07-24 12:10 UTC, rishabh-d-dave commented
Had a chat with Neeraj regarding this PR. He misread this comment - https://github.com/ceph/ceph/pull/56634#pullrequestreview-2957703267 and will be taking a look into the failed QA job.

2026-01-28 07:56 UTC, vshankar commented
Reopened for Umbrella release.

2026-05-12 17:13 UTC, vshankar commented
This PR is under test in [https://tracker.ceph.com/issues/76560](https://tracker.ceph.com/issues/76560).

2026-05-18 05:43 UTC, vshankar commented
jenkins retest this please

2026-06-03 11:35 UTC, neesingh-rh commented
Just rebased

2026-06-04 05:40 UTC, vshankar commented on qa/suites/fs/functional/tasks/meta-injection.yaml
> +      - tasks.cephfs.test_meta_injection
OK, so this change starts testing TestMetaInjection which was previously untested but has the python test case just lying around :/

While that is good, unfortunately, the test fails here: https://pulpito.ceph.com/vshankar-2026-05-25_09:01:16-fs-wip-vshankar-testing-20260525.053031-distro-default-trial/236151/w

with the cephfs-meta-injection tool not found

```
2026-05-25T13:45:55.371 INFO:teuthology.orchestra.run.trial016.stderr:2026-05-25T13:45:55 stdin-killer INFO: command exited with status 0: exiting normally with same code!
2026-05-25T13:45:55.376 DEBUG:teuthology.orchestra.run.trial016:> cephfs-meta-injection --debug-mds=1 --debug-objecter=1 --rank cephfs:0 showm -i 1099511627777 -o /tmp/meta_out
2026-05-25T13:45:55.433 DEBUG:teuthology.orchestra.run:got remote process result: 127
2026-05-25T13:45:55.433 INFO:teuthology.orchestra.run.trial016.stderr:bash: line 1: cephfs-meta-injection: command not found
```

2026-06-04 07:31 UTC, vshankar commented on qa/suites/fs/functional/tasks/meta-injection.yaml
> +      - tasks.cephfs.test_meta_injection
I think we are not packaging cephfs-meta-injection tool. I see that it's included in cephfs_testing under src/CMakeLists.txt though. @neesingh-rh can you check please?

2026-06-04 07:44 UTC, vshankar commented
@neesingh-rh - since this is a yaml change for the most part, I think we can merge this as it is and work on the failing test case. WDYT?

2026-06-04 07:54 UTC, vshankar commented
@neesingh-rh https://tracker.ceph.com/issues/77109

2026-06-04 07:55 UTC, neesingh-rh commented
> @neesingh-rh - since this is a yaml change for the most part, I think we can merge this as it is and work on the failing test case. WDYT?

@vshankar It came from DS, where the issue was that it wasn't taking value -1, which is not an acceptable value as its min value is 8 now and it was wrongly documented in the desc of config. I think we should atleast merge this and proceed with the DS stuff, and follow the test failure as a new tracker. What do u say?

2026-06-04 07:56 UTC, vshankar commented
> @vshankar It came from downstream, where the issue was that it wasn't taking value -1, which is not an acceptable value as its min value is 8 now and it was wrongly documented in the desc of config. I think we should atleast merge this and proceed with the jira, and follow the test failure as a new tracker. What do u say?

Yes, that's what I suggested. I have a tracker assigned to you. This change will be merged soon.

2026-06-08 07:25 UTC, vshankar approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/QA_main_--_2026#wip-vshankar-testing-20260513092143

2026-06-08 08:55 UTC, vshankar commented
/config check ok

2026-06-08 09:03 UTC, merged