reef: mds: defer trim() until after the last cache_rejoin ack being received
ceph/ceph pull request #56747
Opened 2024-04-08 02:24 UTC by lxbsz

backport tracker: https://tracker.ceph.com/issues/65321

---

backport of https://github.com/ceph/ceph/pull/52648
parent tracker: https://tracker.ceph.com/issues/62036

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-06-16 07:29 UTC, leonid-s-usov commented
jenkins test make check

2024-06-16 14:21 UTC, leonid-s-usov commented
```
cephadm/configchecks.py:94:6: E204 whitespace after decorator '@'
cephadm/module.py:2943:10: E204 whitespace after decorator '@'
cephadm/tests/test_cephadm.py:974:6: E204 whitespace after decorator '@'
3     E204 whitespace after decorator '@'
```

https://jenkins.ceph.com/job/ceph-pull-requests/136909/consoleFull#954015656e840cee4-f4a4-4183-81dd-42855615f2c1

the error doesn't seem to be caused by this PR, but it also doesn't seem like something that can be resolved by re-running the build. Probably, you'll have to rebase this @lxbsz

2024-06-17 00:10 UTC, lxbsz commented
> ```
> cephadm/configchecks.py:94:6: E204 whitespace after decorator '@'
> cephadm/module.py:2943:10: E204 whitespace after decorator '@'
> cephadm/tests/test_cephadm.py:974:6: E204 whitespace after decorator '@'
> 3     E204 whitespace after decorator '@'
> ```
> 
> https://jenkins.ceph.com/job/ceph-pull-requests/136909/consoleFull#954015656e840cee4-f4a4-4183-81dd-42855615f2c1
> 
> the error doesn't seem to be caused by this PR, but it also doesn't seem like something that can be resolved by re-running the build. Probably, you'll have to rebase this @lxbsz

Done. Let's see will it happen again.

2024-06-17 08:20 UTC, leonid-s-usov commented
You need to rebase above https://github.com/ceph/ceph/pull/58062

2024-06-17 14:41 UTC, joscollin requested changes
@lxbsz Please rebase.

2024-06-18 04:58 UTC, joscollin commented
Tested in https://tracker.ceph.com/issues/66511

2024-06-18 08:16 UTC, merged