mds: remove the imcorrect std::move for fsname and path
ceph/ceph pull request #56981
Opened 2024-04-18 10:14 UTC by lxbsz

Fixes: https://tracker.ceph.com/issues/65563
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-04-18 12:57 UTC, leonid-s-usov approved these changes
TBH, I don't understand why `move` is even allowed with a `const &` argument, but my tests show that a copy constructor is called despite the move.

If we would like to allow for a move semantics and avoid creating two versions of the constructor (or 4) for the permutation of `const &` and `&&` arguments, here's a c++20 way to declare it:

```
  template<std::convertible_to<std::string> N, std::convertible_to<std::string> P>
  MDSCapMatch(N&& fsname_, P&& path_,
	      bool root_squash_, int64_t uid_=MDS_AUTH_UID_ANY,
	      const std::vector<gid_t>& gids_={})
{
    fs_name = std::forward<N>(fsname_);
    path = std::forward<P>(path_);
...
```

declared this way it can be called as 

```
MDSCapMatch(name, path, ...);

MDSCapMatch(std::move(name), path, ...);

MDSCapMatch("literal name", path, ...);
```

etc

2024-04-18 13:03 UTC, batrick commented
> TBH, I don't understand why `move` is even allowed with a `const &` argument, but my tests show that a copy constructor is called despite the move.

My understanding is that it will create a `std::string const&&` in this instance. (You could have a constructor/operator that accepts such a type.)

2024-04-18 13:05 UTC, batrick approved these changes

2024-04-18 13:09 UTC, batrick commented
I'm also not sure how this PR fixes https://tracker.ceph.com/issues/65563 which seems to be a kclient issue?

2024-04-18 13:58 UTC, lxbsz commented on src/mds/MDSAuthCaps.h
> +    fs_name = fsname_;
yeah, I think I found the root cause. It's the bug of the `git_t`, actually it's 32 bits while the kclient is trying to decode it as `int64_t`.

2024-04-18 13:59 UTC, lxbsz commented
> I'm also not sure how this PR fixes https://tracker.ceph.com/issues/65563 which seems to be a kclient issue?

Actaully this is not a correct fix, please see https://github.com/ceph/ceph/pull/56981#discussion_r1570820276.

2024-04-19 18:39 UTC, batrick approved these changes

2024-04-19 18:40 UTC, batrick requested changes
please remove the `Fixes` line in `mds: remove the imcorrect std::move for fsname and path`

2024-04-22 01:25 UTC, lxbsz commented
> please remove the `Fixes` line in `mds: remove the imcorrect std::move for fsname and path`

Done. Thanks!

2024-04-22 06:00 UTC, leonid-s-usov commented
@lxbsz with the next push, would you please fix the typo in the commit summary 07b01abf6691074ea876b3b5c83f2e00203c0dea? `imcorrect` -> `incorrect`

2024-04-22 06:30 UTC, lxbsz commented
> @lxbsz with the next push, would you please fix the typo in the commit summary [07b01ab](https://github.com/ceph/ceph/commit/07b01abf6691074ea876b3b5c83f2e00203c0dea)? `imcorrect` -> `incorrect`

Done. Thanks @leonid-s-usov

2024-04-25 01:39 UTC, batrick commented
@lxbsz I think you added the ostream changes back in by accident.

2024-04-25 01:48 UTC, lxbsz commented
> @lxbsz I think you added the ostream changes back in by accident.

Removed it.

2024-04-25 03:08 UTC, Svelar commented
jenkins test make check arm64

2024-04-25 18:07 UTC, leonid-s-usov approved these changes

2024-04-26 10:43 UTC, rishabh-d-dave commented
make check failure is unrelated

2024-04-26 10:45 UTC, rishabh-d-dave commented
jenkins test make check

2024-04-29 06:07 UTC, vshankar approved these changes

2024-04-29 06:08 UTC, vshankar commented
jenkins test make check

2024-04-29 08:53 UTC, dparmar18 approved these changes

2024-04-29 20:48 UTC, batrick approved these changes

2024-05-01 15:23 UTC, batrick commented
jenkins test windows

2024-05-02 05:34 UTC, rishabh-d-dave commented
@batrick This is under QA already.

2024-05-03 01:07 UTC, batrick commented
This PR is under test in [https://tracker.ceph.com/issues/65771](https://tracker.ceph.com/issues/65771).

2024-05-03 01:11 UTC, batrick commented
> @batrick This PR is under QA already.

Feel free to merge it if your QA completes successfully.

2024-05-03 07:23 UTC, rishabh-d-dave approved these changes
QA run was successful - https://tracker.ceph.com/issues/65764.

Testing took more time than expected because there were 25-30 new failures, most of them caused by a PR in the testing branch.

2024-05-03 07:28 UTC, merged