crimson/osd/osd_operation.cc: optimize the calculation and output of slow_ops
ceph/ceph pull request #56994
Opened 2024-04-19 02:58 UTC by guojidan

Fixes: https://tracker.ceph.com/issues/65531

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-05-16 02:48 UTC, guojidan commented
jenkins test make check

2024-05-16 02:48 UTC, guojidan commented
jenkins test windows

2024-05-16 02:48 UTC, guojidan commented
jenkins test make check arm64

2024-05-20 23:08 UTC, athanatos commented
The commit message "crimson/osd/osd_operation.cc: optimize the calculation and output of slow_ops" suggests that this is a performance optimization.  In fact, from the linked bug, this actually fixes a few bugs in how the command works.  Please update the commit message to explain what this commit changes and how it fixes the bugs.

2024-05-20 23:09 UTC, athanatos commented
As a guideline, "optimize ..." is basically never an acceptable commit message as it really doesn't tell a future reader what the commit is changing.

2024-05-21 16:45 UTC, athanatos commented on src/crimson/osd/osd_operation.cc
> +  historic_registry.splice(last_of_recents,
Don't we always want to insert at the end of historic_registry?

2024-05-21 16:48 UTC, athanatos commented on src/crimson/osd/osd_operation.cc
> +    --last_of_recents;
I'm confused as to what last_of_recents is supposed to indicate.  Is it the case that for all ops in the interval [last_of_recents, std::end(historic_registry)), get_duration(op) <= local_conf()->osd_op_complaint_time?  If so, I'm not sure this patch actually maintains that invariant.

2024-05-21 16:49 UTC, athanatos commented on src/crimson/osd/osd_operation.cc
> +    --num_recent_ops;
The last op may not be recent.

2024-05-21 16:50 UTC, athanatos requested changes
See my other comments -- I might just be misunderstanding the patch, though.

2024-05-24 07:09 UTC, guojidan commented
hi @athanatos , all historic_client_request ops are in one `op_list`, so I want to separate them, The first `local_conf()->osd_op_history_slow_op_size` elements in the `op_list` store the slow ops log,  while the last `local_conf()->osd_op_history_size` elements  store the normal history ops log, use `last_of_recents` as separated markers.

insert slow ops before `last_of_recents`, normal ops insert at the end of `op_list`

2024-05-28 23:37 UTC, athanatos commented
Perhaps it would be simpler to use two separate lists rather than maintain last_of_recents as a separator?

2024-05-29 00:45 UTC, guojidan commented
> Perhaps it would be simpler to use two separate lists rather than maintain last_of_recents as a separator?

ok, I will reimplement this

2024-06-04 18:57 UTC, athanatos approved these changes
Ah, that's quite clean.  LGTM!

2024-06-09 08:03 UTC, Matan-B commented
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-testing-june-9/

2024-06-09 11:58 UTC, Matan-B commented
jenkins test make check

2024-06-09 12:00 UTC, Matan-B commented
Merging based on (21/21 passed):

https://pulpito.ceph.com/matan-2024-06-09_09:28:06-crimson-rados-wip-matanb-crimson-testing-june-9-distro-crimson-smithi/
rerun dead jobs:
https://pulpito.ceph.com/matan-2024-06-09_10:57:06-crimson-rados-wip-matanb-crimson-testing-june-9-distro-crimson-smithi/

2024-06-10 07:39 UTC, Matan-B commented
jenkins test make check

2024-06-10 11:37 UTC, Matan-B commented
jenkins test make check

2024-06-16 08:32 UTC, merged

2024-06-24 07:09 UTC, xxhdx1985126 commented
Seems that this PR is caused memory leak within the OSD

2024-06-24 07:20 UTC, guojidan commented
> Seems that this PR is causing memory leak within the OSD

can you provide more infomation?

2024-06-24 07:33 UTC, xxhdx1985126 commented
> > Seems that this PR is causing memory leak within the OSD
> 
> can you provide more infomation?

With the commit in this PR, no client request gets destroyed. If you set debug_osd to 25, all client request logs except "client_request.*destroying" are printed.

2024-06-24 08:04 UTC, Matan-B commented
Leak seems intentional though cleanup was omitted here.

```
  ClientRequest::ICRef(
    &op, /* add_ref= */true
  ).detach(); // yes, "leak" it for now!
```
 Is there, while the cleanup is removed
```
    // clear a previously "leaked" op
    ClientRequest::ICRef(&fastest_historic_op, /* add_ref= */false);
```

2024-06-24 08:09 UTC, guojidan commented
> Leak seems intentional though cleanup was omitted here.泄漏似乎是故意的，尽管这里省略了清理。
> 
> ```
>   ClientRequest::ICRef(
>     &op, /* add_ref= */true
>   ).detach(); // yes, "leak" it for now!
> ```
> 
> Is there, while the cleanup is removed在那里，而清理被删除
> 
> ```
>     // clear a previously "leaked" op
>     ClientRequest::ICRef(&fastest_historic_op, /* add_ref= */false);
> ```

Oh, I see, I will fix this.

2024-06-24 08:13 UTC, Matan-B commented
Revert PR here: https://github.com/ceph/ceph/pull/58223
@guojidan, if the revert PR will be merged before the fix feel free to re-push the entire branch again (with the fix).
Thank you!