reef: mds: inode_t flags may not be protected by the policylock during set_vxattr
ceph/ceph pull request #57177
Opened 2024-04-30 17:28 UTC by batrick

backport tracker: https://tracker.ceph.com/issues/65715

---

backport of https://github.com/ceph/ceph/pull/56934
parent tracker: https://tracker.ceph.com/issues/65496

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-05-01 15:29 UTC, batrick commented
jenkins test api

2024-05-01 15:29 UTC, batrick commented
jenkins test make check

2024-05-01 15:29 UTC, batrick commented
jenkins test windows

2024-05-21 16:14 UTC, batrick commented
jenkins test make check

2024-06-27 15:58 UTC, batrick commented
jenkins test api

2024-06-27 15:58 UTC, batrick commented
jenkins test make check

2024-06-27 15:58 UTC, batrick commented
jenkins test windows

2024-07-10 11:41 UTC, joscollin commented
jenkins test make check

2024-07-10 11:41 UTC, joscollin commented
jenkins test api

2024-07-10 15:30 UTC, joscollin commented
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:13470:16: error: no member named 'quiescelock' in 'CInode'
      l = &in->quiescelock;
           ~~  ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:13515:60: error: too many arguments to function call, expected at most 4, have 6
  if (!mds->locker->acquire_locks(mdr, lov, nullptr, {in}, false, true)) {
       ~~~~~~~~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Locker.h:54:8: note: 'acquire_locks' declared here
  bool acquire_locks(MDRequestRef& mdr,

2024-07-23 02:11 UTC, lxbsz commented
jenkins retest this please

2024-07-26 02:03 UTC, lxbsz commented
This PR is under test in [https://tracker.ceph.com/issues/67186](https://tracker.ceph.com/issues/67186).

2024-08-13 09:19 UTC, rishabh-d-dave requested changes

2024-08-13 09:19 UTC, rishabh-d-dave commented on qa/tasks/cephfs/test_subvolume.py
> +        op = self.fs.rank_tell("lock", "path", "/dir1/dir2", "snap:r", rank=1)
QA was unsuccessfull. From `xiubli-2024-08-07_00:51:19-fs-wip-xiubli-testing-20240806.124812-reef-distro-default-smithi/7841140/teuthology.log` -

```
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:======================================================================
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:ERROR: test_subvolume_replicated (tasks.cephfs.test_subvolume.TestSubvolumeReplicated)
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:That a replica sees the subvolume flag on a directory.
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_5536d05be0501ca23bda2e7c129ea5d1781edf43/qa/tasks/cephfs/test_subvolume.py", line 220, in test_subvolume_replicated
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:TypeError: Filesystem.rank_tell() got multiple values for argument 'rank'
2024-08-08T12:09:18.208 INFO:tasks.cephfs_test_runner:
```

Same stacktrace different job -

```
2024-08-08T13:22:44.295 INFO:tasks.cephfs_test_runner:======================================================================
2024-08-08T13:22:44.295 INFO:tasks.cephfs_test_runner:ERROR: test_subvolume_replicated (tasks.cephfs.test_subvolume.TestSubvolumeReplicated)
2024-08-08T13:22:44.295 INFO:tasks.cephfs_test_runner:That a replica sees the subvolume flag on a directory.
2024-08-08T13:22:44.295 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2024-08-08T13:22:44.295 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2024-08-08T13:22:44.295 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_5536d05be0501ca23bda2e7c129ea5d1781edf43/qa/tasks/cephfs/test_subvolume.py", line 220, in test_subvolume_replicated
2024-08-08T13:22:44.296 INFO:tasks.cephfs_test_runner:TypeError: Filesystem.rank_tell() got multiple values for argument 'rank'
2024-08-08T13:22:44.296 INFO:tasks.cephfs_test_runner:
2024-08-08T13:22:44.296 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2024-08-08T13:22:44.296 INFO:tasks.cephfs_test_runner:Ran 129 tests in 5680.938s
```

2024-12-30 19:45 UTC, batrick commented on qa/tasks/cephfs/test_subvolume.py
> +        op = self.fs.rank_tell("lock", "path", "/dir1/dir2", "snap:r", rank=1)
addressed, thanks

2025-01-10 12:26 UTC, vshankar commented
This PR is under test in [https://tracker.ceph.com/issues/69489](https://tracker.ceph.com/issues/69489).

2025-01-28 10:28 UTC, mchangir commented
jenkins test make check

2025-01-29 06:51 UTC, mchangir commented
jenkins test make check

2025-01-29 10:21 UTC, mchangir approved these changes
LGTM

https://tracker.ceph.com/projects/cephfs/wiki/Reef#wip-vshankar-testing-20250113141608-reef-debug

2025-01-29 10:50 UTC, merged