mgr/balancer: set upmap_max_deviation to 1
ceph/ceph pull request #57216
Opened 2024-05-01 21:36 UTC by JoshuaGabriel

Field experience shows that previous value 5 leads to skewed OSD utilization. Set it to 1 and update the relevant test.

Fixes: https://tracker.ceph.com/issues/65748

2024-05-01 21:41 UTC, dvanders commented
Hi @ljflores here's a simple balancer qol improvement.

2024-05-01 21:42 UTC, ljflores approved these changes
LGTM. I have made this adjustment often in testing.

2024-05-03 18:15 UTC, yuriw commented
This PR is under test in [https://tracker.ceph.com/issues/65796](https://tracker.ceph.com/issues/65796).

2024-05-03 22:31 UTC, ljflores requested changes
In talking to @neha-ojha, she mentioned that there may be certain CRUSH rules where deviation 1 doesn't result in good mappings. Putting "Request Changes" and DNM for now so we can look into it.

2024-07-18 17:43 UTC, kamoltat commented
FYI This passed RADOS ://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues65796

However, we are not merging due to the comments above.

2024-07-18 18:23 UTC, dvanders commented
> In talking to @neha-ojha, she mentioned that there may be certain CRUSH rules where deviation 1 doesn't result in good mappings. Putting "Request Changes" and DNM for now so we can look into it.

@neha-ojha do you have more info?

2024-07-18 19:44 UTC, yuriw commented
ref: https://tracker.ceph.com/issues/65796

2024-07-18 21:16 UTC, ljflores commented
> @neha-ojha

@dvanders This PR will need further testing to prove that this setting works well with current CRUSH configurations in the wild. Neha and I discussed that the experiments previously conducted to set the default to 5 (see https://github.com/ceph/ceph/pull/32247#issuecomment-566834970 for the history) should be repeated with current osdmaps from the wild.

I had collected some of these osdmaps for read balancer testing (ref: https://tracker.ceph.com/issues/53622). I plan to use these osdmaps to repeat the experiments done in the past to prove whether this setting is better.

If @JoshuaGabriel also wants to provide proof along those lines, that is fine too. But ultimately this change needs to be further justified against real world CRUSH configurations.

2024-10-16 22:02 UTC, closed without merging