squid: mds: find a new head for the batch ops when the head is dead
ceph/ceph pull request #57494
Opened 2024-05-16 06:41 UTC by lxbsz

backport tracker: https://tracker.ceph.com/issues/66052

---

backport of https://github.com/ceph/ceph/pull/56941
parent tracker: https://tracker.ceph.com/issues/65536

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-05-16 08:17 UTC, leonid-s-usov requested changes
Let's wait with this backport until we complete investigating a different approach to fixing this issue.

2024-05-31 12:13 UTC, joscollin approved these changes

2024-06-05 03:13 UTC, lxbsz commented
> Let's wait with this backport until we complete investigating a different approach to fixing this issue.

@leonid-s-usov @joscollin 

Should I backport the recent merged https://github.com/ceph/ceph/pull/57553 to this PR ? Or raise a new one later after this getting merged ?

2024-06-05 06:31 UTC, leonid-s-usov commented
I would prefer to have it here as one PR, but please reference the tickets correctly: this PR will be serving both backport tickets

2024-06-05 06:53 UTC, lxbsz commented
> I would prefer to have it here as one PR, but please reference the tickets correctly: this PR will be serving both backport tickets

Done, maybe we could just drop the first two commits ?

2024-06-05 07:22 UTC, leonid-s-usov commented
> Done, maybe we could just drop the first two commits ?

Yes! In that case, we should mark the corresponding backport tickets as "Rejected" and explain there in the comment that the other backport supersedes them.

2024-06-05 12:29 UTC, leonid-s-usov approved these changes

2024-07-11 01:44 UTC, lxbsz commented
jenkins retest this please

2024-08-02 05:53 UTC, lxbsz commented
This PR is under test in [https://tracker.ceph.com/issues/67316](https://tracker.ceph.com/issues/67316).

2024-08-19 06:49 UTC, rishabh-d-dave approved these changes
QA run was successful - https://tracker.ceph.com/projects/cephfs/wiki/Squid#19-Aug-2024

2024-08-19 07:59 UTC, merged