script/: add cpu-map.sh to aid manual selection of CPU cores for threads for profiling
ceph/ceph pull request #57562
Opened 2024-05-20 10:28 UTC by perezjosibm

This PR adds a set of utility scripts (inspired/based on previous existing scripts), adapted for learning exercises.
# [script/cpu_map.sh]

tool (based on `scripts/seastar-cpu-map.sh`) to set the CPU core affinity for a group of threads within a process. This is useful when experimenting to set different groups of threads on different CPU cores.

## Usage:

` cpu-map.sh -p <process_PIDs comma separated> -n <process_Name> -g <group-name:affinity-range>`

The user needs to edit the associative arrays in the script to suit for particular requirements.
There are examples at the top of the script, which should make it easier to edit accordingly.

## Example:

This is an example of the execution and the resulting CPU core assignment.
Lets assume you create a cluster with vstart as follows:

`MDS=0 MON=1 OSD=1 MGR=1 ../src/vstart.sh --new -x --localhost --without-dashboard --bluestore --redirect-output --bluestore-devs /dev/sdf --crimson --no-restart`

The alien threads are set (by default) on the range 1-31  CPU cores:

```bash
# taskset -acp $(pgrep crimson-osd)
pid 1672's current affinity list: 0
pid 1681's current affinity list: 0
pid 1682's current affinity list: 0
pid 1683's current affinity list: 1-31
pid 1684's current affinity list: 1-31
pid 1685's current affinity list: 1-31
pid 1686's current affinity list: 1-31
pid 1687's current affinity list: 1-31
pid 1688's current affinity list: 1-31
pid 1689's current affinity list: 0
pid 1690's current affinity list: 1-31
pid 1692's current affinity list: 1-31
pid 1693's current affinity list: 1-31
pid 1694's current affinity list: 1-31
pid 1695's current affinity list: 1-31
pid 1876's current affinity list: 1-31
pid 2057's current affinity list: 1-31
pid 2058's current affinity list: 1-31
pid 2059's current affinity list: 1-31
pid 2060's current affinity list: 1-31
pid 2061's current affinity list: 1-31
```
Suppose you want to segregate the alien threads to CPU cores 1-4 only. You can run the script as follows:

`cpu-map.sh -p $(pgrep crimson-osd) -g alien:"1-4"`

Here is a snippet of the output:

```bash
Skipping 1672
Skipping 1681
Skipping 1682
alien-store-tp: taskset -c -p 1-4 1683
pid 1683's current affinity list: 1-31
pid 1683's new affinity list: 1-4
alien-store-tp: taskset -c -p 1-4 1684
pid 1684's current affinity list: 1-31
pid 1684's new affinity list: 1-4
```

And here is the end result:

```bash
# ps -p $(pgrep crimson-osd) -L -o pid,tid,comm,psr --no-headers >> _threads.out
# taskset -acp $(pgrep crimson-osd) >> _tasks.out
# paste _threads.out _tasks.out
   1672    1672 crimson-osd       0     pid 1672's current affinity list: 0
   1672    1681 syscall-0         0     pid 1681's current affinity list: 0
   1672    1682 log               0     pid 1682's current affinity list: 0
   1672    1683 alien-store-tp    1     pid 1683's current affinity list: 1-4
   1672    1684 alien-store-tp    1     pid 1684's current affinity list: 1-4
   1672    1685 alien-store-tp    2     pid 1685's current affinity list: 1-4
   1672    1686 alien-store-tp    2     pid 1686's current affinity list: 1-4
   1672    1687 alien-store-tp    3     pid 1687's current affinity list: 1-4
   1672    1688 alien-store-tp    3     pid 1688's current affinity list: 1-4
   1672    1689 crimson-osd       0     pid 1689's current affinity list: 0
   1672    1690 bstore_aio        1     pid 1690's current affinity list: 1-4
   1672    1692 rocksdb:low       9     pid 1692's current affinity list: 1-4
   1672    1693 rocksdb:low      26     pid 1693's current affinity list: 1-4
   1672    1694 rocksdb:low       8     pid 1694's current affinity list: 1-4
   1672    1695 rocksdb:high      8     pid 1695's current affinity list: 1-4
   1672    1876 bstore_aio        2     pid 1876's current affinity list: 1-4
   1672    2057 alien-store-tp    1     pid 2057's current affinity list: 1-4
   1672    2058 cfin             26     pid 2058's current affinity list: 1-4
   1672    2059 bstore_kv_sync   19     pid 2059's current affinity list: 1-4
   1672    2060 bstore_kv_final  31     pid 2060's current affinity list: 1-4
   1672    2061 bstore_mempool    2     pid 2061's current affinity list: 1-4
```

### What to edit in the script:

You may only need to add a new group, (as an associative array) which is composed by:

- name of the group
- regular expression identifying the names for the threads to match for,
- a valid range of CPU to be accepted by taskset. This is the default CPU range for this group.
- modify the CPU cores that would be available after the mapping,
- finally, if needed, the regular expression for the threads names that you do not want to modify.

In the script, each of the above items are at the top:

```bash
 12 ########################################################
 13 # Please edit the following to suit your own needs
 14 #
 15 # Regex to define the group of threads names we want to set their affinity:
 16 proc_group_re="alien-store-tp|rocksdb|bstore|cfin"
 17 # Associate array to identify the group and the thread names
 18 declare -A thr_grp_re_name_map=([alien]="$proc_group_re")
 19 # Ditto for their default affinity range:
 20 declare -A thr_grp_range_map=([alien]="4-7")
 21 # You can define further groups as needed
 22
 23 # Range of CPU cores available: i.e. nprocs - rectors
 24 free_cpu_avail="8-31"
 25
 26 # Regex of threads to ignore: do not change their affinity
 27 proc_ignore_re="crimson-osd|reactor|log|syscall"

```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-05-20 22:21 UTC, athanatos requested changes
I think I'm mostly just missing a bit of clarity on how to actually use this script -- slightly more specific examples would probably take care of that.  Generally, I think this is fine to put in scripts/ and will be useful.

2024-05-20 22:21 UTC, athanatos commented on src/script/cpu-map.sh
> +# !      ./cpu-map.sh -p 32 -g
This looks like it's lifted from seastar.git scripts/seastar-cpu-map.sh.  That's fine, but let's update the examples to suggest how to use it specifically with crimson-osd or ceph-osd?

2024-05-20 22:21 UTC, athanatos commented on src/script/cpu-map.sh
> +proc_ignore_re="crimson-osd|reactor|log|syscall"
Is the intention for the user to uncomment one of these sections depending on what they are doing?

2024-08-06 11:29 UTC, perezjosibm commented
Hi @athanatos , I've updated the code and added examples as requested, I'd appreciate your review please. Thanks

2024-08-07 01:54 UTC, athanatos approved these changes
LGTM otherwise

2024-08-07 01:54 UTC, athanatos commented on src/script/cpu-map.sh
> +# !  Important: the "affinity-range" must be a vlid argument for taskset.
valid

2024-08-07 09:02 UTC, merged