mds: fix ceph-mds static build
ceph/ceph pull request #57578
Opened 2024-05-20 20:34 UTC by ascheglov

Fix ceph-mds build with -DENABLE_SHARED=NO

- explicitly add Boost.Thread dependency for json_spirit
- fix multiple definition errors for non-inline functions in mds/QuiesceDbEncoding.h

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-05-28 18:16 UTC, ascheglov commented
While static inline is possible, for the exact purpose of preventing ODR violations, inline is all that is needed here. Surely static would also fix the ODR issue, but by creating a copy of the function in every TU. After all, static is for preventing a name clash of different functions is different TUs.Also please see this SO answer - https://stackoverflow.com/a/2210310921:06, May 28, 2024, Patrick Donnelly ***@***.***>:
@batrick commented on this pull request.



In src/mds/QuiesceDbEncoding.h:
> @@ -15,81 +15,81 @@
 #include "include/encoding.h"
 #include <stdint.h>
 
-void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)
+inline void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)

I'm not certain but I think conventionally it would be:
⬇️ Suggested change
-inline void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)
+static inline void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

2024-05-29 10:01 UTC, ascheglov commented on src/mds/QuiesceDbEncoding.h
> +inline void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)
While static inline is possible, for the exact purpose of preventing ODR violations, inline is all that is needed here. Surely static would also fix the ODR issue, but by creating a copy of the function in every TU. After all, static is for preventing a name clash of different functions is different TUs.

Also please see this SO answer - https://stackoverflow.com/a/22103109

2024-05-29 20:58 UTC, batrick approved these changes

2024-05-29 20:58 UTC, batrick commented on src/mds/QuiesceDbEncoding.h
> +inline void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)
Thanks.

2024-05-29 20:59 UTC, batrick commented on src/mds/QuiesceDbEncoding.h
> +inline void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)
Also, I think you'll want this `squid` as well because this QuiesceDbEncoding.h file was recently backported there. Let's create a tracker ticket?

2024-06-07 14:21 UTC, ascheglov commented on src/mds/QuiesceDbEncoding.h
> +inline void encode(QuiesceDbVersion const& v, bufferlist& bl, uint64_t features = 0)
Thanks, I've opened https://tracker.ceph.com/issues/66397 , not sure if it's properly formatted though.

2024-06-07 14:26 UTC, ascheglov commented
(updated commit messages by adding the Fixes line)

2024-06-07 14:29 UTC, ascheglov commented
jenkins test signed

2024-06-10 08:11 UTC, ascheglov commented
jenkins retest this please

2024-06-13 07:36 UTC, ascheglov commented
jenkins test make check

2024-06-16 04:49 UTC, leonid-s-usov approved these changes

2024-06-16 17:02 UTC, ascheglov commented
jenkins test api

2024-06-16 17:02 UTC, ascheglov commented
jenkins test make check arm64

2024-06-16 17:02 UTC, ascheglov commented
jenkins test make check

2024-06-16 17:03 UTC, ascheglov commented
jenkins test docs

2024-06-16 17:03 UTC, ascheglov commented
jenkins render docs

2024-06-17 19:09 UTC, ascheglov commented
jenkins test make check

2024-06-20 14:09 UTC, batrick requested changes
DNM

2024-09-11 15:44 UTC, batrick requested changes
Anatoly, thanks for your pull request. The code change is fine but we cannot accept it because of your association with a sanctioned entity.

2024-09-11 15:44 UTC, closed without merging