Quiesce should actively cancel an ongoing quiesce if it hasn't frozen the tree yet
ceph/ceph pull request #57579
Opened 2024-05-20 21:20 UTC by leonid-s-usov

Fixes: https://tracker.ceph.com/issues/66123

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-05-21 17:40 UTC, batrick commented
jenkins test make check arm64

2024-05-21 17:42 UTC, batrick requested changes
`mds/quiesce: don't force a remote authpin for the quiesce lock` was not part of the two runs I did for

https://pulpito.ceph.com/?branch=wip-lusov-quiesce-overdrive-export

I would prefer to keep that in another PR/ticket. Let's get the export fix merged quickly.

2024-05-21 21:10 UTC, leonid-s-usov commented
> `mds/quiesce: don't force a remote authpin for the quiesce lock` was not part of the two runs I did for
> 
> https://pulpito.ceph.com/?branch=wip-lusov-quiesce-overdrive-export
> 
> I would prefer to keep that in another PR/ticket. Let's get the export fix merged quickly.

I'm not sure. I think they work together, where the absence of the remote authpin in most of the cases eliminates the possibility for a deadlock. It also reduces the inter-rank messaging. And it's true to the current design of the quiesce. And it's required to fix that test that fails otherwise.

Your run shows [one quiesce timeout due to exporting](https://pulpito.ceph.com/pdonnell-2024-05-21_01:33:07-fs:workload-wip-lusov-quiesce-overdrive-export-distro-default-smithi/7717849/). I have looked at that one and it appears to be the renaming issue or rather a different kind of it.

I'm re-running just the exporter with full replication x8 to stress-test this PR: https://pulpito.ceph.com/leonidus-2024-05-21_18:10:18-fs-wip-lusov-quiesce-overdrive-export-distro-default-smithi/

2024-05-21 21:12 UTC, leonid-s-usov commented
> I'm re-running just the exporter with full replication x8 to stress-test this PR: https://pulpito.ceph.com/leonidus-2024-05-21_18:10:18-fs-wip-lusov-quiesce-overdrive-export-distro-default-smithi/

```
[leonidus@vossi04 leonidus-2024-05-21_18:10:18-fs-wip-lusov-quiesce-overdrive-export-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
[leonidus@vossi04 leonidus-2024-05-21_18:10:18-fs-wip-lusov-quiesce-overdrive-export-distro-default-smithi]$
```

No quiesce errors. I do think that the absence of the authpin plays the role. To validate it I'll rerun the same suite as above but with the previous version of the branch, without the authpin change

2024-05-21 21:15 UTC, leonid-s-usov commented
> To validate it I'll rerun the same suite as above but with the previous version of the branch, without the authpin change

https://pulpito.ceph.com/leonidus-2024-05-21_21:13:35-fs-wip-lusov-quiesce-overdrive-export-distro-default-smithi/

2024-05-22 06:19 UTC, leonid-s-usov commented
This test puts some strain on the system. However, I couldn't find any correlation between the presence of the AP commit and the results:
<img width="974" alt="image" src="https://github.com/ceph/ceph/assets/3144935/b24b9fd7-f6b5-4182-8381-ab228ee34633">

It is still to be validated whether the rename issue would be affected by the AP change

2024-05-22 06:30 UTC, leonid-s-usov commented
scheduling 20 jobs of the workload that has seen the rename issue.

without the AP change: https://pulpito.ceph.com/leonidus-2024-05-22_06:28:15-fs-wip-lusov-quiesce-overdrive-export-distro-default-smithi/

with the AP change: https://pulpito.ceph.com/leonidus-2024-05-22_06:28:39-fs-wip-lusov-quiesce-overdrive-export-distro-default-smithi/

2024-05-22 06:47 UTC, leonid-s-usov commented
Yes, I found that issue with the rename, and it's indeed due to the remote authpin from the quiesce request.

quiesce request on mds.1:
```
 "description": "internal op quiesce_inode:mds.1:50612 fp=#0x1000000383a"
```

took authpin on mds 0:
```
2024-05-21T03:24:08.269+0000 7f6319567700  7 mds.0.server dispatch_peer_request request(mds.1:50612 nref=2 peer_to mds.1 sr=0x56059607a700) peer_request(mds.1:50612.0 authpin)
2024-05-21T03:24:08.269+0000 7f6319567700 10 mds.0.server handle_peer_auth_pin request(mds.1:50612 nref=2 peer_to mds.1 sr=0x56059607a700)
2024-05-21T03:24:08.269+0000 7f6319567700 10 mds.0.server auth_pinning [inode 0x1000000383a [c,head] /volumes/qa/sv_1/d8fbe2d3-1fdc-4c3a-b7dc-a7b20043535f/client.0/tmp/blogbench-1.0/src/blogtest_in/blog-52/comment-9.xml.tmp auth{1=1} v1151 DIRTY
PARENT s=0 n(v0 1=1+0) (iauth excl) (ifile excl) (ixattr excl) cr={24833=0-4194304@b} caps={24833=pAsxLsXsxFsxcrwb/pAsxXsxFxwb@2},l=24833 | request=0 caps=1 dirtyparent=1 replicated=1 dirty=1 0x56059c154000]
2024-05-21T03:24:08.269+0000 7f6319567700 10 mds.0.cache.ino(0x1000000383a) auth_pin by 0x56059e100d80 on [inode 0x1000000383a [c,head] /volumes/qa/sv_1/d8fbe2d3-1fdc-4c3a-b7dc-a7b20043535f/client.0/tmp/blogbench-1.0/src/blogtest_in/blog-52/comm
ent-9.xml.tmp auth{1=1} v1151 ap=1 DIRTYPARENT s=0 n(v0 1=1+0) (iauth excl) (ifile excl) (ixattr excl) cr={24833=0-4194304@b} caps={24833=pAsxLsXsxFsxcrwb/pAsxXsxFxwb@2},l=24833 | request=0 caps=1 dirtyparent=1 replicated=1 dirty=1 authpin=1 0x5
6059c154000] now 1
```

then the rename request tried to authpin-freeze the same inode:

```
2024-05-21T03:24:08.271+0000 7f6319567700  4 mds.0.server handle_peer_request client.24833:456994 from mds.1
2024-05-21T03:24:08.271+0000 7f6319567700  7 mds.0.cache request_start_peer request(client.24833:456994 nref=2 peer_to mds.1) by mds.1
2024-05-21T03:24:08.271+0000 7f6319567700  7 mds.0.server dispatch_peer_request request(client.24833:456994 nref=2 peer_to mds.1 sr=0x56059ff5f500) peer_request(client.24833:456994.0 authpin)
2024-05-21T03:24:08.271+0000 7f6319567700 10 mds.0.server handle_peer_auth_pin request(client.24833:456994 nref=2 peer_to mds.1 sr=0x56059ff5f500)
2024-05-21T03:24:08.271+0000 7f6319567700 20 mds.0.cache.dir(0x20000001f84.100*) lookup (comment-9.xml.tmp, 'head')
2024-05-21T03:24:08.271+0000 7f6319567700 20 mds.0.cache.dir(0x20000001f84.100*)   hit -> (comment-9.xml.tmp,head)
2024-05-21T03:24:08.271+0000 7f6319567700 10 mds.0.server  freezing auth pin on [inode 0x1000000383a [c,head] /volumes/qa/sv_1/d8fbe2d3-1fdc-4c3a-b7dc-a7b20043535f/client.0/tmp/blogbench-1.0/src/blogtest_in/blog-52/comment-9.xml.tmp auth{1=1} v1
151 ap=1 DIRTYPARENT s=0 n(v0 1=1+0) (iauth excl) (ifile excl) (ixattr excl) cr={24833=0-4194304@b} caps={24833=pAsxLsXsxFsxcrwb/pAsxXsxFxwb@2},l=24833 | request=0 caps=1 dirtyparent=1 replicated=1 dirty=1 authpin=1 0x56059c154000]
2024-05-21T03:24:08.271+0000 7f6319567700 10 mds.0.cache.ino(0x1000000383a) auth_pin by 0x56059e103180 on [inode 0x1000000383a [c,head] /volumes/qa/sv_1/d8fbe2d3-1fdc-4c3a-b7dc-a7b20043535f/client.0/tmp/blogbench-1.0/src/blogtest_in/blog-52/comm
ent-9.xml.tmp auth{1=1} v1151 ap=2 DIRTYPARENT s=0 n(v0 1=1+0) (iauth excl) (ifile excl) (ixattr excl) cr={24833=0-4194304@b} caps={24833=pAsxLsXsxFsxcrwb/pAsxXsxFxwb@2},l=24833 | request=0 caps=1 dirtyparent=1 replicated=1 dirty=1 authpin=1 0x5
6059c154000] now 2 <--- 
2024-05-21T03:24:08.271+0000 7f6319567700 15 mds.0.cache.dir(0x20000001f84.100*) adjust_nested_auth_pins 1 on [dir 0x20000001f84.100* /volumes/qa/sv_1/d8fbe2d3-1fdc-4c3a-b7dc-a7b20043535f/client.0/tmp/blogbench-1.0/src/blogtest_in/blog-52/ [2,head] auth{1=1,2=1} v=1152 cv=763/763 REP ap=0+9 state=1610874881|complete f(v5 m2024-05-21T03:24:04.636446+0000 26=26+0) n(v7 rc2024-05-21T03:24:04.636446+0000 b566673 26=26+0) hs=26+12,ss=31+0 dirty=69 | ptrwaiter=0 child=1 frozen=0 subtree=0 importing=0 importbound=0 sticky=0 replicated=1 dirty=1 authpin=0 0x560592cacd00] by 0x56059c154000 count now 0/9
2024-05-21T03:24:08.271+0000 7f6319567700 10 mds.0.cache.ino(0x1000000383a) freeze_inode - waiting for auth_pins to drop to 1
2024-05-21T03:24:08.271+0000 7f6319567700 10 mds.0.cache.ino(0x1000000383a) add_waiter tag 2 0x56059bda5d40 !ambig 1 !frozen 1 !freezing 0
```

this inode is now freezing and is blocking the quiesce but it can't freeze until the quiesce is over and that first authpin is lifted. However, since that authpin is held by the same logical quiesce, it's a deadlock

2024-05-22 12:15 UTC, leonid-s-usov commented
@batrick can we please have a single PR for those two tickets? They will have to be backported everywhere in a batch... 🙏🏻 🙏🏻

2024-05-22 15:14 UTC, leonid-s-usov commented
jenkins test make check arm64

2024-05-22 16:43 UTC, batrick requested changes
Don't forget to QA `-s fs:functional --filter quiesce`.

`mds/qiuesce: allow quiescing a single file in dispatch_quiesce_path`

will break `test_quiesce_path_regfile`

`mds: quiesce_path: don't block the asock thread and return an adequate rc` -> `mds: do not block the asok thread via quiesce_path and return an adequate rc`

otherwise the change is :+1: 

`mds: add `lifetime` cmd param to `lock path`` :+1:

`qa/cephfs: quiesce: test that a quiesce op doesn't hold remote ap` :+1:

Other fixes are good. You've convinced me to combine the changes.

2024-05-23 01:00 UTC, batrick approved these changes

2024-05-23 11:02 UTC, leonid-s-usov commented
```
[leonidus@vossi04 leonidus-2024-05-23_05:20:02-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
7722024/teuthology.log:2024-05-23T07:12:18.630 ERROR:tasks.quiescer.fs.[cephfs]:Couldn't parse response with error Expecting value: line 1 column 1 (char 0); rc: 124 (EMEDIUMTYPE); stdout:
7722025/teuthology.log:2024-05-23T07:23:01.701 ERROR:tasks.quiescer.fs.[cephfs]:Couldn't parse response with error Expecting value: line 1 column 1 (char 0); rc: 124 (EMEDIUMTYPE); stdout:
```

The two errors are MDS crashes but they aren't related to these changes. They are segfaults when trying to schedule the dir overdrive cancelation in the waiter callbacks. It's a problem that I thought I addressed in https://github.com/ceph/ceph/pull/57332#issuecomment-2119004750, but apparently, those checks weren't enough.

```
 *** Caught signal (Segmentation fault) **
  in thread 7fad51eb9700 thread_name:ms_dispatch
  ceph version 19.0.0-3864-g240841e7 (240841e7af1b0d9e69df9a9cff2fda1c4eab645b) squid (dev)
  1: /lib64/libpthread.so.0(+0x12d20) [0x7fad5b26bd20]
  2: (MDCache::dispatch_fragment_dir(boost::intrusive_ptr<MDRequestImpl> const&, bool)+0xf53) [0x562e4fc278b3]
  3: (MDCache::dispatch_quiesce_inode(boost::intrusive_ptr<MDRequestImpl> const&)+0xe7b) [0x562e4fc4366b]
  4: (MDSContext::complete(int)+0x5f) [0x562e4fe1bb5f]
  5: (void finish_contexts<std::vector<MDSContext*, std::allocator<MDSContext*> > >(ceph::common::CephContext*, std::vector<MDSContext*, std::allocator<MDSContext*> >&, int)+0x8d) [0x562e4fa6c50d]
  6: (MDSCacheObject::finish_waiting(std::bitset<128ul>, int)+0x58) [0x562e4fe2e668]
  7: (Locker::eval_gather(SimpleLock*, bool, bool*, std::vector<MDSContext*, std::allocator<MDSContext*> >*)+0x13ff) [0x562e4fccf7cf]
  8: (Locker::_drop_locks(MutationImpl*, std::set<CInode*, std::less<CInode*>, std::allocator<CInode*> >*, bool)+0x174) [0x562e4fcd9044]
  9: (Locker::drop_locks(MutationImpl*, std::set<CInode*, std::less<CInode*>, std::allocator<CInode*> >*)+0x7f) [0x562e4fcd96df]
  10: (MDCache::fragment_drop_locks(MDCache::fragment_info_t&)+0x22) [0x562e4fc07f42]
  11: (MDSContext::complete(int)+0x5f) [0x562e4fe1bb5f]
```

I think I'll have to open a new ticket for this so that we can backport it separately, WDYT @batrick ?

2024-05-23 11:06 UTC, leonid-s-usov commented
https://pulpito.ceph.com/leonidus-2024-05-23_05:20:02-fs-wip-lusov-quiesce-distro-default-smithi/
This was a stress test with 20 jobs of `balancer/automatic export-check n/3 replication/always`, no quiesce issues 

```
leonidus@vossi04 leonidus-2024-05-23_05:18:05-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
[leonidus@vossi04 leonidus-2024-05-23_05:18:05-fs-wip-lusov-quiesce-distro-default-smithi]$
```

2024-05-23 13:51 UTC, leonid-s-usov commented
@batrick eventually, I'm pushing the crash fix to this PR. The problem is that to verify it, I will need to run the job that involves exporting, which isn't stable without the other fixes.

2024-05-23 14:42 UTC, batrick requested changes

2024-05-23 14:42 UTC, batrick commented on src/mds/MDCache.cc
> +      // so we should attempt the abort asyncrhonosuly
spelling

2024-05-23 21:18 UTC, leonid-s-usov commented on src/mds/MDCache.cc
> +      // so we should attempt the abort asyncrhonosuly
🤦🏻 that word

2024-05-25 06:54 UTC, leonid-s-usov commented
Latest:
[Functional](https://pulpito.ceph.com/leonidus-2024-05-24_04:46:49-fs:functional-wip-lusov-quiesce-distro-default-smithi/) - pass

[Stress exporting/renaming/fragmenting](https://pulpito.ceph.com/leonidus-2024-05-24_04:47:38-fs-wip-lusov-quiesce-distro-default-smithi/) - pass (*half failed because of the backtrace scrub, but no quiesce failures)

```
[leonidus@vossi04 leonidus-2024-05-24_04:47:38-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
[leonidus@vossi04 leonidus-2024-05-24_04:47:38-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "Successfully quiesced" -c */teuthology.log
7724261/teuthology.log:25
7724262/teuthology.log:25
7724263/teuthology.log:25
7724264/teuthology.log:25
7724265/teuthology.log:25
7724266/teuthology.log:25
7724268/teuthology.log:25
7724269/teuthology.log:78
7724270/teuthology.log:78
7724271/teuthology.log:74
7724272/teuthology.log:75
7724273/teuthology.log:75
7724274/teuthology.log:78
7724275/teuthology.log:78
7724276/teuthology.log:78
```

[General with-quiesce](https://pulpito.ceph.com/leonidus-2024-05-24_04:50:13-fs-wip-lusov-quiesce-distro-default-smithi/): 2 timeouts

```
[leonidus@vossi04 leonidus-2024-05-24_04:50:13-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
7724309/teuthology.log:2024-05-24T06:39:43.050 ERROR:tasks.quiescer.fs.[cephfs]:Couldn't quiesce root with rc: 110 (ETIMEDOUT), stdout:
7724309/teuthology.log:2024-05-24T06:39:43.051 ERROR:tasks.quiescer.fs.[cephfs]:exception:
7724310/teuthology.log:2024-05-24T06:38:56.474 ERROR:tasks.quiescer.fs.[cephfs]:Couldn't quiesce root with rc: 110 (ETIMEDOUT), stdout:
7724310/teuthology.log:2024-05-24T06:38:56.474 ERROR:tasks.quiescer.fs.[cephfs]:exception:
```

7724309 and 772410 is a problem with the QuiesceAgent ack reordering, reported this in a new defect: https://tracker.ceph.com/issues/66219

2024-05-27 09:09 UTC, leonid-s-usov commented
A rerun with the fix of https://tracker.ceph.com/issues/66219 found by the tests in https://github.com/ceph/ceph/pull/57579#issuecomment-2130962918:

[Functional](https://pulpito.ceph.com/leonidus-2024-05-26_14:12:39-fs:functional-wip-lusov-quiesce-distro-default-smithi) - pass

[Export/replication kernel_untar_build stress](https://pulpito.ceph.com/leonidus-2024-05-26_10:47:39-fs-wip-lusov-quiesce-distro-default-smithi/) 8/20 pass, no quiesce errors

```
[leonidus@vossi04 leonidus-2024-05-26_10:47:39-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
[leonidus@vossi04 leonidus-2024-05-26_10:47:39-fs-wip-lusov-quiesce-distro-default-smithi]$
```

[A generic `with-quiesce` suite](https://pulpito.ceph.com/leonidus-2024-05-26_10:46:27-fs-wip-lusov-quiesce-distro-default-smithi/) - 19/28 pass, no quiesce errors 

```
[leonidus@vossi04 leonidus-2024-05-26_10:46:27-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
[leonidus@vossi04 leonidus-2024-05-26_10:46:27-fs-wip-lusov-quiesce-distro-default-smithi]$
```

[A second generic `with-quiesce` suite](https://pulpito.ceph.com/leonidus-2024-05-26_10:48:16-fs-wip-lusov-quiesce-distro-default-smithi/) - 23/30 passed, 1 quiesce timeout:

```
[leonidus@vossi04 leonidus-2024-05-26_10:48:16-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
7726344/teuthology.log:2024-05-26T12:51:16.035 ERROR:tasks.quiescer.fs.[cephfs]:Couldn't quiesce root with rc: 110 (ETIMEDOUT), stdout:
```

The analysis suggests that this is a client issue, see https://tracker.ceph.com/issues/66229.

In total, there were 980 successful quiesces over the three runs of this batch. The quiesce times are measured by the script, and as such are not reliable, but still, here's the distribution:

<img width="732" alt="image" src="https://github.com/ceph/ceph/assets/3144935/3abc3599-853b-42f5-80ee-40b767d50514">

2024-05-27 11:29 UTC, leonid-s-usov commented
A re-run with the change for [[quiesce] disable debug parameters on quiesce roots](https://tracker.ceph.com/issues/66225)

[Functional](https://pulpito.ceph.com/leonidus-2024-05-27_07:24:32-fs:functional-wip-lusov-quiesce-distro-default-smithi/) - pass

[A generic `with-quiesce` suite](https://pulpito.ceph.com/leonidus-2024-05-27_07:25:29-fs-wip-lusov-quiesce-distro-default-smithi/) - 28/36 passed, 2 quiesce errors:

```
[leonidus@vossi04 leonidus-2024-05-27_07:25:29-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
7727755/teuthology.log:2024-05-27T08:58:00.992 ERROR:tasks.quiescer.fs.[cephfs]:Couldn't quiesce root with rc: 110 (ETIMEDOUT), stdout:

7727756/teuthology.log:2024-05-27T08:36:38.524 DEBUG:tasks.quiescer.fs.[cephfs]:Running ceph command: 'tell mds.4299 quiesce db --set-id 494d7fba --release --await'
7727756/teuthology.log:2024-05-27T08:38:38.557 ERROR:tasks.quiescer.fs.[cephfs]:exception: (124)
```

Both issues are due to messaging errors preventing the delivery of an ack:

7727755 - during the quiesce
```
2024-05-27T08:56:30.985+0000 7f8886fbe640 20 quiesce.agt <agent_thread_main> asyncrhonous ack for a new version: q-map[v:(14:201) roots:1/0]
2024-05-27T08:56:30.985+0000 7f8886fbe640 10 quiesce.mds.1 <operator()> sending ack q-map[v:(14:201) roots:1/0] to the leader 4288
2024-05-27T08:56:30.985+0000 7f8886fbe640  1 -- [v2:172.21.15.81:6834/957495742,v1:172.21.15.81:6837/957495742] send_to--> mds [v2:172.21.15.81:6835/1830870643,v1:172.21.15.81:6838/1830870643] --  -- ?+0 0x56329891fe00
2024-05-27T08:56:30.985+0000 7f8886fbe640  1 -- [v2:172.21.15.81:6834/957495742,v1:172.21.15.81:6837/957495742] --> [v2:172.21.15.81:6835/1830870643,v1:172.21.15.81:6838/1830870643] --  -- 0x56329891fe00 con 0x563297f4d400
2024-05-27T08:56:30.985+0000 7f88927d5640  1 -- [v2:172.21.15.81:6834/957495742,v1:172.21.15.81:6837/957495742] >> [v2:172.21.15.81:6835/1830870643,v1:172.21.15.81:6838/1830870643] conn(0x563297f4d400 msgr2=0x563298204680 crc :-1 s=STATE_CONNECT
ION_ESTABLISHED l=0).read_bulk peer close file descriptor 38
```

7727756 - during the release
```
22151270:2024-05-27T08:36:38.779+0000 7f59bed33640 20 quiesce.mgr.4299 <check_peer_reports> [494d7fba@127,file:/] up_to_date_peers: 2 min_reported_state: QS_QUIESCED max_reported_state: QS_QUIESCED peer_acks: {{QS_QUIESCED=4282,(13:127),QS_QUIES
CED=4296,(13:126),QS_QUIESCED=4299,(13:127)}}
22151274:2024-05-27T08:36:38.779+0000 7f59c7d45640 -1 quiesce.mds.0 <quiesce_dispatch> failed to decode message of type 1286 v1: End of buffer [buffer:2]
```

[Stress test with replication and exporting
](https://pulpito.ceph.com/leonidus-2024-05-27_07:27:31-fs-wip-lusov-quiesce-distro-default-smithi/) - 6/20 passed. Very hight failure rate due to different reasons, but 0 quiesce errors with ~30 successful quiesces per job

```
[leonidus@vossi04 leonidus-2024-05-27_07:27:31-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "ERROR:tasks.quiescer" */teuthology.log
[leonidus@vossi04 leonidus-2024-05-27_07:27:31-fs-wip-lusov-quiesce-distro-default-smithi]$ grep "Successfully quiesced" -c */teuthology.log
7727791/teuthology.log:28
7727792/teuthology.log:26
7727793/teuthology.log:26
7727795/teuthology.log:29
7727797/teuthology.log:25
7727798/teuthology.log:26
7727799/teuthology.log:27
7727800/teuthology.log:29
7727801/teuthology.log:30
7727802/teuthology.log:27
7727803/teuthology.log:30
7727804/teuthology.log:32
7727805/teuthology.log:29
7727806/teuthology.log:30
7727807/teuthology.log:12
7727808/teuthology.log:30
7727809/teuthology.log:25
7727810/teuthology.log:29
```

2024-05-28 16:45 UTC, batrick approved these changes
Fantastic!

2024-05-28 16:46 UTC, merged