squid: osd: full-object read CRC mismatch due to 'truncate' modifying oi.size w/o clearing 'data_digest'
ceph/ceph pull request #57586
Opened 2024-05-21 05:16 UTC by NitzanMordhai

backport tracker: https://tracker.ceph.com/issues/66139

---

backport of https://github.com/ceph/ceph/pull/55008
parent tracker: https://tracker.ceph.com/issues/53240

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-05-22 09:59 UTC, Matan-B requested changes
https://github.com/ceph/ceph/pull/57616

2024-05-31 16:58 UTC, athanatos commented
Do not merge this until https://tracker.ceph.com/issues/66226 is fixed -- the newly added EC test along with 3 others in ceph_test_rados_api_io_pp seem to fail every time.

2025-01-09 16:29 UTC, neha-ojha commented
reopening since the patch has merged into reef

2025-01-15 08:37 UTC, NitzanMordhai commented
@rzarzynski i cherry-picked the commits for https://tracker.ceph.com/issues/66226 just like we did in https://github.com/ceph/ceph/pull/57588#issuecomment-2192421160

2025-01-15 09:39 UTC, Matan-B commented
> #57616

Not addressed yet, see https://github.com/ceph/ceph/pull/57587#discussion_r1916234802

2025-01-15 10:03 UTC, NitzanMordhai commented
@Matan-B please review

2025-01-15 12:12 UTC, Matan-B approved these changes
Approving as this is a clean backport of https://github.com/ceph/ceph/pull/55008 and https://github.com/ceph/ceph/pull/57856. 

Note: 
* Please update https://tracker.ceph.com/issues/66533 with this PR as well
* Personally I would prefer 2 separate backports for 2 separate PRs. However, the 
two are related and R (merged) backport followed the same path - https://github.com/ceph/ceph/pull/57588. Approving to be consistent across backports.

2025-01-15 14:32 UTC, rzarzynski commented
Taking `DNM` out as https://github.com/ceph/ceph/pull/57856 is merged and its backport became part of this PR.

2025-01-15 14:33 UTC, rzarzynski approved these changes

2025-01-23 20:00 UTC, NitzanMordhai commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/SQUID#httpstrackercephcomissues69618

2025-01-23 20:00 UTC, merged