Docs: clarify use of location: in host spec
ceph/ceph pull request #57633
Opened 2024-05-22 15:32 UTC by mcv21

It wasn't clear that you can specify more than one element of the CRUSH hierarchy in a spec file, nor that it might be useful to do so (e.g. to ensure the host ends up beneath the default root).

So update the text to make it clearer, and similarly the example.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-05-22 15:46 UTC, anthonyeleven requested changes

2024-05-22 15:46 UTC, anthonyeleven commented on doc/cephadm/host-management.rst
> +create a new CRUSH host located in the specified hierarchy. You can specify more than
host bucket

2024-05-22 15:56 UTC, anthonyeleven approved these changes

2024-05-22 15:57 UTC, anthonyeleven commented
I'll let @zdover23 gate merging.  Thanks for contributing!

2024-05-22 18:07 UTC, adk3798 approved these changes

2024-05-23 01:26 UTC, merged

2024-05-23 01:28 UTC, zdover23 commented
https://github.com/ceph/ceph/pull/57646 - Squid backport
https://github.com/ceph/ceph/pull/57647 - Reef backport
https://github.com/ceph/ceph/pull/57648 - Quincy backport