squid: mon,cephfs: require confirmation flag to bring down unhealthy MDS
ceph/ceph pull request #57840
Opened 2024-06-03 13:46 UTC by rishabh-d-dave

backport tracker: https://tracker.ceph.com/issues/66330

---

backport of https://github.com/ceph/ceph/pull/56066
parent tracker: https://tracker.ceph.com/issues/61866

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-06-03 13:56 UTC, anthonyeleven approved these changes

2024-06-12 10:49 UTC, rishabh-d-dave commented
```	
Identified problems
	
No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.
```

2024-06-12 10:50 UTC, rishabh-d-dave commented
jenkins test api

2024-06-14 10:57 UTC, joscollin commented
Tested in https://tracker.ceph.com/issues/66423

2024-06-14 11:37 UTC, joscollin requested changes
@rishabh-d-dave There's a failure to be checked: 
https://pulpito.ceph.com/leonidus-2024-06-12_09:41:32-fs-wip-lusov-testing-20240611.123850-squid-distro-default-smithi/7751944/

2024-06-14 12:25 UTC, rishabh-d-dave commented
@joscollin 
> @rishabh-d-dave There's a failure to be checked: https://pulpito.ceph.com/leonidus-2024-06-12_09:41:32-fs-wip-lusov-testing-20240611.123850-squid-distro-default-smithi/7751944/

The failing job is `fs:workload` job and `MDS_CACHE_OVERSIZED` is added here to `fs:functional`, it has nothing to do with `fs:workload` job AFAIS.

2024-06-17 05:07 UTC, joscollin approved these changes

2024-06-17 05:08 UTC, merged