mds: Mark the scrub passed if dirfrag is dirty
ceph/ceph pull request #57953
Opened 2024-06-10 13:05 UTC by kotreshhr

The in-memory and on-disk stats might not match on a directory inode if any of the dirfrag is dirty.
So don't fail the scrub  and mark it as passed if
the dirfrag is dirty.

Fixes: https://tracker.ceph.com/issues/65020

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-06-11 07:30 UTC, kotreshhr commented
Scheduled a QA run with fs:workload multi mds with dynamic balancer or ephemeral random pinning enabled.

https://pulpito.ceph.com/khiremat-2024-06-11_07:27:30-fs:workload-wip-khiremat-57953-scrub-error-0-distro-default-smithi/

2024-06-13 12:14 UTC, kotreshhr commented
I still the error after refreshing the PR with the fix for remote_dirfrag dirtiness. I will investigate further and update the PR
https://pulpito.ceph.com/khiremat-2024-06-13_08:02:02-fs:workload-wip-khiremat-57953-scrub-error-1-distro-default-smithi/

2024-06-13 16:36 UTC, kotreshhr commented
> I still see the error after refreshing the PR with the fix for remote_dirfrag dirtiness. I will investigate further and update the PR https://pulpito.ceph.com/khiremat-2024-06-13_08:02:02-fs:workload-wip-khiremat-57953-scrub-error-1-distro-default-smithi/

@vshankar @leonid-s-usov This particular scrub failure is with the fix. I see that both directory inode and corresponding dirfrag is not dirty and still the rstat is mismatched. The test yml config is as below. So something else is going on. Need to figure out.

<pre>
fs:workload/{0-centos_9.stream begin/{0-install 1-cephadm 2-logrotate 3-modules} clusters/1a11s-mds-1c-client-3node conf/{client mds mgr mon osd} mount/kclient/{base/{mount-syntax/{v1} mount overrides/{distro/stock/{centos_9.stream k-stock} ms-die-on-skipped}} ms_mode/crc wsync/yes} objectstore-ec/bluestore-comp-ec-root omap_limit/10000 overrides/{cephsqlite-timeout frag ignorelist_health ignorelist_wrongly_marked_down osd-asserts pg_health session_timeout} ranks/multi/{balancer/random export-check n/3 replication/default} standby-replay tasks/{0-subvolume/{with-namespace-isolated} 1-check-counter 2-scrub/yes 3-snaps/yes 4-flush/yes 5-quiesce/with-quiesce 6-workunit/fs/misc}}
</pre>

The scrub error is on 
<pre>
"2024-06-13T09:00:29.607433+0000 mds.e (mds.2) 711 : cluster [WRN] Scrub error on inode 0x10000012f02 (/volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17) see mds.e log and `damage ls` output for details" in cluster log
</pre>

Related mds.e.log (inode auth of the directory) . We can find that the inode is not dirty.
<pre>
...
2024-06-13T09:00:29.602+0000 7f4b55282640 10 mds.2.scrubstack handle_scrub mds_scrub(queue_dir_ack 0x10000012f02 fragset_t(*) d0e8b015-afbe-4362-93f9-ce15cda58bb8) from mds.0
2024-06-13T09:00:29.602+0000 7f4b55282640 20 mds.2.scrubstack kick_off_scrubs: state=RUNNING
2024-06-13T09:00:29.602+0000 7f4b55282640 20 mds.2.scrubstack kick_off_scrubs entering with 4 in progress and 7992 in the stack
2024-06-13T09:00:29.602+0000 7f4b55282640 20 mds.2.scrubstack kick_off_scrubs examining [inode 0x10000012f02 [...2a,head] /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ auth{0=1} v952 RANDEPHEMERALPIN f(v1 m2024-06-13T08:55:10.381452+0000 8=8+0) n(v1 rc2024-06-13T08:55:16.501331+0000 b347 9=8+1) (inest mix) mcw={0=AsLsXsFs} | dirtyscattered=0 request=0 lock=0 importingcaps=0 dirfrag=1 caps=0 stickydirs=0 dirtyparent=0 dirwaiter=0 replicated=1 dirty=0 waiter=0 authpin=0 discoverbase=0 scrubqueue=1 randepin 0x5564d8188100]
2024-06-13T09:00:29.602+0000 7f4b55282640 10 mds.2.scrubstack scrub_dir_inode [inode 0x10000012f02 [...2a,head] /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ auth{0=1} v952 RANDEPHEMERALPIN f(v1 m2024-06-13T08:55:10.381452+0000 8=8+0) n(v1 rc2024-06-13T08:55:16.501331+0000 b347 9=8+1) (inest mix) mcw={0=AsLsXsFs} | dirtyscattered=0 request=0 lock=0 importingcaps=0 dirfrag=1 caps=0 stickydirs=0 dirtyparent=0 dirwaiter=0 replicated=1 dirty=0 waiter=0 authpin=0 discoverbase=0 scrubqueue=1 randepin 0x5564d8188100]
2024-06-13T09:00:29.602+0000 7f4b55282640 20 mds.2.scrubstack scrub_dir_inode recursive mode, frags [*]
2024-06-13T09:00:29.602+0000 7f4b55282640 20 mds.2.scrubstack scrub_dir_inode_final [inode 0x10000012f02 [...2a,head] /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ auth{0=1} v952 RANDEPHEMERALPIN f(v1 m2024-06-13T08:55:10.381452+0000 8=8+0) n(v1 rc2024-06-13T08:55:16.501331+0000 b347 9=8+1) (inest mix) mcw={0=AsLsXsFs} | dirtyscattered=0 request=0 lock=0 importingcaps=0 dirfrag=1 caps=0 stickydirs=0 dirtyparent=0 dirwaiter=0 replicated=1 dirty=0 waiter=0 authpin=0 discoverbase=0 scrubqueue=1 randepin 0x5564d8188100]
2024-06-13T09:00:29.602+0000 7f4b55282640 10 mds.2.cache.ino(0x10000012f02) scrub starting validate_disk_state on [inode 0x10000012f02 [...2a,head] /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ auth{0=1} v952 RANDEPHEMERALPIN f(v1 m2024-06-13T08:55:10.381452+0000 8=8+0) n(v1 rc2024-06-13T08:55:16.501331+0000 b347 9=8+1) (inest mix) mcw={0=AsLsXsFs} | dirtyscattered=0 request=0 lock=0 importingcaps=0 dirfrag=1 caps=0 stickydirs=0 dirtyparent=0 dirwaiter=0 replicated=1 dirty=0 waiter=0 authpin=0 discoverbase=0 scrubqueue=1 randepin 0x5564d8188100]
....
....
2024-06-13T09:00:29.602+0000 7f4b55282640 10 mds.2.scrubstack scrub_dir_inode done
2024-06-13T09:00:29.602+0000 7f4b55282640 20 mds.2.scrubstack kick_off_scrubs dir inode, done
2024-06-13T09:00:29.602+0000 7f4b55282640 20 mds.2.scrubstack dequeue [inode 0x10000012f02 [...2a,head] /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ auth{0=1} v952 ap=1 RANDEPHEMERALPIN f(v1 m2024-06-13T08:55:10.381452+0000 8=8+0) n(v1 rc2024-06-13T08:55:16.501331+0000 b347 9=8+1) (inest mix) mcw={0=AsLsXsFs} | dirtyscattered=0 request=0 lock=0 importingcaps=0 dirfrag=1 caps=0 stickydirs=0 dirtyparent=0 dirwaiter=0 replicated=1 dirty=0 waiter=0 authpin=1 discoverbase=0 scrubqueue=1 randepin 0x5564d8188100] from ScrubStack
...
...
2024-06-13T09:00:29.604+0000 7f4b4ea75640 20 mds.2.cache.ino(0x10000012f02) ondisk_read_retval: 0
2024-06-13T09:00:29.604+0000 7f4b4ea75640 10 mds.2.cache.ino(0x10000012f02) decoded 399 bytes of backtrace successfully
2024-06-13T09:00:29.604+0000 7f4b4ea75640 10 mds.2.cache.ino(0x10000012f02) scrub: inotable ino = 0x10000012f02
2024-06-13T09:00:29.604+0000 7f4b4ea75640 10 mds.2.cache.ino(0x10000012f02) scrub: inotable free says 0
2024-06-13T09:00:29.604+0000 7f4b4ea75640  7 mds.2.cache request_start_internal request(mds.2:94019 nref=2) op 5383
...
...
2024-06-13T09:00:29.604+0000 7f4b4ea75640 10 mds.2.cache rdlock_dirfrags_stats_work [inode 0x10000012f02 [...2a,head] /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ auth{0=1} v952 ap=2 RANDEPHEMERALPIN f(v1 m2024-06-13T08:55:10.381452+0000 8=8+0) n(v1 rc2024-06-13T08:55:16.501331+0000 b347 9=8+1) (inest mix) mcw={0=AsLsXsFs} | dirtyscattered=0 request=0 lock=0 importingcaps=0 dirfrag=1 caps=0 stickydirs=0 dirtyparent=0 dirwaiter=0 replicated=1 dirty=0 waiter=0 authpin=1 discoverbase=0 scrubqueue=0 randepin 0x5564d8188100]
....
....
2024-06-13T09:00:29.606+0000 7f4b55282640  7 mds.2.locker handle_file_lock a=syncack on (inest mix->sync g=0) from mds.0 [inode 0x10000012f02 [...2a,head] /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ auth{0=1} v952 ap=3 RANDEPHEMERALPIN f(v1 m2024-06-13T08:55:10.381452+0000 8=8+0) n(v1 rc2024-06-13T08:55:16.501331+0000 b347 9=8+1) (inest mix->sync g=0) (ifile sync r=1) mcw={0=AsLsXsFs} | dirtyscattered=0 request=0 lock=1 importingcaps=0 dirfrag=1 caps=0 stickydirs=0 dirtyparent=0 dirwaiter=0 replicated=1 dirty=0 waiter=1 authpin=1 discoverbase=0 scrubqueue=0 randepin 0x5564d8188100]
2024-06-13T09:00:29.606+0000 7f4b55282640 10 mds.2.cache.ino(0x10000012f02) decode_lock_inest * [2,head]
2024-06-13T09:00:29.606+0000 7f4b55282640 10 mds.2.cache.ino(0x10000012f02) decode_lock_inest * rstat n(v1 rc2024-06-13T08:55:10.383452+0000 b347 8=8+0)
2024-06-13T09:00:29.606+0000 7f4b55282640 10 mds.2.cache.ino(0x10000012f02) decode_lock_inest * accounted_rstat n(v1 rc2024-06-13T08:55:10.383452+0000 b347 8=8+0)
2024-06-13T09:00:29.606+0000 7f4b55282640 10 mds.2.cache.ino(0x10000012f02) decode_lock_inest * dirty_old_rstat {}
2024-06-13T09:00:29.606+0000 7f4b55282640 10 mds.2.cache.ino(0x10000012f02) * first 2 -> 2 on [dir 0x10000012f02 /volumes/qa/sv_1/257f5e61-1d1a-4ee3-8dfe-78182c700535/client.0/tmp/payload.2/multiple_rsync_payload.228227/.build-id/17/ [2,head] rep@0.1 dir_auth=0 sta [...]

2024-06-19 15:05 UTC, leonid-s-usov requested changes
This is a valid approach, but there should be a way to avoid adding a new argument to so many methods. Please consider using the `CInode::validated_data` structure to store and access the information about the remote scrub ack.

2024-06-19 16:46 UTC, vshankar commented
> This is a valid approach, but there should be a way to avoid adding a new argument to so many methods. Please consider using the `CInode::validated_data` structure to store and access the information about the remote scrub ack.

@kotreshhr mentioned that this change doesn't fix the issue. Some explanation in https://tracker.ceph.com/issues/65020#note-34

2024-06-19 17:29 UTC, leonid-s-usov commented
> > This is a valid approach, but there should be a way to avoid adding a new argument to so many methods. Please consider using the `CInode::validated_data` structure to store and access the information about the remote scrub ack.
> 
> @kotreshhr mentioned that this change doesn't fix the issue. Some explanation in https://tracker.ceph.com/issues/65020#note-34

I understand this differently - there is another issue that this change isn't supposed to fix. Kotresh states that in that new issue both the inode and the dirfrag are clean, so it's out of the scope of what the original problem was about. The fix will be different, too.

2024-09-30 06:14 UTC, kotreshhr commented
> @kotreshhr I remember this change fixing one part of the issue. Did we RCA the other part (incorrect rfiles)?

There are two separate issues. I think we can take this and work on the other separately.

2024-09-30 07:44 UTC, vshankar commented
> > @kotreshhr I remember this change fixing one part of the issue. Did we RCA the other part (incorrect rfiles)?
> 
> There are two separate issues. I think we can take this and work on the other separately.

ACK.

2024-10-28 04:49 UTC, vshankar commented
@kotreshhr I think this PR needs to be updated as per comment https://tracker.ceph.com/issues/65020#note-36, yes?

2024-11-12 13:44 UTC, vshankar commented
@rishabh-d-dave PTAL once @kotreshhr pushes an update.

2024-11-12 14:32 UTC, rishabh-d-dave commented
> @rishabh-d-dave PTAL once @kotreshhr pushes an update.

Sure.

2025-01-13 06:26 UTC, vshankar commented
> @kotreshhr I think this PR needs to be updated as per comment https://tracker.ceph.com/issues/65020#note-36, yes?

@kotreshhr Would it be possible to push an update this week?

2025-05-13 14:27 UTC, vshankar commented
@kotreshhr please rebase.

2025-05-16 05:02 UTC, kotreshhr commented
jenkins test make check arm64

2025-05-16 08:35 UTC, kotreshhr commented
> @kotreshhr please rebase.

@vshankar rebased and simplified the commit abf28000054568b5f85887309ccaa543bd906cb6 

Sample run with fs:workoads with scrub/yes - https://pulpito.ceph.com/khiremat-2025-05-16_05:33:04-fs:workload-wip-khiremat-57953-scrub-error-2-distro-default-smithi/

2025-05-16 08:45 UTC, kotreshhr commented
> > @kotreshhr please rebase.
> 
> @vshankar rebased and simplified the commit [abf2800](https://github.com/ceph/ceph/commit/abf28000054568b5f85887309ccaa543bd906cb6)
> 
> Sample run with fs:workoads with scrub/yes - https://pulpito.ceph.com/khiremat-2025-05-16_05:33:04-fs:workload-wip-khiremat-57953-scrub-error-2-distro-default-smithi/

Grepping the teuthology logs did show the code is exercised.

[khiremat@vossi04 khiremat-2025-05-16_05:33:04-fs:workload-wip-khiremat-57953-scrub-error-2-distro-default-smithi]$ find . | grep mds.*.log.gz | xargs zgrep "raw stats most likely wont match since"
```
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:21:07.694+0000 7f75c3676640 20 mds.0.cache.ino(0x10000003836) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:22:34.333+0000 7f75c3676640 20 mds.0.cache.ino(0x10000003593) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:22:34.368+0000 7f75c3676640 20 mds.0.cache.ino(0x10000001f57) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:22:34.587+0000 7f75c3676640 20 mds.0.cache.ino(0x10000000fd7) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:22:34.670+0000 7f75c3676640 20 mds.0.cache.ino(0x10000004e85) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:22:34.724+0000 7f75c3676640 20 mds.0.cache.ino(0x10000001fd7) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:22:34.835+0000 7f75c3676640 20 mds.0.cache.ino(0x10000003836) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:27:02.230+0000 7f75c3676640 20 mds.0.cache.ino(0x10000000fd7) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:27:02.304+0000 7f75c3676640 20 mds.0.cache.ino(0x10000004e85) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:27:02.387+0000 7f75c3676640 20 mds.0.cache.ino(0x10000001fd7) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286703/remote/smithi063/log/94b78f04-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:27:02.440+0000 7f75c3676640 20 mds.0.cache.ino(0x10000003836) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286697/remote/smithi177/log/8f61231c-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:15:55.053+0000 7f60ad71e640 20 mds.0.cache.ino(0x10000000006) raw stats most likely wont match since inode is dirty; please rerun scrub when system is stable; assuming passed for now;
...
...
./8286698/remote/smithi055/log/960251dc-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:18:27.928+0000 7fb630317640 20 mds.1.cache.ino(0x10000000701) raw stats most likely wont match since it's a directory inode and a local dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286698/remote/smithi055/log/960251dc-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:18:27.936+0000 7fb630317640 20 mds.1.cache.ino(0x1000000065a) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286698/remote/smithi055/log/960251dc-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:18:27.952+0000 7fb630317640 20 mds.1.cache.ino(0x10000000d06) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286698/remote/smithi055/log/960251dc-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:18:27.955+0000 7fb630317640 20 mds.1.cache.ino(0x1000000064a) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286698/remote/smithi055/log/960251dc-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:18:27.957+0000 7fb630317640 20 mds.1.cache.ino(0x10000001986) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286698/remote/smithi055/log/960251dc-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:18:27.970+0000 7fb630317640 20 mds.1.cache.ino(0x10000000de0) raw stats most likely wont match since it's a directory inode and a remote dirfrag is dirty; please rerun scrub when system is stable; assuming passed for now;
./8286698/remote/smithi055/log/960251dc-321a-11f0-86fb-adfe0268badd/ceph-mds.b.log.gz:2025-05-16T06:19:15.116+0000 7fb630317640 20 mds.1.cache.ino(0x100000002d9) raw stats most likely wont match since inode is dirty; please rerun scrub when system is stable; assuming passed for now;


```

2025-06-03 07:25 UTC, vshankar commented
@rishabh-d-dave PTAL.

2025-06-25 08:51 UTC, kotreshhr commented
Rebased and addressed an issue - the scrubber was not using the dirfrag dirty flag sent by scrub msg in the ack.

2025-07-09 05:36 UTC, vshankar commented on src/mds/CInode.h
> +    if (dirty_remote_dirfrag_scrubbed)
nit: just return `dirty_remote_dirfrag_scrubbed` bool.

2025-07-09 05:42 UTC, vshankar commented on src/mds/CInode.cc
> +	} else if (in->has_dirty_remote_dirfrag_scrubbed()) {
fold this into the above `else if` (reduces to a single commit then).

2025-07-09 09:50 UTC, kotreshhr commented on src/mds/CInode.cc
> +	} else if (in->has_dirty_remote_dirfrag_scrubbed()) {
I thought of it initially but chose to keep it separate to identify whether local or remote dirfrag is dirty. Let me know if you think if it needs to be merged to single condition and single commit.

2025-07-09 09:55 UTC, vshankar commented on src/mds/CInode.cc
> +	} else if (in->has_dirty_remote_dirfrag_scrubbed()) {
I mean you put it under

```
has_local_dirty_dirfrag || in->has_dirty_remote_dirfrag_scrubbed() {
...
}
```

and use the flag to distinguish if its local or remote dirfrag that's dirty.

2025-07-09 13:56 UTC, kotreshhr commented on src/mds/CInode.cc
> +	} else if (in->has_dirty_remote_dirfrag_scrubbed()) {
@vshankar Done. ptal

2025-07-10 08:23 UTC, kotreshhr commented
jenkins make test arm64

2025-07-10 13:07 UTC, vshankar commented
This PR is under test in [https://tracker.ceph.com/issues/72073](https://tracker.ceph.com/issues/72073).

2025-07-14 08:13 UTC, kotreshhr commented
jenkins make test arm64

2025-07-14 08:14 UTC, kotreshhr commented
jenkins test make check arm64

2025-07-14 13:08 UTC, rishabh-d-dave commented on src/mds/ScrubStack.cc
> +				       inodeno_t(), false, false, false, false, has_dirty_dirfrag);
nit: Perhaps we can pass `has_dirty_dirfrag` and not pass false 4 times.

2025-07-14 13:19 UTC, rishabh-d-dave commented on src/mds/ScrubStack.cc
> +				       inodeno_t(), false, false, false, false, has_dirty_dirfrag);
Ah, we are doing this to avoid modifications to other calls.

2025-07-21 05:20 UTC, vshankar approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/QA_main_2025#wip-vshankar-testing-20250714111344-debug

2025-07-21 05:24 UTC, merged