mgr/dashboard: fix alert broken for multiple alerts
ceph/ceph pull request #58069
Opened 2024-06-16 12:52 UTC by nizamial09

After carbon the alert panel was broken when there are multiple alerts present (telemetry, motd, password expiration).

![Screenshot from 2024-06-16 18-15-02](https://github.com/ceph/ceph/assets/71764184/a2352fc7-dd41-4078-bb9c-55398b147dd1)

Fixes: https://tracker.ceph.com/issues/66512

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-06-18 14:05 UTC, ivoalmeida approved these changes
lgtm

2024-06-18 21:21 UTC, afreen23 commented
I think the banner notif would fit here more
![image](https://github.com/ceph/ceph/assets/25664409/5354bf4d-7547-4901-a017-bd68cb0bde86)
See this https://carbondesignsystem.com/patterns/notification-pattern/#banner

2024-06-18 21:21 UTC, afreen23 requested changes
I think the banner notif would fit here more
![image](https://github.com/ceph/ceph/assets/25664409/5354bf4d-7547-4901-a017-bd68cb0bde86)
See this https://carbondesignsystem.com/patterns/notification-pattern/#banner

2024-06-19 06:38 UTC, nizamial09 commented
thanks @afreen23 I've applied the banner here. Carbon doesn't natively provide the banner though even though its in their guidelines. So I had to make some extra tweaks inorder to bring the banner.

![Screenshot from 2024-06-19 11-22-22](https://github.com/ceph/ceph/assets/71764184/d61a6599-0305-432a-9d53-989f3633b0dd)

2024-06-19 09:24 UTC, afreen23 approved these changes
looks nice the UX changes, thanks @nizamial09 for beautifying 🎉

2024-06-19 12:14 UTC, nizamial09 commented
jenkins test api

2024-06-19 13:33 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/components/alert-panel/alert-panel.component.ts
> +    const type = this.type === 'danger' ? 'error' : this.type;
thank you. I used the NotificationType enum from the carbon-components and now its perfect

2024-06-19 13:34 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/components/telemetry-notification/telemetry-notification.component.html
> +                class="no-margin-bottom"
agreed. we can remove it separately.

2024-06-20 06:29 UTC, nizamial09 commented
jenkins test make check

2024-06-20 06:29 UTC, nizamial09 commented
jenkins test dashboard

2024-06-20 06:29 UTC, nizamial09 commented
jenkins test dashboard cephadm

2024-06-20 12:48 UTC, merged