common/TrackedOp: do not count the ops marked as nowarn
ceph/ceph pull request #58125
Opened 2024-06-19 04:06 UTC by lxbsz

If an op is marked as nowarn then it won't be counted as the slow requests, but currently it will count the initiated time when iterating the inflight ops.

For example:

[WRN] : 1 slow requests, 1 included below; oldest blocked for > 38.764892 secs
[WRN] : slow request 33.875059 seconds old, received at 2024-06-17T14:14:34.228261+0000: client_request(client.78109915:11369251 mkdir #0x1008ecedea2/chk-89588 2024-06-17T14:14:34.097825+0000 caller_uid=1002960000, caller_gid=0{0,1002960000,}) currently failed to wrlock, waiting

The oldest blocked request is 38.764892 old, but the oldest slow request reported is 33.875059 old.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-06-19 06:51 UTC, leonid-s-usov commented
@batrick we had to introduce a new field `continuous` in the quiesce epic to achieve the same, right? Should we review?

2024-06-19 15:54 UTC, batrick requested changes
otherwise lgtm

2024-06-19 15:54 UTC, batrick commented on src/common/TrackedOp.cc
> +      if (!op.warn_interval_multiplier)
```suggestion
      if (!op.warn_interval_multiplier || op->is_continuous())
```

2024-06-19 15:55 UTC, batrick commented
> @batrick we had to introduce a new field `continuous` in the quiesce epic to achieve the same, right? Should we review?

We could consolidate them, yes.

2024-06-20 00:24 UTC, lxbsz commented on src/common/TrackedOp.cc
> +      if (!op.warn_interval_multiplier)
Good catch. Will fix it.

2024-06-20 10:45 UTC, vshankar approved these changes

2024-06-21 01:47 UTC, batrick approved these changes

2024-06-21 01:47 UTC, batrick commented
jenkins test api

2024-06-21 01:47 UTC, batrick commented
jenkins test make check arm64

2024-06-21 13:25 UTC, batrick commented
jenkins test make check arm64

2024-06-21 15:46 UTC, batrick commented
jenkins test make check arm64

2024-06-22 14:42 UTC, batrick commented
jenkins test make check arm64

2024-06-22 14:50 UTC, batrick commented
This PR is under test in [https://tracker.ceph.com/issues/66609](https://tracker.ceph.com/issues/66609).

2024-06-22 20:21 UTC, batrick commented
jenkins test make check arm64

2024-06-23 18:28 UTC, batrick commented
https://tracker.ceph.com/issues/66609#note-1

2024-06-23 18:32 UTC, merged