🧹 cephadmlib/daemons/nvmeof.py: black reformat
ceph/ceph pull request #58362
Opened 2024-06-30 16:11 UTC by baum

# fix jenkins "make check" CI error

black ci error: https://jenkins.ceph.com/job/ceph-pull-requests/137944/consoleFull#-1762044592e2f9bd1b-f570-4eac-a6c0-0080730e3135

```log
check-black: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm> black --check -l78 -t py36 --skip-string-normalization -v cephadmlib/ Identified `/home/jenkins-build/build/workspace/ceph-pull-requests` as project root containing a .git directory. Found input source directory: "/home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib" /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/__init__.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/agent.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/call_wrappers.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/constants.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/container_daemon_form.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/container_engine_base.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/container_engines.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/container_types.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/context.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/context_getters.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemon_form.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemon_identity.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/__init__.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/ceph.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/custom.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/ingress.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/iscsi.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/monitoring.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/nfs.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/node_proxy.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/smb.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/snmp.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/tracing.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/data_utils.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/decorators.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/deploy.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/deployment_utils.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/exceptions.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/exe_utils.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/file_utils.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/firewalld.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/host_facts.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/locking.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/logging.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/net_utils.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/packagers.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/runscripts.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/ssh.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/sysctl.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/systemd.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/systemd_unit.py wasn't modified on disk since last run. /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/templating.py wasn't modified on disk since last run. would reformat /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm/cephadmlib/daemons/nvmeof.py

Oh no! 💥 💔 💥
1 file would be reformatted, 42 files would be left unchanged. check-black: exit 1 (0.66 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/src/cephadm> black --check -l78 -t py36 --skip-string-normalization -v cephadmlib/ pid=1799926 check-black: FAIL ✖ in 8.14 seconds
```

2024-07-01 09:41 UTC, guits commented
jenkins test make check

2024-07-01 09:41 UTC, guits approved these changes

2024-07-01 09:53 UTC, guits requested changes
I don't get it, you already have this change in PR #54671

2024-07-01 13:55 UTC, adk3798 commented
@baum this got added recently as a required check in make check, but at the time that was setup everything should have been passing the check. If you see something failing it in a given PR, it's likely changes from that PR. I just checked some misc. other PRs open against main and don't see them hitting make check failures related to this so I don't think we have a general problem in main (and there's no reason to have this separate PR to add `mtls_dir` as a parameter to this function)

2024-07-01 14:00 UTC, adk3798 commented
> @baum this got added recently as a required check in make check, but at the time that was setup everything should have been passing the check. If you see something failing it in a given PR, it's likely changes from that PR. I just checked some misc. other PRs open against main and don't see them hitting make check failures related to this so I don't think we have a general problem in main (and there's no reason to have this separate PR to add `mtls_dir` as a parameter to this function)

Actually, I haven't merged the PR to add this to make check quite yet, but I will soon and local testing of src/cephadm tox on main seemed to pass.

2024-07-10 15:37 UTC, adk3798 commented
closing as per https://github.com/ceph/ceph/pull/58362#issuecomment-2200225287

2024-07-10 15:37 UTC, closed without merging