quincy: qa/cephfs: fix test_single_path_authorize_on_nonalphanumeric_fsname
ceph/ceph pull request #58559
Opened 2024-07-12 14:47 UTC by rishabh-d-dave

backport tracker: https://tracker.ceph.com/issues/66930

---

backport of https://github.com/ceph/ceph/pull/58311
parent tracker: https://tracker.ceph.com/issues/66077

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-07-26 10:56 UTC, rishabh-d-dave commented
jenkins test make check

2024-08-02 05:01 UTC, lxbsz commented
jenkins test make check

2024-08-19 08:01 UTC, lxbsz commented
The qa failure should be introduced by this PR: https://pulpito.ceph.com/xiubli-2024-08-13_04:29:48-fs-wip-xiubli-testing-20240812.103236-quincy-distro-default-smithi/7850800/.

2024-08-19 08:08 UTC, lxbsz requested changes

2024-08-19 08:08 UTC, lxbsz commented on qa/tasks/cephfs/test_admin.py
> +        self.mount_b.umount_wait(require_clean=True)
This makes no sense in `Quincy` branch, because the default `CLIENTS_REQUIRED` is `1`, which is inherit from `CephFSTestCase` class.

2024-10-24 11:35 UTC, rishabh-d-dave commented
jenkins test make check

2024-10-24 11:35 UTC, rishabh-d-dave commented
jenkins test api

2024-10-24 11:37 UTC, rishabh-d-dave commented
`self.mount_b` is absent in the test because `CLIENTS_REQUIRED` is set 1 for this test class on Quincy branch. So this patch is not required.

2024-10-24 11:37 UTC, closed without merging