mgr/dashboard: add service management for mgmt-gateway
ceph/ceph pull request #58618
Opened 2024-07-16 07:56 UTC by Pegonzal

Fixes: https://tracker.ceph.com/issues/66963

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-07-31 14:27 UTC, cloudbehl commented
Lets have default values/selection for
1. Count
2. SSL Protocols
3. SSL Ciphers

Also add  description for what authentication means

2024-08-02 07:25 UTC, Pegonzal commented
> Lets have default values/selection for
> 
> 1. Count

Adding one as default

> 2. SSL Protocols
> 3. SSL Ciphers

I don't think any default value here is desired 

> Also add description for what authentication means

I'll look into what description to add for it

2024-08-06 08:13 UTC, cloudbehl commented
There should be some recommendations for user.

Like in case of SSL protocols can be check `TLSv1.2` and `TLSv1.3` in options and likewise whats the default supported for SSL Ciphers? @rkachach any idea?

2024-08-06 13:18 UTC, rkachach commented
> > Lets have default values/selection for
> > 
> > 1. Count
> 
> Adding one as default
> 
> > 2. SSL Protocols
> > 3. SSL Ciphers
> 
> I don't think any default value here is desired
> 
> > Also add description for what authentication means
> 
> I'll look into what description to add for it

As for the count right now we can only have one instance (no HA is supported in the first release). For the configuration we support whatever nginx supports, by default we use `TLSv1.3` for strict security ad `TLSv1.2` in some ciphers combinations could be weak. The configuration we are using has been generated by `https://ssl-config.mozilla.org/#server=nginx`

2024-08-20 12:35 UTC, afreen23 requested changes

2024-08-20 16:00 UTC, Pegonzal commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
> +              };
Updated it as per your comment, @afreen23

2024-08-21 05:38 UTC, Pegonzal commented
jenkins test make check

2024-08-21 05:38 UTC, Pegonzal commented
jenkins test dashboard

2024-08-21 05:39 UTC, Pegonzal commented
jenkins test dashboard cephadm

2024-08-21 11:01 UTC, afreen23 requested changes
Hello,

Here are few suggestions from my end:

1. Fixing misalignment
![image](https://github.com/user-attachments/assets/dd2baf72-55be-45df-aee1-d27a3fc4a181)
Hey looks like the labels and checkboxes are quite off.
We need them to be aligned properly.
if you need help you may check other forms' html/css.

2. Having everything under SSL checkbox

![image](https://github.com/user-attachments/assets/12eeafaf-66e9-42a7-a20a-0e7119776639)
Selecting SSL protocol/cipher and then choosing one more SSL check box for cert and key looks confusing so lets put protocol and cipher too with certs and key.

So just one checkbox for SSL which will open up all these options.


3. Multi-select instead of checkboxes

We can consider using [carbon multi-select here](https://web-components.carbondesignsystem.com/?path=/story/components-multi-select--default&globals=outline:true) for protocol and cipher

Thanks for the work @Pegonzal

2024-08-21 11:33 UTC, afreen23 commented
> > > Lets have default values/selection for
> > > 
> > > 1. Count
> > 
> > 
> > Adding one as default
> > > 2. SSL Protocols
> > > 3. SSL Ciphers
> > 
> > 
> > I don't think any default value here is desired
> > > Also add description for what authentication means
> > 
> > 
> > I'll look into what description to add for it
> 
> As for the count right now we can only have one instance (no HA is supported in the first release). For the configuration we support whatever nginx supports, by default we use `TLSv1.3` for strict security ad `TLSv1.2` in some ciphers combinations could be weak. The configuration we are using as default has been generated by `https://ssl-config.mozilla.org/#server=nginx` + some other tweaks.
> 
> Our default config must be secure. We should add a pop-up/warning that changing security configuration of the mgmt-gateway is `user's responsibility` and could lead to a weaker security config.

Then based on https://github.com/ceph/ceph/blob/main/src/pybind/mgr/cephadm/templates/services/mgmt-gateway/internal_server.conf.j2 we can have have some items preselected/checked.

And agree we can add a warning "Modifying security settings may weaken security" or a better wording.

Thanks

2024-08-22 15:54 UTC, Pegonzal commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
> +        </cd-alert-panel>
With `all other services` I meant, grafana, prometheus, alertmanager...
The service mgmt-gateway acts as a reverse proxy providing a single access point, meaning that these services will be available to the user from `{{currentURL}}:{{port}}/service_name`

2024-08-22 15:54 UTC, Pegonzal commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.html
> +                </label>
Changed the text

2024-08-22 15:56 UTC, Pegonzal commented
Thanks for the review @Afreen, I tried to address all your comments. Please take a look and let me know what you think

2024-08-23 07:29 UTC, Pegonzal commented
jenkins test make check

2024-08-23 07:29 UTC, Pegonzal commented
jenkins test dashboard

2024-08-23 07:30 UTC, Pegonzal commented
jenkins test dashboard cephadm

2024-08-27 02:37 UTC, afreen23 commented
Hey,

Commenting here as well just for record.

![image](https://github.com/user-attachments/assets/860d63a9-bf77-41de-b0f3-d4b64d314b6e)
we need to enable this warning if user changes defaults for SSL based settings
I would assume we dont need to provide for now SSL ciphers as there are various options and it might be confusing.
Lets take the feedback and if required add then.

Thanks, great work!

2024-08-27 07:50 UTC, Pegonzal commented
>we need to enable this warning if user changes defaults for SSL based settings

Changed it to show warning on user form changes

2024-08-28 08:48 UTC, Pegonzal commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
> +const SSL_CIPHERS = ['AES128-SHA', 'AES256-SHA', 'RC4-SHA'];
Just to clarify, I believe this is the list of ciphers that will be overwritten 
https://github.com/ceph/ceph/blob/main/src/pybind/mgr/cephadm/templates/services/mgmt-gateway/external_server.conf.j2

We could expand the cipher options in the dropdown or just let the user write the desired one, I guess that would be preferred.
The main issue I see with this is the lack of validation of the ciphers. At least I can't find it if there is any in place.
We could perform frontend validation of the ciphers, but I am not sure which ones we should be taking into account.
Anyways, the recommended use of this service is to have the default configuration as it already tries to provide the strongest security options available. Therefore I just went with this three options I saw in a previous mgmt-gateway spec file example, and we can always expand on them.

What do you think @afreen23 ?

2024-09-02 06:21 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
> +const SSL_CIPHERS = ['AES128-SHA', 'AES256-SHA', 'RC4-SHA'];
Lets add a validation as per the format mentioned  here: https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers
The list of cipher suites is overwhelming therefore better to have regex and string input only. Thanks @Pegonzal

2024-09-09 11:42 UTC, Pegonzal commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
> +const SSL_CIPHERS = ['AES128-SHA', 'AES256-SHA', 'RC4-SHA'];
I've included the possible ciphers, and you can either type or select any of them thanks to the carbon component, you can find the updated video in the PR description, plesae @afreen23 let me know what you think.

The list of ciphers come from the previously mentioned `external_server.conf.j2`

2024-09-09 15:26 UTC, Pegonzal commented
jenkins test make check

2024-09-10 07:18 UTC, Pegonzal commented
https://jenkins.ceph.com/job/ceph-pull-requests/142995/
```
No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.
```

Retriggering

2024-09-10 07:18 UTC, Pegonzal commented
jenkins test make check

2024-09-12 09:17 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
> +const SSL_CIPHERS = ['AES128-SHA', 'AES256-SHA', 'RC4-SHA'];
Sounds good, then @Pegonzal , let me check

2024-09-13 07:59 UTC, rkachach commented
While testing this PR I saw that the spec generated when using default config has the "port" field set to 443:

```
ceph orch ls --service_name mgmt-gateway --export
service_type: mgmt-gateway
service_name: mgmt-gateway
placement:
  hosts:
  - ceph-node-1
spec:
  port: 443
  ssl_protocols:
  - TLSv1.3 
```

This causes issues when generating the `redirect_uri`. I'd suggest by now to omit the port if it's the default one (443 for https and 80 for http). I'll change the cephadm code to handle this better latter, but for now I think we should adjust the dashboard side as all cephadm PRs have been already merged.

2024-09-13 08:18 UTC, Pegonzal commented
> @Pegonzal @afreen23 while testing this PR I saw that the spec generated when using default config has the `port` field set to 443:
> 
> ```
> ceph orch ls --service_name mgmt-gateway --export
> service_type: mgmt-gateway
> service_name: mgmt-gateway
> placement:
>   hosts:
>   - ceph-node-1
> spec:
>   port: 443
>   ssl_protocols:
>   - TLSv1.3 
> ```
> 
> This causes issues when generating the `redirect_uri`. I'd suggest by now to omit the port if it's the default one (443 for https and 80 for http). I'll change the cephadm code to handle this better latter, but for now I think we should adjust the dashboard side as all cephadm PRs have been already merged.

Thanks @rkachach , I have updated the PR.
Now, for default:

```
[ceph: root@ceph-node-00 /]# ceph orch ls --service_name mgmt-gateway --export
service_type: mgmt-gateway
service_name: mgmt-gateway
placement:
  count: 1
spec:
  ssl_ciphers:
  - ECDSA
  - AES128
  ssl_protocols:
  - TLSv1.3
```

Other ports:
```
[ceph: root@ceph-node-00 /]# ceph orch ls --service_name mgmt-gateway --export
service_type: mgmt-gateway
service_name: mgmt-gateway
placement:
  count: 1
spec:
  port: 8888
  ssl_protocols:
  - TLSv1.3
[ceph: root@ceph-node-00 /]# 
```

2024-09-13 08:26 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
> +const SSL_CIPHERS = ['AES128-SHA', 'AES256-SHA', 'RC4-SHA'];
I checked that box, if I entered values what mentione din options I could see this but If I typed out, it did not work for me.
Fpor eg. I entered "HIGH:!aNULL:!MD5;" which is default in [nginx](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers) and it did not show up in config. 
The cipher field was absent.

Again jhghlighting, the list of ciphers provided might not be helpful here either as its rather an overwhelming cipher suites used and a combo of those.
If you try `openssl ciphers` in command shell, you would see by yourself.
IMO lets leave it to the user to type out the cipher.
All the cipher defined are seperated by a colon `:` and end with semicolon `:` as what I am seeing, so we cna put some validation as well.

Thanks

2024-09-13 08:43 UTC, rkachach commented
> > @Pegonzal @afreen23 while testing this PR I saw that the spec generated when using default config has the `port` field set to 443:
> > ```
> > ceph orch ls --service_name mgmt-gateway --export
> > service_type: mgmt-gateway
> > service_name: mgmt-gateway
> > placement:
> >   hosts:
> >   - ceph-node-1
> > spec:
> >   port: 443
> >   ssl_protocols:
> >   - TLSv1.3 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This causes issues when generating the `redirect_uri`. I'd suggest by now to omit the port if it's the default one (443 for https and 80 for http). I'll change the cephadm code to handle this better latter, but for now I think we should adjust the dashboard side as all cephadm PRs have been already merged.
> 
> Thanks @rkachach , I have updated the PR. Now, for default:
> 
> ```
> [ceph: root@ceph-node-00 /]# ceph orch ls --service_name mgmt-gateway --export
> service_type: mgmt-gateway
> service_name: mgmt-gateway
> placement:
>   count: 1
> spec:
>   ssl_ciphers:
>   - ECDSA
>   - AES128
>   ssl_protocols:
>   - TLSv1.3
> ```
> 
> Other ports:
> 
> ```
> [ceph: root@ceph-node-00 /]# ceph orch ls --service_name mgmt-gateway --export
> service_type: mgmt-gateway
> service_name: mgmt-gateway
> placement:
>   count: 1
> spec:
>   port: 8888
>   ssl_protocols:
>   - TLSv1.3
> [ceph: root@ceph-node-00 /]# 
> ```

@Pegonzal by default (if the user has not changes the config) we shouldn't include anything in the spec section:

```
spec:
  ssl_ciphers:
  - ECDSA
  - AES128
  ssl_protocols:
  - TLSv1.3
```
Just FYI, when this field is not specified the real defaults are:

```    
ssl_ciphers              ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
```
And these defaults are part of the templates managed by cephadm... unfortunately there's no way at this moment for the dashboard to get these values :(

2024-09-13 08:43 UTC, Pegonzal commented on src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts
> +const SSL_CIPHERS = ['AES128-SHA', 'AES256-SHA', 'RC4-SHA'];
I'm not following here. Do you want to add the OpenSSL formatting for this?

As it is right now, you can select the desired ciphers, as seen in the video's description

2024-09-16 07:03 UTC, Pegonzal commented
jenkins test api

2024-09-16 08:42 UTC, afreen23 approved these changes

2024-09-16 09:34 UTC, Pegonzal commented
API failure, no problems identified: https://jenkins.ceph.com/job/ceph-api/81635/

2024-09-16 10:55 UTC, Pegonzal commented
Rebased the PR after merging #59379 and added a [fix](https://github.com/ceph/ceph/pull/58618/files#diff-ddec8ca48d4a38889b7993eacdbe3d38a47aea7434460bfa0d67874fffea42a6R1239) to trim `allowlist_domains` , mentioned [here](https://github.com/ceph/ceph/pull/59379#issuecomment-2352467287)

2024-09-16 13:28 UTC, rkachach commented
jenkins test dashboard

2024-09-16 13:28 UTC, rkachach commented
jenkins test dashboard cephadm

2024-09-16 14:13 UTC, Pegonzal commented
jenkins test windows

2024-09-16 14:19 UTC, Pegonzal commented
jenkins test windows

2024-09-16 15:06 UTC, rkachach commented
I tested this PR (rebasing on main) and I can see that the mgmt-gateway is created correctly:

```
[ceph: root@ceph-node-0 /]# ceph orch ls --service_name mgmt-gateway --export
service_type: mgmt-gateway
service_name: mgmt-gateway
placement:
  count: 1
  hosts:
  - ceph-node-1
spec:
  enable_auth: true
```

2024-09-16 16:34 UTC, merged