rgw: donot allow NotPrincipal with Allow Effect
ceph/ceph pull request #58686
Opened 2024-07-19 17:40 UTC by clwluvw

> NotPrincipal must be used with "Effect":"Deny". Using it with "Effect":"Allow" is not supported.
cf. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notprincipal.html
    
Fixes: https://tracker.ceph.com/issues/67047

2024-07-19 18:28 UTC, cbodley commented
i grepped our s3-tests for NotPrincipal and found a single match in [test_get_nonpublicpolicy_deny_bucket_policy_status()](https://github.com/ceph/s3-tests/blob/4eda9c0/s3tests_boto3/functional/test_s3.py#L12796-L12810):
> "Effect": "Allow",
"NotPrincipal": {"AWS": "arn:aws:iam::s3tenant1:root"},

can you please update that test case, now that we'd expect it to fail? if it's no longer testing IsPublic, maybe rename it to something like "test_bucket_policy_allow_not_principal"

2024-07-19 18:53 UTC, clwluvw commented
@cbodley Added in https://github.com/ceph/s3-tests/pull/573

2024-07-19 19:29 UTC, cbodley approved these changes

2024-07-22 18:45 UTC, ivancich requested changes
This PR causes the s3tests_boto3.functional.test_s3.**test_get_nonpublicpolicy_deny_bucket_policy_status** to fail.

2024-07-22 18:48 UTC, cbodley commented
@ivancich can you please link the shaman build for that run? i can reschedule it against the s3test changes in https://github.com/ceph/s3-tests/pull/573

2024-07-22 21:35 UTC, ivancich commented
@cbodley Here it is: https://shaman.ceph.com/builds/ceph/wip-eric-testing-1/0bf402ff8193eee5d71684bab55ddb08a5cdadbe/

2024-07-23 12:59 UTC, cbodley commented
> @cbodley Here it is: https://shaman.ceph.com/builds/ceph/wip-eric-testing-1/0bf402ff8193eee5d71684bab55ddb08a5cdadbe/

thanks, i pushed a branch https://github.com/cbodley/ceph/commits/wip-qa-rgw-dont-allow-not-principal based on that which points s3-tests at https://github.com/ceph/s3-tests/pull/573 and rescheduled with:
> $ teuthology-suite -m smithi -s rgw -c wip-eric-testing-1 -S 0bf402ff8193eee5d71684bab55ddb08a5cdadbe --suite-repo https://github.com/cbodley/ceph.git --suite-branch wip-qa-rgw-dont-allow-not-principal -p 80

pending in https://pulpito.ceph.com/cbodley-2024-07-23_12:55:55-rgw-wip-eric-testing-1-distro-default-smithi/

2024-07-23 12:59 UTC, cbodley commented
jenkins test make check

2024-07-23 17:45 UTC, cbodley commented
https://jenkins.ceph.com/job/ceph-pull-requests/139596/
> Agent went offline during the build
ERROR: Connection was broken

2024-07-23 19:24 UTC, cbodley commented
> pending in https://pulpito.ceph.com/cbodley-2024-07-23_12:55:55-rgw-wip-eric-testing-1-distro-default-smithi/

@ivancich looks like a pass! could you please update your review?

2024-07-25 14:26 UTC, ivancich approved these changes
Thanks, Casey.

2024-07-25 14:31 UTC, merged