quincy: mds/client: return -ENODATA when xattr doesn't exist for removexattr
ceph/ceph pull request #58772
Opened 2024-07-24 02:46 UTC by lxbsz

backport tracker: https://tracker.ceph.com/issues/66776

---

backport of https://github.com/ceph/ceph/pull/55945
parent tracker: https://tracker.ceph.com/issues/64679

This backport will just ignore the following comit:

```
commit ec30c46d1773679ae3787cf68a14b0f7d869101b
Author: Xiubo Li <xiubli@redhat.com>
Date:   Tue Mar 5 08:32:34 2024 +0800

    test/libcephfs: move FsCrypt xattr test to dedicated test file
    
    Switch to use XATTR_CREATE.
    
    Fixes: https://tracker.ceph.com/issues/64679
    Signed-off-by: Xiubo Li <xiubli@redhat.com>
```

Which makes no sense in quincy.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-07-25 04:52 UTC, lxbsz commented
jenkins test make check

2024-08-02 05:04 UTC, lxbsz commented
jenkins test make check

2024-10-15 12:16 UTC, vshankar commented
https://pulpito.ceph.com/xiubli-2024-08-13_04:29:48-fs-wip-xiubli-testing-20240812.103236-quincy-distro-default-smithi/7850722/ seems related to this change.

2024-10-15 12:17 UTC, vshankar requested changes
https://github.com/ceph/ceph/pull/58772#issuecomment-2413752964

PTAL @lxbsz

2025-01-13 13:06 UTC, closed without merging