crimson/osd/pg: properly propagate snap mapper updates and do cleanr-region-based clone objects recovery
ceph/ceph pull request #58868
Opened 2024-07-26 07:28 UTC by xxhdx1985126

This is a POC draft.

Fixes: https://tracker.ceph.com/issues/67057
Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-08-06 01:40 UTC, xxhdx1985126 commented
jenkins test make check

2024-08-07 01:47 UTC, athanatos commented
I think this is mostly right.  I'd like to try to avoid using interruptor::async in the fast path, though.  I'd started on a refactor you might be able to use instead of your last commit, though: https://github.com/athanatos/ceph/tree/sjust/wip-67057-snapmapper

2024-08-07 01:50 UTC, athanatos commented on src/crimson/osd/object_metadata_helper.cc
> +  const pg_missing_item missing_item = missing.get_items().at(soid);
const pg_missing_item & probably?

2024-08-07 02:03 UTC, xxhdx1985126 commented
> I think this is mostly right. I'd like to try to avoid using interruptor::async in the fast path, though. I'd started on a refactor you might be able to use directly instead of your last commit (https://github.com/athanatos/ceph/tree/sjust/wip-67057-snapmapper)?

Thanks:-) I'll drop my last commit.

2024-08-07 02:03 UTC, xxhdx1985126 commented on src/crimson/osd/object_metadata_helper.cc
> +  const pg_missing_item missing_item = missing.get_items().at(soid);
yeah, sorry, will correct it.

2024-08-07 02:05 UTC, xxhdx1985126 commented
@athanatos BTW, can I merge your commits in https://github.com/athanatos/ceph/tree/sjust/wip-67057-snapmapper to this PR?

2024-08-07 02:12 UTC, xxhdx1985126 commented
> 256 - unittest-seastar-calc-subsets (Subprocess aborted)

Sorry, I didn't notice this build error, will fix it.

2024-08-07 02:20 UTC, athanatos commented
@xxhdx1985126 Yeah, you can cherry-pick them over if they seem ok to you.

2024-08-15 03:17 UTC, xxhdx1985126 commented
jenkins test make check

2024-08-17 03:16 UTC, xxhdx1985126 commented
jenkins test make check

2024-08-17 03:16 UTC, xxhdx1985126 commented
jenkins test api

2024-08-17 11:27 UTC, xxhdx1985126 commented
jenkins test api

2024-08-17 11:27 UTC, xxhdx1985126 commented
@Matan-B @athanatos I think this pr is good to go, please take a look again, thanks.

2024-08-18 06:16 UTC, xxhdx1985126 commented
jenkins test api

2024-08-20 02:56 UTC, athanatos commented
jenkins test make check

2024-08-20 03:04 UTC, athanatos approved these changes
PG::submit_transaction has gotten a bit out of hand, but this looks ok to me for now.  @Matan-B should have a look before this merges, though.

2024-08-20 03:09 UTC, xxhdx1985126 commented
> PG::submit_transaction has gotten a bit out of hand, but this looks ok to me for now. @Matan-B should have a look before this merges, though.

Um, I delibrately change `PG::submit_transaction()` to make sure that the pglog is mutated when the `submitted` future resolves. Otherwise, the pglog may get out-of-order.

2024-08-20 04:02 UTC, athanatos commented
> > PG::submit_transaction has gotten a bit out of hand, but this looks ok to me for now. @Matan-B should have a look before this merges, though.
> 
> Um, I delibrately changed `PG::submit_transaction()` to make sure that the pglog is mutated when the `submitted` future resolves. Otherwise, the pglog may get out-of-order.

Oh, I think the changes are correct -- it's just getting tough for me to follow.

2024-08-20 04:20 UTC, athanatos commented
jenkins test api

2024-08-20 09:11 UTC, Matan-B reviewed
>Um, I delibrately changed PG::submit_transaction() to make sure that the pglog is mutated when the submitted future resolves. Otherwise, the pglog may get out-of-order.

Can you help me understand this statement?

Going back to my last comment, is there an additional reason to edit `submit_transaction` to return an interruptible_future besides the added waiting requirement in `_submit_transaction`?

--- 

>Oh, I understand now. My version didn't actually ensure that PG::log_operation was called before sends_complete is initiated. The version in this PR fixes that and is actually a bit easier to understand.

How can `PG::log_operation` be called after `sends_complete` is initiated?

```
ReplicatedBackend::_submit_transaction()
{
  for (auto pg_shard : pg_shards) {
    sends->emplace_back()
  }
  pg.log_operation(..);
  auto all_completed = ...
  auto sends_complete = seastar::when_all_succeed(
    sends->begin(), sends->end()
  ).finally([sends=std::move(sends)] {});
  return {std::move(sends_complete), std::move(all_completed)};
}
```

2024-08-20 09:12 UTC, Matan-B commented on src/crimson/osd/osd_operations/snaptrim_event.cc
> +		  });
This can also refactored in a future PR, feel free to ignore.

2024-08-20 12:45 UTC, xxhdx1985126 commented on src/crimson/osd/pg.cc
> +  auto [submitted, all_completed] = co_await backend->mutate_object(
Yes, that's right.

2024-08-20 13:16 UTC, Matan-B requested changes
I started a refactor on top of the last commit, this should help us avoid re writing `update_snap_map` as the logic there is common.

https://github.com/Matan-B/ceph/commits/wip-matanb-clone-recovery-snapmapper/

If you decide to incorporate the commits above, perhaps we should also add the coroutine suggestions above. I'll try to push them to my branch as well.

2024-08-20 14:21 UTC, Matan-B commented on src/crimson/osd/osd_operations/snaptrim_event.cc
> +		  });
Addressed in the branch attached below

2024-08-21 01:36 UTC, xxhdx1985126 commented on src/crimson/osd/ops_executer.h
> +      });
It seems that we'd better not use coroutine in lambdas: https://quuxplusone.github.io/blog/2019/07/10/ways-to-get-dangling-references-with-coroutines/

2024-08-21 01:39 UTC, xxhdx1985126 commented on src/crimson/osd/osd_operations/snaptrim_event.cc
> +		  });
Same as https://github.com/ceph/ceph/pull/58868#discussion_r1724171698

2024-08-21 08:09 UTC, Matan-B commented
> Um, this is actually what I did in the initial version; but it seems that it'd better not involve seastar::async in the fast path: ceph#58868 (comment)

The refactored commit is identical to the implementation suggested here. Currently, seastar::async will be used in `OpsExecuter::snap_map_remove` regardless.

2024-08-21 08:13 UTC, xxhdx1985126 commented
> > Um, this is actually what I did in the initial version; but it seems that it'd better not involve seastar::async in the fast path: #58868 (comment)
> 
> @xxhdx1985126 The refactored commit is identical to the implementation suggested here. Currently, seastar::async will be used in `OpsExecuter::snap_map_remove` regardless.

Yes, but `OpsExecuter::snap_map_remove` is seldomly called in the fast path, am I right?

2024-08-21 08:18 UTC, Matan-B commented
> Yes, but `OpsExecuter::snap_map_remove` is seldomly called in the fast path, am I right?

In the current implementation in this PR: we use seastar::async in `OpsExecuter::snap_map_remove` which is called in `PG::update_snap_map`

In my suggestion branch: we use seastar::async in `PG::update_snap_map` directly.

Are there any differences which I'm missing?

2024-08-21 08:47 UTC, xxhdx1985126 commented
@Matan-B I cherry-pick your first 3 commits here.

About the last commit which use coroutines within varialbe-capturing lambdas, we might need more discussion.

2024-08-21 10:41 UTC, Matan-B commented
I have moved the common update_snap_map logic to SnapMapper::update_snap_map and updated Crimson to make use of it.
Classic should also reuse the common method but I'll push it as a separate PR once we merge this (to avoid blockers). 

---

Regarding the last commit (1d30c4f). @xxhdx1985126  shared come concerns in using co routines in lambdas [1]  [2]. I think that we should consider this refactor despite the possible risk.
The guideline of "Do not use capturing lambdas that are coroutines"  may not apply here since the lambda in question does not capture beside `this`:
```
[this](auto head_obc, auto clone_obc) -> ObjectContextLoader::load_obc_iertr::future<>
```
We've decided to add the commit here in order have more opinions. 

CC: @athanatos, @cyx1231st 

[1] https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rcoro-capture
[2] https://quuxplusone.github.io/blog/2019/07/10/ways-to-get-dangling-references-with-coroutines

2024-08-21 14:06 UTC, Matan-B commented on src/crimson/osd/ops_executer.h
> +      });
no coroutines in lambdas here 3e093b1e3de9942c890301d64b0d014d2ac148a9

2024-08-22 09:26 UTC, xxhdx1985126 commented
> Regarding the commit ([1d30c4f](https://github.com/ceph/ceph/commit/1d30c4fa61fc1694f581f2a52b64fcef2dcc0e79)). @xxhdx1985126 shared concerns in using co routines in lambdas [1] [2]. I think that we should consider this refactor despite the possible risk. The guideline of "Do not use capturing lambdas that are coroutines" may not apply here since the lambda in question does not capture beside `this`:
> 
> ```
> [this](auto head_obc, auto clone_obc) -> ObjectContextLoader::load_obc_iertr::future<>
> ```
> 
> We've decided to add the commit here in order have more opinions.
> 
> Same question with commit [ef46219](https://github.com/ceph/ceph/commit/ef462191083bc4e9c80e67a3645e59b1084860ca)
> 
> CC: @athanatos, @cyx1231st
> 
> [1] https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rcoro-capture [2] https://quuxplusone.github.io/blog/2019/07/10/ways-to-get-dangling-references-with-coroutines

@Matan-B After a second thought, I've change my mind now, it should be good to use coroutines in this specific context.

2024-08-22 12:00 UTC, xxhdx1985126 commented
I've just fixed a bug in this PR. The change is in `calc_clone_subsets`: we should check the dirty_regions' emptiness before modifying `subsets.data_subset`.

2024-08-26 10:21 UTC, Matan-B approved these changes
Approving, will await additional approval

2024-08-26 10:30 UTC, xxhdx1985126 commented
> @xxhdx1985126, PTAL at the last 3 commits, no change in behavior. If they look good to you we can move this one to qa.

LGTM:-)

2024-08-26 22:38 UTC, athanatos approved these changes

2024-08-27 08:28 UTC, Matan-B commented
jenkins test api

2024-08-28 10:40 UTC, Matan-B commented
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/protobuf/protobuf-config.cmake:14 (include):
  include could not find requested file:

    /usr/lib/x86_64-linux-gnu/cmake/protobuf/protobuf-targets.cmake
Call Stack (most recent call first):
  src/CMakeLists.txt:391 (_find_package)
  src/seastar/cmake/SeastarDependencies.cmake:162 (find_package)
  src/seastar/CMakeLists.txt:399 (seastar_find_dependencies)
```

2024-08-28 10:41 UTC, Matan-B commented
jenkins test make check

2024-08-29 10:29 UTC, Matan-B commented
jenkins test make check

2024-08-29 10:29 UTC, Matan-B commented
jenkins test api

2024-08-29 11:30 UTC, Matan-B commented
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-testing-58868/

2024-08-29 11:55 UTC, Matan-B commented
jenkins test make check

2024-09-03 14:02 UTC, Matan-B commented
osds unable to start, looking into this

2024-09-08 13:59 UTC, Matan-B commented
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-testing-58868-v2/

2024-09-08 14:00 UTC, Matan-B commented
> osds unable to start, looking into this

Last commit should handle this

2024-09-08 15:12 UTC, Matan-B commented
jenkins test make check

2024-09-09 14:49 UTC, Matan-B commented
jenkins test make check

2024-09-09 14:49 UTC, Matan-B commented
https://pulpito.ceph.com/matan-2024-09-09_12:52:34-crimson-rados-wip-matanb-crimson-testing-58868-v3-distro-crimson-smithi/

2024-09-10 06:30 UTC, merged