reef: mgr/dashboard: Changes for Sign out text to Login out
ceph/ceph pull request #58989
Opened 2024-08-01 12:19 UTC by prgoel-code

backport tracker: https://tracker.ceph.com/issues/67201

---

backport of https://github.com/ceph/ceph/pull/58844
parent tracker: https://tracker.ceph.com/issues/67075

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-08-05 11:56 UTC, nizamial09 commented
jenkins test dashboard

2024-08-05 11:56 UTC, nizamial09 commented
jenkins test dashboard cephadm

2024-08-05 11:57 UTC, nizamial09 commented
jenkins test make check

2024-08-06 05:34 UTC, prgoel-code commented
ceph dashboard cephadm e2e tests

2024-08-08 10:50 UTC, cloudbehl commented
jenkins test dashboard cephadm

2024-08-24 21:57 UTC, afreen23 commented
jenkins test dashboard

2024-08-26 09:45 UTC, afreen23 commented
jenkins test dashboard

2024-08-27 02:28 UTC, afreen23 commented
jenkins test dashboard

2024-09-13 10:17 UTC, afreen23 commented
jenkins test dashboard

2024-09-16 19:29 UTC, afreen23 requested changes
@prgoel-code We need to fix failing tests here due to the change brought in here.
```
Error Message
Timed out retrying after 120000ms: Expected to find content: 'Sign out' within the selector: 'cd-identity span' but never did.
Stacktrace
AssertionError: Timed out retrying after 120000ms: Expected to find content: 'Sign out' within the selector: 'cd-identity span' but never did.
    at LoginPageHelper.doLogout (cypress/e2e/ui/login.po.ts:18:7)
    at Context.eval (cypress/e2e/ui/login.e2e-spec.ts:15:10)
```

2024-09-27 11:09 UTC, prgoel-code commented
Pull Request Triage / pr-triage (pull_request_target)  is failing.. Is there any solution for this ?

2024-09-30 07:14 UTC, prgoel-code commented
Please find the attached error.. Its not related to UI changes. 
![image](https://github.com/user-attachments/assets/d575d361-7b28-456b-8839-cd41c419ce1a)

2024-09-30 07:40 UTC, afreen23 commented
jenkins test make check

2024-09-30 07:42 UTC, afreen23 commented
jenkins test dashboard cephadm

2024-09-30 07:43 UTC, afreen23 commented
> Please find the attached error.. Its not related to UI changes. ![image](https://private-user-images.githubusercontent.com/176040506/371982598-d575d361-7b28-456b-8839-cd41c419ce1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODI0NzksIm5iZiI6MTcyNzY4MjE3OSwicGF0aCI6Ii8xNzYwNDA1MDYvMzcxOTgyNTk4LWQ1NzVkMzYxLTdiMjgtNDU2Yi04ODM5LWNkNDFjNDE5Y2UxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNzQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjU5MmVlOGJiZDFjMWY1NTU3MDA5MDYxODBhNmFmNzgxNzkxMDVhMWU2ZjEwZjFhMTQwYzczY2RhZmUwMmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.y2bk1VN6W6KV20GudoVL1q3B0DD5PyFJNjpgI0IDOSI)

Seems flake, lets retrigger and get all these tests passing.

2024-09-30 09:49 UTC, prgoel-code commented
jenkins test make check

2024-09-30 15:26 UTC, afreen23 approved these changes

2024-09-30 15:26 UTC, merged