squid: mgr/dashboard: Changes for Sign out text to Login out
ceph/ceph pull request #58988
Opened 2024-08-01 12:14 UTC by prgoel-code

backport tracker: https://tracker.ceph.com/issues/67200

---

backport of https://github.com/ceph/ceph/pull/58844
parent tracker: https://tracker.ceph.com/issues/67075

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-08-01 13:10 UTC, nizamial09 approved these changes

2024-08-05 11:56 UTC, nizamial09 commented
jenkins test api

2024-08-05 11:56 UTC, nizamial09 commented
jenkins test make check

2024-08-05 11:56 UTC, nizamial09 commented
jenkins test dashboard

2024-08-05 11:56 UTC, nizamial09 commented
jenkins test dashboard cephadm

2024-08-24 21:58 UTC, afreen23 commented
jenkins test dashboard

2024-08-24 21:58 UTC, afreen23 commented
jenkins test dashboard cephadm

2024-08-24 21:58 UTC, afreen23 commented
jenkins test make check

2024-08-26 09:41 UTC, afreen23 commented
jenkins test make check

2024-08-26 09:42 UTC, afreen23 commented
jenkins test make dashboard

2024-08-26 09:42 UTC, afreen23 commented
jenkins test make dashboard cephadm

2024-08-26 09:42 UTC, afreen23 commented
jenkins test make dashboard cephadm

2024-08-26 09:43 UTC, afreen23 commented
jenkins test make dashboard

2024-08-26 09:43 UTC, afreen23 commented
jenkins test dashboard

2024-08-26 09:43 UTC, afreen23 commented
jenkins test dashboard cephadm

2024-08-27 02:29 UTC, afreen23 commented
jenkins test dashboard

2024-08-27 02:29 UTC, afreen23 commented
jenkins test dashboard cephadm

2024-08-30 13:01 UTC, afreen23 commented
jenkins test dashboard

2024-09-13 10:18 UTC, afreen23 commented
Failing tests dashboard:
```
[Test Result](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/) (10 failures / +2)
[should create image.Images page create, edit & delete image test should create image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/should%20create%20image/Images_page_create__edit___delete_image_test_should_create_image/)
[should edit image.Images page create, edit & delete image test should edit image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/should%20edit%20image/Images_page_create__edit___delete_image_test_should_edit_image/)
[should delete image.Images page create, edit & delete image test should delete image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/should%20delete%20image/Images_page_create__edit___delete_image_test_should_delete_image/)
["before all" hook for "should move the image to the trash".Images page move to trash, restore and purge image tests "before all" hook for "should move the image to the trash"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/%22before%20all%22%20hook%20for%20%22should%20move%20the%20image%20to%20the%20trash%22/Images_page_move_to_trash__restore_and_purge_image_tests__before_all__hook_for__should_move_the_image_to_the_trash_/)
["after all" hook for "should move the image to the trash".Images page move to trash, restore and purge image tests "after all" hook for "should move the image to the trash"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/%22after%20all%22%20hook%20for%20%22should%20move%20the%20image%20to%20the%20trash%22/Images_page_move_to_trash__restore_and_purge_image_tests__after_all__hook_for__should_move_the_image_to_the_trash_/)
[should logout when clicking the button.Login page should logout when clicking the button](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/should%20logout%20when%20clicking%20the%20button/Login_page_should_logout_when_clicking_the_button/)
[should create pool and check audit logs reacted.Logs page audit logs respond to pool creation and deletion test should create pool and check audit logs reacted](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/should%20create%20pool%20and%20check%20audit%20logs%20reacted/Logs_page_audit_logs_respond_to_pool_creation_and_deletion_test_should_create_pool_and_check_audit_logs_reacted/)
[should delete pool and check audit logs reacted.Logs page audit logs respond to pool creation and deletion test should delete pool and check audit logs reacted](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/testReport/junit/(root)/should%20delete%20pool%20and%20check%20audit%20logs%20reacted/Logs_page_audit_logs_respond_to_pool_creation_and_deletion_test_should_delete_pool_and_check_audit_logs_reacted/)
[Show all failed tests >>>](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16110/#showFailuresLink)
```

2024-09-16 19:30 UTC, afreen23 commented
jenkins test dashboard

2024-09-16 19:31 UTC, afreen23 requested changes
@prgoel-code we might need to fix login/logout tests:
Please confirm once dashbord test run finishes.
Thanks

```
Error Message
Timed out retrying after 120000ms: Expected to find content: 'Sign out' within the selector: 'cd-identity span' but never did.
Stacktrace
AssertionError: Timed out retrying after 120000ms: Expected to find content: 'Sign out' within the selector: 'cd-identity span' but never did.
    at LoginPageHelper.doLogout (cypress/e2e/ui/login.po.ts:18:7)
    at Context.eval (cypress/e2e/ui/login.e2e-spec.ts:15:10)
```

2024-09-24 08:32 UTC, prgoel-code commented
jenkins test dashboard cephadm

2024-09-24 13:14 UTC, prgoel-code commented
jenkins make check

2024-09-24 13:16 UTC, prgoel-code commented
I have made the required changes for same.. @afreen23

2024-09-25 06:00 UTC, afreen23 commented
jenkins make check

2024-09-25 08:52 UTC, Pegonzal commented
Make check unrelated failure:
https://jenkins.ceph.com/job/ceph-pull-requests/143862/
```
Identified problems
No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.
```

2024-09-25 08:52 UTC, Pegonzal commented
jenkins test make check

2024-09-26 07:31 UTC, prgoel-code commented
Can we merge this @Pegonzal

2024-09-26 10:29 UTC, afreen23 commented
@prgoel-code we need to wait for dashboard tests now, they are failing

2024-09-26 10:29 UTC, afreen23 commented
jenkins test dashboard

2024-09-26 11:50 UTC, prgoel-code commented
jenkins test dashboard

2024-09-27 07:32 UTC, prgoel-code commented
@afreen23  All the required test cases are passing. The files which are showing in console output are not related to my changes, Can we merge this

2024-09-30 07:46 UTC, afreen23 approved these changes

2024-09-30 07:46 UTC, merged