mds: use _exit for QA killpoints rather than SIGABRT
ceph/ceph pull request #59019
Opened 2024-08-05 11:53 UTC by neesingh-rh

Fixes: https://tracker.ceph.com/issues/65579
Signed-off-by: Neeraj Pratap Singh <neesingh@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-08-09 19:07 UTC, batrick requested changes
There are many other `mds_kill` configs to be adjusted.

You also need to update the `qa/` suite to no longer look for core dumps and to check the exit code from the MDS.

2024-08-09 19:07 UTC, batrick commented on src/mds/MDCache.cc
> +    _exit(134);
134 is not a valid exit code. I'm using `120`:

https://github.com/ceph/ceph/pull/56997/files#diff-56ee22e891f482afe8d7ea22e9ad4f49d15698e2546c59187fbce6d34474ab96R1270

Let's just be consistent with that.

2024-09-16 20:03 UTC, batrick commented
ping @neesingh-rh status?

2024-09-17 05:55 UTC, neesingh-rh commented
> There are many other `mds_kill` configs to be adjusted.
> 
> You also need to update the `qa/` suite to no longer look for core dumps and to check the exit code from the MDS.

Do the `mds_kill` configs in `Server.cc, Migrator.cc, MDSTable Server.cc, MDSTableClient.cc` need changes too?

2024-10-28 04:12 UTC, vshankar commented
> > There are many other `mds_kill` configs to be adjusted.
> > You also need to update the `qa/` suite to no longer look for core dumps and to check the exit code from the MDS.
> 
> Do the `mds_kill` configs in `Server.cc, Migrator.cc, MDSTable Server.cc, MDSTableClient.cc` need changes too?

I think so, yes.

2024-10-28 04:13 UTC, vshankar commented
@neesingh-rh Could you plan to update this PR sometime this week. I would like to put the change to test.

2024-11-05 06:03 UTC, neesingh-rh commented
> @neesingh-rh Could you plan to update this PR sometime this week. I would like to put the change to test.

@vshankar Can u pls look at the changes in the test case done to check for the exit status, is correct way or not? Accordingly I will do for other tests.

2025-03-18 13:48 UTC, batrick requested changes
Status?

2025-09-28 15:01 UTC, closed without merging