upgrade rules for NVMeofGW monitors and gateways
ceph/ceph pull request #59198
Opened 2024-08-13 14:15 UTC by leonidc

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-08-13 15:11 UTC, athanatos requested changes
I'll take another look once you've fixed the stray style reverts.

2024-08-13 15:11 UTC, athanatos commented on src/mon/NVMeofGwMap.h
> +      uint8_t version = 1;
version isn't used anywhere else in this function, just pass a 1 into ENCODE_START.

2024-08-13 15:11 UTC, athanatos commented on src/mon/NVMeofGwMap.h
> +      ENCODE_START(version, 1, bl);
The indentation on this section is wrong.  Please re-indent this and every other line in this commit to match my cleanup.

2024-08-13 15:11 UTC, athanatos commented on src/mon/NVMeofGwMap.h
> +
This is a stray newline.  Please check every line in this commit for similar accidental additions.

2024-08-13 15:11 UTC, athanatos commented on src/mon/NVMeofGwMon.cc
> +        << " subsystems " << m->get_subsystems() << dendl;
This chunk changes appears to be an accidental revert of my cleanup PR (changes the indent but doesn't change the content).  Please check over this entire PR for other examples and remove them.

2024-08-13 15:11 UTC, athanatos commented on src/mon/NVMeofGwMon.cc
> +      else if (pending_map.created_gws[group_key][gw_id].performed_full_startup
This chunk appears to be re-introducing formatting I fixed.  Please do not do that.

2024-08-13 15:11 UTC, athanatos commented on src/mon/NVMeofGwTypes.h
> +    const NvmeGwMonState & gw_created,  bool encode_gmap_last)
No.  If you need to modify the structures on encode, make a copy and do it in encode.

2024-08-14 06:31 UTC, ronen-fr commented on src/messages/MNVMeofGwMap.h
> +  static int constexpr VERSION = 2;
That's a pretty unusual order of declarations. I surely  would not have *fixed* 'constexpr int' into 'int constexpr'

2024-08-14 06:36 UTC, ronen-fr commented on src/mon/NVMeofGwSerialize.h
> +#define MAX_SUPPORTED_ANA_GROUPS 16 //used for support backward compatibility
maybe rephrase 'for support'

2024-08-14 06:39 UTC, ronen-fr commented on src/mon/NVMeofGwTypes.h
> +#define MAX_SUPPORTED_ANA_GROUPS 16 // ths define is used for backward compatibility
strange location for a '#define'. After an 'else' - but takes effect anyway.

2024-08-14 06:40 UTC, ronen-fr commented on src/test/test_nvmeof_mon_encoding.cc
> +  uint64_t features = 4540701547738038271;
maybe using an hex number to initialize? would save the reader the need to fire up a calculator...

2024-11-26 15:01 UTC, closed without merging