mon: add mon tick completed latency
ceph/ceph pull request #59238
Opened 2024-08-15 13:34 UTC by YiteGu

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-08-16 01:16 UTC, YiteGu commented
jenkins test make check

2024-08-22 09:02 UTC, Matan-B approved these changes

2024-08-22 11:58 UTC, Matan-B commented on src/mon/Monitor.cc
> +  dout(11) << " tick completed, latency: " << lat << dendl;
@YiteGu, My bad here, I have meant either 10 or 20.

2024-08-22 12:17 UTC, Matan-B approved these changes

2024-08-22 18:57 UTC, YiteGu commented
jenkins test api

2024-08-29 20:42 UTC, batrick requested changes

2024-08-29 20:42 UTC, batrick commented on src/mon/Monitor.cc
> +  dout(10) << "tick begin" << dendl;
I'd prefer we use the `ceph::coarse_mono_clock` for this and any new purpose. (No need to update the `now` variable below, just make a new second one.)

2024-11-30 11:01 UTC, closed without merging