reef: mgr/rest: Trim  requests array and limit size
ceph/ceph pull request #59371
Opened 2024-08-21 05:37 UTC by NitzanMordhai

backport tracker: https://tracker.ceph.com/issues/67644

---

backport of https://github.com/ceph/ceph/pull/54984
parent tracker: https://tracker.ceph.com/issues/67642

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2024-11-07 13:23 UTC, rzarzynski requested changes

2024-11-07 13:23 UTC, rzarzynski commented on PendingReleaseNotes
> +* PG dump: The default output of `ceph pg dump --format json` has changed. The
Hmm, haven't these items snaked into the PR?

2024-11-27 22:59 UTC, rzarzynski approved these changes

2024-11-27 23:31 UTC, anthonyeleven approved these changes

2025-01-09 11:09 UTC, NitzanMordhai commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrackercephcomissues69132

2025-01-10 16:05 UTC, merged