mgr/dashboard: service form hosts selection only show up to 10 entries
ceph/ceph pull request #59576
Opened 2024-09-03 09:41 UTC by nmunet

Fixes: https://tracker.ceph.com/issues/67413

Signed-off-by: Naman Munet <nmunet@redhat.com>
![Screenshot from 2024-09-03 14-57-02](https://github.com/user-attachments/assets/e0105ac1-834c-4bb8-8e5c-95a73ae46bbe)
![Screenshot from 2024-09-03 15-02-46](https://github.com/user-attachments/assets/b1408056-41b0-431d-b609-206ade618743)

As we are already getting the total host count from health API, so using that information to set the query limit for host list API call.
I have made changes in files where host list is shown on the form as a multi-select option.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-09-05 03:43 UTC, nmunet commented
jenkins test make check

2024-09-06 07:11 UTC, Pegonzal requested changes
Hey @nmunet thanks for the work with this!

However I think we should look for another approach, for two reasons:

- The `minimal_health` endpoint should stay, as the name implies, minimal. Feeding it more data is to go against it's original purpose
- The original issue comes from the host pagination, which the `minimal_health` endpoint lacks. This pagination is in place to save on load times by retrieving only the needed information, some endpoints might manage a lot of data (some clusters are huge) and the host list is one of them, so we have to be careful when processing this data.

2024-09-09 05:04 UTC, nmunet commented
jenkins test api

2024-09-09 09:49 UTC, nizamial09 approved these changes
lgtm, thank you @nmunet. btw there's 3 different commit serving the same purpose. let's squash them all into one.

2024-09-09 09:49 UTC, nizamial09 commented on src/pybind/mgr/dashboard/controllers/host.py
> +    def all_hosts(self):
and also add a description about this method on why its needed.
```suggestion
    def list(self):
```

2024-09-12 05:43 UTC, nizamial09 approved these changes
Thanks for addressing the comments and taking care of the nvmeof hosts selection as well.

2024-09-12 05:43 UTC, nizamial09 commented
e2e failures are unrelated

2024-09-12 05:45 UTC, Pegonzal approved these changes

2024-09-12 05:47 UTC, merged