gw deleting state
ceph/ceph pull request #59579
Opened 2024-09-03 18:08 UTC by leonidc

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-09-03 18:17 UTC, athanatos commented on src/mon/NVMeofGwMap.cc
> +      else {
} else {

Check every instance.

2024-09-03 18:18 UTC, athanatos commented
@leonidc Can you explain what the bug being fixed actually is in the commit message?  Doesn't need to be a lot of detail, just enough to understand the diff and what the new state is supposed to represent.

2024-09-04 00:03 UTC, athanatos requested changes
Functionality looks probably ok after formatting fixes are addressed.  Ping me once PR is updated and I'll kick off a test run.

2024-09-04 00:03 UTC, athanatos commented on src/mon/NVMeofGwMap.h
> +  void  track_deleting_gws            (const NvmeGroupKey& group_key,
Extra space after void, remove spaces between track_deleting_gws and (

2024-09-04 00:03 UTC, athanatos commented on src/mon/NVMeofGwMap.h
> +  int  get_num_namespaces (const NvmeGwId &gw_id,
Extra space after int, extra space between namespaces and (

2024-09-04 00:05 UTC, athanatos commented
Update commit message with (brief) description of the bug being fixed.

2024-09-04 04:31 UTC, leonidc commented on src/mon/NVMeofGwMap.cc
> +      auto& gw_created  = gw_created_pair.second;
fixing

2024-09-04 20:09 UTC, athanatos approved these changes
One of my comments had not been addressed, but since you've presumably already tested this version we can leave it as it is -- please check over your PRs for typos in the future before asking for review.

2024-09-04 20:09 UTC, athanatos commented on src/mon/NVMeofGwMon.cc
> +      }
This has not been addressed.

2024-09-04 20:09 UTC, athanatos commented on src/mon/NVMeofGwMap.cc
> +         availability = gw_availability_t::GW_UNAVAILABLE;
Braces around if body.

2024-09-04 20:09 UTC, athanatos commented
jenkins test api

2024-09-04 20:12 UTC, athanatos commented
@leonidc You still have not fixed the commit message.

2024-09-06 06:20 UTC, leonidc commented
jenkins api test

2024-09-06 06:52 UTC, leonidc commented
jenkins api test

2024-09-06 09:22 UTC, caroav commented
jenkins test api

2024-09-06 13:22 UTC, merged