monitor: add availability score feature
ceph/ceph pull request #59673
Opened 2024-09-09 14:11 UTC by shraddhaag

Builds on top of: https://github.com/ceph/ceph/pull/54249
Tracker: https://tracker.ceph.com/issues/67777 
Trello: https://trello.com/c/MNmj6CgJ/764-mon-mgr-track-availability-over-time 

## Description 
This PR introduces the command `ceph osd pool availability-status`. It outputs the availability score for each pool. The score is calculated every 5 seconds (this is currently not configurable but will be made so in followup PRs). 

A sample output of the command looks like this: 
```
$ ceph osd pool availability-status
2024-10-07T05:23:14.840+0000 7fd35b178640 -1 WARNING: all dangerous and experimental features are enabled.
2024-10-07T05:23:14.856+0000 7fd35b178640 -1 WARNING: all dangerous and experimental features are enabled.
POOL           UPTIME  DOWNTIME  NUMFAILURES  MTBF  MTTR  SCORE     AVAILABLE
rbd                2m       14s            1    2m   14s  0.908497          1
.mgr              52s        0s            0    0s    0s         1          1
cephfs.a.meta     48s        0s            0    0s    0s         1          1
cephfs.a.data     45s        0s            0    0s    0s         1          1
```

A pool is considered unavailable if any PG in the pool is not in active state or if there are unfound objects. Otherwise the pool is considered available. 

Integration tests to check availability score are added in `qa/standalone/misc`. 

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2025-01-06 09:12 UTC, shraddhaag commented on src/mon/PGMap.cc
> +         << " has " << i->second.stats.sum.num_objects_unfound << " unfound objects" << dendl;
from my research, I found this is the best way to look for unfound objects in each PG. Please let me know if there is a more efficient way to do this.

2025-01-06 09:12 UTC, shraddhaag commented on qa/standalone/misc/availability.sh
> +#!/usr/bin/env bash
Wasn't sure where this test should live so I added the test in the `misc` dir. Please let me know if there is a more appropriate path for it.

2025-02-06 15:06 UTC, NitzanMordhai requested changes
great job ! please fix and we will make another round of review

2025-02-06 15:06 UTC, NitzanMordhai commented on src/mon/MgrStatMonitor.h
> +  mempool::pgmap::map<uint64_t, PoolAvailability> pool_availability;
please explain the use of mempool..

2025-02-06 15:06 UTC, NitzanMordhai commented on src/mon/MgrStatMonitor.h
> +  mempool::pgmap::map<uint64_t, PoolAvailability> pending_pool_availability;
same.

2025-02-06 15:06 UTC, NitzanMordhai commented on src/mon/mon_types.h
> +  void decode(ceph::buffer::list::const_iterator &p) {
please add also "static void generate_test_instances" function so we will test those changes.
also add the new class to the dencoder types

2025-02-06 15:06 UTC, NitzanMordhai commented on src/osd/PeeringState.h
> +  //       Down
?

2025-02-18 18:56 UTC, kamoltat requested changes
Provided some comments, core logic looks good to me. Great work @shraddhaag !

2025-02-18 18:56 UTC, kamoltat commented on qa/standalone/misc/availability.sh
> +}
This looks good for the first iteration of the test. In the next iteration, we could test the persistence of the feature by bringing all Monitors down and see if the scores persisted correctly.

2025-02-18 18:56 UTC, kamoltat commented on src/mon/MgrStatMonitor.cc
> +      }
Since there's a dout statement, on top why don't we move

`
```suggestion
      if (!p.end()) {
	decode(progress_events, p);
      }
      if (!p.end()) {
        decode(pool_availability, p);
      }
      dout(10) << __func__ << " v" << version
	       << " service_map e" << service_map.epoch
	       << " " << progress_events.size() << " progress events"
	       << " " << pool_availability.size() << "pools availability tracked"
	       << dendl;
```
`

2025-02-18 18:56 UTC, kamoltat commented on src/mon/MgrStatMonitor.h
> +  mempool::pgmap::map<uint64_t, PoolAvailability> pool_availability;
Okay I see, I think mempool is unnecessary here, we can opt-in for just a regular "map". I think originally put that down because I saw a similar implementation elsewhere in the monitor code and so I thought if I were to do things "pool-related" it might give me a better optimization.

2025-02-18 18:56 UTC, kamoltat commented on src/mon/MgrStatMonitor.h
> +  mempool::pgmap::map<uint64_t, PoolAvailability> pending_pool_availability;
same as my comment above

2025-02-18 18:56 UTC, kamoltat commented on src/mon/PGMap.cc
> +         << " has " << i->second.stats.sum.num_objects_unfound << " unfound objects" << dendl;
This looks correct to me!

2025-02-18 18:56 UTC, kamoltat commented on src/osd/PeeringState.h
> +  //       Down
Might be another PeeringState we are missing @shraddhaag, let us know if this is what you intended.

2025-02-18 18:57 UTC, kamoltat commented
FYI, @shraddhaag  This PR needs a rebase against PGMap.h

2025-02-25 15:40 UTC, shraddhaag commented on qa/standalone/misc/availability.sh
> +    ceph osd pool availability-status
Wasn't sure which functions you are referring to here, I used the pattern for bringing down OSDs from this test: https://github.com/ceph/ceph/blob/main/qa/standalone/scrub/osd-scrub-repair.sh#L747. Could you please help with what funcs I can use here from ceph-helpers.sh?

2025-02-25 15:41 UTC, shraddhaag commented on qa/standalone/misc/availability.sh
> +    ceph osd pool availability-status
Same as my comment above.

2025-02-25 15:41 UTC, shraddhaag commented on src/mon/MgrStatMonitor.h
> +  mempool::pgmap::map<uint64_t, PoolAvailability> pool_availability;
Removed usage of mempool!

2025-02-25 15:42 UTC, shraddhaag commented on src/mon/MgrStatMonitor.h
> +  mempool::pgmap::map<uint64_t, PoolAvailability> pending_pool_availability;
removed usage of mempool!

2025-02-25 15:42 UTC, shraddhaag commented on src/osd/PeeringState.h
> +  //       Down
I hadn't added that, it was part of the prior art. Have removed it since it doesn't seem related!

2025-02-25 15:47 UTC, shraddhaag commented on src/tools/ceph-dencoder/osd_types.h
> +TYPE(PoolAvailability)
Please let me know if it should be `TYPE_FEATUREFUL` instead. Wasn't sure what is the difference between `TYPE` and `TYPE_FEATUREFUL`, @NitzanMordhai @kamoltat could you folks please help me understand / point me to docs?

2025-02-26 06:53 UTC, NitzanMordhai commented on src/mon/mon_types.h
> +  void decode(ceph::buffer::list::const_iterator &p) {
@shraddhaag please add the type into src/tools/ceph-dencoder/osd_types.h under "#include "mon/mon_types.h"" 
and you can test that using something like:
ceph-dencoder type PoolAvailability select_test 0 dump_json
ceph-dencoder type PoolAvailability select_test 0 encode
ceph-dencoder type PoolAvailability select_test 1 encode
ceph-dencoder type PoolAvailability select_test 1 encode decode dump_json
etc.

2025-02-26 06:56 UTC, shraddhaag commented on src/mon/mon_types.h
> +  void decode(ceph::buffer::list::const_iterator &p) {
@NitzanMordhai I have already added the type but had a question about the same here: https://github.com/ceph/ceph/pull/59673#discussion_r1970053616

2025-03-11 05:55 UTC, NitzanMordhai commented on src/tools/ceph-dencoder/osd_types.h
> +TYPE(PoolAvailability)
@shraddhaag since you are not depending on FEATUREFUL bits, you don't need to set it as a TYPE_FEATUREFUL

2025-03-11 06:08 UTC, NitzanMordhai approved these changes
LGTM! just the nit comment

2025-03-11 06:08 UTC, NitzanMordhai commented on src/mon/MgrStatMonitor.cc
> +      dout(20) << __func__ << "Deleting pool: " << poolid << dendl;
nit: i think we can do it as 1 dout.

2025-03-17 02:03 UTC, kamoltat approved these changes
Just a few nit suggestions, after changing those, should be good for qa!

2025-03-17 02:03 UTC, kamoltat commented on src/mon/MgrStatMonitor.cc
> +    if (pool_availability.find(poolid) == pool_availability.end()){
think we can do this:
before the for loop:
```
auto pool_avail_end = pool_availability.end();
```

```suggestion
    if (pool_availability.find(poolid) == pool_avail_end){
```

this basically will avoid us calling for end iterator everytime.

2025-03-17 02:03 UTC, kamoltat commented on src/mon/MgrStatMonitor.cc
> +      digest.pool_pg_unavailable_map.end()) {
same here

2025-03-17 02:03 UTC, kamoltat commented on src/mon/MgrStatMonitor.cc
> +      dout(20) << __func__ << "Deleting pool: " << poolid << dendl;
*_dout is a good way to do this.

2025-03-17 02:04 UTC, kamoltat commented
@shraddhaag Just needs rebase against main.

2025-03-31 23:58 UTC, athanatos commented on src/mon/PGMap.cc
> +    f->dump_stream("pgs") << p.second;
This should be an array_section, not a single stream.

2025-03-31 23:59 UTC, athanatos commented on src/mon/PGMap.cc
> +    pool_pg_unavailable_map[poolid];
Doesn't seem to be necessary.

2025-04-01 00:01 UTC, athanatos commented on src/mon/OSDMonitor.cc
> +  else if (prefix == "osd force-create-pg") {
} else if (...) {

2025-04-01 00:02 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +		 << "Pool status: Available to Unavailable" << dendl;
<< ": Pool status

2025-04-01 00:02 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +		 << "Pool status: Available to Available" << dendl;
<< ": Pool status

2025-04-01 00:06 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +      pool_availability[poolid].pool_name = mon.osdmon()->osdmap.get_pool_name(poolid);
Are we sure that digest and mon.osdmon()->osdmap are from the same epoch?  Can digest include pools not present in mon.osdmon()->osdmap?  If you aren't sure, guard against mon.osdmon()->osdmap not containing poolid (perhaps by using "<unknown>" as the pool) to ensure that get_pool_name doesn't assert.

2025-04-01 00:07 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +    if (pool_availability[poolid].is_avail){
) {

2025-04-01 00:08 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +		 << "Pool status: Available to Unavailable" << dendl;
This could probably use the pool name and id.

2025-04-01 00:08 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +		 << "Pool status: Available to Available" << dendl;
This could probably use the pool name and id.

2025-04-01 00:09 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +		 << "Pool status: Unavailable to Unavailable" << dendl;
<< ": Pool status

This could probably use the pool name and id.

2025-04-01 00:09 UTC, athanatos commented on src/mon/MgrStatMonitor.cc
> +		 << "Pool status: Unavailable to Available" << dendl;
<< ": Pool status

This could probably use the pool name and id.

2025-04-01 00:10 UTC, athanatos commented on qa/standalone/mon/availability.sh
> +# Copyright (C) 2024 Red Hat <contact@redhat.com>
This should probably be IBM

2025-04-01 00:12 UTC, athanatos commented on src/mon/mon_types.h
> +      num_failures(0), is_avail(true)
Let's initialize these inline where the members are declared where possible.  Avoids missing them when adding a new constructor.

2025-04-01 00:12 UTC, athanatos approved these changes
LGTM otherwise

2025-04-09 15:14 UTC, sseshasa commented
Rados Approved.
See https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues70727

2025-04-09 19:20 UTC, yuriw commented
jenkins test this please

2025-04-16 15:44 UTC, yuriw commented
jenkins test this please

2025-04-17 04:13 UTC, shraddhaag commented
jenkins test this please

2025-04-17 13:47 UTC, shraddhaag commented
jenkins test this please

2025-04-23 10:50 UTC, shraddhaag commented
jenkins test this please

2025-04-23 11:01 UTC, shraddhaag commented
jenkins test make check

2025-04-23 11:12 UTC, shraddhaag commented
jenkins test make check

2025-04-23 11:23 UTC, shraddhaag commented
jenkins test make check

2025-04-23 13:52 UTC, shraddhaag commented
jenkins test make check

2025-04-24 14:34 UTC, shraddhaag commented
jenkins test make check

2025-04-24 14:44 UTC, shraddhaag commented
jenkins test make check

2025-04-25 05:56 UTC, merged