tool/ceph-bluestore-tool: Make bluefs-bdev-expand command output nicer.
ceph/ceph pull request #59954
Opened 2024-09-24 10:12 UTC by ifed01

Here is a sample output:

inferring bluefs devices from bluestore path
0 : device size 0x4049c000(1.0 GiB) : using 0x1801000(24 MiB) 1 : device size 0x140000000(5 GiB) : using 0x1502000(21 MiB) 2 : device size 0x8c0000000(35 GiB) : using 0x40014000(1.0 GiB) Expanding DB/WAL...
0 : nothing to do, skipped
1 : Expanding to 0x140000000(5 GiB)
1 : size updated to 0x140000000(5 GiB)
2 : Expanding to 0x8c0000000(35 GiB)
2 : size updated to 0x8c0000000(35 GiB)

Fixes: https://tracker.ceph.com/issues/67966

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-09-24 11:27 UTC, sajibreadd commented on src/os/bluestore/BlueStore.cc
>      }
Is this correct? If first device is shared device and it get expanded then it won't update the other devices?

2024-09-25 09:22 UTC, ifed01 commented
jenkins test api

2024-09-30 10:50 UTC, ifed01 commented
jenkins test api

2024-10-01 13:05 UTC, aclamk requested changes
Multi bdev label broke expand_devices code.
Lets discuss where to best fix it.

2024-10-01 13:05 UTC, aclamk commented on src/os/bluestore/BlueStore.cc
> +    r = label_supported ? _write_bdev_label(cct, bdev0, path, label) : 0;
There is now a mess that I introduced.
When operating on BDEV_SLOW it should incorporate multi bdev label, like in `BlueStore::write_meta()`
```
_read_multi_bdev_label(...,&bdev_label_valid_locations, ...);
....
int r = _write_bdev_label(..., bdev_label_valid_locations);
```

2024-10-01 13:05 UTC, aclamk commented on src/os/bluestore/BlueStore.cc
> +    r = label_supported ? _write_bdev_label(cct, bdev0, path, label) : 0;
More over, if new locations became available for label clones we should modify `bdev_label_valid_locations`.

2024-10-01 13:05 UTC, aclamk commented on src/os/bluestore/BlueStore.cc
> +    r = label_supported ? _write_bdev_label(cct, bdev0, path, label) : 0;
In fact, maybe above should be addressed by me in a some tracker.

2024-10-22 13:13 UTC, aclamk commented
#60363 Solves the problem of bdev label clones.

2025-01-17 09:17 UTC, aclamk commented
PR that this depended on just merged:
https://github.com/ceph/ceph/pull/60363

2025-01-23 13:37 UTC, aclamk commented on src/os/bluestore/BlueStore.cc
> +    // We can still get here in non-erroneous scenarios,
This will collide with https://github.com/ceph/ceph/pull/61470/files#diff-6f3b1a5dcf5313dc06f71ba4997ee28ec219ecb5633a728b916465c684f1d87dR6687-R6688 .
But this was first, so I will resolve conflict after this merges.

2025-02-18 17:29 UTC, ifed01 commented
Closing in favor of https://github.com/ceph/ceph/pull/61843

2025-02-19 15:53 UTC, closed without merging