mgr/dashboard: fix cephadm dashboard e2e and a combobox fix
ceph/ceph pull request #60014
Opened 2024-09-27 05:32 UTC by nizamial09

1. previously we were able to add custom items to our select-badges like
custom labels for hosts. but it got dropped unintentionally due to the
carbon. fixing it here

2. the wizard component changes caused issue to the e2e, so fixing it.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-09-27 05:33 UTC, nizamial09 commented
the nfs service creation is currently failing so the nfs export creation issue here is an expected failure for now. its being fixed through: https://github.com/ceph/ceph-container/pull/2244

2024-10-01 07:52 UTC, afreen23 reviewed
Did we check this https://angular.carbondesignsystem.com/?path=/docs/components-combobox--docs#dynamically-added-list-items ?

2024-10-07 07:43 UTC, nizamial09 commented
> Did we check this https://angular.carbondesignsystem.com/?path=/docs/components-combobox--docs#dynamically-added-list-items ?

yup, not helpful though since what we are looking for is to add the keyword that is already typed in the box itself..

2024-10-24 07:15 UTC, nizamial09 commented
jenkins retest this please

2024-11-04 06:29 UTC, afreen23 approved these changes

2024-11-04 06:30 UTC, afreen23 commented
jenkisn test make check

2024-11-07 15:09 UTC, nizamial09 commented
cephadm e2e is still failing, will look into it.

2025-01-10 08:27 UTC, nizamial09 commented
From [the test run](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/13723/), it looks like only one of the test is failing now which is the nfs service creation. That is a known issue in upstream main last time I checked and I think the NFS container itself needs an upgrade to 6.1 inorder to fix it which is being looked into by the build and NFS team.

[Test Result](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/13723/testReport/) (1 failure / ±0)
[should create an NFS cluster.nfsExport page Create, edit and delete should create an NFS cluster](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/13723/testReport/junit/(root)/should%20create%20an%20NFS%20cluster/nfsExport_page_Create__edit_and_delete_should_create_an_NFS_cluster/)
	
Identified problems
Dashboard End-to-End Test Failure (Cypress)

1 of 11 failed (9%)

2025-01-10 08:27 UTC, nizamial09 commented
I'll go ahead and fix the unit tests and update the PR

2025-01-10 08:37 UTC, nizamial09 commented
Should follow after https://github.com/ceph/ceph/pull/60799/

2025-02-17 07:26 UTC, nizamial09 commented
jenkins test make check

2025-02-17 07:26 UTC, nizamial09 commented
jenkins test api

2025-02-17 07:28 UTC, nizamial09 commented
dashboard e2e failure is the usual flaky test. should we disable those since we couldn't manage to make it stable for the past few years and it really depends on the status of the clusters? 
[Test Result](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/17625/testReport/) (6 failures / +2)
["before all" hook for "should open notification sidebar".Notification page "before all" hook for "should open notification sidebar"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/17625/testReport/junit/(root)/%22before%20all%22%20hook%20for%20%22should%20open%20notification%20sidebar%22/Notification_page__before_all__hook_for__should_open_notification_sidebar_/)
["after all" hook for "should open notification sidebar".Notification page "after all" hook for "should open notification sidebar"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/17625/testReport/junit/(root)/%22after%20all%22%20hook%20for%20%22should%20open%20notification%20sidebar%22/Notification_page__after_all__hook_for__should_open_notification_sidebar_/)
[Show all failed tests >>>](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/17625/#showFailuresLink)


cephadm dashboard e2e is failing on nfs service creation which looks like a known issue locally
[Test Result](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/14419/testReport/) (5 failures / -24)
[should create an NFS cluster.nfsExport page Create, edit and delete should create an NFS cluster](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/14419/testReport/junit/(root)/should%20create%20an%20NFS%20cluster/nfsExport_page_Create__edit_and_delete_should_create_an_NFS_cluster/)
[should create a nfs-export with RGW backend.nfsExport page Create, edit and delete should create a nfs-export with RGW backend](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/14419/testReport/junit/(root)/should%20create%20a%20nfs-export%20with%20RGW%20backend/nfsExport_page_Create__edit_and_delete_should_create_a_nfs_export_with_RGW_backend/)
[should show Clients.nfsExport page Create, edit and delete should show Clients](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/14419/testReport/junit/(root)/should%20show%20Clients/nfsExport_page_Create__edit_and_delete_should_show_Clients/)
[should edit an export.nfsExport page Create, edit and delete should edit an export](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/14419/testReport/junit/(root)/should%20edit%20an%20export/nfsExport_page_Create__edit_and_delete_should_edit_an_export/)
[should delete exports and bucket.nfsExport page Create, edit and delete should delete exports and bucket](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/14419/testReport/junit/(root)/should%20delete%20exports%20and%20bucket/nfsExport_page_Create__edit_and_delete_should_delete_exports_and_bucket/)

overall nothing that prevents this PR from merging

2025-02-17 07:28 UTC, nizamial09 commented
jenkins test make check arm64

2025-02-19 09:45 UTC, nizamial09 commented
jenkins test api

2025-02-19 09:45 UTC, nizamial09 commented
jenkins test dashboard

2025-02-19 09:45 UTC, nizamial09 commented
jenkins test dashboard cephadm

2025-02-24 14:44 UTC, afreen23 requested changes

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/cypress/e2e/page-helper.po.ts
> +        const fn: Function = descriptor?.value;
```suggestion
        const fn: Function = descriptor.value;
```
Already using `if`

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/cypress/e2e/page-helper.po.ts
> +        descriptor.value = function (...args: any) {
types

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-modal/form-modal.component.html
> +                         (updatedItems)="field.typeConfig.options = $event"
are we just assigning here ?, want to confirm just.

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +          (selectedItem) => selectedItem.content === item.content
add types

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +      const exists = this.items.some((item) => item.content === searchString);
add type for `item`

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.ts
> +  emit(value: any) {
types

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.spec.ts
> +  });
We should have some tests here

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +    this.searchSubject.pipe(debounceTime(300), distinctUntilChanged()).subscribe((searchString) => {
use the debounce time constant here as well for the combo box service

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +  onInput(event: any) {
types

2025-02-24 14:44 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.ts
> +        distinctUntilChanged((prev, curr) => JSON.stringify(prev) === JSON.stringify(curr))
```suggestion
        distinctUntilChanged()
```
What are the types ? cant this be just this ?
I am concerned over using stringify as for nested objects it will get inefficient.
Can you add types at all places to understand better, thanks.

2025-02-25 05:08 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/cypress/e2e/page-helper.po.ts
> +        descriptor.value = function (...args: any) {
i actually don't know the type here.

the actual interface where this is being passed is defined with `any` type
```
/**
     * Calls the function, substituting the specified object for the this value of the function, and the specified array for the arguments of the function.
     * @param thisArg The object to be used as the this object.
     * @param argArray A set of arguments to be passed to the function.
     */
    apply(this: Function, thisArg: any, argArray?: any): any;
```
and `arg` is passed to `thisArg`. I could say something like `string[]` but not sure if that could cause any regressive behavior.

2025-02-25 05:08 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/components/form-modal/form-modal.component.html
> +                         (updatedItems)="field.typeConfig.options = $event"
yup

2025-02-25 06:05 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +          (selectedItem) => selectedItem.content === item.content
done, thanks

2025-02-25 06:06 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +      const exists = this.items.some((item) => item.content === searchString);
done

2025-02-25 06:06 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.ts
> +  emit(value: any) {
done

2025-02-25 06:06 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.ts
> +  subscribe<T>(handler: (value: T) => void, debounceMs = 300) {
removed it btw and a debounce const is there in the directive now

2025-02-25 06:06 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.spec.ts
> +  });
tests are added to the directive itself.

2025-02-25 06:07 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +    this.searchSubject.pipe(debounceTime(300), distinctUntilChanged()).subscribe((searchString) => {
done

2025-02-25 06:08 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.ts
> +        distinctUntilChanged((prev, curr) => JSON.stringify(prev) === JSON.stringify(curr))
good catch. this was something i wrote for my local testing which I eventually abandoned but forgot to remove. removed it now.

2025-02-25 06:08 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/services/combo-box.service.ts
> +    this.searchSubject
this whole block was abandoned and i wasn't even subscribing this in the directive. Meant for local testing only but forgot to remove it later. Removed this now. thanks for pointing out.

2025-02-25 06:09 UTC, nizamial09 commented
thanks for the reviews @afreen23, updated the PR.

2025-03-05 06:52 UTC, nizamial09 commented
jenkins test make check

2025-03-05 06:52 UTC, nizamial09 commented
jenkins test dashboard

2025-03-05 06:52 UTC, nizamial09 commented
jenkins test dashboard cephadm

2025-03-10 06:51 UTC, nizamial09 commented
the 2 [cephadm dashboard e2e failure](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/15027/consoleFull) is something i couldn't replicate locally? maybe a flake one? I'll check this separately
```
 2 failing

  1) Services page
       should create and delete snmp-gateway service with version V3:
     AssertionError: Timed out retrying after 120000ms: Expected to find element: `cd-service-details`, but never found it.
      at ServicesPageHelper.clickServiceTab (cypress/e2e/cluster/services.po.ts:34:7)
      at Context.eval (cypress/e2e/orchestrator/workflow/09-services.e2e-spec.ts:101:13)

  2) Services page
       should create and delete snmp-gateway service with version V3 and w/o privacy protocol:
     AssertionError: Timed out retrying after 120000ms: Expected to find element: `cd-service-details`, but never found it.
      at ServicesPageHelper.clickServiceTab (cypress/e2e/cluster/services.po.ts:34:7)
      at Context.eval (cypress/e2e/orchestrator/workflow/09-services.e2e-spec.ts:115:13)
```

the 2 [dashboard e2e failure](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/18083/consoleFull), 1 is multi-cluster related which is something that's been recurring since the carbon move. I remember @aaSharma14 looking at it before. The other one is a new one which might be fixed by https://github.com/ceph/ceph/pull/62194

2025-03-10 06:51 UTC, nizamial09 commented
jenkins test make check

2025-03-11 09:22 UTC, afreen23 commented
We should seperate test fixes from combobox issue in a different PR.
Right now its difficult to review and trace.

Thanks

2025-03-13 03:12 UTC, afreen23 commented
Two things for the combobox:

1. We should allow enter keystroke here, so that as I type out and see my selected item, I dont need to move cursor.
Right now, on clicking enter its taking to "hostname" field

https://github.com/user-attachments/assets/f03a3f16-d36f-47bd-af43-dbe5d785b9a0


2. We can  clear the search field, if the searched item is selected. Why bother user to clear that ? :)

https://github.com/user-attachments/assets/2de5f475-8fcb-4605-8604-7c6dc5a4101e

2025-03-13 03:35 UTC, afreen23 requested changes

2025-03-13 03:35 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +export class DynamicInputComboboxDirective implements OnInit, OnDestroy{
We must add comment over this directive explaning what it offers

2025-03-13 03:35 UTC, afreen23 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +  @Output() updatedItems: EventEmitter<ComboBoxItem[]> = new EventEmitter();
also a comment for these

2025-03-13 03:40 UTC, afreen23 approved these changes

2025-03-13 04:57 UTC, nizamial09 commented
> 1. We should allow enter keystroke here, so that as I type out and see my selected item, I dont need to move cursor.
>    Right now, on clicking enter its taking to "hostname" field

I think its a bug maybe not necessarily associated with the combo box :thinking: The reason it took you to hostname is because the form is trying to submit itself when you pressed enter and since hostname is a required field and is empty, it fails the validation and takes you to the field that might have failed validation or simply to the first item in the form..It looks like pressing enter to submit the form is the default behavior and since carbon's combo box is not overriding that behavior it goes on to do the same.

We can look into overriding that ourselves but it requires different sort of change, something that needs to be persisted across the default combo-box component. But what I am doing with the `cdDynamicInputCombobox` is a different thing which is only available when you use that directive. But technically (and as per the current implementation), you can have a combobox without `cdDynamicInputCombobox` directive. I've opened a bug to fix it separately. I am assuming the scope might be bigger since it can affect the native form behavior




> 2\. We can  clear the search field, if the searched item is selected. Why bother user to clear that ? :)

I'd like that too but that should happen in carbon. Because the way I see it now, [it works as said in here](https://angular.carbondesignsystem.com/?path=/story/components-combobox--multiselect). Maybe an enhancement for the carbon team?

2025-03-13 04:58 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +export class DynamicInputComboboxDirective implements OnInit, OnDestroy{
done.

2025-03-13 04:58 UTC, nizamial09 commented on src/pybind/mgr/dashboard/frontend/src/app/shared/directives/dynamic-input-combobox.directive.ts
> +  @Output() updatedItems: EventEmitter<ComboBoxItem[]> = new EventEmitter();
done too

2025-03-13 10:18 UTC, afreen23 commented
> > 1. We should allow enter keystroke here, so that as I type out and see my selected item, I dont need to move cursor.
> >    Right now, on clicking enter its taking to "hostname" field
> 
> I think its a bug maybe not necessarily associated with the combo box 🤔 The reason it took you to hostname is because the form is trying to submit itself when you pressed enter and since hostname is a required field and is empty, it fails the validation and takes you to the field that might have failed validation or simply to the first item in the form..It looks like pressing enter to submit the form is the default behavior and since carbon's combo box is not overriding that behavior it goes on to do the same.
> 
> We can look into overriding that ourselves but it requires different sort of change, something that needs to be persisted across the default combo-box component. But what I am doing with the `cdDynamicInputCombobox` is a different thing which is only available when you use that directive. But technically (and as per the current implementation), you can have a combobox without `cdDynamicInputCombobox` directive. I've [opened a bug to fix ](https://tracker.ceph.com/issues/70434)it separately. I am assuming the scope might be bigger since it can affect the native form behavior
> 
> > 2. We can  clear the search field, if the searched item is selected. Why bother user to clear that ? :)
> 
> I'd like that too but that should happen in carbon. Because the way I see it now, [it works as said in here](https://angular.carbondesignsystem.com/?path=/story/components-combobox--multiselect). Maybe an enhancement for the carbon team?

Yes I noticed the behavior in carbon itself. Thanks for the tracker, we can circle back on them later.
Thanks!

2025-03-13 10:21 UTC, merged

2025-03-13 10:24 UTC, afreen23 commented
Thanks @nizamial09 for great fixes here 🎉