dencoding: check struct_v against DECODE_START(v, ...) at compile-time
ceph/ceph pull request #60159
Opened 2024-10-07 12:05 UTC by rzarzynski

Typical problem found in recent reviews of dencoding changes is missed increment of the version number passed to `DECODE_START()` macro in a decoder.
It's easy to overlook and hard to find as the number is used for rarely happening explicit breaks of schema compatibility.

This commit brings compile-time checks for `struct_v` in decoders (and for `denc` also in encoders) to find a situation when it's compared against version higher than declared using the `DECODE_START(v, ...)` macro.

Additionally, the patch fixes the currently existing issues of this genre buried across the entire code base.

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

--------------
The goldbot snippet is available [here](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:22,endLineNumber:10,positionColumn:22,positionLineNumber:10,selectionStartColumn:8,selectionStartLineNumber:10,startColumn:8,startLineNumber:10),source:'%23include+%3Ciostream%3E%0A%23include+%3Cstdexcept%3E%0A%23include+%3Ctype_traits%3E%0A%23include+%3Cstdint.h%3E%0A%0A%23define+consteval_assert(cond,+msg)+%5C%0A++if+(!!(cond))+%7B+throw+(msg)%3B+%7D%0A%0Atemplate+%3Cunsigned+MaxV%3E%0Astruct+VersionChecker%0A%7B%0A++struct+CheckingWrapper+%7B%0A++++consteval+CheckingWrapper(unsigned+c)+:+c(c)+%7B%0A++++++consteval_assert(%0A++++++++c+%3C%3D+MaxV,+%22checking+against+higher+version+than+declared+in+DECODE_START%22)%3B%0A++++%7D%0A++++unsigned+c%3B%0A++%7D%3B%0A++//+we+want+the+implicit+conversion+to+take+place+but+with+lower%0A++//+rank+than+the+CheckingWrapper-conversion+during+struct_v+cmps.%0A++template%3Cclass+T%3Dvoid%3E+operator+char()+%7B%0A++++return+v%3B%0A++%7D%0A%0A++//+need+the+wrapper+as+the+operator+cannot+be+consteval%3B+otherwise%0A++//+it+couldn!'t+have+accessed+the+non-constexpr+%60v%60.%0A++auto+operator%3C%3D%3E(CheckingWrapper+c)+const+%7B%0A++++return+v+%3C%3D%3E+c.c%3B%0A++%7D%0A++auto+operator%3D%3D(CheckingWrapper+c)+const+%7B%0A++++return+v+%3D%3D+c.c%3B%0A++%7D%0A++unsigned+v%3B%0A%7D%3B%0A%0A%23define+macro(v)+%5C%0A++VersionChecker%3Cv%3E+struct_v%7Bv%7D%0Aint+main(int+argc,+char**+argv)+%7B%0A++VersionChecker%3C42%3E+vc%3B%0A++std::cout+%3C%3C+(vc+%3C+41)+%3C%3C+std::endl%3B%0A++VersionChecker%3C41%3E+v%7B3%7D%3B%0A++if+(vc+%3C+43)+%7B%7D%0A++char+xxx%3B%0A++xxx+%3D+vc%3B%0A++char+yyy%7Bvc%7D%3B%0A++return+0%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang1910,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B20',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+19.1.0+(Editor+%231)',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+19.1.0+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-10-07 12:09 UTC, rzarzynski commented
Do we have a framework for ensuring compilation failures? This isn't something GTest is able to do.

CC: @gregsfortytwo.

2024-10-08 11:14 UTC, NitzanMordhai reviewed
@rzarzynski please see my comment

2024-10-08 11:14 UTC, NitzanMordhai commented on src/osd/ECMsgTypes.cc
> +  if (struct_v > 2 && struct_v.v > struct_compat) {
please explain why you're adding the compare against struct_compat and v ? there are few other compares against compact that are still compared to struct_v and not struct_v.v

2024-10-08 16:23 UTC, cbodley commented
> Do we have a framework for ensuring compilation failures? This isn't something GTest is able to do.

@rzarzynski copying a suggestion from the [cpplang slack](https://cppalliance.org/slack/):

> The way you do compile tests testable with `ctest` is by using an object library via `add_library(whatever OBJECT ...)` that is [EXCLUDE_FROM_ALL](https://cmake.org/cmake/help/latest/prop_tgt/EXCLUDE_FROM_ALL.html) then explicitly calling the build system on the target with `add_test(NAME whatever COMMAND "${CMAKE_COMMAND}" --build "${CMAKE_BINARY_DIR}" --config "\$<CONFIG>" --target whatever)`. Define [cmake-properties(7)](https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#properties-on-tests) as necessary on the test if you want to test for failure or something specific.

2024-10-08 17:07 UTC, rzarzynski commented
Thanks, @cbodley!

2025-02-10 22:09 UTC, rzarzynski commented
Unstale, please.

2025-02-13 19:31 UTC, rzarzynski commented
jenkins test make check

2025-02-17 04:33 UTC, rzarzynski commented on src/osd/ECMsgTypes.cc
> +  if (struct_v > 2 && struct_v.v > struct_compat) {
The problem is comparing `struct_compat` against the `struct_v` which is not a regular integer but an instance of the `CheckingWrapper`. This wrapper is able to compare only against `consteval` expression but `struct_compat` is not like that. This leads to the following FTBFS:

```
ECMsgTypes.cc:223:34: error: the value of ‘struct_compat’ is not usable in a constant expression
```

2025-02-17 04:34 UTC, rzarzynski commented
@NitzanMordhai, @cbodley: implemented the unit testing. Would you mind re-review?

2025-02-18 09:50 UTC, NitzanMordhai approved these changes
LGTM

2025-02-18 12:54 UTC, ronen-fr commented
Nice!

2025-02-18 14:04 UTC, aclamk requested changes
The code is mergeable. Some optional improvements could be taken.

2025-02-18 14:04 UTC, aclamk commented on src/include/denc.h
> +#define DENC_START(_v, compat, p)					\
Do we even want DENC_START to modify this way?
It seems that providing both `v` and `compat` protected against misuse.

2025-02-19 08:51 UTC, rzarzynski commented on src/include/denc.h
> +template <__u8 MaxV>
Fixed.

2025-02-19 08:51 UTC, rzarzynski commented on src/include/encoding.h
>   * @param v current version of the encoding that the code supports/encodes
Left intact.

2025-02-19 08:52 UTC, rzarzynski commented on src/include/denc.h
> +struct VersionChecker
Fixed.

2025-02-19 08:52 UTC, rzarzynski commented on src/include/encoding.h
> +#define DECODE_START_UNSAFE(v, bl)					\
Renamed.

2025-02-19 08:53 UTC, rzarzynski commented
Addressed @aclamk's comments. Ready for another round of review.

2025-02-20 14:33 UTC, aclamk approved these changes

2025-02-24 20:23 UTC, idryomov approved these changes
Ack from the RBD perspective

2025-02-24 20:27 UTC, idryomov commented
Too bad this doesn't catch cases where `struct_v` is passed to a helper or similar gymnastics -- it caught `EventEntry::decode()`, but not `ClientData::decode()` in the same file.  Something that would have grouped `encode()` and `decode()` in such a way that `struct_v` is provided only once would have done it, but would have probably been a _much_ more invasive change.

Also, I'd fold "osd/osd_types: fix wrong DECODE_START version for pg_notify_t" commit into the commit which has all the other fixups.  The fact that this one is recent (November 2024) and was caught after a rebase doesn't make it special.

2025-02-24 21:04 UTC, gregsfortytwo approved these changes
CephFS changes look good and I like the compile-time checking. More explanation of how that works would be nice (this whole part of the code is really under-documented, I know) — I got confused a few times.

2025-02-24 21:08 UTC, gregsfortytwo commented
@rzarzynski do we need to backport the DECODE_START version changes? If we bump the compat_v in a future version to a version between correct struct_v and the bad DECODE_START(v) value, we could unexpectedly break things...but I don't think we've ever set compat_v to a value other than a newly-bumped struct_v, or that we have structures where it would make sense to do so.

2025-02-24 21:13 UTC, rzarzynski commented
> (...) in such a way that struct_v is provided by the developer only once would have done it, but would have probably been a much more invasive change.

I think such a thing already exists -- it's our _denc_ framework, where a developer typically writes just a single `DENC_START(v, ...)`. Indeed, switching would be far more invasive.

2025-02-24 21:17 UTC, rzarzynski commented
> Too bad this doesn't catch cases where struct_v is passed to a helper or similar gymnastics -- it caught EventEntry::decode(), but not ClientData::decode() in the same file.

Hmm, perhaps knocking out the conversion operator could help in this aspect but at the price of increasing the code churn.

2025-02-24 21:21 UTC, rzarzynski commented
> @rzarzynski do we need to backport the DECODE_START version changes? If we bump the compat_v in a future version to a version between correct struct_v and the bad DECODE_START(v) value, we could unexpectedly break things...but I don't think we've ever set compat_v to a value other than a newly-bumped struct_v, or that we have structures where it would make sense to do so.

Do you mean the fixes? My perception was that having them only since a major release makes thinking easier. Also, we tend to avoid schema changes between minors.

2025-02-25 00:54 UTC, rzarzynski commented
Just squashed the recent fix for `pg_notify_t` with other fixes. No other changes.

2025-02-25 01:45 UTC, gregsfortytwo commented
> > @rzarzynski do we need to backport the DECODE_START version changes? If we bump the compat_v in a future version to a version between correct struct_v and the bad DECODE_START(v) value, we could unexpectedly break things...but I don't think we've ever set compat_v to a value other than a newly-bumped struct_v, or that we have structures where it would make sense to do so.
> 
> Do you mean the fixes? My perception was that having them only since a major release makes thinking easier. Also, we tend to avoid schema changes between minors.
> 
> 

Just the random decoders that had the wrong value which you identified and fixed here.
I started out thinking we should put them everywhere but I think I've talked myself into it not mattering; just want to make sure somebody else considers the impact on upgrades. :)

2025-02-25 01:45 UTC, gregsfortytwo commented
> > @rzarzynski do we need to backport the DECODE_START version changes? If we bump the compat_v in a future version to a version between correct struct_v and the bad DECODE_START(v) value, we could unexpectedly break things...but I don't think we've ever set compat_v to a value other than a newly-bumped struct_v, or that we have structures where it would make sense to do so.
> 
> Do you mean the fixes? My perception was that having them only since a major release makes thinking easier. Also, we tend to avoid schema changes between minors.
> 
> 

Just the random decoders that had the wrong value which you identified and fixed here.
I started out thinking we should put them everywhere but I think I've talked myself into it not mattering; just want to make sure somebody else considers the impact on upgrades. :)

2025-03-05 23:48 UTC, chardan approved these changes
I don't know this code well, so I don't have a lot to add-- mostly looks fine to me. Please see note about using identifiers that start with underscores.  I have to wonder, also, if the whole enchilada could be done with templates, for the most part, but that is well out of the change scope.

2025-03-05 23:48 UTC, chardan commented on src/include/ceph_assert.h
> +#define consteval_assert(expr, msg)	\
Is the idea here to stop compilation by throwing from a consteval context? Why not use static_assert? (I haven't seen this code before, I see lots happens in macros, there maybe very good reasons for it.)

2025-03-05 23:48 UTC, chardan commented on src/include/denc.h
> +      consteval_assert(
See previous question about static_assert(); it may not have been available when some of this was written. OTOH, it may have been and might be the wrong thing to use!

2025-03-05 23:48 UTC, chardan commented on src/include/denc.h
> +    __u8 c;
This goes for elsewhere here (_v) also. I'm sure this works fine, but be aware that identifiers beginning with two underscores are reserved for the implementation by the standard; see lex.name (3.1). I personally would avoid using any member starting with '_' at all, as those are also reserved by the standard in the global namespace (lex.name 3.2).

2025-03-05 23:48 UTC, chardan commented on src/include/denc.h
> +  auto operator<=>(CheckingWrapper c) {
These members could probably also be const, if you're feeling like you want even MORE const-ness.

2025-03-06 01:09 UTC, rzarzynski commented on src/include/ceph_assert.h
> +#define consteval_assert(expr, msg)	\
https://stackoverflow.com/a/57226813

2025-03-14 20:00 UTC, ljflores commented
Hey all, apologies for the delay in testing- the QA tracker was mislabeled. Reviews are ongoing now here: https://tracker.ceph.com/issues/70205

2025-03-16 15:13 UTC, yuriw commented
This broke the build https://tracker.ceph.com/issues/70205#note-12
@rzarzynski

2025-03-17 16:36 UTC, rzarzynski commented
@yuriw: the checker has found a legit bug:

```
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/20.0.0-515-g8ff3a1a4/rpm/el9/BUILD/ceph-20.0.0-515-g8ff3a1a4/src/messages/MClientReply.h:232:23:   in ‘constexpr’ expansion of ‘StructVChecker<7>::CheckingWrapper(8)’
```

introduced 2 weeks ago (https://github.com/ceph/ceph/pull/60746).
I will rebase.

2025-03-18 13:06 UTC, rzarzynski commented
In RGW as well:
```
/home/rzarzynski/ceph2/src/rgw/rgw_zone_types.h:590:28:   in ‘constexpr’ expansion of ‘StructVChecker<2>::CheckingWrapper(3)’
```
We really need the compile-time checking.

@yuriw: this PR is particularly susceptible to catching undetected merge conflicts with other PRs. Let's get it in sooner than later.
I think it's ready for a retest.

2025-03-25 22:01 UTC, ljflores commented
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues70205

2025-03-25 22:04 UTC, merged