Misc optimizations
ceph/ceph pull request #60175
Opened 2024-10-07 21:17 UTC by MaxKellermann

Various micro-optimizations.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [X] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [X] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [X] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

2024-10-08 13:28 UTC, batrick requested changes
I have no objections to these changes except that please split these into multiple PRs by component. It's much easier to QA/review that way.

2024-10-08 13:31 UTC, MaxKellermann commented
Will do. One PR per top-level directory?

Can you see why that one unit test fails? I tried building the unit tests, but I get strange build failures - I will eventually fix them, but since I've seen lots of bogus CI failures, I thought maybe this one may be bogus as well...

2024-10-08 13:38 UTC, ronen-fr commented
A minor note: the erase() fixes seem to be more than optimizations. Might be worth mentioning in the title and labels as fixes (unless I'm missing something)

2024-10-08 13:44 UTC, MaxKellermann commented
> A minor note: the erase() fixes seem to be more than optimizations. Might be worth mentioning in the title and labels as fixes (unless I'm missing something)

The old code was not wrong; previously, the iterators were incremented manually before calling `erase()`. That is guaranteed to work, but it's just not good style. This doesn't fix an actual bug, and the program behavior doesn't change. The code just gets simpler and better (for some subjective meaning of "better").

2024-10-09 12:42 UTC, MaxKellermann commented
I created 4 new PRs with almost all of the patches here. When these are merged, I'll rebase this PR and then we see what still remains here.

2024-10-22 05:29 UTC, MaxKellermann commented
Rebased and dropped the patches that are already in the other two remaining open PRs.

2024-11-14 12:51 UTC, MaxKellermann commented
@batrick is this trimmed-down PR acceptable or do you want me to split it further?

2024-12-07 05:55 UTC, MaxKellermann commented
@batrick?

2025-01-04 14:07 UTC, MaxKellermann commented
@batrick?

2025-01-06 13:32 UTC, batrick approved these changes

2025-01-06 13:32 UTC, batrick commented
retest this please

2025-02-02 13:44 UTC, ronen-fr commented
QA run approved (see https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues69648)

2025-02-03 15:57 UTC, yuriw commented
jenkins test docs

2025-02-03 15:58 UTC, yuriw commented
@MaxKellermann it's ready for merge when all checks passed
ref: https://tracker.ceph.com/issues/69648

2025-02-12 16:12 UTC, MaxKellermann commented
All CI tests have succeeded, only "ceph-pr-docs" which has a bogus failure. Thanks @yuriw and @ljflores.
I think that means it can finally be merged - and I'll try my new merge privileges that were granted to me this week for the first time.

2025-02-12 16:12 UTC, merged