quincy: OSD: PG stat is not synchronized between osds after deep-scrub
ceph/ceph pull request #60191
Opened 2024-10-08 11:13 UTC by sajibreadd

backport tracker: https://tracker.ceph.com/issues/68439

--------
backport of 57582
parent tracker: https://tracker.ceph.com/issues/66059

2024-10-08 14:57 UTC, ljflores submitted a review, later dismissed

2024-10-10 07:47 UTC, sajibreadd commented
jenkins test make check

2024-10-12 09:23 UTC, ronen-fr commented
There seems to be a regression associated with the backported PR,
which should be fully understood before backporting.

2024-10-12 09:23 UTC, ronen-fr requested changes
There seems to be a regression associated with the backported PR,
which should be fully understood before backporting.

2024-10-12 10:57 UTC, sajibreadd commented
> There seems to be a regression associated with the backported PR, which should be fully understood before backporting.

That regression is resolved in the parent PR.

2024-10-12 12:56 UTC, ronen-fr commented
Note that I refer to the latest version of the PR - that one that was
merged.

On Sat, 12 Oct 2024 at 13:57, Md Mahamudur Rahaman Sajib <
***@***.***> wrote:

> There seems to be a regression associated with the backported PR, which
> should be fully understood before backporting.
>
> That regression is resolved in the parent PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ceph/ceph/pull/60191#issuecomment-2408521442>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL4OSGFAZUWNYTJRAS32ZRLZ3D6CNAVCNFSM6AAAAABPR6RHEKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBYGUZDCNBUGI>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-10-31 15:07 UTC, closed without merging

2024-10-31 15:07 UTC, ronen-fr commented
Closing, as the backported PR was reverted.