reef: OSD: PG stat is not synchronized between osds after deep-scrub
ceph/ceph pull request #60192
Opened 2024-10-08 11:20 UTC by sajibreadd

backport tracker: https://tracker.ceph.com/issues/68440

--------
backport of 57582
parent tracker: https://tracker.ceph.com/issues/66059

2024-10-08 13:59 UTC, ronen-fr commented
@sajibreadd : I think you meant to flag me as a reviewer, not an assignee..

2024-10-08 14:08 UTC, ronen-fr submitted a review, later dismissed

2024-10-08 14:15 UTC, sajibreadd commented
> @sajibreadd : I think you meant to flag me as a reviewer, not an assignee..

Yeah, sorry.

2024-10-10 11:22 UTC, sajibreadd commented
jenkins test make check

2024-10-12 09:22 UTC, ronen-fr commented
There seems to be a regression associated with the backported PR.
Should be fully resolved before we can backport

2024-10-12 09:23 UTC, ronen-fr requested changes
There seems to be a regression associated with the backported PR,
which should be fully understood before backporting.

2024-10-31 15:06 UTC, ronen-fr commented
Closing, as the backported PR was reverted.

2024-10-31 15:06 UTC, closed without merging