msg/async/ProtocolV[12]: merge multiple `sendmsg()` system calls
ceph/ceph pull request #60307
Opened 2024-10-14 20:25 UTC by MaxKellermann

After https://github.com/ceph/ceph/pull/60224 optimized the receive code path by reducing the number of `recvmsg()` system calls, this PR does something similar with `sendmsg()`: multiple outgoing packets are merged into one single `sendmsg()` system call. This gives another big speedup by removing unnecessary overhead.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [X] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [X] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [X] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

2024-12-07 05:54 UTC, MaxKellermann commented
@batrick, @markhpc it's been nearly two months with no reply.

2024-12-19 14:35 UTC, markhpc commented
@MaxKellermann Heya!  I apologize, I've been traveling for several conference over the past month and haven't been able to review any PRs since mid-november.  To be blunt:  I don't think anyone on the team is actively working on the msgr code right now and that's likely why some of your PRs are stagnating.  @rzarzynski leads the core team, so perhaps he knows if anyone is looking at it more closely right now and could help with reviews.

2024-12-19 17:54 UTC, MaxKellermann commented
> I don't think anyone on the team is actively working on the msgr code

I would be, but I stopped working on Ceph because I'm waiting for PRs to be merged.

2024-12-19 19:11 UTC, MaxKellermann commented
> Would you like to be the formal maintainer of the messenger?

"Like" is not the best word. I'm maintainer of literally dozens of distinct projects, and the day has only 24 hours. What I need the least is yet another project to maintain. I guess everybody here knows that feeling...

The messenger is a very important piece at the center of all Ceph processes, yet it is a big unoptimized knot of spaghetti. It has a simple task, and I wonder why such a simple thing degenerated into this kind of mess. Yes, I'd like to optimize it, and incrementally rewrite it into code that is both faster and simpler.

However, I worry about two things:
1. there are two messenger backends (RDMA and DPDK) that I have no idea of and cannot test/develop/support; these appear to be experimental and not mature for production use, but apparently nobody is working on maturing them. Right now, I don't know how to refactor the core messenger APIs without breaking RDMA/DPDK. I don't even know why these exist and whether the additionaly code complexity for these features is justified. Are the real-world performance gains so large? (and will they remain large even if the messenger gets optimized with io_uring?)

2. this is the more important thing: is my philosophy of optimizing code really what you Ceph people want? I'm a low-level guy, and I can write code at a low level with extremely low overhead. But Ceph appears to be heading a different direction by building the next-generation OSD (=Crimson) on a heavy framework (=Seastar). As much as I dislike Ceph's current (complicated, slow and unsafe) coding style, Crimson/Seastar is the wrong direction for my taste (see https://github.com/ceph/ceph/pull/60452 for a discussion where I explain why I disapprove of Seastar).

If you do like Seastar, you should migrate the messenger to Seastar; it's a framework tailored for exactly this kind of stuff. If Crimson+Seastar is the future, then it makes no sense to maintain other I/O event loops in Ceph. But then I'm the wrong guy for the job, and I wouldn't want to waste time on improving the old messenger. Before I commit to anything, I'd like to know about your plans.

(Apart from technical reasons, [as of yesterday, there are reasons to lose trust in ScyllaDB](https://www.scylladb.com/2024/12/18/why-were-moving-to-a-source-available-license/), the commercial vendor who develops and maintains Seastar. For now, Seastar remains open source, but who knows what'll happen next.)

2024-12-19 19:28 UTC, batrick commented
> > Would you like to be the formal maintainer of the messenger?
> 
> "Like" is not the best word. I'm maintainer of literally dozens of distinct projects, and the day has only 24 hours. What I need the least is yet another project to maintain. I guess everybody here knows that feeling...

Well, no one is taking responsibility for the msgr so even a half-hearted helper is better than nothing.

> The messenger is a very important piece at the center of all Ceph processes, yet it is a big unoptimized knot of spaghetti.

I do not disagree.

> It has a simple task, and I wonder why such a simple thing degenerated into this kind of mess. Yes, I'd like to optimize it, and incrementally rewrite it into code that is both faster and simpler.
> 
> However, I worry about two things:
> 
>     1. there are two messenger backends (RDMA and DPDK) that I have no idea of and cannot test/develop/support; these appear to be experimental and not mature for production use, but apparently nobody is working on maturing them. Right now, I don't know how to refactor the core messenger APIs without breaking RDMA/DPDK. I don't even know why these exist and whether the additionaly code complexity for these features is justified. Are the real-world performance gains so large? (and will they remain large even if the messenger gets optimized with io_uring?)

There was historical interest in this but it may not be worth maintaining. I'm not certain if anyone really cares about it anymore (and could be ripped out) but that requires discussion on the ML / CSC call.

>     2. this is the more important thing: is my philosophy of optimizing code really what you Ceph people want? I'm a low-level guy, and I can write code at a low level with extremely low overhead. But Ceph appears to be heading a different direction by building the next-generation OSD (=Crimson) on a heavy framework (=Seastar). As much as I dislike Ceph's current (complicated, slow and unsafe) coding style, Crimson/Seastar is the wrong direction for my taste (see [msg/async: use io_uring instead of sendmsg() #60452](https://github.com/ceph/ceph/pull/60452) for a discussion where I explain why I disapprove of Seastar).
> 
> 
> If you do like Seastar, you should migrate the messenger to Seastar; it's a framework tailored for exactly this kind of stuff. If Crimson+Seastar is the future, then it makes no sense to maintain other I/O event loops in Ceph. But then I'm the wrong guy for the job, and I wouldn't want to waste time on improving the old messenger. Before I commit to anything, I'd like to know about your plans.

There will be a seastarified msgr but it will be separate. seastar is not appropriate for all Ceph daemons (like the MDS).

2025-01-09 14:46 UTC, markhpc commented
> > It has a simple task, and I wonder why such a simple thing degenerated into this kind of mess. Yes, I'd like to optimize it, and incrementally rewrite it into code that is both faster and simpler.
> > However, I worry about two things:
> > ```
> > 1. there are two messenger backends (RDMA and DPDK) that I have no idea of and cannot test/develop/support; these appear to be experimental and not mature for production use, but apparently nobody is working on maturing them. Right now, I don't know how to refactor the core messenger APIs without breaking RDMA/DPDK. I don't even know why these exist and whether the additionaly code complexity for these features is justified. Are the real-world performance gains so large? (and will they remain large even if the messenger gets optimized with io_uring?)
> > ```
> 
> There was historical interest in this but it may not be worth maintaining. I'm not certain if anyone really cares about it anymore (and could be ripped out) but that requires discussion on the ML / CSC call.
> 

For what it's worth, I had a conversation with @fullerdj at supercomputer 2024 about trying to reinvigorate the RDMA backend.  Not sure if the folks at Cornelis have any time/interest in helping us here, but at least in the HPC world there is still quite a bit of RDMA usage and it's a fairly significant missing feature relative to other storage systems.

2025-01-21 08:02 UTC, MaxKellermann commented
> in the HPC world there is still quite a bit of RDMA usage and it's a fairly significant missing feature relative to other storage systems

I have no idea about the usefulness of RDMA, but right now, Ceph's RDMA code looks unfinished and unmaintained, far from ready for production use and with no perspective of ever getting ready. On the other hand, the existence of this immature messenger backend is a maintenance burden.
Real progress with optimizing the (epoll) messenger can only be made by refactoring the API, but every API change must adjust (and test) all backends.

I don't want to talk you out of this RDMA (or DPDK) feature, but if it's only a pipe dream with no real perspective, Ceph would be better off being honest and remove it, to allow the epoll backend to thrive.

But as @batrick wrote (slightly switching topic):

> There will be a seastarified msgr but it will be separate.

With a Seastar-based messenger in the future, will anybody really ever use the (non-Seastar) RDMA/DPDK messenger? Are these two conflicting goals? (Because Seastar has a DPDK backend already, but apparently no RDMA, but maybe it's better to add RDMA to Seastar than Ceph?)
Or will the non-Seastar parts of Ceph benefit from RDMA? Which parts of Ceph will really use Seastar and which ones will not?

By the way, I don't agree that Ceph should have two separate messenger implementations. But if a non-Seastar messenger has a long-term future ahead, I'd like to help improve it - if you only let me. I have put my work on Ceph on hold for the last three months because I had been submitting PRs faster than you could process them, and it makes no sense to produce more PRs.

2025-01-23 16:26 UTC, adamemerson commented
If someone wanted to do serious work on the messenger and make a Seastar version, I would really, really appreciate it if we could follow a path similar to what some Rust libraries try to do: try to have as much of the logic split out into runtime (e.g. seastar) independent code as possible. Done that way, it should be fairly easy to have someone else (me, likely) take a working Seastar implementation of the messenger and come up with a working Asio messenger based on it without duplicating a bunch of code.

2025-01-23 16:54 UTC, MaxKellermann commented
> working Seastar implementation of the messenger and come up with a working Asio messenger based on it without duplicating a bunch of code

Asio? Oh no.

When @batrick asked whether I'd like to maintain the messenger code, I wasn't sure what direction Ceph is heading, and whether my approach to writing fast networking code was welcome. It looked like Ceph as a whole was heading towards Seastar, and I don't want to touch any Seastar related code. Then it sounded like only some unspecified parts were heading towards Seastar, but what about the rest?

The current messenger uses no bloated framework, which I think is a good thing, it's just not good code, but I can help improve that, if you really want it my way. If, however, the non-Seastar parts of Ceph are going Asio, this is (for me) just as bad as Seastar, and I don't like to touch it. (Just my opinion, which I don't expect anybody to agree with.)

But anyway, I welcome any effort to improve the messenger, so @adamemerson if you step up to replace the current one with something that solves all the obvious issues, it's a good thing.

2025-03-30 21:23 UTC, MaxKellermann commented
It's been nearly half a year without a review. I won't be around for much longer, see https://github.com/ceph/ceph/pull/60452#issuecomment-2764750265 - are you interested in merging this or not? I'd like to get this (and other PRs) off my desk.

2025-05-20 14:22 UTC, MaxKellermann commented
Another two months have passed. Posting a useless comment so the Ceph bot doesn't close it as "stale".

2025-05-20 14:49 UTC, batrick requested changes
Okay, I'll try to sit down and get through this...

Your first commit, perhaps we should add an assert in _try_send that we do not hold the `write_lock`? With an explanation...

Removing the send from `write_message` is okay BUT we recently added the debugging to see when a message is **actually sent via a syscall** and this debug message can no longer be trusted. Can you figure out a way to make the debugging `sending message...` correct with the combined sendmsg?

You also dropped the `logger->inc` calls. Those need to stay.

Otherwise, I like the intent of the change.

2025-05-20 15:05 UTC, MaxKellermann commented
> You also dropped the `logger->inc` calls. Those need to stay.

They are dropped only where the send() calls are dropped. If they stay (even though nothing was actually sent), you will get wrong numbers.

2025-05-20 15:15 UTC, MaxKellermann commented
> Removing the send from `write_message` is okay BUT we recently added the debugging to see when a message is **actually sent via a syscall** and this debug message can no longer be trusted. Can you figure out a way to make the debugging `sending message...` correct with the combined sendmsg?

This could not be trusted before (if the socket buffer is full and send() returns EAGAIN), and this has only become the common case (postponing the actual system call until we know the socket is writable). Since all data is queued in a bufferlist (outgoing_bl) with no information about individual messages, logging this will be hard.

This PR doesn't actually change the code structure: the bufferlist was there before, and the code for flushing it doesn't change; but this has become the comon code path.

This could be changed to preserve information about individual messages, but this would add runtime overhead (both CPU and memory, and of course additional code, reducing instruction cache efficiency in hot code paths). Do you really want that?

2025-05-20 17:28 UTC, batrick commented
> > You also dropped the `logger->inc` calls. Those need to stay.
> 
> They are dropped only where the send() calls are dropped. If they stay (even though nothing was actually sent), you will get wrong numbers.

I don't mean that those calls should stay in that same spot, but they should be moved to where the send actually occurs. Currently the `inc` calls are completely gone.

2025-05-20 17:31 UTC, batrick commented
> > Removing the send from `write_message` is okay BUT we recently added the debugging to see when a message is **actually sent via a syscall** and this debug message can no longer be trusted. Can you figure out a way to make the debugging `sending message...` correct with the combined sendmsg?
> 
> This could not be trusted before (if the socket buffer is full and send() returns EAGAIN), and this has only become the common case (postponing the actual system call until we know the socket is writable). Since all data is queued in a bufferlist (outgoing_bl) with no information about individual messages, logging this will be hard.
> 
> This PR doesn't actually change the code structure: the bufferlist was there before, and the code for flushing it doesn't change; but this has become the comon code path.
> 
> This could be changed to preserve information about individual messages, but this would add runtime overhead (both CPU and memory, and of course additional code, reducing instruction cache efficiency in hot code paths). Do you really want that?

I don't think it's that hard. You can keep track with a vector (which generally never shrinks in allocated space) of pairs like: <off_t, MessageRef> where you know what messages correspond to what offset in the outgoing_bl. There's no need for a map or anything like that. If you move the ref I don't think you even need to adjust the ref count.

It's possible I'm missing some nuance however.

2025-05-20 18:05 UTC, MaxKellermann commented
> I don't mean that those calls should stay in that same spot, but they should be moved to where the send actually occurs. Currently the `inc` calls are completely gone.

If they are gone (i.e. not even present in the EAGAIN code path), then the code was just as buggy before. Of course that needs to be fixed.

2025-05-22 06:42 UTC, MaxKellermann commented
> You can keep track with a vector (which generally never shrinks in allocated space) of pairs like: <off_t, MessageRef> where you know what messages correspond to what offset in the outgoing_bl.

This doesn't sound like something I would like to spend my time on. I don't understand the purpose of this, the existing code is already broken, and since we are migrating away from Ceph, the time I have for Ceph is extremely limited. For Ceph, I believe optimizations like this are extremely important (the current messenger code is very very clumsy, almost beyond repair). Yet this PR has hit a barrier where I see no productive way forward, because I will not implement the missing bookkeeping/logging for the existing EAGAIN code paths. Therefore I close this one, hoping somebody else will improve the messenger eventually.

2025-05-22 06:42 UTC, closed without merging