osd/recovery_types: BackfillInterval Revision
ceph/ceph pull request #60522
Opened 2024-10-28 19:21 UTC by Matan-B

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-10-29 11:07 UTC, Matan-B commented
@xuxuehan, early version, will rebase once we merge the pending fixes.

2024-11-18 16:46 UTC, Matan-B commented on src/osd/recovery_types.cc
> +  version = e.version;
Please see commit message

2024-11-18 16:48 UTC, Matan-B commented
jenkins test signed

2025-01-07 02:58 UTC, athanatos commented on src/osd/recovery_types.h
> +  hobject_t begin; /// object to start populating the interval from
inclusive, right?

2025-01-07 02:59 UTC, athanatos commented on src/osd/recovery_types.h
> +  hobject_t begin; /// object to start populating the interval from
"to start populating" -- this only gets set once the interval has contents.  It's a statement about the current contents, not future ones.  Also, you probably want to specify that it's *inclusive*.

2025-01-07 03:45 UTC, athanatos requested changes
Glad this is getting cleaned up, it's definitely super confusing.

2025-01-07 03:45 UTC, athanatos commented on src/osd/PrimaryLogPG.cc
> +      bi.populate(m->get_data(), m->version);
Seems like it would be cleaner for MOSDScanDigestReply to have a get_interval() method which returns a fully constructed BackfillInterval.

2025-01-07 03:45 UTC, athanatos commented on src/osd/PrimaryLogPG.cc
> +  ceph_assert(backfill_info->empty());
These asserts will probably also need to assert that the optional isn't empty.

2025-01-07 03:45 UTC, athanatos commented on src/osd/PrimaryLogPG.cc
> +  ceph_assert(backfill_info->empty());
If we want PrimaryLogPG::backfill_info to be std::nullopt when not used, it would probably make sense to try to move it into PeeringState?  I think there's a state with a lifecycle which matches it?

2025-01-07 03:45 UTC, athanatos commented on src/osd/recovery_types.h
> + * 1) Unpopulated - only interval's range is set
This is meant to reflect the primary side usage where we have a persistent PrimaryLogPG::backfill_interval where we progressively update the bounds and then update the contents, right?

I'm not sure I like formalizing that update pattern.  It's really a bit of a misuse of the data structure as I think the original intent was mainly for it to be an interchange format between osds.  begin and end should always reflect the current contents of objects.

Perhaps there's a way to massage the primary-side logic so it doesn't update the actual bounds until it updates the contents as well?

I'd particularly like to avoid constructors which place the object into a partial state.  The default construction with begin=end=hobject_t() and an empty objects map is correct in all cases.

If you feel it's cleaner, the mechanism you've created here could work.  I do think you'll want to be more explicit about the intended usage though.

2025-01-07 03:45 UTC, athanatos commented on src/osd/recovery_types.h
> +  BackfillInterval(hobject_t begin);
What is this meant to model?  Certainly, end must be >= begin, so it sets begin=end?

2025-01-07 03:45 UTC, athanatos commented on src/osd/recovery_types.h
> +
Same here, it would probably be worth adding a comment explaining what this constructor is meant to do.  I think there's also an implicit invariant that end >= begin that you'll want to mention.

2025-01-07 03:45 UTC, athanatos commented on src/osd/recovery_types.h
> +  // populate the objects in the interval and update version
This is MOSDBackfillScanReply, right?  That message should have a method which simply returns a fully populated BackfillInterval.  No reason for the message handler to have to do that.

2025-01-07 03:45 UTC, athanatos commented on src/crimson/osd/backfill_state.cc
>                         e.version);
I *think* it's safe to assume that if the projected log has any contents, get_projected_last_update == projected_log.back().version.  (It's not quite safe to assume the same for the actual log because split can leave holes at the end of the log.)

2025-01-07 03:45 UTC, athanatos commented on src/osd/recovery_types.cc
> +void BackfillInterval::update(const pg_log_entry_t &e) {
Yeah, that's way better.

2025-01-07 03:45 UTC, athanatos commented on src/crimson/osd/recovery_backend.cc
>    BackfillInterval bi(m.begin, m.end);
Why not just construct bi here with begin, end, data, version?

2025-01-07 03:45 UTC, athanatos commented on src/osd/PrimaryLogPG.cc
> +  scanned_bi.populate(std::move(objects), version);
Same comment here, could just construct it correctly.

2025-01-07 03:45 UTC, athanatos commented on src/messages/MOSDPGScan.h
> +    OP_SCAN_DIGEST_REPLY = 2,    // populated BackfillInterval reply
If we're going to suffix it with _REPLY, let's make it OP_SCAN_GET_DIGEST_REPLY

2025-01-07 03:45 UTC, athanatos commented on src/osd/PrimaryLogPG.cc
> +	  pbi.end, hobject_t(), eversion_t());
This constructor constructs the request, right?  Can we just not include the version field?  Might make sense to have two different named constructors, one for GET_DIGEST, the other for GET_DIGEST_REPLY?

2025-01-07 03:45 UTC, athanatos commented on src/crimson/osd/recovery_backend.cc
> +  bi.populate(m.get_data(), m.version);
Why do we need the version here?  We won't submit any IOs on the objects in the range we're scanning, so I don't think we need to update the replica bi's from the log/projected_log (not true of the primary).

Alternately, if we actually do need the version, why is it safe to pass in m.version here from an old replica which didn't populate it?

2025-01-07 03:45 UTC, athanatos commented on src/osd/recovery_types.cc
> +      end = objects.rbegin();
This isn't the point of begin and end.  If it were, we could simply have get_begin() and get_end() which check the first and last entries of objects and skip storing them entirely.  Suppose we have an interval begin=x, end=y, objects=[x, t0, t1, ..., tn].  We know that objects is the set of *all* objects t such that x <= t < y.  Processing a delete on x would change objects to [t0, t1, ..., tn], but it doesn't change the fact that it's the set of all objects t such that x <= t < y.  Updating begin to t0 actually throws away information because we lose the fact that we know that there are no objects between x and t0.

Also, the update to end here is actually wrong.  end is exclusive.  From PrimaryLogPG::scan_range:

```
  int r = pgbackend->objects_list_partial(bi->begin, min, max, &ls, &bi->end);
```

PGBackend::objects_list_partial:

```
      r = store->collection_list(
        ch,
        _next,
        ghobject_t::get_max(),
        max - ls->size(),
        &objects,
        &_next);
```

ObjectStore:

```
  /**
   * std::list contents of a collection that fall in the range [start, end) and no more than a specified many result
   *
   * @param c collection
   * @param start list object that sort >= this value
   * @param end list objects that sort < this value
   * @param max return no more than this many results
   * @param seq return no objects with snap < seq
   * @param ls [out] result
   * @param next [out] next item sorts >= this value
   * @return zero on success, or negative error
   */
  virtual int collection_list(CollectionHandle &c,
			      const ghobject_t& start, const ghobject_t& end,
			      int max,
			      std::vector<ghobject_t> *ls, ghobject_t *next) = 0;
```

Specifically, ```   * @param next [out] next item sorts >= this value``` means that next will, in general, sort greater than any element of the returned list and certainly will not be in it.

Assuming I'm not massively wrong (and I could be), BackfillInterval::end will *never* be in objects.

2025-01-07 03:45 UTC, athanatos commented on src/crimson/osd/backfill_state.cc
> +  primary_bi.trim_to(backfill_state().last_backfill_started);
This looks probably right.

2025-01-26 14:55 UTC, Matan-B commented on src/osd/PrimaryLogPG.cc
> +  ceph_assert(backfill_info->empty());
> If we want PrimaryLogPG::backfill_info to be std::nullopt when not used, it would probably make sense to try to move it into PeeringState? I think there's a state with a lifecycle which matches it?

This is tricky, the state which would match is `PeeringState::Backfilling`.
It is possible to move `PrimaryLogPG::backfill_info` into `PeeringState::Backfilling::backfill_info`. However, I don't think that the interface provided by Boost's statechart allows changing the state from outside the machine.
Meaning, the only way for PrimaryLogPG to hold a reference to the state which holds the backfill information would be using `statechart::state_cast<const Backfilling*>` - which provides a const reference (of the state) only.
PrimaryLogPG _must_ have a non-const reference as it's actually responsible for updating the backfill information. Alternatively, we could move the update logic out of PrimaryLogPG but that would probably be unreasonable refactor to go though(?).

2025-01-26 15:04 UTC, Matan-B commented on src/osd/recovery_types.h
> + * 1) Unpopulated - only interval's range is set
> I'm not sure I like formalizing that update pattern. It's really a bit of a misuse of the data structure as I think the original intent was mainly for it to be an interchange format between osds. begin and end should always reflect the current contents of objects.

The main misuse of this data structure is for example when we "initialize BackfillIntervals" in `PrimaryLogPG::recover_backfill`.  There we create an unpopulated BackfillInterval instance for each peer and also for the local interval of this pg.
The idea there is to "mark" where would the interval begin with for future scans/users.

> Perhaps there's a way to massage the primary-side logic so it doesn't update the actual bounds until it updates the contents as well?
> 
> I'd particularly like to avoid constructors which place the object into a partial state. The default construction with begin=end=hobject_t() and an empty objects map is correct in all cases.
> 
> If you feel it's cleaner, the mechanism you've created here could work. I do think you'll want to be more explicit about the intended usage though.

I'll give this more thought to come up with a better/more precise solution.

2025-01-28 13:45 UTC, Matan-B commented on src/osd/PrimaryLogPG.cc
> +  ceph_assert(backfill_info->empty());
Moved to non-optional as it was before for now due to the reason mentioned above.

2025-01-28 13:51 UTC, Matan-B commented on src/osd/recovery_types.h
> + * 1) Unpopulated - only interval's range is set
Added explicit comments to each possible state.

Regarding my comment above:
> There we create an unpopulated BackfillInterval instance for each peer

One way to solve the undefined state would be to change the way `peer_backfill_info` logic works.
Currently we create an (undefined) interval for each peer to be inserted to `peer_backfill_info` until we get
results from the scan. Alternatively, we could add a `peer_backfill_start_scan`(?) that would only keep the mark from which start point we should actually scan the peer from.
**Only when** the results are there, we would emplace then into `peer_backfill_info`.

For now I kept the original way `peer_backfill_info` works with the undefined state allowed.

2025-01-28 13:53 UTC, Matan-B commented on src/crimson/osd/recovery_backend.cc
> +  bi.populate(m.get_data(), m.version);
> why is it safe to pass in m.version here from an old replica which didn't populate it?

My bad there, version was omitted from MOSDPGScan

2025-01-28 13:53 UTC, Matan-B commented on src/osd/recovery_types.cc
> +      end = objects.rbegin();
Added assert for now that the object actually exists in map (and was not deleted)

2025-01-28 14:11 UTC, Matan-B commented
@athanatos, all comments are addressed, thank you for the review.
Left 2 comments as unresolved:
* Possible states - https://github.com/ceph/ceph/pull/60522#discussion_r1904855587
*  Use matching peeringstate state - https://github.com/ceph/ceph/pull/60522#discussion_r1904853412

2025-01-31 00:16 UTC, athanatos approved these changes
Seems reasonable

2025-01-31 00:16 UTC, athanatos commented on src/osd/recovery_types.h
> +  bool is_valid_begin() const {
How about is_begin_trimmed()?  begin is *valid* even if not present in objects.

2025-02-02 12:32 UTC, Matan-B commented on src/osd/recovery_types.h
> +  bool is_valid_begin() const {
Changed to is_existing_begin

2025-02-20 11:20 UTC, Matan-B commented
@SrinivasaBharath, I've rebased this PR and only changed crimson side conflicts - that shouldn't affect any builds/tests already queued.

2025-02-26 23:46 UTC, ljflores reviewed
Hey @Matan-B, in the teuthology run, we found a related failure:
/a/skanta-2025-02-20_22:40:15-rados-wip-bharath8-testing-2025-02-19-0531-distro-default-smithi/8145370
```
2025-02-21T02:28:53.658 INFO:tasks.ceph.osd.8.smithi013.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.3.0-7712-g614b0353/rpm/el9/BUILD/ceph-19.3.0-7712-g614b0353/src/osd/PrimaryLogPG.cc: In function 'uint64_t PrimaryLogPG::recover_backfill(uint64_t, ThreadPool::TPHandle&, bool*)' thread 7fe9d48c3640 time 2025-02-21T02:28:53.665024+0000
2025-02-21T02:28:53.658 INFO:tasks.ceph.osd.8.smithi013.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.3.0-7712-g614b0353/rpm/el9/BUILD/ceph-19.3.0-7712-g614b0353/src/osd/PrimaryLogPG.cc: 13958: FAILED ceph_assert(backfill_info.is_populated())
2025-02-21T02:28:53.658 INFO:teuthology.orchestra.run.smithi043.stdout:{
2025-02-21T02:28:53.658 INFO:teuthology.orchestra.run.smithi043.stdout:    "ops": [],
2025-02-21T02:28:53.658 INFO:teuthology.orchestra.run.smithi043.stdout:    "complaint_time": 30,
2025-02-21T02:28:53.658 INFO:teuthology.orchestra.run.smithi043.stdout:    "num_blocked_ops": 0
2025-02-21T02:28:53.658 INFO:teuthology.orchestra.run.smithi043.stdout:}
2025-02-21T02:28:53.659 INFO:tasks.ceph.osd.8.smithi013.stderr: ceph version 19.3.0-7712-g614b0353 (614b0353cd8002f57cdce54ac5ccd1d045c51c20) squid (dev)
2025-02-21T02:28:53.659 INFO:tasks.ceph.osd.8.smithi013.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x113) [0x5650227fc7a3]
2025-02-21T02:28:53.659 INFO:tasks.ceph.osd.8.smithi013.stderr: 2: ceph-osd(+0x41295a) [0x5650227fc95a]
2025-02-21T02:28:53.659 INFO:tasks.ceph.osd.8.smithi013.stderr: 3: ceph-osd(+0x3b3b2c) [0x56502279db2c]
2025-02-21T02:28:53.659 INFO:tasks.ceph.osd.8.smithi013.stderr: 4: (PrimaryLogPG::start_recovery_ops(unsigned long, ThreadPool::TPHandle&, unsigned long*)+0xf89) [0x565022acaa09]
2025-02-21T02:28:53.660 INFO:tasks.ceph.osd.8.smithi013.stderr: 5: (OSD::do_recovery(PG*, unsigned int, unsigned long, int, ThreadPool::TPHandle&)+0x243) [0x5650229b1323]
2025-02-21T02:28:53.660 INFO:tasks.ceph.osd.8.smithi013.stderr: 6: (ceph::osd::scheduler::PGRecovery::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0xca) [0x565022c135ba]
2025-02-21T02:28:53.660 INFO:tasks.ceph.osd.8.smithi013.stderr: 7: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0xcd0) [0x5650229c9a10]
2025-02-21T02:28:53.660 INFO:tasks.ceph.osd.8.smithi013.stderr: 8: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x2aa) [0x565022f0400a]
2025-02-21T02:28:53.660 INFO:tasks.ceph.osd.8.smithi013.stderr: 9: ceph-osd(+0xb1a5c4) [0x565022f045c4]
2025-02-21T02:28:53.660 INFO:tasks.ceph.osd.8.smithi013.stderr: 10: /lib64/libc.so.6(+0x8a3b2) [0x7fe9f508a3b2]
2025-02-21T02:28:53.660 INFO:tasks.ceph.osd.8.smithi013.stderr: 11: /lib64/libc.so.6(+0x10f430) [0x7fe9f510f430]
```

Since there was another PR tested in the batch that also caused a regression, I will have this PR tested separately to confirm the issue and/or that there were no clashes between the PRs.

Testing ref: https://tracker.ceph.com/issues/70113

2025-02-27 10:05 UTC, aainscow commented
jenkins test make check arm64

2025-03-17 07:55 UTC, Matan-B commented
I'll run this through a minimal suite before qa.

2025-10-21 11:01 UTC, closed without merging