mon/nvmeofgw*: monitors publish in nvme-gw show ana group responsible
ceph/ceph pull request #60663
Opened 2024-11-07 14:42 UTC by leonidc

for  namespace rebalance

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-11-07 16:56 UTC, athanatos requested changes

2024-11-07 16:56 UTC, athanatos commented on src/mon/NVMeofGwMon.cc
> +    global_rebalance_index ++;
global_rebalance_index++;

2024-11-07 16:56 UTC, athanatos commented on src/mon/NVMeofGwMon.cc
> +        f->dump_unsigned ("rebalance_ana_group", index);
f->dump_unsigned("rebalance_ana_group", index);

2024-11-07 16:56 UTC, athanatos commented on src/mon/NVMeofGwMon.h
> +  uint32_t global_rebalance_index;
uint32_t global_rebalance_index = 1;
uint8_t  tick_ratio = 0;

2024-11-07 16:56 UTC, athanatos commented on src/mon/NVMeofGwMon.h
> +    tick_ratio = 0;
No need for this, initialize at the declaration site.

2024-11-08 06:32 UTC, leonidc commented on src/mon/NVMeofGwMon.cc
> +        f->dump_unsigned ("rebalance_ana_group", index);
sure

2024-11-08 21:33 UTC, athanatos approved these changes

2024-11-09 11:02 UTC, leonidc commented
jenkins test api

2024-11-09 13:29 UTC, merged