RGW/logging: add rest API to flush logging bucket
ceph/ceph pull request #60697
Opened 2024-11-11 13:26 UTC by AliMasarweh

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-11-11 14:40 UTC, yuvalif commented on src/rgw/rgw_rest_bucket_logging.cc
> +    const auto max_size = s->cct->_conf->rgw_max_put_param_size;
i don't think we expect any XML payload in this operation. wht information do we need except the source bucket name (which is in the request not the XML payload)?

2024-11-11 14:43 UTC, yuvalif commented on src/rgw/rgw_rest_bucket_logging.cc
> +      return;
do we expect result here to be sucess?
if not we should probably set:`op_ret = -EINVAL`

2024-11-12 09:11 UTC, yuvalif commented
LGTM. 
currently in the process of testing https://github.com/ceph/ceph/pull/59808
so, we should probably take this work after the main PR is merged

2024-11-21 09:35 UTC, yuvalif commented on src/rgw/rgw_rest_s3.cc
> +  if (s->info.args.sub_resource_exists("logging")) {
```suggestion
  if (s->info.args.exists("logging")) {
```

2024-11-21 09:36 UTC, yuvalif commented on examples/rgw/boto3/post_bucket_logging.py
> +    hostname = 'http://127.0.0.1'
this is url not hostname

2024-11-25 16:28 UTC, yuvalif commented on src/test/rgw/bucket_notification/api.py
> +class BucketLogging:
we don't need this.
bucket logging tests are done elsewhere (as part of s3test)

2024-12-11 20:56 UTC, yuvalif commented
s3tests added here: https://github.com/ceph/s3-tests/pull/606

2024-12-11 21:00 UTC, yuvalif commented
please add documentation both to bucket ops doc and bucket logging doc.

2024-12-15 14:09 UTC, AliMasarweh commented
s3tests passed

2024-12-15 14:09 UTC, AliMasarweh commented
> s3tests added here: [ceph/s3-tests#606](https://github.com/ceph/s3-tests/pull/606)

s3tests for bucket logging passed

2024-12-17 10:25 UTC, yuvalif requested changes
please remove the test branch commit before merge

2024-12-17 10:55 UTC, AliMasarweh commented
> please remove the test branch commit before merge

Done

2024-12-17 12:21 UTC, yuvalif approved these changes

2024-12-17 12:22 UTC, yuvalif commented
@AliMasarweh please merge once all tests are passing

2024-12-17 13:34 UTC, AliMasarweh commented
jenkins test make check

2024-12-17 15:08 UTC, merged