mgr/cephadm: Changes for creating root cert with manager cluster fsid
ceph/ceph pull request #60943
Opened 2024-12-04 11:03 UTC by anuradhagadge

cephadm orch mgr: Add fsid detail when ca certificate is created to identify cluster in multi cluster ceph.

Fixes: https://tracker.ceph.com/issues/69081

Signed-off-by: Anuradha Gadge [anuradha.gadge@ibm.com](mailto:anuradha.gadge@ibm.com)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-12-04 12:26 UTC, anuradhagadge commented
jenkins test api

2024-12-04 19:50 UTC, adk3798 commented
jenkins test api

2024-12-10 11:18 UTC, rkachach requested changes
Overall, LGTM but I think we can improve the code with some minor changes :)

2024-12-10 11:18 UTC, rkachach commented on src/pybind/mgr/cephadm/cert_mgr.py
> +        self.ssl_certs: SSLCerts = SSLCerts(fsid=mgr._cluster_fsid)
```suggestion
        self.ssl_certs: SSLCerts = SSLCerts(mgr._cluster_fsid)
```

2024-12-10 11:18 UTC, rkachach commented on src/pybind/mgr/cephadm/ssl_cert_utils.py
> +        self.mgr_cluster_fsid: str = fsid
```suggestion
        self.cluster_fsid: str = fsid
```

2024-12-10 11:18 UTC, rkachach commented on src/pybind/mgr/cephadm/ssl_cert_utils.py
> +            x509.NameAttribute(NameOID.COMMON_NAME, u'cephadm-{}-root'.format(self.mgr_cluster_fsid)),
```suggestion
            x509.NameAttribute(NameOID.COMMON_NAME, f'cephadm-root-{self.cluster_fsid}'),
```

2024-12-10 11:18 UTC, rkachach commented on src/pybind/mgr/cephadm/ssl_cert_utils.py
> +            x509.NameAttribute(NameOID.COMMON_NAME, u'cephadm-{}-root'.format(self.mgr_cluster_fsid)),
```suggestion
            x509.NameAttribute(NameOID.COMMON_NAME, f'cephadm-root-{self.cluster_fsid}'),
```

2024-12-10 11:18 UTC, rkachach commented on src/pybind/mgr/cephadm/tests/test_node_proxy.py
> +        self.http_server.agent.ssl_certs = SSLCerts("fake fsid")
probably we should use a well-formatted fake fsid

2024-12-10 16:32 UTC, anuradhagadge commented on src/pybind/mgr/cephadm/cert_mgr.py
> +        self.ssl_certs: SSLCerts = SSLCerts(fsid=mgr._cluster_fsid)
Done

2024-12-10 16:32 UTC, anuradhagadge commented on src/pybind/mgr/cephadm/ssl_cert_utils.py
> +        self.mgr_cluster_fsid: str = fsid
Done

2024-12-11 09:35 UTC, rkachach approved these changes
Changes LGTM but we need to test them manually in this case.

2024-12-12 07:32 UTC, anuradhagadge commented
Manual testing is in progress for this PR.

2024-12-12 07:33 UTC, anuradhagadge commented
jenkins test make check ceph dashboard cephadm e2e tests

2024-12-17 10:00 UTC, anuradhagadge commented
jenkins test ceph dashboard cephadm e2e tests

2025-01-08 20:40 UTC, adk3798 commented
@anuradhagadge you'd mentioned you saw issues when testing this correct? I saw `Failed to send metadata to mgr: non-200 response <-1> from agent endpoint: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:  unable to get local issuer certificate (_ssl.c:1147)` causing all the cephadm agents to go down in a test run. Does that look like it could be coming from this PR? I'm going to take my testing tag off for the time being and see how that changes the results (example relevant failed test https://pulpito.ceph.com/adking-2025-01-07_14:46:22-orch:cephadm-wip-adk-testing-2025-01-06-1754-distro-default-smithi/8066110/)

2025-01-10 08:36 UTC, rkachach commented on src/pybind/mgr/cephadm/ssl_cert_utils.py
> +        san_list.append(x509.DNSName(f'fsid-{self.cluster_fsid}'))  # Add FSID as a DNSName in SAN
I think the comment in this case is just describing what the code is already doing, so I think we can get rid of it :+1:

2025-01-14 09:00 UTC, anuradhagadge commented
**Manual Dev Testing:**

Primary-Site
1. create multisite setup
2. install rgw service
Create rgw.yaml in cephadm shell with following contents

service_type: rgw
service_id: rgw-shared
service_name: pri-rgw-name
placement:
  hosts:
    - ceph-pri-node-0
spec: 
  rgw_frontend_port: 443
  generate_cert: true
  ssl: true
  zonegroup_hostnames:
    - s3.example.com

ceph orch apply -i rgw.yaml
It will schedule the rgw service

3. RGW service can been using following commands:
[ceph: root@ceph-pri-node-0 /]# ceph orch ls
NAME                       PORTS  RUNNING  REFRESHED  AGE  PLACEMENT        
crash                                 1/1  8m ago     12h  *                
mgr                                   1/2  8m ago     12h  count:2          
mon                                   1/5  8m ago     12h  count:5          
osd.all-available-devices               1  8m ago     12h  *                
rgw.rgw-shared             ?:443      1/1  8m ago     12h  ceph-pri-node-0  
[ceph: root@ceph-pri-node-0 /]# ceph orch ps
NAME                                   HOST             PORTS        STATUS         REFRESHED  AGE  MEM USE  MEM LIM  VERSION          IMAGE ID      CONTAINER ID  
crash.ceph-pri-node-0                  ceph-pri-node-0               running (12h)     8m ago  12h    6929k        -  19.2.0-57.el9cp  189548838d29  7aba652a9fc1  
mgr.ceph-pri-node-0.hoodjh             ceph-pri-node-0  *:9283,8765  running (12h)     8m ago  12h     540M        -  19.2.0-57.el9cp  189548838d29  b4bdd2961432  
mon.ceph-pri-node-0                    ceph-pri-node-0               running (12h)     8m ago  12h    96.6M    2048M  19.2.0-57.el9cp  189548838d29  3171e07bbbaa  
osd.0                                  ceph-pri-node-0               running (12h)     8m ago  12h    88.4M    4096M  19.2.0-57.el9cp  189548838d29  74d69b00117d  
rgw.rgw-shared.ceph-pri-node-0.hgasjm  ceph-pri-node-0  *:443        running (11h)     8m ago  12h    88.9M        -  19.2.0-57.el9cp  189548838d29  9b6cf072f181

4. Set the pools

ceph osd pool ls 
ceph config  set mon mon_allow_pool_size_one true 
ceph osd pool set .rgw.root size 1 --yes-i-really-mean-it; ceph osd pool set .rgw.root min_size 1 --yes-i-really-mean-it 
ceph osd pool set default.rgw.log size 1 --yes-i-really-mean-it; ceph osd pool set default.rgw.log min_size 1 --yes-i-really-mean-it 
ceph osd pool set default.rgw.control  size 1 --yes-i-really-mean-it; ceph osd pool set default.rgw.control min_size 1 --yes-i-really-mean-it 
ceph osd pool set default.rgw.meta  size 1 --yes-i-really-mean-it; ceph osd pool set default.rgw.meta min_size 1 --yes-i-really-mean-it 


5. Get the certififcate:
ceph orch cert-store get cert cephadm_root_ca_cert 

from node0 of secondary cluster

6. Store it in node0 of primary cluster(/etc/pki/ca-trust/source/anchors) where RGW service is deployed.

[root@ceph-pri-node-0 anchors]# ls
sec-ca.crt
[root@ceph-pri-node-0 anchors]# pwd
/etc/pki/ca-trust/source/anchors
[root@ceph-pri-node-0 anchors]# openssl x509 -in sec-ca.crt  -noout  -text 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            2c:52:56:c9:1f:a3:02:07:62:d5:cd:4b:6d:0b:82:6b:4f:e2:2e:a2
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=cephadm-root
        Validity
            Not Before: Jan  8 21:53:51 2025 GMT
            Not After : Jan  9 21:53:51 2035 GMT
        Subject: CN=cephadm-root
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:ca:e4:ca:f1:b1:77:36:9c:dc:f8:b6:55:57:20:
                    de:4d:a7:a2:de:ec:fb:93:7f:90:89:a3:2f:e2:77:
                    6d:f4:60:01:d2:54:f4:7e:52:5b:d8:2d:69:74:93:
                    c6:04:24:9b:ef:3c:fa:15:58:7f:43:64:54:c1:9c:
                    cf:c8:11:c3:59:7c:15:ea:03:89:25:10:92:1c:bc:
                    31:41:b6:59:c8:ed:2a:25:1f:7b:ff:d5:07:55:e5:
                    5d:6b:2f:7c:ac:08:4d:81:70:f5:a2:72:76:0e:c3:
                    b7:e2:56:f7:16:2d:ea:e0:b6:89:97:c5:fb:fa:4d:
                    b3:46:5f:04:0c:56:a0:f2:26:d4:46:87:7c:44:3b:
                    90:40:e1:ce:6f:f4:cf:02:2f:cb:f4:7b:c2:bc:fb:
                    87:60:d1:b8:48:9b:f7:28:79:09:57:9b:76:a9:ef:
                    cd:19:b3:44:10:a3:0b:e5:19:5e:aa:89:5f:b0:40:
                    db:01:a2:b6:7f:f6:b2:d1:5b:f1:bf:c5:38:54:fd:
                    79:75:f3:33:b3:03:c7:a5:a3:9a:9b:b5:c6:bd:5a:
                    1f:38:d3:60:b4:cb:13:9b:56:4e:b8:ad:51:fd:31:
                    36:32:9d:49:68:53:ae:d5:27:fc:ee:4a:9e:f6:e1:
                    9a:9a:6f:ba:8c:ae:81:40:df:14:ca:f3:9c:e2:c2:
                    56:23:19:f2:d8:c1:2e:b7:6a:9c:fe:11:80:7d:be:
                    eb:9b:65:a9:9b:30:51:74:ec:c0:78:79:61:1f:be:
                    7b:e4:a7:27:ee:3c:40:6a:02:0c:48:ef:36:65:af:
                    95:32:50:bd:fa:88:5b:65:d6:e3:17:69:6b:f4:6e:
                    c9:83:5a:70:f1:c9:3c:0f:15:30:09:e5:72:0e:1d:
                    c9:3d:a7:f7:80:d4:c7:d1:d2:d8:a6:73:fe:f1:b1:
                    2e:46:d9:73:b7:ed:1d:aa:09:56:18:3f:94:bc:3b:
                    58:89:4e:c6:38:9d:3e:3f:f5:cc:8a:0c:93:2e:5b:
                    97:b4:10:fc:e6:be:38:e6:5d:ab:dc:93:bd:7c:05:
                    c7:45:f1:50:08:53:9b:08:03:b8:87:c7:43:6b:7c:
                    d7:6b:c5:36:8e:18:ab:ad:45:98:d7:f6:80:0c:74:
                    80:e6:3f:41:4e:00:5b:c9:52:6a:ea:84:6b:64:7f:
                    39:c4:36:e5:e2:79:e3:4e:9b:35:bd:a2:5a:bd:9f:
                    2c:be:0a:c7:ad:f4:24:87:44:96:bf:64:ec:7f:10:
                    45:83:79:4e:e5:89:2d:a9:46:39:07:d5:37:d6:f5:
                    4d:f6:af:2a:0d:be:66:9e:52:fb:ff:a7:5e:ad:c5:
                    7a:fd:76:7c:4b:67:6b:33:a6:f3:33:37:cc:35:3d:
                    4c:db:ff
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:fsid-ab9acb56-ce0a-11ef-bf31-525400c6dd71, IP Address:192.168.100.110
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        3c:fd:f6:f3:e1:fd:3f:9a:ff:3f:a9:ec:84:f2:21:6f:e0:f7:
        e2:e6:4b:9e:4c:21:5b:57:8a:a6:f1:ad:1d:30:b8:04:49:86:
        b8:1f:c6:70:d4:c3:9c:45:78:ac:1f:f9:69:07:38:41:5b:c8:
        38:34:63:08:18:ad:a3:21:e7:71:b9:9d:af:1e:99:4b:11:36:
        e2:70:fa:b3:78:50:6f:1f:77:6e:56:af:fb:db:18:e9:00:b6:
        74:df:6e:2c:b2:40:1f:0e:f3:c3:0a:95:6d:77:71:85:fa:74:
        5e:4f:86:03:ca:34:40:8f:8b:bb:a5:90:85:31:61:96:6b:52:
        5b:ff:08:51:5f:4d:f6:cc:6c:16:6d:6f:37:95:8d:25:32:f9:
        84:fd:94:e7:44:ff:4c:d8:6d:8a:48:25:5d:2e:69:95:94:21:
        44:4c:5b:1f:d2:8e:ec:70:f0:e0:a4:5a:a4:fb:82:a5:31:c1:
        89:10:9d:7a:1f:c6:b4:c2:dc:7e:fb:5a:df:e9:2a:74:d2:f7:
        08:35:64:16:1f:a6:f1:98:7b:c4:59:b2:30:11:e3:67:36:02:
        55:73:b7:13:56:14:c6:66:77:3f:62:b2:f5:ba:16:75:b1:4a:
        5a:5a:9f:13:4f:96:d5:d9:3f:1b:c4:b3:b7:95:0d:be:60:5d:
        63:7d:10:31:a5:17:37:c8:7b:6d:9f:fc:ee:fb:fc:7c:1e:59:
        14:b7:9b:93:0e:64:05:86:a7:25:47:70:fe:e9:0f:5e:aa:66:
        61:72:78:48:65:7f:45:30:e2:50:c0:20:f5:cc:bf:55:09:9f:
        2e:8d:a4:7f:46:c6:27:ac:c3:35:40:95:f1:a6:39:54:bf:35:
        5d:5e:4d:5f:7d:4e:6a:8f:39:d2:eb:34:c6:9e:c3:43:45:8e:
        7b:c8:f7:db:4c:da:cc:f5:9e:f5:1e:e4:e0:e1:ce:fb:8e:46:
        6f:da:20:bc:e6:0d:e9:69:e5:d2:2f:e9:70:f7:ac:60:9d:cd:
        56:92:f4:16:e6:12:77:14:53:d8:df:dd:d0:61:24:81:d3:79:
        21:e9:1d:38:3b:73:6b:ec:41:d5:b2:82:d2:73:ad:7a:8e:ba:
        3a:f3:61:46:23:da:44:b2:20:ae:53:04:16:d0:48:68:57:d9:
        8b:2a:77:d7:45:20:d9:41:8b:16:e5:23:62:d9:3c:97:5b:c8:
        17:26:93:de:d6:97:d4:87:73:a1:ff:3a:0d:6b:89:3c:7d:cf:
        46:f5:86:7f:46:8a:93:31:f8:86:6e:64:1f:dc:ce:36:8d:8c:
        f0:42:d2:2b:23:da:3d:c9:4c:5c:c4:f1:fa:58:d6:cb:03:92:
        54:29:5a:fb:bc:ea:76:5f

7. Try curl comma [...]

2025-01-14 12:58 UTC, anuradhagadge commented
jenkins test api

2025-01-14 13:04 UTC, anuradhagadge commented
jenkins test api

2025-01-14 16:06 UTC, adk3798 commented
jenkins test api

2025-01-14 16:06 UTC, adk3798 commented
jenkins test dashboard cephadm

2025-01-23 19:13 UTC, adk3798 commented
original run: https://pulpito.ceph.com/adking-2025-01-16_05:45:12-orch:cephadm-wip-adk-testing-2025-01-15-1705-distro-default-smithi/

reruns: https://pulpito.ceph.com/adking-2025-01-16_15:09:00-orch:cephadm-wip-adk-testing-2025-01-15-1705-distro-default-smithi/

After reruns, I only saw known issues. There is still the problem of the test_nfs task failing, which would make me hesitant to merge nfs related PRs, but otherwise it was okay.

2025-01-23 19:22 UTC, merged