mgr/cephadm: Ceph orch apply command does not give error if 'placement' is passed as both positional and keyword argument
ceph/ceph pull request #61017
Opened 2024-12-10 10:59 UTC by ShwetaBhosale1

Ceph orch apply command does not give error if 'placement' is passed as both positional and keyword argument, It uses keyword argument value for configuration

Fixes: https://tracker.ceph.com/issues/69174
Signed-off-by: Shweta Bhosale <Shweta.Bhosale1@ibm.com>

Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph orch apply nfs mynfs --port 9090 nfs-ganesha-pool --placement='2'
Invalid command: Duplicate argument 'placement' found.
orch apply nfs <svc_id> [<placement>] [--format {plain|json|json-pretty|yaml|xml-pretty|xml}] [--port <int>] [--dry-run] [--unmanaged] [--no-overwrite] :  Scale an NFS service
Error EINVAL: invalid command
[ceph: root@ceph-node-0 /]# 

[ceph: root@ceph-node-0 /]# ceph orch apply nfs mynfs --port 9090 nfs-ganesha-pool                
Error EINVAL: Cannot place <NFSServiceSpec for service_name=nfs.mynfs> on nfs-ganesha-pool: Unknown hosts
[ceph: root@ceph-node-0 /]# 

[ceph: root@ceph-node-0 /]# ceph orch apply nfs mynfs --port 9090 --placement='2'
Scheduled nfs.mynfs update...
[ceph: root@ceph-node-0 /]# 

```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-12-13 06:37 UTC, ShwetaBhosale1 commented
jenkins test api

2024-12-13 06:37 UTC, ShwetaBhosale1 commented
jenkins test docs

2025-01-08 21:20 UTC, adk3798 approved these changes

2025-01-13 16:20 UTC, adk3798 requested changes

2025-01-13 16:20 UTC, adk3798 commented on src/pybind/ceph_argparse.py
> +                        raise ArgumentError(f"Duplicate argument '{kwarg_desc.name}' found.")
@ShwetaBhosale1  it turns out some commands are expecting to be able to pass certain arguments twice and this breaks that
```
2025-01-10T09:18:56.670 DEBUG:teuthology.orchestra.run.smithi111:> sudo /home/ubuntu/cephtest/cephadm --image quay-quay-quay.apps.os.sepia.ceph.com/ceph-ci/ceph:65aa7a1c767c33f05c64364bd94b41cdc712155a shell -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --fsid 30ab323a-cf33-11ef-9d61-a94da4efb481 -- bash -c 'ceph smb cluster create modusr1 user --define-user-pass=user1%t3stP4ss1 --define-user-pass=user2%t3stP4ss2 --placement=count:1
2025-01-10T09:18:56.671 DEBUG:teuthology.orchestra.run.smithi111:> '
2025-01-10T09:18:56.926 INFO:teuthology.orchestra.run.smithi111.stderr:Inferring config /var/lib/ceph/30ab323a-cf33-11ef-9d61-a94da4efb481/mon.a/config
2025-01-10T09:18:57.035 INFO:journalctl@ceph.mon.a.smithi111.stdout:Jan 10 09:18:56 smithi111 ceph-mon[29075]: pgmap v13: 97 pgs: 97 active+clean; 646 KiB data, 58 MiB used, 179 GiB / 179 GiB avail; 16 KiB/s rd, 654 B/s wr, 7 op/s
2025-01-10T09:18:57.739 INFO:teuthology.orchestra.run.smithi111.stderr:Invalid command: Duplicate argument 'define_user_pass' found.
2025-01-10T09:18:57.740 INFO:teuthology.orchestra.run.smithi111.stderr:smb cluster create <cluster_id> <auth_mode:user|active-directory> [<domain_realm>] [<domain_join_ref>...] [<domain_join_user_pass>...] [<user_group_ref>...] [<define_user_pass>...] [<custom_dns>...] [<placement>] [<clustering:default|always|never>] [<public_addrs>...] [--format <value>] :  Create an smb cluster
2025-01-10T09:18:57.740 INFO:teuthology.orchestra.run.smithi111.stderr:Error EINVAL: invalid command
```
this `ceph smb cluster create` command actually should be able to pass `--define-user-pass` multiple times. There are probably other examples of this, but that's what we happened to hit in the test run
https://pulpito.ceph.com/adking-2025-01-10_07:24:29-orch:cephadm-wip-adk-testing-2025-01-09-1901-distro-default-smithi/8070280

2025-01-15 06:39 UTC, ShwetaBhosale1 commented on src/pybind/ceph_argparse.py
> +                        raise ArgumentError(f"Duplicate argument '{kwarg_desc.name}' found.")
@adk3798 Updated the code, moved that check to store_arg function.

Testing logs:
```
[ceph: root@ceph-node-0 /]# ceph orch apply prometheus 'ceph-node-0' --placement ceph-node-1
Invalid command: Duplicate argument 'placement' found.
orch apply [<service_type:mon|mgr|rbd-mirror|cephfs-mirror|crash|alertmanager|grafana|node-exporter|ceph-exporter|prometheus|loki|promtail|mds|rgw|nfs|iscsi|nvmeof|snmp-gateway|elasticsearch|jaeger-agent|jaeger-collector|jaeger-query>] [<placement>] [--dry-run] [--format {plain|json|json-pretty|yaml|xml-pretty|xml}] [--unmanaged] [--no-overwrite] [--continue-on-error] :  Update the size or placement for a service or apply a large yaml spec
Error EINVAL: invalid command
[ceph: root@ceph-node-0 /]# 


[ceph: root@ceph-node-0 /]# ceph orch apply prometheus 'ceph-node-0'                        
Scheduled prometheus update...
[ceph: root@ceph-node-0 /]# ceph orch apply prometheus --placement ceph-node-1
Scheduled prometheus update...
[ceph: root@ceph-node-0 /]# 

```
```
[ceph: root@ceph-node-0 /]# ceph smb cluster create modusr1 user --define-user-pass=user1%t3stP4ss1 --define-user-pass=user2%t3stP4ss2 --placement=1
{
  "resource": {
    "resource_type": "ceph.smb.cluster",
    "cluster_id": "modusr1",
    "auth_mode": "user",
    "intent": "present",
    "user_group_settings": [
      {
        "source_type": "resource",
        "ref": "modusr1qjpqsycq"
      }
    ],
    "placement": {
      "count": 1
    },
    "public_addrs": []
  },
  "state": "created",
  "additional_results": [
    {
      "resource": {
        "resource_type": "ceph.smb.usersgroups",
        "users_groups_id": "modusr1qjpqsycq",
        "intent": "present",
        "values": {
          "users": [
            {
              "name": "user1",
              "password": "t3stP4ss1"
            },
            {
              "name": "user2",
              "password": "t3stP4ss2"
            }
          ],
          "groups": []
        },
        "linked_to_cluster": "modusr1"
      },
      "state": "created",
      "success": true
    }
  ],
  "success": true
}
[ceph: root@ceph-node-0 /]# 

```

2025-01-15 10:42 UTC, ShwetaBhosale1 commented
jenkins test api

2025-01-15 15:59 UTC, adk3798 commented on src/pybind/ceph_argparse.py
> +                        raise ArgumentError(f"Duplicate argument '{kwarg_desc.name}' found.")
alright, I'll include this in my next test run and see how it goes

2025-01-16 04:41 UTC, ShwetaBhosale1 commented on src/pybind/ceph_argparse.py
> +                        raise ArgumentError(f"Duplicate argument '{kwarg_desc.name}' found.")
Sure, Thanks!

2025-01-23 19:16 UTC, adk3798 commented
original run: https://pulpito.ceph.com/adking-2025-01-16_05:45:12-orch:cephadm-wip-adk-testing-2025-01-15-1705-distro-default-smithi/

reruns: https://pulpito.ceph.com/adking-2025-01-16_15:09:00-orch:cephadm-wip-adk-testing-2025-01-15-1705-distro-default-smithi/

After reruns, I only saw known issues. There is still the problem of the test_nfs task failing, which would make me hesitant to merge nfs related PRs, but otherwise it was okay.

---

For this particular PR I'm going to hold off merging for now and put it through a couple other suites since 1) the issue being fixed isn't ciritical and 2) this is touching a particularly sensitive (and barely maintained) area. Regardless it's good to see the failure from before not showing up anymore.

2025-07-01 13:55 UTC, adk3798 commented
https://pulpito.ceph.com/adking-2025-06-25_15:21:10-orch:cephadm-wip-adk-testing-2025-06-24-1732-distro-default-smithi/

okay for merging other than unexpected monitoring stack test failure

2025-07-02 04:48 UTC, ShwetaBhosale1 commented
jenkins test make check arm64

2025-07-03 08:45 UTC, ShwetaBhosale1 commented
jenkins test make check arm64

2025-07-15 13:54 UTC, adk3798 commented
https://pulpito.ceph.com/adking-2025-07-10_14:21:16-orch:cephadm-wip-adk-testing-2025-07-09-1123-distro-default-smithi/

2025-07-15 13:56 UTC, merged