squid: workunit/dencoder: dencoder test forward incompat fix
ceph/ceph pull request #61011
Opened 2024-12-10 06:45 UTC by NitzanMordhai

backport tracker: https://tracker.ceph.com/issues/69165

---

backport of https://github.com/ceph/ceph/pull/58961
parent tracker: https://tracker.ceph.com/issues/67263

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

2025-02-10 19:12 UTC, rzarzynski requested changes

2025-02-10 19:12 UTC, rzarzynski commented on qa/workunits/dencoder/test_readable.py
> +#!/usr/bin/env python3
Is anobody spawning this script? In `main` there is:

```
$ grep -r  test_readable ../qa
../qa/workunits/dencoder/test-dencoder.sh:$mydir/test_readable.py $CEPH_MNT/client.0/tmp/ceph-object-corpus-master
```

2025-02-11 08:40 UTC, NitzanMordhai commented on qa/workunits/dencoder/test_readable.py
> +#!/usr/bin/env python3
@rzarzynski i'm missed a backport of the test into reef and squid. (https://github.com/ceph/ceph/pull/56743)
I'm going to add it here

2025-02-12 16:26 UTC, rzarzynski approved these changes

2025-02-12 16:26 UTC, rzarzynski commented on qa/workunits/dencoder/test-dencoder.sh
> +$mydir/test_readable.py $CEPH_MNT/client.0/tmp/ceph-object-corpus-master
ACK.

2025-02-19 13:26 UTC, NitzanMordhai commented
jenkins test make check

2025-03-04 12:07 UTC, merged