cephfs_mirror: update entry_path as alias
ceph/ceph pull request #61041
Opened 2024-12-11 11:52 UTC by joscollin

Both snapshot_path and entry_path are the same. So create an alias for the convenient use of entry_path

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2024-12-11 13:04 UTC, joscollin commented
jenkins test api

2025-02-03 12:10 UTC, vshankar requested changes
493312768c138c5a3c32841bee15d00fbd74ad51 looks fine though.

2025-02-03 12:10 UTC, vshankar commented on src/tools/cephfs_mirror/PeerReplayer.cc
> +auto entry_path = snapshot_path;
No, snapshot_path uses `client_snapdir` which entry_path doesn't.

2025-02-04 04:49 UTC, joscollin commented on src/tools/cephfs_mirror/PeerReplayer.cc
> +auto entry_path = snapshot_path;
I was mentioning about [this](https://github.com/ceph/ceph/blame/main/src/tools/cephfs_mirror/PeerReplayer.cc#L59-L61) overload of snapshot_path. This function and `entry_path` are the same.

2025-02-10 08:33 UTC, vshankar commented on src/tools/cephfs_mirror/PeerReplayer.cc
> +auto entry_path = snapshot_path;
OK, I would still want to leave it as separate routines even if the implementation is same. This is so that its clear when invoking the helper as to what is being achieved and maybe the implementation of either of the two could change somewhere along.

2025-02-10 10:02 UTC, closed without merging