libcephfs: New feature - add ceph_setlk and ceph_getlk functions
ceph/ceph pull request #61116
Opened 2024-12-17 14:37 UTC by geokapp

This PR extends the Ceph Client and the libcephfs library with high-level functions that perform record locking. Those functions work on file descriptors rather than on file handles as the low-level functions, ceph_ll_setlk and ceph_ll_getlk, do.

Fixes: https://tracker.ceph.com/issues/69277
Signed-off-by: Giorgos Kappes <giorgos@giorgoskappes.com

2025-07-08 17:37 UTC, batrick approved these changes

2025-07-08 17:44 UTC, batrick approved these changes
Otherwise LGTM. Great job on the tests!

2025-07-08 17:44 UTC, batrick commented on .mailmap
> +Giorgos Kappes <giorgos@polytropo.io> <giorgos@giorgoskappes.com>
nit: I would have preferred these updates in a separate commit.

2025-07-21 15:44 UTC, vshankar commented on .mailmap
> +Giorgos Kappes <giorgos@polytropo.io> <giorgos@giorgoskappes.com>
@geokapp ping?

2025-07-22 05:41 UTC, vshankar commented
jenkins retest this please

2025-07-22 05:55 UTC, vshankar commented on src/libcephfs.cc
> +    return -CEPHFS_ENOTCONN;
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/libcephfs.cc:1412:13: error: use of undeclared identifier 'CEPHFS_ENOTCONN'
 1412 |     return -CEPHFS_ENOTCONN;
      |             ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/libcephfs.cc:1420:13: error: use of undeclared identifier 'CEPHFS_ENOTCONN'
 1420 |     return -CEPHFS_ENOTCONN;
```

Ceph has moved away from CEPHFS_* errno's.

2025-07-22 05:55 UTC, vshankar requested changes
@geokapp PTAL

2025-07-22 14:30 UTC, geokapp commented on src/libcephfs.cc
> +    return -CEPHFS_ENOTCONN;
Hi all,

I’ve performed a rebase and updated the branch to split the commits as suggested and fixed the errno constants to follow the latest Ceph conventions. Please let me know if you have any further feedback.

2025-07-23 11:26 UTC, vshankar commented on src/libcephfs.cc
> +    return -CEPHFS_ENOTCONN;
Sue. Thanks @geokapp . I will have a look.

2025-07-28 13:20 UTC, vshankar commented
jenkins test windows

2025-08-05 12:50 UTC, vshankar commented
jenkins test windows

2025-08-06 03:14 UTC, vshankar commented
We have a windows build failure: https://jenkins.ceph.com/job/ceph-windows-pull-requests/64461/consoleFull#10521527942a811ea2-3e7b-466b-84b4-d13df7e35809

```
/home/ubuntu/ceph/src/test/libcephfs/recordlock_hl.cc:109:14: error: use of undeclared identifier 'CEPHFS_EAGAIN'
  ASSERT_EQ(-CEPHFS_EAGAIN, ceph_setlk(cmount, fd, &lock2, 43, false));
```

That source is still using CEPHFS>* errno.

2025-08-06 10:16 UTC, geokapp commented
> We have a windows build failure: https://jenkins.ceph.com/job/ceph-windows-pull-requests/64461/consoleFull#10521527942a811ea2-3e7b-466b-84b4-d13df7e35809
> 
> ```
> /home/ubuntu/ceph/src/test/libcephfs/recordlock_hl.cc:109:14: error: use of undeclared identifier 'CEPHFS_EAGAIN'
>   ASSERT_EQ(-CEPHFS_EAGAIN, ceph_setlk(cmount, fd, &lock2, 43, false));
> ```
> 
> That source is still using CEPHFS>* errno.

Fixed it.

2025-08-06 10:25 UTC, vshankar commented
> Fixed it.

Thank you. Will run this change through tests.

2025-08-06 11:43 UTC, vshankar commented
This PR is under test in [https://tracker.ceph.com/issues/72445](https://tracker.ceph.com/issues/72445).

2025-08-11 06:50 UTC, vshankar approved these changes
https://tracker.ceph.com/projects/cephfs/wiki/QA_main_2025#wip-vshankar-testing-20250806114233-debug

2025-08-11 06:53 UTC, merged