mgr: Add performance counters support for modules
ceph/ceph pull request #61131
Opened 2024-12-18 13:28 UTC by NitzanMordhai

This commit introduces perf counters to MGR modules,
These counters provide valuable insights into the behavior
and performance of individual modules, aiding in debugging,
optimization, monitoring and identify issues.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2025-06-26 09:27 UTC, NitzanMordhai commented
i made some changes to the PR, I removed the memory and CPU since it didn't show correct results

2025-09-17 14:29 UTC, anthonyeleven reviewed
docs suggestions

2025-09-17 14:29 UTC, anthonyeleven commented on doc/mgr/administrator.rst
> +The mgr includes a ThreadMonitor that tracks CPU usage and memory consumption
s/mgr/Manager/

2025-09-17 14:29 UTC, anthonyeleven commented on doc/mgr/administrator.rst
> +``ceph config set mgr mgr_module_monitor_interval <seconds>``, where seconds
\`\`seconds\`\`

2025-09-17 14:29 UTC, anthonyeleven commented on doc/mgr/administrator.rst
> +The ThreadMonitor provides per-module performance counters accessible via
the admin socket with

2026-01-27 16:41 UTC, rzarzynski commented
jenkins retest this please

2026-01-27 17:12 UTC, rzarzynski reviewed
Overall LGTM; please see comments.

2026-01-27 17:12 UTC, rzarzynski commented on doc/mgr/administrator.rst
> +- ``cpu_usage``: CPU percentage for the main module thread
Reading the doc for the first time (without looking into the code yet), facing the question: how does it work?

2026-01-27 17:12 UTC, rzarzynski commented on src/mgr/ActivePyModules.cc
> +ActivePyModules::~ActivePyModules() {
```suggestion
ActivePyModules::~ActivePyModules()
{
```

2026-01-27 17:12 UTC, rzarzynski commented on src/mgr/PyModuleRegistry.h
> +  { thread_monitor = std::make_unique<ThreadMonitor>(g_ceph_context); }
Why not to use the initializer list?

2026-01-27 17:12 UTC, rzarzynski commented on src/mgr/PyModuleRunner.cc
> -  dout(4) << "Entering thread for " << mod->get_name() << dendl;
Is there a good reason for removing the dout entry?

2026-01-27 17:12 UTC, rzarzynski commented on src/mgr/ThreadMonitor.cc
> +  monitored_threads[thread_id] = info;
Is there a possibility of race conditions here if an operating system reuses the TID (e.g. new thread created & registered, old – with the same TID – deregistered later)?

2026-01-27 17:12 UTC, rzarzynski commented on src/mgr/ThreadMonitor.cc
> +      stop_monitoring();
ACK.

2026-01-27 17:12 UTC, rzarzynski commented on src/mgr/ThreadMonitor.cc
> +      MonitoredThreadInfo& Info_thread = pair.second;
Let's use the C++17's structured bindings for that.

2026-01-27 17:12 UTC, rzarzynski commented on src/mgr/ThreadMonitor.cc
> +  if (elapsed_seconds <= 0) return 0.0;
No need to be cheap on newlines.

2026-03-05 10:19 UTC, rzarzynski commented
jenkins test make check

2026-03-05 10:19 UTC, rzarzynski commented
jenkins test make api

2026-04-14 06:37 UTC, NitzanMordhai commented on doc/mgr/administrator.rst
> +- ``cpu_usage``: CPU percentage for the main module thread
You have a few lines above that:
"The ThreadMonitor provides per-module performance counters accessible via
``ceph daemon mgr.${MGRNAME} perf dump``, including:"

Is that enough?

2026-04-14 06:47 UTC, NitzanMordhai commented on src/mgr/PyModuleRunner.cc
> -  dout(4) << "Entering thread for " << mod->get_name() << dendl;
No, reverting that

2026-04-14 08:01 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +  monitored_threads[thread_id] = info;
Good point! I'll guard it with deregister_thread  - I'll release the tid only if it belongs to that module by its name

2026-04-14 09:52 UTC, NitzanMordhai commented
@rzarzynski, I made the changes. There was also an issue with locks in the monitoring_loop that i needed to fix

2026-04-15 17:21 UTC, sseshasa requested changes
Had a few general comments in the first pass. I will review it more in-depth.

2026-04-15 17:21 UTC, sseshasa commented on src/common/Finisher.h
> +  std::future<void>  started_future;
Doxygen comments for the new members would be very helpful.

2026-04-15 17:21 UTC, sseshasa commented on ThreadMonitor.h
This file appears to be a leftover and can be removed.

2026-04-15 17:21 UTC, sseshasa commented on src/common/options/mgr.yaml.in
> +    each enabled module. If set to 0, collection of these stats will be disabled.
Is the `desc` field complete?  Also, for the long description, do we want to mention ThreadMonitor? Since this is an internal implementation detail, we can replace it with a generic term, for e.g., Manager Monitor. What do you think?

```suggestion
  desc: Period in seconds for collecting Manager modules cpu and memory performance counters.
  long_desc: Period in seconds for Manager Monitor to collect the cpu and memory for 
    each enabled module. If set to 0, collection of these stats will be disabled.
```

2026-04-16 16:03 UTC, sseshasa requested changes
Added a few more comments. Will continue the review.

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +#include <unistd.h>
This can be moved to  `ThreadMonitor.h` as it uses functions exposed by it.

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +#include <sys/syscall.h>
Is this include required?

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> +  std::mutex monitored_threads_mutex;
Could be useful to have a shorthand like below and use it where necessary:

```suggestion
  std::mutex monitored_threads_mutex;
  using ThreadMonGuard = std::lock_guard<decltype(monitored_threads_mutex)>;
```

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> +  ceph::mono_clock::duration monitoring_interval = std::chrono::seconds(2);
This must additionally be initialized to the default value of `mgr_module_monitor_interval` as part of the `ThreadMonitor` constructor.

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +    dout(5) << "Failed to retrieve system configuration"
Would it be better to log this using `derr` here?

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +  MonitoredThreadInfo info;
On successful registration, log the TID and the thread name. I think `dout(0)` would be okay since we log it once during start-up.

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +    dout(20) << "Deregistering thread: '" << it->second.name << "' (TID: " << thread_id << ")" << dendl;
Can this be logged at `dout(0)` level as this can only happen in error cases?

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +      dout(5) << "Failed to read process memory info from /proc/self/statm." << dendl;
Log using `derr`?

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +      for (auto& [tid, Info_thread] : monitored_threads) {
The name `Info_thread` doesn't satisfy the Ceph naming guidelines. `thread_info` seems better.

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +bool ThreadMonitor::process_main_thread(pid_t monitored_tid) {
The `ThreadMonitor::monitoring_loop()` releases the `monitored_threads_mutex` lock before calling this method. If another thread calls deregister/register at the exact same moment, the find() or the subsequent data access, then this could result in a race or crash.

2026-04-16 16:03 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +  auto it = monitored_threads.find(monitored_tid);
The same race or crash issue can happen here since the mutex lock is not held.

2026-04-20 06:49 UTC, sseshasa reviewed
Added a few comments around the main monitoring loop. Will continue the review based on the outcome of existing comments.

2026-04-20 06:49 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +void ThreadMonitor::deregister_thread(pid_t thread_id, const std::string& module_name) {
`module_name` can be `std::string_view` here since it's only used for comparison.

2026-04-20 06:49 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +      }
`process_main_thread()` and `process_serve_thread()` can probably be consolidated into a single method and behave based on whether `serve_tid` is valid for e.g. `bool process_thread_stats(pid_t monitored_tid, pid_t serve_tid = -1)`.

2026-04-20 06:49 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +    if (!serve_threads_to_remove.empty()) {
To ensure that the monitoring loop only performs tasks related to monitoring, can the cleanup tasks namely clearing out `serve_threads_to_remove` and `threads_to_remove` (using `deregister_thread()` be moved to a separate cleanup Finisher thread? The items to clean can be invalidated within the `monitored_threads` map by marking them 'stale` by introducing a new member which conveys one of [VALID, MT_INVALID, ST_INVALID] within the `MonitoredThreadInfo` struct, where,

VALID - both main and serve thread are valid
MT_INVALID - main thread is invalid,
ST_INVALID - serve thread is invalid.

While the main monitoring loop only works with the valid entries, the 
cleanup thread can work with the enties in  `threads_to_remove` and `serve_threads_to_remove`.

May be there could be other approaches to keep monitoring and cleanup tasks separate to ensure that the monitoring loop is not doing too many things under the mutex lock.

2026-04-23 11:38 UTC, NitzanMordhai commented on src/common/Finisher.h
> +  std::future<void>  started_future;
Adding

2026-04-23 12:19 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +#include <sys/syscall.h>
Added while i was working on the change, and they are no longer needed. removing few of them

2026-04-23 12:24 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.h
> +  std::mutex monitored_threads_mutex;
I'm prefer to keep it that way, it always look to massy to re-add the mutex again and again anyway

2026-04-23 13:41 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.h
> +  ceph::mono_clock::duration monitoring_interval = std::chrono::seconds(2);
added to the constructor!

2026-04-23 13:43 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +    dout(5) << "Failed to retrieve system configuration"
with -1 isn't it too aggressive?

2026-04-23 13:46 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +      dout(5) << "Failed to read process memory info from /proc/self/statm." << dendl;
See above, i think it's too aggressive

2026-04-23 13:54 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +  auto it = monitored_threads.find(monitored_tid);
rework it

2026-04-23 13:54 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +bool ThreadMonitor::process_main_thread(pid_t monitored_tid) {
let me rework it

2026-04-23 14:12 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +      }
i made some changes to that area because of changing the locks

2026-04-23 14:16 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +    if (!serve_threads_to_remove.empty()) {
the restructure of the locks already addressed it

2026-04-28 14:37 UTC, sseshasa requested changes
@NitzanMordhai I did another pass over this PR and added a few comments. PTAL.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +#include "ThreadMonitor.h"
Both `ThreadMonitor.h/cc` need to include the copyright header text.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> +#pragma once
Include the copyright header text.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> +  std::mutex monitored_threads_mutex;
Couple of reasons why I suggested the above are:
1. Less text to type
2. If the type of lock is changed, then changing it in one place is easier vs in all  places where it's declared.

But I will leave it up to you.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> +    m_page_size = sysconf(_SC_PAGESIZE);
Wouldn't it be safe to include `unistd.h` for setting up clock ticks and page size?

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +    dout(5) << "Failed to retrieve system configuration"
I see that you have changed it to `derr`. Since this is an abnormal condition, I'd say `derr` makes sense before bailing out of the loop.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +  size_t end = line.find(')', start);
Would it be safer to use `rfind(')',...)` in case the thread name itself contains parenthesis? If this is not possible, then please ignore the comment.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +  for (int i = 0; i < 11; ++i) {  // Changed from 11 to 12
Is the comment valid? Looks like skipping 11 fields is correct. If so, the comments can be amended to reflect the correct number of fields to skip.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +void ThreadMonitor::deregister_thread(pid_t thread_id, const std::string_view module_name) {
Looks like `deregister_thread()` is no longer used in which case the method can be removed.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +      derr << "Failed to read process memory info from /proc/self/statm." << dendl;
On error, shouldn't the monitoring loop stop monitoring and bail out?

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ActivePyModules.cc
> -
Is this removal intentional? If so, it may be moved to a separate commit or a separate re-factor.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ActivePyModules.cc
> -        << active_module->get_fin_thread_name() << dendl;
Is the log removal necessary? Can be retained if useful?

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/ActivePyModules.cc
> +      if (fut.wait_for(std::chrono::milliseconds(100)) == std::future_status::ready) {
Is the finisher guaranteed to start in 100 msecs? Does this need extra handling if it doesn't?

I think the alternatives are:
a) wait indefinitely until the promise is fullfilled, or,
b) wait_for() a much longer time after which a timeout very likely indicates an issue with the thread.

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/MgrStandby.h
> +  void update_active_module_perf_counters() const;
I don't see this defined anywhere?

2026-04-28 14:37 UTC, sseshasa commented on src/mgr/PyModuleRunner.cc
> -
Ditto with respect my previous comment on removing a line.

2026-04-29 13:05 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +  size_t end = line.find(')', start);
yep, changing

2026-04-29 13:11 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +  for (int i = 0; i < 11; ++i) {  // Changed from 11 to 12
right, need to remove that comment, or update it

2026-04-29 13:19 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +void ThreadMonitor::deregister_thread(pid_t thread_id, const std::string_view module_name) {
right, we already have stop_monitoring() that will do the cleanup, i will remove it

2026-04-29 13:23 UTC, NitzanMordhai commented on src/mgr/ThreadMonitor.cc
> +      derr << "Failed to read process memory info from /proc/self/statm." << dendl;
i think it will be to aggressive, it could be that we couldn't open the file, and we will be able to open it on our next round

2026-04-29 13:25 UTC, NitzanMordhai commented on src/mgr/ActivePyModules.cc
> -
no, re-adding it

2026-04-29 13:34 UTC, NitzanMordhai commented on src/mgr/ActivePyModules.cc
> -        << active_module->get_fin_thread_name() << dendl;
we have new logs in register_thread so those log are no longer needed

2026-04-29 13:46 UTC, NitzanMordhai commented on src/mgr/ActivePyModules.cc
> +      if (fut.wait_for(std::chrono::milliseconds(100)) == std::future_status::ready) {
good catch, will wait for the promise to be complete

2026-04-29 13:47 UTC, NitzanMordhai commented on src/mgr/MgrStandby.h
> +  void update_active_module_perf_counters() const;
oh, missed that one.

2026-04-29 14:28 UTC, NitzanMordhai commented
@sseshasa, please see my updates and answers! thanks

2026-04-29 15:43 UTC, sseshasa reviewed
Almost there. Added a few minor comments. PTAL. Thanks!

2026-04-29 15:43 UTC, sseshasa commented on src/mgr/MgrStandby.h
> -
This empty line needs to be reinstated.

2026-04-29 15:43 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> + * Copyright 2024 IBM Corporation
2026

2026-04-29 15:43 UTC, sseshasa commented on src/mgr/ThreadMonitor.cc
> +      derr << "Failed to read process memory info from /proc/self/statm." << dendl;
In that case, should there be a `continue;` after logging the derr? In case of failure, `process_rss_pages` won't be valid, correct?

2026-04-29 15:43 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> + * Copyright 2024 IBM Corporation
2026

2026-04-29 15:43 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> +#include <unistd.h>
minor nit: The includes from standard libraries should come first, followed by common/* and then the rest.

2026-04-30 09:43 UTC, sseshasa approved these changes
LGTM. A lingering minor nit.

2026-04-30 09:43 UTC, sseshasa commented on src/mgr/ThreadMonitor.h
> +#include "common/debug.h"
I meant the following as I see this convention being followed in other places,

```suggestion
#include <unistd.h>$

#include "common/debug.h"
#include "PyModule.h"
```

2026-05-25 07:50 UTC, NitzanMordhai commented
Test /a/skanta-2026-05-08_15:03:45-rados-wip-bharath17-testing-2026-05-08-0400-distro-default-trial/199166/teuthology.log faile with:
`2026-05-08T15:17:25.107 INFO:teuthology.orchestra.run.trial030.stderr:available_objects: 1001 in_flight_objects: 2 total objects: 1003 in_flight 2
2026-05-08T15:17:25.297 INFO:teuthology.orchestra.run.trial030.stderr:terminate called after throwing an instance of 'std::future_error'
2026-05-08T15:17:25.297 INFO:teuthology.orchestra.run.trial030.stderr:  what():  std::future_error: Future already retrieved
2026-05-08T15:17:25.297 INFO:teuthology.orchestra.run.trial030.stderr:*** Caught signal (Aborted) **
2026-05-08T15:17:25.297 INFO:teuthology.orchestra.run.trial030.stderr: in thread 7f2c15633c00 thread_name:ceph_test_objec
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: ceph version 21.0.0-1200-g95e8a733 (95e8a733c5a4b7b16e287d28a4315a3ed511282d) umbrella (dev - RelWithDebInfo)
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 1: /lib64/libc.so.6(+0x3fc30) [0x7f2c13a3fc30]
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 2: /lib64/libc.so.6(+0x8d03c) [0x7f2c13a8d03c]
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 3: raise()
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 4: abort()
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 5: /lib64/libstdc++.so.6(+0xa1b21) [0x7f2c154a1b21]
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 6: /lib64/libstdc++.so.6(+0xad53c) [0x7f2c154ad53c]
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 7: /lib64/libstdc++.so.6(+0xad5a7) [0x7f2c154ad5a7]
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 8: /lib64/libstdc++.so.6(+0xad809) [0x7f2c154ad809]
2026-05-08T15:17:25.298 INFO:teuthology.orchestra.run.trial030.stderr: 9: (std::__throw_future_error(int)+0x3f) [0x7f2c154a475b]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 10: (Finisher::start()+0x184) [0x7f2c146a36d4]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 11: (BlueStore::_kv_start()+0x38) [0x885d08]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 12: (BlueStore::_fsck(BlueStore::FSCKDepth, bool)+0x2e8) [0x85c4d8]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 13: ceph_test_objectstore() [0x6b4bc2]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 14: (StoreTestBase::doSyntheticTest(int, int, unsigned long, unsigned long, unsigned long)+0x585) [0x6b9c15]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 15: (testing::Test::Run()+0xe3) [0x961963]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 16: (testing::TestInfo::Run()+0x41d) [0x961e1d]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 17: ceph_test_objectstore() [0x986043]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 18: (testing::internal::UnitTestImpl::RunAllTests()+0x58f) [0x97bd7f]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 19: (testing::UnitTest::Run()+0x8a) [0x9790fa]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 20: main()
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 21: /lib64/libc.so.6(+0x2a610) [0x7f2c13a2a610]
2026-05-08T15:17:25.299 INFO:teuthology.orchestra.run.trial030.stderr: 22: __libc_start_main()
2026-05-08T15:17:25.300 INFO:teuthology.orchestra.run.trial030.stderr: 23: _start()
`
fixed in the PR

2026-05-26 09:28 UTC, NitzanMordhai commented
Rados approved https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues76482

2026-05-26 09:31 UTC, merged