[docs] : Updated about Vstart in the readme file
ceph/ceph pull request #61142
Opened 2024-12-19 04:01 UTC by Dedsec0098

doc: Gave more details about tips and tricks and troubleshooting for Vstsrt in the readme file.

2024-12-19 09:12 UTC, zdover23 requested changes

2024-12-19 09:12 UTC, zdover23 commented on README.md
> +    >Preserve Existing Data skip cluster reinitialization between tests by using the `-n` flag
Line 141 should be rewritten as a sentence.

2024-12-19 09:12 UTC, zdover23 commented on README.md
> +    >Cluster in a Health Error State: Run ceph status to identify the issue.
"ceph status" should be in backticks.

2024-12-19 09:13 UTC, zdover23 commented on README.md
> +    >Preserve Existing Data skip cluster reinitialization between tests by using the `-n` flag
Line 139 should also be rewritten as a sentence.

2024-12-20 02:04 UTC, zdover23 commented
jenkins retest this please

2024-12-20 03:00 UTC, Dedsec0098 commented
Can you please elaborate on how can I fix this problem of test failing.

2024-12-20 14:50 UTC, zdover23 commented
> Can you please elaborate on how can I fix this problem of test failing.

Change the title of this PR to "doc: Update vstart section in readme.md". The "Signed-off-by" check expects the string "doc" at the beginning of the title. Use "git commit --amend" to achieve this.

I'll take a look at this tomorrow and fix it up if you haven't gotten to it by then.

2024-12-21 00:12 UTC, zdover23 commented
jenkins test make check

2024-12-21 00:12 UTC, zdover23 commented
jenkins test make check arm64

2024-12-21 00:41 UTC, zdover23 commented
jenkins test make check

2024-12-21 05:41 UTC, Dedsec0098 commented
I have done all the changes and also I have removed previous commits that were causing problems with the checks.

2024-12-21 08:12 UTC, zdover23 commented
jenkins retest this please

2024-12-21 09:00 UTC, zdover23 commented
> I have done all the changes and also I have removed previous commits that were causing problems with the checks.

This should be squashed down to a single commit with a title that begins with "doc:". I'll leave this to you for the next twelve hours, and then I'll make a go of it.

2024-12-26 11:53 UTC, zdover23 commented
jenkins test api

2024-12-27 10:10 UTC, zdover23 approved these changes
LGTM. I'll refine the English in a future PR.

2024-12-28 15:32 UTC, merged