cephadm: fence old ranks for SMB service
ceph/ceph pull request #61158
Opened 2024-12-20 16:03 UTC by avanthakkar

Fixes: https://tracker.ceph.com/issues/68512

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2025-01-06 15:45 UTC, phlogistonjohn commented on src/pybind/mgr/cephadm/services/smb.py
> +                        self.mgr.spec_store.save_rank_map(spec.service_name(), rank_map)
Just to capture I comment I had in a meeting:
Because this code is so similar to what nfs is doing, and the fact that the system adds things to the rank map outside of the `CephService` subclasses I think we should, in the future, refactor this part of the rank map management.

We can probably replace the `fence_old_ranks` function with a common method in the base class (or elsewhere) and then provide hooks for the `run_grace_tool` method and the like for the service specific pieces. -- But this is all for a later cleanup effort IMO.

2025-01-06 15:46 UTC, phlogistonjohn commented
Do you plan on adding a new test to check for this specific behavior?

2025-01-07 12:52 UTC, avanthakkar commented
> Do you plan on adding a new test to check for this specific behavior?
Sure! Will try to add a test probably with placement count change and test if config gets updated

2025-01-10 15:59 UTC, phlogistonjohn approved these changes
LGTM

2025-01-10 16:00 UTC, phlogistonjohn commented
@adk3798 would you like to include this in one of your teuthology runs or should I plan to do a specific one for smb stuff?

2025-01-15 15:36 UTC, adk3798 requested changes

2025-01-15 15:36 UTC, adk3798 commented on qa/suites/orch/cephadm/smb/tasks/deploy_smb_ctdb_node_gone_state.yaml
> +      - jq '.[0].placement.count = 2' /tmp/smb_json > /tmp/smb_json_new
teuthology run https://pulpito.ceph.com/adking-2025-01-15_05:55:28-orch:cephadm-wip-athakkar-testing-2025-01-13-1635-distro-default-smithi/

There is only one relevant failure. The new test you're adding (https://pulpito.ceph.com/adking-2025-01-15_05:55:28-orch:cephadm-wip-athakkar-testing-2025-01-13-1635-distro-default-smithi/8077887/) fails with
```
teuthology.orchestra.run.smithi037.stderr:jq: error: Could not open file /tmp/smb_json: No such file or directory
```
after running
```
sudo /home/ubuntu/cephtest/cephadm --image quay-quay-quay.apps.os.sepia.ceph.com/ceph-ci/ceph:f3b6c2e0d8c57fd5e12a5b8ccba3082d1f50972c shell -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --fsid dbe431f2-d310-11ef-9d63-a94da4efb481 -- bash -c 'jq '"'"'.[0].placement.count = 2'"'"' /tmp/smb_json > /tmp/smb_json_new'
```
It looks like that /tmp/smb_json was meant to be made from
```
teuthology.orchestra.run.smithi037:> sudo /home/ubuntu/cephtest/cephadm --image quay-quay-quay.apps.os.sepia.ceph.com/ceph-ci/ceph:f3b6c2e0d8c57fd5e12a5b8ccba3082d1f50972c shell -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --fsid dbe431f2-d310-11ef-9d63-a94da4efb481 -- bash -c 'ceph orch ls --service-name smb.modusr1 --export --format json > /tmp/smb_json'
```
but I'm guessing since they're separate shells (when you directly run `cephadm shell <cmd>` it creates a container, runs the command from within the container, and then cleans it up) the file is created in a container, that container is removed and a new container that doesn't have the file is started where the `jq` command is run resulting in the failure we're seeing.

I think you might want to try following the format from https://github.com/ceph/ceph/blob/main/qa/suites/orch/cephadm/smoke-roleless/2-services/nfs-ingress.yaml#L58 (specifically the use of the `|` with a small bash script put after it) that should allow  multiple commands to be run inside a single cephadm shell instance.

2025-01-16 15:50 UTC, phlogistonjohn commented on qa/suites/orch/cephadm/smb/tasks/deploy_smb_ctdb_node_gone_state.yaml
> +      - jq '.[0].placement.count = 2' /tmp/smb_json > /tmp/smb_json_new
it seems reasonable to me. let's hope the test thinks so too :-)

2025-01-29 16:07 UTC, adk3798 commented
@avanthakkar Still saw a failurein the new test https://pulpito.ceph.com/adking-2025-01-28_03:55:09-orch:cephadm-wip-adk-testing-2025-01-27-1615-distro-default-smithi/8098459/. Failed with
```
Command failed on smithi018 with status 1: 'sudo TESTDIR=/home/ubuntu/cephtest bash -ex -c \'grep \'"\'"\'pnn:2 .*OK\'"\'"\' /tmp/ctdb_status\''
```
in both the original run and rerun

2025-02-13 08:14 UTC, avanthakkar commented
jenkins test api

2025-02-13 09:46 UTC, avanthakkar commented
jenkins test api

2025-02-18 09:43 UTC, avanthakkar commented
jenkins test api

2025-02-24 15:59 UTC, rkachach submitted a review, later dismissed
@avanthakkar recently (few weeks ago) the way deps are calculated have changed by the PR https://github.com/ceph/ceph/pull/60800/files. Now every service needs to define a method `get_dependencies` that returns its deps. You can see several examples in the `monitoring.py` file:

```
    @classmethod
    def get_dependencies(cls, mgr: "CephadmOrchestrator",
                         spec: Optional[ServiceSpec] = None,
                         daemon_type: Optional[str] = None) -> List[str]:
```

So even if your deps are very simple you will need to move the deps code to this new method.

2025-03-03 20:08 UTC, avanthakkar commented
jenkins test api

2025-03-03 21:55 UTC, avanthakkar commented
> @avanthakkar recently (few weeks ago) the way deps are calculated have changed by the PR https://github.com/ceph/ceph/pull/60800/files. Now every service needs to define a method `get_dependencies` that returns its deps. You can see several examples in the `monitoring.py` file:
> 
> ```
>     @classmethod
>     def get_dependencies(cls, mgr: "CephadmOrchestrator",
>                          spec: Optional[ServiceSpec] = None,
>                          daemon_type: Optional[str] = None) -> List[str]:
> ```
> 
> So even if your deps are very simple you will need to move the deps code to this new method.

Thanks! It seems atleast for this PR deps won't be required to be added, but will keep in mind for any future changes related to it

2025-03-04 19:09 UTC, avanthakkar commented
No failures in teuthology run : 
https://pulpito.ceph.com/avan-2025-03-04_14:43:33-orch:cephadm-wip-athakkar-testing-2025-03-04-1827-distro-default-smithi/

2025-03-04 19:12 UTC, adk3798 approved these changes

2025-03-04 19:13 UTC, merged