cephadm: Indicate orch is paused on executing operations
ceph/ceph pull request #61174
Opened 2024-12-24 11:11 UTC by Kushal-deb

cephadm: Indicate orch is paused on executing operations. 

This fix introduces a decorator, `check_orchestrator_paused`, to ensure that commands executed when the orchestrator is paused provide a clear warning to the user.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

2025-01-02 14:41 UTC, phlogistonjohn requested changes
I won't block this getting merged, but I will say that it's a bit ugly due to the "overuse" of HandleCommandResult  (and the subsequent string manipulations).  If cephadm were to adopt an approach of using more typical python workflows with (specific) exception types (an approach encouraged by the object formatter module) this could be much shorter and less ugly.

2025-01-02 14:41 UTC, phlogistonjohn commented on src/pybind/mgr/orchestrator/module.py
> +    @check_orchestrator_paused(get_status_func=lambda self, **kwargs: self._status(**kwargs))
I do object to this repeated lambda stuff. if you have to repeat this on nearly every invocation of your dectorator, build this into the decorator do not "spam" the codebase with it.

2025-01-03 06:30 UTC, Kushal-deb commented on src/pybind/mgr/orchestrator/module.py
> +    @check_orchestrator_paused(get_status_func=lambda self, **kwargs: self._status(**kwargs))
Removed it in the latest commit.

2025-01-03 06:37 UTC, Kushal-deb commented
> I won't block this getting merged, but I will say that it's a bit ugly due to the "overuse" of HandleCommandResult (and the subsequent string manipulations). If cephadm were to adopt an approach of using more typical python workflows with (specific) exception types (an approach encouraged by the object formatter module) this could be much shorter and less ugly.

Hi @phlogistonjohn,

Thank you for your earlier feedback! The current commit addresses your concern about the overuse of HandleCommandResult and the clutter caused by the repeated invocation of lambdas. 

I would, however, like to seek some clarification regarding the behavior when the orchestrator is paused. For example, in its current state, if we attempt to remove a service like crash (e.g., ceph orch rm crash), the system places it in a "deleting" state, and the removal is deferred until the orchestrator is resumed. In contrast, other commands like ceph orch daemon rm osd.6 --force don't exhibit this behavior—they immediately remove the daemon without deferring. Similarly, the ceph orch tuned-profile apply command also applies the changes directly, even when the orchestrator is paused. I've included relevant output snippets below to provide further context.

Given this inconsistency, would it be more appropriate to simplify the behavior by raising an exception when the orchestrator is paused and displaying a message like:
"Orchestrator is paused. Please try again after resuming the orchestrator."

Alternatively, should we aim to ensure consistency by deferring all such operations during the paused state? I’d appreciate your feedback on this approach, and I’m happy to iterate further based on your suggestions.

**Removing crash**
```
[ceph: root@ceph-node-0 ~]# ceph orch status
Backend: cephadm
Available: Yes
Paused: Yes

[ceph: root@ceph-node-0 ~]# ceph orch rm crash
Error EAGAIN: WARNING: The orchestrator is paused. The command is deferred for execution until orchestrator is resumed. 
Removed service crash

[ceph: root@ceph-node-0 ~]# ceph orch ls
NAME                       PORTS  RUNNING  REFRESHED   AGE  PLACEMENT  
crash                                 4/4  <deleting>  51m  *          
```

**Removing an OSD daemon:**

```
[ceph: root@ceph-node-0 ~]# ceph orch ps 
NAME                    HOST         PORTS        STATUS         REFRESHED  AGE  MEM USE  MEM LIM  VERSION                IMAGE ID      CONTAINER ID  
osd.0                   ceph-node-0               running (26h)    64s ago   2d    60.7M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  0b9d1256d028  
osd.1                   ceph-node-1               running (26h)    64s ago   2d    63.4M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  ba2a1dffefa7  
osd.2                   ceph-node-2               running (26h)    64s ago   2d    63.6M    1496M  19.3.0-6008-g60ae04d8  a8b4c1808756  449a16053d5f  
osd.3                   ceph-node-0               running (26h)    64s ago   2d    63.2M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  50aca0b19f7c  
osd.4                   ceph-node-1               running (26h)    64s ago   2d    60.3M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  1560f80ba29a  
osd.5                   ceph-node-2               running (26h)    64s ago   2d    60.5M    1496M  19.3.0-6008-g60ae04d8  a8b4c1808756  6354be288c00  
osd.6                   ceph-node-3               running (23h)    64s ago  23h    63.7M    2992M  19.3.0-6008-g60ae04d8  a8b4c1808756  020aa018ae78  

[ceph: root@ceph-node-0 ~]# ceph orch daemon rm osd.6 --force
Error EAGAIN: WARNING: The orchestrator is paused. The command is deferred for execution until orchestrator is resumed. 
Removed osd.6 from host 'ceph-node-3'

[ceph: root@ceph-node-0 ~]# ceph orch ps
NAME                    HOST         PORTS        STATUS         REFRESHED  AGE  MEM USE  MEM LIM  VERSION                IMAGE ID      CONTAINER ID  
osd.0                   ceph-node-0               running (26h)    94s ago   2d    60.7M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  0b9d1256d028  
osd.1                   ceph-node-1               running (26h)    94s ago   2d    63.4M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  ba2a1dffefa7  
osd.2                   ceph-node-2               running (26h)    94s ago   2d    63.6M    1496M  19.3.0-6008-g60ae04d8  a8b4c1808756  449a16053d5f  
osd.3                   ceph-node-0               running (26h)    94s ago   2d    63.2M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  50aca0b19f7c  
osd.4                   ceph-node-1               running (26h)    94s ago   2d    60.3M    4096M  19.3.0-6008-g60ae04d8  a8b4c1808756  1560f80ba29a  
osd.5                   ceph-node-2               running (26h)    94s ago   2d    60.5M    1496M  19.3.0-6008-g60ae04d8  a8b4c1808756  6354be288c00  

```
**Tuned-profile example:**
```
[ceph: root@ceph-node-0 ~]# ceph orch tuned-profile ls
profile_name: 23-mon-tuned-profile
placement: ceph-node-0;ceph-node-1
settings:
  vm.swappiness: 10
  vm.user_reserve_kbytes: 116851
---

[ceph: root@ceph-node-0 ~]# ceph orch tuned-profile apply -i tuned-profile.yaml 
Error EAGAIN: WARNING: The orchestrator is paused. The command is deferred for execution until orchestrator is resumed. 
Saved tuned profile 23-mon-tuned-profile

[ceph: root@ceph-node-0 ~]# ceph orch tuned-profile ls
profile_name: 23-mon-tuned-profile
placement: ceph-node-0;ceph-node-1
settings:
  vm.swappiness: 10
---

```
**Alternate implementation:**
```
[ceph: root@ceph-node-0 ~]# ceph orch rm crash
Error EAGAIN: WARNING: The orchestrator is paused. Please resume the orchestrator and try again.

[ceph: root@ceph-node-0 ~]# ceph orch resume
[ceph: root@ceph-node-0 ~]# ceph orch ls
NAME                       PORTS  RUNNING  REFRESHED  AGE  PLACEMENT  
crash                                 4/4  4s ago     38m  *          
mgr                                   2/2  3s ago     2d   count:2    
mon                                   4/5  4s ago     2d   count:5    
osd.all-available-devices               7  4s ago     2d   *      
```

2025-01-13 15:25 UTC, anthonyeleven commented on doc/cephadm/troubleshooting.rst
> +This behavior arises because these commands bypass the orchestrator's main serve loop and are not queued for asynchronous execution.
s/serve/working/

2025-01-13 15:25 UTC, anthonyeleven commented on doc/cephadm/troubleshooting.rst
> +example: removing a Daemon
Example: removing a daemon

2025-01-13 17:20 UTC, Kushal-deb commented on doc/cephadm/troubleshooting.rst
> +This behavior arises because these commands bypass the orchestrator's main serve loop and are not queued for asynchronous execution.
Adressed.

2025-01-13 17:21 UTC, Kushal-deb commented on doc/cephadm/troubleshooting.rst
> +example: removing a Daemon
Addressed

2025-02-07 18:49 UTC, adk3798 commented on doc/cephadm/troubleshooting.rst
> +   ceph orch tuned-profile apply
if we're going to put `tuned-profile apply` in this list, I think we should include the normal `orch apply`. Afaik, they're handled similarly. In both cases the spec will get stored, but we won't act on the spec until the orchestrator is unpaused. Given how important the regular apply command is to cephadm operations, it's worth mentioning.

2025-02-07 18:49 UTC, adk3798 commented on src/pybind/mgr/orchestrator/_interface.py
> +            return func(self, *args, **kwargs)
I don't feel like it's necessary to have this whole setup with result parsing for calling a function defined in another file in the same directory. If the reason this needs to be done is that `_status` has that `_cli_read_command` header on it and therefore can't be invoked directly, we could make the current `_status` into something of a stub function and move it's actual contents to another function that can be called from both there and here. That's all assuming we can't just call the `available` function the way `_status` already does here and then just do something like that function is already doing e.g.
```
avail, why, module_details = self.available()
result: Dict[str, Any] = {
    "available": avail,
    "backend": o,
}

if avail:
     result.update(module_details)
else:
     <indicate we don't know>
if 'paused' in result and result['paused']:
    <indicate is paused>
elif 'paused' in result:
    <indicate not paused>
else:
    <indicate we don't know>
```
worth noting in that example, both the "don't know" cases would also be "don't know" cases when invoking `_status` as we are here, since they use the same underlying mechanism.

2025-05-08 20:01 UTC, closed without merging